### ISSUE TITLE
Merge 2 Solutions in Powershell - like on Solution Components Mover - Dynamics 365 Onpremise

### ISSUE THREAD

**Issue by khawla-d** [MscrmTools/XrmToolBox#1000]
Hi,

I want to merge 2 CRM solutions in Powershell - like on Solution components Mover.

Is there any way to automatically run Solution Components Mover from a PS1 file ? a command line or a request

Thank you,

**Comment by MscrmTools** [comment]
No, sorry, there is no such possibility
