### ISSUE TITLE
How to change the time zone of Disabled Users in Dynamics CRM

### ISSUE THREAD

**Issue by ashutosh-DMI** [MscrmTools/XrmToolBox#1002]
I am trying to change the timezone of a disable user by using the tool user setting utility but it is not allowing to do it. However we were able to change the timezone of enabled users. 
Kindly suggest how it can be resolved.
![xrm error](https://user-images.githubusercontent.com/75967895/102046135-aa1ecf00-3e00-11eb-8637-0a8a390b9aef.PNG)

**Comment by MscrmTools** [comment]
This is a limitation of disabled users. So your only possibility is to reactivate users to update his settings, then disable it.
