### ISSUE TITLE
CrmServiceClient Support

### ISSUE THREAD

**Issue by AshV** [MscrmTools/XrmToolBox#1003]
**Is your feature request related to a problem? Please describe.**
Tried using new "CrmServiceClient" while developing new XrmToolBox plugin. By following below code. But it's  throwing Method Not Implemented Exception & Null Reference Exception.

```csharp
var conn = ConnectionDetail.GetCrmServiceClient(true);
```

**Describe the solution you'd like**
At the moment I am not very sure that "CrmServiceClient" is not supported, or my code is not correct.
If it's not supported please add it to "PluginControlBase", if it's already supported, please provide correct way to initialize it.

**Describe alternatives you've considered**
Alternative could be showing a login control again. Which doesn't seems appropriate.

**Additional context**
To be specific, I was trying to call "ExecuteCrmWebRequest" method in "CrmServiceClient".

**Comment by MscrmTools** [comment]
PluginCintrolBase has a property Service that is a CrmServiceClient. You should be able to use it.
If the method you are looking for is not there, try to use latest XrmToolBoxPackage Nuget package that references latest CRM sdk assemblies

**Comment by AshV** [comment]
It was because "System.Net.Http.dll" was missing while I was trying to execute "ExecuteCrmWebRequest()". It's working in my development machine now.
Thanks for your time & support.
