### ISSUE TITLE
[BUG] Help/Feedback/Donate menus don't work

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1004]
Clicking any of the Help/Feedback/Donate menu options for XTB or a tool and nothing happens 🤷‍♂️

![image](https://user-images.githubusercontent.com/2572253/103178112-4d032e80-4880-11eb-9b57-7ae456e98f88.png)

**Comment by MscrmTools** [comment]
ok... that is weird... events are still registered but it does not work indeed... Don't understand it right now...

**Comment by rappen** [comment]
Not entirely sure I'm looking in the right place, but the menu items don't seem to have any onclick event handler defined...

![image](https://user-images.githubusercontent.com/2572253/103548188-b2b97100-4ea5-11eb-865e-074138559dc5.png)

**Comment by MscrmTools** [comment]
ok, events are defined in ghost controls still in designer.cs but not used anymore... I thought removing them from UI should have deleted them from designer.cs but it seems not... Fixing it right now

**Comment by MscrmTools** [comment]
released

**Comment by rappen** [comment]
Tres bien!
