### ISSUE TITLE
[Question] Is it possible to make auto-open of the plugin when connecting to organization happen?

### ISSUE THREAD

**Issue by rafek1241** [MscrmTools/XrmToolBox#1013]
Is it possible to make auto-open of the plugin when connecting to organization happen or make a background task of specific plugin? 
I would like to create monitoring of the queries and when some rows were created I would like to inform the user about that.

**Comment by MscrmTools** [comment]
@rafek1241 not sure to understand the use case...

**Comment by rafek1241** [comment]
I want to create a monitoring plugin which would alert if some of statements returns records, for an example. I don't want to make it totally automatic - XRM toolbox is an entry point so when it's opened -> I would like to do the monitoring of statements on specific organization.

**Comment by MscrmTools** [comment]
Well, this is a bit inverting the current behavior where opening a tool will ask to select a connection.
It seems to be a specific use cas of your own but I'm not sure it will help others

**Comment by daryllabar** [comment]
We had talked once about allowing some sort of command line arguments, or maybe a config that would allow this functionality.  I can see it being helpful in a few niche situations, but I have no idea how difficult it would be to implement.
