### ISSUE TITLE
[BUG] Error while using Easy Translator

### ISSUE THREAD

**Issue by AhrimanSefid** [MscrmTools/XrmToolBox#1014]
I was translating a custom field in Opportunity. When I imported the file, i got this error:

---------------------------
Error
---------------------------
System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: The entity with a name = 'appmodulecomponent' was not found in the MetadataCache. (Fault Detail is equal to Exception details: 

ErrorCode: 0x80041102

Message: The entity with a name = 'appmodulecomponent' was not found in the MetadataCache.

TimeStamp: 2021-01-23T10:55:35.6278153Z

--

).
---------------------------
OK   
---------------------------

**Comment by MscrmTools** [comment]
Can you precise what is the version of the targeted environment?

**Comment by MscrmTools** [comment]
@AhrimanSefid can you answer my question?

**Comment by symvez** [comment]
I had this error with Easy Translator while exporting

**Error**: The entity with a name = 'appmodulecomponent' was not found in the MetadataCache. ErrorCode: 0x80041102

I solved the issue by unticking the option **Export SiteMap custom labels Translation** before exporting.

**Comment by MscrmTools** [comment]
@symvez , what is the version of the targeted organization?

**Comment by symvez** [comment]
Version 1.2021.4.15

**Comment by MscrmTools** [comment]
I'm talking about your organization, not the tool version

**Comment by symvez** [comment]
Microsoft Dynamics CRM 2016 (8.1.0.359)(DB 8.1.0.359)
