### ISSUE TITLE
Change language in dynamics crm

### ISSUE THREAD

**Issue by AhrimanSefid** [MscrmTools/XrmToolBox#1015]
Hi All,

How to change module name in dynamics crm, i am able to install french language but for some module it is still showing in English, please check below screenshot.

`https://community.dynamics.com/resized-image/__size/750x600/__key/communityserver-discussions-components-files/117/6204.language.PNG`

**Comment by MscrmTools** [comment]
I don't understand why you are posting a question on this repository whereas this is absolutely not related to XrmToolBox.

But, as I'm a nice guy, the answer is. Everything is tranlsated. It's just that "Service" and "Marketing" are the same term in French and in English
