### ISSUE TITLE
[BUG] incorrect message during the auto-update process

### ISSUE THREAD

**Issue by georged** [MscrmTools/XrmToolBox#1016]
**Describe the bug**
The message during the auto-update process includes `{0}` placeholder instead of the backup folder name, 

**Screenshots**
![image](https://user-images.githubusercontent.com/928254/105937697-2f58fd00-60aa-11eb-9866-77798d13ff08.png)

**Versions:**
 - XrmToolbox Version: 1.2021.1.44

**Comment by MscrmTools** [comment]
Thank you @georged. Unfortunately, the code seems ok to me but I will try to improve things there
