### ISSUE TITLE
Dynamics CRM: Entity Security Is not working

### ISSUE THREAD

**Issue by narottamdas** [MscrmTools/XrmToolBox#1017]
The "Entity Security" tool seems not working --- is there any other tool for a similar purpose -- to find out the users against a selected privilege?

---
- Deployment: Online
- DB Version: 9.2.21013.131
- Connection Controls Version: 1.2021.1.39
- XrmToolBox Version: 1.2021.1.44

**Comment by MscrmTools** [comment]
Privileges Discovery allows to find out what roles have specific privileges but it does not show you what users have these roles
