### ISSUE TITLE
It is possible to start two (and more) plugins for the same connection

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#102]
This issue become crucial after `MessageBus` implementation.

Currently it's possible to start more than one instance of the same plugin for the same connection. Nothing wrong this that. Might be a bit misleading, but ok.

But when `MessageBus` comes to the play, it should be able to connect to one of the plugin instances, and if there are more than one available, it leads to vagueness.

We cannot eliminate it completely, due to #26 as well, but we can prevent stupid cases, when 10+ instances are created just because user can do it.

----------------------------
I think we should add `MessageBox` that will ask user if he / she really wants to create new instance of the plugin, or it would be enough to switch to the tab with existing instance?

**Comment by MscrmTools** [comment]
That make sense
I know because I do it myself that it can be useful to have two instances of the same plugin with the same connection, like with WebResourceManager if I want to open two solutions, or if I want some kind of cache before I do some updates

**Comment by shytikov** [comment]
Yes, good example with `WebResourceManager`...

Can we assign plugin's instances some unique identifiers? Or any other concept?

In case of `Message Bus` maybe it's not that important which plugin instance to call (since it can always be new, fresh instance), but we should be able to return to correct instance among plugins with same name.

**Comment by MscrmTools** [comment]
Would it be enough if this unique identifier was handled by the user control? This is the only control that do not use Tag property yet and it seems the more convenient way to store this ID.

**Comment by MscrmTools** [comment]
Added a GUID as the pluginControl instance Tag. Hope that will help to manage the scenario you described
