### ISSUE TITLE
IE8

### ISSUE THREAD

**Issue by aizzik** [MscrmTools/XrmToolBox#1020]
hi,
I'm getting the "DOMParser is undefined" error 
when i try to start Ribbon Workbench. 
is it because i use IE 8 on my computer ?

---
- Deployment: Online
- DB Version: 9.2.21032.154
- Connection Controls Version: 1.2021.2.40
- XrmToolBox Version: 1.2021.2.45

**Comment by MscrmTools** [comment]
@scottdurow, can you help on this one?

**Comment by scottdurow** [comment]
The Ribbon Workbench needs IE11 or greater installed

**Comment by MscrmTools** [comment]
Thnak you for the answer @scottdurow
