### ISSUE TITLE
[BUG] Unable to Remove Connection File from the List

### ISSUE THREAD

**Issue by LinnZawWin** [MscrmTools/XrmToolBox#1022]
**Describe the bug**
No option to remove the Connection File from the dropdown list in "Select a connection" popup.

**To Reproduce**
- Click on Connect button from the menu.
- Create a new connection file from the dropdown menu
-  There is no option to remove the new connection file which was created

**Expected behavior**
There should be a button to remove the connection file beside the "Change the name of the current connection file" button.

**Screenshots**
![image](https://user-images.githubusercontent.com/14156926/114624362-acd4f680-9d04-11eb-8726-dd324bb1c3ce.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version: 1.2021.4.46

**Additional context**
Expanded the width of the popup window but the button did not appear

**Comment by MscrmTools** [comment]
Ok @LinnZawWin according to the code, the button does not appear when you are using the connection selector to connect to an environment. It appears only when you are managing the connection using Configuration > Manage connections.

I don't know if it makes sense to allow to manage connections when trying to connect to an environment

**Comment by LinnZawWin** [comment]
Found it after going through the menu Configuration > Manage connections. If it is by design, let it be. Since it is the same dialogue window, I thought it would be the same and didn't know that there is a different logic behind it.

The Connection dialogue being opened from the Connect button currently allows any type of managing connections (new, edit, copy, delete, update password, move to new/existing file, change file name) other than this only action (remove connection file). If it does not allow any other action, I would have looked for it somewhere else. 😅

![image](https://user-images.githubusercontent.com/14156926/115145115-2291e700-a0a4-11eb-9763-14966a9ade8c.png)

![image](https://user-images.githubusercontent.com/14156926/115145144-38071100-a0a4-11eb-8081-0b991f1900fe.png)
