### ISSUE TITLE
Cannot See any new tool

### ISSUE THREAD

**Issue by chaffee007** [MscrmTools/XrmToolBox#1023]
[Write your comment/feedback/issue here]

---
- Deployment: Online
- DB Version: 9.2.21032.164
- Connection Controls Version: 1.2021.2.40
- XrmToolBox Version: 1.2021.4.46

**Comment by MscrmTools** [comment]
Can you be more specific? Screenshot maybe?

**Comment by dschum** [comment]
I can't see tools either. In the previous version 1.2021.2.45 everything works fine on same machine
![toolboxlibrary](https://user-images.githubusercontent.com/82656060/115022337-8a3a0d80-9ebd-11eb-9af2-e49392507e65.PNG)

**Comment by MscrmTools** [comment]
ok, I detected an issue. Can you untick everything and retick what you want to see. I know this fix things. But I need to fix the code itself too

**Comment by MscrmTools** [comment]
Will be fixed in a future release

**Comment by noorahmad-code** [comment]
**Version 1.2021.4.46**

Can not see any thing in the tool library. I even tried checking and unchecking but still.... Can you please let me know whats the last stable version and how can I download it. 

![image](https://user-images.githubusercontent.com/56866510/115595582-15901600-a2a5-11eb-93a1-b0f460327dd2.png)

**Comment by MscrmTools** [comment]
Can you try with the Display option menu in the toolbar? That could fix things waiting for a new release

**Comment by sheilagithub** [comment]
I have this same issue.  Previous release works fine.

**Comment by daryllabar** [comment]
Anything under the Display Options?

**Comment by MscrmTools** [comment]
I will release a new version today to definitively fix this issue

**Comment by ZohaibUddinKhan** [comment]
XrmToolBox Version: 1.2021.4.47

If any of us still facing the same issue, then following steps works in my case:-

1. Un-tick the Display option menu in the toolbar.
2. Close XRMToolBox.
3. Open XRMToolBox.
4. Tick the Display option menu in the toolbar.

Thanks.

**Comment by huynhvanthao** [comment]
XrmToolBox Version: 1.2021.4.47

This save my life when following @ZohaibUddinKhan steps
Thanks
