### ISSUE TITLE
[BUG] Incorrect URL in solutions Components Mover

### ISSUE THREAD

**Issue by filcole** [MscrmTools/XrmToolBox#1027]
**Describe the bug**
URL showin in XrmToolbox Library is incorrect

**To Reproduce**
Open in XRMToolbox library

**Expected behavior**
Correct URL to Solution Components Mover in wiki

**Screenshots**
![image](https://user-images.githubusercontent.com/6078398/115223732-09208780-a104-11eb-9625-442535996939.png)

**Comment by MscrmTools** [comment]
Thank you for reporting. 
I will fix this for the next release
