### ISSUE TITLE
[BUG] Unable to connect to CRM after XrmToolBox update 

### ISSUE THREAD

**Issue by prikrylm** [MscrmTools/XrmToolBox#1031]
Unable to connect to CRM org. Connection manager try to connect with https and add port 80 at the end of url
Desired url is from local net it has only http protocol and no port was entered after url on wizard.

![obrazek](https://user-images.githubusercontent.com/26926725/117263040-27032180-ae52-11eb-99fe-415da25955b8.png)

XrmToolBox v 1.2021.4.47

**Comment by MscrmTools** [comment]
Can you share a picture of the connection wizard first screen (where you put the url)?

**Comment by prikrylm** [comment]
Here it is:
![obrazek](https://user-images.githubusercontent.com/26926725/117270957-06d76080-ae5a-11eb-8a89-49b57c09c8d4.png)

It is the connection that worked before the update.

**Comment by MscrmTools** [comment]
@prikrylm is this still happening?

**Comment by prikrylm** [comment]
Everything was moved to the cloud machines and local machine was switched off. So I don't know if new version correct metioned issue. :-/ It is probably OK to close this issue.
