### ISSUE TITLE
Missing region crm17 detected

### ISSUE THREAD

**Issue by Renato-CH** [MscrmTools/XrmToolBox#1034]
Hello developers, greetings from Switzerland

When we moved our environments to Switzerland we discovered that the connection is no longer possible. The only way to connect is via OAuth. Will you update missing regions?

Best regards, Renato
---
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40

**Comment by MscrmTools** [comment]
Fixed with latest release
