### ISSUE TITLE
[BUG] SettingsManager.Instance.TryLoad errors when class not as expected

### ISSUE THREAD

**Issue by LinkeD365** [MscrmTools/XrmToolBox#1037]
**Describe the bug**
My Project has significantly changed the class used to save settings, from a simple class to a nested array of child classes and as such need to migrate from one class definition to the new. 

I would expect TryLoad to return false rather than error if it finds a class that it is not able to parse

**To Reproduce**

                if (SettingsManager.Instance.TryLoad(GetType(), out FlowConnection flowConnection)) where flowConnection is a class not in the file

**Expected behavior**
Return False

**Desktop (please complete the following information):**
 - XrmToolbox Version 1.2021.2.45

**Comment by MscrmTools** [comment]
Fixed in latest release :)
