### ISSUE TITLE
MetadataDocumentGenerator: Add ability to filter fields by a specific form.

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#104]
I can currently filter output by attributes that exist on any form - but I'd like to be able to export only fields on a specific form.

**Comment by MscrmTools** [comment]
That make sense

I need to find a way to include this feature in the already overcrowded UI of MetadataDocumentGenerator

**Comment by mscottsewell** [comment]
The UI already appears to let you select a form (at least from the 'public forms') but the exported data contains data from all the forms.
![2015-04-09_20-56-18](https://cloud.githubusercontent.com/assets/6276300/7080119/1b8577cc-defb-11e4-966b-35997e7cbc98.png)

**Comment by MscrmTools** [comment]
Ok then...

I really did not work on this tool since a long time :)

**Comment by mscottsewell** [comment]
Even if you never added another feature, it would still be one of my daily go-to tools. :)
As I was working on it - I think the output doesn't match the selection in a couple of ways.
I selected the 'filter by prefix' and typed 'new_' to the textbox - (I thought it would return 'all attributes contained in forms - with the new_ prefix) but the document returned 'all attributes contained in forms' the prefix filter was ignored.

**Comment by MscrmTools** [comment]
Ok I guess I succeeded to fix both problems
