### ISSUE TITLE
Cannot install RibbonWorkbench

### ISSUE THREAD

**Issue by usergithub333** [MscrmTools/XrmToolBox#1040]
**Bug**
First download of XrmToolBox.
Error Message when trying to open RibbonWorkBench after install.

**Workaround**
Downloading an older version of XrmToolBox from 2020 and installing RibbonWorkBench after deinstalling in latest version solved issue in latest version.

**Screenshots**
![image](https://user-images.githubusercontent.com/19838127/119682056-decc9300-be42-11eb-8cf4-e57616315a29.png)

**Desktop (please complete the following information):**
 - XrmToolBox v1.2021.5.47
 - RibbonWorkBench 3.1.443.1

**Comment by MscrmTools** [comment]
Thank you for reporting. I can see what the issue is.
I will release a new version very soon to fix this

**Comment by MscrmTools** [comment]
@usergithub333  this is fixed
A new version is available
