### ISSUE TITLE
[BUG] Error Connecting - Error Requesting Orgs From The Discovery Server

### ISSUE THREAD

**Issue by darreny2** [MscrmTools/XrmToolBox#1044]
**Describe the bug**
When trying to connect to PowerApps CRM, the following error is encountered. Issue started this morning.

ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
ERROR REQUESTING ORGS FROM THE DISCOVERY SERVERFCB
'EnableRegionalDisco' is disabledUnable to connect to CRM:
FCB 'EnableRegionalDisco' is disabled
FCB 'EnableRegionalDisco' is disabledUnable to Login to
Dynamics CRM
Unable to Login to Dynamics CRM

**To Reproduce**
Attempt to connect to PowerApps CRM instance.

**Expected behavior**
Expected to be able to connect to the PowerApps CRM instance.

**Screenshots**

![image](https://user-images.githubusercontent.com/85242095/120504058-0e1e5b00-c381-11eb-9dfd-aec867d8227d.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version - v1.2021.5.49
 - Tool version - n/a

**Comment by darreny2** [comment]
I have been able to resolve my issue. It looks like the Regional Discovery Service has been shut down. I needed to re-do my XRMToolBox connections using the 'Microsoft Login Control' option which appears to use the Global Discovery service. I am now able to connect to the Dataverse with the XRMToolBox. I will close this bug report. Thanks.

**Comment by vkartikiyer** [comment]
> I have been able to resolve my issue. It looks like the Regional Discovery Service has been shut down. I needed to re-do my XRMToolBox connections using the 'Microsoft Login Control' option which appears to use the Global Discovery service. I am now able to connect to the Dataverse with the XRMToolBox. I will close this bug report. Thanks.

Hi,

I am also facing the same issue and I am new to XRMToolbox , can you let me know how you are able to fix the issue.
I tried deleting the existing connection and creating new one but again facing the same issue.

**Comment by vkartikiyer** [comment]
> > I have been able to resolve my issue. It looks like the Regional Discovery Service has been shut down. I needed to re-do my XRMToolBox connections using the 'Microsoft Login Control' option which appears to use the Global Discovery service. I am now able to connect to the Dataverse with the XRMToolBox. I will close this bug report. Thanks.
> 
> Hi,
> 
> I am also facing the same issue and I am new to XRMToolbox , can you let me know how you are able to fix the issue.
> I tried deleting the existing connection and creating new one but again facing the same issue.

Thanks , I have figured it.

**Comment by Prozek-SC** [comment]
> > > I have been able to resolve my issue. It looks like the Regional Discovery Service has been shut down. I needed to re-do my XRMToolBox connections using the 'Microsoft Login Control' option which appears to use the Global Discovery service. I am now able to connect to the Dataverse with the XRMToolBox. I will close this bug report. Thanks.
> > 
> > 
> > Hi,
> > I am also facing the same issue and I am new to XRMToolbox , can you let me know how you are able to fix the issue.
> > I tried deleting the existing connection and creating new one but again facing the same issue.
> 
> Thanks , I have figured it.

Can you share the workaround?  I'm using the latest version and it's still not working for me.

**Comment by Prozek-SC** [comment]
> > > > I have been able to resolve my issue. It looks like the Regional Discovery Service has been shut down. I needed to re-do my XRMToolBox connections using the 'Microsoft Login Control' option which appears to use the Global Discovery service. I am now able to connect to the Dataverse with the XRMToolBox. I will close this bug report. Thanks.
> > > 
> > > 
> > > Hi,
> > > I am also facing the same issue and I am new to XRMToolbox , can you let me know how you are able to fix the issue.
> > > I tried deleting the existing connection and creating new one but again facing the same issue.
> > 
> > 
> > Thanks , I have figured it.
> 
> Can you share the workaround? I'm using the latest version and it's still not working for me.

Okay figured it out:
1. New Connection
2. Microsoft Login Control
3. Use Default radio button and click on Open Microsoft Login Control
4. Choose Office365 (for our org anyway...not using On Premise)
5. Show Advanced
6. Set Online Region to "I don't know" and enter login credentials.
7. You then have to pick the environment to which you want to connect. Could be production, sandbox, etc.   It doesn't appear that this can be changed after that...maybe make a new connection?

Hope this helps.
