### ISSUE TITLE
Connections are being overwritten and set to current environment when connecting to environments

### ISSUE THREAD

**Issue by Reigningfear** [MscrmTools/XrmToolBox#1046]
**Describe the bug**
Upon upgrading to the latest version the day it was released, I noticed that the connections I had set up were overwritten and are now the environment that I logged into initially. I first noticed it when I would transfer data and solutions using a couple of plugins.

**To Reproduce**
Using the solution transfer tool or data transporter (perhaps others), switching to other saved environments overwrites them and changes them to the current environment. 

**Expected behavior**
I expect the environment I select to be the same one and not overwritten.

**Desktop (please complete the following information):**
XrmToolBox Version: 1.2021.6.51
Tool Version: 1.2021.5.19

**Additional context**
To troubleshoot, I have of course rebooted the PC, deleted all XRM files and storage but the issue still occurred. I decided to revert back to a few previous versions and it worked, until today. I was hit with a large discovery error and when I upgraded back to the latest, the same issue occurred. Unfortunately with this type of error, it prevents most of the plugins from being beneficial. Please let me know if there is anything else I can provide to help look into this.

**Comment by MscrmTools** [comment]
Hi @Reigningfear, thank you for reporting. The bug is already known and fixed. I just need to release a new version of connection controls. 
Will do it today

**Comment by MscrmTools** [comment]
Beta version of connection controls with this fix has been released

**Comment by Reigningfear** [comment]
Awesome, glad to hear it was known. This is probably a silly question but how do I take advantage of the updated connection controls?

**Comment by MscrmTools** [comment]
XrmToolBox will pop up to install new connection controls automatically when it's a public release.
For now, I fixed it in a beta version only.

You need to go to XrmToolBox settings to enable the use of pre release version of connection controls
![image](https://user-images.githubusercontent.com/10774317/122518316-57250f00-d011-11eb-9ca4-648c61593a7c.png)

**Comment by Reigningfear** [comment]
This works. Thank you for your support!
