### ISSUE TITLE
Folders in the Connection Manager

### ISSUE THREAD

**Issue by IsolatedStorage** [MscrmTools/XrmToolBox#1049]
Would it be possible to add Folders to the Connection Manager so that we can group together related connections? This will make managing the connections easier and a the connection list at the bottom corner more organised when you have a large number of connections

---
- Deployment: Online
- DB Version: 9.2.21062.128
- Connection Controls Version: 1.2021.6.44
- XrmToolBox Version: 1.2021.6.51

**Comment by MscrmTools** [comment]
This already exists since years :)

See [this youtube video](https://www.youtube.com/watch?v=mC5FR_LaY4w&list=PL0Pd0TO9GnXhGdFwVRb1wfYRGuS4CVmcA&index=3) at 40s
