### ISSUE TITLE
Check if plugin exists

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#105]
As we now have the "messagebus" implemented in #85 it would be great to have the possibility of checking if a specific plugin exists.
If not, trying to call it would be in vain...

**Comment by shytikov** [comment]
:+1:

**Comment by shytikov** [comment]
@rappen What if in case if no plugin was found matching your criteria will be found "Plugin not found" message will be return to caller plugin? Will it suit your needs?

**Comment by rappen** [comment]
My objective is to prevent the possibility to call another plugin if that plugin does not exist.
So I would need a separate method simply returning true/false if it exists. That way, I can disable/hide buttons to call this plugin if necessary.
The MsgBus call is already improved (by me, as I recall) to throw a `PluginNotFoundException` if target plugin does not exist.

**Comment by MscrmTools** [comment]
Resolved with merge from @shytikov
