### ISSUE TITLE
Metadata Cache Update Failed: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by simes1** [MscrmTools/XrmToolBox#1052]
I thought this was a problem with the add-in below but now I think it may be in XTB itself.  I've now seen the error with other add-ins and also when no add-in is loaded at all.  It can take quite a few seconds to display (20-30) and whilst waiting for it to display add-ins themselves can appear not to be working.

![image](https://user-images.githubusercontent.com/11423243/125347279-a6313c00-e352-11eb-9556-1dad474df508.png)

https://github.com/AndrewButenko/PersonalViewChartDBTransferTool/issues/11#issue-938113127

---
- Deployment: Online
- DB Version: 9.2.21063.125
- Connection Controls Version: 1.2021.6.44
- XrmToolBox Version: 1.2021.6.51

**Comment by MscrmTools** [comment]
@markmpn Could you help here ?

**Comment by MarkMpn** [comment]
I wonder if the local metadata cache has got corrupted somehow. Could you try deleting the files in `%appdata%\MscrmTools\XrmToolBox\Metadata` and restart XrmToolBox?

I'd expect to see an ~20 second delay the first time you connect to this instance again, but it should be < 1 second for any subsequent connections. If you get the same problem again, would you be able to share the cache file from this folder so I can see if there's something specific to your metadata that might be causing it?

**Comment by simes1** [comment]
My metadata cache is in a slightly different location (I use the /overridepath:".\SharedAppSettings" command line option):

    .\SharedAppSettings\Metadata

Clearing that folder seems to have fixed it and I now see "updating metadata" and then "metadata updated" in the bottom RH corner of the XTB window.

Thank you

--
Simon

**Comment by MarkMpn** [comment]
Great, glad it fixed it for you. If you hit the same problem in future I’d be interested to get a copy of the files in that folder to see what’s got messed up and if I need to change something to prevent it.

**Comment by simes1** [comment]
I still have the already messed up cache files from this time if that's any use....

**Comment by MarkMpn** [comment]
Yes please, could you email it to me or send me a link to download it? mark @ markcarrington.dev

**Comment by simes1** [comment]
Done

**Comment by MarkMpn** [comment]
Thanks, it looks like these cache files were generated with an earlier version and it's hitting a bug trying to update them. I think now you've deleted the files to force it to recreate a new version it shouldn't hit this same problem again. I'll update the code to make this smoother for other users though.

**Comment by simes1** [comment]
@MarkMpn XRB corrupted itself again the other day.  I think whilst trying to update add-ins (but I guess it might have been something else...).  Are the corrupted metadata cache's (or anything else) of any further use to you?

**Comment by MarkMpn** [comment]
Do you get exactly the same error message displayed again, or something different?

**Comment by simes1** [comment]
I'm pretty certain it was the same but it's true I didn't check too carefully....
