### ISSUE TITLE
Connectivity Issues after a recent update was applied

### ISSUE THREAD

**Issue by SwatiLavi** [MscrmTools/XrmToolBox#1053]
**Describe the bug**
Getting a connection failed error when connecting to Customer Engagement. This has only started happening after the recent update was applied.
![image](https://user-images.githubusercontent.com/87506123/125875365-a66cae6a-642c-46fd-829b-2be64952a99e.png)

**To Reproduce**
User OAuth/ MFA as the connection mechanism and supplied the AppId and Return Url

**Expected behavior**
Connection should be established with dynamics successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/87506123/125875449-f6106a73-3422-4ec2-9f6f-aea281cca287.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version - 1.2021.6.51
 - Tool version

**Additional context**

**Comment by MscrmTools** [comment]
Hi  @SwatiLavi , this error occurs because you have older version of SDK assemblies in your GAC that take precedence over the ones shipped with XrmToolBox.
These cached assemblies do not contain new method added by Microsoft in latest releases.

Please clear your GAC from older SDL assemblies and you will be good

**Comment by SwatiLavi** [comment]
Hi There,

I cleared the GAC but still having the issue.
Source	: Not Provided
Method	: Not Provided
Date	: 16/07/2021
Time	: 11:40:00 PM
Error	: You don't have permission to access any of the organizations in the Microsoft Dynamics CRM Online region that you specified. If you're not sure which region your organization resides in, choose "Don't know" for the CRM region and try again. Otherwise check with your CRM administrator.
Stack Trace	: Not Provided

I have selected Region as Don't know and using Microsoft Login Control. It doesn't work with OAuth/MFA either.

**Comment by MscrmTools** [comment]
It does not seem to be the same issue.

As for this one, I cannot tell. If Microsoft Login Control does not work either, then I don't know how to help you. It means something is wrong on the info you are providing

**Comment by SwatiLavi** [comment]
Hi There,

Thank you so much for your response. Yes, I removed the assembly from one of the GAC locations and received this new error.
However, this morning I did a search again in the GAC folder and found another occurrence of the Microsoft.Xrm.Sdk dll. Removing it helped me resolve the issue.
Thank you so much, your suggestion was spot on!


Regards,
Swati
