### ISSUE TITLE
[BUG] Custom UserControl edges are cutting

### ISSUE THREAD

**Issue by furqansafdar** [MscrmTools/XrmToolBox#1061]
I am working to create a new plugin but when using a custom UserControl within main plugin UserControl, the edges of it are not fully showing and cutting from right and bottom side (screenshots below).

Please advise a resolution.

**Screenshots**
![image](https://user-images.githubusercontent.com/14292272/130564345-a2df2d81-ce18-49dd-9f90-2f93d92548b5.png)
![image](https://user-images.githubusercontent.com/14292272/130564400-93fe7704-439c-42a9-b1b3-f627207d43fb.png)
![image](https://user-images.githubusercontent.com/14292272/130564497-2650cf0a-c163-4fa4-a419-aa175919f869.png)

**Desktop:**
 - XrmToolbox Version - 1.2021.6.51

**Comment by MscrmTools** [comment]
Hi,

This is not a bug. You should use `Dock` property of your controls to enable auto resizing (See [Docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.dock?view=netframework-4.8))
