### ISSUE TITLE
Connection files imported, with "New File"

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1062]
(not sure it should in [Connection](https://github.com/MscrmTools/MscrmTools.Xrm.Connection), it's only user experience)

Many times imported a connection file, it is imported as "New File" instead of the file name.

See: https://www.screencast.com/t/fcvtGd2Sd
(sorry bad colors)

---
- Connection Controls Version: 1.2021.6.43
- XrmToolBox Version: 1.2021.6.51

**Comment by MscrmTools** [comment]
Hi @rappen, it usually happens for "old" connection files if I'm correct since I had a bug where the name of the connection file was not ... in the connection file but only on the list of connection files.
Should work as expected for files created recently (can't tell what recently exactly is)

**Comment by rappen** [comment]
Seems to work fine!
