### ISSUE TITLE
Alternative language for custom attributes

### ISSUE THREAD

**Issue by Jkosobucki** [MscrmTools/XrmToolBox#1067]
Hi,

We are looking for a plugin that allows us to update alternative language for custom attributes.

We have a lot and when trying to update the solution we are getting a timeout.

any suggestions are appreciated!
thanks 
---
- Connection Controls Version: 1.2021.6.43
- XrmToolBox Version: 1.2021.6.51

**Comment by MscrmTools** [comment]
Easy translator ?

**Comment by Jkosobucki** [comment]
Thanks!
