### ISSUE TITLE
Tools-tab can't be found

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1068]
For some reason it doesn't show tab for Tools.

![image](https://user-images.githubusercontent.com/2572253/132990557-d98ae260-5685-4dcf-84ec-1d6b16d1c07f.png)

(dev for tool, can't get it back for anything - deleted all files restart VS, restart pc, reboot the universe - nothing!)

Maybe it would be good to have a menu to add it?

---
- Connection Controls Version: 1.2021.5.42
- XrmToolBox Version: 1.2021.5.47

**Comment by rappen** [comment]
Checking everything... Now I get it!

Upgrade `DockPanelSuite` to 3.1.0 from 3.0.6 - that hides the tools-menu!

**Comment by MscrmTools** [comment]
Yes, I found this too which prevented me to upgrade to 3.1.0

**Comment by BetimBeja** [comment]
I think it is related to this breaking change
![image](https://user-images.githubusercontent.com/11160171/132998372-34bc9b1d-3773-479b-8520-55b379e94c58.png)

**Comment by MscrmTools** [comment]
I don't think so. This is already the value that is used in XrmToolBox and I tried different changes without success.
The problem is the tabs are displayed behind the toolbar (so docking order is not honored). I tried to put tabs on bottom and they are visible but not the top of each page.
I checked quickly the commits of the project but did not found something obvious that can explain this "new" behavior

**Comment by BetimBeja** [comment]
I did some tests with version `3.1.0` of `DockingStation` and changing `DocumentStyle` to `DockingMdi` seems to solve the problem. The problem being the content having a "negative top margin", changing the `DocumentTabStripLocation` to `Bottom` you can see that the top of the document gets "cut".
![image](https://user-images.githubusercontent.com/11160171/133038361-51da7475-332d-4253-9ac5-eb0f7c672254.png)

**Comment by MscrmTools** [comment]
You are correct! I just found this too

**Comment by MscrmTools** [comment]
So I will add the version 3.1 in the next release of XrmToolBox

**Comment by rappen** [comment]
Woohooo! 🥳
I guess only available for next publish release... so "a few month" I guess? Just so I know 🙂

**Comment by MscrmTools** [comment]
It really depends if there is something new to ship, like new SDK assemblies, or really cool new feature

so yes, few months seems to be...

**Comment by MscrmTools** [comment]
What is promising with version 3.1 is the support for .Net core. It basically means that I could (try to) work on a .Net Core XrmToolBox version
