### ISSUE TITLE
Connecting to Teams Dataverse Environments

### ISSUE THREAD

**Issue by ndcatalyst** [MscrmTools/XrmToolBox#1069]
I am trying to connect to Teams Dataverse Environments using Microsoft Login Control (default configuration), Office 365 Deployment Type. I login with my credentials and it shows all of my Dataverse envrionments including the teams based ones. When I attempt to connect to the teams environment and I get a message "Can't Connect to Microsoft Common Data Service".

Is there anything that can be done currently to connect to the Teams Dataverse or is this a new feature that would need to be developed?

---
- Connection Controls Version: 1.2021.6.43
- XrmToolBox Version: 1.2021.6.51

**Comment by MscrmTools** [comment]
Nothing. 
It's not possible to connect to Microsoft Dataverse for Teams with the SDK. So no tool is capable to do this.
This is a limitation handled by Microsoft

**Comment by ndcatalyst** [comment]
Well that is a bummer, thanks for the quick reply
