### ISSUE TITLE
Exception error when trying to launch app: Root element is Missing

### ISSUE THREAD

**Issue by mprill** [MscrmTools/XrmToolBox#1072]
After a system reboot, my xrmtoolbox is no longer opening. I get the following error:
-----
An unexpected error occurred: System.Exception: Root element is missing.
       at XrmToolBox.Options.get_Instance()
       at XrmToolbox.New.NewForm.SetTheme()
       at XrmToolbox.New.NewForm..ctor(String[] args)
       at XrmToolbox.Program.Main(String[] args)

One reason can be that at least one file is locked by Windows. Please unblock each locked files or unlock XrmToolBox.zip before extracting its content
------

Getting the same thing if I unzip the zip file to a new location and try opening from there. Any ideas?

**Comment by MscrmTools** [comment]
Your settings file must be corrupted.
Delete it and you should be good

**Comment by mprill** [comment]
Sorry, can you give me a hint where the settings file is so I can nuke it? I thought the app was standalone :)

**Comment by MscrmTools** [comment]
Should be, by default, in C:\Users\<your_profile>\AppData\Roaming\MscrmTools\XrmToolBox

**Comment by mprill** [comment]
Thanks, I'm back up and running. Appreciate your help and this tool! Will be donating again :)

**Comment by MscrmTools** [comment]
Thank you very much for the support!

**Comment by emibanana** [comment]
Fixed thanks, but please just fix this funny bug, it's so frustranting to figure it out as i re-download the latest version and when i found out that a complete new installation still says "something is missing", its very shocking
