### ISSUE TITLE
Launch with no internet, crashing when connecting to Nuget.

### ISSUE THREAD

**Issue by jimbonovak** [MscrmTools/XrmToolBox#1077]
Trace log below.  Disable internet connection and launch. 

---
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.9.52
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The remote name could not be resolved: 'api.nuget.org'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

**Comment by daryllabar** [comment]
Hey, who let Jim in here?

**Comment by MscrmTools** [comment]
Fixed in latest version
