### ISSUE TITLE
DataImport++ Not Installing Issue

### ISSUE THREAD

**Issue by mert2run** [MscrmTools/XrmToolBox#1078]
Not Installing

An error occured: The nuget package for tool josepmerhej.dataimport(1.2019.2.44) has not been found

---
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.9.52

**Comment by MscrmTools** [comment]
@mert2run is this still an issue?

**Comment by bonomo1** [comment]
I am having this issue as well now with the latest update to one of my tools. 

![image](https://user-images.githubusercontent.com/32522922/153482078-18af98e4-d85c-4c06-b0d9-81488d27cf23.png)

https://www.nuget.org/packages/XRMSolutionDependencyChecker/1.3.1
![image](https://user-images.githubusercontent.com/32522922/153482173-5b5efd79-4f90-4ad8-9d3e-7a5db2417307.png)

https://www.xrmtoolbox.com/plugins/XRMSolutionDependencyChecker/
![image](https://user-images.githubusercontent.com/32522922/153482329-dc184386-09e3-47fb-87b3-5c446ccd52ca.png)

**Comment by MscrmTools** [comment]
This is an issue with the Nuget cache of XrmToolBox.
It should go away by itself

**Comment by bonomo1** [comment]
I was too quick to post an issue. I deleted my comment as I realized my issue was related to a version mismatch, nuget said one version but the plugin itself had another. Apologies for the comment then deleting of it!
