### ISSUE TITLE
Allow only one instance of XrmToolBox in the memory

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#108]
It would be nice if `XTB` would check is there any other instances of itself are already present in the memory. If it is, rather bring already opened `XTB` to front, and do not open new instance once again.

I think since we allow multiple plugin instances, allowing many instances of `XTB` is quite misleading. 

The behavior should be configurable on settings dialog of `XTB`.

**Comment by MscrmTools** [comment]
That makes sense from a end user point of view

But for me, it is practical to be able to use a released version of XrmToolBox for my day to day work but run XrmToolBox in debug mode when optimizing plugins or other purposes. 

As you said, this could be an option in XTB settings

**Comment by mscottsewell** [comment]
I regularly open two copies of the the toolbox side-by-side to compare sitemap, webresources, privileges between DEV/UAT - or UAT/PROD - 

If you allow opening two tabs side-by-side within the toolbox, that's fine - but I still prefer being able to open two separate instances.

**Comment by shytikov** [comment]
It should be configurable. 

But idea of side-by-side plugins is nice by the way!

**Comment by rappen** [comment]
I really don't see the need to introduce even more complexity to XTB in this case.
You either click the XTB icon in the task bar to focus existing instance or you intentionally shift-click to open a new instance.
Sorry, it's a :-1: from me.

**Comment by daryllabar** [comment]
I'm with @rappen ... Let's KISS this one...

**Comment by shytikov** [comment]
I'm  lost, guys. What should we KISS:
* One instance of `XTB`;
* Side-by-side plugins?

I would agree that last one is a bit over that top... But form other hand, I can try to implement this functionality as a plugin! Plugin that will allow compare results of two instances of other plugin, that would be controlled by message bus messages! Although... this would be way over the top...

**Comment by daryllabar** [comment]
I was speaking specifically about the One instance of XTB.

**Comment by MscrmTools** [comment]
So, for this one, it will be a "won't fix" and I close the comment
