### ISSUE TITLE
XrmToolBox - Unhandled exception has occurred in your application, application will not load

### ISSUE THREAD

**Issue by djosoff** [MscrmTools/XrmToolBox#1083]
Experts I am at my wits end.  I suspect I may need to reimage my pc to resolve this.  

1.	Doubleclick XRMToolBox.exe shortcut to launch application.
2.	XrmToolBox window appears with the verbiage Loading Tools…
3.	The message in the window updates to Preparing Start Page…
4.	I am presented with the error:  Unhandled exception has occurred in your application.  If you click Continue, the application will ignore this error and attempt to continue.  If you click Quit, the application will close immediately.  The remote name could not be resolved:  “https”.
5.	Listed below are the details of the error.  If I click Continue, the XrmToolBox page continues to show as Preparing Start Page…. Indefinitely until I kill the program.  

I have removed and reinstalled XRM many times.  My .Net is also current and Ive run the repair utilitiy.  If I install a very old XRMToolbox program, it still gives me the Unhandled Exception error, but if I click continue it will load.  If allows me to run any 'New' program and the list of 20 or so new programs, but if I attempt to install any from the library is fails the with The remote name could not be resolved:  “https”. error.

Below are my pc details and the error details.  Any help is appreciated.  

Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎4/‎29/‎2021
OS build	19042.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0
Processor	Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz   1.90 GHz
Installed RAM	8.00 GB (7.85 GB usable)
System type	64-bit operating system, x64-based processor

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The remote name could not be resolved: 'https'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2021.9.52
    Win32 Version: 1.2021.9.52
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
CrowdStrike.Sensor.ScriptControl
    Assembly Version: 6.26.14003.0
    Win32 Version: 6.26.14003.0
    CodeBase: file:///C:/WINDOWS/System32/CrowdStrike.Sensor.ScriptControl14003.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2021.9.52
    Win32 Version: 1.2021.9.52
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 6.1.7601.24479
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/Microsoft.IdentityModel.DLL
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly Version: 1.2021.9.52
    Win32 Version: 1.2021.9.52
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Common
    Assembly Version: 6.0.0.165
    Win32 Version: 6.0.0.165
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/NuGet.Common.DLL
----------------------------------------
NuGet.Packaging
    Assembly Version: 6.0.0.165
    Win32 Version: 6.0.0.165
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/NuGet.Packaging.DLL
----------------------------------------
NuGet.Protocol
    Assembly Version: 6.0.0.165
    Win32 Version: 6.0.0.165
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/NuGet.Protocol.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/Newtonsoft.Json.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2021.9.46
    Win32 Version: 1.2021.9.46
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2021.9.46
    Win32 Version: 1.2021.9.46
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 9.0.0.0
    Win32 Version: 9.2.46.5279
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly Version: 9.0.0.0
    Win32 Version: 9.2.46.5279
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 9.0.0.0
    Win32 Version: 9.2.46.5279
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.97
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Ui.Styles
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.97
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/Microsoft.Xrm.Tooling.Ui.Styles.DLL
----------------------------------------
Microsoft.Xrm.Tooling.CrmConnectControl
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.97
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/Microsoft.Xrm.Tooling.CrmConnectControl.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 5.2.9.0
    Win32 Version: 5.2.9.0
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
ScintillaNET
    Assembly Version: 3.6.3.0
    Win32 Version: 3.6.3.0
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/ScintillaNET.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/McTools.StopAdvertisement.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2021.7.22
    Win32 Version: 1.2021.7.22
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2019.11.4
    Win32 Version: 1.2019.11.4
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly Version: 1.2021.2.4
    Win32 Version: 1.2021.2.4
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Javista.AttributesFactory
    Assembly Version: 1.2021.5.8
    Win32 Version: 1.2021.5.8
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.ATTRIBUTESFACTORY.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2020.11.11
    Win32 Version: 1.2020.11.11
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2021.9.4
    Win32 Version: 1.2021.9.4
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2019.11.3
    Win32 Version: 1.2019.11.3
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2019.5.3
    Win32 Version: 1.2019.5.3
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeNamingChecker
    Assembly Version: 1.2020.6.0
    Win32 Version: 1.2020.6.0
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTENAMINGCHECKER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly Version: 1.2018.9.11
    Win32 Version: 1.2018.9.11
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2019.11.2
    Win32 Version: 1.2019.11.2
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MscrmTools.CrmTraceReader
    Assembly Version: 1.2018.4.1
    Win32 Version: 1.2018.4.1
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CRMTRACEREADER.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly Version: 1.2020.2.4
    Win32 Version: 1.2020.2.4
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
System.Text.Json
    Assembly Version: 5.0.0.2
    Win32 Version: 5.0.521.16609
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/System.Text.Json.DLL
----------------------------------------
MscrmTools.EmailAnonymizer
    Assembly Version: 1.2019.12.1
    Win32 Version: 1.2019.12.1
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.EMAILANONYMIZER.DLL
----------------------------------------
MscrmTools.EnvironmentVariableManager
    Assembly Version: 1.2021.4.5
    Win32 Version: 1.2021.4.5
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ENVIRONMENTVARIABLEMANAGER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2017.12.3
    Win32 Version: 1.2017.12.3
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2021.7.13
    Win32 Version: 1.2021.7.13
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2021.7.16
    Win32 Version: 1.2021.7.16
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2021.4.4
    Win32 Version: 1.2021.4.4
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PolymorphicLookupCreator
    Assembly Version: 1.2021.7.6
    Win32 Version: 1.2021.7.6
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.POLYMORPHICLOOKUPCREATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
    Assembly Version: 1.2021.1.15
    Win32 Version: 1.2021.1.15
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MscrmTools.PortalRecordsMover
    Assembly Version: 1.2021.4.27
    Win32 Version: 1.2021.4.27
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2018.6.23
    Win32 Version: 1.2018.6.23
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2020.2.12
    Win32 Version: 1.2020.2.12
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2021.5.5
    Win32 Version: 1.2021.5.5
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2021.9.14
    Win32 Version: 1.2021.9.14
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2021.9.9
    Win32 Version: 1.2021.9.9
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2021.7.3
    Win32 Version: 1.2021.7.3
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2021.7.3
    Win32 Version: 1.2021.7.3
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2021.4.15
    Win32 Version: 1.2021.4.15
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2020.4.13
    Win32 Version: 1.2020.4.13
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2021.4.6
    Win32 Version: 1.2021.4.6
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MscrmTools.WebresourcesManager
    Assembly Version: 2.2021.5.18
    Win32 Version: 2.2021.5.18
    CodeBase: file:///C:/USERS/DJOSOFF/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.1.1.3
    Win32 Version: 4.6.26907.01
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/System.Net.Http.DLL
----------------------------------------
MetadataViewProxies_cc9addba-ac59-4721-aa29-1dc140a4cf15
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
NuGet.Configuration
    Assembly Version: 6.0.0.165
    Win32 Version: 6.0.0.165
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/NuGet.Configuration.DLL
----------------------------------------
NuGet.Versioning
    Assembly Version: 6.0.0.165
    Win32 Version: 6.0.0.165
    CodeBase: file:///C:/Users/DJOSOFF/Downloads/RunXRMToolBoxFromHere/NuGet.Versioning.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by MscrmTools** [comment]
it really looks like you cannot access XrmToolBox portal and/or Nuget.org website (This is what is used to install tools).

When you said you reinstall XrmToolBox multiple times, did you clean also the folder C:\users\<your_login>\AppData\Roaming\XrmToolBox?

**Comment by MscrmTools** [comment]
@djosoff, any news?
