### ISSUE TITLE
[BUG]All Nuget Plugins Fail to Load (Attribute Editor)

### ISSUE THREAD

**Issue by zkorws** [MscrmTools/XrmToolBox#1085]
**Describe the bug**
Whenever I load a Nuget plugin I recevie the following error:
![image](https://user-images.githubusercontent.com/95003970/143334666-5cfc3cda-8b3f-4635-8c22-292cdee6cad8.png)

**To Reproduce**
Download any Nuget based plugin, such as Attribute Editor and the tool will fail to load.

**Screenshots**
Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.5.5631.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

**Desktop (please complete the following information):**
 - XrmToolbox Version: 1.2021.9.52
 - Tool version: 1.2021.3.1

**Additional context**
Standard installation of XRMToolbox in root directory on Windows 11, have tried running in admin mode, tried complete unisntall (including clearing the roaming)

Any thoughts would be very grateful.

**Comment by MscrmTools** [comment]
Hi @zkorws, Please remove the faulty tool Colso.Xrm.AttributeEditor from your Plugins folder and you will be good

**Comment by zkorws** [comment]
> Hi @zkorws, Please remove the faulty tool Colso.Xrm.AttributeEditor from your Plugins folder and you will be good

Yes, that works but I need AttributeEditor in order to complete a task I am working on. Are we saying there is something wrong with it in it's current version and I should talk to Colso?

**Comment by MscrmTools** [comment]
Absolutely, you are correct. Latest version seems buggy.
Please contact colso or try to download manually a previous version

**Comment by zkorws** [comment]
Thank you very much, much appreciated!
