### ISSUE TITLE
[Improvement] - Chrome OS compatibilty

### ISSUE THREAD

**Issue by AdminDRC** [MscrmTools/XrmToolBox#1086]
Hello,
Our company is plannig to move our workspace from windows to chromebooks. Nowaday it is impossible to make xrmtoolbox works on Chrome OS.
I would like to know if it is possible to make XrmToolBox available and compatible with ChromeOS or it would be great if you can make it avaible online without download.

Thanks for your help.

**Comment by MscrmTools** [comment]
Sorry but that won't be possible... Too much work involved in both requests
