### ISSUE TITLE
Timeout value cannot be greater than 3:34, otherwise crashes.

### ISSUE THREAD

**Issue by razvanyork** [MscrmTools/XrmToolBox#109]
Because the timeout value is an Int32 and thus can only have a value of 2,147,483,647, which is roughly 3 minutes 34 seconds, XrmToolbox will crash entirely if 3:35 or greater is input in the Timeout value box for any given connection. The timeout value needs to be greater for some conditions -- such as transferring solutions which can take upwards of 5-10 minutes.  If only 3:34 minutes can be detected, then I'd think it should make that the max allowable value, instead of allowing it to save to the XML file which then causes the app to crash every time it is opened. 
After putting in timeout of 3:35 and saving:
![afterputting335](https://cloud.githubusercontent.com/assets/6609209/7139053/62ff15fc-e281-11e4-9d45-f76bd77ffaa5.png)
Every time it loads from then on it crashes:
![loadingerror](https://cloud.githubusercontent.com/assets/6609209/7139009/176474ac-e281-11e4-8318-5f814d26382b.png)

**Comment by MscrmTools** [comment]
Thank your for reporting this

I will update the type to store TimeOut
