### ISSUE TITLE
[BUG] Can't Open after installing latest release XrmToolBox v1.2021.12.53

### ISSUE THREAD

**Issue by paulhasell** [MscrmTools/XrmToolBox#1093]
**Describe the bug**
On reopening after the update it's trying to cache load a tool and fails taking the whole process out before the loading is complete so I can't disable/remove the tool :(

**To Reproduce**
Difficult as it's likely tool dependent

**Expected behavior**
If there's an issue caching during the load process the erroring tool should be isolated to allow the load to complete

**Screenshots**
![image](https://user-images.githubusercontent.com/20418710/146377838-67eaad1f-fb15-4af1-8cc1-f171840c8f40.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version
 - Tool version

**Additional context**

**Comment by MscrmTools** [comment]
Hi, thank you for reporting.
Yes it seems you had some old assemblies... So, I can only thank you to be an old time user of XrmToolBox 😄 
You found the good way to clean up things.

I will let this issue open so that other users may see it if needed

**Comment by BetimBeja** [comment]
I experienced the same issue this morning, I had built the latest version from the source code so I was affraid it was related to that.

**Comment by rexkenley** [comment]
I have the same issue as well, even though I deleted the old version and extracted from the latest zip file. I don't have a plugins folder in my xrmtoolbox.

**Comment by paulhasell** [comment]
The plugins folder is under your user 'hive' .\AppData\Roaming\MscrmTools\XrmToolBox\Plugins

**Comment by Mattw112** [comment]
I have this issue too!  Just updated to latest version now I cant get it to open, giving me error shown 

![image](https://user-images.githubusercontent.com/12132460/146858962-05afec3a-a54e-4c3f-b878-bfee6596a92f.png)

Not sure I'm clear on what someone did to fix this?

Also, not sure if it matters but I upgraded to Windows 11 yesterday.

Terry

**Comment by daryllabar** [comment]
Just delete the Cinteros.Xrm plugins/tools in your plugins folder

C:\Users\{UserName}\AppData\Roaming\MscrmTools\XrmToolBox\Plugins

**Comment by Mattw112** [comment]
I just deleted the one .dll in that location the error was talking about and now it loads again!  thanks

**Comment by LycraLout** [comment]
FYI, same issue here. Same fix. Deleted the offending dlls from the plugins folder and I was good to go.
