### ISSUE TITLE
Regarding installation

### ISSUE THREAD

**Issue by anique9999** [MscrmTools/XrmToolBox#1097]
Hi,
After following the installation and double clicking on XrmToolBox.exe, the application is opening fine but I don't see the application in "Programs and Features" in control panel. Can please tell why it is not appearing in "Programs and Features"?

Thanks,
Anique

**Comment by MscrmTools** [comment]
Because it's not a program that is installed. It's just file copied on your computer

**Comment by anique9999** [comment]
Can you please tell how to install this program?

**Comment by BetimBeja** [comment]
@anique9999 you can read some documentation here https://www.xrmtoolbox.com/documentation/for-users/install-xrmtoolbox/
