### ISSUE TITLE
[BUG]Can't add security role to disabled user with User Role Manager

### ISSUE THREAD

**Issue by zenspassov** [MscrmTools/XrmToolBox#1099]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - XrmToolbox Version
 - Tool version

**Additional context**

**Comment by MscrmTools** [comment]
Hi @zenspassov, this is not a bug but a feature of Dataverse. You cannot add a role to a disabled user. 

Unless you change this configuration : Use Org Settings tool for that

![image](https://user-images.githubusercontent.com/10774317/148248707-f2380c7e-61ad-4084-ae20-86f8b5be985b.png)

Also moving the issue in the appropriate repository
