### ISSUE TITLE
Two or more plugins in the same assembly

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#110]
I faced with very strange situation. 

It's possible to create two or more plugins in the same assembly, and this actually leads to misunderstandings, since all the plugins in the assembly will be assigned with the same metadata, i.e. Title, Description, Author, etc. So you can see two or more plugins with the same name, but opening different controls from same assembly.

I know that we cannot forbid developers to create more than one plugin in assembly, but `XTB` should be more strict when displaying them, since one way or another core is responsible for all the strange things that plugins are doing.

For example:
* we should search for all available plugins in assembly, but display only first one;
* plugin attributes should be assigned not to assembly, but to class instead.
* main plugin control should belong to predefined system-wide namespace.

**Comment by MscrmTools** [comment]
See #131 for possible resolution of this issue.

**Comment by MscrmTools** [comment]
Fixed in DEV branch
