### ISSUE TITLE
Errors with Cinteros dlls after updating to latest XTB version

### ISSUE THREAD

**Issue by simes1** [MscrmTools/XrmToolBox#1100]
Hi,

I've had a few issues updating to the latest XTB version.  I've manged to fix most of them but I'm still getting errors like this one with 3 DLLs in the ./SharedAppSettings/Plugins folder:

- Cinteros.XTB.PluginTraceViewer.dll
- Cinteros.XTB.BulkDataUpdater.dll
- Cinteros.Xrm.FetchXmlBuilder.dll

![image](https://user-images.githubusercontent.com/11423243/148428002-6b24e2a2-102b-49d3-b017-f9f99668ebe5.png)

For the time being I have just renamed the DLLs above to *.dll.old but I'm not sure that will have properly fixed it.

These look like old DLLs from @rappen - I'm not sure if they are still in use somehow or if not whether I should also remove them from some config file or other.

Any ideas how best to proceed?

Regards

--
Simon

---
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.12.53

**Comment by simes1** [comment]
Ooops looks like duplicated #1093 and #1098.

So renaming/deleting should be sufficient on it's own?

**Comment by MscrmTools** [comment]
Correct. You can delete those files
