### ISSUE TITLE
HELP!  Bulk Workflow Execution is only processing a single batch, not the total records

### ISSUE THREAD

**Issue by NinaNuckols** [MscrmTools/XrmToolBox#1101]
I just updated to the 1.2021.12.53 on Monday 1/10/21.   

When running bulk workflow execution tool it is only processing the batch size #, not the record count.  I have a total record count for my query of 378k, with a batch size of 1000 with a zero interval.  I am having to manually restart this every 1000 records.  Its also not providing the estimated time as it did in the previous version or any progress bar.

However, if I reduce the batch size to 50 and add a 1 second interval, it works - just takes double the time to process.  But it does display the Est. Time, still no progress bar.

Any help would be appreciated as we are in a data migration validation for a Go Live.

Thanks

---
- Deployment: OnPremise
- DB Version: 9.1.6.3
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.12.53

**Comment by MscrmTools** [comment]
Unfortunately, I'm not the owner of this tool and I can't see why the update of XrmToolBox would change anything.

Asking help from the owner @andypopkin, hoping he could jump in this issue
