### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BabaMalaika** [MscrmTools/XrmToolBox#1102]
**Describe the bug**
Error when trying to save export config or import config file in "CDS Data Migrator"

**To Reproduce**
connect to environment
select min. one available entity
choose saving path
click on SAVE
![image](https://user-images.githubusercontent.com/97963534/149949829-aba410c0-27bf-4c71-a6ac-ab7631d7baec.png)

**Expected behavior**
Once the export config is generated, a "Successfully created XML file" dialog will pop up and the export JSON file will be generated at the specified location.
![image](https://user-images.githubusercontent.com/97963534/149949754-b8f733b7-7eed-4caa-af38-a5c3b1de4cf4.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/97963534/149949867-9b7b3a18-e412-4504-8c2e-ec53af4d2d3a.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version v1.2021.12.53
 - Tool version CDS Data Migrator 1.1.4.0

**Additional context**
thanks for any help!

**Comment by MscrmTools** [comment]
Hi @BabaMalaika,

Can you create an issue in the [tool repository](https://github.com/Capgemini/xrm-datamigration-xrmtoolbox)?

This tool is not mine and I cannot help you here

**Comment by BabaMalaika** [comment]
sure, sorry my bad
