### ISSUE TITLE
Export to Excel is not working. It shows that it is loading entities, but nothing populates.

### ISSUE THREAD

**Issue by peggyweiss** [MscrmTools/XrmToolBox#1103]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - XrmToolbox Version
 - Tool version

**Additional context**

**Comment by MscrmTools** [comment]
Hi @peggyweiss, what tool are you using?

**Comment by peggyweiss** [comment]
XrmToolbox Export to Excel

Peggy Weiss
Database Administrator & IT Specialist

701.328.5326     *     ***@***.******@***.***>     *     commerce.nd.gov<https://commerce.nd.gov/>

***@***.***

**Comment by MscrmTools** [comment]
So this is not an issue with XrmToolBox.
Please open an issue on the appropriate GitHub repository: https://github.com/rajyraman/mscrmexporttoexcel
