### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by restorick2378** [MscrmTools/XrmToolBox#1106]
**Describe the bug**
Cannot load XRM Toolbox

**To Reproduce**
Download latest copy to computer.
Unblock ZIP
Extract Zip
Start XRM Toolbox
Receive this error:
![image](https://user-images.githubusercontent.com/44639425/151163255-94f0648d-086c-4676-b5d5-b9a7af2917ab.png)

**Expected behavior**
XRM Toolbox should start.  ;-)

**Screenshots**
![image](https://user-images.githubusercontent.com/44639425/151163358-dc43d900-86c0-43f6-bede-58220e1f6481.png)

**Desktop (please complete the following information):**
 - Latest version from site
 - unknown

**Additional context**

**Comment by MscrmTools** [comment]
Hi @restorick2378, 
Did you already have XrmToolBox installed on your computer?

**Comment by restorick2378** [comment]
A while ago, yes

**Comment by MscrmTools** [comment]
So there is a chance the issue is with some cache remaining.
Can you clear this folder C::\users\<your_login>\appData\Roaming\MscrmTools\XrmToolBox?
And try again?

**Comment by restorick2378** [comment]
turns out the colso tools were the issue.  I removed them and all is well
