### ISSUE TITLE
[BUG] Solution Dependency Checker 1.2.0 freezes/hangs all the time on latest xrmtoolbox 1.2021.12.53

### ISSUE THREAD

**Issue by vsn2000** [MscrmTools/XrmToolBox#1107]
**Describe the bug**
With the new release 1.2.0 on xrm toolbox 1.2021.12.53, anytime you try to check a solution for dependency issues, the UI of solution dependency checker just hangs/spins. It does not say "no missing dependecies found"

**To Reproduce**
Run dependency checker against a target dynamics environment

**Expected behavior**
A message indicating either no dependencies were found missing, or a list of missing dependencies.

**Screenshots**

**Desktop (please complete the following information):**
 - XrmToolbox Version 1.2021.12.53
 - Tool version

**Additional context**

**Comment by MscrmTools** [comment]
I would like to say that you should create an issue in the [tool repository](https://github.com/CorterraSolutions/SolutionDependencyChecker) but it seems their author do not allow this :/

So calling authors @bonomo1, @MiddyE57 and @atraczyk24 and closing issue as there is nothing I can do more

**Comment by vsn2000** [comment]
Hi, the issue is that on the latest version of xrmtoolbox 1.2021.12.53,
when you check a solution with depedency checker v1.2.0, it basically
doesn't give any visual feedback of passing or failing. There is no
indication if there are any missing dependencies or whether the solution is
ready to import.

Thanks

**Comment by MscrmTools** [comment]
Nothing changed on how async actions work since many versions.
I would need to check your source code to see if something is wrong
