### ISSUE TITLE
Power FX button issue

### ISSUE THREAD

**Issue by DynamicsNinja** [MscrmTools/XrmToolBox#1108]
I faced an issue where you can't load a solution if there is a Power FX button inside which is not visible in the UI. Not sure if that's supported or not. Do you have any potential workaround for how to do that or do we just need to remove all Power FX buttons for now?

![MicrosoftTeams-image (18)](https://user-images.githubusercontent.com/31212465/153018584-f96baa87-9cde-4318-ac0e-82869e30fd2c.png)

---

- Deployment: Online
- DB Version: 9.2.22012.138
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.12.53

**Comment by BetimBeja** [comment]
@DynamicsNinja maybe the issue should be opened here https://github.com/scottdurow/RibbonWorkbench

**Comment by DynamicsNinja** [comment]
oops, I was wondering why it didn't show up in the right place 😂
