### ISSUE TITLE
Easy translator not processing QueueItem properly

### ISSUE THREAD

**Issue by mattp65** [MscrmTools/XrmToolBox#111]
When importing translations for QueueItem, the ObjectTypeCode errors out saying: "Could not find a picklist value with the specified value: 112" .  The actual number is not important as removing the offending line just results in a different number on the next run.  Guessing these values are actually pulled in by the platform automatically as the entity description and this isn't allowed to be edited directly.

**Comment by MscrmTools** [comment]
I do not reproduce this error message but maybe it has been fixed with latest version.
I will close this issue. Please reopen it if it still fails for you
