### ISSUE TITLE
How can I disable Check for Updates and data collection?

### ISSUE THREAD

**Issue by anique9999** [MscrmTools/XrmToolBox#1113]
Hi,
As a system administrator, is there a way to disable "check for updates" for this application [via installer arguments or through registry etc.]. Also wanted to know about disabling "Data Collect" option. 
![image](https://user-images.githubusercontent.com/90675448/155109610-6622cf3d-cd13-49f2-883f-ea361540c013.png)

I want it to be disable during installation setup only. Can you please help me?

**Comment by MscrmTools** [comment]
Hi @anique9999, thank you for reporting your need. 
I can add a new registry key usage to disable data collection.

**Comment by anique9999** [comment]
Also wanted to know about disabling "Check for updates" option. 

Thank you in advance

**Comment by MscrmTools** [comment]
I can also add a registry key for that

**Comment by MscrmTools** [comment]
@anique9999 Latest version can handle your needs: https://www.xrmtoolbox.com/documentation/for-it-administrators/disabled-xrmtoolbox-features/

**Comment by anique9999** [comment]
Thank you so much.

Wanted to know one more thing, 
I want to restrict usage to specific tools only, and as per the https://www.xrmtoolbox.com/documentation/for-it-administrators/restricting-access-to-xrmtoolbox-and-plugins/ you have to create registry with that contains technical name of tools.

But I'm unable to find the technical name for the tools. How can I find these technical names of the tools [ex. Ribbon Workbench]?

**Comment by BetimBeja** [comment]
@anique9999 you can find the Technical Name of the tools in the related information section on the portal, Ribbon Workbench as an example here:
![image](https://user-images.githubusercontent.com/11160171/157183286-d6a6ce6b-6c09-4fbc-8078-755a42738a26.png)

**Comment by MscrmTools** [comment]
Actually, the technical name is the name of the C# class that exposes the tool... But you are correct, there is no way to find out easily what is this name.
For open sourced project, you can check the name of the assembly. And you can also try to use the name of the dll file without extension

**Comment by anique9999** [comment]
Hi,

Even after disabling the "Check for updates" option from the application via registry, I'm receiving this update prompt:-
![image](https://user-images.githubusercontent.com/90675448/166686301-220180df-8922-4b01-b86c-e311c2444fd7.png)

If I click on check for updates from app, it shows this prompt:- 
![image](https://user-images.githubusercontent.com/90675448/166686583-297932d7-ad72-45b0-996c-6a2b600f530c.png)


**Can you please tell me how can I disable that update prompt?**

**Comment by MscrmTools** [comment]
This update is about connection controls and is quite mandatory to be sure XrmToolBox can connect to environments.
It is not an XrmToolBox update

**Comment by anique9999** [comment]
Hi, 

After setting the registry to disable data collection option. I can still see that data collection option is checked marked in application. Note:- I'm using version 1.2022.4.55

![image](https://user-images.githubusercontent.com/90675448/168064440-c270244d-6da3-40bd-b875-4e183ba86ad0.png)
