### ISSUE TITLE
[BUG]: Cannot access XrmToolBox portal or Nuget feed. Tool library will not be functional

### ISSUE THREAD

**Issue by singapi** [MscrmTools/XrmToolBox#1116]
XrmToolbox shows "Cannot access XrmToolBox portal or Nuget feed. Tool library will not be functional" error on starting and nothing working. 

![image](https://user-images.githubusercontent.com/8726966/156372677-6766db49-8ace-4e1f-a085-990a51d3d76c.png)

- XrmToolbox 1.2022.2.54

"Configuration/Tool library" popup throws next error:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at XrmToolBox.PluginsStore.DTO.XtbPlugin.get_Files()
   at XrmToolBox.New.NewForm.PrepareCategories()
   at XrmToolBox.New.NewForm.<tsddbTools_DropDownItemClicked>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by eleung83** [comment]
I'll comment on this bug, as it was opened before mine, difficulty is that I'm guessing each plugin has a check performed to see if there's an update first, and as it can't connect to the Nuget feed, the plugin can't fully execute

**Comment by sybaris** [comment]
Same problem on version 1.2021.12.53 and 1.2022.2.54

**Comment by singapi** [comment]
I checked XrmToolbox requests on starting using Fiddler and there are no any fail statuses (all statuses have 200 OK). So, I guess the problem is with data the services return (https://api.nuget.org/v3-flatcontainer, https://www.xrmtoolbox.com/_odata/plugins).

**Comment by MscrmTools** [comment]
Hi, thank you for reporting
I'm aware of the issue and fixing this at two levels:
- Data : I've migrated a workflow to a flow but made a mistake. Data is currently being processed to fix the issue
- XrmToolBox itself : I've optimized the code to handle possibly wrong data

**Comment by MscrmTools** [comment]
and this is now fixed. Please restart XrmToolBox

**Comment by singapi** [comment]
@MscrmTools Thanks, that was very fast!

**Comment by MscrmTools** [comment]
not as fast as what I would have liked but I'm happy everyone can use XrmToolBox again

**Comment by Jorgegf97** [comment]
![image](https://user-images.githubusercontent.com/88313663/156392104-7b0fdcc1-1119-4f04-b694-38a990bd4d1c.png)

**Comment by HamzaETTH** [comment]
Same problem here on 1.2022.2.54.

**Comment by singapi** [comment]
@MscrmTools I have the same problem again.

**Comment by MscrmTools** [comment]
@singapi can you try again? this damn flow ran again...

**Comment by HamzaETTH** [comment]
> @singapi can you try again? this damn flow ran again...

it's fixed. thank you.

**Comment by singapi** [comment]
@MscrmTools Confirmed, that's fixed.

**Comment by brucear88** [comment]
The message persists on my installation (version .56), so I cannot install tools from the portal.

![image](https://user-images.githubusercontent.com/103201681/179052633-57d8aeaa-64a2-48e3-8582-f56f3e210c54.png)
