### ISSUE TITLE
[BUG] XrmToolBox is broken after update

### ISSUE THREAD

**Issue by Martype** [MscrmTools/XrmToolBox#1119]
I just updated XrmToolBox to the latest version. After doing so the application failed to start. Some exception was thrown because of Cinteros.XTB.PluginTraceViewer.dll, so I deleted this .dll from the Plugin folder. This fixed at least the application start issue, but the tool library appears to be broken, now.

![image](https://user-images.githubusercontent.com/1420317/156379631-5b64562b-a6fb-42f8-ac18-35ad8e839edc.png)

![image](https://user-images.githubusercontent.com/1420317/156379692-8109d245-6525-4cc3-a8dd-86a2c96b9d2b.png)

![image](https://user-images.githubusercontent.com/1420317/156379815-1456047c-f375-4f3b-9b0c-2facc35bfcc9.png)

************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei XrmToolBox.PluginsStore.DTO.XtbPlugin.get_Files()
   bei XrmToolBox.New.NewForm.PrepareCategories()
   bei XrmToolBox.New.NewForm.<tsddbTools_DropDownItemClicked>d__79.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

 XrmToolbox Version: 1.2022.2.54

**Comment by MscrmTools** [comment]
Please do not open issue already existing... I'm aware of the issue. I'm fixing data right now...
