### ISSUE TITLE
Latest version does not work 2nd March 2022

### ISSUE THREAD

**Issue by AndyGray-k3** [MscrmTools/XrmToolBox#1121]
Latest version worked after initial upgrade but after a restart it doesn't work.

A message bar appears at the bottom "Cannot access XrmToolBox portal or Nuget feed. Tool library will not be functional". 

Some out of the box tools work correctly (Access Checker) but others (Metadata Browser), tool library & third party tools do not work.

Deleted install & settings folders and re-install but still same.

---
- Deployment: Online
- DB Version: 9.2.22021.128
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2022.2.54

**Comment by MscrmTools** [comment]
There are already opened issue for that problem. Please do not open new ones. Fix is on its way

**Comment by t-adriann** [comment]
this bug was already reported and there is work in progress to fix it
