### ISSUE TITLE
[BUG] Library Data Incorrect For Plugin

### ISSUE THREAD

**Issue by z929669** [MscrmTools/XrmToolBox#1122]
XRMToolBox versioning for this plugin was borked in the recent update. Plugin: https://www.xrmtoolbox.com/plugins/AB.PersonalViewsChartsDBTransferTool/

User is incorrectly notified that the plugin has an update, but the update appears to be for the oldest version of the plugin, which itself had a versioning issue. Once the update is applied, user continues to get the plugin update nag. What's more, the plugin DLL is likely broken.

**To Reproduce broken versioning**
1. Install the plugin (or update if exists ... BUT save the plugin DLL if updating. The new one is likely borked)
2. Close XRMToolBox
3. Reload XRMToolBox --> plugin update nag

**To Reproduce broken plugin ?DLL?**
1. Navigate to %AppData%\MscrmTools\XrmToolBox\NugetPlugins
2. Note two concurrent versions of this plugin
3. Load the plugin in XRMToolBox, connecting to data source/destination
4. Load users
5. Select any user(s)
6. Load views/dashboards/charts
7. Get error --> "Unable to cast object of type ‘Microsoft.Xrm.Tooling.Connector.CrmServiceClient’ to type ‘Microsoft.Xrm.Sdk.Client.OrganizationServiceproxy’

**Expected behavior**
no error on loading user assets

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - XrmToolbox Version: 1.2022.2.54
 - Tool version: 1.0.2 & 1.0.0.7

**Additional context**
I think the problem is that XRMToolBox library data was somehow reverted or messed up to point to an old and broken version of this plugin ... or the libreary metadata has versioning conflicts for this plugin ... or the library metadata is pointing to the wrong package for this plugin.

**Comment by z929669** [comment]
Well, I just now updated this plugin, and the versioning seems to reflect current (1.0.0.7). It also is working as expected now. So either you guys fixed it, or it was some issue with the servers or propagation since updating XRMTooBox?

**Comment by MscrmTools** [comment]
@z929669 there was an issue yesterday with tools data on backend side. I guess this is why you got this kind of error
