### ISSUE TITLE
Easy Translator fails when importing attributes

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#113]
I kept getting an error if my translation file included 'attributes'
>Easy Translator - V1.2015.4.3
>Connecting to CRM 2015 Update (Spring) (7.1.0.1059)
>(Only English configured in instance)

Tested exporting 'only' attributes and saving, then re-importing that (unchanged) file and I get the same error:
![2015-04-17_8-11-21](https://cloud.githubusercontent.com/assets/6276300/7201815/b8e41850-e4d9-11e4-9943-d074f2e2a700.png)

**Comment by MscrmTools** [comment]
Maybe some regression with the new version. I will need to check on my own what is the problem.

Thank you for reporting

**Comment by mscottsewell** [comment]
I was able to export -> modify -> import and publish: Entities, Views, Forms, Tabs, and Sections. - 
Only the "attributes" translation caused problems.
(I haven't tried this version of the plugin on CRM 7.0.1 or earlier - the issue may be with CRM.)

**Comment by MscrmTools** [comment]
I do not have access anymore to a Carina organization, mine are all inactive...

Can you give me an access to your organization so that I can find the cause of the error?

**Comment by MscrmTools** [comment]
Thank you for the organization

The problem seems to occur with calculated fields (or at least, the date and state attribute associated with calculated fields)

I'm still investigating anyway

**Comment by MscrmTools** [comment]
For now, I will just report errors and not stop process. 

It seems more a product bug...
