### ISSUE TITLE
Cant install XrmToolBox 1.2022.2.54

### ISSUE THREAD

**Issue by leibishr** [MscrmTools/XrmToolBox#1130]
I'm having trouble installing the latest version of XrmToolBox on my device. I fully removed the previous version i had with all its files and folders.
After downloading the zip package from the main site i unblocked the file and tried opening the executable XrmToolBox.exe but got the following error.
![image](https://user-images.githubusercontent.com/28367735/158604066-48478c75-6d35-4068-8450-813fa0f7ca95.png)

What can i do so i can continue using XrmToolBox?

Thank You!

**Comment by MscrmTools** [comment]
Please follow instructions [here](https://github.com/MscrmTools/XrmToolBox/issues/1093)

**Comment by leibishr** [comment]
Thanks, it worked.
