### ISSUE TITLE
Dependencies they don't care

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1132]
See my issue: https://github.com/rappen/FetchXMLBuilder/issues/679
The FXB version 1.2022.3.1 was installed in a XTB version 1.2021.12.53.
But the FXB has dependency >= 1.2022.2.54 to make sure the versions work.

So it seems like the dependencies don't really work all the way...
It may be I misunderstand this someway 🤔

---
- Deployment: Online
- DB Version: 9.2.22022.134
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2022.2.54

**Comment by MscrmTools** [comment]
I would like to understand if the Tool Library did indicate that the version was not compatible but let the update doable, or if there was no warning at all... 
I will investigate this

**Comment by rappen** [comment]
I don't know all info, but it seems the user had version 1.2021.12.53, and was installing FXB 1.2022.3.1... probably easily...
Maybe @ok-ay can add any more info?

**Comment by ok-ay** [comment]
I was manually installing FXB so perhaps this played a part in missing an incompatible notice.

**Comment by MscrmTools** [comment]
Manual installation cannot check for compatibility. It's just for Tool Library

**Comment by rappen** [comment]
Yep. I guess I'll close this.
