### ISSUE TITLE
[BUG] Microsoft Login Control no longer works

### ISSUE THREAD

**Issue by duckz0r** [MscrmTools/XrmToolBox#1139]
**Describe the bug**
Since today I've not been able to connect to any of my previous saved connections. These connections were all saved with Microsoft Login Control and Office365 logins. 

As I've seen through Microsoft documentation they have removed the authentication through Office365 "Effective April 2022, the authentication protocol will be retired for all new and existing environments within a tenant."

[https://docs.microsoft.com/en-us/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-dataverse](https://docs.microsoft.com/en-us/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-dataverse)

**To Reproduce**
Connect to an existing environment or create a new one with Microsoft Login Control and login with an Office365 auth

**Screenshots**
![image](https://user-images.githubusercontent.com/33985359/162475496-7e4f2120-9f47-4123-9abe-ea9c3075b77e.png)

 - XrmToolbox Version: 1.2022.2.54, but i've tried with previous versions and I get the same error message

**Workaround**
If available, connect with ClientId/ClientSecret

**Comment by MscrmTools** [comment]
It's Microsoft Login Control. I don't have any power on it. 
Maybe you just have to recreate your connections but there is nothing I can do on my side

**Comment by pbojanczyk** [comment]
I'm having the same issue.  I'm unable to connect to any of my environments.  I tried to recreate the connection but it doesn't seem to fix the problem

**Comment by duckz0r** [comment]
> I'm having the same issue. I'm unable to connect to any of my environments. I tried to recreate the connection but it doesn't seem to fix the problem

As I mentioned, you can try to recreate your connections with ClientId/ClientSecret. If you have an app user to the corresponding environment this is.

**Comment by MscrmTools** [comment]
As far as I understand, there could be an outage currently.
Maybe that is the issue.
But, again, if the issue is really with Microsoft Login Control, I can't do anything

**Comment by MattB-msft** [comment]
There was an outage this morning on the global discovery system in the northamerica GEO.  this has been corrected now and you should not see this any longer.

**Comment by MattB-msft** [comment]
@duckz0r  if your still experiencing this could you let me know please? and or open a support ticket with Microsoft? 
else close this issue? 

thanks

**Comment by duckz0r** [comment]
@MattB-msft I believe the issue is resolved. I don't know if the NorthAmerica GEO affected the EMEA GEO, or if it was global, but like you said this was probably due to an outage on MS service.
