### ISSUE TITLE
[HELP] [BUG?] Connection issues

### ISSUE THREAD

**Issue by dornell2020** [MscrmTools/XrmToolBox#1142]
ERROR on exporting translations with Easy Translation - getting AADSTS50196 many times. It is an authentication loop problem - I tested successfully other tools like ERD VISIO BUILDER  - 
Status Code  400
Tried:
- creating a new New Password
- deleting Cookies & Browser Data
- Uninstall & Install tool
:-(  

Any recommendation is very much appreciated! Thank you

**Comment by chironh** [comment]
I was not sure yet if it was tenant or tool related, but it seems I'm getting multiple authentication windows and/or issues using WebResource Manager, Ribbon Workbench, .. since (I guess) the latest update?

**Comment by MscrmTools** [comment]
Microsoft is removing WS_TRUST and Office365 authentication types from environments (it started this very month).
Thus, I had to change the way the authentication is performed.
So all connections created with the wizard might be impacted.
Can you try to recreate connection using OAuth or Microsoft Login Control? That should solve the issue

**Comment by chironh** [comment]
Ah, that could be the case indeed. I'll check and let you know my findings.

**Comment by ewo2022** [comment]
I can confirm this behaviour:
Version: 1.2022.4.55 -> RibbonWorkbench crashes while publishing a solution. Login dialog opens up multiple times
back to Version: 1.2022.2.54 -> everything works fine again

**Comment by tosenau** [comment]
I can confirm this too.

I have the connection problem in every tool, that i used. Login dialog opens up multiple times. 

-> Version: 1.2022.4.55

**Comment by MscrmTools** [comment]
Latest version of connection controls fixes this issue
