### ISSUE TITLE
Restricting tools in XRMtoolbox Library

### ISSUE THREAD

**Issue by anique9999** [MscrmTools/XrmToolBox#1145]
Hi,

As an IT admin, I wanted to restrict usage to specific tools only. After following the doc mentioned on [https://www.xrmtoolbox.com/documentation/for-it-administrators/restricting-access-to-xrmtoolbox-and-plugins/], 
I created the registry :- 
![image](https://user-images.githubusercontent.com/90675448/166689206-224ff867-e2b8-413a-9336-c1ab14bea6f5.png)

But once I open the tools library, I'm able to install/uninstall all the tools available in the library. 
![image](https://user-images.githubusercontent.com/90675448/166689829-b0043243-df27-46f6-999e-ced17d50c1f9.png)

Is there a way of restricting the users to a specific tool only?

**Comment by MscrmTools** [comment]
The check is performed only when listing installed tools in the Tools tab of XrmToolBox.
So users could install any tools but only the one allowed will be listed in the tools list

**Comment by anique9999** [comment]
> one allowed will be listed in the tools list

For testing, I installed "Access Checker" and "Ribbon Workbench" tools. Only "Ribbon workbench" is allowed tool/plugin in registry.

But when I open the Tools tab, I'm able to open to "Access Checker", this should not happen since it's not allowed? 
![image](https://user-images.githubusercontent.com/90675448/166891586-6c6075d4-5f56-4d56-9009-62555236a1bd.png)
![image](https://user-images.githubusercontent.com/90675448/166891710-131c34c7-2aba-4580-8698-936138eb7112.png)

**Comment by MscrmTools** [comment]
Ok, I found a bug. The next release will also check if the tool is allowed when opening it, not only when listing the tools

**Comment by anique9999** [comment]
Can you please tell the ETA of next release?

**Comment by MscrmTools** [comment]
Already released on Wednesday
