### ISSUE TITLE
Support for CRM19 / Norwegian data center

### ISSUE THREAD

**Issue by CodeproKjonix** [MscrmTools/XrmToolBox#1147]
I can't connect to an enviroment on crm19. All my other connections work.

---
- Connection Controls Version: 1.2022.5.50
- XrmToolBox Version: 1.2022.4.55

**Comment by MattB-msft** [comment]
Support for the new geos was added to the most recent update for the Microsoft.crmsdk.tooling.connector lib. 

When xrm tool box picks it up you should be able to connect.

**Comment by MscrmTools** [comment]
I will provide a new version of connection library soon
