### ISSUE TITLE
Cross-Database query transactions & CTE

### ISSUE THREAD

**Issue by cityu-feemster** [MscrmTools/XrmToolBox#1148]
Great tool, SQL 4 CDS! Most helpful indeed.

Provided all environments are in the same tenant, is it possible to implement support for a single SQL query to access tables in more than one environment? 
As a second request, can you implement support for temp tables (i.e. create table #foo or even select * into #foo) or CTE in an environment?

Thanks,
JD Feemster
feemsterjd@cityu.edu
---
- Deployment: Online
- DB Version: 9.2.22043.151
- Connection Controls Version: 1.2022.5.50
- XrmToolBox Version: 1.2022.4.55

**Comment by MscrmTools** [comment]
Hi @cityu-feemster, please post to the appropriate [repository](https://github.com/MarkMpn/Sql4Cds/issues)
