### ISSUE TITLE
Unable to connect to only one environment

### ISSUE THREAD

**Issue by jb-impact** [MscrmTools/XrmToolBox#1149]
**Describe the bug**
Receiving an error when trying to connect to our test environment. This has happened before but disappeared on an update,

**To Reproduce**
Attempt to connect to an environment

**Expected behavior**
Successful connection

**Screenshots**
![image](https://user-images.githubusercontent.com/104577666/170071682-3b46d573-7486-4ec7-b83b-9f8369404080.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version - tried `1.2021.12.53`, `1.2022.2.54`, `1.2022.5.56` 

**Additional context**
Checked user roles. They are the same on all environments (System admin, which is not modifiable)
Also checked that `Client Access License (CAL) Information` is set to `Read-Write`
I tried deleting all connection configurations and files in the AppData folder, too.
Some of our team members are able to connect, while multiple are not. We checked the user settings side by side to make sure the are the same in Dynamics 365 as well as in XrmToolbox.
[xrmtoolbox.log](https://github.com/MscrmTools/XrmToolBox/files/8764096/change.log)

**Comment by MscrmTools** [comment]
This is clearly a problem with the env itself. Nothing I can fix on my side.
Please check you did not rename an env and the env you think you are connecting to is not the real one (it can happen that a renamed env keep the same org url name, and that can mess up things)

**Comment by jb-impact** [comment]
The environment hasn't been renamed recently. Triple checked the URL. Can you explain what you mean by `Please check you did not rename an env and the env you think you are connecting to is not the real one`? I've cleared all configs and I can access the environment by the same link in the browser.

**Comment by jb-impact** [comment]
I found a fix if anyone runs into the same issue. Delete the non-working connection and add a new one. Use the connection string option instead of the wizard. Use the following string and replace with your URL:
`AuthType=Office365;Url=https://contoso.crm.dynamics.com`
Leaving out the username and password must have the app grab credentials from SSO. Of course, this only works if you're logged into Windows with the same account you're logging in with.
