### ISSUE TITLE
Office 365 end point for Australian data centres

### ISSUE THREAD

**Issue by hprasad-dc** [MscrmTools/XrmToolBox#115]
Hello,
I have setup a CRM Online demo environment which is provisioned on crm6.dynamics.com endpoint.  Can you please add this end point to the server list.  Alternatively it would be great if the end points are configurable.  Much appreciated.
Thanks.

**Comment by daryllabar** [comment]
@MscrmTools  There are a couple possibilities for this...   Could go crazy and screen scrape [this site](https://msdn.microsoft.com/en-us/library/gg328127.aspx) for a list of urls each time.  Although it's a fun idea, it's extremely brittle.  I think the best plan is to have the default values hard coded, and then allow for the user to add one manually as a stop gap until the next release...

**Comment by hprasad-dc** [comment]
Hi Daryl,
Thanks for the quick response.  Allowing the user to manually add an end point would be a great idea.  Right now, this functionality is not available so I am stuck.
Regards,
Hari

**Comment by isultan69** [comment]
If you are stucked you can download the source code and add the servername by yoursef and compile it until the next version is released

**Comment by hprasad-dc** [comment]
Thanks for all the responses.  I noticed v1.2015.3.10 has addressed this issue.  Downloaded the latest release and it is working fine.
