### ISSUE TITLE
[BUG] A task was Canceled

### ISSUE THREAD

**Issue by DianaTejeda** [MscrmTools/XrmToolBox#1151]
**Description**
While using the Audit History extractor, the Exporting of the data takes too long, and after a while it shows an Error saying "A task was Canceled". This happens since the latest update from last week.

**To Reproduce**
Select Opportunity in Entity, using the Opportunity ID as the Primary Key field, Filter data using a Personal View and click Export to CSV. Wait for a few minutes until the Error is displayed.

**Expected behavior**
Finish Downloading the data with a File Completed message in less than 15 minutes.

**Screenshots**
![image](https://user-images.githubusercontent.com/47722014/172231723-64230a20-4357-4359-bc86-219c51e7a088.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version 1.2022.5.56
 - Tool version 2.2021.8.1

**Additional context**
Preview Data option works correctly. I already re-created a new connection.

**Comment by MscrmTools** [comment]
Please post this issue in the [appropriate repository](https://github.com/alduzzen1985/Audit-History-Extractor)
