### ISSUE TITLE
Attribute Audit Explorer is not working

### ISSUE THREAD

**Issue by michaelsthomas007** [MscrmTools/XrmToolBox#1154]
I am trying to get new value/old value information from the Queue Item entity using the Attribute Audit Explorer. I am getting the attached error when trying to extract data. I have also used Audit History Extractor and that seemed to work on every entity except for Queue items. 

---
- Deployment: Online
- DB Version: 9.2.22043.153
- Connection Controls Version: 1.2022.5.51
- XrmToolBox Version: 1.2022.5.56
![toolboxerror2](https://user-images.githubusercontent.com/107259476/173074297-12516784-dc21-4447-81c1-47acf825180e.PNG)

**Comment by MscrmTools** [comment]
Please open an issue on the repository of the tool

**Comment by StephaneSeguin** [comment]
Same here

**Comment by MscrmTools** [comment]
I will close the issue since I'm not the owner of this tool.
