### ISSUE TITLE
Deleting `manifest.json` during debugging

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1155]
Removing the `Plugins\manifest.json` during testing and debugging helps, I think.

Suggest the template post-build should have this:
```
IF $(ConfigurationName) == Debug (
      IF NOT EXIST Plugins mkdir Plugins
      xcopy "$(TargetDir)$(TargetFileName)" "$(TargetDir)Plugins\" /Y
      xcopy "$(TargetDir)$(TargetName).pdb" "$(TargetDir)Plugins\" /Y
      del "$(TargetDir)Plugins\manifest.json"
)
```

---
- Connection Controls Version: 1.2022.5.51
- XrmToolBox Version: 1.2022.5.56

**Comment by MscrmTools** [comment]
This will be included in next release
Thanks
