### ISSUE TITLE
Regarding Data Collection

### ISSUE THREAD

**Issue by anique9999** [MscrmTools/XrmToolBox#1156]
Hi,

After setting the registry to disable data collection option. I can still see that data collection option is checked marked in application. Note:- I'm using version 1.2022.4.55

![image](https://user-images.githubusercontent.com/90675448/174779243-9bf18271-5487-4132-bf44-dd0a1ae8a61f.png)

**Comment by MscrmTools** [comment]
Hi @anique9999, there is no link between both settings. One is for the user (in the options), the other is for the admin (in the registry). Registry takes precedence over option
