### ISSUE TITLE
Moving components to be unmanaged

### ISSUE THREAD

**Issue by arangas** [MscrmTools/XrmToolBox#116]
Hello,

The Solutions Component Mover moves components from managed to unmanaged solutions but the components themselves stay marked as Managed. Is it possible to switch them to Unmanaged? :scream_cat:

Cheers!

**Comment by MscrmTools** [comment]
Oh, I see...

Can you just confirm that adding a managed component to an unmanaged solution make this component marked as unmanaged (when performing this manually)?

**Comment by arangas** [comment]
It does not and leaves it managed. I'm hoping its possible to switch it to unmanaged...

**Comment by MscrmTools** [comment]
Sure, it is possible, as for now, it just a copy of an existing item. So I just need to change this value when creating the new solution component. 
This will be fixed for May release

**Comment by MscrmTools** [comment]
@arangas I just tested the scenario. Even manually the item keep its managed state. So I can't do anything about this. Sorry

**Comment by arangas** [comment]
OK - thanks for trying!
