### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by REPhilpott** [MscrmTools/XrmToolBox#1160]
**Describe the bug**
Bulk Form Attribute Manager - cannot find in Tools

**To Reproduce**
Using latest version of Xrmtoolbox. Bulk Form Attribute Manager not showing

**Expected behavior**
Some users are able to see the Bulk Form Attribute Manager and therefore can select and install from the tools library

![image](https://user-images.githubusercontent.com/100853063/177933786-37bae0bd-984c-4a93-99a3-92747da82714.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version - 1,2022.5.56
 - Tool version - ?

**Additional context**

**Comment by MscrmTools** [comment]
It's contained in Form Related Tools 

<img width="503" alt="image" src="https://user-images.githubusercontent.com/10774317/177941648-86de9f43-c5d5-414b-ae13-396cae5d02d2.png">

**Comment by REPhilpott** [comment]
Thank you for your prompt reply. But after installation, Form related tools do not show up in the tool list e.g.

![image](https://user-images.githubusercontent.com/100853063/177947937-8833cb67-fd33-4a4b-bcbc-693d8389640f.png)

Many thanks

**Comment by MscrmTools** [comment]
Once installed, search for Bulk Form Attribute Manager
