### ISSUE TITLE
New tool still pending

### ISSUE THREAD

**Issue by Sellouu** [MscrmTools/XrmToolBox#1163]
Hello,

I submitted a new tool 6 days ago, it was rejected.
So a new version was published to NuGet and upload the tool again ... but it's still Pending at the moment...
Also I already have done a "Force plugin update" and it is the latest version now...

When can I expect another validation run?

Kind regards.
Ahmed Sellou

**Comment by MscrmTools** [comment]
The validation is a manual process and I just did not have time to do it today. 
I will try tomorrow

**Comment by Sellouu** [comment]
Hello,
How can I add the assembly to Plugins folder through command line?
I am using the below commands
1- to create spec file
nuget spec {project name.csproj} 
2- to create the nuget Package
 "Nuget pack"

**Comment by MscrmTools** [comment]
don't know... I'm using Nuget Package Explorer and/or a nuspec file that indicates to use a Plugins subFolder

See [here](https://github.com/MscrmTools/MsCrmTools.Translator/blob/master/MsCrmTools.Translator/MscrmTools.Translator.nuspec)

**Comment by Sellouu** [comment]
I published a new package on Nuget with new version and I have done a "Force plugin update" 
but the status still "Rejected"

**Comment by BetimBeja** [comment]
Hi @Sellouu ,
check your spec file... the `target` for your assembly should be like the following...
```xml
<files>
    <file src="bin\$configuration$\net462\XrmToolBox\plugins\AlbanianXrm.EarlyBound.dll" target="lib\net462\plugins" />
</files>
```
https://github.com/albanian-xrm/Early-Bound/blob/master/AlbanianXrm.EarlyBound/AlbanianXrm.EarlyBound.nuspec#L29

**Comment by Sellouu** [comment]
Thank you dears,
I updated the plugin and waiting for validation

**Comment by Sellouu** [comment]
@MscrmTools , The tool's status still waiting for validation !
