### ISSUE TITLE
Tool validated but not exists in Tool Library

### ISSUE THREAD

**Issue by Sellouu** [MscrmTools/XrmToolBox#1164]
Hello,

I submitted a new tool and it has been validated 48 hours ago,
And sent to me it will be available soon in XrmToolBox Tool Library but it doesn't shown in the tool library yet .

When can I expect it will be exist in XrmToolBox Tool Library?

Kind regards.
Ahmed Sellou

**Comment by MscrmTools** [comment]
It shows up for me
![image](https://user-images.githubusercontent.com/10774317/182021241-0352bb62-4723-48b5-bb69-622debef1eb9.png)
