### ISSUE TITLE
Environment highlighting not working

### ISSUE THREAD

**Issue by ErnstWolthaus** [MscrmTools/XrmToolBox#1169]
Hi,

I'd like to set my XRMToolbox color to Red when working with the production connection.
But it seems setting the Environment Highlight does not work. 
Whenever I open a new XRMToolbox with the PRD connection or change to PRD connection, nothing happens.

<img width="712" alt="Untitled" src="https://user-images.githubusercontent.com/23701708/190430548-72a2b625-6524-4008-afc4-7d831a3dd658.png">

**Comment by MscrmTools** [comment]
I just tested it and it worked as expected.
Can you check in the connections file if the highlight values are there?

**Comment by ErnstWolthaus** [comment]
not there...
<img width="782" alt="Untitled" src="https://user-images.githubusercontent.com/23701708/190442547-dd56d229-aac7-43fa-ae76-3407bd440d37.png">

**Comment by MscrmTools** [comment]
Ok, I can see you are connecting to an OnPremise env, let me check the code if something is wrong with this kind of connection

**Comment by MscrmTools** [comment]
Can you confirm you are using latest version of XrmToolBox?

**Comment by ErnstWolthaus** [comment]
Its an online env....

Op do 15 sep. 2022 17:32 schreef MscrmTools ***@***.***>:

**Comment by MscrmTools** [comment]
The authtype is AD... 
Can you try to create a new connection without using the wizard, but Oauth or Microsoft Login Control? and see if it works better there

**Comment by ErnstWolthaus** [comment]
Yep, that works. Thanks for the support!
