### ISSUE TITLE
Unable to Update Plug-ins

### ISSUE THREAD

**Issue by Rasmus-Petersen-RLL-Sampension** [MscrmTools/XrmToolBox#1180]
The toolbox tells me I have 2 tools ready to be updated:
* Attribute Manager
* Soaplogger

No matter what I do these tools can't be updated, what is wrong?

Here's a cutout of the tools update dialog from the toolbox:
![image](https://user-images.githubusercontent.com/109732477/199000189-0524b44f-2b7a-44dc-b1e1-1958c4770df8.png)

EDIT: Removed reference to plug-in that could actually be updated.

---
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2022.10.58

**Comment by MscrmTools** [comment]
Hi, this happens because of incorrect Nuget packages for these tools.
I will contact tools owner so they can fix their packages

**Comment by MscrmTools** [comment]
Fixed for Attribute Manager
I still do not have answer for SoapLogger

**Comment by MscrmTools** [comment]
Just cleaning issue here. I did not have any answer for SoapLogger.
