### ISSUE TITLE
Onpremise Connection replaces stored  XML elements and causes error when connecting again

### ISSUE THREAD

**Issue by zsuchacek** [MscrmTools/XrmToolBox#1181]
Dearl all, could you please fix this issue regarding to Connection Controls?

Steps to reproduce:

- Create a new Connecction
- Use Connection wizard
- Enter the URL for onpremise Organization including FQDN, for example: https://czdmv233.llpdemo.local/unicareqatemp/
- Pass thru the wizzard until it is succesfuly finished and Connecction is saved.
- Try to use this Connection, error is shown:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/117166227/199218436-01c66fd3-204c-450c-8f02-48ee5ac9bdd6.png">

- Exit Xrmtoolbox and find connection xml file.
- Find and edit this particular Connection - add missing FQDN(in this case .llpdemo.local) to these XML Elements: OrganizationDataServiceUrl, ServerName, WebApplicationUrl
- Save XML and Run Xrmtoolbox again
- Use previously created Connection, everything is OK from now:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/117166227/199219033-87494a42-4b04-4e91-989d-dec50428f9b7.png">

- Exit Xrmtoolbox and find connection xml file.
- Some XML elements changes are rolled back - without FQDN(in this case .llpdemo.local), but Connection still works.
- After some time when Connection throwns errors again has to be edited again.

This issues exists from begining as far as I remember, but now it is really bothering.

Thank you very much in advance!

---
- Deployment: OnPremise
- DB Version: 9.1.12.17
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2022.10.58

**Comment by MscrmTools** [comment]
As far as I know, the issue is not on XrmToolBox but on your onpremise configuration.
The property you mentioned are retrieved from your configuration.
So you should add the FQDN suffix in your onpremise configuration. And connection controls will retrieve them properly

**Comment by zsuchacek** [comment]
Thank you very much for quick response. Now I have bullets for IT department.
Problem solved.
