### ISSUE TITLE
[BUG] Sockeye.ViewTransfer issue

### ISSUE THREAD

**Issue by romeusantiago** [MscrmTools/XrmToolBox#1187]
**Describe the bug**
When I try to run the Sockeye.ViewTransfer plugin, the screen error attached appears.

**To Reproduce**
Download XRM Toolbox, execute, download the Sockeye.ViewTransfer plugin and try to execute it.

**Expected behavior**
Plugin open and let me use it. ;)

Screenshots

![image](https://user-images.githubusercontent.com/15317054/205356783-978b7d6c-32aa-4d56-8837-d9636e3e84b2.png)

 **- XrmToolbox Version:** v1.2022.11.59
 **- Tool version: Version:** 1.2018.4.1

**Comment by MscrmTools** [comment]
Please check with the developer directly. Nothing I can do here to fix this issue
