### ISSUE TITLE
[BUG] Can't Open XrmToolbox For Turkish Locale

### ISSUE THREAD

**Issue by sahinciftci-uzmancrm** [MscrmTools/XrmToolBox#1194]
**Describe the bug**
There is a character in Turkish alphabet as "ı" (equivalent of lower I). Which is the reason XrmToolbox can't find dlls.

**To Reproduce**
Run XrmToolbox in a computer which has Turkish Locale

**Expected behavior**
An error message will occur at start and XrmToolbox will get closed.

**Screenshots**
![image](https://user-images.githubusercontent.com/86140755/209147573-3a44a5c1-07ae-44d9-9251-882462ebefbf.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version : Any Version
 - Tool version: Any Tool

**Additional context**

**Comment by MscrmTools** [comment]
Thanks for reporting.
What seems strange to me is that standard "i" character seems to be replaced with the special turkish character by the system. I don't even understand how is this possible...
