### ISSUE TITLE
Unable to connect CRM

### ISSUE THREAD

**Issue by rmuhammed** [MscrmTools/XrmToolBox#1197]
connecting **crm11**.dynamics.com

getting the following error.

I was able to connect couple of months back months back
---------------------------
Error
---------------------------
ERROR REQUESTING Token FROM THE Authentication context - General ADAL Error

Federated service at https://autologon.microsoftazuread-sso.com/sja.org.uk/winauth/trust/2005/usernamemixed?client-request-id=188cd852-228e-430f-a06a-7bec46729ecf returned error: Authentication Failure => Federated service at https://autologon.microsoftazuread-sso.com/sja.org.uk/winauth/trust/2005/usernamemixed?client-request-id=188cd852-228e-430f-a06a-7bec46729ecf returned error: Authentication FailureException while trying to connect Discovery Server, (Global Discovery) URI is = https://globaldisco.crm.dynamics.com/api/discovery/v2.0/Instances

Federated service at https://autologon.microsoftazuread-sso.com/sja.org.uk/winauth/trust/2005/usernamemixed?client-request-id=188cd852-228e-430f-a06a-7bec46729ecf returned error: Authentication Failure => Federated service at https://autologon.microsoftazuread-sso.com/sja.org.uk/winauth/trust/2005/usernamemixed?client-request-id=188cd852-228e-430f-a06a-7bec46729ecf returned error: Authentication FailureNo Organizations Found, Searched online. Region Setting = GBR

No Organizations Found, Searched online. Region Setting = GBRUnable to Login to Dynamics CRM

Unable to Login to Dynamics CRM
---------------------------
OK   
---------------------------

---
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2022.11.59

**Comment by MscrmTools** [comment]
@rmuhammed what kind of connection are you using? What happens with Microsoft Login Control?

**Comment by rmuhammed** [comment]
@MscrmTools - I am using Connection Wizard and Microsoft Login Control
![image](https://user-images.githubusercontent.com/18535928/211029576-a8e5801b-c7ad-4204-a46a-fcd7e4c0a04e.png)

**Comment by MscrmTools** [comment]
Connection Wizard shouldn't be used anymore as Office365 auth protocol has been removed.
But if an issue occurs when using Microsoft Login Control, then I guess the issue is on MS or your IT side. That should not be due to any XrmToolBox code change.

**Comment by rmuhammed** [comment]
I am able to login to CRM via browser

**Comment by rmuhammed** [comment]
It worked. Thank you!
