### ISSUE TITLE
Opening with overridepath AND other parameters -> breaks after

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1199]
Installing from Tool Library, needs to restart, it breaks probably because I have an other overridepath.
My link: `C:\Dev\XrmToolBox\XrmToolBox.exe /overridepath:c:\Users\JonasRapp\OneDrive\XrmToolBox\`

```
Error Time: 2023-01-11 10:21:49.757
System.ArgumentException
Illegal characters in path.
mscorlib
at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at XrmToolBox.Extensibility.Paths.OverrideRootPath(String newRootPath)
   at XrmToolBox.Program.Main(String[] args)
```
![image](https://user-images.githubusercontent.com/2572253/211768190-95730a15-4278-4ff7-89c3-633c3b130568.png)

---
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2023.1.60

**Comment by rappen** [comment]
Everyone?
If it has to restart XTB, this error gets either when it's exiting or when it's starting again. Not sure which one...

**Comment by rappen** [comment]
Same issue when I open from URL Prototol:

My settings in Regedit:
![image](https://user-images.githubusercontent.com/2572253/212160329-ac596360-bd86-4d9c-a957-f56e60c95655.png)

Command: `"C:\Dev\XrmToolBox\XrmToolBox.exe" /overridepath:"c:\Users\JonasRapp\OneDrive\XrmToolBox\" "%1"`

Exact same error message.
So it's not related to Tool Library, rather a general one, when opening with other parameters.

**Comment by rappen** [comment]
Note: working from VS with these cmdline params, it works.

![image](https://user-images.githubusercontent.com/2572253/212161682-86aa5dc4-1076-462f-ab1a-6eab051230de.png)

Probably issue with mixing plain text and encoded...

**Comment by rappen** [comment]
More details about this issue: https://www.screencast.com/t/AcBifQfs7

**Comment by rappen** [comment]
Unfortunately not quite done...

This is a sample RegEdit:
![image](https://user-images.githubusercontent.com/2572253/215338171-8ce36e85-8bf7-4085-b4ba-fef0749f0a49.png)

Value:
`"C:\Dev\GitHub\XrmToolBox (MscrmTools)\XrmToolBox\bin\Debug\XrmToolBox.exe" /overridepath:"C:\Dev\XTB\" "%1"`

If I use a standard setup, I have this. Same issue:
`"C:\Dev\XrmToolBox\XrmToolBox.exe" /overridepath:"C:\Users\JonasRapp\AppData\Roaming\MscrmTools\XrmToolBox" "%1"`

I use this link from the docs https://www.xrmtoolbox.com/documentation/for-developers/implement-application-protocol/
`xrmtoolbox:%2Fplugin%3A"A%20Sample%20Tool"%20%2Fconnection%3A"DEMO"%20%2Fdata%3A"Hello%20World"`

I dig into XTB code, and I see that we only get one parameter in the `args`:
![image](https://user-images.githubusercontent.com/2572253/215338695-a850a94c-addc-4de4-a557-3f3f34c47d0b.png)

The first arrow should have a quote there. I have no idea why it is like that.

It should be two, the first one `/overridepath:"C:\Dev\XTB\"` and the second one `xrmtoolbox:"2Fplugin.....`.

So the parameters are not cut off in the correct places.

--

If I manually change the RegEdit to remove the quotes of the overridepath like this:
`"C:\Dev\GitHub\XrmToolBox (MscrmTools)\XrmToolBox\bin\Debug\XrmToolBox.exe" /overridepath:C:\Dev\XTB\ "%1"`
it works just fine. But should we?

--

*I know, it may all be only in my head... 
Sometimes it just works, others it's impossible.*

**Comment by MscrmTools** [comment]
Here is what I have... seems to be not the same behavior
Registry
![image](https://user-images.githubusercontent.com/10774317/215428706-e0f2ff7c-4981-4399-9ba2-56f0dd843d27.png)

Result when opening link
![image](https://user-images.githubusercontent.com/10774317/215428677-b12f32a9-0b88-4770-a630-7f25dda83bcf.png)
