### ISSUE TITLE
Icon for error messages seems to be FXB

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1200]
I was not using FXB, but I get this with an error...

![image](https://user-images.githubusercontent.com/2572253/211769287-2485d8fa-96fb-4fd8-921a-74c4fddd6c93.png)

**Comment by MscrmTools** [comment]
It comes from one of your PR :)

https://github.com/MscrmTools/XrmToolBox/pull/1109/files#diff-ca19737640d542569ed4eadb74f17b05423215c111ae5c353c61338bf5b59e65R165

**Comment by MscrmTools** [comment]
I will remove it
