### ISSUE TITLE
Example Plugin does not show Github links

### ISSUE THREAD

**Issue by glosrob** [MscrmTools/XrmToolBox#1203]
**Describe the bug**
Using the Visual Studio template create an example tool which implements IGithubPlugin interface. However, on running the tool, the github links are not visible.

**To Reproduce**
Download the Visual Studio template
Create a new project using the template
Setup debugging and start the tool

**Expected behavior**
Implementing IGithubPlugin should show links to github.

**Screenshots**
![image](https://user-images.githubusercontent.com/2010333/213875526-650b5dd9-dc26-4aa4-bc5c-b88ad6adda7f.png)

**Desktop (please complete the following information):**
 - 1.2022.11.59
 - N/A (sample tool)

**Additional context**
Using Visual Studio 2019

**Comment by MscrmTools** [comment]
The menu should be visible in Help menu of XrmToolBox.
Is that not the case?

**Comment by glosrob** [comment]
Think Im getting confused with the SampleTool in this repo and the tool you get by default in VisualStudio template. Confirming that now...

**Comment by glosrob** [comment]
Yep - brainfart on my part - can just close this one!
