### ISSUE TITLE
[BUG] Plugin assembly error

### ISSUE THREAD

**Issue by zburakguven** [MscrmTools/XrmToolBox#1207]
**Describe the bug**
I have downloaded the latest version and installed some plugins. But everytime when I try to start the app, I receive the "Could not load file or assembly" error.

**To Reproduce**
It's happening because of "toLower()" in PluginManagerExtended.cs line number : 141

<img width="682" alt="image" src="https://user-images.githubusercontent.com/58566925/214057624-e3f4b603-82c9-416f-b6bc-c19cdc26f239.png">

But after to lower it seems like : 
<img width="711" alt="image" src="https://user-images.githubusercontent.com/58566925/214057726-896b9d34-46a2-4c93-836b-086d949e136b.png">

**Expected behavior**
When I removed the "toLower" in line number 141, it works fine.

**Screenshots**

**Desktop (please complete the following information):**
 - XrmToolbox Version : v1.2023.1.60
 - Tool version

**Additional context**

Fyi,

**Comment by MscrmTools** [comment]
We have an opened issue with Turkish locale... Is that your case?

**Comment by zburakguven** [comment]
Sorry, I missed that. I think it's the same. Although my computer language is not Turkish, yet it seems the identical issue.

**Comment by MscrmTools** [comment]
Ok, there is PR to fix the issue. That would be for next release of XrmToolBox

**Comment by zburakguven** [comment]
👍

**Comment by zburakguven** [comment]
👍
