### ISSUE TITLE
Release version in the zip file name

### ISSUE THREAD

**Issue by AMgdy** [MscrmTools/XrmToolBox#121]
Hello,

Kindly can you rename/update/mark the releases zip files with the version number instead of XrmToolBox.zip so later we easily differentiate between the releases?

Thanks.

**Comment by mscottsewell** [comment]
Sorry - :thumbsdown:  from my perspective - I like being able to right-click and 'expand' the files into the 'XrmToolBox' folder without having to copy the files out or rename the file.
Whenever you get an auto-update mechanism in place, maybe my opinion would change... Until then, I like it the way it is.

**Comment by MscrmTools** [comment]
I'm not sure if the idea is good or not... I think Scott got one point with his comment...

**Comment by AMgdy** [comment]
I am using the tools since years and have a lot of old versions and some of it have a predefined confirmation to some CRM instances, my point of asking this question that each time you download a copy of the tools you end up of a list of files in Downloads folder like: XrmToolBox.zip XrmToolBox (1).zip XrmToolBox (2).zip and so one and it's have to retrieve or check a specific version unless you have to open all of the files.

Showing the version number in the in the release file name will help to much when you distribute, share and save/archive the versions.

This was just a recommendation and sure you entitled to do whatever you like since you're the owner of the project :)

Thanks.

**Comment by daryllabar** [comment]
You should be able to used the created on date of the zip to get a pretty good guess as to what version of the file it is.  You could also rename the zip files yourself  All pretty simple work arounds.
