### ISSUE TITLE
Add possibility to *not* show up every time we start XTB

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1210]
It might be easier (and smarter) to be here under the Advanced menu, with a checkbox there to just say "Show it every time it is started" or "Don't show it". Maybe needs three options (Never, When updates available, Always).

![image](https://user-images.githubusercontent.com/2572253/215432987-71467b0a-6a6e-4521-9f86-2605b2bba3f9.png)

---
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2023.1.62

**Comment by MscrmTools** [comment]
Something like that?

![image](https://user-images.githubusercontent.com/10774317/215707201-caa0a14a-7f2f-4364-af93-d9595ea9b0e0.png)

**Comment by rappen** [comment]
Yes!
