### ISSUE TITLE
Newest version [1.2023.1.63] crashing out of the box

### ISSUE THREAD

**Issue by michael-jordan309** [MscrmTools/XrmToolBox#1214]
**Describe the bug**
Downloaded and extracted latest [1.2023.1.63] - unable to use local storage due to laptop security so created a folder and created a shortcut to define storage location. On attempting startup I receive an error detailed below.

**To Reproduce**
See above

**Expected behavior**
The program would start

**Screenshots**

**Desktop (please complete the following information):**
 - 1.2023.1.63
 - N/A

**Additional context**
Details of the error:

Error Time: 2023-02-02 09:29:47.355
System.ComponentModel.Composition.CompositionException
The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

Resulting in: Exception has been thrown by the target of an invocation.

Resulting in: The type initializer for 'LibZ.Injected.AsmZResolver' threw an exception.

Resulting in: The type initializer for '<Module>' threw an exception.

Resulting in: An exception occurred while trying to create an instance of type 'MsCrmTools.ChartManager.Plugin'.

Resulting in: Cannot activate part 'MsCrmTools.ChartManager.Plugin'.
Element: MsCrmTools.ChartManager.Plugin -->  MsCrmTools.ChartManager.Plugin -->  DirectoryCatalog (Path="C:\Users\OITASHJORDAM\Downloads\XrmToolbox\XrmToolboxStorage\Plugins")

Resulting in: Cannot get export 'MsCrmTools.ChartManager.Plugin (ContractName="XrmToolBox.Extensibility.Interfaces.IXrmToolBoxPlugin")' from part 'MsCrmTools.ChartManager.Plugin'.
Element: MsCrmTools.ChartManager.Plugin (ContractName="XrmToolBox.Extensibility.Interfaces.IXrmToolBoxPlugin") -->  MsCrmTools.ChartManager.Plugin -->  DirectoryCatalog (Path="C:\Users\OITASHJORDAM\Downloads\XrmToolbox\XrmToolboxStorage\Plugins")

System.ComponentModel.Composition
at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at XrmToolBox.Extensibility.Manifest.ManifestLoader.<>c.<CreateManifest>b__4_0(Lazy`2 p)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()

**Comment by MscrmTools** [comment]
Can you confirm if previous version of XrmToolBox was working or have/had the same problem?
Also, is the storage folder is on a network drive or a local drive?

**Comment by michael-jordan309** [comment]
Yes, previous version did work. That's what prompted the new install. I had updated to latest version which broke things, so I just tried with a new install.

Storage folder is on local drive (subfolder of XrmToolbox folder, actually).

**Comment by MscrmTools** [comment]
I did not change anything about how tools are retrieved (this is where the error occurs) and the error message `This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms` is more about the security configuration of the computer...
I don't really know how to help you here

**Comment by michael-jordan309** [comment]
Ok - yeah, I'm running a US government managed laptop, so maybe that's the issue. I'll close this bug out then.

**Comment by chrisagriggs** [comment]
In the file XrmToolBox.exe, in the <runtime> section add: <enforceFIPSPolicy enabled="false"/>
