### ISSUE TITLE
[BUG] Tools tab doesn't show the installed tools

### ISSUE THREAD

**Issue by UrSok** [MscrmTools/XrmToolBox#1215]
**Describe the bug**
I was playing around with the additional repository feature. After removing all the additional repositories the Tools tab doesn't show the installed tools.
![image](https://user-images.githubusercontent.com/5286851/216409538-6d0e5886-696b-4709-8377-f5e6dc7dfa55.png)

If I search for SQL 4 CDS it shows up in the suggestions, but it doesn't show up in the list below.
![image](https://user-images.githubusercontent.com/5286851/216410602-7e30ae64-6619-4c4c-9826-2627f8a61ffe.png)

I'm not sure if it is related, but I have ~173 tools installed.

**Desktop (please complete the following information):**
 - XrmToolbox Version 1.2023.1.63

**Comment by MscrmTools** [comment]
What if you restart XrmToolBox ? Does the tool appears?

**Comment by MscrmTools** [comment]
Also, can I see your current settings for repositories?

**Comment by UrSok** [comment]
No, restart doesn't help.

Here are the settings for the repositories:
![image](https://user-images.githubusercontent.com/5286851/216445015-1d854e38-dcf6-4508-930c-77ecc2c618b0.png)

**Comment by MscrmTools** [comment]
Is your Plugins folder still full of tools files?
If yes, can you try to delete manifest.json file in the same folder and restart XrmToolBox

**Comment by MscrmTools** [comment]
New Tool Library should not impact tools list at all so I don't really get it what can happen here

**Comment by UrSok** [comment]
> Is your Plugins folder still full of tools files? If yes, can you try to delete manifest.json file in the same folder and restart XrmToolBox
Yes, it is. I deleted the manifest.json, but this didn't help.

**Comment by UrSok** [comment]
I'd like to add that I fixed it by removing the settings xml.
