### ISSUE TITLE
Updated tool doesn't disappear from the Update available list

### ISSUE THREAD

**Issue by bwmodular** [MscrmTools/XrmToolBox#1218]
**Describe the bug**
I'm not sure if this is a ToolBox bug or to do with the specific tool. Sorry if I'm raising this in the wrong place - let me know and I'll raise it in the appropriate repo (https://github.com/iTanzhao/EntityAccessManagement)
There is a tool ('Entity Access Management') which always shows up in the 'Update Needed' list, no matter how many times I update it. This was true with old Tool library too, so it's not due to the recent update.

**To Reproduce**
The Tool shows up in the list of tools to be updated:
![image](https://user-images.githubusercontent.com/1889586/217036523-ee676f93-fcdd-4653-abf6-129a84608979.png)

Select it and press Install. The tool goes through the motions of installing the update:
![image](https://user-images.githubusercontent.com/1889586/217036782-5e758306-b036-40f3-88de-c530bea70556.png)
but it still shows up in the updates list afterwards.

**Expected behavior**
The tool should be updated and the list should be cleared.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - XrmToolbox Version - 1.2023.1.63
 - Tool version - 1.2022.5

**Comment by MscrmTools** [comment]
It is generally due to assembly file version that was not updated to match the version number of the Nuget package. I will double check this package to understand if this is the root cause

**Comment by MscrmTools** [comment]
That's it
![image](https://user-images.githubusercontent.com/10774317/217044206-a11df8cc-4321-4033-9df2-4448f88670d9.png)

**Comment by MscrmTools** [comment]
I will contact the author

**Comment by MscrmTools** [comment]
Here is the link : https://github.com/iTanzhao/EntityAccessManagement/issues/5

**Comment by iTanzhao** [comment]
Hi All,
I have modified it, please check .

**Comment by MscrmTools** [comment]
Seems ok to me!
Thank you for fixing @iTanzhao

**Comment by bwmodular** [comment]
Thanks @MscrmTools & @iTanzhao - all working well now....
