### ISSUE TITLE
[BUG] Plugins showing installed when not

### ISSUE THREAD

**Issue by tdashworth** [MscrmTools/XrmToolBox#1219]
**Describe the bug**
Our plugin "CDS Data Migrator" is showing as installed enough though it's not. When I try to install it, it doesn't (the NugetPlugins folder is updated but that's all). 

**To Reproduce**
Do a clean install of XrmToolBox. See the plugin is showing as installed. Notice that when installing, it doesn't change things

**Expected behavior**
Install to work. 

**Screenshots**

**Desktop (please complete the following information):**
 - XrmToolbox Version 1.2023.1.63
 - Tool version 2.0.0 onwards

**Additional context**

**Comment by tdashworth** [comment]
https://github.com/Capgemini/xrm-datamigration-xrmtoolbox/issues/90

**Comment by MscrmTools** [comment]
The issue in your repository seems to indicates the issue is with the legacy tools library.
The new tool library should handle this better. The issue was due to version comparison between file version on 4 numbers and Nuget package version on 3 numbers (semantic)

**Comment by tdashworth** [comment]
Thanks for the quick response! 

I'll take a look tomorrow. 

What do you mean by "file version"?

**Comment by MscrmTools** [comment]
Right click on tool assembly -> properties.
You can see the version in the details tab

**Comment by tdashworth** [comment]
Ah, yes, we use GitVersion so the "Assembly File Version" and "Nuget Version" are different formats. Should these match? e.g. 2.0.5.0 for both?

**Comment by tdashworth** [comment]
FYI, the new tool library (LOVE IT) doesn't improve things... While it lists the previous versions, the same behaviour occurs (claims it's installed but silently fails to install).

**Comment by MscrmTools** [comment]
Ok, I will debug this tomorrow and let you know my findings

**Comment by MscrmTools** [comment]
I can see you released an update to your tool and I don't reproduce the issue:
![image](https://user-images.githubusercontent.com/10774317/217192507-e45966f5-3b0e-46d2-8349-0890c1e648f9.png)

CDS Data migrator is not installed and displayed as installable
