### ISSUE TITLE
[BUG] New Tool Library shows unhandled exception when trying to install new tools

### ISSUE THREAD

**Issue by drewbino-rcg** [MscrmTools/XrmToolBox#1220]
**Describe the bug**
The new XrmToolBox Tool Library shows an unhandled exception when trying to install any tool.

**To Reproduce**
1. Open XrmToolBox.
2. Open Tool Library: Configuration > Tool Library.
3. Check a box next to any tool that is not yet installed.
4. In the "Are you sure you want to install 1 tool" box, click Yes.
5. A dialog appears that says "Installing tools..."
6. "Downloading..." step gets a green check.
7. "Installing" step gets a red X and an unhandled exception window appears:
```
************** Exception Text **************
System.ArgumentException: Controls created on one thread cannot be parented to a control on a different thread.
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at XrmToolBox.New.PluginsForm.DisplayCategories(Dictionary`2 categories)
   at XrmToolBox.New.NewForm.PrepareCategories()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at XrmToolBox.ToolLibrary.ToolLibrary.PerformInstallation(PluginUpdates updates, Form form)
   at XrmToolBox.ToolLibrary.Forms.ToolLibraryForm.<>c__DisplayClass111_0.<tsbBulkInstall_Click>b__5(Object s, DoWorkEventArgs evt)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```
8. If you click Continue on the exception dialog and go to the Tools list in XrmToolbox, it looks like the tool is installed.

**Expected behavior**
I expect XrmToolbox to install the tool(s) without error and return to the Tool Library.

**Screenshots**
<img width="1071" alt="XrmToolbox Tool Library Exception" src="https://user-images.githubusercontent.com/64488281/217604881-7ee853bc-cbf0-4a8c-a04e-d476fe6ff8d2.png">

[Full Exception Box Message](https://github.com/MscrmTools/XrmToolBox/files/10688272/xrmtoolbox.library.exception.txt)

**Desktop (please complete the following information):**
 - XrmToolbox Version: 1.2023.1.63
 - Tool version:  happens with any tool

**Additional context**

- This is the first time I've used the new Tool Library to install/update tools.
- Deleting the XrmToolbox folders in AppData and starting over with a fresh XrmToolbox install don't fix the issue.
- The old Tool Library did not have this issue.
- My colleagues are seeing this issue as well.

**Comment by MscrmTools** [comment]
Ok, I reproduce for some tools and not for some others... I will investigate.

If it's too painful, you can revert to the legacy Tool Library in XrmToolBox settings

**Comment by drewbino-rcg** [comment]
Thank you! Legacy Tool Library works.

Not sure if it's related, but I added a separate bug report for an issue I'm having updating FetchXML Builder: #1221

**Comment by BetimBeja** [comment]
I see my tool there :) I will also debug and try to give some feedback. I am sure I did something wrong with the NuGet package or dependencies 😢

**Comment by BetimBeja** [comment]
Hey @MscrmTools 
I see some controls have been created outside of the UI Thread and that's why the error is intermittent. 
```
System.ArgumentException: Controls created on one thread cannot be parented to a control on a different thread.
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at XrmToolBox.New.PluginsForm.DisplayCategories(Dictionary`2 categories)
   at XrmToolBox.New.NewForm.PrepareCategories()
   at XrmToolBox.ToolLibrary.ToolLibrary.PerformInstallation(PluginUpdates updates, Form form)
   at XrmToolBox.ToolLibrary.Forms.ToolLibraryForm.<>c__DisplayClass111_0.<tsbBulkInstall_Click>b__5(Object s, DoWorkEventArgs evt)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

```

**Comment by MscrmTools** [comment]
I found the issue and fixed it. Please test with this version of XrmToolBox.ToolLibrary. 

[XrmToolBox.ToolLibrary.zip](https://github.com/MscrmTools/XrmToolBox/files/10694805/XrmToolBox.ToolLibrary.zip)

Not sure if XrmToolBox will allow to run with a different version of Tool Library, let me know (keep a copy of the existing assembly before replacing it)

**Comment by MscrmTools** [comment]
@BusinessPartnersZA the error looks different...

But Windows 11 ARM? Really? I even did not know it was possible to run Win32 apps in Windows ARM

**Comment by MscrmTools** [comment]
I guess you could but I won't have any way to debug on ARM... So I even don't know where to start to resolve this

**Comment by LordPhoenix-ZA** [comment]
> I guess you could but I won't have any way to debug on ARM... So I even don't know where to start to resolve this

Can always spin up a VM in Azure for you? They support ARM now
