### ISSUE TITLE
[BUG] New Tool Library doesn't update FetchXML Builder past 1.2022.5.1

### ISSUE THREAD

**Issue by drewbino-rcg** [MscrmTools/XrmToolBox#1221]
**Describe the bug**
I have FetchXML Builder version 1.2022.5.1 installed and the new Tool Library shows that an update is available. When the application restarts to install the update, the old version is still installed. Other tools update as expected.

**To Reproduce**
1. Open XrmToolBox.
2. Open Tool Library: Configuration > Tool Library.
3. Check the box next to FetchXML Builder.
4. Click Install in the toolbar.
5. In the "Are you sure you want to update 1 tool" box, click Yes.
6. A dialog appears that says "Installing tools..."
7. "Downloading..." step gets a green check.
8. "Installing" step gets a green circle, with a popup that says, "This application needs to restart to install updated tools... Click Yes to restart this application now."
9. Click Yes.
10. XrmToolBox closes and reopens.
11. Go to the Tool Library: FetchXML Builder still shows same version and that it needs an update.

**Expected behavior**
I expect XrmToolbox to install the latest version of FetchXML Builder.

**Desktop (please complete the following information):**
 - XrmToolbox Version: 1.2023.1.63
 - Tool version:  FetchXML Builder 1.2022.5.1 >> 1.2022.11.2

**Additional context**

- Other tools updated fine.
- I submitted a separate bug for a different issue I'm seeing with the new Tool Library. Not sure if they're related.:
#1220

**Comment by MscrmTools** [comment]
This one has already been reported on fetchxmlbuilder repo but I do not reproduce it

**Comment by MscrmTools** [comment]
Should be fixed now. Please reopen if not
