### ISSUE TITLE
in windows 11, checkboxes next to tools will check/uncheck on double click instead of opening the tool. 

### ISSUE THREAD

**Issue by bullardl** [MscrmTools/XrmToolBox#1223]
Hi, 

first time using in win11

there are checkboxes next to every tool on the far left hand side. attempting to open a tool by clicking or double clicking the tool just checks and unchecks the checkbox. 

this means that no tool can be opened, making the entire crmtoolbox unuseable. issue started after downloaded a new version onto a fresh install of windows 11. 

I have uninstalled and reinstalled, asked around and watched several videos as well as attempt to download the checkboxes showing on files/folders feature in windows explorer with no success. 

---
- Deployment: Online
- DB Version: 9.2.23014.168
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2023.1.63

**Comment by MscrmTools** [comment]
You are using the new Tool Library... this is not the tools list and it is not intended to open tools but to install/uninstall them
