### ISSUE TITLE
XrmToolBox Throws Exception when trying to install tools on Windows ARM

### ISSUE THREAD

**Issue by LordPhoenix-ZA** [MscrmTools/XrmToolBox#1224]
XrmToolBox runs on Windows 11 ARM but throws “Object Reference not set to an instance of an object” error when trying to install tools using the legacy option. 

![image](https://user-images.githubusercontent.com/69793257/218997389-9578e39d-be18-4910-881d-040eeb67606e.png)

**Comment by LordPhoenix-ZA** [comment]
I setup a Copy of Visual Studio 2022 and Copied your source code - Compiled and Tried to get some info to help you debug. If you want I can setup a live session with my VS on ARM @MscrmTools 

![VS Exception](https://user-images.githubusercontent.com/69793257/218996527-b7fd25e8-72eb-4de1-8fbf-2df1ab4efa72.png)

![VS Exception 2](https://user-images.githubusercontent.com/69793257/218996593-95008b05-3347-4b2f-af79-892fa3836155.png)

**Comment by MscrmTools** [comment]
Can you tell me what is the null element?

**Comment by LordPhoenix-ZA** [comment]
> Can you tell me what is the null element?

Not sure exactly what you wanna see. I have the session open still so if you can give me specific instructions I'll send over what you need.

![image](https://user-images.githubusercontent.com/69793257/218998610-19f6e147-4cc4-47e0-89ec-2dcb0c016afd.png)

**Comment by LordPhoenix-ZA** [comment]
![image](https://user-images.githubusercontent.com/69793257/219001538-90b1ba9d-148c-444a-b860-432351d6d884.png)

Found some exceptions in some ActiveX related calls. Not sure if valid.

**Comment by LordPhoenix-ZA** [comment]
So - Side note - Testing FetchXML Builder - Manual Installation

https://fetchxmlbuilder.com/manual-installation/

It installs and works as expected.

**Comment by MscrmTools** [comment]
yes, the issue seems to be with Nuget.
On the 1st screen of your second comment, three things can be null:

- findPackageById
- plugin
- plugin.NugetId

Can you check which one is the faulty one?

**Comment by LordPhoenix-ZA** [comment]
> yes, the issue seems to be with Nuget. On the 1st screen of your second comment, three things can be null:
> 
> * findPackageById
> * plugin
> * plugin.NugetId
> 
> Can you check which one is the faulty one?

Only reference I can find now with null is

 findPackageById - null

![image](https://user-images.githubusercontent.com/69793257/219030212-edc016c5-e6e2-4413-b456-faa8983f68cc.png)

**Comment by MscrmTools** [comment]
Just wondering why you are not using the new Tool Library in latest version of XrmToolBox? It does not use the same api for nuget and should eventually works

**Comment by LordPhoenix-ZA** [comment]
> Just wondering why you are not using the new Tool Library in latest version of XrmToolBox? It does not use the same api for nuget and should eventually works

Because the new tool library has issues, throws an exception, I think you might already have fixed it, but not sure if the fix is released.

**Comment by MscrmTools** [comment]
@LordPhoenix-ZA is the new tool library is ok? can we close this issue?

**Comment by LordPhoenix-ZA** [comment]
All good. We can close.
