### ISSUE TITLE
Unable to search my connections. 

### ISSUE THREAD

**Issue by mtnmuncher** [MscrmTools/XrmToolBox#1226]
Instead, when I click 'connect' I am presented with a pop-up dialog showing 'recently used connections'. As a secondary issue, this list is not my most recently used connections. Also, using the drop-down, located in lower left is very long. I was accustomed to 

1. connect
2. type the first letters of the connection
3. select from a smaller list of 2 or 3 matching the criteria from #2.

---
- Connection Controls Version: 1.2023.2.55
- XrmToolBox Version: 1.2023.1.63

**Comment by MscrmTools** [comment]
Hi @mtnmuncher ,

Thank you for your feedback!

You are currently using a beta version of connection controls. This is why you are seeing this new way of selecting a connection.

The most recently used order is based on a date that is effectively set when using a connection so I don't see how it can be the wrong order.

I guess I should add an option to use or not Most recently used connections. And if not used, replace by a search bar.

Question: before using the beta version of connection controls, did you use or not the connection files feature where you can store connection by customers or any grouping you want or did you have all your connections in a single file?

**Comment by mtnmuncher** [comment]
Got latest beta. Looks good! Cheers
