### ISSUE TITLE
Cannot Open Tool o connection

### ISSUE THREAD

**Issue by salvatored66** [MscrmTools/XrmToolBox#1227]
Good morning,

Today if I try to open any tool or connection I have the Attached  error message:

[Error.txt](https://github.com/MscrmTools/XrmToolBox/files/10792310/Error.txt)

---
- Connection Controls Version: 1.2023.2.55
- XrmToolBox Version: 1.2023.1.63

**Comment by MscrmTools** [comment]
Hi @salvatored66,

It seems you are using beta version of connection controls and this is why you are seeing this error. I have unlisted the latest beta version to fix the issue.

Can you confirm you are using beta version?

**Comment by salvatored66** [comment]
Hi on the help dialog box I see version 1.2023.1.63. What can I do to use again the tool?

Thanks
Salvatore

**Comment by salvatored66** [comment]
Hi on the help dialog box I see version 1.2023.1.63. What can I do to  use  again the tool ?

Thanks
Salvatore

**Comment by MscrmTools** [comment]
In settings, I guess you should see a Yes for Search pre release updates
![image](https://user-images.githubusercontent.com/10774317/220327514-10fb97bb-59f2-4377-afc5-88bda212da9f.png)

Put false instead and validate

Maybe you will have an error then (tell me). If so, you will have to reinstall stable version yourself by using [this package](https://www.nuget.org/api/v2/package/MscrmTools.Xrm.Connection/1.2022.10.54) (change extension to zip, extract, get files MscrmTools.Xrm.Connection... and paste them in your XrmToolBox folder)

**Comment by MscrmTools** [comment]
Should be fixed in latest version of XrmToolBox
