### ISSUE TITLE
WebResourceManager: Change color of saved but not uploaded web resource

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#123]
The idea for little UI improvement:

The work with editing web resources usually takes two steps: 
* Save file;
* Publish it; 

File name of `unsaved` file is shown in red color, while both `saved` and `published` files are shown in black.

This leads to misunderstanding: was the file published? Or it was only saved?

I think we can mark `saved` but `un-published` scripts with another color, so it would be obvious, that additional action might be required to changes take effect on end user.

**Comment by MscrmTools** [comment]
Nice suggestion! What about blue color if not published?

**Comment by shytikov** [comment]
It seems to be perfect choice!

**Comment by MscrmTools** [comment]
I worked on this issue and this new color will be available only for current displayed web resource.
