### ISSUE TITLE
[BUG] previous connections are deleted when adding a new one

### ISSUE THREAD

**Issue by magicalKhachapuri** [MscrmTools/XrmToolBox#1231]
I encountered this issue today after I updated my XrmToolbox. 
When I add a new connection all the other ones get erased, I reproduced the same behavior several times and three out of four times previous connections were deleted.

XrmToolbox Version: 1.2023.1.63

**Comment by MscrmTools** [comment]
as far as I understand, connections are not deleted BUT a screen appears as if there was no connection.
Is that the issue?

**Comment by magicalKhachapuri** [comment]
> as far as I understand, connections are not deleted BUT a screen appears as if there was no connection. Is that the issue?

No, they are deleted, because every time I also checked the 'ConnectionsList.Default.xml' folder and it contained empty `<CrmConnections xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> </CrmConnections>` - element

**Comment by MscrmTools** [comment]
I cannot reproduce this issue but I'm currently working on a new version of connection controls that unfortunately were distributed as a stable version in XrmToolBox... This is why you are getting issues I guess.

I just released a new version of XrmToolBox that avoid this issue and allows to switch back to stable version of connection controls.

Please use this latest version to avoid further problems

**Comment by MscrmTools** [comment]
You said "three out of four times", so if you have a clear repro procedure I can follow to find out why connections are being deleted...

**Comment by magicalKhachapuri** [comment]
So the steps look like this:

1. I check the connections in the 'ConnectionsList.Default.xml' file and identify that for e.g. I have one connection.
2. I launch XrmToolbox.
3. I create new connection > via Microsoft Login Control.
4. I choose the organization, give it a highlight and save it.
5. I press the connections tooltip in the bottom left corner, here I'm expecting 2 connections, one which was already there and second this new one.
6. All I can see it the connection which was created recently.
7. Then I go and check the 'ConnectionsList.Default.xml' file and I can see that previous connection was erased and instead of it a new entry has been made.

I can also do a screen capture if desired.

**Comment by MscrmTools** [comment]
That should be enough. Thank you.

**Comment by magicalKhachapuri** [comment]
This issue is fixed since last update. Thanks

**Comment by MscrmTools** [comment]
Glad to here! And sorry for the issue
