### ISSUE TITLE
[BUG] Version 1.2023.2.64  Data at the root level is invalid Line 257, position 11

### ISSUE THREAD

**Issue by bcbisme** [MscrmTools/XrmToolBox#1234]
**Describe the bug**
Upgraded and even a fresh install getting the following error.  Data at the root level is invalid. Line 257, position 11

**To Reproduce**
upgraded and fresh installs multiple times

**Expected behavior**
cannot open xrmtoolbox not getting past the error detail screen

**Screenshots**

**Desktop (please complete the following information):**
-xrmtoolbox version : 1.2023.2.64

**Additional context**
Error Time: 2023-03-01 12:16:07.622
System.Exception
Data at the root level is invalid. Line 257, position 11.
XrmToolBox
at XrmToolBox.Options.get_Instance()
   at XrmToolBox.New.NewForm.SetTheme()
   at XrmToolBox.New.NewForm..ctor(String[] args)
   at XrmToolBox.Program.Main(String[] args)
![xrmtoolbox error](https://user-images.githubusercontent.com/12277076/222230893-39feb598-f480-4417-8ca3-90c5388df42f.JPG)

**Comment by MscrmTools** [comment]
Can you check the content of the file XrmToolBox.settings.xml?

**Comment by bcbisme** [comment]
I do not see that file,  I am sending the xrmtoolbox.exe.config file

***@***.***

**Comment by bcbisme** [comment]
![xrmerror2](https://user-images.githubusercontent.com/12277076/222244419-f16ef7b1-cb64-4732-9062-7858e543f7d5.JPG)

**Comment by bcbisme** [comment]
*   By deleting the following
  *
  *   Delete content of folder C:\users\appData\your_login\Roaming\MscrmTools\XrmToolBox
  *
  *   Fixed the issue
