### ISSUE TITLE
Bigger fonts please

### ISSUE THREAD

**Issue by TanerRiffat** [MscrmTools/XrmToolBox#1236]
Any chance we can have bigger fonts? Some off us have bad eyesight and this would be very helpful as the current font is tiny e.g. See the tiny font in the assembly list in the Plugin Registration Tool:
![image](https://user-images.githubusercontent.com/86524563/222265356-0c23c946-0d01-4b07-be05-b04cda3f1a31.png)

---
- Deployment: Online
- DB Version: 9.2.23021.194
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2023.2.64

**Comment by MscrmTools** [comment]
This is something that needs to be handled per tool so I cannot do something that would be applied globally.

**Comment by HugoLeitao** [comment]
Is there way to change the font of the tool manually after installing?

**Comment by MscrmTools** [comment]
No, it's not possible and as said before, each tool should handle the capability to change the fonts
