### ISSUE TITLE
Add a possibility to use OR or AND in the categories

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1239]
If I'm now working with Data and Plugins, it always makes an AND for the selected categories.
Would be nice to make it to OR.

![image](https://user-images.githubusercontent.com/2572253/224318615-36d5267c-8c50-48ae-a866-5a9b82222a70.png)

---
- Connection Controls Version: 1.2023.2.55
- XrmToolBox Version: 1.2023.3.64

**Comment by MscrmTools** [comment]
Not sure how I could handle both OR and AND... Another button at the bottom?

**Comment by rappen** [comment]
Yes! Not both at the same time, but a flip flag.

**Comment by MscrmTools** [comment]
shouldn't be too difficult to do

**Comment by rappen** [comment]
Works!
But I think it's backward...
When it says "Use OR operator" I get no hits for Data and Plugins.
When using AND, these hits are shown.

**Comment by MscrmTools** [comment]
Well, I know it's not obvious but the text represents the action that the click will perform. So if it says "Use OR operator", it means you are currently using the AND operator.

**Comment by rappen** [comment]
Ah... I guess we need to call a proper English speaker...
