### ISSUE TITLE
Missing link to PP

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1240]
See: https://www.screencast.com/t/vkwsTNw02x

---
- Connection Controls Version: 1.2023.2.55
- XrmToolBox Version: 1.2023.3.64

**Comment by MscrmTools** [comment]
Yeah... I know... I'm painting the whole control so it cannot be clicked now... Or I need to find a way to determine that the user clicked on the icon (maybe with the click coordinates)

**Comment by MscrmTools** [comment]
it's fixed. I will provide a new test version soon

**Comment by rappen** [comment]
Works great :)
Perhaps change the tooltips over the PP?
