### ISSUE TITLE
Count number for each catagory

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1241]
Nice improvement :)

![image](https://user-images.githubusercontent.com/2572253/224321103-5947fd7a-28f2-49b4-9acb-422aa3780c5b.png)

---
- Connection Controls Version: 1.2023.2.55
- XrmToolBox Version: 1.2023.3.64

**Comment by MscrmTools** [comment]
![image](https://user-images.githubusercontent.com/10774317/224329878-d8327d98-59b6-4f33-ac80-6560636ab852.png)

**Comment by rappen** [comment]
Yes!
Just a space after colon also ;)
