### ISSUE TITLE
Show categories somewhere

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1242]
For a tool, it would be nice to see the categories.
Maybe in the hovering?

![image](https://user-images.githubusercontent.com/2572253/224321860-dc211a48-4ce3-4d4e-b721-d4a20e0bb5fa.png)

---
- Connection Controls Version: 1.2023.2.55
- XrmToolBox Version: 1.2023.3.64

**Comment by MscrmTools** [comment]
![image](https://user-images.githubusercontent.com/10774317/224329937-aa7d9481-72c9-47f0-ab0a-c7729f1eed38.png)

**Comment by rappen** [comment]
Yes!
Just a space after colon also ;)
