### ISSUE TITLE
Recently connections not sorted

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1243]
The last connected one should be at the top, but it isn't.

![image](https://user-images.githubusercontent.com/2572253/224726704-84bfcfdc-aa7e-4a7d-831c-1b948f994a8a.png)

I think it should be sorted by last-opened-connection-datetime-descending.

---
- Connection Controls Version: 1.2023.2.55
- XrmToolBox Version: 1.2023.3.64

**Comment by MscrmTools** [comment]
hum... Should work now. The bug was that the date was saved in the wrong file... I will double check
