### ISSUE TITLE
[BUG] SELECT command returns column name only, no results or data

### ISSUE THREAD

**Issue by javedwoodbine** [MscrmTools/XrmToolBox#1247]
**Describe the bug**
SELECT query is not returning any data, just returning the column name of the Entities

**To Reproduce**
Connected to the DEV environment, Ran the SQL SELECT Query

**Expected behavior**
I expected to see the data present in the Dataverse, in a blog, the SELECT statement, returned query, however when I tried, it didn't return any data, just column name

**Screenshots**
![image](https://user-images.githubusercontent.com/123564209/225960857-cd89e9fe-1ff9-413c-bb3a-fbc00fde1810.png)
![image](https://user-images.githubusercontent.com/123564209/225960946-99a3d4e2-a62c-42c6-93ac-969d4d558eea.png)

**Desktop (please complete the following information):**
XrmToolBox - 1.2023.2.64
 SQL 4 CDS

**Comment by MscrmTools** [comment]
This is an issue for a specific tool. Please open an issue on the tool repository
