### ISSUE TITLE
Add "reload plugins" functionality

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#125]
It would be _nice to have_ mechanism to reload list of plugins without restarting `XTB`.

Sometimes user already started working on something very important, but finds out that needed plugin is missing. He downloads it, unpacks to the `Plugins` folder, but to start using it he needs to restart `XTB`, thus, loose his work. 

This is not a blocker, but just _nice to have_ enhancement to have either button on toolbar, that will allow reload plugins information on request, or maybe `FileSystemWatcher` that will update list automatically accordingly to the `Plugins` folder contents.

**Comment by MscrmTools** [comment]
Fixed in DEV branch.
When a new plugin is added to the plugins directory, a prompt allows user to refresh plugins list
