### ISSUE TITLE
[BUG] [Portal] Unable to Edit My Ratings

### ISSUE THREAD

**Issue by LinnZawWin** [MscrmTools/XrmToolBox#1250]
**Describe the bug**
On xrmtoolbox.com portal, when the user selects one of the Ratings under My Ratings to Edit, the Edit Form dialogue shows the error message `The record you are looking for couldn't be found.`

**To Reproduce**
1. Log in to xrmtoolbox.com
2. Go to [My Ratings](https://www.xrmtoolbox.com/profile/my-ratings/) under profile
3. Click the menu for one of the Ratings
![image](https://user-images.githubusercontent.com/14156926/230161021-d8fc2c3f-18bc-4480-84fe-1562c1a30141.png)
4. The dialogue with an error message `The record you are looking for couldn't be found.` appears.

**Expected behavior**
Edit Form dialogue should allow the user to edit and save the existing Rating of the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/14156926/230160600-e331b258-beba-4b09-9506-cb527c08eac5.png)

**Desktop (please complete the following information):**
N/A 

**Additional context**
N/A

**Comment by MscrmTools** [comment]
Fixed
