### ISSUE TITLE
New tool still Waiting and pending for validation

### ISSUE THREAD

**Issue by Sellouu** [MscrmTools/XrmToolBox#1258]
Hello,

I submitted a new tool 6 days ago,

And it's still waiting an pending for a validation,

When can I expect a validation run to e published?

Kind regards.
Ahmed Sellou

**Comment by MscrmTools** [comment]
Hi!
Sorry for the delay but I have way too much work these days and don’t have time to validate tools.
I will try to handle validations this week

**Comment by Sellouu** [comment]
Sure and thank you for your support
