### ISSUE TITLE
Invalid DockState: Content can not be showed as "Unknown" or "Hidden".

### ISSUE THREAD

**Issue by karthikreddi2103** [MscrmTools/XrmToolBox#1263]
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

![Screenshot 2023-05-22 204624](https://github.com/MscrmTools/XrmToolBox/assets/134305747/d342300a-fcdd-4bcb-8364-d7c2329d911a)

**Comment by karthikreddi2103** [comment]
hi @MscrmTools its worked for me before but suddenly this issue came and unable to continue from here can please guide

**Comment by MscrmTools** [comment]
I guess the issue is it bye settings file. 
Please look at XrmToolBox.settings.xml file to find some dock state with value Hidden or Unknown and remove the corresponding tag

**Comment by karthikreddi2103** [comment]
XrmToolBox.settings.xml where i can get this in extracted folder i could not find this file

**Comment by MscrmTools** [comment]
This should be in C:\Users\<your_profile>\AppData\Romaing\MscrmTools\XrmToolBox\Settings

**Comment by karthikreddi2103** [comment]
>Thanks a lot that resolved my issue @MscrmTools great job 
![IMG-20230524-WA0000(1)](https://github.com/MscrmTools/XrmToolBox/assets/134305747/50723650-3131-4638-b967-6a9ae48691ad)

**Comment by karthikreddi2103** [comment]
issue resolved
