### ISSUE TITLE
FetchXML Builder won't update to the latest version

### ISSUE THREAD

**Issue by thibaug** [MscrmTools/XrmToolBox#1264]
Hi,

I'm trying to update to the latest version of FetchXML Builder, but it won't do it. I can update to a version that's 2 versions ago, but not to the most recent version. So, for example, I can update to 1.2023.11.2, but if I try and update to 1.2023.2.2, then it installs 1.2022.5.1.

1.2023.2.2
1.2023.11.2
1.2022.8.1
1.2022.5.1

![image](https://github.com/MscrmTools/XrmToolBox/assets/63127235/bf4b705d-12de-4204-bd41-3277906359da)

![image](https://github.com/MscrmTools/XrmToolBox/assets/63127235/af9895c6-91d9-49b4-bd57-8fb90baee04e)

I've tried uninstalling and reinstalling, but that didn't help. Is this a plugin dev issue? 

I'm on version 1.2023.2.64 of xrmToolbox.

TIA, 
Gilles

**Comment by MscrmTools** [comment]
Ok, so there was a bug in a previous version of XrmToolBox (or in this one, can't remember) that was downloading the wrong version. Then it was cached and this cache is reused.
To fix the issue, please clear your XrmToolBox NugetPlugins folder.
It should be located by default in C:\users\<your_login>\AppData\Roaming\MscrmTools\XrmToolBox

**Comment by thibaug** [comment]
That worked! Thanks!!
