### ISSUE TITLE
After update Connections, it crashes bad

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1266]
First, I got two updates (XTB and Connections):

![image](https://github.com/MscrmTools/XrmToolBox/assets/2572253/984b1798-d805-4deb-916c-ae850aaf90f8)

Unsure which to update first, I selected Connections.
Now it needs to restart, and after the restart, it crashes, again and again.

Details:
> Error Time: 2023-06-09 10:49:12.610
System.TypeLoadException
Method 'get_DisplaySizeFactor' in type 'XrmToolBox.Options' from assembly 'XrmToolBox, Version=1.2023.3.64, Culture=neutral, PublicKeyToken=null' does not have an implementation.
XrmToolBox
at XrmToolBox.New.NewForm..ctor(String[] args)
   at XrmToolBox.Program.Main(String[] args)

**Comment by MscrmTools** [comment]
You are using the beta version of XrmToolBox. There is now a public release 1.2023.6.65. Please use this one and you should be good

**Comment by rappen** [comment]
Yep, works good.
