### ISSUE TITLE
Tool screen for installed tools broken?

### ISSUE THREAD

**Issue by urklnme218** [MscrmTools/XrmToolBox#1272]
The search box for 'Tools' appears to match only against the tool name beginning at the first character of the tool name rather than looking for a match anywhere in the tool name.  

Is this how it is supposed to work?

Maybe my version is broken as I cannot even see a list of my installed tools then filter based on that.

---
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2023.2.64

**Comment by MscrmTools** [comment]
I can search with a term contained in the name of the tool
<img width="517" alt="image" src="https://github.com/MscrmTools/XrmToolBox/assets/10774317/80dce8cb-ffbd-4b94-b09d-86f9d7b06e31">

**Comment by urklnme218** [comment]
ok.  thanks.  I will see what I can do to repair or upgrade.
