### ISSUE TITLE
Feedback: lots of problems with the app lately

### ISSUE THREAD

**Issue by jrichview** [MscrmTools/XrmToolBox#1273]
[Write your comment/feedback/issue here]
Hello.  I seem to be having a lot of issues with XRM Toolbox lately.  The latest version would throw exceptions whenever I tried to install a tool. I installed an earlier version (per below) but now I'm getting issues with certain key tools that I use like Fetchxml builder. Says it's incompatible with the current version of the app.  It's unclear how to fix this.
---
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2023.1.60

**Comment by MscrmTools** [comment]
I guess your best shot is to reset everything.
To do so, clear the folder C:\Users\<your_login>\AppData\Roaming\MscrmTools\XrmToolBox 

You might want to backup this folder first to get some important files back like your connections, etc.

**Comment by jrichview** [comment]
Thanks, but I've actually already tried that.  The app is functional to a point, but for example I can't get FetchXML Builder tool to show up in the tools list. It's not listed at all, either as already installed, NOT installed, not compatible, etc.   So I know there are still some issues.

**Comment by MscrmTools** [comment]
Well, it seems a specific issue with your computer. If there was really this kind of issue for everybody, I would be flooded by issues 😄 
Sorry but I don't see how I can help here...
