### ISSUE TITLE
Tool Library is Empty

### ISSUE THREAD

**Issue by Mhmdbaba** [MscrmTools/XrmToolBox#1279]
I am using the latest version of XrmToolbox. However, every time I attempt to open the toolbox, the tools fail to load, leaving the page empty.

**To Reproduce**
Try to open the tool library. I'll be attaching a screenshot below:
![image](https://github.com/MscrmTools/XrmToolBox/assets/78954969/acde7f8e-70c1-451c-aea7-6fc14e07a9be)

**Expected behavior**
The tool library would show some tools that I can install.

**Screenshots**

**Desktop (please complete the following information):**
![image](https://github.com/MscrmTools/XrmToolBox/assets/78954969/0e9d07d0-efe1-44bd-a787-117d46a1fda3)
**Additional context**

**Comment by MscrmTools** [comment]
Are you behind a proxy?

If there was really this kind of issue for everyone, then earth would stop spinning, so it must be something on your computer/network

**Comment by Mhmdbaba** [comment]
Thankfully, The world is still spinning. Then the issue is from my side. Thank you for your feedback, very helpful for your support!

**Comment by AlessandroMarc** [comment]
Same here!

**Comment by MscrmTools** [comment]
@Mhmdbaba @AlessandroMarc is this still an issue?

**Comment by AndreasGloeckner** [comment]
Same issue for me. Got the issue since I updated to the new layout.
My previous installed tools works fine. I even downloaded the xrm toolbox again and run it in an extra folder. No proxy.
Cache cleared => nothing.

**Comment by MscrmTools** [comment]
I'm really sorry guys about this issue but as I do not reproduce, it's quite difficult to help.
Can you anyway goes to Settings > Proxy?

There is a test button to check if the tool can reach https://www.xrmtoolbox.com

**Comment by AleksandrRogov** [comment]
Hi, 
The tool library is empty for me as well. Proxy Settings set to "No Proxy", when I click the button to "Apply" proxy settings it shows a message "Connection test succeeded!". Tried clearing the tools cache, that did nothing. Tried with two XrmToolbox versions: 1.2023.10.67 and 1.2023.12.68. Also tried to set "Legacy tools list" that also did nothing.

**Comment by MscrmTools** [comment]
@AleksandrRogov Can you tell me what you see when you test this url : https://www..xrmtoolbox.com/_odata/plugins

**Comment by MscrmTools** [comment]
Do you have access to Nuget.org website too?

**Comment by MscrmTools** [comment]
@AleksandrBaderkov Ok, let's try to tackle down this issue!
Can you try with this version of ToolLibrary? Just extract the content in your XrmToolBox folder.
I forgot to catch exception when loading tools. This version should tell us what the real issue is*
[XrmToolBox.ToolLibrary.zip](https://github.com/MscrmTools/XrmToolBox/files/13590420/XrmToolBox.ToolLibrary.zip)

**Comment by AleksandrRogov** [comment]
@MscrmTools downloaded the files and replaced the ones that were already in a folder. Should it show an error message? Or does it write a log somewhere?

**Comment by MscrmTools** [comment]
Another try.

This version will log some entries in a ToolLibrary.log file in the Logs folder of XrmToolBox... Let see what happens on your side.

[XrmToolBox.zip](https://github.com/MscrmTools/XrmToolBox/files/13591640/XrmToolBox.zip)

Here is my log for a normal usage that works:

2023-12-06 22:08:58 - Load repositories
2023-12-06 22:08:58 - Instantiate store
2023-12-06 22:09:48 - Displaying tools
2023-12-06 22:09:49 - Loading method from ToolLibraryForm
2023-12-06 22:09:49 - Tools already loaded
2023-12-06 22:09:49 - No error reported
2023-12-06 22:09:49 - Displaying tools

**Comment by MscrmTools** [comment]
There is really something specific here. I do not have this problem and I'm using what it needs to avoid file locking...
Any chance you would have visual studio and can debug directly from there? If so, I can tell you where to put break point

**Comment by AleksandrRogov** [comment]
@MscrmTools sure. Let me know what look for.

**Comment by AleksandrRogov** [comment]
@MscrmTools Did not get any exceptions but for some reason the items in the Tool Library are still not being "drawn". I put additional breakpoints in ToolLibraryForm.MainLoad and and it looks like the `Plugins` and `Categories` are there, so they were retrieved without an issue. 

![Snag_1d4019](https://github.com/MscrmTools/XrmToolBox/assets/1893650/e819dcda-9482-4c4b-bd6c-8af9f3ec45f3)

![Snag_1d5d36](https://github.com/MscrmTools/XrmToolBox/assets/1893650/9b6a9428-f384-40a6-9fdc-1de8132d3a5c)

Can you tell me what method is responsible for drawing the plugins on the Tool Library form?

Also there is a `Filter()` method which I am not sure what it is doing, but the `filteredTools` collection is always empty for me. Then This `filteredTools` is being set to a `lvTools` collection. Is this the collection that should be drawn on the Tool Library form, or is it something else?

![image](https://github.com/MscrmTools/XrmToolBox/assets/1893650/0c46f7d4-175c-4b49-9121-cdf6363cebd3)

**Comment by MscrmTools** [comment]
Drawing is made in ToolLibraryForm.Drawing.cs class

Filter method is the one that is called to select the tools to display so if result is empty, that means the combination of filters returns no tools.

**Comment by MscrmTools** [comment]
I'm so dumb I even did not look closely at the very first screenshot in this thread.
No tools are displayed because ALL selection filters are unticked!

If you are in the same situation, please tick one of the selection filter in the menu bar

**Comment by AleksandrRogov** [comment]
Do you mean this? Still nothing...
![image](https://github.com/MscrmTools/XrmToolBox/assets/1893650/4fe943a3-39ba-435f-99bf-7bf018188c5d)

**Comment by AleksandrRogov** [comment]
Nevermind, I closed an app and opened it again and it started working. Thanks!

It was not clear to me what those icons are for and not sure why they were all unselected.

**Comment by MscrmTools** [comment]
I will add a warning when all selection filter are unticked so that it is clearer something has to be ticked

**Comment by daryllabar** [comment]
Might be easier just to check everything if you uncheck everything...

**Comment by MscrmTools** [comment]
When opening Tool library? Yep, easier

**Comment by tsileo-wdi** [comment]
Just a note here for others who find this thread, and perhaps an improvement suggestion.  The way the filters work at the moment is quite confusing, because the ones to the right of the vertical bar are applied as "OR" criteria (I think), while the ones to the left are "AND" criteria ("show only"). So, if the "New" box is checked, it will override everything else and only show you new tools, which is probably what most people aren't realizing.

**Comment by MscrmTools** [comment]
You are correct but I don't know how to handle them differently.
And the ones on the left have a tooltip that says "only"
