### ISSUE TITLE
[BUG] An error occured: Duplicate attribute

### ISSUE THREAD

**Issue by Lik93** [MscrmTools/XrmToolBox#1285]
When pasting the Fetch XML from modern editor in dataverse, tool shows a message An error occurred: Duplicate attribute:
![image](https://github.com/MscrmTools/XrmToolBox/assets/147731383/c452770e-c1cc-437a-bbf1-3502b3670829)

 
After removing no-lock="false" everything works:

 
![image](https://github.com/MscrmTools/XrmToolBox/assets/147731383/cb62a5da-31f9-4a97-a352-6e07672608a6)

**Comment by MscrmTools** [comment]
What tool are you using in XrmToolBox?

**Comment by Lik93** [comment]
Fetch XML / View Record Counter

**Comment by MscrmTools** [comment]
ok, so this is not one of my tool. Please contact the plugin author directly
