### ISSUE TITLE
[BUG] Updating XrmToolBoxPackage from 1.2022.10.58 to 1.2023.7.65 breaks template plugin

### ISSUE THREAD

**Issue by bwmodular** [MscrmTools/XrmToolBox#1290]
**Describe the bug**
Upgrading to latest version of XrmToolBoxPackage NuGet package breaks a new plugin.

**To Reproduce**
With a new plugin created from the Visual Studio Template, update the version of the NuGet package from the default (1.2022.10.58) to the latest (1.2023.7.65).
The plugin no longer compiles, and give these errors:
The type or namespace name 'XrmToolBox' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'PluginBase' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'PluginControlBase' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'IXrmToolBoxPlugin' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'IXrmToolBoxPluginControl' could not be found (are you missing a using directive or an assembly reference?)

**Desktop (please complete the following information):**
VS 2022, Latest version of VSIX template.

Any hints on how to resolve these issues? Thanks!

**Comment by MscrmTools** [comment]
Please upgrade your project to .net framework 4.8 and you should be good

**Comment by bwmodular** [comment]
Thank you so much! If only every compilation error in life was that easy to fix! 😃

**Comment by bwmodular** [comment]
The ToolBox project now compiles OK, but when I run it, I get a Toolbox Initialization error:
![image](https://github.com/MscrmTools/XrmToolBox/assets/1889586/2656f8a8-c1aa-4c1b-b4a9-83ab4ecb649f)

This means I'm unable to see or launch my new Tool

This wasn't happening before the update 1.2023.7.65. I've updated the local version of the Toolbox to 1.2023.6.65 

Any ideas what I should do? Thanks

**Comment by MscrmTools** [comment]
This message is only about Tool Library initialization. It has never blocked me to debug my tools.
That shouldn't block you.
And there is an updated version of the template but it should still display the same error message.
I will try to understand why this error message occurs on debug

**Comment by bwmodular** [comment]
Here's the toolbox running with an unupdated tool from the toolbox template:

![image](https://github.com/MscrmTools/XrmToolBox/assets/1889586/5d11097f-4f0b-4061-a653-89248ab0572d)
After Updating, the Tools tab isn't visible, and I can't find a way to make it visible:

![image](https://github.com/MscrmTools/XrmToolBox/assets/1889586/08d6f34b-167f-496e-b567-b8cfaa3f1ec8)
Sorry if I'm missing something obvious...

**Comment by MscrmTools** [comment]
Never seen it but can you try to close both bottom notifications? I guess I may have an order issue for controls in the main form
