### ISSUE TITLE
XrmToolBox v1.2023.10.67 Update killed connections... wont reconnect

### ISSUE THREAD

**Issue by zavurovm** [MscrmTools/XrmToolBox#1291]
![tool library error](https://github.com/MscrmTools/XrmToolBox/assets/124697771/0bc8a4a1-c502-44b4-a9d8-5c49b211ce35)
![Login_ErrorLog](https://github.com/MscrmTools/XrmToolBox/assets/124697771/0a45f47e-4dfe-4e69-9ff0-7ccd19f880d2)
[Login_ErrorLog.log](https://github.com/MscrmTools/XrmToolBox/files/13230424/Login_ErrorLog.log)
[Write your comment/feedback/issue here]

---
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.10.67

**Comment by MscrmTools** [comment]
Are you behind a proxy?
Can you check in settings the proxy configuration?

**Comment by zavurovm** [comment]
Yes.  Looks like the proxy setting was reset.  I set it.  All of my tools are missing.  Reinstalling.

Thanks!


From: MscrmTools ***@***.***>
Sent: Wednesday, November 1, 2023 2:50 PM
To: MscrmTools/XrmToolBox ***@***.***>
Cc: Zavurov, Mike (DCWP) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [MscrmTools/XrmToolBox] XrmToolBox v1.2023.10.67 Update killed connections... wont reconnect (Issue #1291)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.  Forward suspect email to ***@***.******@***.***> as an attachment (Click the More button, then forward as attachment).


Are you behind a proxy?
Can you check in settings the proxy configuration?

-

**Comment by MscrmTools** [comment]
@zavurovm So you are good now?
Can we close the issue?

**Comment by zavurovm** [comment]
@MscrmTools the proxy issue is resolved.  Thank you!
