### ISSUE TITLE
FetchXML Builder error

### ISSUE THREAD

**Issue by zavurovm** [MscrmTools/XrmToolBox#1293]
![Screenshot 2023-11-03 104754](https://github.com/MscrmTools/XrmToolBox/assets/124697771/c4ec22eb-344f-4a74-a116-fb93245c50c0)

Fetch XML Builder tool not opening with or without connecting first. 

---
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.10.67

**Comment by zavurovm** [comment]
Btw, already tried uninstalling the tool and reinstalling it.

**Comment by MscrmTools** [comment]
@rappen it seems FXB relies on Plugins Store... I wasn't aware of this, sorry.
You will have some work for the week end.
@zavurovm, when running XrmToolBox after update, did you get a notification about cleaning some files?

**Comment by zavurovm** [comment]
I don't recall notifications about cleaning files.  Is there a fix for this?

**Comment by MscrmTools** [comment]
No, it will be with next release. 
So the file XrmToolBox.Pluginstore.dll is still in your XrmToolBox folder ?

**Comment by zavurovm** [comment]
the dll is no longer there..

**Comment by rappen** [comment]
Ouch. I will kill my stats I guess 😉

We'll see, I'm a bit busy these days...
We'll see! I'll try!

**Comment by rappen** [comment]
I'm trying to understand the issue.
Running it on latest&greatest version, it just works fine.

In one place, I was using public method `XrmToolBox.PluginsStore.XmlSerializerHelper`, replaced it and now using `McTools.Xrm.Connection.XmlSerializerHelper`, which is used in more places.

It seems you have duplicated code 😉

I'll let you know when FXB is released!

---
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.10.67
- Tool Version: 1.2023.8.2

**Comment by rappen** [comment]
Fixed here: https://github.com/rappen/FetchXMLBuilder/commit/6a077e245e4d23540da076770ce3fddcc4499aff

**Comment by MscrmTools** [comment]
As connection controls are independent, they have their own code, but yes it's certainly duplicated 😁

**Comment by rappen** [comment]
I assume it is ok to use their public methods? Otherwise I need to copy it to my codes...

**Comment by MscrmTools** [comment]
I must admit I'm not using enough internal accessor... but yes, I think it's ok to use them. I'm not planning to remove any other assemblies

**Comment by zavurovm** [comment]
Thank you for quick turnaround!
