### ISSUE TITLE
More issues with XrmToolBox.PluginsStore

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1294]
I'm working on #1293, but I see more issues - more tools are missing `XrmToolBox.PluginsStore`.
For example, the Access Checker:

![image](https://github.com/MscrmTools/XrmToolBox/assets/2572253/77b5e111-a2a3-4cf0-b84d-8129f4788ecb)

This is a brand new install of XTB. I deleted the storage folder: `C:\Users\<me>\AppData\Roaming\MscrmTools\XrmToolBox` before running it.

I was searching in all my code for "pluginsstore" and I believe all my tools have this reference, but it's never used (I just removed it from FXB where I was actually using `XrmToolBox.PluginsStore.XmlSerializerHelper`), even in my newest tool, creating on stage a few weeks back.

![image](https://github.com/MscrmTools/XrmToolBox/assets/2572253/6ce342da-454b-4202-850d-a2d06dba18f3)

Honestly, I don't understand why some tools are required by `PluginsStore` and crash when we just try to start it, and other tools work fine, even with the reference to PluginsStore. It is only in the csproj files they are referenced.

Do I need to rebuild and publish a new version of all my tools to the latest version of `XrmToolBoxPackage`, and some of you too?

---

**Long story, but now I believe my issues are that `AppInsights` was published in `XrmToolBox.PluginsStore` and is now moved to `XrmToolBox`.**

**Is it possible to fix it once in the XTB? Or should I update all my tools?**

---
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.10.67

**Comment by MscrmTools** [comment]
I don't think this can be fixed in XTB...
So if there was use of method from XrmToolBox.PluginsStore assembly, then yes I guess tools need to be fixed and republished.
Sorry I did not notice this before removing PluginsStore.dll

**Comment by rappen** [comment]
Ok, got it.
I will post on my site a note about if you get an issue looking something like this:

![image](https://github.com/MscrmTools/XrmToolBox/assets/2572253/ee1e13ef-fb37-4f14-a158-05b42e0e851a)

Then you can download `XrmToolBox.PluginsStore.dll` from here, and put it into the XrmToolBox folder.

Is that ok for you?

**Comment by rappen** [comment]
Here it is: https://jonasr.app/missing-xrmtoolbox-pluginsstore/

**Comment by MscrmTools** [comment]
May I behave like Microsoft? These methods were not documented so shouldn't have been used 😅

**Comment by rappen** [comment]
Smart move! 😁

**Comment by Micael-stack** [comment]
hey guys, just did fresh install, same exact error version 1.2022.10.58 for pluginsStore. Following instructions worked but it should be included in the tool...

**Comment by MscrmTools** [comment]
@Micael-stack PluginsStore is not used by XrmToolBox. I know the transition is a bit complicated but it has to happen
