### ISSUE TITLE
User Roles Manager - Error in assign roles in complex business unit hiearchy

### ISSUE THREAD

**Issue by orik007** [MscrmTools/XrmToolBox#130]
Hi

There is a bug if I want to assign role to user/team in different business unit (and business unit hiearchy is pretty complex).

It throws some thing like
InvalidOperationException - There are no rows matching where conditions in .first()

Because roles needs to be searched recursive, not only parentid.

I fixed it in my copy of xrmtoolbox, but what is the proper way to transfer it here? Is any?

Thx

**Comment by MscrmTools** [comment]
Hi @orik007, I'm not a specialist of Github but you should be able to create a pull request so that I can merge your change in my own project

**Comment by orik007** [comment]
Hey, im not an expert either. Never work with github and pull requests. Desktop github does not work for me and i dont know how to connect to github thru VS or which branche should i use :-)

**Comment by MscrmTools** [comment]
Can you send me updated code so that I can apply it on my side?
