### ISSUE TITLE
Tools search box opens "Metadata Browser Companion" instead of "Metadata Browser"

### ISSUE THREAD

**Issue by mdocter** [MscrmTools/XrmToolBox#1300]
Disclaimer: I am not sure if this is a XrmToolBox issue or a Metadata Browser issue.

Above the Tools list, there is a search box. 
When a search for "Metadata" I get the dropdown with the excellent "Metadata Browser" and "Metadata Browser Companion", but when I use the keyboard and select the "Metadata Browser" entry and press 'Enter', the "Metadata Browser Companion" is opened... That's the wrong tool.

![image](https://github.com/MscrmTools/XrmToolBox/assets/796916/f8d9b900-c24d-4b43-8ac6-685b450b8097)

The tools list itself is also filtered and clicking there on "Metadata Browser" entry, the "Metadata Browser" opens. Which is correct.

---
- Deployment: Online
- DB Version: 9.2.23101.230
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.10.67

**Comment by MscrmTools** [comment]
This is an XrmToolBox issue. 
Thank you for reporting it
I will fix the issue for the next release

**Comment by mdocter** [comment]
Great! Thanks @MscrmTools! You're the best.
