### ISSUE TITLE
[BUG] I have updated my XRM Tool box and then tried opening the FetchXML Builder, but got an error!!!

### ISSUE THREAD

**Issue by ChitraRavishankar852** [MscrmTools/XrmToolBox#1303]
**Describe the bug**
Fetch Xml Builder - After updating the tool box, tried opening FetchXML Bilder but error occured. 
Kindly help on how I could 
<img width="253" alt="FetchXML Builder Error" src="https://github.com/MscrmTools/XrmToolBox/assets/152986310/6f289a83-c342-4bc8-8755-679301faecda">
@rappen

**Comment by rappen** [comment]
Update XrmToolBox to 1.2023.10.67.
Update FetchXml Builder to 1.2023.11.1.

Please report if it doesn't fix the problem.

**Comment by MscrmTools** [comment]
Can you share a screenshot of the error?

Are you behind a proxy? If so, you might have to go to Settings > Proxy to configure it

**Comment by MscrmTools** [comment]
Closing this issue as it is related to FetchXml Builder and I think it's fixed with latest version
