### ISSUE TITLE
[BUG] Latest update (2023.12.08) of Plug-in Registration is broken. I immediately receive a message to delete the assembly before re-starting XTB.

### ISSUE THREAD

**Issue by mtnmuncher** [MscrmTools/XrmToolBox#1308]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - XrmToolbox Version
 - Tool version

**Additional context**

**Comment by MscrmTools** [comment]
I can see you open an issue in the appropriate repository, so closing this one
