### ISSUE TITLE
Refactoring plugins management

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/XrmToolBox#131]
Hi guys,
I was considering using MEF (Microsoft Extensibilty Framework) and Application Domains to manage plugins and add features like plugins auto loading, plugins auto update, and so on.

After some digging, it seems there are some limitations that make this implementation complicated:
- You cannot unload loaded assemblies, even with MEF and AppDomain. So autoupdate doesn't seem possible
- MEF does not see new version of an assembly but only addition and removal of assembly file
- Using AppDomain requires to extend a lot the main interface as you cannot use properties but only methods to communicate between main app and plugin and all types are not supported (like Bitmap, for example)

So, I'm now considering not refactoring plugins management at this level. I can still use MEF for plugins auto loading and even using MEF metadata to describe plugins instead of using custom class attributes (which could fix issue #110)
My only concern is about version number that should still be stored at the assembly level and not at the class level. But if more than one plugin is stored in one assembly, shouldn't they have separate version number?

So I need your thoughts about:
- Using MEF to load plugins (that is a breaking change for existing plugins but it will remove some custom code and manage automatically loading only one time the same plugin if libraries is added multiple times with different names)
- Using Metadata to store plugin information at class level. I'm refering to BackgroundColor, PrimaryFontColor, SecondaryFontColor, SmallImageBase64, BigImageBase64, Title and Description. 
- Keeping assembly information for Company and Version

Thank you for your feedback

**Comment by rappen** [comment]
Just one small feedback from me - I definitly think version number and company info can still be on assembly level. If you have several plugins in the same assembly, you still compile them at the same time with source code from one specific commit, so they are essentially of the same version.
