### ISSUE TITLE
User Settings Utility - Error when connecting to On-Prem CRM 2016 Instance

### ISSUE THREAD

**Issue by doneill2cc** [MscrmTools/XrmToolBox#1313]
Good morning, 

For the past few months/updates there has been an issue with User Settings Utility when ever you try to load users from a non-D365 environment.

An error occured: The entity with a name = 'appmodulecomponent' was not found in the metedata cache.

I have Reset my XrmToolBox installation and also completely reinstalled to see if that would rectify the issue, but to no avail.

---
- Deployment: OnPremise
- DB Version: 8.1.0.381
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68

**Comment by MscrmTools** [comment]
Hi @doneill2cc, 
Thanks for reporting this.
This is an issue specific to your version of Dynamics 365. I will handle this

**Comment by doneill2cc** [comment]
Thanks a million if you need any more information let me know

**Comment by MscrmTools** [comment]
Hi @doneill2cc, can you test with this version:
[MsCrmTools.UserSettingsUtility.zip](https://github.com/MscrmTools/XrmToolBox/files/13683749/MsCrmTools.UserSettingsUtility.zip)

**Comment by doneill2cc** [comment]
Thanks for this, and I am sorry to say same issue is present.
1. Replaced dll in appdata/roaming 
2. Reloaded XRMToolbox
3. Connected to on-prem crm 
4. Load Users
5. "Loading Sitemaps" loading screen
6. 'appmodulecomponent' error

I am not seeing any logs that I could share to assist, sorry.

**Comment by MscrmTools** [comment]
Sorry, I inverted the condition to avoid the error
Please try with this one
[MsCrmTools.UserSettingsUtility.zip](https://github.com/MscrmTools/XrmToolBox/files/13685459/MsCrmTools.UserSettingsUtility.zip)

**Comment by MscrmTools** [comment]
Ok, thank you for testing. I will release officialy this new version
