### ISSUE TITLE
[BUG] Dll of tool is not getting installed

### ISSUE THREAD

**Issue by unSkilleds-hub** [MscrmTools/XrmToolBox#1315]
**Describe the bug**
I created the tool "https://www.nuget.org/packages/RS.Security.Center/" and received a message from another user that the tool can be installed, but afterwards not started.

**To Reproduce**
Open XrmToolBox and download "RS Security Center", in the folder "%appdata%\MscrmTools\XrmToolBox\Plugins" the "RS Security Center.dll" will not appear.

**Expected behavior**
The "RS Security Center.dll" should appear in the folder "%appdata%\MscrmTools\XrmToolBox\Plugins".

**Desktop (please complete the following information):**
 - XrmToolbox Version v1.2023.12.68
 - Tool version 1.0.0.4 -1.0.0.43

**Additional context**
I already tried to figure out why this is happening and tried looking up other creators nuget packages and changed the structure of mine according, but it doesn't change a thing.
<img width="259" alt="chrome_RhizopCuku" src="https://github.com/MscrmTools/XrmToolBox/assets/57639833/f7341c54-03a4-45d6-86b4-b93f71f2f7a5">

**Comment by MscrmTools** [comment]
First thing I see is that your assembly has spaces in its name. Can't tell if this is the issue right now but you should avoid this

**Comment by unSkilleds-hub** [comment]
@MscrmTools  Thank you very much for pointing me to this, it solved the issue!
