### ISSUE TITLE
[BUG] App wont Launch due to Invalid DockState

### ISSUE THREAD

**Issue by blakeZTL** [MscrmTools/XrmToolBox#1317]
**Describe the bug**
When trying to open the application, I am receiving an error with a message of 'Invalid DockState: Content can not be showed as "Unknown" or "Hidden".'
The application will not move beyond this point. 

**To Reproduce**
Download the newest release and open the exe

**Expected behavior**
The application opens as intended.

**Screenshots**
![image](https://github.com/MscrmTools/XrmToolBox/assets/111074085/d43e8601-ffe6-4b18-bed3-fd57716aab45)

**Desktop (please complete the following information):**
 - XrmToolbox Version : 1.2023.12.68
 - Tool version : NA

**Additional context**
The problem started on my old 'installation'. I downloaded the latest release, deleted all the old files, unzipped into a new directory and still receiving the error.

**Comment by MscrmTools** [comment]
What tool are you trying to open? There should be a config file with it that reference a dock state with an incorrect value

**Comment by blakeZTL** [comment]
I am not trying to open a specific tool... just the application. The last tools I can remember using were Fetch XRM Builder and API Builder. Where can I find the config file to check? I don't see anything in the folder except XrmToolBox.exe.config. I have also trying using a brand new downloaded version in a separate folder with the same results.

**Comment by MscrmTools** [comment]
All settings files should be located in C:\Users\your_profile\AppData\Roaming\MscrmTools\XrmToolBox\Settings

**Comment by blakeZTL** [comment]
So it was my XRMToolBox.Settings.xml file.  Somehow it got corrupted with this line
`<PluginsListDocking>Unknown</PluginsListDocking>`
I have attached the file if curious. I deleted the settings file and the application launched perfectly fine.
[XrmToolBox.Settings.xml.pdf](https://github.com/MscrmTools/XrmToolBox/files/14447681/XrmToolBox.Settings.xml.pdf)

Thank you so much for your help!

**Comment by tsileo-wdi** [comment]
Just to leave a comment here, this happened to be today on v1.2024.9.69.  I resolved it by just deleting that single line from XRMToolBox.Settings.xml (no need to delete the entire file).

<PluginsListDocking>Unknown</PluginsListDocking>
