### ISSUE TITLE
MessageWidth/Height is semi-respected

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1319]
I need a bigger progress panel since this is a bit tight:

![image](https://github.com/MscrmTools/XrmToolBox/assets/2572253/8db928da-46e6-4ceb-88dc-9e0d25994913)

But I thought that would be possible, since x years back, and I see this should be supported:

![image](https://github.com/MscrmTools/XrmToolBox/assets/2572253/40963b6f-5e6e-49dc-a25a-bfb42f52c8d6)

But when I see the result, it seems like somehow it is respected when looking at the waiting-gif here in the right-lower corner, and the text is... higher? But the actual panel has the default size.

![image](https://github.com/MscrmTools/XrmToolBox/assets/2572253/70cb4d74-1b85-4634-8495-3dd785f8fad6)

---
- Deployment: Online
- DB Version: 9.2.24012.226
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68

**Comment by MscrmTools** [comment]
@rappen, is this still an issue?

My latest test seems to say it's working as expected with the following code :
``` var asyncinfo = new WorkAsyncInfo()
 {
     Message = "Waiting...",
     MessageHeight = 700,
     MessageWidth = 1200,
     Work = (a, args) =>
     {
         Thread.Sleep(5000);
     },
     PostWorkCallBack = (args) =>
     {
     }
 };
 WorkAsync(asyncinfo);
```

![image](https://github.com/user-attachments/assets/87568537-6630-4ee0-a0b2-ad357d636842)

**Comment by rappen** [comment]
Tested more - it looks like it starts in the expected size, but after an `ProgressChanged` it defaulted the size.

...and now I see that we can send the size to the `SetWorkingMessage` method.
So, as expected - my mistake! 😁
