### ISSUE TITLE
[BUG]  Issue with Missing XrmToolBox Dependency in NuGet Package

### ISSUE THREAD

**Issue by mohamed1234567890vv** [MscrmTools/XrmToolBox#1321]
I am currently facing an issue related to the "Add new tool" feature, where I encounter an error message stating: "Errors have been found in your NuGet package: XrmToolBox version dependency is missing in NuGet package."
![image](https://github.com/MscrmTools/XrmToolBox/assets/30890030/6f8582ba-786e-491e-be60-310726cb6e0a)

Furthermore, when I attempt to add the dependency manually by searching for the XrmToolBox NuGet package, I encounter another problem. Instead of finding the package, I receive an error message saying: "Oops! Error 404 - Page Not Found. Looks like you might have gotten lost. Let's see if we can help you find your way!"
![image](https://github.com/MscrmTools/XrmToolBox/assets/30890030/9670cef2-7db6-4fe3-a6d9-b2fa85fdb682)

I would appreciate any assistance in resolving this issue and successfully adding the XrmToolBox dependency to my project. Thank you.

![image](https://github.com/MscrmTools/XrmToolBox/assets/30890030/c152cd80-a650-4441-8b70-a3760e541e20)

**Comment by mohamed1234567890vv** [comment]
@MscrmTools  please advice

**Comment by MscrmTools** [comment]
Sorry, I was in a rush...

First, why a dependency to Iconator in your package?

Second, here is the way to put the correct dependency: https://www.xrmtoolbox.com/documentation/for-developers/deploy-your-plugin-in-plugins-store/

Follow the Doc, there is a chapter about dependencies

**Comment by mohamed1234567890vv** [comment]
No issues, just I follow the instructions But still issue not fixed, please find the attached.

I

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mohamed1234567890vv** [comment]
I have updated but still the issue 
![thumbnail_original-6B10BF82-EC3D-43E8-8C51-394DCCE8284D](https://github.com/MscrmTools/XrmToolBox/assets/30890030/f22b4402-11a0-4eb1-aef3-fbf3699bf472)
![thumbnail_original-D371A4D0-48CB-433F-8CA1-08B0D46F8549](https://github.com/MscrmTools/XrmToolBox/assets/30890030/b61e3f27-5739-4691-a7bb-965aa74b6fc2)

**Comment by mohamed1234567890vv** [comment]
![Uploading issue.png…]()

**Comment by MscrmTools** [comment]
ah! I know! XrmToolBox looks for all version of the nuget package. Please unlist all previous version but the latest and you should be good

**Comment by AmanPuthawalaStridely** [comment]
no that this no work i also got the same error
