### ISSUE TITLE
Easy Translator - Forms tabs, sections and fiels not exported correctly

### ISSUE THREAD

**Issue by irisrenner** [MscrmTools/XrmToolBox#134]
When I Export an entity for Translation, it does not contain the already existing translations for the following Tabs:

- Forms Tabs
- Forms Sections
- Forms Fields

This makes it difficult to know what has been translated or not.
It might create Problems when you fill out the info again... and make Errors.

How can I fix that?
Thanks

**Comment by MscrmTools** [comment]
What is the version of XrmToolBox and Easy Translator you are using?

**Comment by irisrenner** [comment]
Hello

thanks for the quick reply

I am using Version 1.2015.5.6.

Greetings

Iris Renner
CRM Business Analyst
IT Business Analyst Sales & Marketing

Geberit Verwaltungs AG
Schachenstr. 77, CH-8645 Jona
T: +41 55 221 6232
M: +41 79 7062057
iris.renner@geberit.com
http://www.geberit.ch http://www.geberit-aquaclean.ch




Von:    MscrmTools <notifications@github.com>
An:     MscrmTools/XrmToolBox <XrmToolBox@noreply.github.com>, 
Kopie:  irisrenner <iris.renner@geberit.com>
Datum:  20.05.2015 15:51
Betreff:        Re: [XrmToolBox] XRM Toolbox - Easy Translator (#134)



What is the version of XrmToolBox and Easy Translator you are using?
—
Reply to this email directly or view it on GitHub.


--------------------------------------------------------------------------------------------------
Disclaimer:
The content of this e-mail (including attachments) is confidential and intended for the use of the addressee only. If you are not the intended recipient please delete the e-mail; dissemination or disclosure of its content to anyone is strictly prohibited!
Before opening an attachment please check it for viruses. We accept no liability for any damage caused by viruses.

**Comment by MscrmTools** [comment]
I'm not sure to understand, what do you mean by "already existing translations"?
Did you translate those part using EasyTranslator once and it is not appearing again?

**Comment by irisrenner** [comment]
yes. Exactly.
I have translated with the tool and imported these translations.
When I do an export again, these translations are missing.
We are developing in english and at the moment translating into german 
(1031).

Thanks
Iris


Iris Renner
CRM Business Analyst
IT Business Analyst Sales & Marketing

Geberit Verwaltungs AG
Schachenstr. 77, CH-8645 Jona
T: +41 55 221 6232
M: +41 79 7062057
iris.renner@geberit.com
http://www.geberit.ch http://www.geberit-aquaclean.ch




Von:    MscrmTools <notifications@github.com>
An:     MscrmTools/XrmToolBox <XrmToolBox@noreply.github.com>, 
Kopie:  irisrenner <iris.renner@geberit.com>
Datum:  20.05.2015 16:37
Betreff:        Re: [XrmToolBox] XRM Toolbox - Easy Translator (#134)



I'm not sure to understand, what do you mean by "already existing 
translations"?
Did you translate those part using EasyTranslator once and it is not 
appearing again?
—
Reply to this email directly or view it on GitHub.


--------------------------------------------------------------------------------------------------
Disclaimer:
The content of this e-mail (including attachments) is confidential and intended for the use of the addressee only. If you are not the intended recipient please delete the e-mail; dissemination or disclosure of its content to anyone is strictly prohibited!
Before opening an attachment please check it for viruses. We accept no liability for any damage caused by viruses.

**Comment by MscrmTools** [comment]
Let me try to reproduce the bug (I can do the same test with English/French translations)

**Comment by irisrenner** [comment]
thanks! Just fyi: I will not be working tomorrow til tuesday. back on wednesday. Just in case I do not reply :-)

**Comment by LieuweBuis** [comment]
Hi, we have the same issue with the labels on de sub-grids on the Contact and Cases forms. We don't see these labels in the exports.

**Comment by irisrenner** [comment]
How about the accounts? I have the problem there as well.
Is that something what can be fixed?

Thanks
Iris


Iris Renner
CRM Business Analyst
IT Business Analyst Sales & Marketing

Geberit Verwaltungs AG
Schachenstr. 77, CH-8645 Jona
T: +41 55 221 6232
M: +41 79 7062057
iris.renner@geberit.com
http://www.geberit.ch http://www.geberit-aquaclean.ch




Von:    LieuweBuis <notifications@github.com>
An:     MscrmTools/XrmToolBox <XrmToolBox@noreply.github.com>, 
Kopie:  irisrenner <iris.renner@geberit.com>
Datum:  26.05.2015 13:48
Betreff:        Re: [XrmToolBox] XRM Toolbox - Easy Translator (#134)



Hi, we have the same issue with the labels on de sub-grids on the Contact 
and Cases forms. We don't see these labels in the exports.
—
Reply to this email directly or view it on GitHub.


--------------------------------------------------------------------------------------------------
Disclaimer:
The content of this e-mail (including attachments) is confidential and intended for the use of the addressee only. If you are not the intended recipient please delete the e-mail; dissemination or disclosure of its content to anyone is strictly prohibited!
Before opening an attachment please check it for viruses. We accept no liability for any damage caused by viruses.

**Comment by MscrmTools** [comment]
This should be something possible

I still did not have time to work on this but I will try this week

**Comment by MscrmTools** [comment]
Ok, so far, the only problem I see is about tabs, sections of fields that have unique identifier with a mix of lower and upper case which made the retrieval of there elements difficult and thei translation impossible.

But if I translate tab, section or field, then import, then export again, I can find my translated items

**Comment by MscrmTools** [comment]
Regarding subgrids, it should already works as is

**Comment by irisrenner** [comment]
back from vacation.
Not sure If I understand your comment above...
I have been using the tool for quite a while, but did not have the Problem before. Only with this Version and a previous one (that is why I upgraded to this one.)

Is there anything I can do?

**Comment by MscrmTools** [comment]
@irisrenner, does the problem still exist in latest release?

**Comment by irisrenner** [comment]
Hi

thanks for asking.
just figured it out!
When I set the systemlanguage (where I want to translate) to german, then 
the values for german are missing.
When set to english it works OK!!!

Thanks
Iris


Iris Renner
CRM Business Analyst
IT Business Analyst Sales & Marketing

Geberit Verwaltungs AG
Schachenstr. 77, CH-8645 Jona
T: +41 55 221 6232
M: +41 79 7062057
iris.renner@geberit.com
http://www.geberit.ch http://www.geberit-aquaclean.ch




Von:    MscrmTools <notifications@github.com>
An:     MscrmTools/XrmToolBox <XrmToolBox@noreply.github.com>, 
Kopie:  irisrenner <iris.renner@geberit.com>
Datum:  25.07.2015 12:45
Betreff:        Re: [XrmToolBox] XRM Toolbox - Easy Translator (#134)



@irisrenner, does the problem still exist in latest release?
—
Reply to this email directly or view it on GitHub.


--------------------------------------------------------------------------------------------------
Disclaimer:
The content of this e-mail (including attachments) is confidential and intended for the use of the addressee only. If you are not the intended recipient please delete the e-mail; dissemination or disclosure of its content to anyone is strictly prohibited!
Before opening an attachment please check it for viruses. We accept no liability for any damage caused by viruses.
