### ISSUE TITLE
Implementing INoConnectionRequired doesnt seem to do anything

### ISSUE THREAD

**Issue by femo1de** [MscrmTools/XrmToolBox#1347]
**Describe the bug**
It seems that implementing the interface INoConnectionRequired  does not have any effect.

**To Reproduce**
Create a new plugin with the current template in Visual Studio, implement INoConnectionRequired

**Expected behavior**
Tool should not prompt me to create a new connection when opening my plugin.

**Desktop (please complete the following information):**
 - XrmToolbox Version: 1.2023.10.67

**Comment by MscrmTools** [comment]
@femo1de can you confirm you implemented the interface in the plugin class and not the plugincontrol class

See [this example](https://github.com/MscrmTools/XrmToolBox/blob/master/Plugins/MsCrmTools.SampleTool/Plugin.cs)

**Comment by femo1de** [comment]
Sorry, yes seems the issue was on our side.
