### ISSUE TITLE
Cannot Import XrmToolBox .zip. Throws an Error

### ISSUE THREAD

**Issue by JohnEllsworthIII** [MscrmTools/XrmToolBox#135]
CRM 2011: When I tried to import XrmToolBox as a solution, I am greeting with the following error: The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics CRM are not supported.

**Comment by mscottsewell** [comment]
John - it's not a solution to import - it's an application - 
Unblock the zip file (https://github.com/MscrmTools/XrmToolBox/wiki/Unblocking-downloaded-files)
and then extract it to a folder and run locally.

**Comment by MscrmTools** [comment]
Thank for the answer, Scott :)

**Comment by JohnEllsworthIII** [comment]
Thanks. Much appreciated.
