### ISSUE TITLE
How do i tranfer a security role from dev to sit using FetchXML

### ISSUE THREAD

**Issue by EmmanuelAbutu** [MscrmTools/XrmToolBox#1354]
[Write your comment/feedback/issue here]

---
- Deployment: Online
- DB Version: 9.2.24083.198
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68

**Comment by EmmanuelAbutu** [comment]
@daryllabar Thanks for the response.

**Comment by EmmanuelAbutu** [comment]
Hi @daryllabar 
i was able to follow what  you said and it worked but i have another question. I have some security roles on DEV and SIT, but i just updated some of them on DEV and i want to deploy the updated chances to SIT. Whats the best way to go about it.

**Comment by daryllabar** [comment]
That's really beyond the scope of this git-hub issue, but you'd want to add your security role(s) to a solution in Dev, and then ideally use Power Platform Pipelines, or some other ALM process to move export and import the solution, but you can also do them manually.  Best practice would be to export it as a managed solution if you do do it manually.

**Comment by EmmanuelAbutu** [comment]
@daryllabar Thanks for the Response, I'm grateful!
