### ISSUE TITLE
Unable to login to XRM Toolbox (connect to dataverse)

### ISSUE THREAD

**Issue by girishuppal** [MscrmTools/XrmToolBox#1364]
Just updated XRM Toolbox with this version
![image](https://github.com/user-attachments/assets/cc8bdb00-5a75-41c3-a355-a6709564e1c9)
![image](https://github.com/user-attachments/assets/a24e31ba-a2c5-445f-a776-cfc4797e08c8)
![image](https://github.com/user-attachments/assets/7e253ff7-2eff-4300-95b9-cbefd338e7ad)

After retyping creds, this is the error message i get

![image](https://github.com/user-attachments/assets/97f59085-c213-4b52-a8ad-d0994335ef82)

**Comment by MscrmTools** [comment]
The update did not work as expected. Please update again and you should be fine

**Comment by girishuppal** [comment]
All sorted. Thanks @MscrmTools !

**Comment by Loes365** [comment]
Hi @MscrmTools i keep getting this error as well, with as an error; 
Source	: Microsoft.VisualBasic
Method	: GetFreeDiskSpace
Date	: 17/12/2024
Time	: 12:47:34
Error	: Cannot determine the amount of available disk space.
Stack Trace	: at Microsoft.VisualBasic.Logging.FileLogTraceListener.GetFreeDiskSpace()

I tried installing xrmtoolbox again, on our server and on my laptop, i tried the overridepath that is mentioned on the site but I keep getting this error. Can you please help? Thanks in advance!

**Comment by MscrmTools** [comment]
@Loes365 This is a completly different issue. Please open a new issue and provide steps to get this error + screenshot please
