### ISSUE TITLE
Script Finder issue

### ISSUE THREAD

**Issue by WalidMg** [MscrmTools/XrmToolBox#137]
I downloaded the latest version of XrmToolBox today May 21st 2015 from the official website. It works fine but the Export to CSV in the Script Finder plugin doesn't work properly, the columns names are on one line and all the data is on one line (disorganized also).

**Comment by MscrmTools** [comment]
Ok, I can reproduce the error. 

This will be fixed in June release.

**Comment by MscrmTools** [comment]
Actually, it's already fixed thanks to a pull request.
