### ISSUE TITLE
Request for macOS Compatibility

### ISSUE THREAD

**Issue by nunosubtil** [MscrmTools/XrmToolBox#1371]
**Is your feature request related to a problem? Please describe.**

Yes, the app is not natively compatible with macOS, requiring users to rely on complex workarounds like virtual machines, compatibility layers, or additional hardware. These solutions are inconvenient, resource-intensive, and an unreasonable expectation for users needing only this one application.

**Describe the solution you'd like**

	1.	Develop a native macOS version that allows macOS users to utilize the application without unnecessary workarounds.
	2.	Alternatively, create a browser-based version of the application, accessible on any platform, ensuring all users can access it seamlessly.
	3.	Provide a straightforward and easy-to-follow guide for macOS users who must rely on alternative setups to ensure the app functions correctly.

**Describe alternatives you've considered**

	1.	Running the app in a virtual machine (e.g., Parallels, VMware), which incurs high system overhead and cost.
	2.	Using compatibility layers like Wine or CrossOver, which often result in poor performance, compatibility issues and limited support.
	
**Additional context**

Mac users should not need to invest in a separate Windows PC, deal with complex configurations, or suffer reduced performance to access this application. A native macOS solution or platform-agnostic alternative like a browser-based version would greatly improve accessibility. If resources are a concern, even a basic version for macOS would suffice to alleviate user frustration.

**Comment by MscrmTools** [comment]
Hi @nunosubtil 
What you are asking for is that ALL XrmToolBox developers rewrite all the 300+ tools in another format than the one used currently.
Could I remember you that this tool and all included tools are provided for free? 
Developing a MacOS version and/or a web based version of XrmToolBox would require hundreds (if not thousand) hours of development.
I can't see any of the developers starting this journey.

The easiest way is to emulate Windows on your MacOS. It does work so there is no need for us, developers, to provide a MacOS or web based version
