### ISSUE TITLE
MRU for Connections

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#138]
This is a very minor, but nice to have, request:
MRU list for the connections, so my last used connection appears first in the list etc.

**Comment by MscrmTools** [comment]
Shouldn't be too complicated to implement

Are we just talking about counting connections usage (like plugins list does) or MRU for last week/month/year? I mean, I can work very very often with one connection and never again after, it will still shows up in first positions

**Comment by rappen** [comment]
No counting, simply "Most Recently Used" (not "Most Commonly Used")
Of course a newly created connection should appear on top as well :)

**Comment by MscrmTools** [comment]
Oh I see! so, storing last used date in the connection

**Comment by rappen** [comment]
:+1:
