### ISSUE TITLE
Is there something similar to XrmTool box to edit Command Bar?

### ISSUE THREAD

**Issue by dpace23236** [MscrmTools/XrmToolBox#140]
Use and LOVE XRMToolBox to edit SiteMap, is there a similar tool that can easily edit Command Bar without having to know XML, tried Ribbon Workbench but way to difficult for newbie?

**Comment by MscrmTools** [comment]
No, nothing else that Ribbon Workbench which is, by far, the easiest way to edit ribbon

**Comment by shytikov** [comment]
In other words we're still looking for brave young man who can write such a plugin from scratch.

**Comment by rappen** [comment]
:+1:

**Comment by MscrmTools** [comment]
I already have source code to edit a ribbondiffxml (still buggy by the way) in a "sitemap editor" way (treeview that display xml structure)
As command bar are easier to display (using toolstrip) than ribbon, there is definitively something to do here... 
If only I had time...

It's already hard to maintain XTB these days...

**Comment by scottdurow** [comment]
I hear you guys! I'm currently working on a cut down version of the Ribbon Workbench for simple command bar editing. Watch this space!

**Comment by MscrmTools** [comment]
Woohoo!!! Can't wait to see it in action! This would be a great addition from the ribbon master to XTB

**Comment by rappen** [comment]
:+1: :+1:

**Comment by rajyraman** [comment]
Nice..

**Comment by MscrmTools** [comment]
A new plugin development model has been checked in on my DEV branch. If you are working on a plugin to come, it would be better to work with this new model

**Comment by rajyraman** [comment]
Had a look at the branch. I like the new MEF approach. Looks like a breaking change, but plugin code change required to work with the new model is very minimal.

**Comment by shytikov** [comment]
Maybe someone can write small wiki article describing changes needs to be done to migrate plugins to new code base?

**Comment by MscrmTools** [comment]
I'll do that in the next few days

**Comment by MscrmTools** [comment]
Or even today => [link to wiki page](https://github.com/MscrmTools/XrmToolBox/wiki/Migrate-your-plugin-to-be-compatible-with-July-release)

**Comment by rappen** [comment]
You rock!

**Comment by shytikov** [comment]
An we roll after you!

**Comment by MscrmTools** [comment]
I'm super happy to close this issue! RibbonWorkbench is available for XrmToolBox! (See Plugins Store)
