### ISSUE TITLE
Cannot connect to online site 

### ISSUE THREAD

**Issue by dmajors479** [MscrmTools/XrmToolBox#142]
I am unable to connect the toolbox with our online site.  I've just downloaded your program and this is my first attempt to connect it with our online site.  The site is within our Office 365 tenant and uses active directory for logging in.  Our IT staff believes it's not our firewall.  Any help is greatly appreciated

![cannot connect to online site](https://cloud.githubusercontent.com/assets/12660896/7915524/12bc1dba-084c-11e5-978d-39927681c575.png)

**Comment by MscrmTools** [comment]
To be honest, this is the only configuration I cannot test as I don't have access to any Office 365 tenant with Active Directory login.
I'm using simplified connection mechanism so CRM assemblies should handle this kind of stuff on its own but it seems it does not
I will try to get feedback from Microsoft about this particular connection mode

**Comment by MscrmTools** [comment]
Are you sure that crm.dynamics.com is the appropriate CRM Online endpoint? this is the North America endpoint. Does this fit your location?

**Comment by dmajors479** [comment]
Yes, I am located in the U.S.  Our site's url is our unique company name and then crm.dynamics.com.
Appreciate the help.

**Comment by MscrmTools** [comment]
Any chance I get a temporary account on your organization to test connection?

**Comment by dmajors479** [comment]
That may be difficult to do.  Let me check.

**Comment by rappen** [comment]
We have O365 connected to our ADFS - these settings work for us:
![image](https://cloud.githubusercontent.com/assets/2572253/7917618/f5df70f8-088b-11e5-9378-12e31478b6f0.png)

**Comment by MscrmTools** [comment]
So it looks more a configuration issue on your side...

**Comment by MattNC** [comment]
@dmajors479 If you are using federated authentication with CRM Online, you will have an ADFS sign-in page, so you should be able to connect if you remove the checkmark from "Use Office 365" and check the "Use IFD" option instead.

**Comment by MscrmTools** [comment]
No answer from @dmajors479 since almost two months.
Closing this issue
