### ISSUE TITLE
Script Finder does not find onLoad events

### ISSUE THREAD

**Issue by AndrewAMLLP** [MscrmTools/XrmToolBox#143]
It appears that the Script Finder does not load all the form events. Specifically, it fails to find onLoad events.

**Comment by MscrmTools** [comment]
Can you precise if you use latest version?

I will try to reproduce

**Comment by AndrewAMLLP** [comment]
Yes, I am using version 1.2015.5.6.

**Comment by MscrmTools** [comment]
Same version, different results

![image](https://cloud.githubusercontent.com/assets/10774317/7964585/c51b44c2-0a18-11e5-8efd-6bb9747fe21c.png)

It works for me

**Comment by AndrewAMLLP** [comment]
Odd. These are my results. There should be onLoad events for the Case entity (I have confirmed this by viewing form events on the form itself).
![scriptfinderbug](https://cloud.githubusercontent.com/assets/12721983/7964865/e78f6582-09ce-11e5-9250-80d3b16ce6da.JPG)

**Comment by MscrmTools** [comment]
I know I shouldn't but can you provide a screenshot of form events?

**Comment by AndrewAMLLP** [comment]
Yeah, here is a snapshot.
![formscriptevents](https://cloud.githubusercontent.com/assets/12721983/7965067/f0f10076-09cf-11e5-8dd8-5eb2d1e88d24.JPG)
Is it possible it has something to do with the fact that Case is a custom entity?

**Comment by MscrmTools** [comment]
No.

What is the version of CRM?

**Comment by AndrewAMLLP** [comment]
CRM 2011.

**Comment by MscrmTools** [comment]
Same for me on my test. The only possibility I see is if your entity comes from CRM 4 upgrade. 
In this condition, some script are defined as system events scripts so I don't display them.

When you export a solution with this entity, check attribute of events to see if they are declared as system events

**Comment by AndrewAMLLP** [comment]
That does appear to be the issue. Thanks for the help.
