### ISSUE TITLE
Add "Help" menu to redirect to help web page

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/XrmToolBox#144]
This would allow a user to reach an help web page.

A new menu like Feedback and Donate could be added

**Comment by rappen** [comment]
So you are thinking common interface to each plugin as well, so we can implement an `IPluginHelpInterface`?

**Comment by MscrmTools** [comment]
Absolutely

As I am (with a colleague) writing basic documentation on each tool for the wiki, it could be a good way to  help user to access this documentation quickly

**Comment by MscrmTools** [comment]
Fixed in DEV branch. Will be merged before next release
