### ISSUE TITLE
Selecting entity with SiteMap Editor throws NullReferenceException

### ISSUE THREAD

**Issue by arangas** [MscrmTools/XrmToolBox#146]
Hello,

I'm using CRM 2011 and adding a SubArea to a site map. Unfortunately, the SiteMap Editor throws an exception when I click "Select entity". I'm not aware of anything unusual about my organisation that might cause this. Exception details below:

System.NullReferenceException: Object reference not set to an instance of an object.
   at MsCrmTools.SiteMapEditor.Forms.EntityPicker.FillEntities()
   at MsCrmTools.SiteMapEditor.Controls.SubAreaControl.buttonSelectEntity_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MscrmTools** [comment]
What is the version of sitemapeditor?
Are you connected to an org when editing the sitemap?

**Comment by arangas** [comment]
Sorry I didn't include the version because it's in the stack trace - 1.2015.5.6. I was previously on 1.2015.2.something when I first had the issue. I then wiped out my extracted download of the toolbox and replaced it with the latest.

The SiteMap Editor forces me to connect before it will open.

**Comment by MscrmTools** [comment]
I'm sorry but I do not reproduce it with the same version. What I did to (not) reproduce:
Open XrmToolBox
Click on SiteMapEditor
Select a CRM 2011 connection 
Click on Load SiteMap
Expand an Area, then a Group
Right click on Group and click on Add SubArea
Click on "Select Entity"
The list is displayed

![image](https://cloud.githubusercontent.com/assets/10774317/8001372/6cf99cfa-0b65-11e5-8143-598f9041ea74.png)

**Comment by arangas** [comment]
Hello again,

I've downloaded the code and have better repro steps and the cause for you.

First of all, the site map has to be loaded from a file and not CRM. The exception does not occur if the site map has been opened from CRM.

The exception occurs because `entityCache` is null on this line: https://github.com/MscrmTools/XrmToolBox/blob/41f2aa8ffa5e7f0cee3ecabe40d4f6da3438f18a/Plugins/MsCrmTools.SiteMapEditor/Forms/EntityPicker.cs#L68

I tried to uncomment the lines before this one which seems to populate the cache if it is null, but the code would not compile. I haven't looked at the code base before so I'm not sure how to progress.

Thanks :smile:

**Comment by MscrmTools** [comment]
Ok it makes sense

If no connection, it fails to retrieve entities. I will work on this.

**Comment by MscrmTools** [comment]
You should not even arrive at this code since if no connection exists, a warning dialog tells you so.

![image](https://cloud.githubusercontent.com/assets/10774317/8081904/32989382-0f79-11e5-98c5-d0295096b8e3.png)

**Comment by arangas** [comment]
Exact repro steps:

1. Load XrmToolbox
2. Double-click SiteMap Editor
3. Answer "Yes" to connecting to organisation
4. Choose organisation and wait for "Connecting..." dialog
5. Click Open SiteMap and choose site map file
6. Expand an area, and group, right-click on it and click "Add Sub Area"
7. Click "Select entity"

Exception occurs.
