### ISSUE TITLE
Make it easy to add a connection from a URL

### ISSUE THREAD

**Issue by arangas** [MscrmTools/XrmToolBox#148]
When adding a CRM connection, I would really like to simply copy and paste the URL into the New Connection dialog. However instead I have to "parse" it and break out all of the components into their correct fields:

![newconnection](https://cloud.githubusercontent.com/assets/132198/8073182/9c906170-0f60-11e5-8216-f3cf973af3d4.png)

It would be handy if the "Server Information" part of the dialog worked more like the TFS New Connection dialog, which accepts a URL and disables all of the other controls when it detects one:

![tfsconnection](https://cloud.githubusercontent.com/assets/132198/8073181/9c8f5c4e-0f60-11e5-8a71-2bfba15e9f54.png)

I would be happy to implement this with some guidance/discussion if you would like.

Cheers!

**Comment by rappen** [comment]
:+1:

**Comment by MscrmTools** [comment]
It would be possible but we should also keep the possibility to discover available organizations for a deployment 

I imagine having two options in the create connection dialog:
Use known url
Discover available orgs

**Comment by rappen** [comment]
Absolute, @mscrmtools.
Using the full URL would simply be a shortcut to populate the fields in the connection dialog :)

**Comment by arangas** [comment]
Yes that's what I was thinking, as @rappen described.

**Comment by MscrmTools** [comment]
Here is the screen of my attempts to do something simpler

Specifying an url
![image](https://cloud.githubusercontent.com/assets/10774317/9882488/2431d788-5bd5-11e5-8c5c-6c558bebad58.png)

if online, asking for authentication model
![image](https://cloud.githubusercontent.com/assets/10774317/9882509/41f230f6-5bd5-11e5-8543-c66e6b83eb5d.png)

then asking for credentials (if online or IFD, custom, if not you can choose)
![image](https://cloud.githubusercontent.com/assets/10774317/9882496/320db278-5bd5-11e5-82e8-883d8609d8be.png)

Any thoughts?

**Comment by daryllabar** [comment]
Rather than asking if they are O365, can you just attempt to connect with both methods, then record who wins for the future.  Less buttons means less chances for mistakes

**Comment by MscrmTools** [comment]
Absolutely! It will take more time if second shot is the good one but we can consider office 365 as the default

**Comment by daryllabar** [comment]
You should be able to setup two tasks and run it async.  I could stub something like that out for you if you'd like.

**Comment by MscrmTools** [comment]
The new connector is ready to be launched with next release of XrmToolBox with CRM 2016 support

**Comment by rappen** [comment]
Big time :+1:
