### ISSUE TITLE
Sometimes plugins list does not respond on mouse clicks

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#15]
Unfortunately I cannot give more precise steps to reproduce, but from time to time, quite often, I would say, after loading main window the plugins list does not respond on mouse clicks.

You may perform as much left clicks as you want, but window `Do yo want to connect to CRM first?`  will not pop up.

Most of the time you may connect to CRM manually via toolbar button, and after that you will be able to load plugin.

Sometimes you may wait for several minutes, and plugin list will start responding on clicks. And very rarely the only possible way is to restart application completely.

**Comment by MscrmTools** [comment]
I guess it's not about specific plugins but more about where you click on the plugin item.

To fix this, I tried to add a transparent panel in front of the control but it does not render as expected (or I don't know how to do it properly). If I could success to add this transparent panel, it will cover all plugin surface and registering Click event on this panel would be enough (instead of registering event on each control)

**Comment by daryllabar** [comment]
If the control isn't registering the on-click event, why would a transparent panel be able to register it?

**Comment by shytikov** [comment]
I guess @MscrmTools is right about the target where I'm clicking too. Apart of the cases when I was not able to start plugin at all, I've noticed, that if you click on plugin icon you are able to start it with almost 99,99% chance, while if you click on empty space most likely you will not be able open plugin from first click...

Need to investigate exacts steps to reproduce as well. I thought it just mysterious bug only I have. It happens, I have hands growing from wrong place, and all my 10 fingers are thumbs :+1:

**Comment by MscrmTools** [comment]
@daryllabar, if a control that surface all plugin element has the Click event, so I'm sure all surface is clickable

**Comment by MscrmTools** [comment]
Reading samples on Internet gave me a clue... If I set the property Enabled to false for all controls inside the plugin UserControl, then clicking on control effectively click on the UserControl itself!
I think I found the solution :+1:

**Comment by MscrmTools** [comment]
Ouch... it was not the solution... it works for the small plugin model but not he "normal" one. 

It works on small plugin model because I'm painting the label myself. But when it comes to standard labels, disabled ones are always grey, you can't control the color...

What's your thought about small or "normal" plugin model? Which one do you prefer? Could I remove the "normal" model?

**Comment by rappen** [comment]
From a user point of view, I like the compact model, better overview of available plugins.
From an exhibitionistic author point of view, I like the normal model, better exposure of logo and name ;)

**Comment by MscrmTools** [comment]
That doesn't help :D

**Comment by shytikov** [comment]
My opinion: compact plugins looks better visually, the only thing that is missing — plugin description. If it would be added to compact view, it would be great.

**Comment by MscrmTools** [comment]
The description is displayed as a tooltip when the cursor is on the plugin name

**Comment by shytikov** [comment]
It appears only when mouse is over plugin... 

But guess I know how it's possible improve navigation among lots of plugins. How about introducing plugin groups? So plugins with similar functionality will be tightened into bundles with related functionality.

**Comment by MscrmTools** [comment]
I laready thought about groups but I'm not sure on how to implement it so it's easy to code and then to use

**Comment by shytikov** [comment]
I can imagine... You need to develop new `WindowsForms` component from ground up.

**Comment by daryllabar** [comment]
It would be nice to allow a mouse over of a plugin to populate a form that gives a better description of what the plugin actually does...  Simple example would be to allow the plugin to give a URL that points to a page that describes what the plugin is and how it works...  Then the toolbox would just load the webpage in a browser control (Could even thread it to start doing the loading while the Splash Screen is displayed, and cache it for display later) whenever the mouse enters the plugin.

**Comment by MscrmTools** [comment]
More simple, what about a "Help" icon displayed on the plugin item. Only visible if the plugin implements some kind of HelpUrl property ?
A tooltip on that image could display the description of the tool + a mention like "Click on the help icon to go to [somewhere]"

**Comment by daryllabar** [comment]
We could probably reuse the project page provided by the Github/Codeplex interfaces

**Comment by MscrmTools** [comment]
absolutely

**Comment by MscrmTools** [comment]
This does not fix the current issue, by the way... unless nobody is against removing "normal" display

**Comment by rappen** [comment]
Concerning grouping of plugins, could it be solved by a property `PluginGroup` that is of an enum type which is declared in the `PluginBase` class?
If someone feels an option in the enum is missing, well this is open source...
(I know, still doesn't solve the issue here ;) )

**Comment by daryllabar** [comment]
rappen, I don't see a need to make it an enum.  Just a string that is matched on would work fine, but I think the design would be rather difficult to implement.  As far as the current issue, the large icon view is great for being able to figure out what a plugin does.  So if it was to be removed, there would need to be some functional replacement.

**Comment by shytikov** [comment]
@daryllabar I think that `enum` is better, the predefined set of categories will eliminate possible **Zoo** of users custom categories.

Regarding normal view, large icons, or how it's called... I think you right, additional functional replacement would be needed. But if done right, it would work better for users, than list that responses randomly on mouse clicks.

**Comment by daryllabar** [comment]
@shytikov, remember, the end user has to add in the additional plugins, so the "Zoo" would be due to the user adding additional plugins.

**Comment by shytikov** [comment]
@daryllabar not sure what do you mean... Maybe it depends on implementation... But what I was thinking about, is to come up with the predefined set of, for example, 10 categories, that will be 10 items in `PluginGroup` enumeration. 

Plugins developed by users will fall into one of these 10 predefined categories, they will not be able to create new one, unless it would be added to the `PluginBase` class by core developers.

In this case will be no Zoo. Only 10 (for example) possible options to choose from.

**Comment by daryllabar** [comment]
@shytikov.  Using an Enum, we're just limiting plugin developers to the (hypothetical) 10 Categories that (I'm assuming one would be an "Other").  If we used a String we could be completely open to developers defining whatever category they want via a String.  (What if someone internally wrote plugins that they wanted to group by "Production Ready" and "Not Production Ready" why limit them by using an enum?)  The XrmToolBox could still provide a struct that lists the 10 Group Names, so they are only ever defined in one spot, giving the intellisense of the Enum implementation, with the flexibility of a string implementation.

Love that we have this much discussion about a hypothetical future feature... Does GitHub Provide a better format for this type of communication?

**Comment by rappen** [comment]
@daryllabar You have my vote! :+1:

**Comment by shytikov** [comment]
We can have discussions on [Gitter](https://gitter.im/) :bulb:

**Comment by MscrmTools** [comment]
I updated the "normal" plugin model since all controls did not handle clicks. That should do the trick
