### ISSUE TITLE
SecondaryFontColor not used when showing large icons

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#152]
Changing the ``SecondaryFontColor`` only affects company info etc when displaying small icons.
![image](https://cloud.githubusercontent.com/assets/2572253/8180351/585342c2-141d-11e5-9330-36c3f102c178.png)

When displaying large icons only the ``PrimaryFontColor`` is used.
![image](https://cloud.githubusercontent.com/assets/2572253/8180370/7aaad268-141d-11e5-9615-aae0c56825c1.png)

**Comment by MscrmTools** [comment]
It is by design.

Would you like this to be used in Large icons list?

**Comment by rappen** [comment]
It does not really matter to me, I just noticed that second color was never used with the large icons.



-------- Originalmeddelande --------
Från: MscrmTools <notifications@github.com>
Datum: 2015-06-16 17:25 (GMT+01:00)
Till: MscrmTools/XrmToolBox <XrmToolBox@noreply.github.com>
Kopia: Jonas Rapp <Jonas.Rapp@cinteros.se>
Rubrik: Re: [XrmToolBox] SecondaryFontColor not used when showing large icons (#152)


It is by design.

Would you like this to be used in Large icons list?

-
