### ISSUE TITLE
Give the WebResource Manager a Better Workspace Concept

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#154]
I primarily use VS to edit js.  I just started using Roots and hitting a couple pain points.

1. When loading a root, htm files are not being loaded, only htm.
2. You have to do a full search for the path of a custom root.  You can't paste or type a file path
3. Would be awesome if there was a way to right click on the solution, and say Refresh from disk.
4. Would be even more awesome if there was an option to publish files that were modified after a certain DateTime.  You could chose a date time, or you could choose since last published, so as long as you leave the XTB open, it would know the last time it pushed webresources, and push all files that have been modified since then (or maybe just selected them?)

**Comment by rappen** [comment]
5. How about a file listener, automatically uploading and publishing web resources as they are changed on disk...? Very similar to a tool (not yet publicly available) by @shytikov that updates plugin assemblies in CRM when they are compiled in VS and changed on disk :)

**Comment by MscrmTools** [comment]
1. Easy
2. You would like to search for a specific file and the root will be added automatically? for example : if I choose the file c:\temp\new_\scripts\form\account.js, you would like the file is added in the treeview with new_ root, and subfolders scripts and form?
3.  Should be easy to do so, I just have to store the folder the files were taken from
4. That should be doable. When loading files or solution, save the current datetime. Then add an option to publish files changed after that datetime. Update date time after publishing
5. Seems weird to me. It means you are working outside WebResourceManager to deal with files but WebResourceManager updates and publishes web resources in background... Isn't it dangerous?

**Comment by daryllabar** [comment]
2. Is simpler, just use the same sort of dialog that you use to load files where you can paste in the path.  Right now if your dev folder is 6 folders deep, you have to navigate from C: to folder 1 to folder 2 to folder 3 etc... Via a GUI without the option to paste or type in the path.

5.  I could see that being dangerous if your working in a shared CRM environment, but if you're pointing to a local VM that only you have access to, I could see it being beneficial.

@rappen I would be interested in an auto publish Plugin tool.  Would be nice to add it to the build script, so you could create a Custom build that published it.  Any way I could get a hold of that?

**Comment by daryllabar** [comment]
OK, Git hub renumbered my numbers.  1 should be 2 and 2 should be 5

**Comment by MscrmTools** [comment]
Points 1 to 3 are covered in next release code.

Point 4 need more work time. I will close this issue (when validating changes) and create a new one for this specific point
