### ISSUE TITLE
Connecting to CRM Online Update 1

### ISSUE THREAD

**Issue by hprasad-dc** [MscrmTools/XrmToolBox#157]
I am getting errors when I try to connect to a CRM Online Update 1 demo organisation.  Is the latest release of XrmToolBox expected to work with CRM Online Update 1?

**Comment by MscrmTools** [comment]
Yes, it should work

I can connect to the same kind of organization.

Can you provide a screenshot of your connection settings?

**Comment by hprasad-dc** [comment]
Hi,
Thanks for the prompt response.  It is all good now – looks like there was some temporary glitch in my crm online environment.
Regards,
Hari
