### ISSUE TITLE
Execute plugins inside separate AppDomains

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#158]
Hi,

I haven't tried this scenario in `MEF` enabled version yet, but in `Main` branch it's possible to reproduce.

Due to .NET nature not all resources are possible to dispose explicitly. In fact we cannot control when and how most of the objects will be disposed. And most unpleasant for me is events, to which objects are subscribed.

For example I just reproduced really stupid situation, when my plugin, which is using _internal_, **private** instance of `FileSystemWatcher` type, was responding on events even plugin itself was closed. Naturally, whole `XTB` crashed loudly after this event raised.

I think we could wrap all plugins into separate `AppDomains`. This will let us kill two rabbits with one stone: we will protect `XRM` internals from retrospection (by revoking Reflection permission from `AppDomain`) and will safely release everything after `AppDomain` will be disposed with plugin closure. 

What to you think?

**Comment by daryllabar** [comment]
As a part of the Closed Event, you could remove all of your event handlers.  That is probably a good idea to do anyway.

**Comment by MscrmTools** [comment]
Just one comment, using AppDomain will require plugins to communicate only through methods as Properties does not seem exposed through proxy

It seems far more complicated to me but I'm not a super developer... If you succeed to implement it, I'm interested

**Comment by shytikov** [comment]
@MscrmTools if you interested I'm also interested :+1:

**Comment by MscrmTools** [comment]
Using AppDomain for each plugin is the only way to allow unloading of a plugin to reload it for autoupdate feature, so Yes I'm interested.

**Comment by shytikov** [comment]
@MscrmTools so, killing two rabbits with one stone! 

@daryllabar you're right, your approach will work. But needed object could be buried deep somewhere in the structure, so it would be inaccessible to unsubscribe in this case destroying AppDomain will be the only choice, as I can see it.

**Comment by rappen** [comment]
From my subjective perspective - I have prepared FXB for the current MEF-approach and I am going on vacation.... I'm ready to publish next release by the click of a button, but I am not ready to re-work the plugin if any of the above changes requires so...
Would that be required, and if so, when?

**Comment by shytikov** [comment]
No changes needed from plugin developers. It's core feature — plugins will be executed inside unrestricted sandbox. Plugins will not feel difference, except the fact they could be fully unloaded and reloaded when core decide to do so.

**Comment by rappen** [comment]
I am though a bit worried by the comment @MscrmTools made that no properties are accessible, I believe that can cause problems for me...

**Comment by MscrmTools** [comment]
After some thinking, maybe I'm wrong...
The problem I had was when I was using only one interface. Now that we have two of them (IXrmToolBoxPlugin and IXrmToolBoxPluginControl), that should be less problematic...
Another thing to consider when using appDomain, passing data between appdomain seems to work only with simple types (for example, Image cannot be passed through appdomains proxies)

**Comment by shytikov** [comment]
Yes, there is an obstacles that prohibits crossing appDomain boundaries. But even complex types could be passed if they are could be serialized or they are derived from `MarshalByRefObject` class.

So far I was able to transfer all types of objects from and to appDomain, except `async` related objects, like `TaskResult` class or something like this.

**Comment by MscrmTools** [comment]
It seems this request won't be able to be implemented. Closing the issue
