### ISSUE TITLE
Start plugin using keyboard

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#159]
Low prio question: Is there any way to start a plugin without clicking on it with the mouse?
I like my keyboard and try to develop as much as possible for "keyboard control".

**Comment by MscrmTools** [comment]
Currently no

What could be done is: when filtering plugins list with search bar, if only one plugin remains and the user press Enter, then the plugin is opened

**Comment by rappen** [comment]
Or making the list focusable and accepting that "enter = click" ? Now only the button bar has focus when tabbing the main form.

**Comment by MscrmTools** [comment]
It should be possible to navigate the plugins list with keyboard...

**Comment by shytikov** [comment]
I've added feature starting plugin from search box.

So far it's just standard .NET implementation, so it's not `Google Chrome`'s smart address bar, please keep in mind.

**Comment by MscrmTools** [comment]
I've merged my dev branch to main branch
