### ISSUE TITLE
MetadataDocGen - When "Location on form" is selected, list only a single form per row.

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#165]
When "Include Attribute location in Forms" option is checked in the Metadata Document Generator -
![2015-06-30_12-46-50](https://cloud.githubusercontent.com/assets/6276300/8436915/adfedf44-1f29-11e5-9665-991e0fbb6524.png)
 

If Individual Forms are not selected you get duplicated rows in the output.
(Listing the attribute multiple times would be good - if only one form was indicated per row.  As it is, the attribute is listed once per form and all forms are listed every time - resulting in rows that are duplicates of each other.)
![2015-06-30_12-46-09](https://cloud.githubusercontent.com/assets/6276300/8436812/035d43c8-1f29-11e5-85e9-d3f0626248dc.png)

If an Individual Form is selected, the attribute is only exported one time, but it still includes references to the 'unselected' forms. - It should only include a reference to the 'selected' form.

![2015-06-30_12-43-03](https://cloud.githubusercontent.com/assets/6276300/8436814/06a5101a-1f29-11e5-9c42-d6ab43be424a.png)

**Comment by andypopkin** [comment]
When I choose the "All Attributes on Forms" I get nothing returned in the list of forms and nothing returned in my export.

**Comment by MscrmTools** [comment]
When selecting this option, you need to select the entity on the left side, which should display the list of forms. You can then select the forms to use

**Comment by andypopkin** [comment]
Ah okay, user error. This can be closed/removed! Thanks!
