### ISSUE TITLE
Selected and Tool Order settings no longer applied.

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#167]
In the Settings dialog, the tool 'selection' checkboxes and the preferred order are no longer applied to the main toolbox window.

![2015-07-06_12-19-43](https://cloud.githubusercontent.com/assets/6276300/8527334/1ea755b4-23da-11e5-9693-acbb35839419.png)

**Comment by shytikov** [comment]
I would say, if you un-check "Display most used tools first", hiding start working.

So it's actually collision of settings. "Display most used tools first" should display only enabled tools.

**Comment by shytikov** [comment]
Counts of how many times plugins was called don't work for me through...

**Comment by MscrmTools** [comment]
This is due to how MEF exposes class name

Bug fixed!
