### ISSUE TITLE
Import/Export NN relationships does not work after update to 1.2015.7.6

### ISSUE THREAD

**Issue by UlrikBC** [MscrmTools/XrmToolBox#169]
Load Metadata results in this error:
"An error occured: Object reference not set to an instance of an object."

Previous versions all worked fine and get the same result on multiple machines.

**Comment by MscrmTools** [comment]
Hi,
This plugin was using semicolon instead of coma as separator . The tool has been fixed to use coma instead of semicolon. 

Could you test it with this new separator?

**Comment by crmch** [comment]
Hi,

Same issue, clicking on load metadata results in:

"An error occured: Object reference not set to an instance of an object."

**Comment by UlrikBC** [comment]
The error comes first thing when trying to load the metadata. I am on version 1.2015.7.6.

![2015-07-08_6-41-52](https://cloud.githubusercontent.com/assets/13226192/8571578/84b61738-253c-11e5-85f1-d013de6c353a.png)

Thanks

**Comment by MscrmTools** [comment]
Ok, I change the way the plugin was written to align with new development process. The bug was found and fixed.
I guess I'll publish a new release soon to clean other bugs due to new plugin development model
