### ISSUE TITLE
Debugging Inside a XrmToolBox Plugin

### ISSUE THREAD

**Issue by edgardojimenez** [MscrmTools/XrmToolBox#17]
I want to know how to debug inside a XrmToolBox plugin.  The debugger doesn't stop on a breakpoints inside a plugin.  Is there a trick?  Awesome tool BTW.  Thanks in advance.

**Comment by shytikov** [comment]
Maybe your XrmToolBox captures compiled binary from its distribution, instead of your code?

It should be something trivial there. Maybe you just cannot hit breakpoint, since it's not in execution path?

**Comment by MscrmTools** [comment]
You must attach to xrmtoolbox.exe and make sure dll and pdb files for your plugins are in the Xrmtoolbox folder

**Comment by JasonMichaelRobertson** [comment]
You need to setup like this https://www.xrmtoolbox.com/documentation/for-developers/debug/ also Build Events must create the Plugin Folder in Debug Folder root then the XrmToolBox.exe with its dll's also needs to be in the Root of the Debug Folder. Download the Sample Project at the Bottom of this Page https://www.xrmtoolbox.com/documentation/for-developers/multipleconnectionsplugincontrolbase-base-class/ Build it remove the Read only on Files then start with debugging
