### ISSUE TITLE
Audit Center - Suggestion of solving todays overwhelming list of attributes => almost infinite scrolling 

### ISSUE THREAD

**Issue by pieeetr** [MscrmTools/XrmToolBox#173]
Attributes are today grouped by entity which is good, but the list of attribues can be extreamly long. Some say even the engineers at the mouse department over at logitech are fidgeting :)

Alternative A) I believe that an easy adjustment would enhance usability. Use the same convention as you have done in the view layout replicator. Select an (1) entity from the entity list on the left side, Then populate associated attributes in the right list.

Alternative B) Just collapse the list of attributes so you only see entity names at first glance, then you have to click on an entity to see the associated attributes.

Keep up the good work you're doing. Really awsome stuff!

**Comment by MscrmTools** [comment]
Hi, that makes sense!

I will work on it

Thank you for the feedback!
