### ISSUE TITLE
Attribute Bulk Update: Inactive Forms

### ISSUE THREAD

**Issue by adoerig** [MscrmTools/XrmToolBox#176]
We use the attribute bulk updater a lot. Great tool!

In a crm migration we had to deactivate the old 2011 forms. Now it seams that the "on from" attribute in attribute bulk updater also checks inactive forms. This does not make sens for me, because we do not use them any more. Because they are system froms we can not delete them.

Thanks
Adrian

**Comment by MscrmTools** [comment]
Thank you for reporting this.

I will fix it for next release

**Comment by adoerig** [comment]
Great! Thanks!!

**Comment by MscrmTools** [comment]
Ok, I filtered on FormActivationState = 1 (active) and added also Quick Create forms

**Comment by adoerig** [comment]
Thanks a lot. Works perfectly!
