### ISSUE TITLE
Metadata Document Generator: Form Location not working in latest build

### ISSUE THREAD

**Issue by andypopkin** [MscrmTools/XrmToolBox#177]
Not sure if I am the only one experiencing this or not, but the Form Location feature of the Metadata Document Generator does not appear to be functioning like it used to. Going back to version 1.2015.6.9 is a workaround for now :)

**Comment by MscrmTools** [comment]
See Issue #165 to understand changes for this feature.

I guess it is now working as it should have worked since the beginning
