### ISSUE TITLE
Tool for bulk Export / Import CHARTS?

### ISSUE THREAD

**Issue by miiiaptyltd** [MscrmTools/XrmToolBox#178]
Hi Team,

What a great set of tools.

I was wondering if anyone has ever considered building a tool to assist in Exporting / Importing CHARTS in bulk?

Seems like it may be most similar to the View Layout Replicator where you could select the Entity, and then tick one/many CHARTS to Export.

Importing would be great if it could be acted on in Bulk, but would need to consider the fact of Replacing/Creating Another if the same Chart already exists.

Once again, fantastic job everyone.

Dan

**Comment by MscrmTools** [comment]
This is a great tool idea! I add it to my to do list!

**Comment by miiiaptyltd** [comment]
Cool.

I doubt I'd be much help with building the plugin, but I'd be happy to do any testing that may help out.

Cheers,
Dan

**Comment by MscrmTools** [comment]
Here is the documentation for the upcoming tool https://github.com/MscrmTools/XrmToolBox/wiki/Chart-Manager

**Comment by miiiaptyltd** [comment]
Wow!

Looks amazing. Better than I had expected!

Look forward to trying it.

Dan



MiiiA Pty Ltd

On 26 Jul 2015, at 11:02 pm, MscrmTools <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is the documentation for the upcoming tool https://github.com/MscrmTools/XrmToolBox/wiki/Chart-Manager

-
