### ISSUE TITLE
1.2015.6.9 error when generating document for all attributes on form

### ISSUE THREAD

**Issue by UnaClancy** [MscrmTools/XrmToolBox#179]
This issue only happens when I select all attributes on form, it happens I select one entity or all entities and if I select the form name or no form. it successfully prints to word if I say all attributes.
![error message 1](https://cloud.githubusercontent.com/assets/13444878/8817184/8c927266-3073-11e5-8b2d-7af6043fb2b8.png)

**Comment by MscrmTools** [comment]
What if you try the same with version 1.2015.7.6 ?

**Comment by UnaClancy** [comment]
Okay i downloaded this version and the issue has been resolved, much appreciated.
