### ISSUE TITLE
July Release - issue loading dll (Update: not replicated anymore)

### ISSUE THREAD

**Issue by maturmel** [MscrmTools/XrmToolBox#180]
Hi,

It looks like the plugin loading code looks for classes named "Plugin" in the plugin assemblies. I would have expected it to look for a classe inheriting PluginBase instead. This would allow more flexibility towards the naming of our descriptor classes.

In my setup I have plugin assemblies that reference other utility assemblies that share code with CRM plugins. I have one of these utility assembly holding a class named "Plugin" but it refers to the base Plugin class of CRM. It has nothing to do with XrmToolBox. The toolbox tries to instantiate that class and fails as soon as this utility assembly is in the Plugins folder. The plugin class is not decorated with [Export].

Of course I could break my utility assembly and try to remove the need to have that class deployed to the Xrm Toolbox plugin, but this is too big of a project for me to do right now (My CRM solution has 50 projects in it). I had to revert to the June release for now, I will take a closer look at this later.
However I think it would be nice is the plugin loading went less broad in its search of plugin class (maybe by requiring the Export attribute to be present - which I thought was the case when I read the release notes).

Regards
Marc-Andre

**Comment by MscrmTools** [comment]
Hi,
I guess you did not figure out how the new plugin mechanism is working

It is absolutely not searching for a class nameds plugin. It loads all class that are decorated with Export attribute and are implementing interface IXrmToolBoxPlugin.

Maybe the migration documentation is not clear enough (I'm not good at writing development documentation and my English is not as good as I would like to). Do not hesitate to update it to be clearer.

So, to update your plugins, you should basically do 3 steps:
- Create a new class (named whatever you want) that implements IXrmToolBoxPlugin and decorate it with Export attribute, as explained in upgrade documentation
- Implements the unique method of IXrmToolBoxPlugin that return your current plugin UserControl
- Update your existing plugin by removing class attributes and (only if not devired from pluginbase) change IMsCrmToolsPluginUserControl to IXrmToolBoxPluginControl

**Comment by maturmel** [comment]
Hello,

Thanks for reaching out. Let me clarify the error I experienced yesterday.
My issue is not about making my plugins recognized by the new version. This I was able to succeed by following your documentation.

My plugin assembly reference another assembly (file named Utilites.dll). I have put there classes that I share between several XrmToolBox plugins and other CRM-related code too. That Utilities.dll contains a class named "Plugin", which I am guessing is the source of my error. As soon as this Utilities.dll is in the Plugins subfolder of XrmToolbox, the XmlToolbox throws an unhandled exception on start, and does not reach the normal screen. Whenever I remove this assembly from the folder, the program starts normally.

I understand the purpose of the Export attribute and I can confirm you I am not using it anywhere in my Utilties.dll. So I don't understand why there is a problem loading that dll in XrmToolbox. I have other dlls that do not contain any XrmToolBox plugin (but have shared code as well) and they load fine when placed in XrmToolBox/Plugins folder. So in trying to find out why Utilities.dll causes problem when loading, the one thing that caught my eye is that it contains a class named "Plugin". 

If you want sample of my code or dll to replicate on your end please let me know.

Regards
Marc-Andre

**Comment by MscrmTools** [comment]
I'm happy everything works fine now!

I'm closing the issue
