### ISSUE TITLE
connection problem (saasplaza)

### ISSUE THREAD

**Issue by JurriaanK** [MscrmTools/XrmToolBox#181]
Hi, I get an error message when I try to create a new connection and press 'get Orgs'.
I included a picture of the error message.
I tried different ways of typing server name / domain / home realm url. This was the only option where a login attempt was made (judging from the error message).

Is there a solution to this problem?

![error](https://cloud.githubusercontent.com/assets/13466194/8848448/b317a2d4-3137-11e5-82ce-0170c44deb75.jpg)

**Comment by MscrmTools** [comment]
Just fill server name with Discovery endpoint, without protocol, something like discovery.saasplaza.com

**Comment by JurriaanK** [comment]
I tried, but I get another error:
[image: Inline image 1]

Jurriaan

**Comment by JurriaanK** [comment]
My password contains a space-character by the way. Could that be part of the problem?

**Comment by JurriaanK** [comment]
I did some googling:
Maybe it is a similar problem like this?
http://forums.asp.net/t/1700221.aspx?ID3242+The+security+token+could+not+be+authenticated+or+authorized+

**Comment by MscrmTools** [comment]
No, there is no reason this is the cause

Do not put any value on Domain field, put just your username in Username and of course your password

**Comment by JurriaanK** [comment]
I tried these combinations:

Use SSL | Use IFD | Server Name | Server Port | Home realm url | Domain (custom authentification) | Error
------|---|-------|----------|----|---|---|-----
X |  | discovery.crm2011.saasplaza.com | 443 | (empty) | ***********.crm2011.saasplaza.com | 1
X |  | ***********.crm2011.saasplaza.com | 443 | (empty) | ***********.crm2011.saasplaza.com | 1
X |  | discovery.crm2011.saasplaza.com | (empty) | (empty) | ***********.crm2011.saasplaza.com | 1
X |  | ***********.crm2011.saasplaza.com | (empty) | (empty) | ***********.crm2011.saasplaza.com | 1
X | X | ***********.crm2011.saasplaza.com | 443 | (empty) | ***********.crm2011.saasplaza.com | 2
X | X | ***********.crm2011.saasplaza.com | (empty) | (empty) | ***********.crm2011.saasplaza.com | 2
X | X | discovery.crm2011.saasplaza.com | (empty) | (empty) | ***********.crm2011.saasplaza.com | 2
X | X | discovery.crm2011.saasplaza.com | 443 | (empty) | (empty) | 2
X | X | ***********.crm2011.saasplaza.com | 443 | (empty) | (empty) | 2
X | X | discovery.crm2011.saasplaza.com | (empty) | (empty) | (empty) | 2
X | X | ***********.crm2011.saasplaza.com | (empty) | (empty) | (empty) | 2

All of course with valid username and password.

********* is the domain I type in the browser when I login into CRM.

Error 1:
![error1](https://cloud.githubusercontent.com/assets/13466194/8861707/38b6392e-318c-11e5-9a68-f6d986df6f50.jpg)

Error 2:
![error2](https://cloud.githubusercontent.com/assets/13466194/8861711/3cadc920-318c-11e5-95e5-5dc6991d3cf4.jpg)

**Comment by MscrmTools** [comment]
When I said use discovery.saasplaza.com, it was perhaps just an example. I don't know what the value is. 
You should look at it in CRM web app > SETTINGS > Customizations > Developer resources

**Comment by JurriaanK** [comment]
Yeah, i got that. I did look it up and it is correct as I used it: discovery.crm2011.saasplaza.com. I really tried a lot of combinations, retyped my password several times to be sure, etc.
BTW, I also use MSCRMToolKit_0.6.2, where you must also login to CRM from a desktop application. Logging in is no problem with that. So I really don't know what I can do anymore. Are you really sure it is not a problem in your application or in the interaction between Saasplaza and your app?

Tell me what I can do to identify the problem, I will make a detailed report with screenshots and all.

**Comment by MscrmTools** [comment]
Could you send me a user/password info so that I can test myself?

**Comment by JurriaanK** [comment]
I cannot create users myself, unfortunately. My username has admin rights and there is some sensitive data present, so I could not. Is there another way?

**Comment by MscrmTools** [comment]
Can you send me screenshots of IFD Wizard  from deployment manager? 
Maybe I could identify something wrong

**Comment by JurriaanK** [comment]
No, I have no access to the deployment manager. Saasplaza is a third party (actually fourth party in our case) which is hosting our CRM.

**Comment by JurriaanK** [comment]
I could ask our supplyer for a temporary login with no access to the entities we are using, but that could take a while.

**Comment by JurriaanK** [comment]
And I am also not sure if they want to... :-S

**Comment by MscrmTools** [comment]
Can't help more without more info

**Comment by JurriaanK** [comment]
I understand, I will try. I get back to you next week. Thanks so far.

**Comment by JurriaanK** [comment]
I succeeded to connect with the account of a colleague. The only difference
is that her password is shorter and doesn't have a space character at the
end (like 'password ').
So my guess is that's the problem. I cannot change it myself, but I will
ask my supplier next week.
Thanks for your time and your great tool! I 'll make a donation.



Jurriaan

**Comment by MscrmTools** [comment]
Thanks
