### ISSUE TITLE
Web Resource Manager : Allow to update and publish from a specific DateTime or last Update/Publish DateTime

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/XrmToolBox#186]

**Comment by MscrmTools** [comment]
@daryllabar I'm working on this item you requested some times ago and here is what I implemented so far

Each web resource now has a State that stores if the web resource has been changed, updated or published or none of the previous state.
When you save locally a web resource, a panel indicates how many web resources need to be updated to the CRM organization.
More over, the whole path to these web resources is in blue in the tree view

Here is the general display
![image](https://cloud.githubusercontent.com/assets/10774317/15506527/4775b39a-21c8-11e6-9121-6ae09953af8e.png)

Here is the option when you click on "Update" link
![image](https://cloud.githubusercontent.com/assets/10774317/15506626/97e27854-21c8-11e6-9372-437362a171a9.png)

Question: Should I process local items (loaded from disk) or remote items (loaded from organization) the same way. Meaning, Should I display a message "must be updated to the CRM organization" when local items?

**Comment by daryllabar** [comment]
First off, awesome.  Second off, not sure I understand your question.  Local files will 

1. Not exist in CRM
2. Exist in CRM, and not have changed
3. Exist in CRM, and changed locally, but not on the server
4. Exist in CRM, and changed on the sever, but not locally
5. Exist in CRM, and changed both locally and on the server.

Nothing is required for 2.
1 and 3 should result in changes being pushed to CRM
4 should result in changes being pulled down locally,
5 should result in asking the user if they want to override the server file with their local version.

Does that answer your question?

**Comment by MscrmTools** [comment]
Yes it does! 

Not sure yet how to handle points 4 and 5 since I cannot see yet how to determine that a file is different because the server file is more recent or older than the local file

**Comment by daryllabar** [comment]
I see a couple options.

I think the best option would be to show a different icon color, or background, or something, that distinguishes that these files have not yet been sync'd to CRM since opening the tool.  If the file changes, once the tool has already loaded the local files, then just show those as needing to be sync'd.

Once the files have been sync'd to CRM, then you'll be able to maintain 4 & 5.  

Does that make sense?

**Comment by MscrmTools** [comment]
Yes, it does... Still need to find what is the best UI behavior to highlight these items

**Comment by daryllabar** [comment]
You could take the standard Icons, and just add a opacity to them, so they are grayer, until they've been sync'd

**Comment by MscrmTools** [comment]
Yes, possible... I will do it

**Comment by MscrmTools** [comment]
Done! And delivered in latest WebResources Manager.

Points 4 and 5 will be handled in a future release

**Comment by Samitya** [comment]
I get an error when I trying to update any webresource. System.OverflowException: Value was either too large or too small for an Int32
[https://c2n.me/3VVN0b8](url)
Version
[https://c2n.me/3VVN8jr](url)

**Comment by Samitya** [comment]
Any news?

**Comment by friedrickjoel** [comment]
> I get an error when I trying to update any webresource. System.OverflowException: Value was either too large or too small for an Int32
> [https://c2n.me/3VVN0b8](url)
> Version
> [https://c2n.me/3VVN8jr](url)

I also have this issue.  I've tried to remove all traces of XrmToolbox and the Plugin, nothing works.

**Comment by ololonly** [comment]
@Samitya @friedrickjoel have you found some solution?
