### ISSUE TITLE
Web Resource Manager : Allow to expand/collapse nodes including subnodes

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/XrmToolBox#187]
This will help to collapse all tree nodes in one action, which is better with many leafs

**Comment by zmulk** [comment]
Where do I find the collapse all button in the menu item ?
It is not there, I do find it in when I right-click a node, but ut that collapse only that node with its children.

**Comment by MscrmTools** [comment]
There is no "Collapse all" button... 
If you need one, please create a new issue
