### ISSUE TITLE
A Really Silly Question .... 

### ISSUE THREAD

**Issue by lindainevanston** [MscrmTools/XrmToolBox#189]
Have used XrmTool box for a long time.  But this new version I can't start.

I downloaded and unblocked the zip.  Unzipped.   No issues; but I don't find an EXE to start the application as with previous versions.  

Maybe it's just been a long week .... Any feedback will be appreciated.

Thanks!

L.

**Comment by MscrmTools** [comment]
I know that some antivirus remove untrusted executable. Maybe you are facing this situation but I can assure you there is still a xrmtoolbox.exe file. The only latest difference is all plugins are in a Plugins folder

**Comment by MscrmTools** [comment]
No feedback, so I close this issue. Do not hesitate to reopen it if needed
