### ISSUE TITLE
I have MS CRM 2011 which version of XRMTOOLBOX should use.

### ISSUE THREAD

**Issue by Manimozhi** [MscrmTools/XrmToolBox#190]
I downloaded the latest source code it came with referenced assemblies for Microsoft.Xrm.Sdk.dll with version 7.0.0.0. In my current dev environment uses 5.0. I am not able to build the solution the error is 
Error	175	The type or namespace name 'Xrm' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	C:\Projects\XrmToolBox-master\XrmToolBox-master\XrmToolBox\MainForm.cs	9	17	XrmToolBox
it would be good to know which version used for XRM.SDK 5.0.

**Comment by daryllabar** [comment]
If you want to build the latest solution, you'll need the 7.X SDK dlls.  If you want connect to CRM 2011, you can do so with the latest XrmToolBox versions.  Just download the actual complied exe.  You'll need to go to CodePlex to find code that would be using the 5.0 SDK dlls.

**Comment by Manimozhi** [comment]
Thanks, EXE works
