### ISSUE TITLE
View Transfer Tool : Filter Source User Views by Owner or System.

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#191]
[Feature Requests]

1) Allow the user to filter the list of entities+views to "User Views", "System Views", or "All Views"
2) Add a source user filter to narrow the selection to the views owned by a specific user. 
3) Additionally, if possible, allow the plugin user to select one, multiple or all views owned by the selected user for transfer - without clicking into each entity to find whether there are user views contained in that entity. 

One or more of these options would be useful to quickly copy/update one or more of the user views owned by User A in Dev to Prod.

**Comment by gfritz** [comment]
Amended commit message which made a duplicate reference I cannot remove.  Now trying on item 3.

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/DamSim.ViewTransferTool #2](https://github.com/MscrmTools/DamSim.ViewTransferTool/issues/2) via [**ZenHub**](https://www.zenhub.com/)
