### ISSUE TITLE
View Transfer Tool : Allow the selection of the user in the destination org.

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#192]
[Feature Request]

Allow the user to select the destination user for the views in the destination environment. - Or optionally, assign the views to the 'connection' user in the destination.

Currently if moving from one environment to another, unless the user is the same guid as the source environment, the transfer will fail.

**Comment by maerger** [comment]
Yes please this would be a great feature!

**Comment by pieeetr** [comment]
Sounds neat!

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/DamSim.ViewTransferTool #1](https://github.com/MscrmTools/DamSim.ViewTransferTool/issues/1) via [**ZenHub**](https://www.zenhub.com/)
