### ISSUE TITLE
Tool Suggestion : Export/Import Access Team Templates

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#194]
When moving an entity that has Access Teams enabled from one environment to another, the access teams aren't moved - and if the access team templates are created new in each environment, the GUIDS are different - This causes trouble when you move an solution containing an entity form that references the access team from one environment to the next. - 

It would be helpful to be able to export one or more Access team Templates from one environment to an xml file - and then import / update them in another environment from the previously exported file.

This would help by making sure the GUIDS for the access teams match in both environments.

(The two environments are in very different domains and can't be connected simultaneously, so allowing for transfer via a file would be important to me.)

**Comment by MscrmTools** [comment]
@mscottsewell even if I saw you already talked with lucas_is, I record here the fact that he has developed this plugin. I will put the download url in this thread as soon as it is available

**Comment by lucasalexander** [comment]
So one issue @mscottsewell will have with my solution is that it's a point-to-point connection - no saving the file and then loading it later :(. I probably would be looking at that at some point, but I don't have a firm ETA.

**Comment by mscottsewell** [comment]
@lucasalexander - I don't see that as a barrier. My current config only has 3 Access Teams defined. (two on one entity and one on another.) - So far I haven't had a config with more than 6 Access Team Templates - (which was probably 2 too many.)  - 
Besides I do this move so rarely that I'm guessing I'd lose a config file in the time between moves and still wind up having to recreate it. :)

**Comment by MscrmTools** [comment]
Available here : https://github.com/lucasalexander/Crm-Sample-Code/releases/tag/AlexanderDevelopment.AccessTeamTemplateMover-v1.0
