### ISSUE TITLE
Can't load sitemap

### ISSUE THREAD

**Issue by MarcusNaylor** [MscrmTools/XrmToolBox#195]
XRMToolBox v1.2015.2.4.  CRM 2013 SP1 on premise.

I previously had no issues loading the SiteMap, now this fails with the following error
I can't pinpoint the unexpected end of line in the XML, and my SiteMap XML checks out as valid.

![image](https://cloud.githubusercontent.com/assets/12860642/9059830/a7929032-3aa5-11e5-88c7-659c5cec211f.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: SubArea. Line 1, position 237.
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at MsCrmTools.SiteMapEditor.AppCode.TreeNodeHelper.AddTreeViewNode(Object parentObject, XmlNode xmlNode, SiteMapEditor form, Boolean isDisabled)
   at MsCrmTools.SiteMapEditor.AppCode.TreeNodeHelper.AddTreeViewNode(Object parentObject, XmlNode xmlNode, SiteMapEditor form, Boolean isDisabled)
   at MsCrmTools.SiteMapEditor.AppCode.TreeNodeHelper.AddTreeViewNode(Object parentObject, XmlNode xmlNode, SiteMapEditor form, Boolean isDisabled)
   at MsCrmTools.SiteMapEditor.SiteMapEditor.DisplaySiteMap()
   at MsCrmTools.SiteMapEditor.SiteMapEditor.<LoadSiteMap>b__4(RunWorkerCompletedEventArgs e)

**Comment by MarcusNaylor** [comment]
Just updated to v1.2015.7.6 (was using the updater but not on the most current version).  Error is still the same as above.

**Comment by MscrmTools** [comment]
Hi,
The error seems to indicate there is a problem with a sub area node.
Sitemap editor cannot produce this kind of errors so I imagine sitemap has been edited manually somewhen
The only way to fix it is to query sitemap SQL table to retrieve xml, find the subarea in error and fix it

**Comment by MarcusNaylor** [comment]
The site map has not been edited manually, the only times it has been edited is with XrmToolBox or by adding solutions. Bothers does not appear to be any errors in the site map in CRM, and when I inspect the XML it validates.

Sent from my iPhone

On 5 Aug 2015, at 17:22, MscrmTools <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
The error seems to indicate there is a problem with a sub area node.
Sitemap editor cannot produce this kind of errors so I imagine sitemap has been edited manually somewhen
The only way to fix it is to query sitemap SQL table to retrieve xml, find the subarea in error and fix it

—
Reply to this email directly or view it on GitHub<https://github.com/MscrmTools/XrmToolBox/issues/195#issuecomment-128057075>.



Marcus Naylor

Business Intelligence – CRM Developer
Craneware

Office:         +44 131 550 3189
Mobile:         +44 798 452 0576
Fax:    +44 131 550 3101

M.Naylor@craneware.com<mailto:M.Naylor@craneware.com>

www.craneware.com<http://www.craneware.com>



About Craneware, Inc.
Craneware (AIM: CRW.L) is the leader in automated revenue integrity solutions that improve financial performance for healthcare organizations. Craneware's market-driven, SaaS solutions help hospitals and other healthcare providers more effectively price, charge, code and retain earned revenue for patient care services and supplies. This optimizes reimbursement, increases operational efficiency and minimizes compliance risk. By partnering with Craneware, clients achieve the visibility required to identify, address and prevent revenue leakage. To learn more, visit craneware.com<http://www.craneware.com/> and revenueintegrityjourney.com<http://www.craneware.com/journey/>

NOTICE: This email contains confidential or proprietary information which may be legally privileged. It is intended only for the named recipient(s). If an addressing or transmission error has misdirected the email, please notify the author by replying to this message. If you are not the named recipient, you are not authorized to use, disclose, distribute, copy, print or rely on this email, and should immediately delete it from your computer system.

**Comment by MscrmTools** [comment]
Older version are still available here : https://github.com/MscrmTools/XrmToolBox/releases

Search for releases, not prereleases

**Comment by MscrmTools** [comment]
Problem comes from comments that contain only text. 
Fixed
