### ISSUE TITLE
Is the Import/Export N:N Relationship Tool Compatible w/ CRM Online 2015?

### ISSUE THREAD

**Issue by retsik** [MscrmTools/XrmToolBox#198]
I haven't had the ability to test it in 2013, but I'm able to load the metadata, identify my assets and the input file (two values separated by ;).  When I click the Import NN Relationships button, a small yellow pops up for about a quarter of a second and disappears.  No entry is made on the log window and no data appears to have been imported.

I've tried switching the entities around, a single row input file, but the results are the same.

Additionally, when I select the Export N:N button, I get the file dialog, but no file is ever saved.

**Comment by MscrmTools** [comment]
The tool has been changed to use comma instead of semicolon as the separator.
Can you test again with this separator?

**Comment by retsik** [comment]
No change...  :-(

Here's some sample records from my import file:

DH0021576LT,1049700000-6756201000-6372005
DH0021578LT,1047100000-6727101000-6372005

The first value is the unique key for my custom Asset entity, and the second is the unique key for my custom Account Code entity.

Here's a snapshot of my tool settings:

![image](https://cloud.githubusercontent.com/assets/11135293/9137119/98fe3cb0-3ce9-11e5-9eb2-6b31cbbe0f95.png)

**Comment by lykebank** [comment]
I'm having this same issue.  The N:N import tool doesn't appear to do...anything.

**Comment by gabeworden** [comment]
Same issue with 2015 On Prem and version of toolbox 2015.7.31

**Comment by retsik** [comment]
I'm getting ready to port data from an old MS Access system into a new CRMOL 2015 solution.  I've managed to develop the necessary extracts and CRM imports, with the exception of the one N:N relationship.  Unless I can get the N:N import tool working soon, I guess my only option will be to develop a junction entity and modify the associated forms.

**Comment by MscrmTools** [comment]
Sorry but I'm in vacation and I'm not able to fix this problem until I'm back in two weeks.
If someone who forked the project can fix it, I should be able to merge the fix

**Comment by shytikov** [comment]
Guys, we need to setup automatic builds for `XTB` just for cases like this, so we can fire development builds without @MscrmTools being so much involved. 

I have small fix for the issue. I have found that service instance used in the plugin was never assigned, so I just reused service instance supplied with `PluginBase`.

@retsik, @lykebank can you build code? Or it's better to provide you binaries for testing?

**Comment by shytikov** [comment]
@MscrmTools pull request #203 was created.

**Comment by lykebank** [comment]
Binaries would be better for me, for testing.

**Comment by retsik** [comment]
I can't build the code, so the binaries would be great -

**Comment by shytikov** [comment]
@retsik, @lykebank can you please check this binary: https://github.com/Cinteros/XrmToolBox/releases/download/issue-198/Javista.XrmToolBox.ImportNN.zip ?

Just extract this file to your `Plugins` folder. It should overwrite old plugin.

This is temporary location for the binary, I will remove files as soon as issue will be confirmed fixed and solution will be merged to `XTB` trunk.

**Comment by lykebank** [comment]
@shytikov The new .dll works as expected.  Thanks for the troubleshooting!

**Comment by retsik** [comment]
Working for me as well.  Thanks!! 





-------- Original message --------

**Comment by shytikov** [comment]
Glad to hear! :100:
