### ISSUE TITLE
Enhance ConnectionDetail object with web-address of given organization

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#2]
`ConnectionDetail` object of `PluginBase` does not contain easy to find web-address of given organization.

It contains server address, server port, switch is connection secure and other stuff, but no easy to access information about organization web-address.

After roaming around I find out that it is possible to extract this using following code:

```c#
var chunks = this.ConnectionDetail.GetOrganizationCrmConnectionString().Split(new char[] { ';', '=' }, StringSplitOptions.RemoveEmptyEntries);
var url = new Uri(chunks[1]);
```

But it would be much nicer, if this information would be accessible from `ConnectionDetail` directly.

**Comment by MscrmTools** [comment]
Ok, I will add this information in ConnectionDetail class

**Comment by shytikov** [comment]
Thank you!
