### ISSUE TITLE
Webresource Manager Refresh From Disk isn't working

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#200]
http://screencast.com/t/e2VstSmrRV (Don't konw why, but the audio is out of sync)

Basically the Refresh from Disk throws an error when attempting to refresh a single item in the tree, and does nothing when attempting to refresh from a folder or root.  Also the folder / root doesn't remember the folder it is mapped to.

**Comment by MscrmTools** [comment]
even if I found another bug when refreshing folder from disk for certain file names, refreshing content seems to work for me in the latest (pre)release (and I did not change anything in WebResourceManager)

**Comment by MscrmTools** [comment]
I close this issue because I think it is working. If not, please reopen this issue
