### ISSUE TITLE
Does the Import/Export NN Relationships tool work anymore?

### ISSUE THREAD

**Issue by lykebank** [MscrmTools/XrmToolBox#201]
When I identify the entities, relationship, and fields, and then browse & select my .csv file, and then click Import NN relationships...nothing happens - no logs in the Log window and nothing gets imported.

I've tried with comma-separated csv, comma-separated txt, and semi-colon-separated csv, all with zero results.

**Comment by gabeworden** [comment]
Same issue with 2015 On Prem and version of toolbox 2015.7.31

**Comment by shytikov** [comment]
Could  you please check code in #203? It should fix the issue.

**Comment by lykebank** [comment]
the fix in #203 works.
