### ISSUE TITLE
Connecting to CRM Online with Azure MFA enabled

### ISSUE THREAD

**Issue by LoweredCircle** [MscrmTools/XrmToolBox#204]
We are testing out Azure Multi Factor authentication with O365 and found that XrmToolBox cannot connect to the web service while MFA is enabled.  

![mfa](https://cloud.githubusercontent.com/assets/13733228/9174905/cdd3e638-3f50-11e5-9a36-93356d11135e.png)

**Comment by MscrmTools** [comment]
Yes, it is true. XrmToolBox uses Microsoft.Xrm.Client.dll assembly to connect to CRM. This assembly does not support MFA.
I should use new assemblies from Microsoft to enable this. But I would need time and a working environment that uses MFA which is not the case. I'm not sure I will be able to add this feature soon.

**Comment by PeterSelchDahl** [comment]
It will require that the application is ADAL aware:
https://msdn.microsoft.com/en-us/library/azure/jj573266.aspx

**Comment by MscrmTools** [comment]
Latest CRM SDK tooling assemblies do all the job
Just let me time to test and implement it

**Comment by retsik** [comment]
Hope you find a solution soon.  My organization just enabled MFA and I'm now unable to connect via XRMToolbox.  :-(

**Comment by MscrmTools** [comment]
I have some news...

I can't talk about it explicitly since I'm under NDA with Microsoft on this topic but this won't be possible at least until launch of CRM 2016.

**Comment by PeterSelchDahl** [comment]
You Can use The MFA Whitelisting function, if your organisation uses The Cloud version of Microsoft MFA. This Will bypass MFA, when you Connect from a trusted IP. 


http://blogs.technet.com/b/ad/archive/2014/04/25/enhancing-azure-mfa-with-contextual-ip-address-whitelisting.aspx

You Will have to by either Azure AD premium license, EMS license or activate The Azure MFA function.

**Comment by MscrmTools** [comment]
Closed because linked to #337
