### ISSUE TITLE
error occurred while retrieving organizations

### ISSUE THREAD

**Issue by nigelwillits** [MscrmTools/XrmToolBox#206]
Please help. I am trying to create a new connection to crm4.dynamics.com in XRMToolbox. I tick 'Use CRM Online' and it automatically ticks 'Use SSL' and 'Use Office 365' and it automatically selects Custom Authentication. I select crm4.dynamics.com from the drop-down. This is the server for all our CRM instances. I enter the same login and password that I use to access our CRM instances. But when I click 'Get Orgs', it gives this error:
An error occurred while retrieving organizations: Metadata contains a reference that cannot be resolved:
'https://disco.crm4.dynamcis.com:80/XRMServices/2011/Discovery.svc?wsdl',
Inner Exception: The operation has timed out

**Comment by MscrmTools** [comment]
You are using an old version which had issue when connecting to SSL servers.
Please download latest version

**Comment by nigelwillits** [comment]
Thank you for the quick reply. When I try your latest version I get the attached error on launch. If I click Continue, nothing happens.
![xrmtoolboxerror](https://cloud.githubusercontent.com/assets/13780506/9252399/0852d0ae-41d0-11e5-94e7-aa1eb13c8d7b.png)

**Comment by nigelwillits** [comment]
I moved the toolbox to a different location on the computer and now it runs ok. Excellent tools. Thanks.
