### ISSUE TITLE
Old plugins hide new ones :)

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#207]
I haven't checked the code, so maybe this was done intentionally. Through this leads to really strange behavior.

`XTB` currently supports two locations of plugins:

* Current folder of `XrmToolBox.exe`
* `Plugins` sub-folder

First location has priority over second one. 

And if we have old (before July) plugin in first location and new (after July) plugin in second location, `XTB` will show no desired plugin in the list.

It's quite not obvious why after adding new dlls into `Plugins` sub-folder they not come up in the list.

I believe people who upgraded `XTB` to old folder have found this funny bug. Can we come up with proper fix for it?

**Comment by MscrmTools** [comment]
Can we just check for plugins in XrmToolBox root folder and delete them before loading "new" plugins?

**Comment by daryllabar** [comment]
I'd say prompt, then delete

**Comment by MscrmTools** [comment]
got it! thanks
