### ISSUE TITLE
Visual gap in plugins list when there is no scrollbar present

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#21]
When limited number of plugins are loaded and they are fit single main screen, plugin items are not spread all over available free space. Small gap of scrollbar size remains.

![Imgur](http://i.imgur.com/9HaPY7E.png)

Looks a bit strange and inaccurate. I believe it should be possible to update plugin elements with the code that will adjust their size depending on fact is scrollbar present or not.

**Comment by MscrmTools** [comment]
It was by design since I don't know how to resize items when the scrollbar is visible. Need some investigation to see if I can detect the scrollbar is displayed

**Comment by shytikov** [comment]
Needs to be reopened... 

Scenario, when old behavior is still valid:

* Load `XTB` with small number of plugins (one or two);
* Verify that there is no visual gap;
* Click on `Settings` button on toolbar;
* Change display type of plugins (if it was 'Small' change to 'Large' and vise versa);
* Size of plugins will be changed accordingly, and visual gap will return;
* Try to resize window;
* Gap will disappear.

**Comment by MscrmTools** [comment]
Ok, to fix : When changing size of plugins, apply correct display
