### ISSUE TITLE
System.TypeLoadException: Could not load type 'XrmToolBox.Attributes.BackgroundColorAttribute' from assembly 'XrmToolBox, Version=1.2015.7.31

### ISSUE THREAD

**Issue by AngeloGibertoni** [MscrmTools/XrmToolBox#210]
Hi,

I've just upgraded to the newest version and I get the error below.  Although a window opens, I cannot access it.  I am running Windows 8.1.  I do have the latest version of .net (4.5.2).

Any help gratefully received :)

System.TypeLoadException: Could not load type 'XrmToolBox.Attributes.BackgroundColorAttribute' from assembly 'XrmToolBox, Version=1.2015.7.31, Culture=neutral, PublicKeyToken=null'.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at Microsoft.Internal.AttributeServices.GetAttributes[T](ICustomAttributeProvider attributeProvider)
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TryGetExports(ExportProvider provider, ComposablePart part, ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part)
   at System.ComponentModel.Composition.Hosting.CompositionServices.TryInvoke(Action action)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at XrmToolBox.MainForm.<MainForm_Load>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/Downloads/XrmToolBox/XrmToolBox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34250 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Downloads/XrmToolBox/XrmToolBox.Extensibility.DLL
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 6.3.9600.16384
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Downloads/XrmToolBox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.0.3315.606
    Win32 Version: 1.0.3315.606
    CodeBase: file:///D:/Downloads/XrmToolBox/McTools.Xrm.Connection.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.0.3523
    CodeBase: file:///D:/Downloads/XrmToolBox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Cinteros.Xrm.DataUpdateTool
    Assembly Version: 1.2015.5.6
    Win32 Version: 1.2015.5.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.DATAUPDATETOOL.DLL
----------------------------------------
Cinteros.Xrm.FetchXmlBuilder
    Assembly Version: 1.2015.7.61
    Win32 Version: 1.2015.7.61
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.FETCHXMLBUILDER.DLL
----------------------------------------
Cinteros.Xrm.StepsManipulationTool
    Assembly Version: 1.2015.5.6
    Win32 Version: 1.2015.5.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.STEPSMANIPULATIONTOOL.DLL
----------------------------------------
Cinteros.Xrm.VersionVerifier
    Assembly Version: 1.2015.5.6
    Win32 Version: 1.2015.5.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.VERSIONVERIFIER.DLL
----------------------------------------
Cinteros.Xrm.XamlMigrationTool
    Assembly Version: 1.2015.5.6
    Win32 Version: 1.2015.5.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.XAMLMIGRATIONTOOL.DLL
----------------------------------------
Cinteros.Xrm.XmlEditorUtils
    Assembly Version: 1.2015.7.61
    Win32 Version: 1.2015.7.61
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.XMLEDITORUTILS.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormAttributeManager
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMATTRIBUTEMANAGER.DLL
----------------------------------------
MsCrmTools.FormLibrariesManager
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMLIBRARIESMANAGER.DLL
----------------------------------------
MsCrmTools.FormParameterManager
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMPARAMETERMANAGER.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MsCrmTools.PrivDiscover
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PRIVDISCOVER.DLL
----------------------------------------
MsCrmTools.RoleUpdater
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ROLEUPDATER.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserRolesManager
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERROLESMANAGER.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MsCrmTools.WebResourcesManager
    Assembly Version: 1.2015.7.31
    Win32 Version: 1.2015.7.31
    CodeBase: file:///D:/DOWNLOADS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------

**Comment by shytikov** [comment]
Which plugin you're trying to open?

Or everything happens even before you have opened anything?

Can you extract `XTB` to empty folder, to ensure, that it don't mess up with older plugins (it was breaking change in July release that might cause this).

**Comment by AngeloGibertoni** [comment]
It was right at start up, but yes, once I extract to an empty folder all words as it should, that's great thanks very much!

Great set of tools btw :)

**Comment by shytikov** [comment]
All credits goes to @MscrmTools :+1:

**Comment by rgallini** [comment]
I got this error with these plugins:
Bulk Workflow Tool
older Cinteros XML builder (the updated one works fine)

**Comment by shytikov** [comment]
There is a braking change in July release... All plugins needs to be updated otherwise these incompatibilities will pop up further...

Most plugin developers already updated their plugins, so solution is just get rid of the old and get new fall for every plugin.

**Comment by MscrmTools** [comment]
Please contact developers directly when some plugins are not updated.
