### ISSUE TITLE
See/remove existing privilege in Role Updater

### ISSUE THREAD

**Issue by lykebank** [MscrmTools/XrmToolBox#212]
The Role Updater plugin is pretty good for quickly adding privileges to a security role.  But if I could see what privileges the current role (after selecting it and clicking 'Next') already HAS, that would be very useful.  And if listing the privileges is possible, then a 'Remove Privilege' button would be handy, too.

I realize I can open up the role in CRM to perform privilege removal... but if the ToolBox is to make it easier/quicker, I think this functionality would fit well into the Role Updater plugin.

**Comment by MscrmTools** [comment]
I'm not sure how the UI should handle this feature...
Would it be sufficient if I add a checkbox "Display only privileges already in selected roles" that filters privileges list?

**Comment by lykebank** [comment]
Hm, the opposite I think.
On the 'Select Privileges and Levels that need to be updated' page, a filter to "Display only privilege-level combinations NOT already in selected role(s)" would ensure that I'm only adding new privilege-level combinations to the role(s).
If there would be a Remove Privileges Page...show privileges of the role, and select which ones to remove.

The web UI's bubble page may indeed be the best option.

**Comment by MscrmTools** [comment]
Back on the thread, @lykebank 

I analyze how the plugin is working and "Removing a privilege" is the same than "Adding a privilege" with no access (red circle). So I guess, implementing a checkbox that allows to display only exisiting privileges seems enough to me.

Any thoughts?

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.SecurityRelated #4](https://github.com/MscrmTools/MsCrmTools.SecurityRelated/issues/4) via [**ZenHub**](https://www.zenhub.com/)
