### ISSUE TITLE
No Form Location info exported from Metadata Document Generator

### ISSUE THREAD

**Issue by th0car** [MscrmTools/XrmToolBox#214]
Thanks for a great tool.
There is no data in the column for "Form location" after exporting to Excel even though "Attribute location in Forms" was checked in the XRM Toolbox GUI for Meta data Document Generator

Target Connection: CRM On Premise 2013
XRM Toolbox version: 1.2015.7.31
Meta data document Generator ver 1.2015.7.31

Regards,
Thomas

**Comment by MscrmTools** [comment]
I'm using the same version as you are and can't reproduce. 

Can you provide a screenshot of your configuration? Can you also save the configuration and display it here?

**Comment by th0car** [comment]
I'm "off net" until september 7. I'll get back with screenshot and config
then.
Den 28 aug 2015 2:11 em skrev "MscrmTools" <notifications@github.com>:

**Comment by jweresch** [comment]
I have the same issue with same version.  Connecting to CRM online.  When choosing option to only include attributes on the form, the results are blank.  When choosing all attributes and selecting form location checkbox, then that column on spreadsheet is blank.  Any Advice?

**Comment by th0car** [comment]
OK - Some more information on this:
Using an older version (XRM Toolbox v1.2015.3.10 with Metadata Document Generator 1.2015.2.21) on the same server and organization doesn't produce this problem. 

Screendump of config:
![docgen_gui_screenshot](https://cloud.githubusercontent.com/assets/1445963/9851634/02b0d900-5afa-11e5-872a-6bb9d4f8ee12.png)

Screendump of gui for the country entity (custom):
![crm_gui_country](https://cloud.githubusercontent.com/assets/1445963/9851651/1c182eca-5afa-11e5-9167-0b461f3414a3.png)

Screendump of generated Excel (for the country entity)
![docgen_excel](https://cloud.githubusercontent.com/assets/1445963/9851734/95ec2a1c-5afa-11e5-9898-350a45e57e40.png)

(I don't enclose any screendumps for the lead entity - just letting you know that we tested that one to get a non-custom entity tested as well - same result - no form info in Excel.)

Regards,
Thomas Carlsson, Cinteros AB (using my private GitHub account though...)

**Comment by th0car** [comment]
And here is the content om the msettings file when saved:
`<?xml version="1.0" encoding="utf-8"?>
<GenerationSettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <EntitiesToProceed>
    <EntityItem>
      <Name>cint_mms_mua_employers_association</Name>
      <Attributes />
      <Forms />
      <FormsDefinitions />
    </EntityItem>
    <EntityItem>
      <Name>lead</Name>
      <Attributes />
      <Forms />
      <FormsDefinitions />
    </EntityItem>
    <EntityItem>
      <Name>cint_mms_mua_country</Name>
      <Attributes />
      <Forms />
      <FormsDefinitions />
    </EntityItem>
  </EntitiesToProceed>
  <FilePath>C:\Users\thca\Desktop\form_test_1.xlsx</FilePath>
  <IncludeOnlyAttributesOnForms>false</IncludeOnlyAttributesOnForms>
  <DisplayNamesLangugageCode>1053</DisplayNamesLangugageCode>
  <AddAuditInformation>false</AddAuditInformation>
  <AddFieldSecureInformation>false</AddFieldSecureInformation>
  <AddRequiredLevelInformation>true</AddRequiredLevelInformation>
  <AddValidForAdvancedFind>false</AddValidForAdvancedFind>
  <AddFormLocation>true</AddFormLocation>
  <AddEntitiesSummary>false</AddEntitiesSummary>
  <AttributesSelection>AllAttributes</AttributesSelection>
  <OutputDocumentType>Excel</OutputDocumentType>
  <Prefixes />
</GenerationSettings>`

**Comment by th0car** [comment]
When comparing with an msettings-file from the older version I notice that the `<FormsDefinitions />`-part isn't present in the old one.

**Comment by MscrmTools** [comment]
Ok, got it!

Thank you for reporting it, I will try to fix this ASAP
