### ISSUE TITLE
Update description via Attribute Bulk Updater (or meta data document generator)

### ISSUE THREAD

**Issue by pieeetr** [MscrmTools/XrmToolBox#215]
It would be a great addition to the Attribute Bulk Updater if you could update field descriptions through the tool. It's important that it's fast, we don't want form reloads for every entered description. Instead, do all updates per entity, then hit publish changes before the form reloads.

A bold alternative to this (who remembers a coward?) is to make the Meta data document generator document available for re-import. Dangerous but truly awsome if it was possible to program it to be safe. If we're careful while deciding which fields that can be reimported we should be pretty safe right?

**Comment by MscrmTools** [comment]
Or, you can also use easy translator. This tool exports DisplayName and Description for each attributes and already has an import feature

**Comment by pieeetr** [comment]
Oh that's even better, excellent. I didn't know that little gem of a function was hidden in a translator-tool.

**Comment by shytikov** [comment]
It would be nice to integrate these two with `MessageBus`...

**Comment by MscrmTools** [comment]
@shytikov can you elaborate?

**Comment by shytikov** [comment]
@MscrmTools  sure! But after `AppDomains`, if I may...

**Comment by MscrmTools** [comment]
Ok, so I close this issue as a workaround exists with Easy Translator
