### ISSUE TITLE
Import NN relationships doesn't work

### ISSUE THREAD

**Issue by chungpfcat** [MscrmTools/XrmToolBox#216]
![xrmtools](https://cloud.githubusercontent.com/assets/13956723/9458709/7819dc04-4b24-11e5-8902-04681980d247.JPG)

I'm now trying to use import NN relationship tools upload opportunities and competitor nn relationship with below txt file :

new opportunity;A. Datum

However, nothing was shown and done after I click the button import NN relationship. 

Checking that connection is no problem and using administrator right.

What did I miss ?

Regards,
Catherine

**Comment by MscrmTools** [comment]
Last version uses coma as separator instead of semi colon

Could you try this?

**Comment by chungpfcat** [comment]
Hi Experts,

Tried. But still doesn’t work.

Regards,
Catherine

**Comment by chungpfcat** [comment]
Hi,

Even I exported the NN relationship but there is no file created in my local directory.

Regards,
Catherine

**Comment by MscrmTools** [comment]
Ok, I will work on this. 

Thank you for reporting

**Comment by chungpfcat** [comment]
Hi Experts,

When could the problem being fixed ? It’s a urgent needs for my project implementation. We’re planning to finish data migration for UAT walk-through by next week.

Regards,
Catherine

**Comment by Jgrassan** [comment]
I'm getting same error.
