### ISSUE TITLE
Error: Output file was not updated or not found! \Plugins\CrmSvcUtil Ref\CrmServiceContext.cs

### ISSUE THREAD

**Issue by michaelgluis** [MscrmTools/XrmToolBox#219]
How do i fix this? I am currently running the Early Bound Generator version 1.2015.8.11. I cannot create my model stub file without the file existing before running it. I have tried creating the cs file manually and elevating the security permission on the destination folder to everyone, but to no avail it keeps bombing out.

**Comment by MscrmTools** [comment]
This plugin is not developed by me, please report this error on https://xrmearlyboundgenerator.codeplex.com/
