### ISSUE TITLE
Several active connections to MS CRM servers

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#221]
Currently we have only one active connection to one MS CRM server. It basically means that all the plugins suppose to work with only one server at the moment. 

Sometimes there is a need to work with several servers simultaneously. In current implementation is a quite tricky. Yes it's possible to open two instance of plugin, change connection and update it only for one of the plugin instances... or use two instances of `XTB`... But it would be much nicer, if it would be possible out of the box by just using single instance of `XTB`.

What do you think?

**Comment by MscrmTools** [comment]
That is not true, If you open a plugin with connection A, then change connection without applying change to opened plugin, then open another plugin with connection B, both plugins can work with their respective connection.
But you are true, only the current connection is displayed to indicate it will be used for next opened plugin

**Comment by MscrmTools** [comment]
Any thoughts on this issue, @shytikov ?

**Comment by shytikov** [comment]
Working with two active connections is a bit painful in current implementation. 

For example. Let's open connection, open two instances of same plugin. Create some actions in one of plugins and change connection. 

`XTB` will ask to update connection on two instances of the plugin. It will show the list of plugin instances, where user can select which instance to update.

But all instances of the same plugin has same name. So user have 50/50 chance to guess instance of plugin he wants. And if he guess wrong, he might loose progress he did in one of the instances.

I'm not talking about fact, that on status bar we have text saying *Connected to.. * implying that this is the **only** active connection of `XTB` globally,  while it is its **last** active connection globally. And more information about active (local?) connections could be found on tab headers.

And, btw, it's impossible to disconnect from connection. No matter where information about it was found: in status bar or tab header.

I'm trying to say, that more explicit handing of connections would be nice. 

* Remove last active connection from status bar as misleading. Or change this text depending on plugin which is currently on top.
* Add explicit change of connection for current plugin. For example by left clicking on tab header. Where user can select from list of available connection for given instance of plugin and not guess, should connection be updated for given instance or not;
* Disconnect from connection. Just sanity check, that none of plugin instances are connected to the given server no more. And no modification will apply.

`XTB` started as single connection application, as far as I can tell, but currently evolved to multi connection application, but legacy code remains. And I think it leads to confusions, that could be easily avoided by performing small refactoring :+1:

**Comment by MscrmTools** [comment]
Got it!

Thank you for the precisions

**Comment by MscrmTools** [comment]
I guess I have part of this one fixed in next version to come + some updates done over the years
