### ISSUE TITLE
Tab header shows assembly info instead of plugin name

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#222]
After reconnecting CRM the text of the tab changes from the _plugin name_ to the _assembly name_.

Scenario:
1. Connect to CRM
2. Open a plugin (in this case the View Designer)
3. The header shows plugin name and active connection:
![image](https://cloud.githubusercontent.com/assets/2572253/9516610/0029f5da-4caa-11e5-8707-d30ab32c7b86.png)

4. Connect to another org
5. Select to update the plugin
6. The header now shows information from the assembly instead:
![image](https://cloud.githubusercontent.com/assets/2572253/9516638/4073e2c2-4caa-11e5-9858-fb7d52f16296.png)

In the screen shots I opened two instances of the plugin to demonstrate the difference if a plugin is updated (right plugin) or not (left plugin).

**Comment by shytikov** [comment]
:+1:
