### ISSUE TITLE
Reformat source using CodeMaid

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#225]
[CodeMaid](http://www.codemaid.net/) is open source extension to Visual Studio, that helps keep source code formatting consistent and sane.

It would be very nice to have `XTB` files to checked with `CodeMaid` this will unify styling in all source files and will reformat them using same standards.

Why it's matters?

Mostly because ease of reading and understanding what source code does. All methods, fields and properties will be grouped, sorted alphabetically and surrounded with regions. Unused using will be automatically removed. Everyones' code will look in the same logical and structural manner, so it will be easy to dig through it, understand what's going on and how to fix it.

**Comment by rappen** [comment]
Is it possible to specify this per project/solution in VS?
If not, it will also affect all customers and projects for all XTB developers, which is hardly acceptable...
Can we "trust" CodeMaid for the future?
Can CodeMaid co-esist with Resharper and other plugins, as they have overlapping functionality?

**Comment by shytikov** [comment]
`CodeMaid` do not run automatically, you need to explicitly ask for reformatting of file or group of files.

`CodeMaid` looks like more stripped version of `ReSharper`. Not as much powerful, but not as much big and slow. It's free, so anyone can get a copy. It integrates seamlessly to Visual Studio, so its presence is not noticeable. No changes in existing key shortcuts or colorful menus everywhere.

![CodeMaid](https://cloud.githubusercontent.com/assets/1185905/9545312/93b4f104-4d88-11e5-9a06-c153f112d7bc.png)

`CodeMaid` is quite easy to resources, it does not monitor your code all the time as `ReSharper` does, so you will not notice any difference in performance.

I'm not using `ReSharper` so I don't know how they co-exist. But with there is no mess with other plugins. 

`CodeMaid` is [Open Source](https://github.com/codecadwallader/codemaid)... So it gets more credit for that from me personally :+1:

**Comment by MscrmTools** [comment]
I'm using it now along with Resharper without any problem.
We sure can do this as it does not change anything in code behavior
