### ISSUE TITLE
User Settings Utility - Track email messages

### ISSUE THREAD

**Issue by kashshah** [MscrmTools/XrmToolBox#229]
Hello,

There seems to be an error in being able to set the 'Track email messages' setting.  The current options available on the tool allow you to change the value of the drop-down but you can not change the value of the related tick box, which is very important.  The tool should be changed by having these options, with the appropriate changes to the underlying code:

- No change
- Check incoming email ... All email messages
- Check incoming email ... Email messages in response to CRM email
- Check incoming email ... Email messages from CRM Leads, Contacts and Accounts
- Check incoming email ... Email messages from CRM records that are email enabled
- Don't check incoming emails

The first option makes no changes, the last option un-ticks the tick box and all the other options ticks the tick box with the appropriate setting for the drop-down.

Thanks for your fabulous tool.  

Kash Shah

**Comment by MscrmTools** [comment]
That makes sense! 
Thank you for the feedback

**Comment by MscrmTools** [comment]
After some checks, I don't understand you request. 
Here is my tracking options in CRM 2015

<img width="350" alt="emailtracking" src="https://cloud.githubusercontent.com/assets/10774317/9848777/98202bb4-5ae4-11e5-9a75-14d55167faa0.png">

So I cannot see the checkbox you are talking about...

**Comment by kashshah** [comment]
Hi

I have been investigating this and also been away on holiday, hence this late reply.

The screenshot that you have sent is the web browser version, I think.  This one below is the one shown in the Outlook Connector for the CRM system.  Once you see this it will make sense to you.

[cid:image002.png@01D0FB9E.1A3ACC90]

Many thanks and kind regards.

Kash Shah
Web Developer | BMA technology services
T: 020-7383-6368| M: 07739-859-658| E: kshah@bma.org.uk<mailto:kshah@bma.org.uk>

**Comment by kashshah** [comment]
Hi

I have been investigating this and also been away on holiday, hence this late reply.

The screenshot that you have sent is the web browser version, I think.  This attached image is the one shown in the Outlook Connector for the CRM system.  Once you see this it will make sense to you.

Many thanks and kind regards.
Kash Shah
Web Developer | BMA technology services
T: 020-7383-6368| M: 07739-859-658| E: kshah@bma.org.uk<mailto:kshah@bma.org.uk>



Many thanks and kind regards.

Kash Shah
Web Developer | BMA technology services
T: 020-7383-6368| M: 07739-859-658| E: kshah@bma.org.uk<mailto:kshah@bma.org.uk>


The BMA is the voice of doctors and medical students in the UK. 

We are an apolitical professional association and independent trade union, representing doctors and medical students from all branches of medicine across the UK and supporting them to deliver the highest standards of patient care.
_______________________________________________________________________ 

This email and any attachments are confidential and intended solely for the addressee. If you have received this email in error please notify postmaster@bma.org.uk.  Email sent or received by the BMA is monitored.

The British Medical Association.
Registered as a company limited by guarantee in England and Wales under registered number 00008848.
Registered office:  BMA House, Tavistock Square, London WC1H 9JP
                        http://bma.org.uk
_______________________________________________________________________

**Comment by MscrmTools** [comment]
Sorry but the screenshot you mentioned is not visible.
I did install a Outlook client and I cannot see the checkbox you are talking about.
More over, in the usersettings entity metadata, I cannot find any attribute that could store the information you are talking about
Can you attach the screenshot you were talking about?

**Comment by kashshah** [comment]
Hello

Here is the screen shot, both as an inline image and an attached file.  I hope you will be able to see it.

[cid:image001.png@01D0FF49.E64B89B0]

Many thanks and kind regards.

Kash Shah
Web Developer | BMA technology services
T: 020-7383-6368| M: 07739-859-658| E: kshah@bma.org.uk<mailto:kshah@bma.org.uk>

**Comment by MscrmTools** [comment]
Nop... replying by email does not seem to attach image correctly...

**Comment by kashshah** [comment]
![email settings in crm options](https://cloud.githubusercontent.com/assets/14111114/10275724/ab8c66d2-6b41-11e5-8b10-eeaa2d9e11be.jpg)

**Comment by MscrmTools** [comment]
Ok, after lot of tests, it seems this value is not stored in usersettings entity... And I did not find where it is stored... Maybe it is just a local value stored in local DB when using Outlook....
If anyone knows where this value is stored, I'm listening...

**Comment by MarkusHoelzl** [comment]
Hi MscrmTools!
I can not contribute on this particular thread but I am looking forward to enter a suggestion to the user settings.
I am looking forward to address all possible user settings through MscrmTools to maintain these seetings for 1200 users centrally. Just sendings e-mail doesn't work because user a ignoring them. Any thought's?
BR Markus

**Comment by MscrmTools** [comment]
not sure to understand your suggestion... What would you like to see in this tool?

**Comment by MarkusHoelzl** [comment]
Hi!
Thx for your quick reply!

I am looking for a functionality to set all user settings centrally ( by using xrmtools). To my knowledge it is currently only possible to set some user settings but not all of them.
E.g. we are looking to set every of these personal options in regard to the Email setup. This is very necessary for us the prevent users from errors and not working processes.
Is there a chance to get such features in the near future?

BR Markus


[cid:image002.png@01D104FD.C24DCA50]


Von: MscrmTools [mailto:notifications@github.com]
Gesendet: Montag, 12. Oktober 2015 14:38
An: MscrmTools/XrmToolBox <XrmToolBox@noreply.github.com>
Cc: Hölzl Markus mho09 <markus.hoelzl@gw-world.com>
Betreff: Re: [XrmToolBox] User Settings Utility - Track email messages (#229)


not sure to understand your suggestion... What would you like to see in this tool?

—
Reply to this email directly or view it on GitHub<https://github.com/MscrmTools/XrmToolBox/issues/229#issuecomment-147384252>.

P
Im Sinne unserer Umwelt: Bitte bedenken Sie, dass ein Ausdruck dieser Nachricht wertvolle Ressourcen verbraucht.
For the sake of our environment: Please be aware of the fact that printing this message consumes valuable resources.

**Comment by MscrmTools** [comment]
AFAIK, all email options stored in usersettings entity are editable in this tool. As per this thread, some options seem to be stored directly on the client computer when it comes to CRM client for Outlook. These ones are not editable through this tool (which makes sense as they are not stored on the server).
But you are right, not all options are included and some of them (especially Formatting options) are just too complex to implement (or I don't have time to gather all informations for each formatting option)

**Comment by MscrmTools** [comment]
any thoughts? If not, I will close this issue
