### ISSUE TITLE
XRMToolBox

### ISSUE THREAD

**Issue by rvroemen** [MscrmTools/XrmToolBox#230]
Hi,

I just downloaded XRMToolBox v1.2015.7.31.
Unfortunately, after extracting the files (I unblocked the ZIP file), I only get two menu options: A sample Tool and Chart Manager. The plugins are still available in the directory on the hard disk, but they do not appear in the menu.

Any suggestions?

By the way, it is a great tool which I use quite often!

Regards,

René

**Comment by MscrmTools** [comment]
Did you extract the zip in an existing Xrmtoolbox folder? If so, you would consider unzipping files on a new folder instead

**Comment by shytikov** [comment]
Related to #207?

**Comment by rvroemen** [comment]
Yes, this looks like the same problem.
I extracted the zip file to another folder and copied the mscrmtools2011.config file from the existing folder into the new folder.
This seems to work.

Van: Alexey Shytikov [mailto:notifications@github.com]
Verzonden: maandag 7 september 2015 23:32
Aan: MscrmTools/XrmToolBox <XrmToolBox@noreply.github.com>
CC: René Vroemen <r.vroemen@crmplusplus.nl>
Onderwerp: Re: [XrmToolBox] XRMToolBox (#230)


Related to #207<https://github.com/MscrmTools/XrmToolBox/issues/207>?
