### ISSUE TITLE
User Roles Manager not removing roles for disabled users in child BUs

### ISSUE THREAD

**Issue by liorabel** [MscrmTools/XrmToolBox#232]
Consider the following Business Unit structure:
- Organisation
  - Level 1 BU
    - Level 2 BU

I have users in Level 2 BU. Some are enabled and some are disabled.
When trying to remove a specific security role from an enabled user, everything works as expected. When trying the same for a disabled one, the role is not removed.
The same behaviour repeats itself when trying to add a role to enabled or disabled users.

When trying to remove **all** roles from a disabled user, the roles are removed as expected.

I did not test this with the root BU and do not know if that makes a difference.

**Comment by MscrmTools** [comment]
Just look quickly in source code but it seems there is no filter on users for these actions... But I do see an empty catch which means something can fail but the plugin says nothing.
I will try your scenario

**Comment by MscrmTools** [comment]
What do you mean by "removing all roles" ? There is no such feature in the tool.

I tested to add and remove roles of a disabled user and it is not authorized by the application which could explain why the too cannot do it.

That's why I'm asking what is "removing all roles"

**Comment by liorabel** [comment]
A 'Remove all roles' option is achieved by selecting no roles and using the option to remove all roles and add selected ones.

**Comment by MscrmTools** [comment]
I succeeded to reproduce once but now, I can't anymore!

Removing role works with both options (remove selected roles or remove existing roles and add selected roles) for a disabled user in a child BU.

Adding role to a disabled user fails but it does silently in the current version. This is a normal behavior since CRM application is not allowing it

**Comment by BGasnier** [comment]
Hi,
I found an issue in Organization which have more than 5000 records in the role table.
Maybe is it related to this ?
I have a solution from my side but as I am not familiar with GitHub I need to find the good process to show you my changes and eventually push into the main.

**Comment by MscrmTools** [comment]
If you found a new issue, please create a new issue on Github
Then I will give you an answer about the way to push your changes

**Comment by MscrmTools** [comment]
@BGasnier any news about a fix for the bug you found?

**Comment by BGasnier** [comment]
From my side I corrected: https://github.com/MscrmTools/XrmToolBox/issues/376 I don't know if it is related.

**Comment by MscrmTools** [comment]
oh, that's right... sorry, I forgot it...

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.SecurityRelated #5](https://github.com/MscrmTools/MsCrmTools.SecurityRelated/issues/5) via [**ZenHub**](https://www.zenhub.com/)
