### ISSUE TITLE
Export NN relationship doesn't work

### ISSUE THREAD

**Issue by dean0918** [MscrmTools/XrmToolBox#233]
Hi

when I exported the NN relationship, there was csv created but nothing in it and the file size is 0KB by XrmToolBox v 1.2015.7.31  and XrmToolBox.prerelease_v1.2015.0908.12.
 Is there anything did I miss？

Thanks and have a nice day!

Dean
Regards

**Comment by MscrmTools** [comment]
I just tested the latest prerelease and it works for me... Are you sure you selected the appropriate NN relationship?

**Comment by dean0918** [comment]
Thanks a lot for your answer, but I tried several times as the follow steps, it still doesn't work.

1. Create new N:N relationships
![a1](https://cloud.githubusercontent.com/assets/14227804/9894144/13c3d0da-5c53-11e5-951c-a69e952fa767.jpg)
2. Publish All Custmizations.
![a2](https://cloud.githubusercontent.com/assets/14227804/9894137/05f5a244-5c53-11e5-97b9-b2b175e51374.jpg)
3. Load MetaData and Export NN relationships
![a3](https://cloud.githubusercontent.com/assets/14227804/9894182/85535b12-5c53-11e5-88a1-7862ccd35294.jpg)
4. Export the file 
![a4](https://cloud.githubusercontent.com/assets/14227804/9894219/d92ce0a0-5c53-11e5-9b20-1528dbad47a8.jpg)
5. Check the file, and it is empty
![a5](https://cloud.githubusercontent.com/assets/14227804/9894237/077c64e4-5c54-11e5-82e0-8e4da5bfa441.jpg)

**Comment by MscrmTools** [comment]
I'm certainly asking a dumb question, but in your procedure you don't indicate creating records for this relationship, you just create the relationship. You are creating records for this relationship, right?

**Comment by dean0918** [comment]
Thanks a lot for you help and I made a very stupid mistake that I forgot to create records for the relationship as you mentioned. It is working very well.
