### ISSUE TITLE
Pass connection with msgbus calls

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#237]
Scenario:
1. Open plugin A with connection to org 1
2. Connect to org 2, but do not update plugin A
3. Click msgbus button in plugin A to open plugin B

Plugin B that was opened from plugin A will now be connected to the last connected org in XTB, which is org 2, while plugin A is still connected to org 1.

It would make much more sense to make sure called plugin is always using the same connection as the calling connection.

**Comment by MscrmTools** [comment]
As I did not develop the message bus part, I'm sure @shytikov is the man that could fix this

**Comment by MscrmTools** [comment]
Fixed in the upcoming release
