### ISSUE TITLE
Import/Export NN Relationships (CRM2011)

### ISSUE THREAD

**Issue by SBEND** [MscrmTools/XrmToolBox#239]
I am new according to import/export NN relationships in CRM2011. Well .. now I am trying to import NN relationships but the program does nothing. At least i think it doens't do anything. I just filled the aquiring fields and pushed the button "Import NN Relationships" but nothing happens. What do I do wrong? 
![troubleshooting - nn import relationships](https://cloud.githubusercontent.com/assets/14311949/9903770/57d1caea-5c79-11e5-848f-45ab547510b8.png)
![Uploading Troubleshooting - NN import relationships.png…]()

**Comment by MscrmTools** [comment]
There is on known error in this plugin. 
Can you download latest [prerelease bits](https://github.com/MscrmTools/XrmToolBox/releases/tag/XrmToolBox.prerelease_v1.2015.0916.25) and take only this plugin from there to overwrite the one you are using?
It should work better

**Comment by SBEND** [comment]
Thank you for the quick respons! 

I just download the newest release and yes indeed, now the button works and I see that the tool is working. But now I get the error that the record was not found. But when I look up CRm -> i can see the person. So now something still is going wrong. Do you know what I am doing wrong? 
![troubleshooting - nn import relationships 5](https://cloud.githubusercontent.com/assets/14311949/9905123/4f715988-5c83-11e5-9c89-02b6a766b32d.PNG)
![Uploading Troubleshooting - NN import relationships(6).PNG…]()
![troubleshooting - nn import relationships 2](https://cloud.githubusercontent.com/assets/14311949/9905125/4f73d834-5c83-11e5-94fa-56cd22146763.png)
![Uploading Troubleshooting - NN import relationships(3).png…]()
![troubleshooting - nn import relationships 4](https://cloud.githubusercontent.com/assets/14311949/9905124/4f7192cc-5c83-11e5-9f02-7ef774d91084.PNG)

**Comment by MscrmTools** [comment]
can you send also the line that corresponds to these screenshots?

**Comment by SBEND** [comment]
Line 2 = corresponding with the shots I just send!

**Comment by MscrmTools** [comment]
I don't see the data from the import file

**Comment by SBEND** [comment]
This is the importdata! 

![troubleshooting - nn import relationships 3](https://cloud.githubusercontent.com/assets/14311949/9907546/f927901c-5c8f-11e5-8e35-8f29ac904a77.png)

**Comment by MscrmTools** [comment]
I'm sorry but could you open the file with notepad and send me a screenshot of line 2 data?

**Comment by SBEND** [comment]
Yeah! Sure! 


![nn import troubleshooting](https://cloud.githubusercontent.com/assets/14311949/9907719/b9c5b22c-5c90-11e5-95ba-697ae0ae5954.JPG)

Like this?

**Comment by MscrmTools** [comment]
Yes!
So, as it seems semicolon was disturbing some people, the new separator is comma. And there shouldn't be header line

Can you fix the file and try again

**Comment by SBEND** [comment]
Yes I am going to try! I will let u know!

**Comment by SBEND** [comment]
Yes it's working!! Thank you very much!!

**Comment by SBEND** [comment]
Have a nice day!!
