### ISSUE TITLE
XrmToolBox fails to connect to CRM Online if user password contains double quote mark (")

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#240]
Found issue in `XTB`. If user password contains double quote mark (`"`) the [GetDiscoveryCrmConnectionString()](https://github.com/MscrmTools/XrmToolBox/blob/master/Connection%20Projects/McTools.Xrm.Connection/ConnectionDetail.cs#L219) method produces discovery string that could not be parsed by [CrmConnection.Parse()](https://github.com/MscrmTools/XrmToolBox/blob/master/Connection%20Projects/McTools.Xrm.Connection/ConnectionDetail.cs#L162).

Probably quotes needs to be escaped, through I'm not sure how to do this correctly, and I'm also not sure about symbols that could also be misinterpreted.

But result is dramatic. User cannot connect to CRM online via `XTB`  unless password is changed.

**Comment by MscrmTools** [comment]
The same apply for semicolon character as it is a separator in the connectionstring. But I handled this one.
I guess it cannot be escaped and I need to add this character in the banned character for a password

**Comment by MscrmTools** [comment]
Using `DbConnectionStringBuilder` fix all problems

**Comment by shytikov** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by shytikov** [comment]
:+1: :+1: :+1: :+1: :+1:
