### ISSUE TITLE
View Transfer Tool: Cannot connect to target organization

### ISSUE THREAD

**Issue by bryce2071** [MscrmTools/XrmToolBox#244]
Hi, 
i hope i am not to blind to see .. 
but, how can i select a target environment..

if i start the view transfer tool in menu, the source gets set to the acutally set connection.
in the view transfer tool i can see at the top right the "Select"-Button .. but if i there select a connection, this is set as new source, not as target.
???
THX, Greetings PeB

**Comment by MscrmTools** [comment]
You are right... This is a bug...
Strange thing is : This tool has not been updated in this release. I need to find what happened

**Comment by MscrmTools** [comment]
Ok found it!
The problem does not come with the tool but with a change in XrmToolBox core

**Comment by bryce2071** [comment]
ok, thx.
Released in next version?

**Comment by MscrmTools** [comment]
Yes but next release will be today since it is really a blocking issue for this tool and solution transfer tool too
