### ISSUE TITLE
Metadoc Generator: Include relationship name of a lookup?

### ISSUE THREAD

**Issue by bryce2071** [MscrmTools/XrmToolBox#246]
Hi ... 

is it possible to include the relationship name of a lookup in the exported metadoc 
maybe under the "Additional data" col.

thx, greets peB

**Comment by MscrmTools** [comment]
That would be possible but this is not an information contained in a Lookup attribute metadata, so it requires to retrieve more metadata and have a performance impact.

But, this is possible

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.MetadataDocumentGenerator #4](https://github.com/MscrmTools/MsCrmTools.MetadataDocumentGenerator/issues/4) via [**ZenHub**](https://www.zenhub.com/)
