### ISSUE TITLE
Script Finder do not show OnLoad scripts

### ISSUE THREAD

**Issue by fvakiliev** [MscrmTools/XrmToolBox#247]
I noticed that the _Script Finder Plug-In_ (in some cases and for some forms) does not show the scripts for the event _OnLoad_. In addition, these scripts are clearly present.

XrmToolBox: 1.2015.9.22
CRM 2015 (RU 0.1) OnPremise ADFS/IFD

PS: CRM DB had migrated from the 2011 version, but this particular form was created as a new (not inherited).
PPS: To @MscrmTools - This issue was moved from the [CodePlex discussion](https://xrmtoolbox.codeplex.com/discussions/645371)

Regards!
@fvakiliev

**Comment by MscrmTools** [comment]
Would you be able to provide the XML part of the form definition that register events?

**Comment by daryllabar** [comment]
The Form Manager now handles OnLoad Form Events.  Does your OnLoad event show up there?

**Comment by fvakiliev** [comment]
Part of customizations.xml with form definition added:
[opportunity form definition-customizations.xml](https://drive.google.com/file/d/0B0g3qigl7UpqdW1HUXZSS205SGM/view?usp=sharing)

**Comment by fvakiliev** [comment]
To @daryllabar:
Yes, the Form __Libraries Manager__ sees OnLoad scripts very good!
But, unfortunately, it's not good for me.

**Comment by daryllabar** [comment]
Ok.  That at least shows that the XML is formatted as expected.

**Comment by MscrmTools** [comment]
From my point of view, the tool works as expected but the Xml does not

Here is the problematic line:

     <event name="onload" application="true" active="true">

Application=true tells this is internal onload event, and not a custom one. This is why the tool does not display it.
But I can also see a node "InternalHandlers" which did not exist before some version. 
So, now that I know this node, I can fix the tool

**Comment by fvakiliev** [comment]
Hi @MscrmTools

Thanks for the answer. I'll look forward to the new version of the plugin.

@fvakiliev

**Comment by fvakiliev** [comment]
How to I get a new __MsCrmTools.ScriptsFinder.dll__ ?

**Comment by MscrmTools** [comment]
Download the latest prerelease in Release page of this repository

**Comment by fvakiliev** [comment]
Yes! Work fine. Thanks.
