### ISSUE TITLE
AndyPopkin.CRMBulkWorkflowTool not compatible with 2015 toolbox ?

### ISSUE THREAD

**Issue by ameed** [MscrmTools/XrmToolBox#248]
Hi,

I had used CRM Bulk Workflow execution tool before, when it was an independent tool. I found the plugin of the same tool for XrmToolBox, however, when i try to run XrmToolBox with plugin's dll copied and unblocked in the plugins folder, i get following error on startup. I have downloaded plugin's dll from here: http://zero2ten.com/crm-2013-bulk-workflow-tool-for-xrmtoolbox/
I am not sure if that is a problem with plugin or something to do with XrmToolBox, but i can see the exception occurs during render part of application. I have also sent the same issue to Andy (zero2ten). I hope you can take a look, and suggest me if there is a way to still work with plugin with toolbox in 2015. I tried added plugin dll in a Visual Studio project, and then added XrmToolBox.exe as reference. Visual studio throws compilation error requiring a specific version of XrmToolBox dll

"The type 'XrmToolBox.IMsCrmToolsPluginUserControl' is defined in an assembly that is not referenced. You must add a reference to assembly 'XrmToolBox, Version=1.2014.7.16, Culture=neutral, PublicKeyToken=null'.	C:\Work\Sand\CRMBulkWorkflowExecutor\CRMBulkWorkflowExecutor\Program.cs	12	13	CRMBulkWorkflowExecutor"

**Comment by MscrmTools** [comment]
If you look in the wiki for available tools for XrmToolBox, you will notice that Andy did not update his tool to be compatible with the latest breaking changes in XrmToolBox (which occur in July).
Please contact Andy to get an updated version or use a version of XrmToolBox older than July 2015
