### ISSUE TITLE
Connection error to O365  CRM with AD sync

### ISSUE THREAD

**Issue by brucesithole** [MscrmTools/XrmToolBox#249]
Our crm tenant is on office 365 and we have our company AD doing a sync with azure & the portal allowing users to currently use their windows/ad credentials to access crm. Therefore our usernames are in the format of:
me@mycompany.com
Pwd being the AD password.

I cant authenticate to the online environment(APAC).
Any ideas what combinations/permutations are needed to authenticate with this setup?

**Comment by MscrmTools** [comment]
I never authenticate with this scenario so I'm not sure how to connect...
I would need an environment to do some test to answer you

**Comment by rappen** [comment]
I think that is exactly how we run our CRM too.
This is my personal config:
![image](https://cloud.githubusercontent.com/assets/2572253/10072742/359d88e6-62c4-11e5-8442-3f88c4fb492a.png)

**Comment by brucesithole** [comment]
Awesome tool by the way. Im sure I know what the issue is, I was having the same issue with the plugin registration tool,USD Deployment tool etc and the fix I put in which worked with both scenarios was to add 

<system.net>
<defaultProxy useDefaultCredentials=”true”>
</defaultProxy>
</system.net>

in the exe.config files...then when I chose the office365 authentication option,it worked. Not sure how I could add this setting to your tool unless I rebuild with the .config file. Just FYI :)

**Comment by brucesithole** [comment]
Ahhh I might try and see if I can get it to work with the configuration set by @rappen

**Comment by MscrmTools** [comment]
@brucesithole Are these settings specific to your organization? if not, can you share them? if yes, can you write a page on the wiki (or update the one about connection) that explains how to update confg file to make it work?

**Comment by brucesithole** [comment]
These are the settings Im attempting to use:
![image](https://cloud.githubusercontent.com/assets/3655839/10126065/e28c9064-65cc-11e5-93e0-f9d15f6e43b0.png)


And this is the resulting error message:
![image](https://cloud.githubusercontent.com/assets/3655839/10126070/fc7a0b8c-65cc-11e5-8d35-dbb658cde39f.png)


Like I said,other articles on the net discussed how you need to add the settings in my prev comment to get the connection to work for other tools(e.g. plugin registration). In the tools config I have tried setting the various proxy settings but to no avail. If anyone has any suggestions,let me know,otherwise I will post an update once(if!) I get it working.

**Comment by devbot920** [comment]
Anyone know what I might need to make this work with Windows 10.  I am getting a similar error, but when opening the source code, I see the recommended setting is already in the app.config when compiled.  Below is the error I am getting when attempting to connect.  Any help would be greatly appreciated. 

![image](https://cloud.githubusercontent.com/assets/6684148/10613057/392dadd8-7719-11e5-9a81-3a5cc05ed1d7.png)

**Comment by MscrmTools** [comment]
Authentication failure seems obvious to me... Are you sure about your credentials? what is the type of ddeployment? Online? OnPremise?

**Comment by brucesithole** [comment]
Just to let you know that I was able to connect to the environment. A bit of trial and error (and looking at the code) meant I had to put the proxy settings on the tool which then allowed me to retrieve the organizations. (settings -> Proxy->Use custom proxy). I set the custom authentication to 'No' after putting in the proxy settings.
