### ISSUE TITLE
Improve parsing of comments in SiteMap editor

### ISSUE THREAD

**Issue by slahn** [MscrmTools/XrmToolBox#252]
The current parsing of comments in the sitemap editor is a bit fragile.
A comment like
```xml
<!-- temporarily disable this group <Group ...></Group>-->
```
or 
```xml
<!-- <Group></Group><Group></Group> -->
```
will cause the sitemap load to fail.

I've tried to address this in https://github.com/slahn/XrmToolBox/commit/e25c9081779ab08feeebe4f9b03e980be213a866, by supporting multiple elements in one comment, and by only handling valid elements in the comment, not any text nodes that are there after parsing.
Do you want a pull request?

As an alternative, I can come up with a more helpful error when the comment parsing fails.

**Comment by MscrmTools** [comment]
Yes, I'm fine with a pull request.
I can see in your changes that you handle the treeview build. I don't have time to check it now but are you sure it does not require change when parsing back treeview to XML ?

**Comment by slahn** [comment]
I only looked at the preview of the XML, so I'll double check, but it looked fine. The loading is "destructive" in that text comments will be lost, and multiple elements in one comment will end up in multiple comment elements in the output.

**Comment by MscrmTools** [comment]
But does multiple comment elements are parsed fine when during next loading? after having save the sitemap to the server?

**Comment by slahn** [comment]
Yes,
```xml
<!-- <Group>...</Group><Group>...</Group> -->
```
is read in as two nodes into the tree, and is exported as
```xml
<!-- <Group>...</Group>-->
<!-- <Group>...</Group>-->
```
