### ISSUE TITLE
Code folding in web resources manager

### ISSUE THREAD

**Issue by Quodnon** [MscrmTools/XrmToolBox#253]
Feature request.
Is it possible to add code folding in web resource manager plugin? 
That would allow to expand\collapse large bunches of code.
* .html pages folding on  open/close tags 
* .js libraries folding on curly brackets "{}"

**Comment by shytikov** [comment]
I've heard it was one of suggestions to replace editor with the new improved version. I'm pretty sure it supports folding as well.

**Comment by MscrmTools** [comment]
It supports folding. I just need time to test embedding wpf in winforms in this scenario

**Comment by daryllabar** [comment]
Weird thought, but would it be possible to embed VS Code instead?

**Comment by shytikov** [comment]
I LOVE Visual Studio Code, but it's essentially Google Chrome in text editor wrapper... So probably it's just impossible...

**Comment by daryllabar** [comment]
impossible-ish?  http://www.codeproject.com/Articles/9123/Hosting-EXE-Applications-in-a-WinForm-project

I'd at least venture to say it's outside the scope of the XTB.  I mean, it would be nice if it solved world hunger, but that's not really it's purpose.

**Comment by MscrmTools** [comment]
First tests are promising

![image](https://cloud.githubusercontent.com/assets/10774317/10141366/66ee3fda-660c-11e5-9d20-70b44309c1e8.png)

**Comment by daryllabar** [comment]
First tests of what?

**Comment by MscrmTools** [comment]
Of using avalonedit wpf editor in web resource manager

**Comment by Quodnon** [comment]
Awesome. Thanks a lot. Looking forward for release.

**Comment by MscrmTools** [comment]
I'm still fighting with XML/HTML folding. It is supposed to be included in standard, but I can't get it work so far

**Comment by MscrmTools** [comment]
Ok guys! Code folding is ready, using ICSharpCode.AvalonEdit

I just have a glitch with high DPI screen with increased font size. First time AvalonEdit is loaded the tool change its display to 100% instead of percentage defined in Screen properties (in my case 125%). When you navigate to another web resource and any other after that, the tool resize to its normal size. It does not occur when the font size is set to default (100%)
