### ISSUE TITLE
Web Resouces Manager - Selecting Folder and publishing creates Invalid Cast Exception

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#254]
I've loaded some files from the disk, that are setup on my disk in some subfolders and I'm getting an error:

![image](https://cloud.githubusercontent.com/assets/9728423/10137400/4b8ef4cc-65c7-11e5-9fe7-ee0193633ecd.png)

If I unselect the folder but select all of the items in the folder, I don't have the issue...

**Comment by daryllabar** [comment]
I can't debug the dll because it's being IlMerged, but I can say that there somewhere the full path to the scripts folder is being stored in the tag of the scripts tree node.

**Comment by MscrmTools** [comment]
Thank you @daryllabar, I'll have a look...

**Comment by MscrmTools** [comment]
Found the problem... easy to fix
