### ISSUE TITLE
Easy Translator Feedback

### ISSUE THREAD

**Issue by RodolfoLuisPereira** [MscrmTools/XrmToolBox#255]
Hi
Thanks for including dashboards in easy translator.
To Be perfect covering all needs, would be nice that in a future version, also includes:
- Entity Charts
- Worflows "Stop Workflows step-cancel" since we can place message to user there
- Business rules - On error messages to user

**Comment by MscrmTools** [comment]
Thank you for the feedback
Nevertheless, I'm using only SDK capability to translate crm items and I'm quite sure some if the items requested cannot be accessed (or updated) through SDK.
For example, I wanted to allow translation of CommandBar items but SDK does not allow to update them, you can just read them.
So, I will investigate about the possibility to translate these items only through SDK and if I find a way, it will be implemented

**Comment by RodolfoLuisPereira** [comment]
Makes sense

Cheers

Enviado do meu iPhone

No dia 30/09/2015, às 07:52, MscrmTools <notifications@github.com<mailto:notifications@github.com>> escreveu:


Thank you for the feedback
Nevertheless, I'm using only SDK capability to translate crm items and I'm quite sure some if the items requested cannot be accessed (or updated) through SDK.
For example, I wanted to allow translation of CommandBar items but SDK does not allow to update them, you can just read them.
So, I will investigate about the possibility to translate these items only through SDK and if I find a way, it will be implemented

**Comment by MscrmTools** [comment]
Hi, I was able to investigate, so here are the results:
Charts => Definitively doable! 
Workflow error message => not translatable
Business Rules error message => doable! will require some time but doable

**Comment by MscrmTools** [comment]
After more investigation, only charts can be translated through SDK, business rules error message cannot
