### ISSUE TITLE
Bulk Workflow Tool Is not appearing in list of applications.

### ISSUE THREAD

**Issue by mtnmuncher** [MscrmTools/XrmToolBox#257]
I copy the DLL (AndyPopkin.CRMBulkWorkflowTool (1).dll) to the plugin folder. I receive the message that a new application has been added. I choose, yes, to add it. However, it is not appearing the list of applications.

I am using build 2015.9.22 of XrmToolBox.

**Comment by MscrmTools** [comment]
As mentionned in the [wiki](https://github.com/MscrmTools/XrmToolBox/wiki/Available-plugins-for-XrmToolBox), this tool is not yet compatible with XrmToolBox older than June 2015 release. Please contact the developer to get an update on when this tool will be available
