### ISSUE TITLE
CrmOnline 2015 Connection Error - "An unsecured or inccorrectly secured fault was received.." 

### ISSUE THREAD

**Issue by denizintepe** [MscrmTools/XrmToolBox#264]
When I click to GetOrgs for my CrmOnline account, I experience the problem below:
![image](https://cloud.githubusercontent.com/assets/5639059/10575181/876817b0-7663-11e5-9030-7bc00af1c7e1.png)

ServerInformation: CrmOnline and Office365 is selected
ServerName: crm4 domain is selected
Authentication: Custom authentication is selected with login info like below: accountName@companyname.onmicrosoft.com 

I am sure that the CRM site is up an running.
I am going to install latest .Net packages and try to debug the app, but if I can get an easy solution it would be great : ) Thanks!

**Comment by MscrmTools** [comment]
Do you have authentication federation with local Active Directory?

**Comment by denizintepe** [comment]
Actually it is a 30 day trial version of Crm Online, I have created an Office 365 account and using that account to connect to CRM, so I am not sure how they manage my connection in the background. I didn't configured anything
I have also debbuged the app and I ve seen that the RetrieveOrganization service is throwing this error.
I hope my answer helps.

**Comment by MscrmTools** [comment]
No it does not :(
I don't have any problem to access a trial Org right now

**Comment by denizintepe** [comment]
My connection dialog is like below, do you see any difference from your setup?
![image](https://cloud.githubusercontent.com/assets/5639059/10577087/ced50394-7670-11e5-8b24-ca88b4645670.png)
Is there anything need to be configured on CRM end to give access to this app?

**Comment by MscrmTools** [comment]
Everything seems ok in your config...
Can you just confirm your org is in EMEA tenants?
If yes, would it be possible that your network alters the request sent to CRM Online?

**Comment by denizintepe** [comment]
I have run the app in a remote server in a different network and it worked without any problem.
I guess, somehow my network changes the request as you said.

Thanks for pointing out!

**Comment by MscrmTools** [comment]
You're welcome
