### ISSUE TITLE
Multiple config files / Customer config files 

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#265]
What do you think about having multiple connection config files?

For example file per customer, several files stored in different locations, under source control, probably, and one master file in default location (with some common connections inside)?

My motivation is following: some customers has their own set of servers, sometimes quite a lot of them. If number of customers is significant, or with the time, connection file growing bigger and bigger. It's impossible to share this file with one team, since it contains information that should be visible for another one.

What if we could split config file and move connection details between smaller files? Some of these files could be located in TFS or GIT and shared with the team, for easier `XTB` setup.

Files could be added and deleted from `XTB` in any time. Distributed by mail and so on. Click on the file might start `XTB` and open connection dialog, for example.

@MscrmTools what do you think about this idea?

**Comment by rappen** [comment]
A lot easier now that #262 is implemented too :)

**Comment by MscrmTools** [comment]
@shytikov I think this could be great!
But I don't have much time these days to analyze what has to be changed

**Comment by shytikov** [comment]
Cool! :+1: 

@MscrmTools will you agree if `mscrmtools2011.config` file will be split on two: 
* Proxy-related and list specific settings will go to `XrmToolBox.Settings.xml`;
* And list of `ConnectionDetail` will in in `Default.Connections.xml`;

Link to `Default.Connections.xml` will be in `XrmToolBox.Settings.xml` together with any other links to connections file.

Small dropdown list will be added to `Select Connection` window, so user can switch context. It would be possible to add new connection file there, or delete existing.

**Comment by MscrmTools** [comment]
That seems promising :)
Yes I love that approach!

**Comment by MscrmTools** [comment]
What about this?

![image](https://cloud.githubusercontent.com/assets/10774317/13179580/d2d6c27e-d724-11e5-86eb-0ec03be03db4.png)


and when changing file

![image](https://cloud.githubusercontent.com/assets/10774317/13179554/b7d66632-d724-11e5-80f5-ee4d7d105504.png)

And the resulting files on disk
![image](https://cloud.githubusercontent.com/assets/10774317/13179619/f7e2c9fa-d724-11e5-9975-8c78f1991062.png)

**Comment by daryllabar** [comment]
It may be beneficial to be able to specify the location of the config file (so you could have it sitting in a Source Controlled location)  Is that allowed, or do they all have to exist in the root?

**Comment by MscrmTools** [comment]
When creating or adding a file, you can specify the location of the file

**Comment by daryllabar** [comment]
Awesome!

**Comment by rappen** [comment]
Definitely a winner! :+1:

**Comment by MscrmTools** [comment]
See [Issue #2](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/2)
