### ISSUE TITLE
WebResourceManager : Automatic save to file

### ISSUE THREAD

**Issue by craigseymour** [MscrmTools/XrmToolBox#266]
Enhancement Request: I've tried various tools for managing CRM Web Resources, JavaScript in particular, and always come back to XRMToolBox.  The missing piece for me is a way to integrate with source control.  At the simplest level, automatically saving the files when published to a specified location on disc; beyond that the ability to put a command-line handler on save and publish to allow commits.

**Comment by MscrmTools** [comment]
What may be possible would be to enable users to run command line on the following event:
- before saving file
- after saving file
- before updating and publishing
- after updating and publishing

With the help of at least one tag ({%FilePath%} or something like that), you could achieve what you want.

I should also add an option to automatically Save to disk when performing a save in the tool

Any thought?

**Comment by craigseymour** [comment]
The real issue is having to remember to manually save the files to disc in order to push them into source control.  So automatic save would be a great start - you still have to remember to go to the source control tool afterwards, but at the very least there is that one record of the changed file.  

The ability to specify a command line on the after events would be good, because then it's all automatic.  You can then work entirely in XRMToolbox without having to go anywhere else.  I guess there is the issue of not having commit messages - I'm using Git which allows me to interact with the command prompt at the time of the commit, so I'd be alright - other systems might need the option to prompt for a 'message'?

I'm struggling to think of a use for the before events, but that's almost certainly my lack of imagination :-)

**Comment by MscrmTools** [comment]
Before event, especially for save, could help to check out files (I know this can be useful for TFS)
