### ISSUE TITLE
Expose OData endpoint in ConnectionDetail

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#267]
It would be great if the Organization Data Service endpoint was exposed in the ``ConnectionDetail`` class.
![image](https://cloud.githubusercontent.com/assets/2572253/10663407/7b7af512-78bb-11e5-97c3-6b84503aae1a.png)

This of course relates to https://github.com/Cinteros/FetchXMLBuilder/issues/4

**Comment by MscrmTools** [comment]
Definitively doable!
