### ISSUE TITLE
Script Finder - Add script parameters to output

### ISSUE THREAD

**Issue by liorabel** [MscrmTools/XrmToolBox#269]
I sometimes use the Script Finder module to map an existing form's events and transfer all the required ones to a new form. One thing that's missing from the output (both built-in and CSV) are the parameters passed to the function.
Because this is missing, I need to manually go to each field with an event to verify the passed parameters.

**Comment by daryllabar** [comment]
The Form Script Manager has this functionality.  Just right click on the form on the right hand side

**Comment by liorabel** [comment]
@daryllabar, the Form Libraries Manager (could not find one with the name you gave) has this functionality in a partial way. There are two issues with it:
1. This is not easy to use when migrating logic between forms as it requires additional clicks and isn't all in a single view.
2. This only supports form events and not field events.

**Comment by daryllabar** [comment]
You're right @liorabel ,  it doesn't provide a simple way to be able to apply the same event among multiple forms.  That sort of use case feels like the exception, not the rule.  It also doesn't allow for field events.  IMHO it is much easier to wire up field events using js in the form onLoad, rather than doing it through the ui.  Can you do that instead?

**Comment by liorabel** [comment]
@daryllabar, my goal here was to migrate the form logic without having to rewrite any code.
This has also already been flagged by @MscrmTools as an Enhancement so they seem to agree this could be useful.

I have already done what I needed to do on these forms so thanks. :)

**Comment by MscrmTools** [comment]
I agree! Will work on it

@Daryl, wiring everything in onload event is easier from a developer stand point but absolutely not from a customer standpoint who would like to understand what is wired

**Comment by daryllabar** [comment]
Sorry @Daryl, @MscrmTools  meant @daryllabar

@MscrmTools, we may want to put this logic in a shared place, so both plugins can access it.

**Comment by MscrmTools** [comment]
I understand the interest to share some code parts but what if we need to change things later only for one plugin ?
I'm currently writing this enhancement, so let see how it works and we can think about having shared assembly maybe with common methods

**Comment by MscrmTools** [comment]
Code is ready. I'm closing the issue as it will be fixed in next release.
