### ISSUE TITLE
not able to import translation

### ISSUE THREAD

**Issue by saralagerquist** [MscrmTools/XrmToolBox#271]
I exported translations on the Account entity. I changed two words in an option set and when i tried to import the translation I got this error message:

![issue-import translation](https://cloud.githubusercontent.com/assets/15727681/11031427/bbda9f5a-86d4-11e5-9cad-4a7bbbfcbc81.JPG)

I've tried several times, I've tried not touching the option set just editing something that was not translated before but I get the same message.

What can i do?

**Comment by MscrmTools** [comment]
Hi, can you give me information about the optionset you tried to translate? custom or system attribute? entity? did you change the displayname or the description?

**Comment by saralagerquist** [comment]
Hi,

I tried to change a picklist on Account, the labels of it, it is very weirdly translated as it is today.

{4e33af09-ba43-4365-a747-c7e4f9992172}

account

customertypecode

Picklist

1

Label

Kund

Competitor

{4e33af09-ba43-4365-a747-c7e4f9992172}

account

customertypecode

Picklist

1

Description

{4e33af09-ba43-4365-a747-c7e4f9992172}

account

customertypecode

Picklist

4

Label

Potentiell kund

Investor

{4e33af09-ba43-4365-a747-c7e4f9992172}

account

customertypecode

Picklist

4

Description

{4e33af09-ba43-4365-a747-c7e4f9992172}

account

customertypecode

Picklist

9

Label

Återförsäljare

Reseller



But my last attept i did not touch the option set if that would be the issue but it’s not. I get the error message even though I don’t change the option set.


/Sara



Sara Lagerquist
Verksamhetskonsult

Cinteros AB
Drottninggatan 68
111 21 Stockholm
+46 72 856 04 35
sara.lagerquist@cinteros.se<mailto:sara.lagerquist@cinteros.se>
www.cinteros.se<http://www.cinteros.se/>


[Cinteros]

Från: MscrmTools [mailto:notifications@github.com]
Skickat: den 9 november 2015 11:43
Till: MscrmTools/XrmToolBox <XrmToolBox@noreply.github.com>
Kopia: Sara Lagerquist <sara.lagerquist@cinteros.se>
Ämne: Re: [XrmToolBox] not able to import translation (#271)


Hi, can you give me information about the optionset you tried to translate? custom or system attribute? entity? did you change the displayname or the description?

**Comment by saralagerquist** [comment]
any progress in finding out the issue? :)

**Comment by MscrmTools** [comment]
Can you precise the version of Easy Translator, XrmToolBox and CRM organization you are connecting to?

**Comment by saralagerquist** [comment]
Easy Translator version: 1.2015.916.25
XrmToolBox version: 1.2015.916.25
Organization version: 7.0.1.129

**Comment by MscrmTools** [comment]
Ok, the problem comes from attributes derived from calculated fields... I need to find a way to identify these attributes so that they won't be exported
