### ISSUE TITLE
Monospaced fonts in WebResource Manager

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#272]
Hi,

Is it possible to switch WebResource Manager to use monospaced fonts, as it was before? I know new features like folding are really cool, but when working with code monospaced fonts look much in place than any other type of the font.

What do you think about this?

**Comment by daryllabar** [comment]
Yes please, monospace!

**Comment by MscrmTools** [comment]
Sure! For next release.

I will fix this one in master branch so that you can download a perversion asap

**Comment by rappen** [comment]
Download a WHAT?? ;) 
https://en.wikipedia.org/wiki/Perversion

**Comment by MscrmTools** [comment]
comment updated :)

**Comment by shytikov** [comment]
:+1: Monospace looks much nicer to me!
