### ISSUE TITLE
Folding by default in WebResource Manager

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#273]
Folding one of the nicest features ever, but it has certain gaps in implementation.

I think it should be enabled by default for non-compressed JS files, in addition it does not make sense to have folding if file is compressed.

What others think about these suggestions?

**Comment by MscrmTools** [comment]
I'm ok with your remark but how could I detect if code is compressed or note?

**Comment by shytikov** [comment]
I cannot say for sure, but it should be possible to find out, for example, if search for number of lines that starts from spaces or tabs, or if line has four or more spaces in the row, or by the length of the line (compressed code should have very long long lines), or one more idea is to try compress code in memory and see how size differs. If size change is less then 10%, so file was already compressed.

I think last approach should be most reliable one... Maybe a bit more resource-consuming... But it could be done in background, so user will not notice anything.

**Comment by MscrmTools** [comment]
I updated the code to implement your vision of folding. Can you test the prerelease and tell me what you think of this implementation?

**Comment by shytikov** [comment]
Thanks for implementations! It's very neat! There are some differences with my ideal picture, but it's more cosmetics :) Work with web resources become so much nicer now! Thank you!
