### ISSUE TITLE
Maybe it's time to recover About form?

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#274]
I've noticed that `XTB` missing About form, in the same time it actually exist in the source code, it's ugly, outdated, but it present there.

I was thinking maybe we can replace that ugly outdated form with nice and shiny welcome screen? And return "About" button to menu?

`XTB` develops quickly nowadays, so it would be easier to observe which version is used. Because now to understand version of `XTB` core we required to restart it.

**Comment by MscrmTools** [comment]
or you can see it in the title bar ?

**Comment by shytikov** [comment]
Sorry I don't see it... 

![no_about](https://cloud.githubusercontent.com/assets/1185905/11037837/3572ed60-8700-11e5-94b1-ce4163caaff5.png)

**Comment by shytikov** [comment]
Ah, you about version, sorry, I didn't see it there :) You right. 

But still About form would be nice to have (again)

**Comment by MscrmTools** [comment]
That is possible, yes
