### ISSUE TITLE
Access Checker: More Fields in User Selection

### ISSUE THREAD

**Issue by gfritz** [MscrmTools/XrmToolBox#276]
Our organization has users with the same First and Last names that exist across multiple Business Units and Active Directory domains because we have multiple locations logging into our CRM instance.  

It would be easier to distinguish users in the User Selection Dialog if the user Domain Names were displayed in the lookup.  Access rights can be different per Business Unit so the Business Unit of the user is also an identifier.

**Comment by MscrmTools** [comment]
Closed thank to the PR
