### ISSUE TITLE
Delete connection initiated from application status bar does not ask for confirmation

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#278]
I was trying to update connection using drop-down menu in application status bar, but since I drank too much coffee, I missed `Edit` and pressed `Delete`. Without any confirmation my connection was *GONE*.

I didn't believed my eyes, and tried once more, but paying attention to details. Same thing. `XTB` don't ask for confirmation when deletes connection from status bar menu.

I could not stop verifying this bug until all connections was gone from my configuration file.

Can we consider adding confirmation message on deletion of connection?

**Comment by skfd** [comment]
It' should not ask for confirmation. It should have an ability to undo deletion. UX же.
