### ISSUE TITLE
Unhandled exception 

### ISSUE THREAD

**Issue by AnatolyLoy** [MscrmTools/XrmToolBox#279]
1. Download version XrmToolBox:
  Версия сборки: 1.2015.2.21
  Версия Win32: 1.2015.2.21
2. unzip to folder
3. Run XrmToolBox.exe and get unhandled exception:

************** 
System.FormatException: Входная строка имела неверный формат.
   в System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   в System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   в XrmToolBox.AppCode.GithubVersionChecker.<RunAsync>d__3.MoveNext()

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.96.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/XrmToolBox.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Версия сборки: 3.5.0.0
    Версия Win32: 6.3.9600.16384
    CodeBase: file:///C:/windows/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
McTools.Xrm.Connection
    Версия сборки: 1.0.3315.606
    Версия Win32: 1.0.3315.606
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Версия сборки: 7.0.0.0
    Версия Win32: 7.0.0.3523
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/DamSim.SolutionTransferTool.DLL
----------------------------------------
System.Net.Http
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
DamSim.ViewTransferTool
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/DamSim.ViewTransferTool.DLL
----------------------------------------
System.Web.Extensions
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34274
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
Javista.XrmToolBox.ImportNN
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/Javista.XrmToolBox.ImportNN.DLL
----------------------------------------
McTools.StopAdvertisement
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/McTools.StopAdvertisement.DLL
----------------------------------------
System.Xml.Linq
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Версия сборки: 7.0.0.0
    Версия Win32: 7.0.0000.3543
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Deployment
    Версия сборки: 7.0.0.0
    Версия Win32: 7.0.0000.3543
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/Microsoft.Xrm.Sdk.Deployment.DLL
----------------------------------------
System.Runtime.Serialization
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ServiceModel
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
Microsoft.Xrm.Client
    Версия сборки: 7.0.0.0
    Версия Win32: 7.0.0000.0000
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/Microsoft.Xrm.Client.DLL
----------------------------------------
System.Runtime.Caching
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------
System.IdentityModel
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
PresentationFramework
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Data.Services
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Services/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Services.dll
----------------------------------------
MsCrmTools.AccessChecker
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.AccessChecker.DLL
----------------------------------------
System.Data.Services.Client
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Services.Client/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Services.Client.dll
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.AssemblyRecoveryTool.DLL
----------------------------------------
MsCrmTools.FormAttributeManager
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.FormAttributeManager.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.AttributeBulkUpdater.DLL
----------------------------------------
MsCrmTools.FormLibrariesManager
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.FormLibrariesManager.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.AuditCenter.DLL
----------------------------------------
MsCrmTools.FormParameterManager
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.FormParameterManager.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.FetchXmlTester.DLL
----------------------------------------
MsCrmTools.Iconator
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.Iconator.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.FlsBulkUpdater.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.MetadataBrowser.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.ScriptsFinder.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.SiteMapEditor.DLL
----------------------------------------
System.Design
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.MetadataDocumentGenerator.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.SolutionComponentsMover.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.SolutionImport.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MscrmTools.SyncFilterManager.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.SynchronousEventOrderEditor.DLL
----------------------------------------
MsCrmTools.Translator
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.Translator.DLL
----------------------------------------
ReachFramework
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/ReachFramework/v4.0_4.0.0.0__31bf3856ad364e35/ReachFramework.dll
----------------------------------------
MsCrmTools.UserRolesManager
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.UserRolesManager.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.UserSettingsUtility.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.ViewLayoutReplicator.DLL
----------------------------------------
MsCrmTools.WebResourcesManager
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.WebResourcesManager.DLL
----------------------------------------
MsCrmTools.PrivDiscover
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.PrivDiscover.DLL
----------------------------------------
MsCrmTools.RoleUpdater
    Версия сборки: 1.2015.2.21
    Версия Win32: 1.2015.2.21
    CodeBase: file:///C:/AnatoLoyDISK/Projects/CRM/XrmToolBox/MsCrmTools.RoleUpdater.DLL
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.36213 built by: FX452RTMLDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Web
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34274 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.resources.dll
----------------------------------------

**Comment by shytikov** [comment]
Сложно сказать наверняка, поскольку версия очень старая (практически девять месяцев). Можно попросить скачать последнюю сборку и проверить в ней?

Поменялся формат плагинов и огромное количество багов было закрыто — велика вероятность того, что всё будет работать как надо с последней версией `XTB`.

**Comment by AnatolyLoy** [comment]
Prerelease is working well!
Thanks!
