### ISSUE TITLE
Fix error importing charts in ChartManager

### ISSUE THREAD

**Issue by wilhelmhalys** [MscrmTools/XrmToolBox#280]
Hi!

I found a bug when importing several charts at the same time. After a few seconds performing the operation I get an error related to some problem with the input string.

After analyzing the error in the master branch, I found out there is a string.Join generating an an incorrect XML structure. I changed it and now it is working fine.

Please correct it:

File
-----
  \Plugins\MsCrmTools.ChartManager\MainControl.cs

Method
---------
  public void ProcessFiles(List<string> files)

OLD
------

`Service.Execute(new PublishXmlRequest
                                {
                                    ParameterXml = string.Format("<importexportxml><entities>{0}</entities><nodes/><securityroles/><settings/><workflows/></importexportxml>",
String.Join(")", results.Select(r => string.Format("<entity>{0}</entity>", r.Entity.GetAttributeValue<string>("primaryentitytypecode")))))
                                });`

NEW:
-------
 `Service.Execute(new PublishXmlRequest
                                {
                                    ParameterXml = string.Format("<importexportxml><entities>{0}</entities><nodes/><securityroles/><settings/><workflows/></importexportxml>", 
String.Join("",results.Select(r => string.Format("<entity>{0}</entity>",r.Entity.GetAttributeValue<string>("primaryentitytypecode")))))
                                });`

Sorry for the way to report the issue, but it is my first time submiting a change in GitHub,

Regards
Wilhelm Halys

**Comment by MscrmTools** [comment]
Thank you for the feedback! I will fix it as soon as possible
