### ISSUE TITLE
XrmToolBox does not allow passwords with semicolon

### ISSUE THREAD

**Issue by krmr** [MscrmTools/XrmToolBox#281]
The program does not allow passowrds containing a semicolon (';') for CRM Online/Office 365.

From a comment in #240 I understand that this should work now. But after clicking on 'Get Orgs.' there is an error message "Password cannot contains semicolon character [...]".

I did a quick test and commented out corresponding code in ConnectionForm.cs (lines 166-169). Afterwards the program could successfully connect to CRM Online.

**Comment by MscrmTools** [comment]
Hi,
Sorry for that! I handled this scenario but forgot to remove the warning when creating a connection...
I will fix this ASAP

**Comment by krmr** [comment]
Wow, thanks a lot for the prompt fix!
