### ISSUE TITLE
Win10 Connection Error: ACS10001: An error occurred while processing the SOAP header

### ISSUE THREAD

**Issue by dvalerian** [MscrmTools/XrmToolBox#282]
- Windows 10 Pro (fully updated) 10.0.10586 N/A Build 10586
- .NET Framework 4.6 (all enabled)
- .NET Framework 3.5 (all enabled)
- Windows Identity Foundation 3.5 (enabled)
- Latest Version of XRM Toolbox (v1.2015.11.5)

Connection Settings:
- Use CRM Online
- Use Office 365

When clicking "Get Orgs."...

If I put in the wrong password I get an authentication error.  If I put in the right password I get the following error:
ACS10001: An error occurred while processing the SOAP header

Been using this product for years and love it.  Stumped by this error.  Thanks for any help.

**Comment by MscrmTools** [comment]
Hi!
Aboslutely nothing changed from a connection stand point in the latest version. 
What is the version of CRM Online?

**Comment by dvalerian** [comment]
CRM Online 2015 Update (7.1.1.4210)(DB 7.1.1.4210)

**Comment by MscrmTools** [comment]
Do you have federation to use your local credentials as CRM online credentials?

**Comment by dvalerian** [comment]
Yes, I think so, we just started using Azure AD Online as part of our O365 Subscription.  Not sure if that is the same thing, but I now use my O365 account to log into Win10 and for CRM Online.

**Comment by MscrmTools** [comment]
I don't have this kind of environment to test what parameters need to be set

**Comment by MscrmTools** [comment]
Did you try with latest version?

**Comment by MscrmTools** [comment]
Old issue, closing it. 
Open it again if needed
