### ISSUE TITLE
Esc button to close all dialogs

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#283]
Using the Esc button to close dialogs is more or less standardized behaviour in Windows.
It would be nice to have that in all dialogs in XTB too :)

**Comment by KingRider** [comment]
dialogs mean Tabs? Try CTRL+F4

**Comment by MscrmTools** [comment]
I guess the author of this issue is talking about every dialog that could be opened in plugins (like selection dialog or others)

**Comment by rappen** [comment]
Nope @KingRider - dialogs=dialogs, not tabs. Not really windows standard behaviour to close tabs using Esc, no?
And well, primarily I mean dialogs from the main XTB application, such as connection windows etc.

**Comment by MscrmTools** [comment]
Done wherever it was possible to implement
