### ISSUE TITLE
[Request] Open XML Ribbon Workbench

### ISSUE THREAD

**Issue by KingRider** [MscrmTools/XrmToolBox#286]
I no like SDK and love XTB... i need load XML ribbon

Look a example
http://garethtuckercrm.com/2011/01/18/how-to-view-ribbon-definitions-in-crm-2011-3/

Install Ribbon Workbench:
http://www.develop1.net/public/page/Ribbon-Workbench-for-Dynamics-CRM-2011.aspx

Thanks!

**Comment by MscrmTools** [comment]
Ribbon Workbench could possibly arrive in XrmToolBox but it is not my tool... I know the developer is considering implementing a light ribbon editor in XrmToolBox but you will have to wait

**Comment by KingRider** [comment]
ok thanks!
