### ISSUE TITLE
MsCrmTools.SampleTool has Null Pointer Exception

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#29]
`MsCrmTools.SampleTool` fires Null Pointer Exception in `ProcessWhoAmI` method.

Variable `service` is never assigned. 

I believe this plugin like a jump-start for new developers, and it contains recommended approaches to development. But how then `service` variable should be assigned? @MscrmTools can you provide quickfix in the recommended way how to do it?

**Comment by shytikov** [comment]
It will get closed automatically as soon as it will be merged to `master`.

**Comment by MscrmTools** [comment]
Just for information, the fix is about making the method that is called by ExecutMethod public instead of private
