### ISSUE TITLE
Find and replace Web Resources Manager - behaviour improvement for keyboard jockeys

### ISSUE THREAD

**Issue by craigseymour** [MscrmTools/XrmToolBox#291]
Since the folding text editor was introduced, the 'Find and Replace' dialog behaviour has been a bit annoying.  There are 3 small changes needed to help out users who prefer the keyboard to the mouse:

1. When launching Find and Replace with CTRL-F or Edit menu - set focus to the text input (it seems to currently be invisibly set to 'Match Case', making it necessary to grab the mouse and click into the text input box (or hit 'Tab' multiple times) to start typing in it.  

2. Map the Enter key to the 'Find Next' button - it's currently necessary to click the button (or Tab to it)  to execute the search.

3. Map the Escape Key to cancel.

A final tweak (if possible) is to make the dialog open up on the same monitor as the Web Resources Manager - it currently seems to default to the primary monitor

**Comment by MscrmTools** [comment]
Hi Craig and thank you for your feedback.
These changes have already been requested and are ready to ship for next release

**Comment by craigseymour** [comment]
Smashing!  Thank you :-)
