### ISSUE TITLE
Bug in Privilege discovery plugin -  shows wrong results than what is queried

### ISSUE THREAD

**Issue by nitinTest123** [MscrmTools/XrmToolBox#292]
I was searching for security roles that implement Org wide read privilege for Activity, but the result displayed roles that had BU level read privilege on Activity (some of the displayed roles actually had org level read as well). The screenshot will explain all.

Privilege Discovery tool version: 1.2015.7.6
CRM Version 2013 (On prem)
![privilege discovery shows wrong results](https://cloud.githubusercontent.com/assets/16291068/11783930/f9b86800-a279-11e5-87bd-0054655e0ee4.png)

**Comment by MscrmTools** [comment]
I just reviewed the code and cannot find any problem with it, nor can I reproduce your problem.
If possible, I would be happy to receive a solution with your security roles so that I can import them in one of my development organization and test it with the same data you used to get the problem

**Comment by nitinTest123** [comment]
Hi, unfortunately I cannot submit you the solution since the security role alone will fail to import without the rest of the entities (which are client confidential information) and cannot be shared.

I checked a little bit around for other entities and indeed privilege discovery tools works correctly. It's only for some weird reason that it shows wrong results for "Activity" entity.

Thanks for your help and efforts, anyways. Please keep the good work up. You are filling in a huge gap(missing features) in default CRM system!

**Comment by MscrmTools** [comment]
I close this issue. If needed, reopen it
