### ISSUE TITLE
Connect Using IFD

### ISSUE THREAD

**Issue by gloebig** [MscrmTools/XrmToolBox#294]
Hello,
I am new to using the XrmToolBox

Can someone assist me with connecting using an IFD?

It says to use for an IFD the Server Name: 
Use <discovery_name>.<domain>.<extension>

My discover name looks like this, can you help with parsing? 

https://crmdiscovery.servername.com:5555/XRMServices/2011/Discovery.svc

For the domain, mine looks like this, can you help with parsing?

https://crm.servername.com:5555/main.aspx#

Or is there a previous issue with an example for this?

**Comment by MscrmTools** [comment]
Try like the capture below... in "Server Name", put crmdiscovery.servername.com

![2015-12-18_09-16-02](https://cloud.githubusercontent.com/assets/10774317/11892387/02c7493e-a568-11e5-8664-42f06f320f96.png)

**Comment by gloebig** [comment]
That did it, thank you very much!
