### ISSUE TITLE
"An error occurred while retrieving organizations"

### ISSUE THREAD

**Issue by eliotstock** [MscrmTools/XrmToolBox#295]
![xrm_toolbox_login](https://cloud.githubusercontent.com/assets/1144814/11898425/a9505116-a58f-11e5-95a5-ff5c4c49d06c.png)
![xrm_toolbox_error](https://cloud.githubusercontent.com/assets/1144814/11898428/ad866c2a-a58f-11e5-962e-822bab122ed1.png)

I have filled in the "Login" field, but the error message implies I haven't.

**Comment by MscrmTools** [comment]
Can you confirm if you Office 365 is federated with your local AD?
For Office 365 based CRM, login should be an email address

**Comment by eliotstock** [comment]
No local AD, just Office 365. I did eventually manage to log in and yes, that log should have been an email address. But that's not the bug. The bug is that the error message is wrong. ".UserName" *is* populated.

**Comment by MscrmTools** [comment]
I'm not bulding this error message, I'm passing your information to CRM SDK assembly that return this error... Nothing I can do by myself

**Comment by MscrmTools** [comment]
There is a new connection wizard. I close this "issue".
