### ISSUE TITLE
with release v1.2015.12.20 I cannot connect to https://orgname.crm4.dynamics.com

### ISSUE THREAD

**Issue by rvroemen** [MscrmTools/XrmToolBox#296]
Is the CRM4 server not anymore supported?

**Comment by MscrmTools** [comment]
Yes it should work... During my latest tests, I did not have any problem to connect to EMEA organization 
I will make a test soon to ensure this

**Comment by MscrmTools** [comment]
I confirm

![image](https://cloud.githubusercontent.com/assets/10774317/11938747/461d27fa-a81d-11e5-94a7-ac3879543882.png)

**Comment by MscrmTools** [comment]
Please provide feedback about this problem. Otherwise, I will close this issue

**Comment by rvroemen** [comment]
I tried to connect to a different organization, that was successful!
Please close the issue …

Van: MscrmTools [mailto:notifications@github.com]
Verzonden: dinsdag 5 januari 2016 13:45
Aan: MscrmTools/XrmToolBox <XrmToolBox@noreply.github.com>
CC: René Vroemen <r.vroemen@crmplusplus.nl>
Onderwerp: Re: [XrmToolBox] with release v1.2015.12.20 I cannot connect to https://orgname.crm4.dynamics.com (#296)


Please provide feedback about this problem. Otherwise, I will close this issue

**Comment by MscrmTools** [comment]
Thank you for the feedback
