### ISSUE TITLE
WorkAsyncInfo constructor with callback parameter

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#297]
It would be great to have an overload of the `WorkAsyncInfo` constructor that takes callback method argument:
`public WorkAsyncInfo(string message, Action<BackgroundWorker, DoWorkEventArgs> work, Action<RunWorkerCompletedEventArgs> callback)`

**Comment by daryllabar** [comment]
The purpose behind creating the WorkAsyncInfo class was to keep from having 15 different constructors that are awkard to read and results in changes to the IWorkAsync interface.  The latter wouldn't be affected by this change, but the former would still be a potential issue. 

Does anyone else have any thoughts?

**Comment by shytikov** [comment]
Current signature is inconsistent at least. If `work` action requires `callback` action it should be added as argument to constructor, not assigned to property after creation of object. So `WorkAsyncInfo` will be constructed and all his properties could be marked as `readonly` and guaranteed will not be changed by other code.

If we implying that `WorkAsyncInfo` instance could have mutable `work` and `callback`, we should not pass `work` as input parameter than.

**Comment by daryllabar** [comment]
The Info object is designed to be mutable, until you pass it into the WorkAsync Call, although nothing is currently "Locking" that down, although maybe we should?

**Comment by MscrmTools** [comment]
Very old thread :)
Do we need to continue improving it or things are good the way they are now?

**Comment by rappen** [comment]
We're good :)

**Comment by MscrmTools** [comment]
Ok, I'm closing the issue. Anyone can reopen it if needed
