### ISSUE TITLE
User Roles Manager - Show what users have role assigned?

### ISSUE THREAD

**Issue by ChrisEZT** [MscrmTools/XrmToolBox#298]
This is probably more of an enhancement than an issue.  Would it be possible to select a security role, and then show what users are assigned to that role?  Perhaps in the existing User Roles Manager plugin?

Thanks!

**Comment by MscrmTools** [comment]
There is a default report in mscrm that displays a matrix or users and roles.
It is called user overview

**Comment by MscrmTools** [comment]
So I guess I won't implement your feature request
