### ISSUE TITLE
Connect to crm 2016 online

### ISSUE THREAD

**Issue by cedar-technologies** [MscrmTools/XrmToolBox#299]
Does v1.2015.12.20 offers the possibility to connect to crm 2016 online using O365 account?

Thanks

**Comment by MscrmTools** [comment]
Yes, if you put your CRM online org url, you should have to specify your login and password, then it should connect
The only scenario I wasn't able to test is if your office 365 is federated with your local AD

**Comment by MscrmTools** [comment]
I just tested it now

![image](https://cloud.githubusercontent.com/assets/10774317/11938769/77328358-a81d-11e5-8db6-4a6defec6e95.png)

**Comment by cedar-technologies** [comment]
No my office 365 is not, I'm going to give it a try again (sorry really new to the tool)

**Comment by MscrmTools** [comment]
No problem, just copy your browser url when connected to your organization and paste it in the connection wizard url

**Comment by cedar-technologies** [comment]
I was able to connect with a previous version (1.2015.11.5) but not with the latest one, should I pass this url : https://xxxxxx.crm.dynamics.com then my O365 Credentials?

**Comment by MscrmTools** [comment]
Yes

**Comment by cedar-technologies** [comment]
I can connect with 1.2015.11.5 but for some reason not with 12.20, is crm 2016 supported with 11.5?

**Comment by MscrmTools** [comment]
No, normally, you should not be able to connect to CRM 2016 with 11.5

**Comment by MscrmTools** [comment]
I don't know if you overwrote your Xrmtoolbox folder with the latest version but if so, please try with a fresh copy

**Comment by MscrmTools** [comment]
Ok, there is definitively a problem here... I cannot succeeded either to connect to a CRM 2016 online. My previous test was a CRM 2015 Online (my mistake).
Anyway, I tried with PluginRegistrationTool from CRM 2016 SDK and there is the same problem, I cannot connect so it looks like a problem with SDK assemblies.
I'm trying to reach Microsoft to get some help on this topic.

**Comment by cedar-technologies** [comment]
Thanks, let me know if you find out a solution :-)
Alex

**Comment by MscrmTools** [comment]
It was not working yesterday, it is working today without any change...

Can you test again today?

**Comment by cedar-technologies** [comment]
Hi,

no it's still not running

**Comment by ValoremXrm** [comment]
Hey MscrmTools, long time user. Thank you for your work on this. I just downloaded Christmas release and it will not connect. I lost older version when computer crashed or I would just use that and move on. I am accessing O365 2015 7.1.1. No rush, enjoy your holidays.

**Comment by MscrmTools** [comment]
This is a known issue where the connection works only if use ssl parameter is set to false, even with office 365!!! A work around is on the way, just need to commit it

**Comment by mscottsewell** [comment]
I am also unable to connect to a 2015 O365 instance using the latest 2015.12.20 release - 
(The November version still works fine.)  
I'm reading your comment but I don't see a place to set the SSL Parameter to False, is that something I can do to test? or do I need to wait for your commit?

**Comment by MscrmTools** [comment]
Unfortunately, I need to release a new version for that...

**Comment by MscrmTools** [comment]
Can you test latest pre release version?

**Comment by mscottsewell** [comment]
I tried the 2016.104.72 release. When it attempted to connect, it threw "Object reference not set to an instance of an object" - are there any logs/messages that I could provide that would be helpful?
![image](https://cloud.githubusercontent.com/assets/6276300/12089544/d5a7298e-b2b3-11e5-89eb-1456cdd22ad2.png)


This is connecting to CRM Online (2015) - (It uses our ADFS server for authentication.)

**Comment by MscrmTools** [comment]
@rappen is on the same situation... and I guess my changes should work but this new error message seems related to my code...
Just to be sure, can you add this xml in the xrmtoolbox.exe.config file?
```XML
<system.diagnostics>
    <trace autoflush="true" />
    <sources>
      <source name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient"
              switchName="Microsoft.Xrm.Tooling.Connector.CrmServiceClient"
              switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="console" type="System.Diagnostics.DefaultTraceListener" />
          <remove name="Default" />
          <add name ="fileListener" />
        </listeners>
      </source>

      <source name="Microsoft.Xrm.Tooling.CrmConnectControl"
              switchName="Microsoft.Xrm.Tooling.CrmConnectControl"
              switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="console" type="System.Diagnostics.DefaultTraceListener" />
          <remove name="Default" />
          <add name ="fileListener" />
        </listeners>
      </source>
    </sources>
    <switches>
      <!--
            Possible values for switches: Off, Error, Warning, Info, Verbose
                Verbose:    includes Error, Warning, Info, Trace levels
                Info:       includes Error, Warning, Info levels
                Warning:    includes Error, Warning levels
                Error:      includes Error level
        -->
      <add name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value="Verbose" />
      <add name="Microsoft.Xrm.Tooling.CrmConnectControl" value="Verbose" />
      <add name="Microsoft.Xrm.Tooling.WebResourceUtility" value="Verbose" />
    </switches>
    <sharedListeners>
      <add name="fileListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="XRMToolingLogs.log" />
      <!--<add name="eventLogListener" type="System.Diagnostics.EventLogTraceListener" initializeData="XRMTooling" />-->
    </sharedListeners>
  </system.diagnostics>
```
It should write some logs in the XrmToolBox folder when trying to connect

**Comment by rappen** [comment]
Just to confirm - I get the same ``Object reference....`` error using latest prerelease.

**Comment by MscrmTools** [comment]
Hum... I thought I just added another extra connection with the SSL parameter set to false...

It must be something else...

**Comment by mscottsewell** [comment]
@MscrmTools - Were you asking me to add the XML (above) to new file in my directory? I created a file, but now the toolbox doesn't start. "side-by-side configuration is incorrect"
If that's not what you were asking me to do - just disregard. ;)

**Comment by MscrmTools** [comment]
The complete file should looks like this:

```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<system.diagnostics>
    <trace autoflush="true" />
    <sources>
      <source name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient"
              switchName="Microsoft.Xrm.Tooling.Connector.CrmServiceClient"
              switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="console" type="System.Diagnostics.DefaultTraceListener" />
          <remove name="Default" />
          <add name ="fileListener" />
        </listeners>
      </source>

      <source name="Microsoft.Xrm.Tooling.CrmConnectControl"
              switchName="Microsoft.Xrm.Tooling.CrmConnectControl"
              switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="console" type="System.Diagnostics.DefaultTraceListener" />
          <remove name="Default" />
          <add name ="fileListener" />
        </listeners>
      </source>
    </sources>
    <switches>
      <!--
            Possible values for switches: Off, Error, Warning, Info, Verbose
                Verbose:    includes Error, Warning, Info, Trace levels
                Info:       includes Error, Warning, Info levels
                Warning:    includes Error, Warning levels
                Error:      includes Error level
        -->
      <add name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value="Verbose" />
      <add name="Microsoft.Xrm.Tooling.CrmConnectControl" value="Verbose" />
      <add name="Microsoft.Xrm.Tooling.WebResourceUtility" value="Verbose" />
    </switches>
    <sharedListeners>
      <add name="fileListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="XRMToolingLogs.log" />
      <!--<add name="eventLogListener" type="System.Diagnostics.EventLogTraceListener" initializeData="XRMTooling" />-->
    </sharedListeners>
  </system.diagnostics>
</configuration>
```

**Comment by mscottsewell** [comment]
OK - it looks like it's connecting to the service and it finds the 9 orgs in our O365 organization - but when it attempts to connect to my production org 'XX' - it fails.

    Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : DiscoverOrganizations - Discovery Server Get Orgs Call Complete - Elapsed:00:00:02.4671943
    Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Found 9 Org(s)
    Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : looking for Org = XX in the results from CRM's Discovery server list.
    Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM

I'm happy to send the complete log to you directly.

**Comment by MscrmTools** [comment]
Yes, please!
And send me the url you are using too
Thanks

**Comment by mscottsewell** [comment]
@MscrmTools Done. - sent to your gmail account.

**Comment by MscrmTools** [comment]
Ok, for information, the problem seems related to the fact that the organization uses AAD.
In this configuration the constructor for class `CrmServiceClient` expects the organization unique name instead of the organization url name
I tested the same in an organization (also 7.1.1) without AAD and it works fine with organization url name

I'm waiting for feedback from Microsoft

**Comment by rappen** [comment]
Workaround until MS got this figured out, that at least work to connect Online 7.1.1.4314 over O365:
Replace organization friendly name with it's unique name found under __Settings - Customizations - Developer Resources__:

_Red smudge indicates friendly name, green smudge is unique name._
![image](https://cloud.githubusercontent.com/assets/2572253/12179482/7e205a0c-b577-11e5-8355-40b7b7332199.png)

![image](https://cloud.githubusercontent.com/assets/2572253/12179503/9febf8e4-b577-11e5-99f7-150fa958babb.png)

**Comment by ValoremXrm** [comment]
Thank you Jonas, this works great!

Tom Northrup | Manager, CRM | Valorem Consulting
+1 (816) 533-7983 | tnorthrup@valoremconsulting.com<mailto:tnorthrup@valoremconsulting.com>

**Comment by forceworks** [comment]
Yes, this worked for me also, thanks

**Comment by KittyDreadful** [comment]
I still can't get this work.  I'm on 8.0.0.286 (CRM 16).  This is killing me!  Any help?  Any idea when it will be fixed?  :/

**Comment by MscrmTools** [comment]
@kittyDreadful is your Office 365 tenant federated with your local AD?

**Comment by KittyDreadful** [comment]
No, its not.

**Comment by joenewstrom** [comment]
I have AAD and had to use the following combination:

1. Enter the URL Unique Name as @rappen indicated.
2. Do not check "Use your current credentials" (this threw an error)
3. Do not check "Store passwords as encrypted string in connections file" (this threw an error and is bad password hygiene anyway)
4. Connect and type in your password. (Works)

Little bit of getting used to vs. the old XRM Toolbox but it works fine once you're in.

**Comment by Golsaa** [comment]
I'm trying to use v1.2016.1.30 for CRM 2016 online but it doesn't connect to CRM yet. Any suggestion? 
![xrmtoolboxcannotconnectcrm](https://cloud.githubusercontent.com/assets/17053734/12797948/9d350c3e-cb2b-11e5-9567-e5b71ac82158.JPG)

thanks

**Comment by rappen** [comment]
Incorrect error message "Object reference not set..." should be resolved by PR #332. Try prerelease from Feb 3. or later where this is included.
At lease you should get a more informative message then...

**Comment by Skubakoob** [comment]
Getting same error - the pre release just gives me an unable to login to crm message
I've tried the unique name, no joy with that. Any way to get more information about what it's actually complaining about?

**Comment by daryllabar** [comment]
You have to hand edit the connection xml.  Just changing it in the UI won't work due to another bug.

**Comment by soliver99** [comment]
how do you "hand edit the connection xml"?

**Comment by daryllabar** [comment]
@soliver99, open up the xml file in Notepad ++

**Comment by bsampath84** [comment]
@daryllabar I am also seeing the same error. I have hand-edited the xml and seeing the same issue. the version i am using is 1.2016.1.30. My organization also uses 2 factor authentication. Is that also a factor for not working? Please let me know.

**Comment by daryllabar** [comment]
@MscrmTools My understanding is that 2 factor authentication isn't enabled for the XTB.  Is that correct?

**Comment by MscrmTools** [comment]
You are right, two factors is not supported yet

**Comment by daryllabar** [comment]
@bsampath84 , there is your answer.

**Comment by bsampath84** [comment]
@daryllabar thank you for the quick response.. Could you please let me know if you know Abby other tool that can work with two factor? I mean I am trying to use fetchxml builder on our crm online 2015 instance

**Comment by daryllabar** [comment]
Sorry. can't help there.  You could stand up a demo environment, import you solution into that, and then build your fetch XML in that.

**Comment by McSockMonkey** [comment]
I had this problem as well.  It was resolved for me by opening the toolbox, going to the Settings, then the Proxy tab and changing the setting to "Use Internet Explorer configured proxy".  So for some, this or the Custom Proxy may be a solution.

**Comment by rodarius** [comment]
Is it the plan to use the 2Factor authentication with the application password or are you going to implement the actual 2Factor logon with actively retreiving the 2nd factor ?

**Comment by MscrmTools** [comment]
I won't implement anything myself but let XRM.Tooling assemblies from Microsoft do the job. But, as stated in #337, it will take time since I don't have yet a deployment with 2F authentication available

**Comment by Golsaa** [comment]
I tried to hand edit the config file as bellow 
![handeditconnectionstr](https://cloud.githubusercontent.com/assets/17053734/13039361/c9c599a0-d402-11e5-9f56-612c4dc6b666.JPG)



And I still have issue connecting to CRM with this exception
![64string-exception](https://cloud.githubusercontent.com/assets/17053734/13039311/224ebed6-d402-11e5-8cf6-5f4ea30aa81f.JPG)

**Comment by rgsiiiya** [comment]
I am able to connect to CRMOL 2016 with build:   1.2016.130

**Comment by LastExile1** [comment]
I have been using the product for quite some time now and it has been an amazing help.  I appreciate all of your work that has gone into everything.  I too am experiencing this login issue.

The tool will sit there in a stated of trying to connect and then display the "Object not set to an instance of an object."  I have gone through and checked both my production and dev settings in Developer Resources with no luck.  I've gotten so far as to copy the connection information that has been saved in the last known working version for me, which was v1.2015.11.05 where it uses the **Microsoft.Xrm.Client.dll** instead of the newly updated connection changes in later releases **Microsoft.IdentityModel.Clients.ActiveDirectory.dll** and **Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll**.  I'm not too familiar with why the move was made but I imagine my issue is the 2 form factor authentication.  My environment is CRM Online 2015 update 1 with ADFS 3.0.

For now it looks like I'm stuck using XrmToolBox v1.2015.11.05 until something is done about fixing or updated the authentication process.  Is there any way to back track the new version to the older authentication process, that still works for me?  Been dying to try a less buggy version of PowerBI Option-Set Assistant as it's been a complete life saver for me.
![capture](https://cloud.githubusercontent.com/assets/15112916/13227049/7defbb04-d949-11e5-909c-05364b9e42af.PNG)

**Comment by daryllabar** [comment]
@LastExile1 Please see @rappen 's Comment: https://github.com/MscrmTools/XrmToolBox/issues/299#issuecomment-169771747

You may need to hand edit your Configuration XML to remove all "friendly name" org names.

**Comment by LastExile1** [comment]
Thanks for the reply @daryllabar.  I realized i was trying to edit an existing connection with the fix thus resulting in a failure every time.  So I scrapped that and created a new connection like I should have to begine with using @rappen 's fix of unique name in front of the rest of the required url string.

**_[UNIQUE_NAME].crm.dynamics.com_**

That worked and I'm using v.1.2016.1.30 for anyone else having issues.

**Comment by DebSil** [comment]
This is nuts.  Why in the world is this stuff not part of Dynamics?????

I have followed all instructions here and still cannot connect.  Have gotten the "unique name" of our org in 2016 Online and am still getting "If the unique name for your organization is different from the name used in the url you provided, please replace the organization name in the url with the organization unique name
<img width="376" alt="xrmtoolboxerror" src="https://cloud.githubusercontent.com/assets/9323672/13608603/80bf4706-e523-11e5-8f9f-980459cca027.png">

**Comment by MscrmTools** [comment]
Is http (and not https) a typo mistake?
If you want more information on why this is not working, please [enable tracing](https://github.com/MscrmTools/XrmToolBox/wiki/Enable-tracing-in-XrmToolBox) then find the error message in the trace and past it in this thread

**Comment by DebSil** [comment]
<img width="430" alt="step1" src="https://cloud.githubusercontent.com/assets/9323672/13608812/63403d38-e524-11e5-96ce-93d850b9d601.png">

<img width="432" alt="step2" src="https://cloud.githubusercontent.com/assets/9323672/13608827/6c1696d2-e524-11e5-8473-8f0a74ddea3c.png">


<img width="430" alt="step3" src="https://cloud.githubusercontent.com/assets/9323672/13608832/7081f7c0-e524-11e5-93a0-6b1952d85cf1.png">

**Comment by DebSil** [comment]
My XRMToolbox folder does not contain XrmToolBox.exe.config

**Comment by MscrmTools** [comment]
as mentioned in the wiki article, you may have to create it

**Comment by Rustice** [comment]
![image](https://cloud.githubusercontent.com/assets/18499237/14580756/66c6aca8-03d8-11e6-8a7f-92d59009446a.png)

I follow the instructions to put the Unique Name in the url, but I'm still getting this error message. Any ideas?

**Comment by cacbon** [comment]
We have the same issue, i.e. the old XrmToolBox work, but the new is not.
Even tried with the connection string, i still failed.
Then I accidentally found a combination of parameters that made it able to connect to our CRM 2015 on-premise:
- do not check on "Use your current credentials"
- select No for IFD on the next step (even though that our system had deployed IFD)
- on the 3rd step: enter domain name, user name, password. The username must be in the format of username@shortdomainname (eg. tom@mydomain instead of tom@mydomain.com). Select encrypt password to save into the connection file.

Hope this combination help some way.

 Regards,
-

**Comment by pratyush2512** [comment]
![image](https://cloud.githubusercontent.com/assets/19660487/15663835/96804546-271c-11e6-9293-e399480f667a.png)
 how to solve this error,its urgent please reply asap

**Comment by MscrmTools** [comment]
It might be urgent but if so, I guess you read this thread and tried all answers in it, right?

**Comment by pratyush2512** [comment]
no reply is solving this error please try to help me from step to step to figure it out

**Comment by MscrmTools** [comment]
Could you, at least, provide basic information like deployment type (onpremise, online, IFD) and also provide logs?
With just "it does not work", I can't help you

**Comment by pratyush2512** [comment]
ok i am working on XRM recent version trying to connect crm 2016 on premise one sever is connecting but another one is not connecting

**Comment by pratyush2512** [comment]
i want to edit the site map of 2016 crm on premise  accroding to crm 2015 on premise its the business requirement so for that i am using xrm but its not connecting so how would i edit ?is there any other way?

**Comment by MscrmTools** [comment]
Logs please? You should have a log file in your Xrmtoolbox folder

**Comment by pratyush2512** [comment]
![image](https://cloud.githubusercontent.com/assets/19660487/15665132/af863eec-2726-11e6-905e-899ddd6b310c.png)
this the log

**Comment by MscrmTools** [comment]
Is it an IFD/ADFS configured deployment?

**Comment by pratyush2512** [comment]
IFD configured

**Comment by MscrmTools** [comment]
ok, did you try to use domain\username in username for credentials?

**Comment by kdeepak4** [comment]
Found out the issue for "Unable to login to dynamics CRM" error in XRM toolbox. "Plugin registration tool" plugin is causing this issue. Remove the Plugin from "Plugins" folder of XRM toolbox. Close "XRM toolbox" and re-open. this will solve the issue

**Comment by shytikov** [comment]
This issue is not about Plugin Registration Tool. It's about having two plugins that uses early bound. You can make Plugin Registration working if you'll delete Early Bound generator or Ribbon workbench.

We're working on finding solution for this issue — #353.

**Comment by AbhishekSinha17** [comment]
I am getting below error. Tried with unique orgname `
![Uploading Untitled.png…]()


`

**Comment by AbhishekSinha17** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19207138/19311784/6db0aa3e-90ad-11e6-859f-a466accf064e.png)

**Comment by AbhishekSinha17** [comment]
I am connecting to CRM online in 2016

**Comment by AbhishekSinha17** [comment]
I have given unique org name also. Any help will be appreciated.

**Comment by MscrmTools** [comment]
This error means the url expected cannot be reached. This can be a network error (proxy/firewall?) or a temporary outage of CRM Online

**Comment by BubunCTS** [comment]
Hi I am not able to connect XRM Tool Box .Please help
![xrm](https://user-images.githubusercontent.com/35954769/35558292-a9d53980-05cd-11e8-8b02-28a5f2ff5a32.PNG)
