### ISSUE TITLE
Connect to crm 2016 on-premises

### ISSUE THREAD

**Issue by zwheui** [MscrmTools/XrmToolBox#302]
When I try to use the latest version v1.2015.12.20 to connect my Dynamic CRM 2016 on-premises

The connection always fail with the error "unable to login to Dynamic CRM"

Anyone have this issue?

I see the release log said this version is support to connect CRM 2016.

**Comment by zwheui** [comment]
BTW, I can use this version to connect my Dynamic CRM 2015 successfully.

So, I'm not sure that is this version really support Dynamic CRM 2016?

**Comment by MscrmTools** [comment]
Yes it should, I can connect to my own on premise organization.
Is it just on premise or claims authentication enabled deployment ?
You can enable tracing for Xrmtoolbox by following this article : https://msdn.microsoft.com/fr-fr/library/dn689064.aspx
And look in there what is wrong

Latest release use new CRM assemblies so connections are something quite new in this release

**Comment by zwheui** [comment]
It is just on premise, not claims authentication.

Are you saying the tool only works for the claims?

**Comment by MscrmTools** [comment]
No. I'm just trying to figure if your CRM deployment has something specific

**Comment by zwheui** [comment]
My CRM 2016 is using the SQL 2016 CTP 3.2 with separate server deployment.

I open the Deployment management and find the status of the organization is failed.

I add a new organization for testing. There is a error during the adding.

I ignore that error, the new organization status is enabled.

But still the XrmToolbox can't connect neither the org.

I think I have to use the SQL Server 2014 and deploy the CRM again.

**Comment by MscrmTools** [comment]
Did you enable trace to see what is going on?

**Comment by zwheui** [comment]
It works when I'm using SQL 2014 to redeployment the environment.

When we meet something weird in MS Application, reinstall is always the most efficient way to solve the problem :-)

Now I can connect the CRM 2016 with the tool, thank you.

But I'm facing another issue after I config the IFD of CRM 2016, I will open another case for it.
