### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by baltmann** [MscrmTools/XrmToolBox#304]
The .exe errors on start.
Ran as Administrator on Win10.
Zip files unblocked.

![xrmtoolboxerrorstarting](https://cloud.githubusercontent.com/assets/1978241/12072103/a319919a-b124-11e5-8a14-e261b7768f45.JPG)

**Comment by shytikov** [comment]
Hi! Happy New 2016! :) 

Not sure, maybe I have seen this error already... I suppose we have fixed it long time ago. Can you update `XrmToolBox` to most recent version and verify?

**Comment by baltmann** [comment]
Hi Alex,

I had an old version! :(

V1.2015.2.21

 

It looks much better with :)

V1.2015.12.20

 

Thanks for your prompt help.

And snovim godom to you too!

 

Bill

**Comment by caiello3** [comment]
I'm new to Xrm, but heard a lot of good things. I am getting this same error when trying to open it. Using v1.2015.2.21. Zip is unblocked, Windows 8.1. Thanks!

**Comment by MscrmTools** [comment]
You are using a reaaallllly old version. Please use the latest one available at www.xrmtoolbox.com
