### ISSUE TITLE
Improvement: Collapse all button needed in the Webresource Manager

### ISSUE THREAD

**Issue by zmulk** [MscrmTools/XrmToolBox#305]
There should be a Collapse all button in the menu item, to collapse all the open nodes.
Some project have a long list of open nodes.

**Comment by MscrmTools** [comment]
I will work on this

Thank you for the feedback

**Comment by MscrmTools** [comment]
I added two link labels under the preview

![image](https://cloud.githubusercontent.com/assets/10774317/12263922/2b5c1c1a-b933-11e5-905f-df2b4265bb75.png)

You can get this version in the latest pre release or wait for the January release
