### ISSUE TITLE
SiteMap Editor incorrectly reading "Pass Params" value

### ISSUE THREAD

**Issue by cfharp** [MscrmTools/XrmToolBox#306]
I have two different orgs that needed the AccountKey for ClickDimensions to be updated, and it seems that the value "Pass Params" on a SubArea is not correctly read from the xml. In the context of ClickDimensions, this is the cdi_settingspage which launches a URL and needs orgname to be passed through. Even though the customizations.xml has this flag set to true, the SiteMap Editor in XrmToolBox is displaying (and saving) it as false.

**Comment by MscrmTools** [comment]
What is the version of SiteMapEditor you are using?

**Comment by cfharp** [comment]
Sorry about that - SiteMapEditor v1.2015.11.4 and XrmToolBox v1.2015.11.5. 

I see there is a new version, 2015.12.20, which I just downloaded and found the same issue.

**Comment by MscrmTools** [comment]
Ok, I saw something on my code and thought I had fixed it. I will review the code

**Comment by MscrmTools** [comment]
PassParams can be set to 0, 1, True or False. 
I just handled True or False, so I will add support for values 0 and 1

**Comment by MscrmTools** [comment]
Can you check latest prerelease to see if it fixes your issue?

**Comment by cfharp** [comment]
I just tested using v1.2016.112.83 and it still seems to be broken.

Before:
<SubArea Id="cdi_settingspage" Title="ClickDimensions Settings"
Icon="$webresource:cdi_cdsettings32x32" Url="
https://app.clickdimensions.com/MSCRM/v2015/pages/Settings.aspx?accountKey=REMOVED"
Client="Web" PassParams="1" />

After:
<SubArea Icon="$webresource:cdi_cdsettings32x32" Id="cdi_settingspage" Url="
https://app.clickdimensions.com/MSCRM/v2015/pages/Settings.aspx?accountKey=REMOVED"
Title="ClickDimensions Settings" AvailableOffline="false"
PassParams="false" Client="Web" />

**Comment by MscrmTools** [comment]
It should be good now => latest prerelease

**Comment by cfharp** [comment]
Looks good, thank you!
