### ISSUE TITLE
Manage NN Relationship : Allow to import/remove marketing list members

### ISSUE THREAD

**Issue by Jay-ZhangJie** [MscrmTools/XrmToolBox#308]
Hi,

I tried to import NN relationship data between MarketingList and Account entities. However, it gave me error as "Associate is not supported for ListMember".

I assume this plugin uses Associate/AssociateEntities Request all the way while listmember needs AddListMembers Request. 

Hope this enhancement/bug can be fixed soon.

![nnissue](https://cloud.githubusercontent.com/assets/16599309/12181967/5aaf4a20-b553-11e5-8362-5d24e614ee04.png)

**Comment by MscrmTools** [comment]
Hi, thanks for reporting this lack of feature

I can definitively work on it. Can't give any ETA

**Comment by MscrmTools** [comment]
Done! Please download latest pre release version if you don't want to wait for January official release

**Comment by Jay-ZhangJie** [comment]
Thanks, and this is a really quick fix.
