### ISSUE TITLE
port number 433 for SSL connection

### ISSUE THREAD

**Issue by blackphoenixinf** [MscrmTools/XrmToolBox#31]
Hi,

It seems that while using the SSL connection, port is defaulted to 433, it seems to be wrong.
Can you please confirm?

Thanks

**Comment by shytikov** [comment]
It seems [you're right](https://github.com/MscrmTools/XrmToolBox/blob/master/Connection%20Projects/McTools.Xrm.Connection.WinForms/ConnectionForm.cs#L381).

But maybe it applies only in some special cases?

Can you confirm that you cannot connect to organization via `https`?

**Comment by blackphoenixinf** [comment]
Yes, this is my case.
I got error:
"An error occured while retrieving organizations: Metadata contains a reference that cannot be resolved: 'DISCOVERY SERVICE URL'.
Inner Exception: Unable to connect to the remote server
Inner Exception: No connection could be made because the target machine actively refused it "IP" :433"
Which is correct, as https by default uses port 443.

**Comment by shytikov** [comment]
This looks like a typo. I created pull request #32, that fixes it.
