### ISSUE TITLE
Connect to CRM 2016 on-premises with IFD Deployment

### ISSUE THREAD

**Issue by zwheui** [MscrmTools/XrmToolBox#312]
I can connect with the url:
https://qbcrm2016dev.quesbook.com/
and internal
http://192.168.8.15:8008/QBCRM2016Dev
https://internalcrm.quesbook.com/qbcrm2016dev

but neither of them can be used to connect the xrmtoolbox

before I do the IFD, I can use connect to the xrmTool with http://192.168.8.15:8008/QBCRM2016Dev

Anther question, what's the home realm url? How can I get this url?

**Comment by zwheui** [comment]
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Discovery URI is = http://192.168.8.15:8008/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : DiscoverOrganizations - Initializing Discovery Server Object with http://192.168.8.15:8008/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - attempting to connect to CRM server @ http://192.168.8.15:8008/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: Microsoft.Xrm.Sdk
Method	: .ctor
Date	: 2016/1/14
Time	: 12:06:59
Error	: Data[0] = "The provided uri did not return any Service Endpoints!
{0}"
Data[1] = ""
Stack Trace	: 在 Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   在 Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   在 Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   在 Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   在 Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()

**Comment by zwheui** [comment]
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Discovery URI is = https://qbcrm2016dev.quesbook.com:443/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : DiscoverOrganizations - Initializing Discovery Server Object with https://qbcrm2016dev.quesbook.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - attempting to connect to CRM server @ https://qbcrm2016dev.quesbook.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - created CRM server proxy configuration for https://qbcrm2016dev.quesbook.com/XRMServices/2011/Discovery.svc - duration: 00:00:00.2519532
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - proxy requiring authentication type : Federation 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: Microsoft.Xrm.Sdk
Method	: GetIssuerEndpoint
Date	: 2016/1/14
Time	: 12:08:35
Error	: The authentication endpoint Username was not found on the configured Secure Token Service!
Stack Trace	: 在 Microsoft.Xrm.Sdk.Client.IssuerEndpointDictionary.GetIssuerEndpoint(TokenServiceCredentialType credentialType)
   在 Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   在 Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateFederationInternal(AuthenticationCredentials authenticationCredentials)
   在 Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   在 Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   在 Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   在 Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   在 Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()

**Comment by zwheui** [comment]
test account: crmtest01@quesbook.com
pass: 123456
this account only has sales person role, I'm not sure if it's enough for the test.
Or you need the administrator role?

**Comment by MscrmTools** [comment]
Thank you for all these information. 
I will try to find the right way to connect to this deployment and fix code if required.
I'm teaching a class today so maybe I will be able to work on it only tonight.

**Comment by MscrmTools** [comment]
Another test you can perform is using one of the official tool from the CRM 2016 SDK to check if you can connect to your deployment. 
If you can connect with these tools, then the problem is on XrmToolBox side. If not, the problem is on your deployment configuration

**Comment by MscrmTools** [comment]
I tested myself your information with the login tester tool included in the SDK and I can't succeed to connect to your deployment

**Comment by zwheui** [comment]
Thank you, I'm using the SDK to test too.

The error log is : The authentication endpoint Kerberos was not found on the configured Secure Token Service!

I'm finding the solution of it, do you have any idea about this?

**Comment by MscrmTools** [comment]
Unfortunately, I did not install yet IFD with CRM 2016 so I don't know...
Try to google the error message

**Comment by zwheui** [comment]
now, I can disable the IFD and Claim based. Then the connection will work.

Hope someone can find the error about the Kerberos problem.
