### ISSUE TITLE
Error to Run XrmToolBox.exe

### ISSUE THREAD

**Issue by khalidchaudhry** [MscrmTools/XrmToolBox#313]
I am trying to execute the executable but getting below error

Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Input string was not in a correct format.

**Comment by MscrmTools** [comment]
Can you please use the latest version?

**Comment by SigrunO** [comment]
I just downloaded v1.2015.2.21 and am getting the same error.

**Comment by MscrmTools** [comment]
Why people do not download the latest version???
Lastest version is 1.2015.12.20

**Comment by SigrunO** [comment]
if I hunt for xrmtoolbox 2015 on google I get sent to https://xrmtoolbox.codeplex.com/
click on downloads there and you get an old version. From there I thought it was the most current version! Why is the version there old?

**Comment by MscrmTools** [comment]
I don't know why google references this page...
CodePlex project homepage indicates the project is now on Github

Ok, I see, the download links leads to the first version on GitHub and not on the latest... sorry for that.

So, please go to www.xrmtoolbox.com to be sure having the latest version

**Comment by SigrunO** [comment]
Thanks for the better link - after you pointed out that I'm not getting the latest release I explicitly hunted for the correct version and found it. 

It's also good that the link on codeplex now points to the current release and not the first one.

**Comment by MscrmTools** [comment]
Can you validate latest version works for you?

**Comment by SigrunO** [comment]
It works better, but it has crashed 3 times so far. Unfortunately I don't have detailed information. I wanted to see if it happens again today, so I can give you more information. Is there a log file that provides information that would help you?

**Comment by MscrmTools** [comment]
If the problem occurs during tool launch, so I'm affraid there is no log associated...
Are you sure you unblock assemblies like mentioned in the [wiki](https://github.com/MscrmTools/XrmToolBox/wiki/Unblocking-downloaded-files)?

**Comment by SigrunO** [comment]
No, the problem does not occur during launch. It starts ok, I am able to modify settings in the sitemap. I have also saved changes, but then in the middle of changing some more it crashes.

I unblocked the zip file after download. This is definitely not an issue.

**Comment by MscrmTools** [comment]
Could it be the same as in this [issue](https://github.com/MscrmTools/XrmToolBox/issues/293)?
If so, next release will fix this issue.
In the meantime, please download the latest [prerelease](https://github.com/MscrmTools/XrmToolBox/releases/tag/XrmToolBox.prerelease_v1.2016.0121.90) that already contains the fix

**Comment by SigrunO** [comment]
Could be. I just had the exception again and it looks exactly like the last one on the page you are referring to. I will try the prerelease.

**Comment by MscrmTools** [comment]
Did you try it?

**Comment by SigrunO** [comment]
Yes, I finally had time to try the pre release and I haven't had the issue again. So it looks like it is fixed.

**Comment by MscrmTools** [comment]
good to know

**Comment by Aykutkonushbaev** [comment]
I've downloaded the latest version v.1.2016.8.23 and unblocked file. Then extracted and run XrmToolBox.exe. I'm having an error: 
![image](https://cloud.githubusercontent.com/assets/5517389/18507600/d7e8c598-7a92-11e6-90f6-e45e484dd3c0.png)

**Comment by rappen** [comment]
I have seen that on occasions.
Turns out that one connection was empty in the ID attribute in the connections file. Removing that entry made it possible to run XTB and recreate the connection.
