### ISSUE TITLE
Can't make a connection

### ISSUE THREAD

**Issue by 01jh2013** [MscrmTools/XrmToolBox#314]
I have multiple production instances of CRM Online. I can connect to one instance but not the other.  I am the administrator of both. The message I get is "Unable to Login to Dynamics CRM". I get this when I attempt to make the new connection.

**Comment by MscrmTools** [comment]
What is the version of the organization you cannot connect to? 
IS your Office 365 tenant federated with your local AD?

Moreover, to enable trace and get more information : [Enable tracing in XrmToolBox](https://github.com/MscrmTools/XrmToolBox/wiki/Enable-tracing-in-XrmToolBox)

**Comment by 01jh2013** [comment]
Current version: Microsoft Dynamics CRM Online 2015 Update 1 (May 2015) 
We use Active sync - It's the same user with the same roles set 

I don't have development tools to update the .exe file

**Comment by MscrmTools** [comment]
Tracing does not require to update exe file, but exe.config file which is a text file (XML actually).
Anyway, you are in the specific scenario with a known problem. Please review the page [Connecting to a Microsoft Dynamics CRM deployment](https://github.com/MscrmTools/XrmToolBox/wiki/Connecting-to-a-Microsoft-Dynamics-CRM-deployment) I just updated to indicates how to use a workaround (see Known issue paragraph)

**Comment by 01jh2013** [comment]
Using this method does connect – then I get the error below.

[cid:image001.png@01D15200.47658C10]

Then I get this error

[cid:image002.png@01D15200.47658C10]

**Comment by MscrmTools** [comment]
The images are not visible.
Please post them using the web interface and not answering through email

**Comment by 01jh2013** [comment]
[Uploading error.docx…]()
Here are the errors I get after successfully connecting to the instance

**Comment by MscrmTools** [comment]
The doc is not uploaded...

**Comment by 01jh2013** [comment]
[error.docx](https://github.com/MscrmTools/XrmToolBox/files/95924/error.docx)

**Comment by MscrmTools** [comment]
That would mean that your mscrmtools2011.config file contains connections without id... 
Can you try to delete (or move away) this file and try again?
Also, what is the version of XrmToolBox?

**Comment by 01jh2013** [comment]
Deleting the config file appears to have worked!  My version is 1.2015.12.20

**Comment by MscrmTools** [comment]
Ok, if it's ok for you , then can you close the issue?
