### ISSUE TITLE
Unable to create connection v1.2015.12.20

### ISSUE THREAD

**Issue by lukegri** [MscrmTools/XrmToolBox#315]
Unable to create connection to CRM Online version 7.2

Once entering credentials and trying to connect I get an error message "Unable to Login to CRM Dynamics". Credentials work fine to sign into web app.

See attached error log.
[XRMToolingLog.txt](https://github.com/MscrmTools/XrmToolBox/files/94628/XRMToolingLog.txt)

**Comment by MscrmTools** [comment]
I guess you are using Office 365 federated with your local AD, am I right? If so, please follow workaround mentioned by rappen in [this page](https://github.com/MscrmTools/XrmToolBox/issues/299)

**Comment by lukegri** [comment]
Connected. Thanks
