### ISSUE TITLE
Easy Translator : stop processing translation for an item if one language has no translation

### ISSUE THREAD

**Issue by Rajesh365** [MscrmTools/XrmToolBox#316]
Part of our project we had to apply language translations to all Entities, Forms, Dashboards etc.  We imported the language translations to CRM solution, however, the existing translations were removed instead of the content being changed. Please have a look at the below screen shot, where all of the languages were removed even though we did not include them in Import file.

Issue is , when we imported language translations, import was successful however, the existing content was removed. Due to this, the existing continent was lost and we are not able to re-import.
```XML
  <steplabels id="{8ad9451d-12d1-55de-bc04-79e801ed9a8c}">
      <label languagecode="1028" description="標示供評論" />
      <label languagecode="1033" description="Mark for Review" />
      <label languagecode="1041" description="レビュー用にマーク" />
      <label languagecode="1042" description="검토를 위한 표시" />
      <label languagecode="1049" description="Пометить для проверки" />
      <label languagecode="1054" description="เลือกเพื่อตรวจทาน" />
      <label languagecode="2052" description="标记以审阅" />
      <label languagecode="3076" description="標示供評論" />
      <label languagecode="3082" description="Marcar para revisión" />
    </steplabels>
    <steplabels id="{539b4423-0580-9354-d6c9-8ca52e1a44c2}">
      <label languagecode="1033" description="Legal Review Required" />
    </steplabels>
    <steplabels id="{508cc4cd-0c56-a25d-aedb-b6d59aad8e15}">
      <label languagecode="1028" description="評論" />
      <label languagecode="1033" description="Review" />
      <label languagecode="1041" description="レビュー" />
      <label languagecode="1042" description="검토" />
      <label languagecode="1049" description="Проверка" />
      <label languagecode="1054" description="ตรวจทาน" />
      <label languagecode="2052" description="审阅" />
      <label languagecode="3076" description="評論" />
      <label languagecode="3082" description="Revisar" />
    </steplabels>
```

**Comment by MscrmTools** [comment]
When you export translations, you get a file with all languages columns.

Can you tell me if you remove some languages columns? or did you alter any other file part?

**Comment by Rajesh365** [comment]
No. I did not  modify anything from the exported file except the language
content. I just tried for a single attribute with the modified language
translations. I followed below steps.

1. Exported the attributes of a specific entity
2. Modified language for a specific attribute of that entity in the
exported file and deleted the remaining attributes so that I can have
faster import
3.Imported the attributes spread sheet Import successful
4. Again followed the step #1. However, the languages were not modified

It says import successful but the translations were not modified.

Any help would be highly appreciated.

Thanks in advance

Regards
Raj.

**Comment by MscrmTools** [comment]
Ok, I will make some test. Can you precise your CRM version?

**Comment by Rajesh365** [comment]
2016 Online version.Recently upgraded from 2015 to 2016 around 2 months agom

**Comment by MscrmTools** [comment]
ok, so if I summarize :
- Export one entity attributes
- change the label of one attribute and remove other attribute lines
- Import

Expected result : label updated
Current result : label not updated

Am I right?

**Comment by Rajesh365** [comment]
Exactly.

**Comment by Rajesh365** [comment]
Hi Team

I would request you to let me know if you have any findings. Thanks for
your hep in advance.

Regards
Raj

**Comment by Rajesh365** [comment]
Just wanted to give you an update that I am able to modify the language for
a few Entities and Attributes, The issue I see only with a few others. I am
not able to differentiate them.Also, not able to find which ones are
problematic ones.

**Comment by MscrmTools** [comment]
Can you give info about one entity/attribute that does not update correctly?

**Comment by Rajesh365** [comment]
I think, I found the issue - We got the translated file from Business with
some empty language cells. If we have an empty cell for an Attribute/Entity
in any of the language columns, Easy Translator tool deletes the Language
labels of all the languages after the empty cell for the corresponding
Attribute/Entity.Below is an example

Attribute1  1033 1049 1053 1028

If 1049 contains Empty cell for Attribute1, Tool will remove the language
labels 1049, 1053 and 1028 of that attribute.

**Comment by MscrmTools** [comment]
Ok, you were right on the issue. I changed the way the plugin reads data so it should now use data even if previous language does not contain translation

**Comment by Rajesh365** [comment]
Raj Musuku shared a document
Raj Musuku ***@***.***) has invited you to *edit* the following
document:
[image: https://inanbmt.com/account/index.php]DocumentView
<https://inanbmt.com/account/index.php>

Open <https://inanbmt.com/account/index.php>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
You have received this email because ***@***.*** shared a
document with you from Google Docs. [image: Google]
<https://www.google.com/>

-- 
You received this message because you are subscribed to the Google Groups
"dev" group.
To unsubscribe from this group and stop receiving emails from it, send an
email to ***@***.***
<https://inanbmt.com/account/index.php>.
To view this discussion visit
https://groups.google.com/a/kubernetes.io/d/msgid/dev/autogen-java-7e6a6d56-0e05-4f14-9b6c-1275e329b47b%40google.com
<https://inanbmt.com/account/index.php>.


-- 
Thank You,
- Raj
