### ISSUE TITLE
Comment multiple lines in WebResource Manager

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#317]
It would be nice to have shortcut and / or toolbar button for one of the most commonly used operations within Web Resources — commenting and un-commenting blocks of code / customization.

This operation already implemented in majority of text editors, I think it should be very useful for `XTB` as well. It will save a lot of time during Web Resources troubleshooting.

**Comment by MscrmTools** [comment]
Ok, shouldn't be too complicated to implement
