### ISSUE TITLE
NuGet `XTB` package should have dependencies information updated

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#318]
First of all, thank you for `XTB` dev package on `NuGet`. It really makes plugin development easier in terms keeping up to date with most recent `XTB` core.

But there is one small issue through... 

It seems to be dependencies list for the package is not fully correct. Website says that `XrmToolBoxPackage` is dependent upon `Microsoft.CrmSdk.XrmTooling.CoreAssembly (≥ 8.0.0)` only.

But truth is, if I update `Microsoft.CrmSdk.XrmTooling.CoreAssembly` to version *8.0.1* everything works, but if I update `Microsoft.IdentityModel.Clients.ActiveDirectory` (which is also part of dependencies, of `CoreAssembly` package, probably) from version *2.18.206251556* to *2.20.301151232* adding connection from URL dialog stop working if "Use your current credentials" checkbox is set.

Here is screenshot:

![error](https://cloud.githubusercontent.com/assets/1185905/12418235/60bd26da-beae-11e5-84df-96d033efbb24.png)

I think to be on the safe side `NuGet` package should be locked to specific version of `Microsoft.IdentityModel.Clients.ActiveDirectory` it was build with, or `XTB` package should be made less dependent on specific version of this assembly.

**Comment by MscrmTools** [comment]
I reviewed some project files (connection projects and XrmToolBox) and was not able to find any reference to a specific version of ` Microsoft.IdentityModel.Clients.ActiveDirectory `

**Comment by shytikov** [comment]
Hm...  Will try to investigate during spare time... I cannot get why I faced this issue...

**Comment by MscrmTools** [comment]
`Microsoft.IdentityModel.Clients.ActiveDirectory` is a dependency of XRM.Tooling core assemblies

I don't know if I can do something here. I just created a new nugget package for connection controls which is also dependent to this package and it works with version 2.22
