### ISSUE TITLE
NuGet Package missing System.ComponentModel.Composition

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#320]
I'm creating a dummy local plugin for internal use, and I referenced the NuGet Package.  Looks like we need to add the "frameworkAssemblies" tag https://docs.nuget.org/create/nuspec-reference with the System.ComponentModel.Composition dll listed.  It was not automatically added as a project reference.

**Comment by MscrmTools** [comment]
Ok will add it
