### ISSUE TITLE
Error: Principle user missing prvReadUserQuery

### ISSUE THREAD

**Issue by lukegri** [MscrmTools/XrmToolBox#322]
![error](https://cloud.githubusercontent.com/assets/16762086/12484056/9fa2910e-c058-11e5-85da-6176c80962d6.jpg)
I am using v1.2015.7.31 of the tool with my office365 admin credentials and successfully connect to my organization, however when trying to Load Users and Settings I receive an error (see attached).

I have tried the newest version of the tool and find the same error. My office365 admin user is Sys.Admin and Sys.Customizer so has full permissions.

Any ideas?

**Comment by MscrmTools** [comment]
What plugin are you trying to use?

**Comment by lukegri** [comment]
User Settings Utility

Thanks for the reply.

**Comment by MscrmTools** [comment]
In this plugin, the code impersonates as the user. So it means that at least one user missed the privilege to read personal views (userquery).
Is there a reason why some (or all) users cannot read personal views?

**Comment by lukegri** [comment]
I have not intentionally prevented users from reading personal views. All users have either System Administrator security role, or a custom security role with the following:

![security role](https://cloud.githubusercontent.com/assets/16762086/12506566/38d8fbb4-c0f0-11e5-8188-da1ddae21dbb.jpg)

**Comment by lukegri** [comment]
Anyone?

**Comment by daryllabar** [comment]
The error you're getting is a user permission error with the user logging into CRM from within the Tool.  I'd check that the user that is logging in as an admin, if not, try an admin, that should resolve your issue.

**Comment by lukegri** [comment]
Thank you!!

**Comment by davidsickmiller** [comment]
I got this error when trying to access Dynamics with a user account that lacked a Dynamics license.
