### ISSUE TITLE
Edit connection leads inconsistent information in configuration file and interface

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#323]
New `Add connection` / `Edit connection` dialog corrupts configuration data.

For example, by adding this url first: `http://crm2013/Org1/`and than editing it to `http://crm2013/org2` leads to following configuration file:

```
<OriginalUrl>http://crm2013/org2</OriginalUrl>
<Organization>Org1</Organization>
<OrganizationUrlName>org2</OrganizationUrlName>
<OrganizationFriendlyName>Org1</OrganizationFriendlyName>
<OrganizationServiceUrl>http://crm2013/Org1/XRMServices/2011/Organization.svc</OrganizationServiceUrl>
<OrganizationDataServiceUrl>http://crm2013/ORG2/XRMServices/2011/OrganizationData.svc</OrganizationDataServiceUrl>
```

Despite `XTB` still connects to correct (second) organization, information about first organization is still present in the configuration file. This information is still visible on interface too, for example in connection list incorrect organization name (first) is still displayed.

In addition, seems to be `XTB` inconsistently puts urls into lower case (need to investigate further)

**Comment by MscrmTools** [comment]
This is specific to changing organization within the same deployment. This will be fixed in Connection Project
