### ISSUE TITLE
Separate connectivity tools to isolated NuGet package

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#325]
As we use ``McTools.Xrm.Connection`` plus sub assemblies for connectivity in various projects, having a separate package for those on NuGet would be great, to not have to include XTB assemblies to projects not requiring it.

**Comment by MscrmTools** [comment]
Possible, but would require to write some documentation on how to use them

**Comment by rappen** [comment]
Can't really find that documentation now, do you have a link so I can have a look?
Today I include XTB package, then remove all references I do not explicitly need, to keep my deployment package size/complexity down.

**Comment by MscrmTools** [comment]
No, that is the point, having separate package requires to write this documentation to explain how to use connection controls independently from XrmToolBox

**Comment by rappen** [comment]
Ah, got it.

**Comment by MscrmTools** [comment]
https://www.nuget.org/packages/MscrmTools.Xrm.Connection/

**Comment by MscrmTools** [comment]
Please open issue in the appropriate repository if needed : https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues

**Comment by garethfentimen** [comment]
Can we have old versions as well here? For people still on CRM 2015?

**Comment by garethfentimen** [comment]
I have put one up on Nuget a few weeks ago.

I would prefer there to be an official one

See: McTools.Xrm.Connection.2015

**Comment by MscrmTools** [comment]
This connection control works for CRM 2015 too...

**Comment by garethfentimen** [comment]
No it doesn't, you get a message saying that the version of the SDK that is
being targeted is version 8.0. CRM 2015 SDK is v7.

I may be mistaken but this was my experience.

**Comment by garethfentimen** [comment]
I guess the problem could have originated in
the McTools.Xrm.Connection.WinForms dll instead which I was also using

**Comment by MscrmTools** [comment]
I would be curious to see the exact message, since I'm able to use the current version of XrmToolBox with CRM 2011, 2013, 2015 and 2016, event if SDK used is v8

**Comment by MscrmTools** [comment]
This can require to put this XML code in app.config to redirect calls from older SDK to latest assemblies

```XML
 <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Sdk" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Deployment" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Crm.Sdk.Proxy" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

**Comment by MscrmTools** [comment]
This is what is done in XrmToolBox

**Comment by garethfentimen** [comment]
Ah thank you, I will give that a try.
