### ISSUE TITLE
Consider distributing most popular community tools together with XrmToolBox core

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#327]
I think it would be very nice to consider adding third-party plugins to main XTB package.

There are many great tools developed, but their existence is not very clear for user, since we don't have mechanism to search for all plugins available.

@MscrmTools do you think it could be feasible to add some tools developed by community as part of standard distribution? I'm specially implying on Early Bound Generator and FetchXML Builder, if @daryllabar or @rappen would not mind?

This thought came after I installed and set up XTB for several developers in the raw. First things you do after downloading core, you download these two plugins... So maybe?.. In terms of stability and quality they both look very good.

I believe it it would be done technically as git submodules, and legally clearly stated that all credits and support requests should be forwarded to respective authors.

Or maybe let's create packages site like:

* https://packagecontrol.io
* https://www.nuget.org/
* https://crates.io/
* https://www.npmjs.com/

**Comment by daryllabar** [comment]
I would love to make a plugin that allows for searching for and installing plugins.  I'm just a little lost as to how we ensure things are easily searchable, and ensure compatibility.

**Comment by MscrmTools** [comment]
If added to the main package, then it looks like it would be a manual task for me and I don't want to handle this (it takes already lot of time to prepare a XTB package)

I would prefer a way to get plugins directly from inside XrmToolBox.

**Comment by MscrmTools** [comment]
@daryllabar It shouldn't be a plugin but a feature of XTB

My question is : Where to store the plugins list so XTB is able to discover them and download them?

**Comment by rappen** [comment]
How about this:

* Instruct 3. party devs to upload their plugin packages to NuGet, assibling package names like "XrmToolBox.Plugins._myplugin_".
* Implement NuGet client (surely there must by some easily implemented API?) in XTB searching for packages matching the pattern.
* Either have a separate function/form to search for available plugins, or even include NuGet matches in the existing plugin list.
* If plugin is not installed, show Install button. If update to a plugin is available, show Update button. Uninstall should probably be available as well, even if you can still hide plugins from the list.

An extra check to investigate plugin compatibility (compiled with corresponding interfaces etc) would be even better.

**Comment by shytikov** [comment]
:+1: :heavy_multiplication_x: :100: :arrow_forward: :arrow_forward: :arrow_forward: :bomb:

**Comment by shytikov** [comment]
It suppose to mean "thumb up hundred times, result will be bomb"...

**Comment by daryllabar** [comment]
I'm not sure if there is an api, but you should be able to use the NuGet command line to download the dlls.

**Comment by shytikov** [comment]
I guess I have found something that should help us: http://matthamilton.net/nuget-for-plug-ins

**Comment by daryllabar** [comment]
That looks good!

**Comment by MscrmTools** [comment]
Working on this feature...
Questions:

1. What property should I use to detect XTB plugins on Nuget? It seems that Tag property might do the job. I would like to avoid using the Title property that could not contains the word "XrmToolBox"

2. The property should starts with "XrmToolBox." + your plugin/package name. Does it sound ok for you?

**Comment by daryllabar** [comment]
I'm not entirely knowledgeable in the world of NuGet, but it makes sense to use the Tag.  Maybe include a major version in it as well, referencing the version of the Xrm.Sdk?  That way we don't return plugins that are no longer up-to-date?

**Comment by MscrmTools** [comment]
Good remark! I'm not sure either how to really deal with "compatible" plugins

**Comment by MscrmTools** [comment]
Another remark : I would have liked to indicate when the plugins is already installed in XrmToolBox but I think when you use one assembly for multiple plugins, then I'm not able to detect if the package corresponds to already installed plugins

**Comment by daryllabar** [comment]
hmm... I would have a single Nuget Package that contains all the assemblies... does that make it easier?

**Comment by daryllabar** [comment]
If it's a huge deal, I can always ILMerge it...

**Comment by MscrmTools** [comment]
Hummm, I should have think before writing... I guess I just have to list assembly files in Plugins directory and compare it with files in packages...
I would need a real package to test...

**Comment by daryllabar** [comment]
Want me to create a NuGet Package?

**Comment by MscrmTools** [comment]
That would be great to test in real condition!
Only condition, the Tag has to start with "XrmToolBox."

**Comment by MscrmTools** [comment]
Here is a preview of the dialog.

![image](https://cloud.githubusercontent.com/assets/10774317/14284765/3f859880-fb49-11e5-9462-66774d94aa70.png)

I tested it with XTB nuget package which is not a plugin but it is just for testing purpose.
The dialog can (or should) detect not installed plugin, installed plugin with latest version and plugins to update.

remark : all files will need a version number. Keeping 1.0.0.0 will not work (I will complete the wiki with these information when the dialog is finished)

**Comment by daryllabar** [comment]
Done

**Comment by MscrmTools** [comment]
don't see it yet... I think I have to wait...

**Comment by MscrmTools** [comment]
Ok, I see it
Your package has no "Title" set so it does not render well in the list view
The package should have a version that equals file version in the package, so that I can check if this is an update or not
I'm not sure about how I should handle package dependencies since some of them already exists as XrmToolBox dependencies (like CRM SDK assemblies) and some other don't necessary exist. I think Nuget package for plugins shouldn't reference any dependencies but should contain all required files (except ones delivered with XTB)

thoughts?

**Comment by MscrmTools** [comment]
The source code is available in the branch "DEV", for those of you that want to test it right away.
I'm sure there is optimization to do but it should be quite functionnal

**Comment by daryllabar** [comment]
I will add a Title to the NuSpec, and remove all dependent NuGet Packages, and update the version to match the dll.  I probably won't get to it until tomorrow...

**Comment by MscrmTools** [comment]
no problem, I'm stopping development for today so no hurry

I'm just glad it seems to work quite effortless

**Comment by rappen** [comment]
This sounds too interresting not to try tonight....!
I will try to create an FXB package, and see what I can do about the dependency to CRMWinForm it contains...

**Comment by MscrmTools** [comment]
As the package is not a development package, just add all files necessary without any dependencies and your should be good.

Also note that I just handle files and not sub folders, I need to fix that!

**Comment by rappen** [comment]
Looks good!! :+1: 
![image](https://cloud.githubusercontent.com/assets/2572253/14294525/ec19f69a-fb71-11e5-91f8-a46ba6756a29.png)

However, selecting to install update I get this:
![image](https://cloud.githubusercontent.com/assets/2572253/14294470/a63765a4-fb71-11e5-8d59-f4f18c579e08.png)
*Cannot find part of the path C:\ProgramData\XrmToolBox\Plugins\Cinteros.Xrm.FetchXmlBuilder.1.2016.4.99\lib\net* (in Swedish at the top above)

For some reason the path is truncated in the middle of "net452".

My folder structure looks ok:
![image](https://cloud.githubusercontent.com/assets/2572253/14294490/cdfbf712-fb71-11e5-92b4-62adf3794c14.png)

**Comment by rappen** [comment]
Ah, found it. XTB code assumes assemblies will be in subfolder /lib/net/ in the nuget package.
Will see if I can extract actual subfolder from the package definition.

**Comment by MscrmTools** [comment]
Yes, I should have mentioned that the folder shouldn't be framework dependent because I won't know which version to take

**Comment by MscrmTools** [comment]
ok, ready for upcoming release
