### ISSUE TITLE
Reset Form function

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#328]
You know what would be a super function?

__Reset Form to default.__

Just like you can reset the sitemap.

So many times I have started editing a form, and just want to go back to standard layout in the current CRM version.
Or in upgrade scenarios, when a solution or org is upgraded, you want the default layout in the new version, and then add your custom fields.
Or when you realize that you want to deliver custom forms with your customizations and leave standard forms intact.

__Anyone up for the challenge?__ :-)

**Comment by shytikov** [comment]
It's impossible to achieve without backup of form definition... Thus we need to have in advance all definitions for all forms in all CRM versions... 

Through we can create our own visual from editor... And it would be epic!

**Comment by rappen** [comment]
Let's not get crazy here. Manipulating form definitions is not something you implement over the weekend...
The Sitemap Editor persists the default sitemaps for different versions, I guess this tool could persist form definitions in a similar way.

**Comment by shytikov** [comment]
What if I come up with plugin that will allow save form definitions directly from CRM, and update them directly afterwards?

So if person made backup in advance, he would be able to import it directly without import solution import.

**Comment by rappen** [comment]
Not really what I am looking for, but in some other scenario that might be useful.

**Comment by MscrmTools** [comment]
That would require to store all forms definitions... too much work here for me :)

If someone wants to create a plugin for that, he can do it
