### ISSUE TITLE
N:N import : cannot import CSV file if an attribute contains comma because quotes are not correctly managed

### ISSUE THREAD

**Issue by davidlb** [MscrmTools/XrmToolBox#329]
It would be useful to support attribute enclosed in quotes in case it contains a comma.

Example:
1234,"a,b"

Anyway, thanks for the very good job on XrmToolBox!

**Comment by MscrmTools** [comment]
Ok, I guess it can be done even if I'm surprised that linking value contains a comma

**Comment by davidlb** [comment]
Yeah, it's not common but I just have the case this morning where the field "name" had a comma :)

**Comment by MscrmTools** [comment]
Ok, I found a simple way to handle this problem. 
I just hope no one will come with a requirement to handle quote in data, because, it will require to add external libraries (like CSV helper) to deal with it
