### ISSUE TITLE
The Plugin Registration add-in causes XRMToolbox (v. 1.2016.1.30) to fail to load.

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#331]
I get an unhandled exception if the PluginRegistration.dll is in the XRMToolBox Plugins directory : 

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Xrm.Sdk, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Xrm.Sdk, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

If I remove the plugin registration DLL from the plugin folder it opens fine.

(I added an issue to their page, but thought you'd want to know.)

**Comment by shytikov** [comment]
I will take a look today!

**Comment by MscrmTools** [comment]
@mscottsewell can you confirm your xrmtoolbox.exe.config file looks like the same here : https://github.com/MscrmTools/XrmToolBox/blob/master/XrmToolBox/app.config

**Comment by mscottsewell** [comment]
I don't have an XRMToolBox.exe.config file in my directory - 
I have one in an older folder where I was debugging with you previously.
Should this file be distributed in the regular zipfile I downloaded?

**Comment by MscrmTools** [comment]
I guess it should be, yes...

**Comment by mscottsewell** [comment]
OK - If I copy the file into that folder, everything works. - Will you be adding the config file to the regular distribution?

**Comment by MscrmTools** [comment]
I will do so for next releases

**Comment by MscrmTools** [comment]
To do => Deliver the config file along with other files in release package

**Comment by bryce2071** [comment]
Hi, 

i have the same problem here.
I have a XrmToolBox.exe.config AND it is exacely the same like posted above.

But the error comes only on some plugins ... 
here for ex. in bulk workflow execution - tool.

any help?

THX, Gr. PeB

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.IO.FileNotFoundException: Die Datei oder Assembly "Microsoft.Xrm.Sdk, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
Dateiname: "Microsoft.Xrm.Sdk, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
   bei XrmToolBox___Bulk_Workflow_Execution.BulkWorkflowExecution.<getWorkflows>b__4(BackgroundWorker w, DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

WRN: Protokollierung der Assemblybindung ist AUS.
Sie können die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.
Hinweis: Die Protokollierung der Assemblybindungsfehler führt zu einer gewissen Leistungseinbuße.
Sie können dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.



************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
XrmToolBox
    Assembly-Version: 1.2016.5.27.
    Win32-Version: 1.2016.5.27.
    CodeBase: file:///D:/XrmToolBox/XrmToolBox.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
XrmToolBox.Extensibility
    Assembly-Version: 1.2016.5.27.
    Win32-Version: 1.2016.5.27.
    CodeBase: file:///D:/XrmToolBox/XrmToolBox.Extensibility.DLL.
----------------------------------------
Microsoft.IdentityModel
    Assembly-Version: 3.5.0.0.
    Win32-Version: 10.0.14342.1000.
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
McTools.Xrm.Connection
    Assembly-Version: 1.2016.5.27.
    Win32-Version: 1.2016.5.27.
    CodeBase: file:///D:/XrmToolBox/McTools.Xrm.Connection.DLL.
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly-Version: 1.2016.5.27.
    Win32-Version: 1.2016.5.27.
    CodeBase: file:///D:/XrmToolBox/McTools.Xrm.Connection.WinForms.DLL.
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly-Version: 8.0.0.0.
    Win32-Version: 8.1.0.383.
    CodeBase: file:///D:/XrmToolBox/Microsoft.Xrm.Sdk.DLL.
----------------------------------------
System.Xml.Linq
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.
----------------------------------------
System.ComponentModel.Composition
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll.
----------------------------------------
AndyPopkin.BulkWorkflowExecution
    Assembly-Version: 1.2016.5.17.
    Win32-Version: 1.2016.5.17.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/ANDYPOPKIN.BULKWORKFLOWEXECUTION.DLL.
----------------------------------------
Cinteros.Xrm.CRMWinForm
    Assembly-Version: 2016.4.12.6.
    Win32-Version: 2016.4.12.6.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.CRMWINFORM.DLL.
----------------------------------------
Cinteros.Xrm.FetchXmlBuilder
    Assembly-Version: 1.2016.5.109.
    Win32-Version: 1.2016.5.109.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.FETCHXMLBUILDER.DLL.
----------------------------------------
Cinteros.Xrm.Plugins
    Assembly-Version: 1.2016.5.34.
    Win32-Version: 1.2016.5.34.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.PLUGINS.DLL.
----------------------------------------
Cinteros.Xrm.XmlEditorUtils
    Assembly-Version: 1.2016.5.109.
    Win32-Version: 1.2016.5.109.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.XMLEDITORUTILS.DLL.
----------------------------------------
DamSim.SolutionTransferTool
    Assembly-Version: 1.2016.5.1.
    Win32-Version: 1.2016.5.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL.
----------------------------------------
DamSim.ViewTransferTool
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL.
----------------------------------------
DLaB.AttributeManager
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.ATTRIBUTEMANAGER.DLL.
----------------------------------------
DLaB.Common
    Assembly-Version: 1.0.1.9.
    Win32-Version: 1.0.1.9.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.COMMON.DLL.
----------------------------------------
DLaB.EarlyBoundGenerator
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.EARLYBOUNDGENERATOR.DLL.
----------------------------------------
DLaB.Xrm.2016
    Assembly-Version: 1.1.7.1.
    Win32-Version: 1.1.7.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.XRM.2016.DLL.
----------------------------------------
DLaB.Xrm.Entities
    Assembly-Version: 8.0.1.0.
    Win32-Version: 8.0.1.0.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.XRM.ENTITIES.DLL.
----------------------------------------
DLaB.XrmToolboxCommon
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.XRMTOOLBOXCOMMON.DLL.
----------------------------------------
EPPlus
    Assembly-Version: 4.0.5.0.
    Win32-Version: 4.0.5.0.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/EPPLUS.DLL.
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL.
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly-Version: 1.2016.5.3.
    Win32-Version: 1.2016.5.3.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL.
----------------------------------------
MsCrmTools.AccessChecker
    Assembly-Version: 1.2016.5.1.
    Win32-Version: 1.2016.5.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL.
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly-Version: 1.2016.5.1.
    Win32-Version: 1.2016.5.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL.
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL.
----------------------------------------
MsCrmTools.AuditCenter
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL.
----------------------------------------
MsCrmTools.ChartManager
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL.
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly-Version: 1.2016.5.1.
    Win32-Version: 1.2016.5.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL.
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL.
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL.
----------------------------------------
MsCrmTools.FormRelated
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL.
----------------------------------------
MsCrmTools.Iconator
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL.
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL.
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL.
----------------------------------------
MsCrmTools.SampleTool
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL.
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL.
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL.
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL.
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly-Version: 1.2016.5.2.
    Win32-Version: 1.2016.5.2.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL.
----------------------------------------
MsCrmTools.SolutionImport
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL.
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL.
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL.
----------------------------------------
MsCrmTools.Translator
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL.
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL.
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL.
----------------------------------------
MsCrmTools.WebResourcesManager
    Assembly-Version: 1.2016.5.2.
    Win32-Version: 1.2016.5.2.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL.
----------------------------------------
Ryr.ExcelExport
    Assembly-Version: 2.3.0.0.
    Win32-Version: 2.3.0.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/RYR.EXCELEXPORT.DLL.
----------------------------------------
Ryr.SolutionHistory
    Assembly-Version: 2.2.0.0.
    Win32-Version: 2.2.0.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/RYR.SOLUTIONHISTORY.DLL.
----------------------------------------
Ryr.XrmToolBox.EntityImageUpdater
    Assembly-Version: 2.2.0.0.
    Win32-Version: 2.2.0.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/RYR.XRMTOOLBOX.ENTITYIMAGEUPDATER.DLL.
----------------------------------------
System.Net.Http
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll.
----------------------------------------
System.Runtime.Serialization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
----------------------------------------
System.Design
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll.
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly-Version: 8.0.0.0.
    Win32-Version: 8.1.0.359.
    CodeBase: file:///D:/XrmToolBox/Microsoft.Crm.Sdk.Proxy.DLL.
----------------------------------------
MetadataViewProxies_4b672e5f-d0bb-4a4f-bf54-7fa6eeed3aec
    Assembly-Version: 0.0.0.0.
    Win32-Version: 4.6.1569.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll.
----------------------------------------
NuGet.Core
    Assembly-Version: 2.11.1.812.
    Win32-Version: 2.11.1.812.
    CodeBase: file:///D:/XrmToolBox/NuGet.Core.DLL.
----------------------------------------
System.Web.Extensions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll.
----------------------------------------
System.Web
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll.
----------------------------------------
WindowsBase
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll.
----------------------------------------
System.Data.Services.Client
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Services.Client/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Services.Client.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly-Version: 2.1.0.0.
    Win32-Version: 2.1.0.556.
    CodeBase: file:///D:/XrmToolBox/Microsoft.Xrm.Tooling.Connector.DLL.
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly-Version: 2.24.0.0.
    Win32-Version: 2.24.30411.1323.
    CodeBase: file:///D:/XrmToolBox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL.
----------------------------------------
System.ServiceModel
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll.
----------------------------------------
System.Web.Services
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll.
----------------------------------------
SMDiagnostics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll.
----------------------------------------
System.ServiceModel.Internals
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll.
----------------------------------------
System.Xaml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll.
----------------------------------------
System.ServiceModel.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.ServiceModel.resources.dll.
----------------------------------------
System.xml.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Xml.resources.dll.
----------------------------------------
System.ServiceModel.Channels
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll.
----------------------------------------
System.IdentityModel
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.IdentityModel.Selectors
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel.Selectors/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.Selectors.dll.
----------------------------------------
System.RunTime.Serialization.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1569.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Runtime.Serialization.resources.dll.
----------------------------------------

**Comment by MscrmTools** [comment]
This is caused by old plugins that not have been updated...

I know that BulkWorkflowTool has an update coming soon
