### ISSUE TITLE
When connectiono created, icon for it in status bar drop-down list is missing

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#334]
Right after creation of connection icon for it is missing in status bar drop-down list is missing. Here is an illustration (red rectangle in place of missing icon):

![missing_icon](https://cloud.githubusercontent.com/assets/1185905/12779502/98601cb2-ca68-11e5-8079-1e3829dfbdb9.png)

After `XTB` restart icon is on place.

**Comment by MscrmTools** [comment]
Moved in Connection controls project : [Issue 1](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/1)
