### ISSUE TITLE
NuGet Package XrmToolBoxPackage.1.2016.1.30 is invalid

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#335]
Looks like XrmToolBox.Extensibility  references McToolsXrm.Connection 1.2016.1.30, but the Nuget version is only 1.2016.1.29.

**Comment by MscrmTools** [comment]
Package 1.2016.1.30 published
Tell me if it works better

**Comment by daryllabar** [comment]
Works 100% correct now.  Thanks!
