### ISSUE TITLE
Please support 2 factor authentication

### ISSUE THREAD

**Issue by bsampath84** [MscrmTools/XrmToolBox#337]
This is an enhancement request. Please support 2 factor  authentication for CRM 2015 online.

**Comment by MscrmTools** [comment]
This is something I really want to implement but I do not have a deployment to test and debug against.
So it might take time before I implement this feature

**Comment by MscrmTools** [comment]
Hi, Good news!
I succeeded to implement some code to support MFA.
It still requires time to implement it completely in XrmToolBox but I can tell that it should arrive soon (next release or the one after, if everything goes well)
It will also requires that each company that wants to use XrmToolBox with MFA configure its Azure Active Directory to register XrmToolBox application before being able to use it

**Comment by rodarius** [comment]
Whats the appID and Uri to register XrmTools with AzureAD?

**Comment by MscrmTools** [comment]
You will have to register a "generic" app yourself in your azure ad and provide appid and redirecturi in the connection string to connect in CRM.

**Comment by MscrmTools** [comment]
More precision: the appid will be auto generated in your generic app. The redirecturi can be anything

**Comment by rodarius** [comment]
I added the application to the AzureAD and granted it logon rights to the CRM.

Im using this :

new CrmServiceClient("AuthType=OAuth;Username=chrisa@fhaas02.onmicrosoft.com; Password=whatever;Url=https://fhaas02.crm4.dynamics.com;AppId=3e8c56b2-b831-41f9-b9b2-ca7a9af6552c;RedirectUri=http://www.xrmtoolbox.com;TokenCacheStorePath=c:\\temp;LoginPrompt=Always")

The whole thing only sits there and does nothing at all, never comes back from the constructor. 

Any hints, what am i doing wrong?

**Comment by MscrmTools** [comment]
Yes, I found out that when using MFA, you must not include username and password in the connection string, certainly a bug in Microsoft assembly

**Comment by rodarius** [comment]
"AuthType=OAuth;Url=https://fhaas02.crm4.dynamics.com;AppId=3e8c56b2-b831-41f9-b9b2-ca7a9af6552c;RedirectUri=http://www.xrmtoolbox.com;TokenCacheStorePath=c:\\temp;LoginPrompt=Always" 

doesnt do anything either :(   (Alos leaving Username=;Password=; in doesnt help)

What is it actually supposed to do? Popup anything, or just go on and connect?

IM getting a feeling, that MFA is trying to drive me crazy

It seems to be stuck here
Microsoft.Xrm.Tooling.Connector.dll!Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindAuthorityAndResource

**Comment by MscrmTools** [comment]
it should pop up a window...
I figured out that CacheStorePath has to be a file path, so in your case : c:\temp\XrmToolBoxOauthCache.bin

(note, the file name and extension can be anything and no need of double back slash)

**Comment by MscrmTools** [comment]
filename : anything with an extisting folder

**Comment by rodarius** [comment]
Thnx a ton, I got it working now. Not the best documented piece of code, that microsoft threw at us yet :)

**Comment by MscrmTools** [comment]
Glad to hear it's working for you!

Also just discovered that I could share an AppId and a RedirectUrl for XrmToolBox but I don't have an Azure tenant for which I'm sure it will stand "forever"... Maybe I would need to explain how to create your own Azure AD app, and propose generic AppId and RedirectUrl mentionning it could not be usable at anytime

**Comment by rodarius** [comment]
Are you going to support the App Password thingie? So far I cannot logon using the app password created via the azure Portal (I treid myself and while i got the MFA with actual 2 Factor up and running now, the App Password is still killing me)

**Comment by MscrmTools** [comment]
It's no more about "Am I going to support...". 
I have implemented the possibility to use connection string which is directly used by Microsoft connection assemblies. If Microsoft support it (I don't have the answer), then XrmToolBox will support it

**Comment by rodarius** [comment]
Thank, ill see if I can get a working connection string for that. If I find one, Ill share it
