### ISSUE TITLE
Web Resource Manager: Select/Unselect all not working

### ISSUE THREAD

**Issue by raphaelmoser** [MscrmTools/XrmToolBox#338]
Since v. 1.2016.1.30 the "Select/Unselect all" Checkbox in the Web Resource Manager stopped working for me. None of the loaded resources gets selected.
Saving checked Web resources with roots then saves every loaded resource to disk anyway.
Saving checked Web resources to disk does nothing.

**Comment by raphaelmoser** [comment]
Check/uncheck all works again, thanks!

**Comment by MscrmTools** [comment]
You're welcome!
