### ISSUE TITLE
Connecting to O365 organization seems to take much longer now with the GitHub version, 1.2015.2.21 than it did with the last previous version I had from CodePlex.

### ISSUE THREAD

**Issue by crexin** [MscrmTools/XrmToolBox#34]
Connecting to O365 organization seems to take much longer now with the GitHub version, 1.2015.2.21 than it did with the last previous version I had from CodePlex.  It's possible it may have something to do with the organization, but I had just connected earlier today to the same organization with the Older XRMToolbox version and didn't have any delay in connecting to the organization.  Now it's taking upwards of 30 seconds to minutes to finish connecting.

**Comment by MscrmTools** [comment]
Nothing has changed in the connection process so far... I know there is a bug with the wrong port for ssl (433 instead of 443) but it shouldn't connect at all if you were facing this bug.

**Comment by MscrmTools** [comment]
What previous version did you use when connecting more quickly? Is that a version before using CRM 2015 SDK assemblies?

**Comment by mcross9095** [comment]
I'm having a problem with the new version, too. I previously used a recent version from 2014. With the new version 1.2015.2.21, try to connect to a CRM 2013 Online instance times out. I'm able to log into the CRM organization without a problem.

**Comment by MscrmTools** [comment]
I don't understand... it times out but you can connect?

You should have the port 433 error if you are using the latest version.

I'm ready to ship a new version so if you can confirm the port is the problem, I will be able to ship it.

**Comment by mcross9095** [comment]
When connecting to CRM ONLINE, there is no 433 error, it just times out. I was able to connect to an IFD instance hosted in our private cloud by changing the 433 to 443.

**Comment by crexin** [comment]
Sorry for the delayed response as I've been busy the last few weeks.  Something did get updated and I've able to connect without issue to the CRM Online organizations with build version v1.2015.3.10.  So for me, I'm happy with it.  :)
