### ISSUE TITLE
Iconator - change background colour 

### ISSUE THREAD

**Issue by ewenstewart** [MscrmTools/XrmToolBox#342]
with the new 'white' on 'clear' icons - it would be good if the background colour for the icons could be a colour other than white  - currently all I see is white on white icons :-)

**Comment by ewenstewart** [comment]
ps - I currently get round this by setting the PC to display high contrast

**Comment by MscrmTools** [comment]
Here is the implementation
![image](https://cloud.githubusercontent.com/assets/10774317/13315631/1df1c282-dbac-11e5-95f0-f94705a3f1dd.png)
