### ISSUE TITLE
Allow to sort/filter/copy the grid results in Metadata Viewer

### ISSUE THREAD

**Issue by sarjanwebdev** [MscrmTools/XrmToolBox#343]
This will help a lot in code generation and documentation.

**Comment by daryllabar** [comment]
What do you mean by "code generation"?

**Comment by MscrmTools** [comment]
Sort => already available
Filter => you can filter entities or attributes by logical or display name already. More will be to complicated to implement
Copy => I could work on that

**Comment by sarjanwebdev** [comment]
If you want to generate few lines together e.g update all 30+ date fields
in an entity for timezone then you can generate code by text manipulation
instead of using intellisense each line. For that you need to be able to
list all field schema names. One column only.

**Comment by MscrmTools** [comment]
Why not using MetadataDocumentGenerator plugins to extract all these fields?

I close the issue as this is a workaround.

Please reopen the issue if you have more to say about this
