### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by gunntest** [MscrmTools/XrmToolBox#344]
Hi,

I have installed this version XrmToolBox v 1.2016.1.30 but I receive this message.

How can I solve this?

grt
Elio tagliola

**Comment by shytikov** [comment]
Can you provide more info? Like which plugin are you using, which actions you're performing, in which order, some connection details (type of CRM installation, version) and information about your operating system.

**Comment by rappen** [comment]
I would suspect having a look at the by now pretty long thread #299 could help you solve this problem.
Error message is probably due to an error in the error handling, which would otherwise display something like "Unable to login" for which you might find a solution in #299.
That is my bet :)

**Comment by MscrmTools** [comment]
I close this issue since the explanation by @rappen should fix the problem
