### ISSUE TITLE
Cannot connect to previously configured orgs

### ISSUE THREAD

**Issue by bowens11** [MscrmTools/XrmToolBox#345]
I cannot connect to previously configured organizations. They worked previously but in the last two weeks I am receiving this error when try to connect to any org.

![image](https://cloud.githubusercontent.com/assets/17439625/13268080/69bec7c8-da4e-11e5-9c13-8648df966e21.png)

**Comment by MscrmTools** [comment]
This error message is totally unknown to me... Are you sure nothing changed with authentication for you organizations (like enabling Azure AD, setting IFD, or thing like that)?

**Comment by bowens11** [comment]
Issue resolved.

We use single sign-on and force password updates every 90 days. Just had to clear the config file and reload the orgs with the new passwords. 

Thanks.
