### ISSUE TITLE
Web Resource Manager: Save checked Web resources (with roots) to disk

### ISSUE THREAD

**Issue by raphaelmoser** [MscrmTools/XrmToolBox#349]
Hi

When I use "Save checked Web resources (with roots) to disk", the selection of files that I have made is not considered. Every Web resource that was fetched from the server is saved. 

In this example, i've loaded all html files from crm, selected only one tree and had all the files saved anyway:
![image](https://cloud.githubusercontent.com/assets/625151/13395796/4db326f8-def1-11e5-88a3-ea92aea0308a.png)

When I use "Save checked Web resources to disk", then the selection works.

This has been like that for a couple of versions. I don't know if that's an bug or I don't understand the feature fully? I was expecting that only selected files or trees with at least on selected file would be exported.

Kind regards

**Comment by MscrmTools** [comment]
Stupid bug... easy to fix... will do immediatly

**Comment by raphaelmoser** [comment]
Thanks again! =)
