### ISSUE TITLE
Assembly Recovery Tool Load assemblies right after loading plugin itself

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#35]
Hi,

What do you think about changing default behavior of Assembly Recovery Tool during load?

Right now, after loading plugin user should press `Load assemblies` button to get list of assemblies, while this extra click does not make sense, if valid connection is present in `XTB` it's logical just load list of assemblies automatically. 

`Load assemblies` button should be renamed in `Reload assemblies` button then.

What do you think? Is this valid point?

**Comment by MscrmTools** [comment]
Good point

I know it's an extra click but my initial thought was that a user does not necessarily know what the tool is. So, first time he opens it, maybe he doesn't want to initiate the process before seeing what the tool looks like

**Comment by rappen** [comment]
The same goes for `Load entities` in numerous plugins, `Load sitemap` in Sitemap Editor etc...
