### ISSUE TITLE
Error "Invalid Xml: SiteMap Xml root must be SiteMap!" for valid SiteMap.xml file.

### ISSUE THREAD

**Issue by eliotstock** [MscrmTools/XrmToolBox#351]
![wrmtoolbox_sitemap](https://cloud.githubusercontent.com/assets/1144814/13501762/cb6241ae-e15f-11e5-8745-42bafda5b76e.png)

[SiteMap.xml.txt](https://github.com/MscrmTools/XrmToolBox/files/157223/SiteMap.xml.txt)

**Comment by MscrmTools** [comment]
Can you explain the steps to get this error?

**Comment by eliotstock** [comment]
Open SiteMap Editor, Open SiteMap.

**Comment by MscrmTools** [comment]
I don't know why but your sitemap xml file has one "SiteMap" root node that should be removed in order to open correctly

**Comment by eliotstock** [comment]
Yeah, that's valid, at least for a sitemap that's come from an unmanaged solution:

```
<SiteMap>
  <SiteMap IntroducedVersion="7.0.0.0">
 ...
```

**Comment by MscrmTools** [comment]
Ok, the point is "Open SiteMap" feature is designed to open XML produced by SiteMapEditor, not from a solution export. 
So, just remove the first "SiteMap" root node and you should be good to go

**Comment by MscrmTools** [comment]
I close this issue
If you feel it shouldn't be closed, please tell me
