### ISSUE TITLE
Windows Identity Foundation error on run

### ISSUE THREAD

**Issue by DebSil** [MscrmTools/XrmToolBox#352]
Each time I try to run XRMTOOLBOX.EXE I get the error:

Unable to find Windows Identity Foundation 3.5 ....

I am running Windows 7 Professional with SP 1 and Windows Identity Foundation already installed.

**Comment by rappen** [comment]
See prereqs info in the wiki: https://github.com/MscrmTools/XrmToolBox/wiki/Software-prerequisites

**Comment by MscrmTools** [comment]
This is the code that fails and means WIF seems to be not installed
```C#
 Assembly.Load("Microsoft.IdentityModel, Version=3.5.0.0, Culture=neutral, publicKeyToken=31BF3856AD364E35");
```

**Comment by DebSil** [comment]
But when I try to run the install, the install tells me WIF is already installed.

**Comment by MscrmTools** [comment]
What do you mean by installing WIF? WIF is a feature that should be activated, not installed so I'm wondering if what you are trying to install is effectively what is required
