### ISSUE TITLE
Service is null in Custom Plugin

### ISSUE THREAD

**Issue by thambirm** [MscrmTools/XrmToolBox#356]
Hi , I am working custom plugin for XRMToolBox . In the class inherit from "PluginControlBase" , "service" property is null even though "XRM ToolBox" connected to CRM Online . Even 'Sample Tool" is also not working correctly . other plugins are working correctly . I have just followed the steps mentioned in wiki to create plugin . Did i miss any steps ?

**Comment by daryllabar** [comment]
Are you making an async call before you access the Service?

**Comment by MscrmTools** [comment]
No feedback since more a month, I close the issue. Do not hesitate to reopen it if you want to provide more information
