### ISSUE TITLE
Typo in interface name

### ISSUE THREAD

**Issue by macacq** [MscrmTools/XrmToolBox#357]
Hi.

Implementing sending messages to status I've noticed strange spelling of interface `IStatusBarMessager`. My humble opinion, the name should be `IStatusBarMessenger`, through, I just a country boy with no high school education at all.

Anyway, it seems to be it is used only in sample plugin (where it is actually not working at all), and I also haven't seen that it is used in third-party plugins, so maybe it's still possible to give correct spelling to the interface?

Or it was done for purpose?

Thanks in any case for any information!

**Comment by MscrmTools** [comment]
The naming comes from this [issue](https://github.com/MscrmTools/XrmToolBox/issues/90) 
Tell me if it really needs to be updated

**Comment by daryllabar** [comment]
Wow... @macacq is  right.

**Comment by MscrmTools** [comment]
Ok, I will create a new interface and mark the existing one as obsolete
