### ISSUE TITLE
Very strange code in SampleTool

### ISSUE THREAD

**Issue by macacq** [MscrmTools/XrmToolBox#358]
Sample tool has following code:

```
public void ProcessWhoAmI()
{
    WorkAsync(new WorkAsyncInfo
    {
        Message = "Retrieving your user id...",
        Work = (w, e) =>
        {
            while (e.Cancel == false)
            {
                if (w.CancellationPending)
                {
                    e.Cancel = true;
                }
                var request = new WhoAmIRequest();
                var response = (WhoAmIResponse)Service.Execute(request);

                e.Result = response.UserId;
            }
        },
        ProgressChanged = e =>
        {
            // If progress has to be notified to user, use the following method:
            //SetWorkingMessage("Message to display");

            // If progress has to be notified to user, through the
            // status bar, use the following method
            if (SendMessageToStatusBar != null)
                SendMessageToStatusBar(this, new StatusBarMessageEventArgs(50, "progress at 50%"));
        },
        PostWorkCallBack = e =>
        {
            if (!e.Cancelled)
            {
                MessageBox.Show(string.Format("You are {0}", (Guid)e.Result));
            }
        },
        AsyncArgument = null,
        IsCancelable = true,
        MessageWidth = 340,
        MessageHeight = 150
    });
}
```

I looked at this code during implementation of communication with `StatusBar`. As I mentioned in #357, code was not helpful... Unfortunately. 

I have following questions so far:

* Why we have (almost) infinite `while` loop in the `Work` delegate? For spamming CRM with `WhoAmI` requests?
* `ProgressChanged` delegate is not fired... Why? Is there an example, how to notify about progress change?

Thanks!

**Comment by daryllabar** [comment]
Your first bullet point does appear to be an infinit-ish loop, but as to your second point, the ProgressChanged method is only triggered when [w.ReportProgress](https://msdn.microsoft.com/en-us/library/a3zbdb1t(v=vs.110).aspx) is called.  The Progress Changed will operate on the main UI thread, while the Work method is on a separate thread.

**Comment by MscrmTools** [comment]
The "infinite loop" was just to illustrate Cancelation capabilities of background worker

**Comment by daryllabar** [comment]
Maybe a comment should added to make it more explicit?

**Comment by MscrmTools** [comment]
Absolutely, I will do it
