### ISSUE TITLE
Metadata Document Generator - Automatic/implicit intersect entities not included

### ISSUE THREAD

**Issue by cint-mats** [MscrmTools/XrmToolBox#359]
When extracting the metadata, you can select the implicit intersect entities that CRM automatically creates for N:N-relations in the entities list. However, they don't get extracted to the Excel file.

This has stopped working between versions 1.2015.11.5 and 1.2106.2.28. The organization I'm connecting to is on a CRM 2016 on-prem server, so this could be a CRM 2016 issue too.

**Comment by cint-mats** [comment]
Works in 1.2015.12.20 connecting to CRM 2016 on-prem.

**Comment by macacq** [comment]
Here is suspicious commit https://github.com/MscrmTools/XrmToolBox/commit/e2fe860f9da9e4394d27cc73e644df6a39bb34e1#diff-7ca9ed6aaa12a690fa087baa9c1d0fb1

Haven't investigated deeply, but this is only not maintenance commit from long time ago. If I'm right [v.1.2016.1.30](https://github.com/MscrmTools/XrmToolBox/releases/tag/v.1.2016.1.30 ) release should work ok.

**Comment by cint-mats** [comment]
It works with 1.2016.1.30.

Not being totally fluent in C# and this codebase, I suspect row 436: 
`if (emdDisplayNameLabel != null)`
In previous version, the sheet was always created. Since CRM creates these entities automatically, they don't have a localized name. 

Maybe add some NULL handling when setting the name in line 434, or in the emd.DisplayName.LocalizedLabels.FirstOrDefault function?

**Comment by cint-mats** [comment]
Code change has been merged. I concider this issue resolved.
