### ISSUE TITLE
Assembly Recovery Tool unable to find method exception

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#36]
There one scenario, that forces Assembly Recovery Tool to fire exception. Please follow this steps:

* Open XrmToolBox (`XTB`), do not connect to any organization;
* Choose Assembly Recovery Tool (`ART`) from the list, do not connect to any organization even if plugin insists;
* In `ART` that successfully loaded press `Load assemblies` button;
* In list of organization choose **ANY** organization;
* Exception raised `Unable to find method MainControl.RetrieveAssemblies` in `PluginBase` class;

**Comment by MscrmTools** [comment]
Argh... RetrieveAssemblies must be set as public to avoid this bug!

Can you handle this when you update the tool?

**Comment by shytikov** [comment]
Sure, no problem!

**Comment by shytikov** [comment]
Sure, no problem. Task for a second.
