### ISSUE TITLE
Console.test - Inconsistencies in assemblies

### ISSUE THREAD

**Issue by davidlb** [MscrmTools/XrmToolBox#362]
Console.test still use Microsoft.Xrm.Client assemblies but it have removed from SDK 2016. I don't get the purpose of Console.test but I see 3 solutions:
- update packages.config to rely on SDK 2015 dependencies (I can submit a pull request)
- update Console.test to use SDK 2016 assemblies
- remove Console.test from the project it's useless now :)

**Comment by MscrmTools** [comment]
I just use it for my internal test... I know it shouldn't be in the source controler...

**Comment by MscrmTools** [comment]
I will remove the project from the solution
