### ISSUE TITLE
View Transfer Tool : Teams taken into account?

### ISSUE THREAD

**Issue by jweresch** [MscrmTools/XrmToolBox#365]
Just wondering if this takes into account that a team can own a personal view?  I'm getting an error that system user doesn't exist when trying to transfer.  GUIDs are sync'd up, but its a team that owns the view not a systemuser

**Comment by MscrmTools** [comment]
I'm quite sure team are not handled today, but we should be able to implement this feature

**Comment by MscrmTools** [comment]
This is included in latest version of this plugin available on the Plugins Store
