### ISSUE TITLE
SiteMap Editor doesn't allow maintenance of Privilege entity within a subarea

### ISSUE THREAD

**Issue by paulboiano** [MscrmTools/XrmToolBox#370]
In looking at an older article it looks like the "Add a Privilege" was doable via the Sitemap editor in the past. In using the view xml button for a sitemap component I can see the Privilege spec within a subarea but I can't modify it or remove it. Is that functionality available in Sitemap editor? Or do we go with the old manual customization of XML method via solution?

Thanks,
Paul

**Comment by MscrmTools** [comment]
That should work... I will check it tomorrow

**Comment by MscrmTools** [comment]
I just checked and was able to :
- Load a sitemap without privilege
- Add privilege to a SubArea
- Update the sitemap
- Load again the site map => the privilege is visible

Can you elaborate more on what is not working on your side? what is the version of SiteMapEditor you are using?

**Comment by MscrmTools** [comment]
@paulboiano can you update this issue or I will close it

**Comment by MscrmTools** [comment]
I close this issue. 
If you have more information for me, please reopen the issue and complete it
