### ISSUE TITLE
Unable to connect to a Microsoft Dynamics CRM 2016 On premise

### ISSUE THREAD

**Issue by whcervecero** [MscrmTools/XrmToolBox#375]
Hello,

I just tried to connect the XRM toolbox to a CRM 2016 on premise and I receive a message "Unable to Login to Dynamics CRM".
Is there a connection problem with on-premises systems?
Someone could explain to me what is the information to indicate in the New Connection popup window?
Thanks a lot.

**Comment by MscrmTools** [comment]
There shouldn't be problem to connect to OnPremise environment.
If using IFD, I guess something does not work as expected.
Can you elaborate on how you try to connect?

**Comment by winton31** [comment]
Same for me with 2015 on prem using IFD.  I was able to connect with a previous version of the XRM toolbox..

**Comment by MscrmTools** [comment]
Please use the latest version and the connection string option to connect

**Comment by vppetrov** [comment]
Doesn't work for me either. With normal connection parameters (worked with previous version of XrmToolBox) I get the "Unable to login to Dynamics CRM". With connection string (which works from my application) I get "Organization cannot be null or empty. Parameter name: Organization Name". here is the string I am using: Url=https://orgname.server.com; Username=user@server.com; Password=mypass;

**Comment by MscrmTools** [comment]
Please review the MSDN page for connection string.
You need to add a AuthType key
If using IFD, please try to add the domain in the username key (domain\username)
If using IFD, you still need to add the organization at the end of the url (https://orgname.server.com/orgname)

**Comment by vppetrov** [comment]
None of these works. The same connection string works without a problem from a .net application.

**Comment by vppetrov** [comment]
By the way, version 1.2015.7.31 successfully connects with these properties:
- Use IFD: yes
- Server: https://orgname.server.com
- Server Port: 443
- Home realm url: empty
- Domain: empty
- Login: user@server.com
- Password: mypass

**Comment by MscrmTools** [comment]
When using a connection string, XrmToolBox does not alter it. It just pass it to the new CRM SDK connection assemblies to perform the connection.
When you talk about a .NEt application, which connection assembly is used? Microsoft.Xrm.Client.dll or Microsoft.Xrm.Tooling.Connector.dll?

**Comment by vppetrov** [comment]
It's Microsoft.Xrm.Client.dll but it's an older version: 7.0.0.0

**Comment by MscrmTools** [comment]
Ok, so Microsoft.Xrm.Client.dll is deprecated and does not support lot of authentication mechanism (Oauth, MFA, etc). This is why Microsoft provides a new assembly Microsoft.Xrm.Tooling.Connector.dll that is used by latest version of XrmToolBox.
Connection strings are different for this new version of connection assembly
This explains why your connection string is working with the .net application and not with XrmToolBox

**Comment by vppetrov** [comment]
Do you have a link where the new connection strings and maybe the transformation from an old one to the new one is described?

**Comment by MscrmTools** [comment]
When using the latest version of XrmToolBox connection wizard, there is a link to this page

**Comment by vppetrov** [comment]
I tried the Microsoft.Xrm.Tooling.Connector.dll and this one works:

var crmSvc = new CrmServiceClient(new System.Net.NetworkCredential("user@server.com", "mypass", null), AuthenticationType.IFD, "orgname.server.com", "443", "orgname", useUniqueInstance: false, useSsl: true);
Console.WriteLine(crmSvc.IsReady); -> true

However I cannot get any connection string to work. Unfortunately in XrmToolBox I don't see the possibility to enter all these data (it was there before but not in the new wizard). Is there any way to enter all the information?

**Comment by vppetrov** [comment]
After manually editing the mscrmtools2011.config I get this error: ID3242: The security token could not be authenticated or authorized.

**Comment by MscrmTools** [comment]
can you share your latest connection string?

**Comment by vppetrov** [comment]
`AuthType=IFD; Url=https://orgname.server.com/orgname; Username=user@server.com; Password=mypass`

I cannot provide the port separately (I tried also with https://orgname.server.com:443/orgname with the same result), the useSsl flag and the organization name separately.

**Comment by MscrmTools** [comment]
Did you try with AuthType=AD ?
Did you try with username that is not an email address but an AD login?

**Comment by vppetrov** [comment]
I tried both, unfortunately no luck

**Comment by MscrmTools** [comment]
maybe the log file has more information about what is going wrong

**Comment by vppetrov** [comment]
If you mean the XrmToolBoxConnection.log it says:

> The authentication endpoint Kerberos was not found on the configured Secure Token Service!

However the same settings but as objects (see my code above) work. I cannot see what is different.

**Comment by MscrmTools** [comment]
I know that using the constructor has some fallback methods if something goes wrong whereas connection string has not
I won't be able to help you more I guess...

**Comment by vppetrov** [comment]
Do you plan to implement all features in the new version of XrmToolBox as they were in the previous versions? I mean these, because they are working:

![crm](https://cloud.githubusercontent.com/assets/13319429/14535771/c047c164-026f-11e6-971c-b7c56c8877a1.png)

**Comment by MscrmTools** [comment]
This is not as easy as just saying it... 
Previous versions used a connection dialog that cannot deal with new connection assemblies from CRM SDK. 
It does not support either OAuth or MFA

Just for information, the old connection dialog just produced a connection string used with `CrmConnection`class. But new assemblies used updated connection string.

**Comment by lindid** [comment]
Has anyone been able to troubleshoot this more? Seems like it is CRM 2016 on premise deployments with the issue. I have a hosted deployment - IFD and have tried both connections and none seems to work. I get exactly the same issues as discussed above. 

Connection string: AuthType=IFD; Url=https://myorg.myserver.com/uniqueorgname; Username=myusername; Password=mypassword

This keeps giving me "Unable to Login to Dynamics CRM"

From the log: it refers to a Value cannot be null - which value I can't see what I might be missing? Can you see anything here?

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: Microsoft.Xrm.Sdk
Method	: .ctor
Date	: 2016/05/02
Time	: 11:17:13 AM
Error	: Value cannot be null.
Parameter name: securityTokenResponse
Stack Trace	: at Microsoft.Xrm.Sdk.Client.ServiceProxy`1..ctor(IServiceConfiguration`1 serviceConfiguration, SecurityTokenResponse securityTokenResponse)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM

**Comment by MscrmTools** [comment]
Did you try this  [solution](https://github.com/MscrmTools/XrmToolBox/issues/363#issuecomment-216035104) ?

**Comment by lindid** [comment]
I did now! And it worked. Thank you so very much.

**Comment by MscrmTools** [comment]
Closing the issue as it seems everyone succeeded to connect
