### ISSUE TITLE
User Roles Manager doesn't work properly when role table is bigger than 5000 rows

### ISSUE THREAD

**Issue by BGasnier** [MscrmTools/XrmToolBox#376]
User role change doesn't work properly when organization contains more than 5000 rows in role table.
Some roles are updated or removed as asked and some other not.

The query used under this plugin to retrieve all roles have a limit to 5000 records.
I found A solution to leverage this limit by using a LINQ query and I need to add also the Microsoft.Xrm.Client.dll.

I would like to push this change but as I am not familiar with GitHub I need to find the good process to show you my changes and push this into the main.

**Comment by MscrmTools** [comment]
Microsoft.Xrm.Client is not an option since it is deprecated by Microsoft.

But we can use a while loop to query roles with paging

**Comment by BGasnier** [comment]
I didn't know that, thanks. Finally, it could also work without this dll and without loop.

**Comment by isultan69** [comment]
You can still use linq. Just generate Scheme with no Microsoft.Xrm.Client

**Comment by BGasnier** [comment]
I would like to know the process to be able to check my changes and push in your repository:
1 - I would like to do changes in private and build in Visual Studio to check.
(Currently I did a Fork and Clone this repository on my computer in Visual Studio)
2 - When I checked that is building and working, how to push in your main branch?

**Comment by BGasnier** [comment]
@isultan69 Yes, its what I did

**Comment by MscrmTools** [comment]
I'm not a github expert and never did a pull request so I can't help you here...
Anyone can help him?

**Comment by isultan69** [comment]
Download github app and install it.
Clone project to local folder
Make your changes
Create branch
Create pull request

**Comment by daryllabar** [comment]
In Visual Studio, you can check in your changes to your repository.  It's a check-in, which is local on your machine, then a sync, which pushes it to your fork in GitHub.

Then open up github in your browser, go to your fork, and click on create pull request.  Just select the XTB and your fork, and click create.

**Comment by MscrmTools** [comment]
I'm waiting for your pull request to include it in the march release.
Hope you can create it before end of month
