### ISSUE TITLE
Could not load file or assembly "Microsoft.IdentityModel.Clients.ActiveDirectory, version=2.18.0.0"

### ISSUE THREAD

**Issue by njlassi** [MscrmTools/XrmToolBox#378]
Hi,

I tried to connect to a CRM Organization using IFD on the latest release (1.2016.322.126). And Got this error :  Could not load file or assembly "Microsoft.IdentityModel.Clients.ActiveDirectory, version=2.18.0.0". 
I have an older version of XrmToolBox using Windows Identity Foundation library and it works fine.

Did someone got this same problem ?

Thank you.

**Comment by MscrmTools** [comment]
It is possible that some version use more recent libraries...
In this case, you should edit the configuration file XrmToolBox.exe.config to extend the assembly binding to use version X.X.X.X (check the version in the file properties) instead of 2.18.0.0

**Comment by njlassi** [comment]
I edited the XrmToolBox.exe.config file with version=2.23.0.0, but I still get the same error.

**Comment by MscrmTools** [comment]
can you share your configuration file (only assemblyBinding part)?

**Comment by MscrmTools** [comment]
I close this issue. 

If stable version shows the same error, please reopen the issue and paste your configuration file
