### ISSUE TITLE
Version 03.30 doesn't load

### ISSUE THREAD

**Issue by polshgiant** [MscrmTools/XrmToolBox#379]
I downloaded 2016.3.30, unblocked the zip, and extracted to a folder.  When I try to run XrmToolbox.exe, nothing happens.  In my event log I see two errors:

> Application: XrmToolBox.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IO.FileNotFoundException
>    at XrmToolBox.Program.Main(System.String[])

and

> Faulting application name: XrmToolBox.exe, version: 1.2016.3.30, time stamp: 0x56fbd302
> Faulting module name: KERNELBASE.dll, version: 10.0.10586.162, time stamp: 0x56cd45b4
> Exception code: 0xe0434352
> Fault offset: 0x0000000000071f28
> Faulting process id: 0x79e0
> Faulting application start time: 0x01d18ab36517d3a7
> Faulting application path: G:\[snip]\XrmToolBox 1.2016.03.30\XrmToolBox.exe
> Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
> Report Id: 84ba596d-7233-4b5e-b15f-672d8814908d
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by crexin** [comment]
I get this same crash as well.  If I choose to debug, it gives me more details gives the error below that I copied to the clipboard.

"System.IO.FileNotFoundException was unhandled
Message: Could not load file or assembly 'XrmToolBox.Extensibility, Version=1.2016.3.30, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
"

**Comment by daryllabar** [comment]
It appears @MscrmTools  missed a dll.  I used the NuGet Version for my builds, you can [download my full version](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/releases/download/2016.3.30.1/DLaB.XrmToolBoxTools.Full.zip) and see if that works if you want a work around.

**Comment by MscrmTools** [comment]
Sorry for that!
I updated the package. Please download again the latest version

**Comment by polshgiant** [comment]
New package worked, thank you.

**Comment by crexin** [comment]
I can confirm that the new package works as expected.  :)
