### ISSUE TITLE
Breaking change in NewVersionForm

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#380]
Maybe I am over-consuming XrmToolBox, but there was such a nice feature available for plugins to be able to use the ``XrmToolBox.AppCode.GithubVersionChecker`` class to check for new versions, and then the ``XrmToolBox.Forms.NewVersionForm`` to display release notes and provide a big nice **Update now!** button.

**Now it gives this behaviour**

All is well here:
![image](https://cloud.githubusercontent.com/assets/2572253/14171125/9730fa50-f731-11e5-9d53-fbb6c4d6b7e3.png)

But clicking the Update button gives this:
![image](https://cloud.githubusercontent.com/assets/2572253/14171135/ad49634a-f731-11e5-84c0-d95deece8dcf.png)

And then this:
![image](https://cloud.githubusercontent.com/assets/2572253/14171142/b5619df4-f731-11e5-8c71-c3c74555525f.png)

Clicking the Open XrmToolBox button gives really ugly crash:
```System.InvalidOperationException: Cannot start process as no file name was given.
   vid System.Diagnostics.Process.Start()
   vid System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   vid XrmToolBox.AutoUpdater.AutoUpdater.button1_Click(Object sender, EventArgs e)```

**Comment by rappen** [comment]
I guess the problem might be that I direct the Update button to the FXB home page, and not directly to the ZIP file...

**Comment by MscrmTools** [comment]
As explained on Gitter, I updated these files and they are now specific to XrmToolBox
The unzip error is because the file donwloaded is the HTML page and not the zip package.

In the NewVersionForm constructor, please pass the actual zip package as the last argument, that should work better (if it works for other thing that XTB)

**Comment by rappen** [comment]
Ok. Sorry for not recognizing that from Gitter.
Is it still supposed to work for updating plugins too?

**Comment by MscrmTools** [comment]
I'm not sure since I'm not using it for this purpose
You'll have to try...
The autoupdater does the following:

- Download
- Unzip
- Backup XTB folder
- Paste zip content to XTB foler

I guess if your zip contains a folder plugins with your files, it should work
