### ISSUE TITLE
View Tranfer Tool (CRM On-Premise to Online) Error

### ISSUE THREAD

**Issue by gedamico** [MscrmTools/XrmToolBox#383]
When attempting to transfer views from CRM 2015 On-Premise to CRM 2016 Online, receiving error when I select transfer view.  The GUID or user is not recognized in the online version. I am assuming this is due to the On-Premise  version is accessing by a Domain\user name and the Online version that was migrated the GUID ID and login does not match.

Error:
Error while transferring views: Unable to find a user in the target organization with domain name or id. 

Does anyone know how to get past this?

**Comment by MscrmTools** [comment]
I guess you are right, the domain name is used to retrieve the targeted user account.
Except coding a mapping dialog, I don't see any possibility to fix this problem

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/DamSim.ViewTransferTool #3](https://github.com/MscrmTools/DamSim.ViewTransferTool/issues/3) via [**ZenHub**](https://www.zenhub.com/)
