### ISSUE TITLE
Can XrmToolBox be used with delegate access

### ISSUE THREAD

**Issue by RSA999** [MscrmTools/XrmToolBox#384]
In CRM Online 2015 it is possible for an organization who has delegated access to logon to the CRM without need an account in that organization. This is great for partners/consultants who are providing services so they do not need a dedicated account 

But this doesn't seem to work with XRMToolbox. It seems a dedicated account in that organization is still needed. 

Can you confirm if this is correct and, if it isn't, how to get delegated access working.

**Comment by MscrmTools** [comment]
I never tried to connect with such an account but the only thing I can tell is that latest version of XrmToolBox uses lastest version of connection controls that allows using connection string.
So, if Microsoft allows to connect with delegated admin, then a connection string format should exists, and XrmToolBox supports it. If not, then XrmToolBox cannot handle it by itself

**Comment by RSA999** [comment]
So this works fine when logging on directly to CRM Online. I'm just not sure how to structure the connection string to reflect the organization's url but the delegated access logon credentials.
