### ISSUE TITLE
Easy Translator: No Export for Workflow Categories

### ISSUE THREAD

**Issue by JBraeunig** [MscrmTools/XrmToolBox#388]
Exporting the complete Default Solution using the Easy Translator does not pickup the Workflow Categories in the localized labels tab that is found through the Default Solution translations .xml exported from within the crm system.  This restricts the easy translator from editing the labels on Business Process Flows.  Is it possible to add this into the Easy Translator in a future release?

`
![image](https://cloud.githubusercontent.com/assets/18291263/14290999/49b26ce4-fb2f-11e5-97ec-42fc385a9b0d.png)

**Comment by MscrmTools** [comment]
Hi,
No it,s not possible to export them. Well I can export them but no method in the CRM sdk allows me to update them through code.
So I close this issue since it is not achievable
