### ISSUE TITLE
Null pointer exception in View Transfer Tool

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#39]
In View Transfer Tool null pointer exception raises when trying to display view where column width was not set explicitly.

Debugger catches following location: https://github.com/MscrmTools/XrmToolBox/blob/master/Plugins/DamSim.ViewTransferTool/ViewTransferTool.cs#L460

`columnNode.Attributes["width"]` is null. For me it fired on `Sharepoint Document` entity, trying to display `All SharePoint Document` view.
```
---------------------------
Error
---------------------------
Error while displaying view: Object reference not set to an instance of an object.
---------------------------
OK   
---------------------------
```

Vanilla CRM 2013 database.

**Comment by MscrmTools** [comment]
I'm not really the owner of this tool and I'm quite sure the owner won't update it...

Need to figure out what to change to fix it
