### ISSUE TITLE
Error on 'XrmToolBox.Attributes.BigImageBase64Attribute' 

### ISSUE THREAD

**Issue by BrianTodd** [MscrmTools/XrmToolBox#391]
I'm receiving the following error on load:   System.TypeLoadException: Could not load type 'XrmToolBox.Attributes.BigImageBase64Attribute' from assembly 'XrmToolBox, Version=1.2016.3.30, Culture=neutral, PublicKeyToken=null'.  

Never had any issues with previous versions.   I just copied the new files over the old.

Thanks!

**Comment by MscrmTools** [comment]
It comes from old plugins not compatible with latest version.
Please do not copy new version over old one

**Comment by BrianTodd** [comment]
That did the trick.   I'll be sure not to copy new over old in the future.   Thanks a bunch!
