### ISSUE TITLE
Importing translations

### ISSUE THREAD

**Issue by twanninger** [MscrmTools/XrmToolBox#397]
I have been working on importing languages into my CRM environment via the Easy Translator tool in the XRM Toolbox.  I would continue running into errors when it would get to the _base fields.  This has been an issue in the past so I removed all the _base fields from the translation document and tried importing again.  After running for 25 minutes the import fails and gives me the attached error.  I was hoping someone might be able to tell me what the issue is, we have 8 languages to get translated and imported back into the system.
Tanya Wanninger
608.220.6042
![easy translator error](https://cloud.githubusercontent.com/assets/18405793/14439710/29241014-fff2-11e5-8393-17ae71704f10.jpg)

**Comment by arow44** [comment]
I have same problems (both). Did you solve it? 
Thanks

**Comment by twanninger** [comment]
No, I wasn’t able to get it resolved using XRMToolbox.  I ended up using the CRM OOTB translations, they were able to import successfully.

**Comment by JDHannan** [comment]
I have this exact same problem.  I tried doing it with just one of our custom entities and just one language and it gives me the same exact error message.  I'm not sure what twanninger is saying about _base fields either so I can't attempt to remove them. It gives me the error in only a few seconds.

**Comment by JDHannan** [comment]
Even if I take the file it exports and try to import that, it fails
I am using CRM 2015 0.2 on prem

**Comment by mscottsewell** [comment]
@JDHannan  - try exporting with none of the 'global options' and only the first of the "entity related options" check marks selected - If that works, add a few more options and re-test - maybe you can isolate which of the options is creating the challenge.
In one environment on one entity I experienced this with one of the options (I can't remember which one.) - and if I exported all but that one, it worked. 
On subsequent environments/entities, I could choose all the options without error.

**Comment by MscrmTools** [comment]
I'm still in holidays but I'm jumping in...

The error message talks about relationship translation error. Try to avoid exporting it until i find out why the problem is

**Comment by JDHannan** [comment]
MScottSewell> That was a good idea, I reduced it down to what you suggested and it did work. I didn't actually mean to import it, I tried to click on the Import tab, but clicked the Import button and it must have been already filled in from a previous attempt and it just imported the fresh export.
I've also been messing around with the standard (and terrible) CRM way of doing translations and in the end, I had tonnes of things labelled #REF 
I have restored a backup of my org and as per MscrmTools' indication, I am not going to play with it anymore for the time being.

**Comment by JDHannan** [comment]
I finally got back around to looking at this again and it fails only when i pick the very last option - Export Relationships that are using custom labels.

Hope that helps

**Comment by maricasoderstam** [comment]
I have the same issue! Any updates?

**Comment by MscrmTools** [comment]
I can work on this today... stay tuned!

**Comment by MscrmTools** [comment]
@maricasoderstam @JDHannan Can you confirm if the error still exists with latest version? I exported a relationship with custom label, tried to import it back with or without value for not translated label and it does not fail...

**Comment by maricasoderstam** [comment]
@MscrmTools I downloaded the latest and greatest and the error still occurs. I get the following error.

It could be something in my file but I haven't been able to identify it. 

![2017-03-20 11_27_25-xrmtoolbox for microsoft dynamics crm 2011 to 2016 v1 2017 2 13](https://cloud.githubusercontent.com/assets/26480071/24096068/40a7038c-0d60-11e7-93d0-ebfa0db15777.png)

**Comment by MscrmTools** [comment]
May I have the spreadsheet with data?

**Comment by maricasoderstam** [comment]
[EasyTranslator - MUA1.XLSX](https://github.com/MscrmTools/XrmToolBox/files/854615/EasyTranslator.-.MUA1.XLSX)

**Comment by MscrmTools** [comment]
I guess I found the issue... You have one relationship without any translation, even for the base langage.
If I apply the same in my sample file, I get the same error
![image](https://cloud.githubusercontent.com/assets/10774317/24107952/805b5f88-0d8c-11e7-80a7-d73309d903b3.png)

**Comment by MscrmTools** [comment]
By the way, I'm moving the issue in the appropriate repository, please contine the discussion there

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.Translator #3](https://github.com/MscrmTools/MsCrmTools.Translator/issues/3) via [**ZenHub**](https://www.zenhub.com/)

**Comment by JDHannan** [comment]
I have done an export with the tool, then done a re-import with no changes and re-imported it and had it not work as i said on July 16 above.  While it might be true that having no translation for the base language breaks it, it seems like the tool shouldn't export something it can't re-import. Either have it export the default value for the default language, or have it ignore rows with nothing in the base language column?
