### ISSUE TITLE
Use of HTTPS is apparently forced upon establishing a connection to CRM

### ISSUE THREAD

**Issue by DmytroLapshyn** [MscrmTools/XrmToolBox#399]
The latest stable release of XrmToolBox 1.2016.3.30 appears to use SSL to connect to the CRM web services even if the http protocol and port 80 were specified in the CRM Url.

The error message in the log file looks like this:

```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: System.ServiceModel
Method	: Retrieve
Date	: 4/13/2016
Time	: 12:57:34 PM
Error	: Metadata contains a reference that cannot be resolved: 'https://crm:80/OrgName/XRMServices/2011/Organization.svc?wsdl&sdkversion=8'.
Stack Trace	: at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceConfiguration..ctor(Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ConnectAndInitCrmOrgService(OrganizationDetail orgdata, Boolean IsOnPrem, Uri homeRealmUri)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()

```
As you can see, the URL starts with "https" despite port number 80.

I've seen mebtioning of some "Use SSL" checkbox in the connection screen UI, but it does not seem to be present in 1.2016.3.30 (and neither there seems to be such an option in the Settings screen)

**Comment by MscrmTools** [comment]
I'm often connecting to OnPremise deployements without SSL enabled and never faced this situation.
Can you share your connection wizard screen?

**Comment by DmytroLapshyn** [comment]
@MscrmTools here's the screenshot:

![Connection screen](https://monosnap.com/file/wg0hzxSk28ZHTXmu0ybqz9SDKp0aCJ.png)

I've tried the connection string approach as well, with no luck either

**Comment by MscrmTools** [comment]
The only part of code that defines the usage of SSL or not is the following:
```C#
updatedDetail.UseSsl = updatedDetail.OriginalUrl.StartsWith("https");
```

which obviously should be set to False in your case

Can you validate that your CRM web site is not set with two bindings (port 80 and 443)?

**Comment by DmytroLapshyn** [comment]
> Can you validate that your CRM web site is not set with two bindings (port 80 and 443)?

You knew :) There are indeed two bindings, one for http and the other for https. What's more interesting, neither has the port number explicitly specified.

**Comment by DmytroLapshyn** [comment]
I've also tried connecting with the https URL, but this didn't work either with the same error message in the log file:

`Error	: Metadata contains a reference that cannot be resolved: 'https://crm:80/Sigma/XRMServices/2011/Organization.svc?wsdl&sdkversion=8'`

**Comment by MscrmTools** [comment]
It is not supported to have two bindings for CRM web site : https://technet.microsoft.com/en-us/library/hh699671.aspx#IIS

Maybe it is the root cause...

**Comment by DmytroLapshyn** [comment]
That could be. However, in that case, CRM for Outlook would also have problems connecting to the CRM, right? While, in reality, CRM for Outlook works just fine with this setup.

I've talked to our admins and they say this rather means one can't have multiple http (or https) ports, however having just one port for http and just one port for https is OK.

**Comment by MscrmTools** [comment]
ok, maybe there is some port redirection that make call to 80 redirected to 443

**Comment by DmytroLapshyn** [comment]
@MscrmTools Is there a way I could quickly debug McTools.Xrm.Connection.WinForms? It appears to be a separate project which is referenced as a NuGet package from XrmToolBox. Do you happen to have a Visual Studio solution where both XrmToolBox and McTools.Xrm.Connection.WinForms would be included as projects?

**Comment by MscrmTools** [comment]
Yes, please look at my other repositories, you will see the project MscrmTools.Xrm.Connection

**Comment by DmytroLapshyn** [comment]
Hmm... 

ConnectionDetail.cs, line 326

crmSvc.CrmConnectOrgUriActual contains a URL starting with https even though CrmServiceClient was constructed with http and port number 80 on line 318.

So it looks like a problem with XRM SDK, then?

**Comment by MscrmTools** [comment]
More with your deployment configuration actually... can you look in the deployment manager properties (tab "Web address") on the CRM server ?
There should be https value somewhere

**Comment by DmytroLapshyn** [comment]
> can you look in the deployment manager properties (tab "Web address") on the CRM server ?
There should be https value somewhere

Will have our admins look into it, thanks!

**FYI**: Explicitly specifying the port number, i.e. https://crm:443/OrgName/ appears to have done the job

**Comment by DmytroLapshyn** [comment]
> can you look in the deployment manager properties (tab "Web address") on the CRM server ?
There should be https value somewhere

Checked, the "Binding" radio button is set to HTTPS

So the problem is that HTTP is enabled in IIS along with HTTPS (otherwise I have no idea where does the HTTP binding come from in the Organization.svc WSDL)?

**Comment by MscrmTools** [comment]
I guess it is the problem, when connecting with an url, some information are retrieved from the deployment configuration, which could cause the issue

**Comment by DmytroLapshyn** [comment]
Thanks so much for your kind support efforts!
