### ISSUE TITLE
After adding new connection it displayed in Connection List incorrectly

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#4]
Adding new connection:
![Adding new connection to XrmToolBox](http://i.imgur.com/dh04djg.png)

New connection was added:
![New connection was added](http://i.imgur.com/F6hd0bj.png)

Note, contents of `Organization` and `Server` column are switched. 

The issue is just visual representation bug, after reopening of Connection List window, columns are populated with correct values.

**Comment by MscrmTools** [comment]
Will fix this also

Are you reviewing the whole application? :)

**Comment by shytikov** [comment]
Oh no :) I'm was working with ConnectionDetail object in my plugin, so I bumped on several small issues, that I would like to share :)
