### ISSUE TITLE
Easy Translator slow loading entity translations when using EPPlus

### ISSUE THREAD

**Issue by damonfutter** [MscrmTools/XrmToolBox#40]
When using the cutting edge development version that has included the ability to use EPPlus instead of GemBox for spreadsheet access, there is a performance problem when loading Entity Translations.

When loading translations for entities, it goes exponentially slower the more entities you have in the worksheet.  I think there is a mis-placed closing brace which is causing *ALL* of the entity translations to be loaded for *EVERY LINE* of the spreadsheet.

The code file is **EntityTranslation.cs** and the offending closing brace is on **line 200**.  I think it needs to be moved about 7 lines upwards so that the translations are only loaded once, when they have all been loaded out of the spreadsheet.

p.s. Thanks for implementing EPPlus in the first place.  Without it we would not even have been able to build the code and run it.

**Comment by MscrmTools** [comment]
Thank you for reporting the problem. You are right about the cause of the problem.

I will update the code ASAP
