### ISSUE TITLE
New plugin candidate: Save Dynamic List as Public View

### ISSUE THREAD

**Issue by guusvanw** [MscrmTools/XrmToolBox#400]
Hi I've created a (very simple) plugin that allows the user to save a dynamic marketing list"s query as a public view. If you want I'm happy to share (no access to contribute). :)

**Comment by rappen** [comment]
:+1:

**Comment by MscrmTools** [comment]
You can share it by creating a nuget package that will be listed in the upcoming XrmToolBox plugins store
See [this wiki page](https://github.com/MscrmTools/XrmToolBox/wiki/Distribute-your-plugins-through-XrmToolBox-and-Nuget)
