### ISSUE TITLE
Solution Components Mover moves entire entity instead of the segments from the source solution

### ISSUE THREAD

**Issue by hjmhyl** [MscrmTools/XrmToolBox#404]
In CRM 2016 we have a new feature to add segments of a entity into a solution, so in my source solution I have one  entity with only one field added, however, after copying the components from source solution to target solution via Solution Components Mover, all the components in the source solution are moved into the target solution. Could the Solution Components Mover be changed to copy the segments instead of all the components for CRM 2016?

**Comment by MscrmTools** [comment]
Yes, it's on my roadmap

**Comment by MscrmTools** [comment]
Done! and available through the Plugins Store

Also, the project has been moved to [its own repository](https://github.com/MscrmTools/MsCrmTools.SolutionComponentsMover)
