### ISSUE TITLE
Error on try connection lastest version

### ISSUE THREAD

**Issue by michaelfp** [MscrmTools/XrmToolBox#406]
Consulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

************** Texto de Exceção **************
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   em System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   em XrmToolBox.MainForm.<ManageConnectionControl>b__23_3(Object sender, ConnectionFailedEventArgs e)
   em McTools.Xrm.Connection.ConnectionManager.SendFailureMessage(String failureReason, Object parameter)
   em System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by MscrmTools** [comment]
Can you confirm you have the file XrmToolBox.exe.config with assembly bindings in it?

**Comment by MscrmTools** [comment]
No answer since three weeks.
Closing the issue
