### ISSUE TITLE
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

### ISSUE THREAD

**Issue by polshgiant** [MscrmTools/XrmToolBox#407]
I auto-updated XrmToolbox to the latest version, and upon opening I get the error message from the title on top of the plugins store window.  When I dismiss the error message, no results appear in the store.  Also, the plugins that I had installed previously (such as the Cinteros ones) don't appear in the toolbox anymore.

**Comment by MscrmTools** [comment]
What if you run the XrmToolBox again?

**Comment by polshgiant** [comment]
The store worked after re-opening. I selected both and got an error about not being able to find file or assembly DLaB.Common.  Now every time I open the toolbox I get this error and even if I click Continue on the error, I cannot access the toolbox window.

**Comment by MscrmTools** [comment]
Can you confirm if this file exists in Plugins folder
Also, does it exist in C:\ProgramData\XrmToolBox\Plugins\DLaB.Xrm.XrmToolBoxTools.1.2016.4.28\lib\net452\plugins ?

**Comment by polshgiant** [comment]
It does exist in the plugins folder of the directory that has the toolbox exe that I run, but not in the programdata folder.  However, there is a plugins folder in the programdata folder with a slightly different version number where it also exists.

Path does not exist: C:\ProgramData\XrmToolBox\Plugins\DLaB.Xrm.XrmToolBoxTools.1.2016.4.28\lib\net452\plugins
Path does exist and does contain DLaB.Common:
C:\ProgramData\XrmToolBox\Plugins\DLaB.Xrm.XrmToolBoxTools.1.2016.4.27\lib\net452\plugins

**Comment by MscrmTools** [comment]
@Daryllabar, any help?

**Comment by daryllabar** [comment]
I'm not sure what the cause is, but if you delete all DLaB dlls, and then re-download, everything works.

**Comment by polshgiant** [comment]
From which XrmToolbox folder? My main one or the ProgramData one?

**Comment by MscrmTools** [comment]
The main one

**Comment by polshgiant** [comment]
Deleting all DLaB dlls from MainToolboxFolder\Plugins and MainToolboxFolder\Plugins\CrmSvcUtil Ref worked.

**Comment by polshgiant** [comment]
@daryllabar @MscrmTools I had to go through these steps again with the latest update.  Just fyi.
