### ISSUE TITLE
Failing to load options

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#408]
I just updated from the 1.2016.3.30 version to 1.2016.4.28 using the auto updater, and no matter how I restart the application or remove third party plugins, I still get this:
![image](https://cloud.githubusercontent.com/assets/2572253/14968009/bda8b07c-10ba-11e6-9626-578bc2be81a8.png)
Error message on the first line is "Root element is missing".

The settings file was apparently 0 byte. Deleting it solved the problem.
I create this issue just to keep track if it occurs for someone else.
(Too bad I lost the plugin use count numbers ;) )

**Comment by MscrmTools** [comment]
All files should be backed up in c:\programdata\xrmtoolbox when using auto update

Can you check if your settings file is there?

**Comment by MscrmTools** [comment]
@rappen You never told me if your settings file was backed up... did it?

**Comment by rappen** [comment]
Sorry, this may be obsolete now. I close the issue and get back if I encounter the problem again!

(and pleeease cross your fingers that we beat Belgium tonight...)

**Comment by MscrmTools** [comment]
I bet that Sweden beats Belgium in our company bet contest! Go Ibra, GO!

**Comment by OmniaK** [comment]
Hi @MscrmTools , I had an update yesterday for my XrmToolbox and now I have the same error.
I tried to remove the folder and re-download it and it still fails to load the XrmToolbox 
I can't find a settings file in the update folder on c:\programdata\xrmtoolbox
Any idea what to do ?!
