### ISSUE TITLE
Error on N:N import attempt

### ISSUE THREAD

**Issue by bowens11** [MscrmTools/XrmToolBox#409]
Plugin loads as desired, but when I go to action the .csv I receive the attached error
[xrmtoolboxerror.txt](https://github.com/MscrmTools/XrmToolBox/files/249174/xrmtoolboxerror.txt)

**Comment by MscrmTools** [comment]
Thank you for reporting it. Does your file use the separator defined in the menu bar?

**Comment by bowens11** [comment]
The file is delimited by commas, which was the setting in the plugin

**Comment by MscrmTools** [comment]
Ok, I must have missed something... I will fix it in the next couple of hours

**Comment by MscrmTools** [comment]
Issue deported to the plugin repository [#1](https://github.com/MscrmTools/Javista.XrmToolBox.ManageNN/issues/1)

Problem fixed and available through the Plugin Store

**Comment by bowens11** [comment]
Thank you!
