### ISSUE TITLE
Easy Translator - Relationship Custom Labels

### ISSUE THREAD

**Issue by LycraLout** [MscrmTools/XrmToolBox#41]
Currently, Easy Translator does not translate the `CustomLabels` collection in the `EntityRelationshipRole`. This results in Associated View tiles that are not translated.

**Comment by MscrmTools** [comment]
I will try to add this feature

Does it seem ok to you if I export only relationships with custom labels?

**Comment by LycraLout** [comment]
That makes good sense to me. That will reduce the amount of work the translator is doing.
