### ISSUE TITLE
Unable to install Package Because It Is Being Used By Another Process

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#411]
I have previously installed the FetchXML Builder.  Today I went to install the Cinteros Tools for XrmToolBox, but I got an error:

![image](https://cloud.githubusercontent.com/assets/9728423/15071943/62edc7c6-135d-11e6-80d2-2586677aa99e.png)

I'm wondering if we need an option to install on next startup?  Maybe it's good practice to ILMerge all of our shared dlls into a single one for plugins for the XrmToolBox?

**Comment by MscrmTools** [comment]
There already is a "restart to install" option but maybe it does not handle the process correctly when there is an installation AND an update.
And you are right, I guess FetchXmlBuilder uses the same assembly that Cinteros Tools, which cause the problem...
Maybe I should check if embeded do not exist already to determine if a restart is required
