### ISSUE TITLE
SiteMapEditor : Unhandled exception of type NullReferenceException when provided wrong LCID (adding new description)

### ISSUE THREAD

**Issue by msk-one** [MscrmTools/XrmToolBox#414]
At SiteMap editor, when I tried to add description to newly created area, at first message box showed up, with text that LCID should be 4/5 digits long. But, after that, there was unhandled exception of message:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MsCrmTools.SiteMapEditor.SiteMapEditor.TsbItemSaveClick(Object sender, EventArgs e)
   (...)
```

**Comment by MscrmTools** [comment]
I cannot reproduce but I'm not even sure to understand how you got this error.
Can you detail each step to reproduce the error?
What version of SiteMapEditor do you use?

**Comment by msk-one** [comment]
Version 1.2016.4.27 of SiteMapEditor

Steps: open SiteMap from connected CRM server -> select any area -> any group -> try to create Description there, input wrong LCID -> Save -> Click OK on message -> Unhandled Exception Message

**Comment by MscrmTools** [comment]
ok, I can reproduce and will work on it.

Thank for reporting it

**Comment by MscrmTools** [comment]
Fixed and available in the Plugins Store
