### ISSUE TITLE
Filter Web Resources

### ISSUE THREAD

**Issue by craigseymour** [MscrmTools/XrmToolBox#415]
I'd like to be able to more easily able to get to 'my stuff' in Web Resources Manager.  The first thing I have to do every time I load up the web resources is collapse everything, and scroll through all the Click Dimensions, Microsoft and other vendor stuff to get to my stuff.  

Perhaps a regex in a persistent pane at the top of the tree?

**Comment by MscrmTools** [comment]
Is your stuff not on a dedicated solution? If so, you can load only web resources from this solution 

For "Collapse everything", there is a new shortcut under the treeview to collapse all folder

**Comment by craigseymour** [comment]
No, I didn't think to put it in its own solution.  Duh...  That's the way to go!  Thanks.

(I use the collapse feature, but ClickDimensions and others spam the root with their stuff, so it's not been a perfect workaround):

![wr](https://cloud.githubusercontent.com/assets/14763830/15243656/d98b913c-18f4-11e6-8206-38a8fc0452ec.png)

**Comment by MscrmTools** [comment]
Can you close the issue if creating a dedicated solution works for you?

**Comment by craigseymour** [comment]
Sure - wasn't sure if that was the protocol.

**Comment by daryllabar** [comment]
If you have local web resources on disk, you can just load from that instead.
