### ISSUE TITLE
Unable to connect to Dynamics Online 2015

### ISSUE THREAD

**Issue by cbailiss** [MscrmTools/XrmToolBox#417]
I have downloaded the latest version of the tools and cannot connect to an Dynamics CRM Online 2015.  Having no luck.  Am I doing something wrong?

Simply get "Unable to login to Dynamics CRM" error.  In the new connection dialog have tried:
https://ABCDEF.crm4.dynamics.com/
and
https://ABCDEF.crm4.dynamics.com/ABCDEF

Have also tried a connection strings that look like:
AuthType=Office365;Username=me@emailaddress.org.uk;Password=passwd;Url=https://ABCDEF.crm4.dynamics.com/
and
AuthType=Office365;Username=me@emailaddress.org.uk;Password=passwd;Url=https://ABCDEF.crm4.dynamics.com/ABCDEF

All of the above URLs and credentials can be used to login to Dynamics via web browser but none work when connecting in XRM toolbox.

Are any more useful details logged anywhere?

Also, on opening the new version I get a "The type initializer for 'NuGet.ProxyCache' threw an exception." error.  Related?

This all feels difficult to get working, a lot more difficult than it used to.

**Comment by MscrmTools** [comment]
To get more information on why the connection did not succeed on your organization, please activate the trace by following [this procedure](https://github.com/MscrmTools/XrmToolBox/wiki/Enable-tracing-in-XrmToolBox)

Then, please post the log here so we can analyze what the problem is

**Comment by cbailiss** [comment]
Thanks for the very fast reply.  Log contents below.  Looks like it is almost there?  This was done using a connection string that looked like:
AuthType=Office365;Username=me@emailaddress.org.uk;Password=passwd;Url=https://emsuat.crm4.dynamics.com
The credentials used are the same as I used to login through the UI, though I don't enter the password through the web browser as we have ADFS set up.  It is however the correct password (since I use it daily for many other things).

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Using User Specified Server 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (Europe, Middle East and Africa) URI is = https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : DiscoverOrganizations - Initializing Discovery Server Object with https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - attempting to connect to CRM server @ https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - created CRM server proxy configuration for https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc - duration: 00:00:06.4748000
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - proxy requiring authentication type : OnlineFederation 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - Authenticated via OnlineFederation. Auth Elapsed:00:00:02.8834000
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - service proxy created - total create duration: 00:00:09.3738000
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : DiscoverOrganizations - Discovery Server Get Orgs Call Complete - Elapsed:00:00:10.1694000
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Found 3 Org(s)
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : looking for Org = emsuat in the results from CRM's Discovery server list.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM

**Comment by cbailiss** [comment]
I have also used the same login credentials via a .NET app that uses the Dynamics SDK and it works there with no problems.

**Comment by cbailiss** [comment]
Re (unrelated, but I mentioned it in my original post): The error  "The type initializer for 'NuGet.ProxyCache' threw an exception." that was being thrown in the Plugins Store...
By moving the XRM Tool Box from the desktop to c:\ this error went away, and I can now install add-ins using the Plugins Store screen.

**Comment by MscrmTools** [comment]
Can you try using org Unique name instead of URL org name?

**Comment by cbailiss** [comment]
Where exactly? - at the end of the URL in the connection string?

**Comment by MscrmTools** [comment]
No, before ".crm4.dynamics.com", put the unique orgname instead of the name used in the browser URL

**Comment by cbailiss** [comment]
That worked, thank you very much.  I appreciate the very fast assistance.
This solution seems to contradict the information at:
https://msdn.microsoft.com/en-US/library/mt608573.aspx
The above states "You can specify either the friendly or the unique name of the organization to connect to.".
Might be good idea to have an FAQ item about connection issues.

**Comment by MscrmTools** [comment]
The wiki already mentions this problem

**Comment by MscrmTools** [comment]
Can you share the connections log? 
Please delete the log file first, then retry to connect, then provide the log file

**Comment by sindhumm** [comment]
*Warm Regards,*
*Manisindhu Medandrao.*

**Comment by MscrmTools** [comment]
Don't know if you tried to send the file per email but it does not work

**Comment by sindhumm** [comment]
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 10:22:18
AM  Source : System.ServiceModel
Method : Retrieve
Date : 7/18/2018
Time : 10:22:18 AM
Error : Metadata contains a reference that cannot be resolved: '
https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9
'.
Stack Trace : at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState
resolveCallState)
   at
System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever
retriever)
   at
Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type
contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri,
Boolean checkForSecondary)
   at
Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri
serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1
servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials
userCredentials, ClientCredentials deviceCredentials, String LogString,
CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri
discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials,
ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri
discoServer, Boolean useGlobal)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers
onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1 :
Source : System
Method : GetResponse
Date : 7/18/2018
Time : 10:22:18 AM
Error : The remote name could not be resolved: 'disco.crm.dynamics.com'
Stack Trace : at System.Net.HttpWebRequest.GetResponse()
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 10:22:18
AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 10:22:44
AM  Source : System.ServiceModel
Method : Retrieve
Date : 7/18/2018
Time : 10:22:44 AM
Error : Metadata contains a reference that cannot be resolved: '
https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9
'.
Stack Trace : at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState
resolveCallState)
   at
System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever
retriever)
   at
Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type
contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri,
Boolean checkForSecondary)
   at
Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri
serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1
servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials
userCredentials, ClientCredentials deviceCredentials, String LogString,
CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri
discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials,
ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri
discoServer, Boolean useGlobal)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers
onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1 :
Source : System
Method : GetResponse
Date : 7/18/2018
Time : 10:22:44 AM
Error : The remote name could not be resolved: 'disco.crm.dynamics.com'
Stack Trace : at System.Net.HttpWebRequest.GetResponse()
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 10:22:44
AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 10:22:53
AM  Source : System.ServiceModel
Method : Retrieve
Date : 7/18/2018
Time : 10:22:53 AM
Error : Metadata contains a reference that cannot be resolved: '
https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9
'.
Stack Trace : at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState
resolveCallState)
   at
System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever
retriever)
   at
Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type
contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri,
Boolean checkForSecondary)
   at
Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri
serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1
servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials
userCredentials, ClientCredentials deviceCredentials, String LogString,
CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri
discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials,
ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri
discoServer, Boolean useGlobal)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers
onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1 :
Source : System
Method : GetResponse
Date : 7/18/2018
Time : 10:22:53 AM
Error : The remote name could not be resolved: 'disco.crm.dynamics.com'
Stack Trace : at System.Net.HttpWebRequest.GetResponse()
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 10:22:53
AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 10:26:25
AM  Source : System.ServiceModel
Method : Retrieve
Date : 7/18/2018
Time : 10:26:25 AM
Error : Metadata contains a reference that cannot be resolved: '
https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9
'.
Stack Trace : at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState
resolveCallState)
   at
System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever
retriever)
   at
Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type
contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri,
Boolean checkForSecondary)
   at
Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri
serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1
servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials
userCredentials, ClientCredentials deviceCredentials, String LogString,
CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri
discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials,
ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri
discoServer, Boolean useGlobal)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers
onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1 :
Source : System
Method : GetResponse
Date : 7/18/2018
Time : 10:26:25 AM
Error : The remote name could not be resolved: 'disco.crm.dynamics.com'
Stack Trace : at System.Net.HttpWebRequest.GetResponse()
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 10:26:25
AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 11:29:13
AM  Source : System.ServiceModel
Method : Retrieve
Date : 7/18/2018
Time : 11:29:13 AM
Error : Metadata contains a reference that cannot be resolved: '
https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9
'.
Stack Trace : at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState
resolveCallState)
   at
System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever
retriever)
   at
Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type
contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri,
Boolean checkForSecondary)
   at
Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri
serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1
servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials
userCredentials, ClientCredentials deviceCredentials, String LogString,
CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri
discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials,
ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri
discoServer, Boolean useGlobal)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers
onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1 :
Source : System
Method : GetResponse
Date : 7/18/2018
Time : 11:29:13 AM
Error : The remote name could not be resolved: 'disco.crm4.dynamics.com'
Stack Trace : at System.Net.HttpWebRequest.GetResponse()
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 11:29:13
AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 11:38:05
AM  Source : System.ServiceModel
Method : Retrieve
Date : 7/18/2018
Time : 11:38:05 AM
Error : Metadata contains a reference that cannot be resolved: '
https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9
'.
Stack Trace : at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState
resolveCallState)
   at
System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever
retriever)
   at
Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type
contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri,
Boolean checkForSecondary)
   at
Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri
serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1
servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials
userCredentials, ClientCredentials deviceCredentials, String LogString,
CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri
discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials,
ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri
discoServer, Boolean useGlobal)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers
onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1 :
Source : System
Method : GetResponse
Date : 7/18/2018
Time : 11:38:05 AM
Error : The remote name could not be resolved: 'disco.crm.dynamics.com'
Stack Trace : at System.Net.HttpWebRequest.GetResponse()
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 11:38:05
AM  Unable to Login to Dynamics CRM

*Warm Regards,*
*Manisindhu Medandrao.*

**Comment by MscrmTools** [comment]
Remote name that cannot be resolved: it’s an issue with your corporate network

**Comment by sindhumm** [comment]
How to resolve it?


*Warm Regards,*
*Manisindhu Medandrao.*

**Comment by MscrmTools** [comment]
Maybe but the error message is pretty clear, something is not reachable...
You can try to download the previous version of XrmToolBox if you want to check if the new version is the cause of the problem

**Comment by sindhumm** [comment]
when I am trying to use the old version this is the error



*Warm Regards,*
*Manisindhu Medandrao.*

**Comment by sindhumm** [comment]
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 1:51:30
PM  Source : System.ServiceModel
Method : Retrieve
Date : 7/18/2018
Time : 1:51:29 PM
Error : Metadata contains a reference that cannot be resolved: '
https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9
'.
Stack Trace : at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState
resolveCallState)
   at
System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever
retriever)
   at
Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type
contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri,
Boolean checkForSecondary)
   at
Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri
serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1
servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials
userCredentials, ClientCredentials deviceCredentials, String LogString,
CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri
discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials,
ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri
discoServer)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers
onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1 :
Source : System
Method : GetResponse
Date : 7/18/2018
Time : 1:51:30 PM
Error : The remote name could not be resolved: 'disco.crm.dynamics.com'
Stack Trace : at System.Net.HttpWebRequest.GetResponse()
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 1:51:30
PM  Source : System.ServiceModel
Method : Retrieve
Date : 7/18/2018
Time : 1:51:29 PM
Error : Metadata contains a reference that cannot be resolved: '
https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9
'.
Stack Trace : at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState
resolveCallState)
   at
System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever
retriever)
   at
Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type
contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri,
Boolean checkForSecondary)
   at
Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri
serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1
servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials
userCredentials, ClientCredentials deviceCredentials, String LogString,
CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri
discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials,
ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri
discoServer)
   at
Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers
onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1 :
Source : System
Method : GetResponse
Date : 7/18/2018
Time : 1:51:30 PM
Error : The remote name could not be resolved: 'disco.crm.dynamics.com'
Stack Trace : at System.Net.HttpWebRequest.GetResponse()
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper
timeoutHelper)
   at
System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper
timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 1:51:30
PM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error 2 7/18/2018 1:51:30
PM  Unable to Login to Dynamics CRM


*Warm Regards,*
*Manisindhu Medandrao.*

On Wed, Jul 18, 2018 at 1:52 PM, Manisindhu Medandrao <sindhumunnu@gmail.com

**Comment by MscrmTools** [comment]
Everything is on XrmToolBox portal documentation : https://www.xrmtoolbox.com/documentation
