### ISSUE TITLE
Assembly Recovery Tool very slow on environments that have many large assemblies registered

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#418]
`Assembly Recovery Tool` acts a bit not optimal during its operation: it tries to load all assemblies (including their binary content) in one go. This makes plugin very slow on environments where lots of plugins registered.

Need to admit, that loading binary content of all assemblies is unnecessary. It makes more sense to load only information about all plugins, and then, when user selects plugins he wants to recover — ask CRM about contents of these assemblies only.

**Comment by MscrmTools** [comment]
Thank you for the pull request!
The plugin has been moved to its [own repository](https://github.com/MscrmTools/MsCrmTools.AssemblyRecoveryTool)
