### ISSUE TITLE
Common session store

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#420]
I know both Early Bound Generator and FetchXml Builder have some persistance mechanism, so when the tool is closed and open again, they resume from the last state.

Can we have a common persistance mechanism so that other tools can use this kind of capability?

**Comment by MscrmTools** [comment]
As the persistence data is independant for each tool, I don't see how I can implement a common persistance mechanism... But if someone has ideas, I'm listening

**Comment by rajyraman** [comment]
I was thinking more along these lines: Before the tool is closed it hands over the data to base class for persistance. When the tool is opened again, base class passes along the persisted data to the tool. The tool then takes of translating the data to the UI state.

**Comment by daryllabar** [comment]
You thinking of storing a string per plugin? And maybe have a string per plugin per connection as well?  And maybe a way to clear the plugins cache as well?, Then leave it to the plugin to parse the string?

**Comment by rajyraman** [comment]
We are thinking along the same lines. If the plugin wants this centralised state capability, it implements a interface. The interface method on the tool, will push the state and the base will serialise it and persist to disk. This method will be called just before the tool closes.

Upon re-opening the tool, base class re-hydrates the state and pushes it to the plugin. I am not 100% sure if the state stored is connection specific. If it is, it could speed up the initial load I guess e.g. entities, views etc. But if we take this approach, we leave it up to the user to refresh the state manually. LinqPad connections takes this approach, so that the entityset is display straightaway as it doesn't have to retrieve it from the service, once the connection is saved.

Base class: Doesn't know what the state is, how it is structured. Knows only how to persist it, read it and pass it to the plugin currently in view, in a commonly agreed format.

Tool: doesn't knows how to state is stored, but knows that it can rely on base class to store it and received it at the right time to populate the UI.

**Comment by daryllabar** [comment]
The state in the EarlyBound generator is just an object that is serialized to XML.  So if the interface waa generic, such that the type T implemented serializable, then everything should work.

It would be nice to have two different states, one for universal settings, and one for connection specific settings.  The universal settings would be loaded/saved on load and close.  The connection specific would be done on that, as well as connection changes.

**Comment by rappen** [comment]
I completely agree with the discussion here.
I would absolutely love it if the XTB host could manage storing settings etc for me, and I could just "trust" the session information.
And as Daryl suggests, one universal and one connection specific would be great.
In the FXB case I store settings universally and current fetchxml by connection.

**Comment by MscrmTools** [comment]
I'm back with some good news!
As you might have heard, XrmToolBox should be available soon in Windows 10 Store.
To allow this, I had to redirect all file writing to userprofile appdata. But I can't do that for your plugins
So, for next version, I will add a SettingsManager that you will be able to use to store your plugins settings and retrieve them (based on a connection or not).
The only requirement is that your settings class has to be serializable to xml

off topic: I will provide a simple logger too so that you can trace what your plugin is doing and user will be able to read the log if needed

**Comment by rajyraman** [comment]
This is exciting news Tanguy 😃. I look forward to  this feature. Thank you for all the hard work.

**Comment by rappen** [comment]
Super sweet! 🌟

**Comment by rajyraman** [comment]
One more thing I forgot to ask: Do we now have a protocol handler for XrmToolBox? For e.g. can I have a URI something like xrmtoolbox:?tool=fxb&conn=default&action=run. With this URI, I am indicating that XrmToolBox should connect to the default connection. I don't think we can specify a default connection at the moment. In that case, the last connection can be used to connect (using the saved credentials). Clicking on the URI link will open FXB tool and execute the query that FXB has saved in its last session.

I am not sure how realistic this is or whether it is possible, but I was looking through the magnet URI scheme https://en.wikipedia.org/wiki/Magnet_URI_scheme and though this would be great, if we have auto launch XrmToolBox with parameters. This means that I can just share a link on an email or blog post, and it will make things easy for people who are clicking that link, instead of looking at multiple screenshots.

**Comment by MscrmTools** [comment]
I guess this is now live on latest version of XrmToolBox so I close the issue
