### ISSUE TITLE
Access Checker Doesn't work for Attachments (toolbox v1.2016.4.28)

### ISSUE THREAD

**Issue by cabreram** [MscrmTools/XrmToolBox#421]
If you specify Attachment as the Entity Name and then click the Search Box next to the Object ID field, you will receive the error "InvalidArguemnt=Value of '0' is not valid for 'SelectedIndex'
I'm assuming this is because there is no view for the Attachment entity.

If instead of searching for the attachment, the Object Id is input manually.  When clicking Retrieve rights, you will receive the error "RetrievePrincipalAccess method does not support entities of type 'attachment'.

**Comment by MscrmTools** [comment]
I can fix the first error you received. 

For the second one, the message is explicit enough, CRM does not allow to check rights for this entity

**Comment by cabreram** [comment]
Understood about the second error message...just letting you know in case you wanted to filter out entities that won't work from the combobox

**Comment by MscrmTools** [comment]
I will try to see if I can filter them, thanks

**Comment by MscrmTools** [comment]
The error message is fixed and the problem handled by the tool.

The tool now has [its own repository](https://github.com/MscrmTools/MsCrmTools.AccessChecker) and is available through the Plugins Store
