### ISSUE TITLE
Failing to connect to plugins store through a corporate proxy

### ISSUE THREAD

**Issue by plepaisant** [MscrmTools/XrmToolBox#422]
The plugins store can not be acessed behind a corporate web proxy. 

![proxy](https://cloud.githubusercontent.com/assets/5773885/15471165/f301f630-20f4-11e6-9883-77f4e68beb8d.PNG)

 
To fix this, the file Nuget.config must contain the following entry:

```
<config>
    <add key="http_proxy" value="http://proxyIP:portIP" />
</config>
```

It would be great if the plugins store could handled corporate proxies.

**Comment by MscrmTools** [comment]
If a real proxy has to be defined in the config file, then I guess I cannot do anything. Did you succeeded to connect using the same proxy configuration than the one in XrmToolBox.exe.config like below

```XML
 <system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true">
      <proxy autoDetect="True" bypassonlocal="False" />
    </defaultProxy>
  </system.net>
```

**Comment by plepaisant** [comment]
I have tried this settings and the one above:

```` xml
 <defaultProxy>
       <proxy  proxyaddress="http://proxyIP:proxyPort" bypassonlocal="true" />
  </defaultProxy>

````

None of them are working. 
I guess NuGet.PackageManager only gets settings from f %APPDATA%\NuGet\NuGet.Config .
I thougth of an optionnal form to fill in with the proxy parameters. Nuget.config file could be modified  or override in xrmToolBox. folder.

**Comment by MscrmTools** [comment]
Problem is: even if I could implement this, I won't be able to test it since I don't have access  to a network with a proxy

**Comment by plepaisant** [comment]
I can submit a pull request  with an "experimental option"  to fill in the proxy options. This form would be displayed if a System.Net.WebException is raised while retrieving the Nuget Packages for xrmToolBox.  The settings  would be stored in the NugetConfig file.

I can only test it with our corporate proxy. It could be enhanced later with feedbacks from the community.

**Comment by MscrmTools** [comment]
Sure! that would be great!

**Comment by plepaisant** [comment]
Which is the preferred repository to add the proxy settings form for the store

 XrmToolBox or MscrmTools.Xrm.Connection?  There are many forms in the last one.

**Comment by MscrmTools** [comment]
The store is on XrmToolBox project, not on MscrmTools.Xrm.Connection, so I would say "XrmToolBox"

**Comment by MscrmTools** [comment]
I close the issue since your pull request will be included in the next release
