### ISSUE TITLE
Cannot connect to Organisation

### ISSUE THREAD

**Issue by PascalHOL** [MscrmTools/XrmToolBox#424]
I cannot connect to an Organisation,because the Microsoft.IdentityModel.Clients.ActiveDirectory or a dependent dll is not found
![image](https://cloud.githubusercontent.com/assets/19547917/15496727/2bdd13a2-2197-11e6-9e07-8b4a8cca4585.png)

**Comment by MscrmTools** [comment]
There should be a binding configuration in the file XrmToolBox.exe.config that redirects usage of this assembly to version 2.24.
Please open this file and verify if you have the following section:

```XML
<dependentAssembly>
  <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory" publicKeyToken="31bf3856ad364e35" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-2.24.0.0" newVersion="2.24.0.0" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms" publicKeyToken="31bf3856ad364e35" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-2.24.0.0" newVersion="2.24.0.0" />
</dependentAssembly>

```

**Comment by PascalHOL** [comment]
I dont have such a file it seems it is not part of the zip
![image](https://cloud.githubusercontent.com/assets/19547917/15496977/90a37fbe-2198-11e6-85b4-262f7ceeca06.png)

I downloaded version XXX.161 and XXX.159

**Comment by PascalHOL** [comment]
I dont have such a file. Looks like it is not part of the .zip
![image](https://cloud.githubusercontent.com/assets/19547917/15496977/90a37fbe-2198-11e6-85b4-262f7ceeca06.png)

I downloaded version .161 and .159

**Comment by PascalHOL** [comment]
I dont have such a file. Looks like it is not part of the .zip

I downloaded version .161 and .159

**Comment by MscrmTools** [comment]
Ok it is because you downloaded a pre release version, that should be use only in complement of an official release
Please download XrmToolBox from http://www.xrmtoolbox.com to be sure getting the latest official version

**Comment by PascalHOL** [comment]
Cool. I got three times the message "something went wrong." Now i posted three times :-(

Downloading the release solved the Issue.
