### ISSUE TITLE
Cannot Connect to Organization

### ISSUE THREAD

**Issue by vektastic** [MscrmTools/XrmToolBox#428]
I am trying to use the User settings tool, so I am adding my connection to my 2016 server. However, It says it is unable to do so, and I have tried multiple different things to get this done.

![image](https://cloud.githubusercontent.com/assets/19613018/15615437/fa179274-2403-11e6-8b7d-4a67c46ab3d7.png)

I have attached a log trace. Is there more you need than this?

[XrmToolBoxConnection trace.zip](https://github.com/MscrmTools/XrmToolBox/files/287021/XrmToolBoxConnection.trace.zip)

**Comment by MscrmTools** [comment]
The error message is "The server was unable to process the request due to an internal error" which seems to indicate there is a problem with your server.
Can you explain the settings you used and your deployment configuration (ADFS/IFD ? HTTPS?, etc)

**Comment by vektastic** [comment]
It's an IFD configuration, with the URL being along the lines of "https://<ORGNAME>.crm.<domain>.com

**Comment by MscrmTools** [comment]
IFD is the hardest type of deployment to debug because the cause of error can be difficult to identify.
First thing to test: use domain\login in username textbox

**Comment by vektastic** [comment]
That was it! I'm connected. Thanks. Bailed me out of a tricky issue. ;)

**Comment by MscrmTools** [comment]
Just FYI, the documentation on the wiki mentions this :)

**Comment by vektastic** [comment]
I apologize. I must have missed it. Was in a panic. ;)

**Comment by MscrmTools** [comment]
No problem, I really need to find a way to display this information directly in the connection wizard
