### ISSUE TITLE
N:N Tool Not Logging Anything

### ISSUE THREAD

**Issue by kjb1030** [MscrmTools/XrmToolBox#429]
I am trying to import a file with the following data example:
Memorial Day 2016,IA001AME

The tool starts but there is never an error or any logs in the window and then it stops. I am currently
using v1.2016.4.28

There is one relationship that I created manually and when I use the export functionality, it does export that relationship.

**Comment by MscrmTools** [comment]
Can you test latest release? There was a bug if you did not change the separator at first

**Comment by kjb1030** [comment]
Same thing. I get the importing screen but no logs ever appear then the importing screen disappears.

Screen shot with version and my relationships:

[cid:image001.png@01D1B8CD.45ABF9C0]

**Comment by MscrmTools** [comment]
I cannot see the image...

**Comment by MscrmTools** [comment]
Sending image by email does not seem to work

**Comment by kjb1030** [comment]
Ok I'll try attaching here in GH

![nnimage](https://cloud.githubusercontent.com/assets/19617821/15628027/cb5d0390-24c3-11e6-86a9-9cf887ee090c.png)

**Comment by MscrmTools** [comment]
I just tested latest version and everything works as expected...

**Comment by MscrmTools** [comment]
proof:
![image](https://cloud.githubusercontent.com/assets/10774317/15628096/c4283466-24f8-11e6-82a0-a36ff016bcee.png)

**Comment by kjb1030** [comment]
Ok, any ideas as to why it might not be working for me? The file has 444 records in, should I try less records? Is it possible it’s a timeout issue?

Thanks for your help!

Kanika

**Comment by MscrmTools** [comment]
No idea, the code is pretty simple, and any error should be displayed in the logs...

If you have time now to share your screen so that I can see how it behaves

**Comment by kjb1030** [comment]
Sure.

**Comment by MscrmTools** [comment]
You can send me an email to tanguy92@gmail.com with your skype id so that we can see the behavior

**Comment by MscrmTools** [comment]
Based on your email answer, custom CRM plugins were blocking import of NN relationships.
I'm closing the issue
