### ISSUE TITLE
PowerBI OptionSet Assistant Refresh Suggestion

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#431]
Upon startup, if the PowerBI Option-set Xref Entity already exists, Parse it to find which enities/optionsets have already been 'chosen' - That should allow the user to 'start' with the existing selections - and then add/remove choices and have the list rebuilt. (This would help by avoiding having to start over each time and potentially miss when an option is updated/added/deleted.)

**Comment by MscrmTools** [comment]
Fixed and available in Plugins Store!

**Comment by mscottsewell** [comment]
Wow - this is great - Thank you Tanguy !
