### ISSUE TITLE
"Power BI Option-Set xRef" entity will not be created in organisation

### ISSUE THREAD

**Issue by CSauter** [MscrmTools/XrmToolBox#433]
Dear team,
thank you for your very perfect tools.
While using Power BI Option-Set Assistent for the first time I get the following error.
1) Connection is working, other plugins of XRMTools are working fine
1b) yes, I have full admin rights on the organisation
2) Starting Power BI Option assistant is fine
3) Loading entities as well as related optionsets for e.g. selected entity incident is fine
4) After clicking on "Create records.." I get the message box that entity "Power BI Option-Set xRef " does not exist and has to be created first. I click on "yes".
5) A very fast yellow message box appears that says "entity created"
BUT
Neither in the entity list of XRMTools nor directly in my organization in "Customization" the new entity is shown.
6) I did a "Public all" in my organisation...nothing
7) I click on "Create records.." again...same procedure as starting with 5.)
8) Clicking on "Delete Power BI Option-Set xRef " leads finally into the message box "There is no Power BI Option-Set xRef entity in this organization"

I use CRM Online 2015 with German language as basic language

Thank you very much for your kind feedback
Carsten

**Comment by MscrmTools** [comment]
Hi, Looks like a bug in the CRM SDK where the assembly send CRM 2016 Update 1 specific message even if you are connected to a CRM 2015 Update 1 or CRM 2016 organization.

I will ask Microsoft, stay tuned

**Comment by CSauter** [comment]
Cool, thank you very much for your fast answer.
I will stay tuned…

Mit freundlichen Grüßen
__________________________________________________
united systems AG
Carsten Sauter
Email: mailto:Carsten.Sauter@united-systems.de

Von: MscrmTools [mailto:notifications@github.com]
Gesendet: Dienstag, 7. Juni 2016 16:14
An: MscrmTools/XrmToolBox <XrmToolBox@noreply.github.com>
Cc: Sauter, Carsten <Carsten.Sauter@united-systems.de>; Author <author@noreply.github.com>
Betreff: Re: [MscrmTools/XrmToolBox] "Power BI Option-Set xRef" entity will not be created in organisation (#433)


Hi, Looks like a bug in the CRM SDK where the assembly send CRM 2016 Update 1 specific message even if you are connected to a CRM 2015 Update 1 or CRM 2016 organization.

I will ask Microsoft, stay tuned

**Comment by mscottsewell** [comment]
In the short term - here's a copy of the entity - you can import it manually -
[PowerBIOptionSetEntity_1_0_0_0_target_CRM_7.0.zip](https://github.com/MscrmTools/XrmToolBox/files/303158/PowerBIOptionSetEntity_1_0_0_0_target_CRM_7.0.zip)

**Comment by CSauter** [comment]
Perfekt. Thank you all for the workaround. It works now with importing the "entity" manually with above solution.

**Comment by MscrmTools** [comment]
Fixed and available in Plugins Store!

**Comment by asaleh101** [comment]
Where is the option set created when looking through Power BI Odata feed?

**Comment by MscrmTools** [comment]
It is a new entity called powerbi something....
