### ISSUE TITLE
Power BI Option-Set Assistant.

### ISSUE THREAD

**Issue by mikeyv10** [MscrmTools/XrmToolBox#434]
Hello,

I've connected my organisations CRM online to the XRM Tool Box, and i want to use the Power BI Option-Set Assistant. However after I load and select the correct entity, then select the option sets i want to map, I 'Create records for selected options sets' but nothing appears to happen.

I look both in CRM and Power Bi and the new entity hasn't been created.

Are you able to help at all.

I've downloaded the latest update.

Regards,
Mike.

**Comment by MscrmTools** [comment]
Hi, Looks like a bug in the CRM SDK where the assembly send CRM 2016 Update 1 specific message even if you are connected to a CRM 2015 Update 1 or CRM 2016 organization.

I will ask Microsoft, stay tuned

**Comment by mscottsewell** [comment]
@mikeyv10 - Take a look at the workaround I offered in the comments here - https://github.com/MscrmTools/XrmToolBox/issues/433 
You can import that customization file and it will create the single entity needed.

**Comment by mikeyv10** [comment]
Hi Scott,

That’s done the trick.

Thanks for your help.

Regards,
Mike.


Michael Violette CRM Administrator and Sales Support Analyst
Achilles
T: +44 (0)1235 838061
E: michael.violette@achilles.com<mailto:michael.violette@achilles.com>
www.achilles.com<http://www.achilles.com/>
Follow us:

[cid:image002.png@01D13346.CD9FBC20]<https://www.linkedin.com/company/achilles-group-limited>

[cid:image003.png@01D13346.CD9FBC20]<https://www.facebook.com/AchillesLtd>

[cid:image004.png@01D13346.CD9FBC20]<https://twitter.com/achillesltd>

[cid:image005.png@01D13346.CD9FBC20]<https://www.youtube.com/channel/UCZvuoz4DElVkoeIy4NwNKhA>

[cid:image006.png@01D13346.CD9FBC20]<http://ity.vc/AchillesGooglePlusLink>

[cid:image007.png@01D13346.CD9FBC20]<http://www.achilles.com/en/industry-blog>

[cid:image008.png@01D13346.CD9FBC20]<vimeo.com/achillesltd/videos>

**Comment by MscrmTools** [comment]
Fixed and available in Plugins Store!
