### ISSUE TITLE
Power BI Option Set Assistant

### ISSUE THREAD

**Issue by CRMProjectGuy** [MscrmTools/XrmToolBox#436]
Everytime I try to use this (CRM online 2016 pre sp1)
It gives me the prompt to create the entity but it never creates the entity.
Therefore no data :(
![capture](https://cloud.githubusercontent.com/assets/19815152/15887195/d089e7b4-2d58-11e6-9c61-c30aefdfb25c.PNG)
Have refreshed , closed and opened the app and crm and also published - still nothing!

**Comment by MscrmTools** [comment]
Did you even look a the issue list? This problem has already been reported twice

It's a bug with CRM SDK assembly (apparently) and I'm waiting for Microsoft feedback

**Comment by mscottsewell** [comment]
:) 

BTW - @CRMProjectGuy you can manually create the entity by importing the customization file I added in one of the other threads. - That could be an interim fix until the issue with the SDK is resolved. (which is likely entirely outside of this project's control)

**Comment by CRMProjectGuy** [comment]
Thx :0)

**Comment by MscrmTools** [comment]
Just found a code workaround! Fix on its way... hope to be able to deliver it tonight

**Comment by MscrmTools** [comment]
Fixed and available in Plugins Store!
