### ISSUE TITLE
PluginStore - Notes become clickable

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#438]
This text becomes clickable:

![image](https://cloud.githubusercontent.com/assets/2572253/16117800/29d13df0-33d4-11e6-99f3-adce66a0469f.png)

But Windows has no idea what it might be...

![image](https://cloud.githubusercontent.com/assets/2572253/16117814/3c3a3d0c-33d4-11e6-9021-7f0ea05ca648.png)

From nuspec file:
`    <releaseNotes>
      Note: These plugins require the FetchXML Builder to be installed to work properly!
    </releaseNotes>
`

**Comment by MscrmTools** [comment]
The program parses the text to an uri. If it succeeds, Then it is clickable.
I guess "note:" is interpreted as a valid uri

**Comment by rappen** [comment]
Guess I have to change to "Please note:" ;)

**Comment by MscrmTools** [comment]
May I close this issue?

**Comment by rappen** [comment]
Yes, I will work around it.
