### ISSUE TITLE
Common way to closing plugins

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#44]
Right now every plugin developer needs to implement call to `CloseTool()` method. And this leads to whole bunch of possible ways how to close plugin: via toolstrip menu button, via regular button, via menu item or context menu for example.

Is it possible to implement common way to close plugins? For example right click on plugin header and selecting item in context menu? Or implement close button `[x]` on every tab header?

**Comment by MscrmTools** [comment]
I'm not a fan of context menu since for now, there will be just one action. And context menu with one action seems ugly to me.
Close button on tab header could be nice but it's all about painting and I'm not an expert. But that is my favorite choice anyway

**Comment by shytikov** [comment]
I would agree on context menu with one item... 

How about keyboard short cut `Crtl+F4`? It seems to be pretty common way to close tabs.

**Comment by MscrmTools** [comment]
Keyboard shortcuts are nice but not visible, so end users could miss them.
So we can use them but we also need a visual way to close tabs

**Comment by shytikov** [comment]
BTW, second command in context menu might be update connection to selected tab. 

We have an option to update connection information for tabs, when we're updating connection in main application, but after closing that window there is no way to update connection on selected plugin.

**Comment by MscrmTools** [comment]
Nice idea but it's still not visible to end users :)
Anyway, we can right some documentation about it

**Comment by daryllabar** [comment]
You can already middle click (scroll wheel button click) on the tab header to close it.

**Comment by MscrmTools** [comment]
does everybody agree to add a context menu on tab header with two options:
* Close
* Update connection

**Comment by rappen** [comment]
:+1: 
Does that mean we might as well remove the Close-buttons within our plugins? That would be nice :)

**Comment by MscrmTools** [comment]
We could remove them, if needed, yes

This is just the only visual indicator on how to close a plugin so I like them anyway. The goal is to avoid confusing users
