### ISSUE TITLE
Cleaning ProgramData folder

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#440]
Perhaps it would be good to implement some cleaning of the XTB ProgramData folder.
It is growing....

![image](https://cloud.githubusercontent.com/assets/2572253/16148000/0b058738-3487-11e6-82d7-4841815b956a.png)

**Comment by MscrmTools** [comment]
Does a "clean cache" button on the Plugins Store dialog is enough?

**Comment by rappen** [comment]
Absolutely :+1:
