### ISSUE TITLE
Resetting Home

### ISSUE THREAD

**Issue by Boydski** [MscrmTools/XrmToolBox#443]
The list of widgets is getting big! But every time I close a widget, Home is scrolled back to the top. Please do not refresh back to top. I like staying where I was. :)

**Comment by MscrmTools** [comment]
Thank for your feedback.
Nevertheless, I did not find any code that reset the Home tab so it will require more investigation to understand why it is behaving this way

**Comment by rajyraman** [comment]
Fixed this and tested this locally. Saving the scroll position and setting it again after tool closes works.
![closetool](https://cloud.githubusercontent.com/assets/5035266/16322734/aac09d42-39e8-11e6-9923-462dfea10239.png)

Made this small change on the MainForm.cs. Will submit PR soon.

**Comment by rajyraman** [comment]
I don't think this made it into v.1.2016.6.29, as it doesn't appear to be working. Sourcecode is different with this version.

![close tool](https://cloud.githubusercontent.com/assets/5035266/16470174/08956c00-3e98-11e6-9806-2a387d3d8db3.png)

**Comment by MscrmTools** [comment]
Crap... I did merge the source... Was the pull request on Main branch?

**Comment by rajyraman** [comment]
The source is from the decompiler. As far as I see, it is in the master though.
