### ISSUE TITLE
Unable to create a system sync filter from a system view

### ISSUE THREAD

**Issue by dsika** [MscrmTools/XrmToolBox#447]
XrmToolBox Version 1.2016.6.29
CRM on-premise Version 8.1.0.359

I'm trying to create a new system sync filter from a system view. But the option is greyed out...

![2016-07-01 07_47_14](https://cloud.githubusercontent.com/assets/791105/16513049/a72765ac-3f61-11e6-8433-df7260f0e7b2.png)

**Comment by MscrmTools** [comment]
Only items syncable with Outlook can create Outlook Template

Accounts are not syncable. Only Contact and activities are.
