### ISSUE TITLE
Sitemap - Specify a view

### ISSUE THREAD

**Issue by sethtbacon** [MscrmTools/XrmToolBox#448]
Based on [Microsoft's documentation](https://msdn.microsoft.com/en-us/library/gg328483.aspx#BKMK_DisplayViewInApplicationUsingSiteMap), you place the following code in the URL location of the sitemap editor.
`/_root/homepage.aspx?etn=<entity logical name >&amp;viewid=%7b<GUID value of view id>%7d`

What I found is that you actually need to remove the "amp;" as the xrmtoolbox automatically adds the "amp;" after the ampersand.

`/_root/homepage.aspx?etn=<entity logical name >&viewid=%7<GUID value of view id>%7d`

I don't think this is an issue but something to be aware of and wanted to document for others.

**Comment by MscrmTools** [comment]
Ok, thank you for this information, it will be added in the wiki when SiteMapEditor documentation will be created

**Comment by ltouro** [comment]
@sethtbacon Thanks for the tip. Saved me some time.

@MscrmTools Just FYI, the documentation seems to be outdated. The issue is also present in the built-in Sitemap Editor. One should not use `amp;` in any case. ```/_root/homepage.aspx?etn=<entity logical name >&viewid=%7<GUID value of view id>%7d``` seems to be the correct template.
