### ISSUE TITLE
Fetch XML / View Record Counter doesn't work for activities

### ISSUE THREAD

**Issue by carterbarry88** [MscrmTools/XrmToolBox#449]
Hi there,

I am busy testing out some of the great features in the XRM Toolbox. I came across the following issue:
<img width="363" alt="fetch xml issue" src="https://cloud.githubusercontent.com/assets/20337773/16651977/51e2a844-443f-11e6-90e2-ba6c74eb4f81.PNG">
This issue happened with all activity entities. The code is expecting "appointmentid" or "taskid" or "phonecallid" for example. It is not able to use the "activityid" as the reference point. 

I am guessing that the code is looking for the "entityname" + "id" as the default reference point. You would just need to update this for activity entities. The tool worked perfectly for non-activity entities.

Regards

Barry

**Comment by rappen** [comment]
I would suggest you use FetchXML Builder (also available in Plugin Store) to compose your own counting query, then you can make sure the query is valid.
Aside from that, the record counting plugin is not published by @MscrmTools, you probably need to find proper channels to get in touch with Mawens Business Solutions that publish the plugin.

**Comment by rajyraman** [comment]
I ran into the same issue when I was testing out the new tool yesterday. Unfortunately, the tool seems to be closed source at the moment, otherwise I would have tried to fix it.

If record count is really all you are after it is much easier to do it in LINQPad.

**Comment by carterbarry88** [comment]
Thanks Both, I was looking for a project to report the issue direct to the developer but couldn't find anything like that. Unfortunately I don't have LINQPad or any LINQ skills so would take longer than what it is worth. Just have to either use the SQL DB or use the Bulk Worfklow Execution Tool. It does a count of records before it executes.

**Comment by rappen** [comment]
In that case, I would really recommend FetchXML Builder... you can use an existing view as query or compose your own.

**Comment by MscrmTools** [comment]
Closing this issue since it is not related to XrmToolBox but a specific third party plugin
