### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by bryce2071** [MscrmTools/XrmToolBox#453]
Hi, 

i cant Export records (5,4 Mio records) to Excel ... 

there Comes the following .NET Framework Error: unhandeld exception.
I tested different values for BatchSize (from 500-5000) and Max Rows per File.

-----

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Ryr.ExcelExport.ExcelExportPlugin.<>c__DisplayClassc.<ExportCurrentViewToExcel>b__8(BackgroundWorker w, DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
XrmToolBox
    Assembly-Version: 1.2016.6.29.
    Win32-Version: 1.2016.6.29.
    CodeBase: file:///D:/XrmToolBox/XrmToolBox.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
XrmToolBox.Extensibility
    Assembly-Version: 1.2016.6.29.
    Win32-Version: 1.2016.6.29.
    CodeBase: file:///D:/XrmToolBox/XrmToolBox.Extensibility.DLL.
----------------------------------------
Microsoft.IdentityModel
    Assembly-Version: 3.5.0.0.
    Win32-Version: 10.0.14366.0.
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
McTools.Xrm.Connection
    Assembly-Version: 1.2016.5.27.
    Win32-Version: 1.2016.5.27.
    CodeBase: file:///D:/XrmToolBox/McTools.Xrm.Connection.DLL.
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly-Version: 1.2016.5.27.
    Win32-Version: 1.2016.5.27.
    CodeBase: file:///D:/XrmToolBox/McTools.Xrm.Connection.WinForms.DLL.
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly-Version: 8.0.0.0.
    Win32-Version: 8.1.0.383.
    CodeBase: file:///D:/XrmToolBox/Microsoft.Xrm.Sdk.DLL.
----------------------------------------
System.Xml.Linq
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.
----------------------------------------
System.ComponentModel.Composition
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll.
----------------------------------------
AndyPopkin.BulkWorkflowExecution
    Assembly-Version: 1.2016.6.7.
    Win32-Version: 1.2016.6.7.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/ANDYPOPKIN.BULKWORKFLOWEXECUTION.DLL.
----------------------------------------
Cinteros.Xrm.CRMWinForm
    Assembly-Version: 2016.7.7.8.
    Win32-Version: 2016.7.07.8.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.CRMWINFORM.DLL.
----------------------------------------
Cinteros.Xrm.FetchXmlBuilder
    Assembly-Version: 1.2016.7.113.
    Win32-Version: 1.2016.7.113.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.FETCHXMLBUILDER.DLL.
----------------------------------------
Cinteros.Xrm.Plugins
    Assembly-Version: 1.2016.6.45.
    Win32-Version: 1.2016.6.45.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.PLUGINS.DLL.
----------------------------------------
Cinteros.Xrm.XmlEditorUtils
    Assembly-Version: 1.2016.7.113.
    Win32-Version: 1.2016.7.113.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.XMLEDITORUTILS.DLL.
----------------------------------------
Cinteros.XTB.BulkDataUpdater
    Assembly-Version: 1.2016.6.10.
    Win32-Version: 1.2016.6.10.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CINTEROS.XTB.BULKDATAUPDATER.DLL.
----------------------------------------
Cinteros.XTB.PluginTraceViewer
    Assembly-Version: 1.2016.6.7.
    Win32-Version: 1.2016.6.7.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CINTEROS.XTB.PLUGINTRACEVIEWER.DLL.
----------------------------------------
Cinteros.XTB.ViewDesigner
    Assembly-Version: 1.2016.6.5.
    Win32-Version: 1.2016.6.5.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CINTEROS.XTB.VIEWDESIGNER.DLL.
----------------------------------------
Colso.DashboardTransferTool
    Assembly-Version: 1.2016.7.7.
    Win32-Version: 1.2016.7.7.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/COLSO.DASHBOARDTRANSFERTOOL.DLL.
----------------------------------------
CRMConsultants.CreateAttributes
    Assembly-Version: 1.2016.5.27.
    Win32-Version: 1.2016.5.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CRMCONSULTANTS.CREATEATTRIBUTES.DLL.
----------------------------------------
CRMConsultants.DuplicateDetectionReport
    Assembly-Version: 1.2016.5.27.
    Win32-Version: 1.2016.5.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CRMCONSULTANTS.DUPLICATEDETECTIONREPORT.DLL.
----------------------------------------
Cube.XRMToolBox.RecordCounter
    Assembly-Version: 1.2016.7.2.
    Win32-Version: 1.2016.7.2.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/CUBE.XRMTOOLBOX.RECORDCOUNTER.DLL.
----------------------------------------
DamSim.SolutionTransferTool
    Assembly-Version: 1.2016.5.1.
    Win32-Version: 1.2016.5.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL.
----------------------------------------
DamSim.ViewTransferTool
    Assembly-Version: 1.2016.6.1.
    Win32-Version: 1.2016.6.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL.
----------------------------------------
Develop1.XrmTBPlugin.RibbonWorkbench2016
    Assembly-Version: 3.0.16.0.
    Win32-Version: 3.0.16.0.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DEVELOP1.XRMTBPLUGIN.RIBBONWORKBENCH2016.DLL.
----------------------------------------
DLaB.AttributeManager
    Assembly-Version: 1.2016.6.1.
    Win32-Version: 1.2016.6.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.ATTRIBUTEMANAGER.DLL.
----------------------------------------
DLaB.Common
    Assembly-Version: 1.0.1.12.
    Win32-Version: 1.0.1.12.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.COMMON.DLL.
----------------------------------------
DLaB.EarlyBoundGenerator
    Assembly-Version: 1.2016.6.1.
    Win32-Version: 1.2016.6.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.EARLYBOUNDGENERATOR.DLL.
----------------------------------------
DLaB.Xrm.2016
    Assembly-Version: 1.1.7.5.
    Win32-Version: 1.1.7.5.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.XRM.2016.DLL.
----------------------------------------
DLaB.Xrm.Entities
    Assembly-Version: 8.1.0.1.
    Win32-Version: 8.1.0.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.XRM.ENTITIES.DLL.
----------------------------------------
DLaB.XrmToolboxCommon
    Assembly-Version: 1.2016.6.1.
    Win32-Version: 1.2016.6.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/DLAB.XRMTOOLBOXCOMMON.DLL.
----------------------------------------
EPPlus
    Assembly-Version: 4.0.5.0.
    Win32-Version: 4.0.5.0.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/EPPLUS.DLL.
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly-Version: 1.2016.6.1.
    Win32-Version: 1.2016.6.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL.
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly-Version: 1.2016.5.3.
    Win32-Version: 1.2016.5.3.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL.
----------------------------------------
MsCrmTools.AccessChecker
    Assembly-Version: 1.2016.5.1.
    Win32-Version: 1.2016.5.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL.
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly-Version: 1.2016.5.1.
    Win32-Version: 1.2016.5.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL.
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL.
----------------------------------------
MsCrmTools.AuditCenter
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL.
----------------------------------------
MsCrmTools.ChartManager
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL.
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly-Version: 1.2016.5.1.
    Win32-Version: 1.2016.5.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL.
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL.
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL.
----------------------------------------
MsCrmTools.FormRelated
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL.
----------------------------------------
MsCrmTools.Iconator
    Assembly-Version: 1.2016.6.3.
    Win32-Version: 1.2016.6.3.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL.
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly-Version: 1.2016.6.1.
    Win32-Version: 1.2016.6.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL.
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL.
----------------------------------------
MsCrmTools.SampleTool
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL.
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL.
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL.
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly-Version: 1.2016.6.1.
    Win32-Version: 1.2016.6.1.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL.
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly-Version: 1.2016.6.3.
    Win32-Version: 1.2016.6.3.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL.
----------------------------------------
MsCrmTools.SolutionImport
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL.
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL.
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL.
----------------------------------------
MsCrmTools.Translator
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL.
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL.
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly-Version: 1.2016.4.27.
    Win32-Version: 1.2016.4.27.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL.
----------------------------------------
MsCrmTools.WebResourcesManager
    Assembly-Version: 1.2016.6.3.
    Win32-Version: 1.2016.6.3.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL.
----------------------------------------
Ryr.ExcelExport
    Assembly-Version: 2.3.0.0.
    Win32-Version: 2.3.0.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/RYR.EXCELEXPORT.DLL.
----------------------------------------
Ryr.SolutionHistory
    Assembly-Version: 2.2.0.0.
    Win32-Version: 2.2.0.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/RYR.SOLUTIONHISTORY.DLL.
----------------------------------------
Ryr.XrmToolBox.EntityImageUpdater
    Assembly-Version: 2.2.0.0.
    Win32-Version: 2.2.0.
    CodeBase: file:///D:/XRMTOOLBOX/PLUGINS/RYR.XRMTOOLBOX.ENTITYIMAGEUPDATER.DLL.
----------------------------------------
System.Net.Http
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll.
----------------------------------------
System.Runtime.Serialization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
----------------------------------------
System.Design
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll.
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly-Version: 8.0.0.0.
    Win32-Version: 8.1.0.359.
    CodeBase: file:///D:/XrmToolBox/Microsoft.Crm.Sdk.Proxy.DLL.
----------------------------------------
MetadataViewProxies_3c5c6aa6-6923-4d7c-b353-c3fc6963e051
    Assembly-Version: 0.0.0.0.
    Win32-Version: 4.6.1584.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll.
----------------------------------------
System.Web.Extensions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll.
----------------------------------------
System.Web
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll.
----------------------------------------
McTools.StopAdvertisement
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///D:/XrmToolBox/McTools.StopAdvertisement.DLL.
----------------------------------------
NuGet.Core
    Assembly-Version: 2.11.1.812.
    Win32-Version: 2.11.1.812.
    CodeBase: file:///D:/XrmToolBox/NuGet.Core.DLL.
----------------------------------------
WindowsBase
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll.
----------------------------------------
System.Data.Services.Client
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Services.Client/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Services.Client.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly-Version: 2.1.0.0.
    Win32-Version: 2.1.0.556.
    CodeBase: file:///D:/XrmToolBox/Microsoft.Xrm.Tooling.Connector.DLL.
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly-Version: 2.24.0.0.
    Win32-Version: 2.24.30411.1323.
    CodeBase: file:///D:/XrmToolBox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL.
----------------------------------------
System.ServiceModel
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll.
----------------------------------------
System.Web.Services
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll.
----------------------------------------
SMDiagnostics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll.
----------------------------------------
System.ServiceModel.Internals
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll.
----------------------------------------
System.Xaml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll.
----------------------------------------
System.ServiceModel.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.ServiceModel.resources.dll.
----------------------------------------
System.xml.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Xml.resources.dll.
----------------------------------------
System.ServiceModel.Channels
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll.
----------------------------------------
System.IdentityModel
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.IdentityModel.Selectors
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel.Selectors/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.Selectors.dll.
----------------------------------------
System.RunTime.Serialization.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1584.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Runtime.Serialization.resources.dll.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by MscrmTools** [comment]
Please contact the owner of this plugin. I did not develop this plugin

**Comment by bryce2071** [comment]
Hi, 

ohh, i thought, the 3rd Party plugins would read here too.
sorry.
thx.
