### ISSUE TITLE
Expected an absolute, well formed http URL without a query or fragment. Parameter name: serviceRoot

### ISSUE THREAD

**Issue by RazDynamics** [MscrmTools/XrmToolBox#454]
Plugin Store Error message;
Expected an absolute, well formed http URL without a query or fragment. Parameter name: serviceRoot

Most likely a Firewall issue but still testing

**Comment by MscrmTools** [comment]
Never seen this message before...
Were you able to do more testing?

**Comment by MscrmTools** [comment]
@RazDynamics Any news?

**Comment by RazDynamics** [comment]
Its no longer occurring, seems to be a security related Group Policy settings that caused after extracting and running the app and maybe blocked a component?

**Comment by MscrmTools** [comment]
Ok, i close The issue then

**Comment by nehakharbanda** [comment]
I am getting the same error after implementing ESO WIF claim based authentication on ASP.NET web application. Can anyone help, what can be the reason of this error ?


[ArgumentException: Expected an absolute, well formed http URL without a query or fragment. Parameter name: serviceRoot]    System.Data.Services.Client.UriResolver.ConvertToAbsoluteAndValidateBaseUri(Uri& baseUri, String parameterName) +141    System.Data.Services.Client.DataServiceContext..ctor(Uri serviceRoot, DataServiceProtocolVersion maxProtocolVersion, ClientEdmModel model) +67    Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper..ctor(Uri serviceRoot, DataServiceProtocolVersion maxProtocolVersion, Func`1 accessTokenGetter, IEnumerable`1 customTypeMappings) +246    Microsoft.Azure.ActiveDirectory.GraphClient.ActiveDirectoryClient..ctor(Uri serviceRoot, Func`1 accessTokenGetter, IEnumerable`1 customTypeMappings) +72    Accenture.Security.Eso.Web.EnterpriseClaimsAuthenticationManager.ConsumeCustomizedSchema(ClaimsPrincipal incomingPrincipal) +204    Accenture.Security.Eso.Web.EnterpriseClaimsAuthenticationManager.Authenticate(String resourceName, ClaimsPrincipal incomingPrincipal) +63    System.IdentityModel.Services.WSFederationAuthenticationModule.SignInWithResponseMessage(HttpRequestBase request) +665    System.IdentityModel.Services.WSFederationAuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs args) +467    System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +139    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +91
--

**Comment by kiranatshinde** [comment]
PM> Install-Package Ninject -Version 3.3.4
Install-Package : Expected an absolute, well formed http URL without a query or fragment.
Parameter name: serviceRoot
At line:1 char:1
+ Install-Package Ninject -Version 3.3.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], ArgumentException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
