### ISSUE TITLE
Issue on connection to a 2015 Spring Online

### ISSUE THREAD

**Issue by daggen** [MscrmTools/XrmToolBox#455]
First, Great tool!

My problem occur when connecting to an Online instance. It seems to pick the wrong instance. My setup is that this environment from start had an extra Sandbox environment but when we reach 25 user we recieved a new Sandbox instance. During a while was both instances active but now are we not using the old one anymore. The old sandbox address was <orgname>test.crm.... but is now changed to  <orgname>testold.crm.... The new sandbox instance has now the <orgname>test.crm... url. In 2015 version of CRM Toolbox I saw all instances in the organization picker and when selecting the relevant instance everything worked out fine. Now in XrmToolbox 1.2016..6.29 I enter the url to the new sandbox but still ends up in the old one. I cannot find anyway for me to connect the right instance.

**Comment by MscrmTools** [comment]
@daggen, Did you succeed to connect?

**Comment by daggen** [comment]
We removed the old test instance from office 365 and it is connecting correctly know.
