### ISSUE TITLE
Solution Transfer Tool for CRM Online 2016 -- has anyone tried it?

### ISSUE THREAD

**Issue by Quacker245** [MscrmTools/XrmToolBox#456]
So when I am going to transfer a solution from one 2016 environment to another, it says:
"This plugin has not been tested with CRM 2016 yet, especially regarding new solution framework"

has anyone proceeded with the transfer? I am wary of trying it without knowing what the risks are specifically.

I also use the customize ribbon solution and don't want to break either of my environments.

Thanks!

**Comment by MscrmTools** [comment]
Yes I did and it worked. I have to remove the mention that it has not been tested
