### ISSUE TITLE
App display scaling issue on Surface Pro 4

### ISSUE THREAD

**Issue by piyushpaliwal** [MscrmTools/XrmToolBox#457]
I have recently started working on an SP4 where the default OS scaling is set to 200% and XrmToolBox renders very poor on it. Totally blurry fonts and icons.
If we change the compatibility setting to disable display scaling then the icons are so tiny and the fonts are huge, it still looks mess.

**Comment by MscrmTools** [comment]
I'm working (and actually developping XrmToolBox) on a Surface Pro 4 too and I don't have this problem.


Only difference I see: I'm using 150% scaling, not 200%


What is your version of XrmToolBox?

**Comment by piyushpaliwal** [comment]
The version is 1.2016.6.29
On 150% scale it blurs the fonts while on 200% it's pixelated. Let me try putting some screenshots (you might have to zoom a little bit in order to see the differences)
**Scale 150%**
<img width="1356" alt="scale_150" src="https://cloud.githubusercontent.com/assets/635693/17405987/47b2fff8-5a7f-11e6-8ecf-c5b69bc78f2d.png">

**Scale 200%**
![scale_200](https://cloud.githubusercontent.com/assets/635693/17405986/47b06cf2-5a7f-11e6-85ce-639568f5a17d.png)

**Comment by MscrmTools** [comment]
Unfortunately, I'm not sure I can do better here...

It seems a limitation with WinForms
