### ISSUE TITLE
Option to close tabs without prompt

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#466]
Super-minor bur super-simple issue.
When I close my tabs I usually know what I am doing, so I just get annoyed by constantly being prompted to confirm closing the tab.
If it could be configured to go away, I would be extremely superhappy and save so many clicks every day.
![image](https://cloud.githubusercontent.com/assets/2572253/17510443/35b0341c-5e1f-11e6-9cc6-c61fc2ca994b.png)

(By the way, I will start working on this right away ;) )

**Comment by daryllabar** [comment]
I thought there was already a configuration for this.  

Also, scroll button click on a tab will close it

**Comment by daryllabar** [comment]
But not without the prompt :(

**Comment by MscrmTools** [comment]
There is a global parameter to avoid this pop up  when closing XTB

**Comment by rappen** [comment]
I will soon have a PR ready for you.

![image](https://cloud.githubusercontent.com/assets/2572253/17514564/94eecd08-5e33-11e6-979a-c94a9978bfed.png)
