### ISSUE TITLE
Suggestion: 'Select All Plugins' toggle in for Plugin store

### ISSUE THREAD

**Issue by bwmodular** [MscrmTools/XrmToolBox#469]
Just a suggestion, but it would be great to be able to toggle Select All/None in the Plugin Store.
When you first download the Toolbox, you are presented with a list of 30+ plugins. If you want to install them all, you have to tick them all individually.

Anyway, keep up the good work - couldn't survive without the toolbox!

**Comment by rappen** [comment]
:+1: Been wanting that too...
