### ISSUE TITLE
Xrmtoolbox V1.2016.6.29 Cant Connect To CRM 2016 On Premise IFD Enabled

### ISSUE THREAD

**Issue by payamiii** [MscrmTools/XrmToolBox#471]
Hi Everyone.
I have a Problem with XRMtoolbox on version 1.2016.6.29. I Have Microsoft CRM 2016 Update 1 On premise and IFD enabled On it, But the Xrmtoolbox can not connect to the CRM.
Please Help me as soon as possible.

**Comment by shytikov** [comment]
It's very hard to troubleshoot issue remotely.

But if you can try to run `XTB` from the source code, you could help us by saying which place it fails, or which error message it throws.

I believe so special knowledge is needed, just download Visual Studio Community Edition, download source code and open it with Visual Studio. Then `F5` and let magic to happen.

**Comment by daryllabar** [comment]
There is also the connection log that can be looked at.  Not sure if you have to turn it on, but it should reside in the same directory as your XrmToolBox.exe.

**Comment by derekfinlinson** [comment]
I'm having the same issue and haven't been able to connect to an IFD deployment of any kind since the 1.2015.11.5 version. I've attached my relevant connection log entry.

[connection log.txt](https://github.com/MscrmTools/XrmToolBox/files/418438/connection.log.txt)

**Comment by MscrmTools** [comment]
The username has to be formatted like Domain\Username in order to work
@derekfinlinson @payamiii Did you try that? did it work?

**Comment by derekfinlinson** [comment]
Entering the domain in the Username field instead of the Domain field worked for me. Does the Domain field only apply if it's a non IFD On-Premise?

**Comment by MscrmTools** [comment]
It seems, yes... I don't know why
