### ISSUE TITLE
The security timestamp is invalid because its creation time

### ISSUE THREAD

**Issue by MaorWithM** [MscrmTools/XrmToolBox#473]
Hey,
I'm getting this erro while i'm trying to connect to a new connection : 
"The security timestamp is invalid because its creation time is in the future"
Any ideas how to solve it? 
thanks.

**Comment by shytikov** [comment]
Are your computer clock is in sync with UTC?

**Comment by MscrmTools** [comment]
@MaorWithM Were you able to test @shytikov suggestion?

**Comment by MscrmTools** [comment]
Closing the issue since @shytikov solution is probably the answer and because @MaorWithM did not answer since more than a month
