### ISSUE TITLE
Split XrmToolBox functionality between several AppDomains

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#474]
This task is summary for #158 and #353 and place where we could discuss details of `AppDomain` implementation.
### Motivation

Why we need  `AppDomains` inside `XrmToolBox` and why it's important to implement them in the right way? 
1. Most obvious reason is **early-bound assemblies**. They are automatically resolved for current `AppDomain` and if two or more plugins in a same `AppDomain` will use early-bound, only one plugin will work properly. Rest will be routed to early-bound types in another assembly, and thus will fail casing types.
2. **Stability**.  Connection problem caused by one plugin actually affects all plugins that shares same connection. Sometimes issues in one plugin makes whole `XTB` fail. It would be nice to be able avoid such behavior in the future.
3. **General trust**. Right now plugins could have same permissions to a user's system as `XTB` executable itself. Basically this means plugin developers have access to everything on users' computers. And plugins also could send that data over the internet. For most of the plugins source code is available, so it's possible to audit them. But now with plugin shop we cannot be 100% sure that compiled binary is built from same source code, as published. And some plugins not providing source code at all.
### Solution

Several `AppDomains` that could be granted different level of privileges and could be reloaded or recycled based on current situation application faced. 
### Implementation

The must:
- [ ] Each plugin instance should communicate with its own CRM client instance isolated in separate `AppDomain` to ensure plugins are not interfering with each other;
- [ ] Make possible for user to unload `AppDomain` — i.e. closing and recycling connections for selected plugin instances.
- [ ] Introduce no breaking changes.

This should solve issue with early-bound assemblies and improve `XTB` stability.

---

Nice to have:
- [ ] `XTB` UI should be executed in separate `AppDomain` with no permission to read system's register or send or read data via Internet;
- [ ] All external communication UI part should perform through "headless" (no UI) Core, which will be auditing these actions and warn user if something suspicions is going on;
- [ ] Plugins should provide information about entities they need to have access, Core will restrict their access to that entities only;

These steps should solve general trust issues.

**Comment by daryllabar** [comment]
Great start here!  The one thing missing is how to overcome issues with WinForms and having separate App Domains.  I know nothing about how to accomplish it, only that I've heard that it's not always possible.  Is there a good explanation somewhere that we could reference, that lists the problems, and the hoops required to overcome them?  

Maybe it would be helpful to create a dummy app that loads "plugins" in separate App Domains to test and verify the solutions to those issues?

**Comment by shytikov** [comment]
Regarding WinForms... It was so long time ago, but I was playing with it as part of #158. It's impossible to add sandboxed control on a form. WinForms internally tries to set `Parent` property of child control with the pointer to parent control. And this is just impossible, since pointer `IntPtr` is not simple type and cannot be serialized to cross AppDomain border.

There are several ways to overcome this: 

* Use `WPF`. Something was done right with these controls, so they could be serialized and passed between AppDomains. The problem is — we don't want to rewrite everything to `WPF`.
* Use "WPF-adapter". It's possible to place `WPF` control on WinForms control, and create placeholder. And then make plugin export `WPF` control which will hold child WinForms control, pass this sandwich through AppDomain border and put it to placeholder. But this looks waaaay too ugly... And this is just theory... I haven't tried it.
* There is true hacker's approach: "rape" `IntPtr` logic as it described here: http://do-the-right-things.blogspot.se/2009/07/cross-appdomain-winform-implementation.html

I will probably try this one first... It looks simplest for me. Though it seems to be that @scottdurow uses variant of second approach in his RibbonWorkbench plugin... Maybe he could also share some WPF magic with us...

**Comment by daryllabar** [comment]
I know this doesn't resolve issues with Motivation #3 listed above, but could we implement our own IOrganizationService that takes requests, and sends them to a different AppDomain for each plugin?  I would think that would eliminate any WPF-adapter, or "rape"-ing involved.

**Comment by shytikov** [comment]
Yes, this is basically whereI was heading to. This is bullet #1 in my Implementation "the must"... I also don't see another option that we could implement without "violence"...

**Comment by daryllabar** [comment]
So based on https://msdn.microsoft.com/en-us/library/system.appdomain.aspx?f=255&MSPPError=-2147217396:

```C#
class Module1
{
    public static void Main()
    {
        // Get and display the friendly name of the default AppDomain.
        string callingDomainName = Thread.GetDomain().FriendlyName;
        Console.WriteLine(callingDomainName);

        // Get and display the full name of the EXE assembly.
        string exeAssembly = Assembly.GetEntryAssembly().FullName;
        Console.WriteLine(exeAssembly);

        // Construct and initialize settings for a second AppDomain.
        AppDomainSetup ads = new AppDomainSetup();
        ads.ApplicationBase = AppDomain.CurrentDomain.BaseDirectory;

        ads.DisallowBindingRedirects = false;
        ads.DisallowCodeDownload = true;
        ads.ConfigurationFile = 
            AppDomain.CurrentDomain.SetupInformation.ConfigurationFile;

        // Create the second AppDomain.
        AppDomain ad2 = AppDomain.CreateDomain("AD #2", null, ads);

        // Create an instance of MarshalbyRefType in the second AppDomain. 
        // A proxy to the object is returned.
        MarshalByRefType mbrt = 
            (MarshalByRefType) ad2.CreateInstanceAndUnwrap(
                exeAssembly, 
                typeof(MarshalByRefType).FullName
            );

        // Call a method on the object via the proxy, passing the 
        // default AppDomain's friendly name in as a parameter.
        mbrt.SomeMethod(callingDomainName);

        // Unload the second AppDomain. This deletes its object and 
        // invalidates the proxy object.
        AppDomain.Unload(ad2);
        try
        {
            // Call the method again. Note that this time it fails 
            // because the second AppDomain was unloaded.
            mbrt.SomeMethod(callingDomainName);
            Console.WriteLine("Sucessful call.");
        }
        catch(AppDomainUnloadedException)
        {
            Console.WriteLine("Failed call; this is expected.");
        }
    }
}

// Because this class is derived from MarshalByRefObject, a proxy 
// to a MarshalByRefType object can be returned across an AppDomain 
// boundary.
public class MarshalByRefType : MarshalByRefObject
{
    //  Call this method via a proxy.
    public void SomeMethod(string callingDomainName)
    {
        // Get this AppDomain's settings and display some of them.
        AppDomainSetup ads = AppDomain.CurrentDomain.SetupInformation;
        Console.WriteLine("AppName={0}, AppBase={1}, ConfigFile={2}", 
            ads.ApplicationName, 
            ads.ApplicationBase, 
            ads.ConfigurationFile
        );

        // Display the name of the calling AppDomain and the name 
        // of the second domain.
        // NOTE: The application's thread has transitioned between 
        // AppDomains.
        Console.WriteLine("Calling from '{0}' to '{1}'.", 
            callingDomainName, 
            Thread.GetDomain().FriendlyName
        );
    }
}
``` 

We just need to create an class that

1. Inherits from MarshalByRefObject,
2. Implements the IOrganizationService.  
3. We'll also need to get the Plugin Assembly to use to Load the EarlyBound Types.  This can use the current IEarlyBoundProxy interface to request this information from the plugin.
4. Settings required to connect to CRM.

The XTB should be able to create this instance (DomainIsolatedOrganizationService?) in a new AppDomain, then call an initialize method to pass it the connection information and the EarlyBoundProxy Types (or perhaps make this a constructor?).  It will need to load the ProxyTypes Assembly into it's domain.  Then this object should be able to handle all Organization Requests to CRM.

Does that work?

**Comment by MscrmTools** [comment]
Hi,
I performed some tests with WPF and nothing change here... It seems just not possible to use UI elements (UserControl) from separate AppDomain in the main AppDomain.

I read a lot of blog articles or forums questions and answer is always => not possible

Isolation works if no UI is involved thought

**Comment by MscrmTools** [comment]
Closing the issue (third one I'm closing today :)) since we cannot implement AppDomains with UI components
