### ISSUE TITLE
Add ability to qucikly reset search criteria when searching plugins in the main window

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#475]
This is minor, but could be nice to have.

When search criteria was entered and no plugins was found, `XTB` shows window with completely empty tab only. Unless you paid attention to search field content, it's not obvious why no plugins showed up.

My suggestion, in case if search didn't return any results, show text label, something like: "Searching for `query` did not matched any plugins installed. Please redefine the criteria, reset it, or download some new plugins from our plugin store" (and some buttons or links, that will reset search criteria or open plugins store).

I believe it would be also usable in search result show link to plugin store, or link to results from plugin store. So user will know, that despite there are no matching pluings locally, but there are some online! And he can go there and download them.

**Comment by MscrmTools** [comment]
Yes, it is a nice to have feature, you are correct!

I will work on this

**Comment by MscrmTools** [comment]
what about this screen?

![image](https://cloud.githubusercontent.com/assets/10774317/17803584/a9838e5e-65f7-11e6-956b-5a929631a523.png)

**Comment by shytikov** [comment]
I really like "Open Plugins Store" part and "reset search filter" is also very accurate. But text in red is a bit too scary. Definitely person should be alarmed if he tried to find plugin named `ghdhjfghj`. But mostly because cats should not be allowed on a keyboard :) 

Maybe we can write same text in more calm manner? What other UI experts think? @rappen? @daryllabar?

**Comment by rappen** [comment]
I am ok with the text, except grammatically incorrect "did not matched", it should be "did not match". :)

**Comment by MscrmTools** [comment]
I can use the same color used for the Open Plugins Store text

**Comment by shytikov** [comment]
I have found alignment issue.

"or reset search filter" test feels to be aligned more to right comparing "Open Plugins Store" text. I believe all text should be aligned using the same axis. I understand that most probably an image and it's whole with bag... but I believe text will be more accurate if we align it properly.

**Comment by shytikov** [comment]
Same color would be nice! Could we use same blue everywhere? Since we already have two different blue colors?

**Comment by MscrmTools** [comment]
Sure we can use same blue everwhere (logo, text and link)

For text alignment, it won't be easy... I think I will let it this way :)

**Comment by MscrmTools** [comment]
![image](https://cloud.githubusercontent.com/assets/10774317/17804236/e8a911f0-65fa-11e6-8c62-ac45cb4b6967.png)

**Comment by shytikov** [comment]
It looks quite OK for me! It would be nice to allow text "or reset the search filter" be moved a bit to the left, but other than that, looks more very sexy I must say :)

**Comment by MscrmTools** [comment]
it's all center aligned, text and image (as Open Plugins Store + logo is one image)

**Comment by MscrmTools** [comment]
For this issue, I do not implement searching plugins store when filtering.
That could be another issue to create
