### ISSUE TITLE
Bulk Form Attribute Manager - Loading entities does not clear existing

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#476]
Minor issue, of course, but clicking Load Entities to refresh the content duplicates the entities...

![image](https://cloud.githubusercontent.com/assets/2572253/17774470/155c07fe-6554-11e6-995b-a01c24ee9a67.png)

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.FormRelated #1](https://github.com/MscrmTools/MsCrmTools.FormRelated/issues/1) via [**ZenHub**](https://www.zenhub.com/)
