### ISSUE TITLE
Unable to open Plugin store on 1.2016.8.23

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#478]
It shows following error message:

```
---------------------------

---------------------------
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
---------------------------
OK   
---------------------------
```

How to reproduce:
1. Update older version of the `XTB` via build-in `AutoUpdater`
2. Start `XTB`
3. Start `Plugin Store`
4. Error message will be shown;

**Comment by shytikov** [comment]
Ok, strange... now I cannot reproduce that...

**Comment by blackphoenixinf** [comment]
had the same error on first app start, after closing and reopening it`s gone and store works fine.

**Comment by shytikov** [comment]
So something is wrong there anyway...

**Comment by MscrmTools** [comment]
It occurs ONLY after and auto update... Don't know why

**Comment by shytikov** [comment]
Excuse my ignorance, but do we have some kind logging functionality, that we can enable to at least find out place where this exception happened?

I believe it once again something to do with SDK DLL versions... or any other DLL versions...

**Comment by MscrmTools** [comment]
No we don't...

The error occurs during MEF composition AFAIK

**Comment by MscrmTools** [comment]
A new faulting plugins detection has been added in the latest version
