### ISSUE TITLE
Plugins are able to register their shorcuts application wide

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#479]
Here is the case inspired by: https://github.com/Innofactor/PluginRegistration/issues/8

It looks like if plugin declares keyboard shortcut, it become available application wide. Even if plugin's tab is not selected. Thus, it's possible to trigger plugin's functionality from invalid context. Or even hijack useful functionality calls :)

**Try yourself**: open `WebResource Manager` and any other plugin, make that plugin active, and call WebResource Manager functionality (for example, upload `Ctrl + U`).

**Proposed solution**: Instruct plugin developers to export as metadata keyboard shortcuts they want to expose application wide. Register all these shortcuts when plugin is loaded to tab. If tab is deselected, remove bindings to shortcuts. Add bindings again, as soon as tab is selected once again.

**Comment by daryllabar** [comment]
Wouldn't it be easier to have some way to check if the current plugin is open, then in any keyboard bindings, immediately return if not open?

**Comment by rappen** [comment]
Agree with @daryllabar on this. Each plugin should make sure context is valid to handle the key-events triggered.

**Comment by shytikov** [comment]
I was thinking of this as easiest solution, but I'm afraid that plugin maybe won't be able to capture all events that needed, sine they are happening in parent objects. I believe it's possible, but could be a bit fragile.

But! Instead we could implement two events on every plugin: register shortcuts and unregister them. And core could trigger them on the right moment. For example.

**Comment by MscrmTools** [comment]
So, a new interface, again 😄

**Comment by shytikov** [comment]
So maybe we could avoid it if developers would export information about shortcuts they want to register globally?

**Comment by daryllabar** [comment]
As a part of the Early Bound Hack, I was able to reflectively remove an event handler.  If you're just concerned with the on key press and key up and key down events, it wouldn't be that hard to remove them on lost focus of the plugin, and enable on focus.

**Comment by MscrmTools** [comment]
I'm implementing a new interface to intercept keyboard event. Events will be send to the active plugin only, if it implements this new interface : ```IShortcutReceiver```
