### ISSUE TITLE
Audit Center - Add unsaved changes warning or persist when changing entities

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#481]
In the audit center, if I configure the attributes on one entity and then select another entity to configure the changes on the first are lost (unless I save and publish before selecting the new entity.) - there's no warning or recognition that the current entity's attribute selections are lost when changing to a new entity.

Either persist the attribute selections when changing from one entity to the next and let the user click 'Apply Changes' once **all** selections are made - or warn the user before changing entities that there are unsaved changes to the current entity that must be published or lost.

**Comment by MscrmTools** [comment]
I tested this again and found out that the only action not kept (only visually) is an attribute added to audit. 
A removed attribute is kept.
So, I will fix this soon

**Comment by MscrmTools** [comment]
Available in Plugins Store
