### ISSUE TITLE
Error Importing Translations

### ISSUE THREAD

**Issue by chadwatson77** [MscrmTools/XrmToolBox#486]
I've seen the following error when importing translations.  Just exported Attributes from our Sandbox environment for one entity (opportunity) and then tried to reimport without changing anything to make sure it was going to work before working on the translations (other than removing the base fields)

![image](https://cloud.githubusercontent.com/assets/22104913/18399316/4836caaa-769e-11e6-8741-dde19de87e7f.png)

Any thoughts on this?

**Comment by MscrmTools** [comment]
Can you check with MetadataBrowser if the entity with ObjectTypeCode 10115 exists on your organization?

**Comment by chadwatson77** [comment]
It does not show up within the Metadata Browser.

**Comment by MscrmTools** [comment]
It seems an old component that used to exist is still referenced in some records of your organization whereas it has been removed
