### ISSUE TITLE
Does Bulk Entity Updater support new Customer type fields?

### ISSUE THREAD

**Issue by Customery** [MscrmTools/XrmToolBox#487]
With CRM 2016 Update 1, there is a new field data type: Customer. Customer fields can accept account or contact references and can be added to custom entities.
I have added a Customer field to a custom entity and now I would like to use Bulk Entity Updater to set all the fields on the form to read-only.
I have connected to my org, retrieved the list of entities but get an error trying to retrieve the attributes of my custom entity: "Error while retrieving entity: Found an integer attribute with unrecognized format: new_customeridtype."
My guess is that this tool hasn't been updated to work with the new Customer field data types. Has anyone got it working for a custom entity containing a Customer field?

**Comment by MscrmTools** [comment]
Hi Neil,
I just tested the same scenario (in CRM OnPremise 2016 SP1) and did not faced the error message...

Is it still happening?

**Comment by MscrmTools** [comment]
@Customery just pinging in case you don't receive all updates
