### ISSUE TITLE
Windows 10 - GetMaxPriviledgeDepthForUser failed...

### ISSUE THREAD

**Issue by osadder** [MscrmTools/XrmToolBox#490]
using windows 10; I am not able to use any tool in XrmToolBox. once I open the tool and get the following error:

SecLib::GetMaxPrivilegeDepthForUser failed. Returned hr = -2147209463, User: fef9f920-9d3f-e611-8138-c4346bac3acc

This is CRM OL and the user that I am logging in as is an administrator

**Comment by MscrmTools** [comment]
Is your administrator account in the top business unit of CRM?

**Comment by osadder** [comment]
it is... I am able to connect now using the unique org name instead of the friendly URL as suggested in the article below. 

https://github.com/MscrmTools/XrmToolBox/wiki/Connecting-to-a-Microsoft-Dynamics-CRM-deployment

the interesting thing is that now I am not able to connect to the same org using v1.2015.9.22... I get a different error but I can just upgrade the XrmToolbox unless you want the error for research/edification purposes.

thanks for the quick response!
