### ISSUE TITLE
Possibility to select if it include sorting or not

### ISSUE THREAD

**Issue by daggen** [MscrmTools/XrmToolBox#491]
First, Great Tool! this have saved me a lot!

A suggestion for improvements would be if it is possible to select if sorting should also be included in the replication or not. This could be done by add a extra checkbox among the buttons which say "replicate sorting"[X]. 

Please continue working on this tool as this is one of the biggest time saving plugins, at least when there are many views.

**Comment by MscrmTools** [comment]
Hi,
Can you precise the plugin you are talking about?

**Comment by daggen** [comment]
View Layout Replicator

**Comment by MscrmTools** [comment]
I just checked the code and tried again the tool => Sorting IS included as part of the replication

**Comment by MscrmTools** [comment]
I close this issue. Do not hesitate to reopen it if I misunderstood something

**Comment by daggen** [comment]
Yes, it is included. 

My scenario is that I have about 40 Opportunity Views Systems
I want all System Views to have same columns, including position, width. 
But 10 should be sorting on Est. closing date. 10 on Actual closing date. 20 on Opportunity Name. 

(1)Hence when I like to update which columns should be available, position and width I like to runt the tool on all 40 views without changing which field it does the sorting on.
(2)The other scenario is when I would like to change the sorting also. In my case would it be natural to change the secondary sorting field for only 10 of the views at a time. 

Scenario (2) is available today and it is really working out fine for me. Scenario (1) on the other hand is not possible.

My idea is that in ribbon with the buttons you add ha checkbox "[ ] Include sorting" and if it is ticket then should sorting be replicated. If not, then only the columns. Current version is sorting always included.

Please let me know if I have misunderstood the tool
