### ISSUE TITLE
Form Libraries Manager Window Resize issue

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#492]
:(

![image](https://cloud.githubusercontent.com/assets/9728423/18632645/790ad61c-7e46-11e6-936f-932560471d29.png)

**Comment by MscrmTools** [comment]
Easy one :)

Let me move it to the appropriate repository

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.FormRelated #2](https://github.com/MscrmTools/MsCrmTools.FormRelated/issues/2) via [**ZenHub**](https://www.zenhub.com/)
