### ISSUE TITLE
Problem connecting when error in Default Organisation

### ISSUE THREAD

**Issue by cint-mats** [MscrmTools/XrmToolBox#493]
Me and a colleague had problems connecting to a organisation while other colleagues could connect just fine. It seems the problem was that Default Organisation in MSCRM_CONFIG database was pointing to a no longer existing organisation for the accounts with the problem. 

I'm not sure if the connection handling of XTB can lookout for and mitigate this problem, or if it's code external to the project that is the only way to handle this situation. Anyway, a heads up to at least check if anything can be done, or just add to list of things to check when troubleshooting connection problems.

**Comment by MscrmTools** [comment]
It looks more like a problem in the deployment than something XrmToolBox can handle. Nevertheless, do you still have the corresponding error message?

**Comment by cint-mats** [comment]
Unfortunately not, but as I remember, it was very generic and short. Can try to recreate, but earliest next week.
