### ISSUE TITLE
Can't launch plugin after connecting successfully with oauth to CRM Online 2016

### ISSUE THREAD

**Issue by talynone** [MscrmTools/XrmToolBox#495]
Using XrmToolBox v1.2016.8.23

Connecting to CRM Online 2016 via oauth. As stated in the FAQ saving username/password fails for an oauth connection, so I don't specify them, which prompts me for credentials on connect.

When I launch a plugin and it asks to connect to my organization first, if I say yes a successful connection occurs then I get the error "An error occured when trying to display this plugin: Object reference not set to an instance of an object." When I try to launch any other plugin the same error immediately displays.

However if I open a plugin tab first and tell it not to connect and then connect manually after the plugin tab is open and tell xrmtoolbox refresh the open plugins tabs with the current connection, then the open plugins work, but I still can't open any new plugin tabs (same error as above).

I've read about a similar issue in the issues section but the work-around solution of storing/saving the username/password is not an option for my required oauth connection.

**Comment by MscrmTools** [comment]
It will require some time before I can get an environment where I can connect using OAuth so be patient but I will look at this

**Comment by talynone** [comment]
Great, thanks for the update.

**Comment by MscrmTools** [comment]
I succeeded to get an Oauth enabled environment! And found the bug. 
I hope to release the fix in the upcoming september release

**Comment by talynone** [comment]
Awesome, thanks for the quick response. When my next paycheck clears I'll donate what I can to help support this project.
