### ISSUE TITLE
Update does not force restart, allows for plugin store crash

### ISSUE THREAD

**Issue by joenewstrom** [MscrmTools/XrmToolBox#497]
Upon updating to Latest Xrm Toolbox version, The application was automatically relaunched. However, opening the plugin store caused a fatal crash in the application. Restarting the application appears to have resolved the issue. I will test as I update the toolbox on my other devices to see if I can repro.

**Comment by MscrmTools** [comment]
Hi @joenewstrom, this is a known issue... The application is restarted but I don't know why it requires a second restart...

**Comment by MscrmTools** [comment]
Is it still happening? I did not see it lately
