### ISSUE TITLE
Error while using Easy Translator

### ISSUE THREAD

**Issue by NickPl** [MscrmTools/XrmToolBox#498]
I was translating a custom field in Opportunity. When I imported the file, i got this error:

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: The blc_total_amount_base field has an invalid XAML formula definition. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault).

blc_total_amount_base is a calculated field. Ever since, I can't import any translation in Opportunity using the tool.

**Comment by smakken** [comment]
Same for me.

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: The new_weightedrevenue_base field has an invalid XAML formula definition. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault).

Please address this issue because I can't import any translation of the attributes in Opportunity.

**Comment by MscrmTools** [comment]
can you confirm the error occur on a calculated/rollup field?

**Comment by smakken** [comment]
Yes, it's a calculated field of the type Currency, so including the base fields.

![2016-12-06 14_27_22-formulas](https://cloud.githubusercontent.com/assets/15250233/20927202/beaa73b4-bbc0-11e6-82a9-ac176aac62cc.png)

BTW: I'm using v1.2016.10.2 of XrmToolBox

**Comment by MscrmTools** [comment]
Ok, I will make some test when I have time

**Comment by MscrmTools** [comment]
So the problem is with Rollup field, not calculated ones...

Still need to find what is the problem exactly

**Comment by smakken** [comment]
In my case it's the base currency field that is related to a calculated field that is mentioned in the error message:
The new_weightedrevenue_base field has an invalid XAML formula definition.

![2016-12-07 15_56_01-calculated field - weighted revenue - microsoft dynamics crm - internet explorer](https://cloud.githubusercontent.com/assets/15250233/20972677/f6f721ec-bc95-11e6-9641-e97f9f1872c5.png)

**Comment by MscrmTools** [comment]
Ok, this problem seems to be on Microsoft side, so I can't do anything. I just added in latest versions logging so that we have the error message but the import goes on

**Comment by hamidrzeinali** [comment]
I love this plugin a lot.
I wrote a comment in this page (https://www.xrmtoolbox.com/plugins/MsCrmTools.Translator/) but I did not get any answer.
can anyone help me to solve my problem ?

I want to translate filters in Advance Find but I cannot.
For Example : In Advance Find how to translate filters for Date Time Fields ? (Today,tomorrow, last x days and ...)

Thanks

**Comment by MscrmTools** [comment]
The plugin page is made to rate the plugin, not asking a question.

As for your question, please use the appropriate repository to ask it: https://github.com/MscrmTools/MsCrmTools.Translator/issues
