### ISSUE TITLE
Sync problem between XrmToolBoxPackage and MscrmTools.Xrm.Connection packages

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#499]
Creating a new plugin using latest nuget packages gives the following error when trying to open the plugin user control (form):
![image](https://cloud.githubusercontent.com/assets/2572253/19109035/d7a78c7e-8af3-11e6-9889-5e21b914707a.png)

It seems XrmToolBox.exe from the XTB package is compiled for Connection project of May version, but September version is included in the package.
Trying back and forth with older versions of the different packages to get it working now...

**Comment by MscrmTools** [comment]
I reviewed the source code and references to connection projects do use September version! I don't know why it is still referencing May version when executing

**Comment by MscrmTools** [comment]
Found!
The problem is on XrmToolBox.Extensibility project
Fixing it...

**Comment by rappen** [comment]
Woop woop! 👍
