### ISSUE TITLE
Main application loses focus after showing splash screen

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#5]
This is really minor thing, but quite annoying when you developing plugin. 

I setup Visual Studio to start `XrmToolBox` executable each time after build to test functionality I've implemented. And actually `XrmToolBox` acts the same running stand-alone as well.

`XrmToolBox` starts, shows splash screen and then disappears from sight. It is still in task bar, but user need to click its icon to bring it back to focus state.

It's minor, if user starts `XrmToolBox` only once, but if it is done in consequence (like during plugin debugging, it's quite annoying to search `XrmToolBox` among running programs). Sometimes it might confuse inexperienced user, since expected behavior of the program that had been run is to stay on top of any other programs that is currently running.

Maybe it's specific it my environment. I need somebody else to confirm the issue. I'm using Windows 8.1.

**Comment by rappen** [comment]
Same issue for me - very minor, but *oh so annoying*! :)

**Comment by shytikov** [comment]
:100:%

**Comment by MscrmTools** [comment]
Yes, I'm aware about this problem... But did not find any solution last time I worked on it...

I need to find out something...

**Comment by rappen** [comment]
I bet @shytikov can find the solution to that one too... ;)

**Comment by shytikov** [comment]
@rappen Challenge accepted!

**Comment by MscrmTools** [comment]
Excellent!

I obviously accept this pull request :)
