### ISSUE TITLE
Error while opening a webresource

### ISSUE THREAD

**Issue by con-ssc** [MscrmTools/XrmToolBox#501]
I get an initial error when I open a webresource in the webresource manager

![image](https://cloud.githubusercontent.com/assets/8189808/19230111/ed078f64-8ed2-11e6-87a8-431d67f3f855.png)

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.WebResourcesManager #12](https://github.com/MscrmTools/MsCrmTools.WebResourcesManager/issues/12) via [**ZenHub**](https://www.zenhub.com/)
