### ISSUE TITLE
Allow to explicitly disconnect and to reconnect respectively

### ISSUE THREAD

**Issue by myfairsyer** [MscrmTools/XrmToolBox#502]
(Maybe sort of related to #221?)

**Comment by MscrmTools** [comment]
Can you give a scenario where this makes sense to have these two features?

**Comment by myfairsyer** [comment]
When posting this I had connection issues I could only solve by reconnecting.
IIRC the VPN got lost and reestablished but I had to reconnect in XTB manually.

**Comment by MscrmTools** [comment]
I guess there is no need to disconnect. You already can click on connect button to reapply a connection
