### ISSUE TITLE
Hide plugins in the store

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#503]
Some plugins are just not interesting to have.
Especially since anyone can now put anything on NuGet without any usability qualification etc.

So it would be nice to be able to hide plugins in the store, so I don't get notifications of new versions of not interesting plugins.

Today I just download anything new to get rid of the notification, and then hide them in the plugin list, which feels "wrong" :)

**Comment by MscrmTools** [comment]
Notifications are only for installed plugins, so I guess you only should have to not install everything to not have notifications you don't care about.
But I can add some "I'm not interested" option for plugins in the store

**Comment by rappen** [comment]
That would be nice 👍

**Comment by MscrmTools** [comment]
This feature will be provided in November release
