### ISSUE TITLE
Uninstall plugins

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#504]
Now that installing plugins is so smooth and easy, an equally smooth way to uninstall them (and thus not be prompted to upgrade when upgrades are available) would be nice.
Related to #503.

**Comment by MscrmTools** [comment]
Sure. Only problem (still related to AppDomain) is that it will require to restart XTB to be applied

**Comment by MscrmTools** [comment]
This feature will be provided in November release
