### ISSUE TITLE
Lockdown Components for Power Users

### ISSUE THREAD

**Issue by rksharma24** [MscrmTools/XrmToolBox#509]
Hi,
As per comments on Gitter, it would be great if we could make the tool available to Power Users by being able to lockdown the add-ins for them. (i.e Only release the 'safe' components and not give the capability to download new ones).

Thanks,
Rocky.

**Comment by daryllabar** [comment]
Wait, we are trusting a user not to completely hose a CRM instance with one of the "safe" components, but not to know which plugins are "safe"?

Not sure that is possible...

**Comment by rksharma24** [comment]
Hi,
There are some components which are useful for CRM online  like 'export to excel' which are useful for large data sets in the online environment. Also Record Counter, Access Checker, Metadata Browser, Privilege Discovery. These are non-destructive components. IT would be ideal if we could install only those component we choose by distributing a locked down version.
Just a thought, otherwise we have to resort to either finding alternate tools or building them in-house.

**Comment by skfd** [comment]
Here comes the "XrmToolBox Pro" feature!

**Comment by rksharma24** [comment]
Hi,
This is so we can do a controlled release of what we allow users to do (mainly to fill in the gaps of CRM online). We don't want users downloading and attempting to use modules that have not been tested in the corporate environment or against all combinations of the CRM Security model.
However one possibility could be that the access to the modules are actually defined in the CRM Security Roles? That would work.

Regards,
Rocky.

**Comment by MscrmTools** [comment]
I do agree with Daryl, most of "destructive" plugins require administrator or customizer privileges.
Don't give these privileges to your users and the worse you'll get is they encounter error messages

No need to implement anything in XrmToolBox
