### ISSUE TITLE
Running xrm toolbox in a virtual server with no internet access, error on startup

### ISSUE THREAD

**Issue by svedjehammar** [MscrmTools/XrmToolBox#51]
Running xrm toolbox in a virtual server with no internet access.
Error on startup
************** Exception Text **************
System.Net.WebException: The remote name could not be resolved: 'api.github.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

Is internet access required to run the toolbox?

**Comment by MscrmTools** [comment]
Thanks for reporting. I will handle these errors to not report anything if no connection is available
