### ISSUE TITLE
XrmToolBox crashes during connecting to the organisation

### ISSUE THREAD

**Issue by michaelmittermair** [MscrmTools/XrmToolBox#510]
During connecting to the organisation, some times the tool crashes completely. After restarting it, the connection to the organisation is working.

The Exception from the event viewer:

```
Application: XrmToolBox.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at McTools.Xrm.Connection.ConnectionManager.LoadConnectionsList()
   at McTools.Xrm.Connection.ConnectionManager.fsw_Changed(System.Object, System.IO.FileSystemEventArgs)
   at System.IO.FileSystemWatcher.OnChanged(System.IO.FileSystemEventArgs)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

```
Faulting application name: XrmToolBox.exe, version: 1.2016.9.24, time stamp: 0x57e69127
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18340, time stamp: 0x57366075
Exception code: 0xe0434352
Fault offset: 0x0000000000008a5c
Faulting process id: 0x3e1c
Faulting application start time: 0x01d22b502e5b86f7
Faulting application path: C:\Tools\CRM\XrmToolBox\XrmToolBox.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: 89631229-9743-11e6-82d5-54ee75342b76
Faulting package full name: 
Faulting package-relative application ID: 
```

We are using CRM 2016 On-Premise (8.1.0.359)

**Comment by MscrmTools** [comment]
The problem seems to occur when loading the connections list...
I would need a fully reproducable scenario to debug and fix

**Comment by michaelmittermair** [comment]
What do you need to repoduce the scenario?

My Steps:
1. Start the XrmToolBox
2. Click on "Connect to CRM"
3. Select the Item (it's an OnPremise connection)
4. Application crashes

After starting the application again, I'm able to connect

**Comment by MscrmTools** [comment]
Does it still occur in 1.2017.1.11 version?

**Comment by michaelmittermair** [comment]
Today I got the same error again.

**Comment by medevil84** [comment]
Ok, I think i've understand where is the bug. The connection file is read while the update of the "LastUsedOn" (caused by the "Connect") method is in progress. 
The bug isn't always reproducible because the connection file is probably cached and reading/writing is faster. 
Maybe we can place a lock on CrmConnection.cs so write and read do not occur at the same time?

**Comment by michaelmittermair** [comment]
seems to be fixed
