### ISSUE TITLE
Unable to Open XrmToolBox Application

### ISSUE THREAD

**Issue by altmank** [MscrmTools/XrmToolBox#511]
Hello, I could use some help figuring out why I can't get XrmToolbox to open. I downloaded the 9.24 version and when I run the app (as administrator) the process executes but I never see any UI.

The process stays open in the background until I force close it.

I confirmed I unblocked the zip before extracting, it did not help.

I also confirm I have the following: Microsoft .Net Framework 4.5.2, Windows Identity Foundation. 

The Auto-updater program fails to open as well but it actually crashes upon load unlike the main application.

**Comment by MscrmTools** [comment]
As discussed on Gitter, this is an issue related to a software control implemented in the company
