### ISSUE TITLE
Role Updater - Activities not loaded

### ISSUE THREAD

**Issue by BorisTch** [MscrmTools/XrmToolBox#512]
On the plugin "Role Updater", when loading the privileges available, the activities related privileges does not appear (or is not at the right place in the alphabetical order).

XrmToolbox version : 1.2016.9.24
CRM Version : 8.1.0.359

**Comment by MscrmTools** [comment]
you are correct, in my French organization, it is displayed as Quick Campaign privilege

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.SecurityRelated #1](https://github.com/MscrmTools/MsCrmTools.SecurityRelated/issues/1) via [**ZenHub**](https://www.zenhub.com/)
