### ISSUE TITLE
Hanging on Loading Web resources

### ISSUE THREAD

**Issue by AntoineGauthier** [MscrmTools/XrmToolBox#514]
The latest version _(v1.2016.10.2)_ of the XTB leaves the SiteMap Editor as well as the Iconator plugin hanging on the Loading Web resources popup. There might be some other plugins affected by the issue.

![capture](https://cloud.githubusercontent.com/assets/10197231/19761034/8f4f67ce-9c34-11e6-8bcb-e197828c3730.PNG)

The data seem to be correctly loaded though only the popup stays open.

I double checked with an other version _(1.2016.6.29)_ of the XTB using the same SiteMap Editor plugin version and no issues there which leads me to believe that the issue is not directly plugin related.

**Comment by MscrmTools** [comment]
Can you try to download again this version? I updated it quite quickly but maybe not enough

Then test again

**Comment by AntoineGauthier** [comment]
It worked indeed. My bad. Thanks for the quick reply :)

**Comment by daryllabar** [comment]
That was actually my bad for the bug!
