### ISSUE TITLE
Fresh installation of XRMToolbox 1.2016.10.2 - Did not start File not load McTools.Xrm.Connection

### ISSUE THREAD

**Issue by asifhuddani** [MscrmTools/XrmToolBox#515]
XrmToolBox v1.2016.10.2 - while opening the first time getting below error.

My assumption - Default zip did not contain XrmToolBox.exe.config
![error](https://cloud.githubusercontent.com/assets/10806603/19763805/d1e51cf4-9c0d-11e6-953f-baefe9136249.jpg)

**Comment by MscrmTools** [comment]
You are correct!

I forgot that one!! I will update the package asap

**Comment by MscrmTools** [comment]
The package has been updated!

Can you download it again?

Thanks for reporting

**Comment by asifhuddani** [comment]
I checked with new download and it's working fine.

**Comment by asifhuddani** [comment]
Yeah sure I will download, but I already placed old config and check its working for me.

Let me check and tell you.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Oct 27, 2016 at 4:08 PM +0530, "MscrmTools" <notifications@github.com<mailto:notifications@github.com>> wrote:


The package has been updated!

Can you download it again?

Thanks for reporting

-

**Comment by asifhuddani** [comment]
Yes it's working fine with new download.

Thanks
Asif Huddani

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Oct 27, 2016 at 4:08 PM +0530, "MscrmTools" <notifications@github.com<mailto:notifications@github.com>> wrote:


The package has been updated!

Can you download it again?

Thanks for reporting

-

**Comment by MscrmTools** [comment]
Thanks for the confirmation
