### ISSUE TITLE
Error when Connecting to IFD CRM - Value cannot be null. Parameter name: s

### ISSUE THREAD

**Issue by altmank** [MscrmTools/XrmToolBox#517]
Connecting to an IFD instance of CRM 2016. I can setup a connection and it says successful in the wizard section but when trying to connect outside of the connection setup, I get the error:

> Value cannot be null. Parameter name: s

I'm using V1.2016.10.2 of XrmToolBox.

**Comment by daryllabar** [comment]
This isn't for when generating Early Bound Entities using the Early Bound Generator is it?

**Comment by altmank** [comment]
Hi @daryllabar, I was using the "Connect To CRM" from the main program interface, not within a plugin.

**Comment by daryllabar** [comment]
OK, just making sure.  There is a known bug with that plugin.

**Comment by altmank** [comment]
Using the connect drop-down from the bottom left of the interface, I actually get an exception version of the error. That exception text is as follows:

> 
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at XrmToolBox.MainForm.<ManageConnectionControl>b__24_3(Object sender, ConnectionFailedEventArgs e)
   at McTools.Xrm.Connection.ConnectionManager.SendFailureMessage(String failureReason, Object parameter)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by altmank** [comment]
Here is my config that is failing, for confidentiality I replaced the values in the config with placeholders. 

`    <ConnectionDetail>
      <AuthType>Federation</AuthType>
      <ConnectionId>daf6e6cc-1c9d-4614-a36b-ef276f374b65</ConnectionId>
      <ConnectionName>Test Environment</ConnectionName>
      <ConnectionString></ConnectionString>
      <UseConnectionString>false</UseConnectionString>
      <IsCustomAuth>false</IsCustomAuth>
      <UseIfd>true</UseIfd>
      <UseOnline>false</UseOnline>
      <UseOsdp>false</UseOsdp>
      <UserDomain><AD_domain></UserDomain>
      <UserName>kmaltman</UserName>
      <UserPassword></UserPassword>
      <SavePassword>false</SavePassword>
      <UseSsl>true</UseSsl>
      <ServerName><subdomain>.<domain>.com</ServerName>
      <ServerPort>443</ServerPort>
      <OriginalUrl>https://<subdomain>.<domain>.com</OriginalUrl>
      <Organization><orgName></Organization>
      <OrganizationUrlName><orgName></OrganizationUrlName>
      <OrganizationFriendlyName><orgName></OrganizationFriendlyName>
      <OrganizationServiceUrl>https://<subdomain>.<domain>.com/XRMServices/2011/Organization.svc</OrganizationServiceUrl>
      <OrganizationDataServiceUrl>https://<subdomain>.<domain>.com/XRMServices/2011/OrganizationData.svc</OrganizationDataServiceUrl>
      <OrganizationVersion>8.1.0.359</OrganizationVersion>
      <HomeRealmUrl></HomeRealmUrl>
      <Timeout>1200000000</Timeout>
      <WebApplicationUrl></WebApplicationUrl>
      <LastUsedOn>01/01/0001 00:00:00</LastUsedOn>
    </ConnectionDetail>`

**Comment by MscrmTools** [comment]
Please do not fill domain name but instead provide username format as domain\login

**Comment by altmank** [comment]
Hi @MscrmTools, I adjusted the config to use domain in my username field but the exact same issue persists.

**Comment by MscrmTools** [comment]
Can you look into the connection log file that should be located in XrmToolBox root folder? As the stacktrace talks about connection failure, maybe the connection did not succeed after all

**Comment by altmank** [comment]
The content of the log file is this:

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : OrganizationWebProxyClient is null

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #31](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/31) via [**ZenHub**](https://www.zenhub.com/)
