### ISSUE TITLE
Plugin download counters lie to me

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#518]
As I am updating my plugins regularly, I realize that the counters in the Plugin Store (and on the web page) show aggregated download numbers, and releasing many new versions gives me unearned good credit.
I would suggest displaying download counters for a single version, either the most popular version or the latest version.

**Comment by shytikov** [comment]
Yes, but...

Your leadership motivates me to come up with a new functions for my plugins. So I can update them too. And get more download count points.

**Comment by MscrmTools** [comment]
I need to update code (easy for web site, not sure for c# version)

**Comment by rajyraman** [comment]
You crack me up @rappen. I believe that you deserve to be in the top of the leader board. So I am voting against this change.

**Comment by MscrmTools** [comment]
www.xrmtoolbox.com is up to date with latest release download count

**Comment by rappen** [comment]
So - now I can just wait for the brand new release of Plugin Trace Viewer to start climbing the charts after starting over from zero again! :)

**Comment by MscrmTools** [comment]
Not sure Nuget.Core allows to get download count by version

**Comment by shytikov** [comment]
@rappen you need to accept your destiny — to be first. No matter of what.
