### ISSUE TITLE
Suggest adding the plugin 'filename' to the metadata window in the plugin store.

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#519]
I wanted to delete a particular plugin - but wasn't sure which file to delete - adding the filename to the metadata in the plugin store would make it easy to find / delete the plugin file.

**Comment by MscrmTools** [comment]
Or even better, add a remove button to uninstall à plugin

**Comment by shytikov** [comment]
Somewhat related to #513

**Comment by MscrmTools** [comment]
Absolutely! I'm implementing #513 too

**Comment by MscrmTools** [comment]
@rappen sure it's on its way (I'm currently working on it - almost finished)

**Comment by MscrmTools** [comment]
A global Uninstall feature will be provided in November release
