### ISSUE TITLE
Error in Import/Export tools

### ISSUE THREAD

**Issue by antoinedionne** [MscrmTools/XrmToolBox#52]
Hey !

I downloaded the XrmToolBox recently but I have some problem with it.

I unblocked the .zip file, then I extracted the files into a folder.
I ran the software, created a connection, from there, everything works.

When I chose the import/export N:N relation Tools, I get an error.

My Windows is in french so I will try to translate it generally.

It say:
An error occured on the HTTP response at
http://*****/MicrosoftDynamics/XRMServices/2011/Organization.svc.
The reason can be that the link at the terminal point use something else that is not HTTP.
It can also be due to a ignored context from the HTTP (maybe because the service is stopped)
For more info check the server log.

I am using dynamics On-Premise (still in trial) and I don't know that to do right now -_-

Thanks for any help!

**Comment by MscrmTools** [comment]
Hi Antoine,
If it's easier for you to speak in French, no problem :)

I never saw this error message (please post the french version, if possible) but if you provide me the complete french error message, I can dig into it

**Comment by antoinedionne** [comment]
Hey !
Thank you for your quick answer :)

It's actually when I click on "Load Metadata" that I get the error.

But my Partner resetted the server and now it's working! I don't know what was in conflict but if it ever do it again, I will post the error message here.

Thank you and have a nice day !

**Comment by MscrmTools** [comment]
Nice to hear it's working fine for you now
