### ISSUE TITLE
Feature Request: Clone Connection

### ISSUE THREAD

**Issue by con-ssc** [MscrmTools/XrmToolBox#521]
I have relatively often the need to duplicate a connection because only the org name changes or the server address. It would be nice if there was an option to duplicate a connection just to tweak some thing.

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #13](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/13) via [**ZenHub**](https://www.zenhub.com/)
