### ISSUE TITLE
PostBuildEvent "libz.exe inject-dll" will fail if TargetPath contains spaces

### ISSUE THREAD

**Issue by Peter-Coppens** [MscrmTools/XrmToolBox#523]
Build of "MsCrmTools.ChartManager.csproj" will fail on copy step in PostBuildEvent if $(TargetPath) contains spaces.

Please surround $(TargetPath) with double quotes in the PostBuildEvent node:
`<PostBuildEvent>"$(SolutionDir)packages\LibZ.Tool.1.2.0.0\tools\libz.exe" inject-dll --assembly "$(TargetPath)" --include MsCrmTools.ChartManager.dll --include ICSharpCode.TextEditor.dll
      copy /y "$(TargetPath)" "$(SolutionDir)XrmToolBox\$(OutDir)Plugins\$(TargetFileName)"
</PostBuildEvent>`

Error message:
> The command ""D:\Tools\Microsoft\CRM 2013 Tools\XrmToolBox\SourceCode\XrmToolBox-master\packages\LibZ.Tool.1.2.0.0\tools\libz.exe" inject-dll --assembly "D:\Tools\Microsoft\CRM 2013 Tools\XrmToolBox\SourceCode\XrmToolBox-master\Plugins\MsCrmTools.ChartManager\bin\Debug\MsCrmTools.ChartManager.dll" --include MsCrmTools.ChartManager.dll --include ICSharpCode.TextEditor.dll
      copy /y D:\Tools\Microsoft\CRM 2013 Tools\XrmToolBox\SourceCode\XrmToolBox-master\Plugins\MsCrmTools.ChartManager\bin\Debug\MsCrmTools.ChartManager.dll "D:\Tools\Microsoft\CRM 2013 Tools\XrmToolBox\SourceCode\XrmToolBox-master\XrmToolBox\bin\Debug\Plugins\MsCrmTools.ChartManager.dll"
" exited with code 1.	MsCrmTools.ChartManager

**Comment by MscrmTools** [comment]
it's not really an issue but ok, let's do this...

Personnaly, I never create folder with spaces for my developments. That's why I never get this kind of error :)

**Comment by daryllabar** [comment]
I've noticed, I had to fix most of the build scripts back in the day!
