### ISSUE TITLE
How do I unhash the password in my connections file?

### ISSUE THREAD

**Issue by nzhome** [MscrmTools/XrmToolBox#525]
in the file mscrmtools2011.config  I see these lines, how can I convert these hashes from and to the real password?

```
<UserName>my_svc_account@realm1.onmicrosoft.com</UserName>
<UserPassword>123456789034kk10qYZG4g==</UserPassword>
```

**Comment by nzhome** [comment]
I found this on another website for converting the password to and from the hash in the config file.

string str = CryptoManager.Decrypt(this.userPassword, "MsCrmTools", "Tanguy 92*", "SHA1", 2, "ahC3@bCa2Didfc3d", 256);

using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace McTools.Xrm.Connection
{
    internal class CryptoManager
    {
        public CryptoManager()
        {
        }

        public static string Decrypt(string cipherText, string passPhrase, string saltValue, string hashAlgorithm, int passwordIterations, string initVector, int keySize)
        {
            byte[] bytes = Encoding.ASCII.GetBytes(initVector);
            byte[] numArray = Encoding.ASCII.GetBytes(saltValue);
            byte[] numArray1 = Convert.FromBase64String(cipherText);
            byte[] bytes1 = (new PasswordDeriveBytes(passPhrase, numArray, hashAlgorithm, passwordIterations)).GetBytes(keySize / 8);
            ICryptoTransform cryptoTransform = (new RijndaelManaged()
            {
                Mode = CipherMode.CBC
            }).CreateDecryptor(bytes1, bytes);
            MemoryStream memoryStream = new MemoryStream(numArray1);
            CryptoStream cryptoStream = new CryptoStream(memoryStream, cryptoTransform, CryptoStreamMode.Read);
            byte[] numArray2 = new byte[(int)numArray1.Length];
            int num = cryptoStream.Read(numArray2, 0, (int)numArray2.Length);
            memoryStream.Close();
            cryptoStream.Close();
            return Encoding.UTF8.GetString(numArray2, 0, num);
        }

        public static string Encrypt(string plainText, string passPhrase, string saltValue, string hashAlgorithm, int passwordIterations, string initVector, int keySize)
        {
            byte[] bytes = Encoding.ASCII.GetBytes(initVector);
            byte[] numArray = Encoding.ASCII.GetBytes(saltValue);
            byte[] bytes1 = Encoding.UTF8.GetBytes(plainText);
            byte[] numArray1 = (new PasswordDeriveBytes(passPhrase, numArray, hashAlgorithm, passwordIterations)).GetBytes(keySize / 8);
            ICryptoTransform cryptoTransform = (new RijndaelManaged()
            {
                Mode = CipherMode.CBC
            }).CreateEncryptor(numArray1, bytes);
            MemoryStream memoryStream = new MemoryStream();
            CryptoStream cryptoStream = new CryptoStream(memoryStream, cryptoTransform, CryptoStreamMode.Write);
            cryptoStream.Write(bytes1, 0, (int)bytes1.Length);
            cryptoStream.FlushFinalBlock();
            byte[] array = memoryStream.ToArray();
            memoryStream.Close();
            cryptoStream.Close();
            return Convert.ToBase64String(array);
        }
    }
}

**Comment by daryllabar** [comment]
I have to do this exact thing for the Early Bound Generator.  The [DLaB.XrmToolboxCommon.dll adds an extension](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/blob/master/DLaB.XrmToolBoxCommon/Extensions.cs) that does this:

**Comment by MscrmTools** [comment]
@nzhome yes, that is the way to unhash the password
