### ISSUE TITLE
Query with Alias does not work

### ISSUE THREAD

**Issue by MilindKothavade** [MscrmTools/XrmToolBox#526]
Hi,

I have created simple fetchxml query with alias for attributes and it was giving expected result set but suddenly it stopped fetching the details. Upon removal of alias name for attributes it started working.

Have verified query several times and it appears to be totally okay.
My observation is sometime it works properly with alias and sometime it does not work with alias.

Am i supposed to make any change in the query or XRMTOOLBOX tool to make query workable with alias for attributes.

Pls. advise.

Thanks.

**Comment by MscrmTools** [comment]
Hi,
In which plugin are you trying this?

**Comment by MilindKothavade** [comment]
I have tried it in XRMTOOLBOX tool.

**Comment by MscrmTools** [comment]
sure but what plugin in XrmToolBox? XrmToolBox itself does nothing but exposing plugins

**Comment by rajyraman** [comment]
Possibly FetchXml builde or FetchXml Tester? @rappen can probably answer this if it is FXB.

**Comment by rappen** [comment]
My experience of this says alias is only supported for attributes when you have an aggregate query.
It used to work for non-aggregate queries too, but that "bug" was "fixed" in recent versions of CRM.

**Comment by MscrmTools** [comment]
As @MilindKothavade does not answer question and did not provide enough information (CRM version, Plugin used, etc.) I'm closing the issue. @MilindKothavade can reopen it if needed
