### ISSUE TITLE
Plugin folder Path Backwards compatibility

### ISSUE THREAD

**Issue by scottdurow** [MscrmTools/XrmToolBox#528]
I'm in the process of updating the Ribbon Workbench to support the November Release of the XrmToolbox.

I've come up against a challenge due to the plugin folder location having moved to the User's ApplicationData folder.
I need a way of retrieving the plugin folder location that is backward compatible with earlier version of the XrmToolbox and so can't use the new Paths static class. 

Rather than call `Paths.PluginsPath` (because it's not available in older versions) should I use:
```
var userApplicationDataFolder = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
var pluginFolderPath =  Path.Combine(userApplicationDataFolder, "MscrmTools", "XrmToolBox");
```

I'm worried about the /overridepath argument - when is that used?

Guidance would be appreciated!

**Comment by scottdurow** [comment]
Also - what is the best method to use to get the XrmToolbox version so I can determine the plugin path correctly:

```System.Reflection.Assembly.GetEntryAssembly().GetName().Version.ToString()```
or 
```System.Windows.Forms.Application.ProductVersion```

**Comment by MscrmTools** [comment]
I guess it is (from your plugin) `System.Reflection.Assembly.GetExecutingAssembly().GetName().Version` which is the version of the currently executed application

**Comment by scottdurow** [comment]
Ok I'll use the `GetEntryAssembly` - both return the same

What about the code above - should I use that to get the plugin folder without the need for Paths? Or if I compile against the new assemblies will that work for the older versions of the toolbox?

**Comment by MscrmTools** [comment]
No you can't use this code. The problem is not the code itself but plugins, with older version, are still located in XrmToolBox root folder, so your code should not change for older version of XrmToolBox.

If newer version, then use `Paths.PluginsPath`

Why is it important to use `Paths.PluginsPath` instead of the code above? because user can decide to override the storage location by adding a `OverridePath` parameters when running XrmToolBox and `Paths` class will still give you the appropriate location

**Comment by MscrmTools** [comment]
Ok, it seems more complicated (but not impossible) than expected

You can use this kind of code in your plugin class to determine what control to display. The first one can implement any class of the new version whereas the second one can only use class from older version 

```C#
 public class Plugin : PluginBase
    {
        /// <summary>
        /// This method return the actual usercontrol that will
        /// be used in XrmToolBox
        /// </summary>
        /// <returns>User control to display</returns>
        public override IXrmToolBoxPluginControl GetControl()
        {
            if (Assembly.GetExecutingAssembly().GetName().Version > new Version(1, 2016, 11, 0))
            {
                return new SampleTool();
            }
            else
            {
                return new SampleTool2();
            }
        }
```

**Comment by scottdurow** [comment]
I have got around the problem using reflection.
This is my code to get the Plugin folder path so that it is backward compatible.
```c# 
var pluginFolder = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"Plugins");
if (System.Reflection.Assembly.GetEntryAssembly().GetName().Version >= new Version("1.2016.11"))
{
    // November 2016 release of XrmToolbox stores plugins in the User's AppData folder
    pluginFolder = (string)Type.GetType("XrmToolBox.Extensibility.Paths,XrmToolBox.Extensibility")
        .GetProperty("PluginsPath").GetValue(null,null);
}
```
Note that I am use `GetEntryAssembly` not `GetExecutingAssembly`
