### ISSUE TITLE
Plugins Folder

### ISSUE THREAD

**Issue by micheleietri** [MscrmTools/XrmToolBox#529]
When i install any plugin the folder "plugin" isn't created in the xrmtoolbox folder. Where i can find it?

**Comment by MscrmTools** [comment]
Hi,
Plugin folder (along with other files) is now located in your roaming profile (c:\users\your_login\MscrmTools\XrmToolBox\Plugins)

**Comment by DanielHolth** [comment]
Thank you for an awesome tool. Btw, I found the folder here... C:\Users\[your_login]\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\
Very handy if you are deploying for a very strict onprem customer.
