### ISSUE TITLE
Open working folder

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#531]
Sometimes you just don't know where you started XTB or where it finds its plugins etc.
So it would be great to display the application folder and the current root working folder in the Settings dialogue.
If they are clickable as well, to actually open the folders would be even better.

**Comment by daryllabar** [comment]
+1

**Comment by MscrmTools** [comment]
I knew I had to provide this feature but did not have time to do so...

**Comment by MscrmTools** [comment]
What if ?

![image](https://cloud.githubusercontent.com/assets/10774317/20978778/7063d8d6-bcaa-11e6-8ea9-99636a059608.png)

**Comment by rappen** [comment]
Sweet :)
Perhaps a note that if the overridepath contains spaces it must be contained in double quotes?

Maybe it is just me, but having the path to the exe folder would be nice too.... when you encounter problems with updates or whatever.

**Comment by MscrmTools** [comment]
Makes sense! Will add it too
