### ISSUE TITLE
Webresource manager: Load Web resources should traverse all subfolders

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#532]
Webresources manager does not traverse all subfolders to grab the valid webresources when you use the File->Load Webresources functionality. For e.g if this is my folder structure:
```
├───testfolder
│   ├───nested1
│   │   └───app
│   │       └───css
│   │               test.css
│   │               
│   └───nested2
│       └───js
│               test.js
```
there is no easy way to get this into CRM using web resources manager without manually recreating the folder structure. Load web resources should all subfolders by default. It will also be handy to have a "Load Web resource from zip file" functionality.

WebResourceUtility, that is distributed with the SDK searches through subfolders by default.

**Comment by MscrmTools** [comment]
I never add any trouble to load that kind of structure... in an existing virtual folder with drag and drop.

Your structure is not loaded because no folder looks like a root folder (i.e. Ending with underscore character) and a root folder ha to exist

**Comment by rajyraman** [comment]
Never realised it till now. I thought Load Webresources automatically creates the root. Created a new root +drag drop works beautifully. Case of me being stupid I guess.

**Comment by MscrmTools** [comment]
This shows one of the problem with XrmToolBox and its plugins in general: lack of documentation to explain people what they can achieve with it and how...

Anyway, may I close this issue?

**Comment by rajyraman** [comment]
Thank you Tanguy. Please close.
