### ISSUE TITLE
Error Duplicate Detection

### ISSUE THREAD

**Issue by marucan007** [MscrmTools/XrmToolBox#533]
![error](https://cloud.githubusercontent.com/assets/24530645/21112710/98a1a968-c05b-11e6-887d-9e9f4dbf7767.JPG)

This is the error I receive when the Duplicate Detection is done 100% and trying to generate report.  Thanks!

**Comment by MscrmTools** [comment]
I'm not the author of this tool. Please report issues to the plugin owner
