### ISSUE TITLE
Incorrect Spelling on Connection Window

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#534]
Specify is spelled "speficiy" on the IFD Connection form.
![image](https://cloud.githubusercontent.com/assets/9728423/21210930/10226192-c24d-11e6-9e74-dea17760d103.png)

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #15](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/15) via [**ZenHub**](https://www.zenhub.com/)
