### ISSUE TITLE
Referencing XrmToolBox.Extensibilitywhile starting xrmtoolbox

### ISSUE THREAD

**Issue by dotnetprog** [MscrmTools/XrmToolBox#535]
I am trying to develop my own tool and I get this Exception below when trying to test it.
I have followed instruction for above 2015.x.x.x Version .

When my ssembly plugin is signed , i get this. If it is not signed , I get no error but i dont see my tool displayed in the list although is in the folder : C:\Users\MyProfile\AppData\Roaming\MscrmTools\XrmToolBox\Plugins
```
System.Reflection.ReflectionTypeLoadException: Multiple Exception Occured Attempting to Intialize the Plugin Manager
Exception 1
System.IO.FileLoadException: Impossible de charger le fichier ou l'assembly 'XrmToolBox.Extensibility, Version=1.2016.11.3, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Un assembly avec un nom fort est requis. (Exception de HRESULT : 0x80131044)
Nom de fichier : 'XrmToolBox.Extensibility, Version=1.2016.11.3, Culture=neutral, PublicKeyToken=null'
```
Here's some screenshots:
![toolbox](https://cloud.githubusercontent.com/assets/24593889/21238402/eb257710-c2d0-11e6-9b5d-2c636b1608ce.png)
![toolbox2](https://cloud.githubusercontent.com/assets/24593889/21238406/ececeae2-c2d0-11e6-9233-7c78a27a2f64.PNG)
![toolbox3](https://cloud.githubusercontent.com/assets/24593889/21238408/ee5f17c4-c2d0-11e6-93c6-3d6e4ef4ed8d.PNG)
![toolbox4](https://cloud.githubusercontent.com/assets/24593889/21238411/f00659c0-c2d0-11e6-885b-6c099e79922a.PNG)
![toolbox5](https://cloud.githubusercontent.com/assets/24593889/21238412/f1854644-c2d0-11e6-842b-a50896a8e561.PNG)

**Comment by rappen** [comment]
Hi - have you followed the wiki regarding debugging setup?
https://github.com/MscrmTools/XrmToolBox/wiki/Debug-your-plugins-during-development

(I finished it only hours ago, so you might have missed it :) )

**Comment by rappen** [comment]
...also... I noticed today that if you omit the two lines specifying the icon, the plugin does not appear at all:
```
    ExportMetadata("SmallImageBase64", ""),
    ExportMetadata("BigImageBase64", ""),
```
Try including them.

**Comment by MscrmTools** [comment]
@dotnetprog as you might have noticed, the assemblies are not signed. I need to think about what the impacts are if insigned the assemblies

Is that a requirement that you assembly is signed?

**Comment by dotnetprog** [comment]
Not at all, I unsigned it and added these 2 lines: 
`ExportMetadata("SmallImageBase64", ""),
    ExportMetadata("BigImageBase64", ""),`
And it solved my problem.

Thanks for help guys.
