### ISSUE TITLE
Display XTB dependency version for plugin in Plugins Store

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#537]
NuGet packages for XTB plugins contain a dependency specifying minimum version of XTB required.
Until the actual dependency is implemented to prevent incompatible versions, it would be nice to display the dependency version in the info window for the plugin.

**Comment by MscrmTools** [comment]
Preview of UI for this issue

![image](https://cloud.githubusercontent.com/assets/10774317/21358952/cae67c7a-c6da-11e6-9eb7-2e1c8091bb61.png)

**Comment by mscottsewell** [comment]
I like it ... as long as it doesn't encourage me to Experience the Interactive Service Hub, Get the App for Dynamic, Enable SharePoint Integration, Turn on Insights, etc. every time I open it. :scream:

**Comment by MscrmTools** [comment]
lol, no it is just for plugin selected and not compatible
