### ISSUE TITLE
Multi Thread Not Working Perfectly

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/XrmToolBox#538]
Hi
i don't know if this is a problem or it's just like this 
In case you ware using the Web resource Manger and you are publishing a web resource 
while this time if you open any thing else both action will keep loading 
my example i open the StieMap and i start loading SiterMap Both action keep running for long time (Loading and publishing) 
So is this a bug or miss use from my side

**Comment by MscrmTools** [comment]
What version of XrmToolBox?

**Comment by aboodh95** [comment]
v1.2016.11.4

**Comment by MscrmTools** [comment]
Publishing does affect the whole organization performance so it might be related...

**Comment by aboodh95** [comment]
This what was in my mind
but i want to inform you 
Thanks
