### ISSUE TITLE
Difficulty connecting to Dynamics Financials

### ISSUE THREAD

**Issue by zBestData** [MscrmTools/XrmToolBox#539]
Hi,

Does the tool box work with the new Financials Version released in November?  I am having difficulty establishing a connection.  What am I missing? 

 The user is setup in dynamics as an admin.  

**URL**: ( I have tried these ):
https://ORGANIZATION.financials.dynamics.com:7048
https://ORGANIZATION.financials.dynamics.com:7048/MS/ODataV4 https://ORGANIZATION.financials.dynamics.com:7048/MS/ODataV4/Company('ORGANIZATION')

**User Name**:  Have tried both User and User@domain.com

![2016-12-19 1](https://cloud.githubusercontent.com/assets/14015883/21316986/28756adc-c5d1-11e6-8130-94a214f4271a.png)

**Comment by MscrmTools** [comment]
Financials is not made of Dynamics CRM components so the answer is no, it is node compatible or even made for

**Comment by zBestData** [comment]
Ok.   Thanks1
