### ISSUE TITLE
Delegated administrator

### ISSUE THREAD

**Issue by StephaneSeguin** [MscrmTools/XrmToolBox#540]
Hello,

I have a Partner delagate access to my customer CRM. The authentofication of the XRMtoolBox, is always retreving data for our internal CRM and not the customers. Even if the URL is different.

Is this something that can be fixed?

regards,

**Comment by MscrmTools** [comment]
This kind of issue is related to the CRM configuration, not how XrmToolBox works.

Can you confirm you are connecting to an off deployment? If so, you might want to review the configuration

**Comment by StephaneSeguin** [comment]
Hi, Has a partner we are approved by the Customer to access their system has a delegate administrator. This gives us access to all customer organisation with our personal login information. But In the XRM toolbox alway connect me to our company CRM organisation. It doens't look at the URL provided.  There is no CRM configuration for this, it's a Office 365 delegate access.
