### ISSUE TITLE
Manage NN Relationships - Import is not successful using GUIDs

### ISSUE THREAD

**Issue by rsmorkos** [MscrmTools/XrmToolBox#542]
After the latest update to the plug-in, I'm seeing the following 2 issues:

When using the GUIDs to create the import file to create the NN relationship - 
1. Sometimes I get an error saying that the GUID/record was not found even though the record does exist, and I do verify that the GUID is typed correctly ( I copy past it, and I open the record to look at it as well to make sure it's inactive or deleted somehow)

2. If the GUIDs are found by the plug-in, I see a message saying 'Success', but when I go to the record itself, I don't see an NN relationship created and it's not showing in the sub-grid on the form

**Comment by MscrmTools** [comment]
Afaik the latest version only adds some debug information but does not change the way data are imported

**Comment by MscrmTools** [comment]
Closing the issue since you opened one in the appropriate repository
