### ISSUE TITLE
Allow for Changing Passwords on Multiple Connections

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#544]
I have Dev, QA, Stage, and Prod environments, all with the same AD credentials.  I have to change my password every 60 days... it would be nice to be able to select multiple connections, and change the passwords for all in one shot.

**Comment by MscrmTools** [comment]
Possible! For connection "issues" could you create an issue in the appropriate repository (MscrmTools.Xrm.Connection)?

**Comment by daryllabar** [comment]
Totally.
