### ISSUE TITLE
PowerBi Option Set Entity not visible in CRM Dynamics 2016 Online update 1

### ISSUE THREAD

**Issue by lagrottan** [MscrmTools/XrmToolBox#545]
We have been using the PowerBi option set utility in xrmtoolbox since its first release.  Previously we used it with Dynamics CRM online 2015 and it seemed to work well.  We have also upgraded 2015 CRM online to 2016 and it continues to work.  However, when we use CRM online 2016 Update 1 as the base, the PowerBi Option set entity is not visible in CRM Dynamics online customizations, nor can PowerBi Desktop find it.  We are able to connect to the correct org, and create the powerbi option set and update the values.  Everything seems to work fine with no errors.  However, when you go into Dynamics the entity is not there.    i have now seen this multiple times on different CRM online 2016 update 1 environments.

**Comment by MscrmTools** [comment]
Opened in the appropriate repository

**Comment by lagrottan** [comment]
This can be closed.  This is not a bug with the plugin or xrmtoolbox necessarily.  This is what is happening - we have a Dynamics 2016 U1 online environment that initially had a URL for abc.crm.dynamics.com.  We then renamed it to xyz.crm.dynamics.com.   Then, we had to rename it back to abc.crm.dynamics.com.   As it turns out, simply connecting the toolbox to abc.crm.dynamics.com was not connecting to the correct tenant.  Even though you could connectthe toolbox  to abc, it was the wrong abc environment - like a duplicate on the Microsoft side.  I suppose with the renaming of URL's it created 2 ABC CRM databases on the Microsoft side.  We instead connected the toolbox using the OrgID instead of ABC and everything works fine.
