### ISSUE TITLE
Sorting columns in the store popup

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#546]
When I clicked twice on any column header in the XrmToolBox store popup, I got this error.

![xrmtoolbox store error](https://cloud.githubusercontent.com/assets/5035266/21532046/c0cceed2-cda0-11e6-9c71-c2c4780a3666.png)

**Comment by rappen** [comment]
Related to this (I think) is that the first time you click a column, it always sorts descending.
I think through most XTB plugins too...
