### ISSUE TITLE
Sitemap Editor Error - URGENT!

### ISSUE THREAD

**Issue by Breitenkamp-DK** [MscrmTools/XrmToolBox#547]
I have previously removed the 'Service' section from my sitemap but now I need it again. I receive an error when trying to add default subarea to the sitemap. Please see attached file. What to do?
![2017-01-09_10-29-04](https://cloud.githubusercontent.com/assets/25004132/21762065/02557e28-d657-11e6-8d26-ce31c394f36d.png)

CRM version is: 8.1.0.549
Sitemap editor: 1.2017.1.4

**Comment by MscrmTools** [comment]
What is the CRM organization version?

**Comment by Breitenkamp-DK** [comment]
CRM version is: 8.1.0.549
Sitemap editor: 1.2017.1.4

**Comment by MscrmTools** [comment]
Ok, i will review the program and fix this

**Comment by Breitenkamp-DK** [comment]
excellent, thx

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.SiteMapEditor #6](https://github.com/MscrmTools/MscrmTools.SiteMapEditor/issues/6) via [**ZenHub**](https://www.zenhub.com/)
