### ISSUE TITLE
Bug: Importing connection file to fresh installation is failing

### ISSUE THREAD

**Issue by daggen** [MscrmTools/XrmToolBox#548]
First off, great tool!

Secondly. I had some issues with my Xrmtoolbox and it didn't update. This issue was due to own modifications. So I exported all my connections and removed everything else, even the folders in AppData, before downloading a fresh zip file and starting over. I open "manage connection" and add existing file and can now see all my connections. Problem now is that every time I open Xrmtoolbox and use the button in the lower left corner it is empty until I switch connection file under connections or Manage connection.  I've tried to copy the file to default but then I get an error message instead of some file in AppData is missing.

What I expect is that when adding a file and moving all connection to default that they show up in default and that the next time I start Xrmtoolbox I can find them immediately when pressing the button in lower left corner.

**Comment by MscrmTools** [comment]
Something like this?
![image](https://cloud.githubusercontent.com/assets/10774317/21810496/5df505be-d74c-11e6-897c-69e1d29dec10.png)

where Default, Default (1) and Default (2) are three differents connection files

**Comment by rappen** [comment]
Big 👍 from me!

**Comment by daggen** [comment]
Looks good. Would it be possible to merge all connection files to same
list? If the user want it separated she goes to connect in the upper menu
while see everything at once use the lower button?

**Comment by MscrmTools** [comment]
I can maybe parameterize the behavior... Let me see what I can do

**Comment by MscrmTools** [comment]
This is parameterized! ready for next release
