### ISSUE TITLE
Bug: Not possible to lood if there exist duplicated entries

### ISSUE THREAD

**Issue by daggen** [MscrmTools/XrmToolBox#549]
This is a great option to the SDK tool!
I've a problem. We imported a default solution which added all the plugins and steps one more time. Because of this there exist a lot of duplicates. This is something that the SDK tool manage but your plugin fails because key already exist. I would be great if your tool could cope with this situation as well.

Possible enhancement, a filter to show duplicate only. This would be used for us when trying to solve our problem....

**Comment by MscrmTools** [comment]
What XrmToolBox plugin are you talking about?

**Comment by daggen** [comment]
Plugin registration tool

**Comment by MscrmTools** [comment]
This is not one of my plugin. Please check with the plugin author

**Comment by rappen** [comment]
@daggen Please submit issue here instead: https://github.com/Innofactor/PluginRegistration/issues
