### ISSUE TITLE
Metadata Document Generator

### ISSUE THREAD

**Issue by DebSil** [MscrmTools/XrmToolBox#553]
This plugin is generating a System.ServiceModel.FaultException "Could not find entity" no matter what entities I select for the document generation.
<img width="351" alt="xrmtoolboxerror" src="https://cloud.githubusercontent.com/assets/9323672/22124938/cefe12a4-de5f-11e6-918c-970418541b77.png">
#

**Comment by MscrmTools** [comment]
what CRM version?
What XrmToolBox version?
What MetadataDocumentGenerator version?

**Comment by DebSil** [comment]
2016 Online
XRM Toolbox 1.2016.11.4
Metadata Document Generator: 1.2016.8.23


Debbie Silbert
debsilbert@verizon.net

**Comment by MscrmTools** [comment]
Works like a charm on the same versions on my side

Are you sure you have appropriate permissions on this organisation?

**Comment by DebSil** [comment]
I am the administrator.  I will try again today.  It's been a bit since I posted this issue.
