### ISSUE TITLE
First and last release date for plugins

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#554]
It would be nice to be able to see release dates of first and newest version of each plugin.
Doesn't have to be in the grid, could be shown in the details section for selected plugin.

**Comment by MscrmTools** [comment]
Like this?

![image](https://cloud.githubusercontent.com/assets/10774317/22298242/1aa46c98-e320-11e6-9878-3a63d159e0d6.png)

**Comment by rappen** [comment]
Nice :)
