### ISSUE TITLE
Open XrmToolBox folder starts XrmToolBox

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#555]
It seems clicking the link starts the full path to current XTB instance. So the XTB app is started again.
It should probably just start the directory part of the path.

![image](https://cloud.githubusercontent.com/assets/2572253/22220803/7a33dd36-e1b0-11e6-857f-580b5ec7c330.png)

Running version 1.2017.1.5.

**Comment by MscrmTools** [comment]
The code does use a folder path and on my computer it does open expected folder...

**Comment by rappen** [comment]
Got it!
This was a super nice windows feature, actually =D

My path to XTB exe:
``C:\Dev\Tools\XrmToolBox\XrmToolBox.exe``
So it would open
``C:\Dev\Tools\XrmToolBox``

However, I also have a shortcut file:
``C:\Dev\Tools\XrmToolBox.lnk``

Guess what happens.... :p

Funny thing is that if I click Start - Run... and paste the folder path, Explorer is opened with that folder, ont the shortcut.

**Comment by MscrmTools** [comment]
I'm relieved it's not a bug in XTB finally :)

thanks
