### ISSUE TITLE
Gap in plugin list

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#557]
Strange gap exists in plugin list:

![gap](https://cloud.githubusercontent.com/assets/1185905/22327976/311fccc0-e3ba-11e6-86c4-ab05ac36d7f0.png)

**Comment by shytikov** [comment]
Somehow it's related to `MscrmTools.DashboardTransferTool.dll`, it should appear in this gap, but instead it is displayed in the end of the list.

**Comment by MscrmTools** [comment]
Ah ok, I know where it comes from... fix on the way...

**Comment by MscrmTools** [comment]
Hum... this file should not exist... It must come from an older bug...

I close this issue

**Comment by shytikov** [comment]
Anyway. I investigated the case, and I can tell you following, we do have an issue in the code — plugins are identified by name only, and theoretically two different developers can call their plugins identically. And only one will be displayed then and gap remains. 

Identifying plugins by GUIDs doesn't help in this case either. Because someone can overtake GUID value as well.

Basically `XTB` now allows `fishing` attacks. Since we don't have control over NuGet repository no one forbids me from adding new `FetchXMLBuilder`, for example, and there is 50% chance that mine plugin will overtake original plugin by @rappen :)

So... fix. Kind of. Instead of class type names full qualified names used. They are, again strings, but they include name of assembly as well. No plugins will be hidden. No gaps in the list.

**Comment by shytikov** [comment]
Just to clarify, how my last comment connected to the gaps in the list.

Gap in my case was placeholder for `MscrmTools.DashboardTransferTool.dll` plugin. But since in another plugin `MscrmTools.ViewTransferTool.dll` exported class was named exactly the same as in first one (and had same GUID), so when was adding `ViewTransferTool` on form we actually found `DashboardTransferTool` instead (exported classes was named identically) and it was moved from one location to another. Thus, gap in the list was created.

**Comment by MscrmTools** [comment]
Understood!

In a (hopefully) near future, Nuget won't be the only step to get a plugin in the plugins store. I should get soon a CRM and portal license thanks to my MVP status and I will create a XrmToolBox portal that will be the repository where Plugins Store will get plugins to show

This way, it will be possible to validate plugins before showing them in Plugins Store

**Comment by shytikov** [comment]
Just in case, I've prepared possible fix, it's in PR #559
