### ISSUE TITLE
Plugins should not be loaded in asynchronious task

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#56]
@rappen have found the case when plugin fails to initialize when it's loaded synchronously (current approach).

It happens if during initialization some Windows.Forms routines should be performed. If plugins are loaded synchronously Threading Exception pop-up.

Here is example of [similar case, that happened in another application](http://stackoverflow.com/q/13580475/1047741).

Despite performance loss, loading plugins should be done synchronously in context of current thread.

**Comment by MscrmTools** [comment]
Should I expect a pull request to correct this problem?

**Comment by shytikov** [comment]
Always!
