### ISSUE TITLE
Loding information from NuGet takes long time

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#560]
Currently `PluginStore` window takes too long to load. Mostly because number of plugin we need to have information about.

First we getting list of available plugins, and then, getting information about each one. And I believe this routine could be optimized. 

For example, we can display information in the plugins list already after, for example fist 10 plugins. Or sort in the manner, when first plugins with updates will be shown, and then — rest.

**Comment by daryllabar** [comment]
Do you have a quick link to where this is done in the code?

**Comment by MscrmTools** [comment]
@Rappen asked for release dates... that is what slows the store

**Comment by rappen** [comment]
Oooops.

**Comment by shytikov** [comment]
But solution could be easy — just add release date asynchronously...

**Comment by MscrmTools** [comment]
fixed!
