### ISSUE TITLE
Value in `/overridepath` cannot be absolute path

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#563]
We have `/overridepath` command line switch that allows to load plugins from specified location...

But if we identify location as absolute path (including drive), like so `c:\my\awesome\plugins\path` XrmToolBox will fail to start with following message:

```
---------------------------
Error
---------------------------
An unexpected error occured: System.IO.DirectoryNotFoundException: c
   at XrmToolBox.Extensibility.Paths.OverrideRootPath(String newRootPath)
   at XrmToolBox.Program.Main(String[] args)

One reason can be that at least one file is locked by Windows. Please unlock each locked files or unlock XrmToolBox.zip before extracting its content
---------------------------
OK   
---------------------------
```

I believe issue here is semicolon. We splitting argument's value by semicolon, skipping first chunk and taking first one. But if argument contains absolute path, with drive, we would have unexpected semicolon, that will ruin the logic.

Here is the place:

https://github.com/MscrmTools/XrmToolBox/blob/master/XrmToolBox/Program.cs#L35-L36

**Comment by rappen** [comment]
Write:

``"/overridepath:c:\my\awesome\plugins\path"``

Does that help?

**Comment by MscrmTools** [comment]
That should fix it, right?

```if (arg.ToLower().StartsWith("/overridepath:"))
                    {
                        var parts = arg.Split(':');
                        Paths.OverrideRootPath(string.Join(":", parts.Skip(1)));
                    }

**Comment by shytikov** [comment]
I was thinking about something like following:

    if (arg.ToLower().StartsWith("/overridepath:"))
    {
        var parts = arg.Split(new string[] { "/overridepath:" }, StringSplitOptions.RemoveEmptyEntries);

        if (parts.Length > 0)
        {
            Paths.OverrideRootPath(parts[0]);
        }
    }

**Comment by shytikov** [comment]
But your solution is more elegant!

**Comment by MscrmTools** [comment]
I go for it then!

**Comment by rappen** [comment]
I like oneliners.

```
Paths.OverrideRootPath(arg.Substring(arg.IndexOf(':')));
```

**Comment by shytikov** [comment]
I feel too verbose right now...

**Comment by shytikov** [comment]
Maybe just, simply:

```
Paths.OverrideRootPath(arg.Substring(14));?
```

**Comment by rappen** [comment]
Well my suggestion is generic and works for extracting all cmdline parameters ;)

**Comment by shytikov** [comment]
But that code itself is inside `if (arg.ToLower().StartsWith("/overridepath:"))` condition. So no other arguments except `overridepath` will not pass through.
