### ISSUE TITLE
User authentication failed

### ISSUE THREAD

**Issue by zmulk** [MscrmTools/XrmToolBox#564]
I work on a remote pc and I don't log out, its always on.
Everyday when I want to work it gives me this error.
I think the user gets logged out and needs to login everyday.
In previous version I could just leave my work and continue the next day.

**Comment by MscrmTools** [comment]
What version did you use before? and now?
What version of targeted CRM ?

**Comment by zmulk** [comment]
Now I am using version v1.2016.11..4
CRM version is on prem Dyn 365.

Before this I was using version of v1.2016.3.30

**Comment by MscrmTools** [comment]
Would it be possible that it comes more from Dynamics 365 than XrmToolBox? AFAIK, there is no change in connections that could behaves like you say

**Comment by zmulk** [comment]
It might be that :s
