### ISSUE TITLE
Please consider consolidating packages among projects

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#565]
Hi,

I'm having hard times developing plugins, even despite I read [article how to do it](https://github.com/MscrmTools/XrmToolBox/wiki/Debug-your-plugins-during-development). Visual Studio constantly refuses to design my forms, because of missing `McTools.Xrm.Connection` assembly of versions that already about half of a year old.

In runtime it is fixed by adding `dependentAssembly` section to `app.config` file, but unfortunately trick is not working in design time.

So. When I was almost desperate, I've noticed that `XrmToolBox.Extensibility` and `XrmToolBox.AutoUpdater` reference that old version, and actually causing all these strange issues.

Can we keep track on packages in `XTB` solution, so within one release all dependencies are consolidated? Ok, maybe it won't let us get rid of `dependentAssembly` configuration (since third-party plugins could rely on specific version), but at least it should solve issues in design mode.

And last and not least, I hope this will make @rappen happy, because I know he is also experiencing issues like this, and they almost drive him to hit a wall.

**Comment by daryllabar** [comment]
Every time I update the XrmToolBox Nuget I spent 2-4 hours fixing degin time dependency issues.

**Comment by rappen** [comment]
:+1:

**Comment by shytikov** [comment]
One more idea. Implement `AppDomain.CurrentDomain.AssemblyResolve` event handler. So we can manually control how assemblies are resolved. I believe implementing it once it's better than update `app.config` with every version.

**Comment by shytikov** [comment]
@MscrmTools can you consider uploading packages with consolidated dependencies to NuGet?

Current version of `XTB` contains breaking changes, so plugins needs to be updated, but updating plugins is **THE PAIN** in current situation.

I would really-really appreciate your input.

**Comment by shytikov** [comment]
I've updated binary dependencies for these, who want to design plugins for current version. Just unpack `packages.zip` and replace with these files dependencies you have in your `packages` folder.

[packages.zip](https://github.com/MscrmTools/XrmToolBox/files/741932/packages.zip)

These files, are result of compilation of following branch: https://github.com/Innofactor/XrmToolBox/tree/issue-565

**Comment by MscrmTools** [comment]
I'll do that soon

**Comment by shytikov** [comment]
Sorry for being such a nagging boy :) I have found workaround (build dependencies myself), so no rush at all.

Sorry once again.
