### ISSUE TITLE
The service Microsoft.VisualStudio.Shell.Interop.ISelectionContainer already exists

### ISSUE THREAD

**Issue by OliverFlint** [MscrmTools/XrmToolBox#567]
Hi, When opening the designer for a User Control that inherits `PluginControlBase` I recieve the following error and am unable to open the designer.

> The service Microsoft.VisualStudio.Shell.Interop.ISelectionContainer already exists in the service container. Parameter name: serviceType

Any ideas what the problem is?

If I change the User Control back to inheriting `UserControl` it works fine.

Thanks
Ollie

**Comment by shytikov** [comment]
It's most likely related to #565. You can check in output window, it complains about missing library. However, library is there, it's just incorrect version of it.

**Comment by shytikov** [comment]
How to fix for now. Find out which version is missing (I bet it's `McTools.Xrm.Connection, 2016.9.1`), install it for your project using NuGet. Downgrade to this version, if it was already present. Design what you need, and final build do with most recent version.

**Comment by OliverFlint** [comment]
That seems to do the trick thanks!

Downgraded MscrmTools.Xrm.Connection to v1.2016.9.1 which also downloaded the dependency XrmToolBoxPackage to 1.2016.11.3.

**Comment by OliverFlint** [comment]
FYI, This issue seems to be resolved now.

MscrmTools.Xrm.Connection v1.2017.2.12
XrmToolBoxPackage v1.2017.2.13

**Comment by rappen** [comment]
I got this now again and solved this be closing VS, deleting contents of the .vs folder where my solution is, restarting VS and recompiling. Seems like one of those file/settings/caching problems that pop up now and then, might be after switching source branch. VS2019, .net fw 4.6.2.

**Comment by rappen** [comment]
Seems like this issue is reintroduced with `MscrmTools.Xrm.Connection` version 1.2019.2.20.
Ping @MscrmTools

**Comment by jazmatician** [comment]
I actually saw the issue with 2019.2.22, but it went away when I rolled the MscrmTool.Xrm.Connection package back to 2019.2.20.

**Comment by rappen** [comment]
@jazmatician Yes, same behavior for me too now.
1.2019.2.22 produces the error, but 1.2019.2.20 does not.

**Comment by deepakkumar1984** [comment]
I am also getting with v 1.2019.6.25. Downgrading to 1.2019.2.20 fixed the issue and able to load the win form designer. I am unable to upgrade the XrmToolBox plugin to latest version

**Comment by rappen** [comment]
For me 1.2019.6.25 works fine!
