### ISSUE TITLE
Auto connect to last known connection

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#575]
Add a checkbox in the setting to automatically connect to the last known connection. When this is checked, XrmToolBox will save the current connection info to the disk and automatically connect, when XrmToolBox is reopened.

**Comment by rappen** [comment]
Should commandline parameter ``/connection`` override this?

**Comment by shytikov** [comment]
I would say, it's better to rephrase that task to be more general. We should remember not only last connection, but also last plugins opened, so if `XTB` started without any parameters, restore previous state.

Definitely, it should be setting "Restore session" or something like that, to control that behavior.
