### ISSUE TITLE
Getting errors while selecting FxB

### ISSUE THREAD

**Issue by rikincrm** [MscrmTools/XrmToolBox#578]
Hi Team,

I am getting error (see attached) while I select FxB.
![fxb error](https://cloud.githubusercontent.com/assets/25478961/22503838/91220a46-e899-11e6-8f41-ad96437bf79d.png)

Regards,
Rikin

**Comment by rappen** [comment]
If you update to latest (and greatest!) version of XrmToolBox this will be solved.
If XrmToolBox does not update automatically, download latest version from www.xrmtoolbox.com
