### ISSUE TITLE
User Setting Plug-in Error

### ISSUE THREAD

**Issue by spcoman** [MscrmTools/XrmToolBox#579]
When I try to update user settings I get the error below. How do I correct it?

![capture](https://cloud.githubusercontent.com/assets/25466676/22519778/b287cd8e-e87f-11e6-871a-7530ba5625f0.JPG)

**Comment by MscrmTools** [comment]
It seems you XrmToolBox.exe.config file is wrong with assembly bindings... can you post the content of this file?

**Comment by spcoman** [comment]
Below is a snip of the XRMToolbox Folder and below that is the code for the exe.

![xrmtoolbox contents](https://cloud.githubusercontent.com/assets/25466676/22552533/4f1c0d66-e927-11e6-8c5f-2e9ba035aa42.JPG)

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.24.0.0" newVersion="2.24.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.24.0.0" newVersion="2.24.0.0" />
      </dependentAssembly>
      
      <dependentAssembly>
        <assemblyIdentity name="McTools.Xrm.Connection" publicKeyToken="96037217801d9658" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2017.1.10" newVersion="1.2017.1.10" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="McTools.Xrm.Connection.WinForms" publicKeyToken="f1559f79cf894e27" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2017.1.10" newVersion="1.2017.1.10" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Tooling.Connector" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <loadFromRemoteSources enabled="true" />
  </runtime>
  <system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true">
      <proxy autoDetect="True" bypassonlocal="False" />
    </defaultProxy>
  </system.net>
  <system.diagnostics>
    <trace autoflush="true" />
    <sources>
      <source name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" switchName="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="console" type="System.Diagnostics.DefaultTraceListener" />
          <remove name="Default" />
          <add name="CustomListener" />
        </listeners>
      </source>
    </sources>
    <switches>
      
      <add name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value="Error" />
    </switches>
    <sharedListeners>
      <add name="fileListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="XrmToolBoxConnection.log" />
      <add name="CustomListener" type="Microsoft.Xrm.Tooling.Connector.DynamicsFileLogTraceListener, Microsoft.Xrm.Tooling.Connector" BaseFileName="XrmToolBox_Connection" Location="LocalUserApplicationDirectory" MaxFileSize="52428800" />
    </sharedListeners>
  </system.diagnostics>
</configuration>

**Comment by spcoman** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.24.0.0" newVersion="2.24.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.24.0.0" newVersion="2.24.0.0" />
      </dependentAssembly>
      
      <dependentAssembly>
        <assemblyIdentity name="McTools.Xrm.Connection" publicKeyToken="96037217801d9658" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2017.1.10" newVersion="1.2017.1.10" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="McTools.Xrm.Connection.WinForms" publicKeyToken="f1559f79cf894e27" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2017.1.10" newVersion="1.2017.1.10" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Tooling.Connector" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <loadFromRemoteSources enabled="true" />
  </runtime>
  <system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true">
      <proxy autoDetect="True" bypassonlocal="False" />
    </defaultProxy>
  </system.net>
  <system.diagnostics>
    <trace autoflush="true" />
    <sources>
      <source name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" switchName="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="console" type="System.Diagnostics.DefaultTraceListener" />
          <remove name="Default" />
          <add name="CustomListener" />
        </listeners>
      </source>
    </sources>
    <switches>
      
      <add name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value="Error" />
    </switches>
    <sharedListeners>
      <add name="fileListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="XrmToolBoxConnection.log" />
      <add name="CustomListener" type="Microsoft.Xrm.Tooling.Connector.DynamicsFileLogTraceListener, Microsoft.Xrm.Tooling.Connector" BaseFileName="XrmToolBox_Connection" Location="LocalUserApplicationDirectory" MaxFileSize="52428800" />
    </sharedListeners>
  </system.diagnostics>
</configuration>

**Comment by spcoman** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.24.0.0" newVersion="2.24.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.24.0.0" newVersion="2.24.0.0" />
      </dependentAssembly>
      
      <dependentAssembly>
        <assemblyIdentity name="McTools.Xrm.Connection" publicKeyToken="96037217801d9658" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2017.1.10" newVersion="1.2017.1.10" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="McTools.Xrm.Connection.WinForms" publicKeyToken="f1559f79cf894e27" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2017.1.10" newVersion="1.2017.1.10" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Tooling.Connector" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <loadFromRemoteSources enabled="true" />
  </runtime>
  <system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true">
      <proxy autoDetect="True" bypassonlocal="False" />
    </defaultProxy>
  </system.net>
  <system.diagnostics>
    <trace autoflush="true" />
    <sources>
      <source name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" switchName="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="console" type="System.Diagnostics.DefaultTraceListener" />
          <remove name="Default" />
          <add name="CustomListener" />
        </listeners>
      </source>
    </sources>
    <switches>
      
      <add name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value="Error" />
    </switches>
    <sharedListeners>
      <add name="fileListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="XrmToolBoxConnection.log" />
      <add name="CustomListener" type="Microsoft.Xrm.Tooling.Connector.DynamicsFileLogTraceListener, Microsoft.Xrm.Tooling.Connector" BaseFileName="XrmToolBox_Connection" Location="LocalUserApplicationDirectory" MaxFileSize="52428800" />
    </sharedListeners>
  </system.diagnostics>
</configuration>

**Comment by spcoman** [comment]
![configfile](https://cloud.githubusercontent.com/assets/25466676/22552642/c4c86f14-e927-11e6-896d-c7106d3c4c89.JPG)

**Comment by MscrmTools** [comment]
The binding for Microsoft.Xrm.Tooling.Connector should be 0.0.0.0-X.X.X.X where X.X.X.X is the version of the corresponding file on your XrmToolBox folder.
So I guess that should be 0.0.0.0-2.1.0.0

**Comment by spcoman** [comment]
Like so?

![newcode](https://cloud.githubusercontent.com/assets/25466676/22555514/f17fada6-e931-11e6-9709-195a34075aff.JPG)

**Comment by spcoman** [comment]
Still throws the same error when I try to update User Settings Utility. I edited and saved the config file on my laptop that came from the extract with the 2.1.0.0

**Comment by MscrmTools** [comment]
can you check the version of Microsoft.Xrm.Tooling.Connector on the XrmToolBox folder?

**Comment by spcoman** [comment]
So I uninstalled the version I had, downloaded the newest 2017 version, and when I reinstalled I got the same issue. Microsoft.Xrm.Tooling.Connection version 2.0.0.303.

I should mention that the Sitemap Editor works fine. All other plug-ins can connect and download the setting, entities, etc. but can't apply changes.

**Comment by spcoman** [comment]
Sorry! I that was the CRMConnectControl version. Below is a snip of the correct .dll.

![details](https://cloud.githubusercontent.com/assets/25466676/22567587/804aa5dc-e95e-11e6-8805-5950b7ffc862.JPG)

**Comment by MscrmTools** [comment]
So what if you put 2.2.0.0 as the target assembly binding?

**Comment by Careccb76** [comment]
I am having the same issue.  Any thoughts on how to fix?

![image](https://cloud.githubusercontent.com/assets/20117138/22572124/a5a9b702-e970-11e6-8523-80a1fe74b754.png)

**Comment by Careccb76** [comment]
Actually, I don't see it in the list of plugins?

![image](https://cloud.githubusercontent.com/assets/20117138/22575711/6db8bcde-e985-11e6-8ce6-ce9b1b1d2d1e.png)

**Comment by MscrmTools** [comment]
The plugin is still embedded with XrmToolBox solution. I don't reproduce your error but have another one which is strange. I will work on it

**Comment by xairrick** [comment]
I also noticed that it was missing from the list of plugins (and plugin store).  I copied the plugin from an older version of the xrmtoolbox.   Then I updated XrmToolBox.exe.config with the following;

 <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Tooling.Connector" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>

This allowed it to work (I hope I didn't break the other plugins).

**Comment by MscrmTools** [comment]
The plugin should be embedded with XrmToolBox but maybe I missed something. And the binding is correct and should break anything.
Next release of XrmToolBox won't require explicite bindings
