### ISSUE TITLE
Error on Start with version 1.2017.1.11

### ISSUE THREAD

**Issue by vssconnell** [MscrmTools/XrmToolBox#580]
[XrmToolbox v.1.2017.1.11 on load error.txt](https://github.com/MscrmTools/XrmToolBox/files/750644/XrmToolbox.v.1.2017.1.11.on.load.error.txt)
I get an error when starting the latest release.

**Comment by MscrmTools** [comment]
Is it a fresh install or an update of a previous version?

**Comment by vssconnell** [comment]
Update initially I then removed and reinstalled.  Are there registry settings that I might have neglected?

**Comment by MscrmTools** [comment]
No, no registry settings...
May Insee your XrmToolBox.exe.config file?

**Comment by vssconnell** [comment]
Here
[XrmToolBox.exe.zip](https://github.com/MscrmTools/XrmToolBox/files/750698/XrmToolBox.exe.zip)

**Comment by MscrmTools** [comment]
Hum... It's maybe due to an incompatible plugin...

Can you run XrmToolBox with a command line XrmToolBox.exe /overridepath:. and see if it behaves the same?

**Comment by vssconnell** [comment]
Same result

**Comment by vssconnell** [comment]
I should add that I have tried installing an older version still in my downloads with very few plugins and then upgrading.  I got the download in September 2016 but have one from August 2015 too.   I got the same result.

I had chosen to upgrade because I was getting issues with the Attribute Usage plugin.

**Comment by MscrmTools** [comment]
can you tell me what are the version of your Microsoft.Xrm.Sdk.dll in XrmToolBox folder?

**Comment by vssconnell** [comment]
![sdk version](https://cloud.githubusercontent.com/assets/25530568/22596218/8f14fa8a-ea22-11e6-83a5-cb378246b80f.PNG)

**Comment by MscrmTools** [comment]
What I don't understand is why your XrmToolBox tries to get the version 7 and not mine...

**Comment by vssconnell** [comment]
Sorry can't help.  Is it worth cloning and attempting to run from my Visual Studio environment?

**Comment by MscrmTools** [comment]
don't think so but you could try to add some assembly bindings for CRM SDK assemblies in XrmToolBox.exe.config

**Comment by vssconnell** [comment]
I'm sorry but I'm not sure how to do this, tips?  Also version  v1.2016.11.4 displays the same issue however version  v1.2016.8.23 loads but is now presenting another issue with Attribute Usage Inspector (which is what prompted me to upgrade.
![attribute usage inspector](https://cloud.githubusercontent.com/assets/25530568/22598643/0413bfb6-ea2c-11e6-9bd9-e12dc85886a0.PNG)

**Comment by whitecm1** [comment]
I am having the same issues - however running XrmToolBox with a command line XrmToolBox.exe /overridepath:. as suggested works

**Comment by MscrmTools** [comment]
The overridepath changes the location where XrmToolBox stores its files (plugins, settings, logs, etc.). 

So that can mean that a plugin is impacting the whole XrmToolBox and make it fail at startup

**Comment by MscrmTools** [comment]
Does the problem still occur with latest version?

**Comment by vssconnell** [comment]
I still get errors (although not the same - see below) I have however moved my implementation to a VM development box which seems to be working fine.  This makes me think that its a local problem rather than a solution issue.
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.TypeLoadException: Method 'WorkAsync' in type 'DLaB.XrmToolboxCommon.DialogBase' from assembly 'DLaB.XrmToolboxCommon, Version=1.2015.7.6, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at XrmToolBox.PluginManagerExtended.Initialize()
   at XrmToolBox.MainForm.<MainForm_Load>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2017.3.14
    Win32 Version: 1.2017.3.14
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2017.2.7
    Win32 Version: 1.2017.2.7
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 6.1.7600.16394
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly Version: 1.2017.3.5
    Win32 Version: 1.2017.3.5
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
    Assembly Version: 2.12.0.817
    Win32 Version: 2.12.0.817
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/NuGet.Core.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2017.2.12
    Win32 Version: 1.2017.2.12
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2017.2.12
    Win32 Version: 1.2017.2.12
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 8.0.0.0
    Win32 Version: 8.2.0.713
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly Version: 8.0.0.0
    Win32 Version: 8.2.0.566
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 8.0.0.0
    Win32 Version: 8.2.0.749
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.758
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 2.24.0.0
    Win32 Version: 2.24.30411.1323
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms
    Assembly Version: 2.24.0.0
    Win32 Version: 2.24.30411.1323
    CodeBase: file:///C:/Users/stephen.connell/Desktop/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Cinteros.Xrm.CRMWinForm
    Assembly Version: 2016.8.8.9
    Win32 Version: 2016.8.08.9
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.CRMWINFORM.DLL
----------------------------------------
Cinteros.Xrm.FetchXmlBuilder
    Assembly Version: 1.2016.12.115
    Win32 Version: 1.2016.12.115
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.FETCHXMLBUILDER.DLL
----------------------------------------
Cinteros.Xrm.XmlEditorUtils
    Assembly Version: 1.2016.4.106
    Win32 Version: 1.2016.4.106
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.XMLEDITORUTILS.DLL
----------------------------------------
Cinteros.XTB.ViewDesigner
    Assembly Version: 1.2016.8.7
    Win32 Version: 1.2016.8.7
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XTB.VIEWDESIGNER.DLL
----------------------------------------
Cube.XRMToolBox.RecordCounter
    Assembly Version: 1.2017.1.3
    Win32 Version: 1.2017.1.3
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CUBE.XRMTOOLBOX.RECORDCOUNTER.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2016.10.3
    Win32 Version: 1.2016.10.3
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2017.1.2
    Win32 Version: 1.2017.1.2
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
Develop1.XrmTBPlugin.RibbonWorkbench2016
    Assembly Version: 3.0.24.0
    Win32 Version: 3.0.24.0
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DEVELOP1.XRMTBPLUGIN.RIBBONWORKBENCH2016.DLL
----------------------------------------
DLaB.LocalToGlobalOptionSet
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DLAB.LOCALTOGLOBALOPTIONSET.DLL
----------------------------------------
DLaB.Xrm
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DLAB.XRM.DLL
----------------------------------------
DLaB.XrmToolboxCommon
    Assembly Version: 1.2015.7.6
    Win32 Version: 1.2015.7.6
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DLAB.XRMTOOLBOXCOMMON.DLL
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly Version: 1.2017.1.2
    Win32 Version: 1.2017.1.2
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2017.1.6
    Win32 Version: 1.2017.1.6
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.556
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MICROSOFT.XRM.TOOLING.CONNECTOR.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2016.5.1
    Win32 Version: 1.2016.5.1
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2016.5.1
    Win32 Version: 1.2016.5.1
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly Version: 1.2017.1.4
    Win32 Version: 1.2017.1.4
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2016.9.1
    Win32 Version: 1.2016.9.1
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MscrmTools.DashboardTransferTool
    Assembly Version: 1.2016.6.1
    Win32 Version: 1.2016.6.1
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DASHBOARDTRANSFERTOOL.DLL
----------------------------------------
MscrmTools.DataUsageInspector
    Assembly Version: 1.2016.9.20
    Win32 Version: 1.2016.9.20
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DATAUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly Version: 1.2016.8.2
    Win32 Version: 1.2016.8.2
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2016.11.2
    Win32 Version: 1.2016.11.2
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2016.10.4
    Win32 Version: 1.2016.10.4
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2017.1.3
    Win32 Version: 1.2017.1.3
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
    Assembly Version: 1.2017.3.0
    Win32 Version: 1.2017.3.0
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2017.1.3
    Win32 Version: 1.2017.1.3
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2017.3.7
    Win32 Version: 1.2017.3.7
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2016.6.3
    Win32 Version: 1.2016.6.3
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2017.3.4
    Win32 Version: 1.2017.3.4
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2017.1.3
    Win32 Version: 1.2017.1.3
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MsCrmTools.WebResourcesManager
    Assembly Version: 1.2017.3.9
    Win32 Version: 1.2017.3.9
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
MSCRMUtilities.FetchXMLToStringConverter
    Assembly Version: 1.0.0.5
    Win32 Version: 1.0.0.5
    CodeBase: file:///C:/USERS/STEPHEN.CONNELL/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMUTILITIES.FETCHXMLTOSTRINGCONVERTER.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------

**Comment by MscrmTools** [comment]
Ok, can you confirm that all your plugins are up to date?

**Comment by vssconnell** [comment]
This was a clean install of the latest version.

**Comment by MscrmTools** [comment]
Sure, but with latest versions, plugins are not stored in the same place, so even if you install a new one, it will still consume same plugins

**Comment by vssconnell** [comment]
OK but I have removed all previous versions and extracted the latest download which I then attempted to run.  I would expect that this would include the most recent plugins.  I'm not sure what I'm missing.

**Comment by MscrmTools** [comment]
No, downloading latest version just add latest plugins from me, not from other developers.
Go to your roaming folder : C:\users\your_login\AppData\Roaming\MscrmTools\XrmToolBox and delete the folder "Plugins" (or its content, whatever).
Then start again XrmToolBox

**Comment by vssconnell** [comment]
OK thanks.  This appears to have resolved the issue.
