### ISSUE TITLE
Spinner overlay during connection

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#582]
With xrmtoolbox shortcut with connection and tool args and resuming session from (#581), it is not quite obvious that XrmToolBox is trying to connect when it is open. The only indication of this is a small label on the bottom right. Can we have a modal overlay spinner when connection is being made, or some other UI to indicate this? Otherwise people might look to connect again or open a tool before the connection request is complete.

**Comment by MscrmTools** [comment]
This will be handled in the next release. Here is what it looks like when opening XrmToolBox with a specific connection
![image](https://cloud.githubusercontent.com/assets/10774317/25518578/9c74f61c-2bf4-11e7-8971-4d4454e62e89.png)

**Comment by rajyraman** [comment]
Looks awesome..You are on a roll today. Saw so many issues closed in my GitHub feed.

**Comment by MscrmTools** [comment]
Yes, I'm trying to clean the issues. Too many of them without feedback or nothing to do in the end
