### ISSUE TITLE
Metadata Document Generator: Deleted AttributeSelection on reorder Entities

### ISSUE THREAD

**Issue by r-weisser** [MscrmTools/XrmToolBox#583]
After reordering the entities of a loaded configuration, the previous attributeselection is removed.
Reordering is very useful, when you want to keep always the same order for comparison of different versions.

Steps:
- Setting: 'Selected attributes', then select some entities and attributes
- Save
- Load settings and check for previous selected attributes (they are selected)
- Reorder entites and check again (selection is gone)

CRM 2016
XrmToolBox 2017.1.11

**Comment by MscrmTools** [comment]
Thank you for reporting the issue. I will work on this as soon as I find time

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.MetadataDocumentGenerator #2](https://github.com/MscrmTools/MsCrmTools.MetadataDocumentGenerator/issues/2) via [**ZenHub**](https://www.zenhub.com/)
