### ISSUE TITLE
Directory name is invalid

### ISSUE THREAD

**Issue by meghanareed** [MscrmTools/XrmToolBox#586]
I recently moved around some files and as a result had to redownload the XrmToolbox. I've re-downloaded, unblocked and unzipped the file. However, I am still getting this error.

![image](https://cloud.githubusercontent.com/assets/24827171/22891358/12e4f556-f1dd-11e6-8345-58c6437fc621.png)

**Comment by MscrmTools** [comment]
may i see the full path (except your username)?

**Comment by meghanareed** [comment]
I had to go in and delete the AppDate files for MSCRMTools - in both the Roaming and Local - then it allowed this to work.
