### ISSUE TITLE
Get CRM Credentials

### ISSUE THREAD

**Issue by ghost** [MscrmTools/XrmToolBox#587]
Hi there,
is there an easy way (I needed to use the reflection and looks a bit ugly) to get the CRM Credentials (I mean: username+domain & password) of the current connection directly from an XrmToolbox's plugin?

Thanks,
gennaro

PS: I do apologies if this is not the correct channel for making this kind of questions!

**Comment by daryllabar** [comment]
I do this in the EarlyBoundGenerator.  https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/blob/master/DLaB.XrmToolBoxCommon/Extensions.cs
See GetUserPassword

The rest of the information is on the ConnectionDetail I believe.

**Comment by daryllabar** [comment]
But it would be awesome if the XTB provided a way to opt into giving away your credentials.

> The Plugin X is requesting access to your Password.  Do you want to give Access?  (no/once/always)

**Comment by getangar** [comment]
Thanks Dary!
Well truth be told I get everything I get from the ConnectionDetails which is not anyway directly accessible from the plugin (infact I Need to get the data using teh reflection).

Regards,
gennaro

**Comment by MscrmTools** [comment]
Good news, there will be a way to ask for credentials (if present) in the next release
