### ISSUE TITLE
Error while importing translations

### ISSUE THREAD

**Issue by InnaGo** [MscrmTools/XrmToolBox#589]
Hi, 
after moving to a new notebook, I have problems with the import of the translations. I get the attached error (is in German, I can translate if you need). The same file I can import on a different PC. I didn't find any solution in web according this issue...
![errorxrmtoolbox](https://cloud.githubusercontent.com/assets/25924908/23160373/807c29b4-f826-11e6-9401-6aa2d0a04008.jpg)
Thx,
Inna

**Comment by MscrmTools** [comment]
Hi @InnaGo , you need to use the latest version of XrmToolBox to avoid this message
