### ISSUE TITLE
User Setting Utility Error when applying changes

### ISSUE THREAD

**Issue by DPReynolds** [MscrmTools/XrmToolBox#590]
After the latest update to the XRMToolBox, I am getting the following error when trying to use the "User Setting Utility" to update the user records with Dynamic 365 (CRM 2016) OnPrem and OnLine.

An error occured: Method not found: 'Microsoft.Xrm.Tooling.Connector.CrmServiceClient McTools.Xrm.Connection.ConnectionDetail.get_ServiceClient()'.

**Comment by MscrmTools** [comment]
I don't reproduce this error.
Can you tell me the version of XrmToolBox ?

**Comment by bmcghan** [comment]
I received the error in the latest version as well.  Here is a screenshot:
(https://cloud.githubusercontent.com/assets/26463895/24003367/a3797ce4-0a39-11e7-8f61-bf147ad40c07.png)

**Comment by MscrmTools** [comment]
That should be resolved with latest version available on plugins store
