### ISSUE TITLE
Error when loading XrmToolBox

### ISSUE THREAD

**Issue by pyrofenix** [MscrmTools/XrmToolBox#591]
I am not an expert with the tool, but have used it on and off for years.  I noticed that I had an outdated version, so downloaded v.1.2017.2.13 and had an issue loading the application.

I blew away my old version and tried again with no luck, got the following error:  
![image](https://cloud.githubusercontent.com/assets/25936687/23180475/8f9168a6-f83f-11e6-9b6a-deb0b2323e0d.png)

I then tried a slighly older version and got the same error.  I made sure that I unblocked the zip file before extracting (into my download folder).

Note:  after clicking quit - I get the following error message.
![image](https://cloud.githubusercontent.com/assets/25936687/23181083/8fe09d48-f841-11e6-9668-c285412f4dae.png)

**Comment by Derek-Hughes** [comment]
Same happening here, but with different CRM based DLL, looking for 7 but 8.2 was included in the download.

**Comment by MscrmTools** [comment]
Is it still happening? if yes, please reopen the issue
