### ISSUE TITLE
Sync Filter Manager: Error while updating users Local Data Rules

### ISSUE THREAD

**Issue by michaelmittermair** [MscrmTools/XrmToolBox#592]
With the current version (v1.2017.2.13) I get an error, if I try to reset the filter for a specific user. Errormessage: Error while updating users Local Data Rules: Method not found 'Microsoft.Xrm.Tooling.Connector.CrmServiceClient McTools.Xrm.Connection.ConnectionDetail.get_ServiceClient()'.

![image](https://cloud.githubusercontent.com/assets/1768685/23199497/07073aca-f8cf-11e6-9d49-c925e0cc7c86.png)

**Comment by MscrmTools** [comment]
@michaelmittermair I do not reproduce this error... can you explain how you are connected to your organization? (Connection string, or Office 365 federeated AD, etc.)

**Comment by michaelmittermair** [comment]
I'm tested it on an on-premise installation with the following installations:

- Microsoft Dynamics 365, Version 1612 (8.2.0.749) (DB 8.2.0.749) on-premises (with IFD)
- Microsoft Dynamics® CRM 2016 (8.1.0.372) (DB 8.1.0.372) (without IFD)

On both versions the same error.
The sync filter manager has the version 1.2016.8.23

Connectionstring looks like: https://urltoserver/orgname

**Comment by MscrmTools** [comment]
Should be fixed on latest version.
If not please reopen
