### ISSUE TITLE
Error when updating Web Resources

### ISSUE THREAD

**Issue by jmsims2** [MscrmTools/XrmToolBox#594]
I just today started getting an error when trying to update and publish web resources that I edit and can't figure out whats going on.  The error is: Error while updating web resource: There should be at least one entity returned. Count: 0.

The details from the exception text are below.  Not sure what the problem is...any help would be greatly appreciated.

**Comment by jmsims2** [comment]
Just noticed that this isn't happening on all web resources, but only web resources that I renamed last night using XrmToolbox.

**Comment by jmsims2** [comment]
Sorry for all the comments, but upon further inspection, it looks like CRM does not like when you rename web resources.  I renamed them using web resources manager in XrmToolbox and everything that I renamed has disappeared from within the customizations area, yet the web resources are loading on forms and load in XrmToolbox.  This is happening in Microsoft Dynamics 365 Version 1612 (8.2.0.780) (DB 8.2.0.779) online.  Thanks for any help.

**Comment by MscrmTools** [comment]
How did you rename Web Resource?? this is not something doable with WebResourceManager...

**Comment by MscrmTools** [comment]
@jmsims2 any feedback?

**Comment by jmsims2** [comment]
I right click on the name of the web resource, click rename and then this window pops up:

![image](https://cloud.githubusercontent.com/assets/2560527/23757713/df18ba20-04a4-11e7-9a6b-f2593422fc87.png)

**Comment by MscrmTools** [comment]
Ok, this feature should be allowed only when the webresource is not already existing on CRM organization, I guess... let me check the code

**Comment by MscrmTools** [comment]
Ok, after reading the code, this feature deletes and recreate a new web resource since it is not possible to rename directly it. 
So if the web resource was in a solution, then the renamed web resource is not added back in the solution. Maybe that would need to be the fix

**Comment by MscrmTools** [comment]
Moving the issue in the appropriate repository

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.WebResourcesManager #23](https://github.com/MscrmTools/MsCrmTools.WebResourcesManager/issues/23) via [**ZenHub**](https://www.zenhub.com/)
