### ISSUE TITLE
Updated XRMToolbox to version v1.2017.2.13 - and now I can't connect

### ISSUE THREAD

**Issue by CarieMcK** [MscrmTools/XrmToolBox#598]
After updating, I lost all of my saved connections, and am unable to connect to CRM instances that I previously had connected.
I would assume I did something wrong except I know I'm not the only one having this problem. 

Thanks.

**Comment by MscrmTools** [comment]
All your saved connections are backed up in C:\Program Data\XrmToolBox\Backup_something...

Can you provide log files to understand what is wrong. This version uses latest version of CRM SDK assemblies. There might be a problem with them.
