### ISSUE TITLE
Can't Launch XrmToolBox - Proxy Server errors

### ISSUE THREAD

**Issue by simes1** [MscrmTools/XrmToolBox#60]
Hi Tanguy,

As requested see below re errors I get trying to launch XrmToolBox behind an Internet Proxy Server.  (In this case CRM is on-premise with no IFD so I don't really care too much if XrmToolBox can't connect to the Internet but the lack of access - I think to GitHub - seems to stop it even displaying the main page.

First I got:
"System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required."

Then I created an application.exe.config file as described here:
https://xrmtoolbox.codeplex.com/discussions/566947

I got a little bit further but then ran into:
"System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions 192.30.252.137:443"

192.30.252.137 appears to be a GitHub server.  XrmToolBox is running on Windows 8.1 and works fine on Public WiFi but obviously I can't get to our on-premise CRM from there...

Any ideas how to fix/workaround?

--
Simon

**Comment by MscrmTools** [comment]
Could you send me your email address so that I will be able to send you a version to test Proxy usage in XrmToolBox?

**Comment by simes1** [comment]
Thanks - Work email is simon.hetzel@kingston.gov.uk<mailto:simon.hetzel@kingston.gov.uk> (but I don’t think you will be able to email a ZIP file with executables in it).  If not try the one below and I’ll see if I can figure out a way to put it somewhere I can access from the Internal network.

Regards

--
Simon Hetzel
LinkedIn:          http://uk.linkedin.com/in/simonhetzel
Tel:                  01225 863885
Email:              simon.hetzel@simplesimes.net<mailto:simon.hetzel@simplesimes.net>

**Comment by MscrmTools** [comment]
As per conversation offline with @simes1, I have added the ability to define a custom proxy in XrmToolBox options. Will be merged soon

**Comment by Alen79** [comment]
Hi I have the same issue.Getting (407) Proxy Authentication Required error message when starting XRM Toolbox. Can you help me?

Thanks
Alen

**Comment by shytikov** [comment]
Can you try to update `XTB` to most recent version? It should be already fixed.

**Comment by MscrmTools** [comment]
If the proxy is configured in IE with a .pac file, then an additional configuration is necessary 

It consists of adding a config file for Xrmtoolbox.exe program
