### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by sangerslee** [MscrmTools/XrmToolBox#600]
Hello! I am trying to write a new plugin and have followed the instructions. However, even though my plugin dll is copied to the %AppData%\Roaming\MscrmTools\XrmToolBox\Plugins folder, the plugin is not listed within the available plugins. Is there something that I am missing?

Thanks.

**Comment by MscrmTools** [comment]
I guess we answered this question on Gitter. It was missing image metadata
