### ISSUE TITLE
Scripts in Ribbon

### ISSUE THREAD

**Issue by craigseymour** [MscrmTools/XrmToolBox#601]
Does Scripts Finder find scripts in ribbons? Doesn't seem to, and can't find source to check.

**Comment by MscrmTools** [comment]
Hi,
Yes it does! I'm using it quite often for this purpose. What version are you using?

**Comment by MscrmTools** [comment]
The proof
![image](https://cloud.githubusercontent.com/assets/10774317/24093952/c143f662-0d56-11e7-99a7-63c9e0040fd5.png)
