### ISSUE TITLE
User Settings Utility: select users based on FXB query

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#602]
Filter uses by using FXB to compose the query.

**Comment by MscrmTools** [comment]
Can you remind me if there is any doc on how to implement the appropriate interface?

**Comment by rappen** [comment]
Easiest to follow highlighted lines here: https://github.com/andypopkin/XrmToolBox---Bulk-Workflow-Execution/issues/4
There is also a blog post that describes it a bit more, but uses a custom class for the communication, which is not necessary: http://jonasrapp.innofactor.se/2015/04/IntegrateFXB.html

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.UserSettingsUtility #1](https://github.com/MscrmTools/MsCrmTools.UserSettingsUtility/issues/1) via [**ZenHub**](https://www.zenhub.com/)
