### ISSUE TITLE
XrmToolBox won't open in v1.2017.2.13

### ISSUE THREAD

**Issue by antbanks2014** [MscrmTools/XrmToolBox#603]
After I unblock the zip file and try running the .exe I get the below error and I'm not sure how to get around this

![image](https://cloud.githubusercontent.com/assets/4238860/24050642/dcb35c1a-0b05-11e7-96b5-73900fbff726.png)

**Comment by daryllabar** [comment]
So you have:
- Downloaded the zip file
- Unblocked the zip file
- Extracted the zip file
- then navigated to the unzipped folder, and opened the XTB, and it gave you that error?

**Comment by antbanks2014** [comment]
That is correct @daryllabar

**Comment by MscrmTools** [comment]
This error message seems to indicate that one of the password encrypted are not valid... I would try to remove connection files just for testing purposes

**Comment by natemac709** [comment]
I'm experiencing a similar error message.

Prior to download:
- I imported a config file with existing un & pw into the root XTB folder
- Prep for download: I deleted all existing folders and files of XTB 

Download steps:
- Downloaded XTB v1.2017.2.13 into new folder
- Unblocked the XTB zip
- Extracted the XTB zip files into new folder
- Un-checked read-only in properties of unzipped XTB folder 
- Ran XTB.exe

Got an error: 
 Error: An unexpected error occurred: System.ArgumentException: The directory name C:\User\{user}\{folder}\{folder}\Xrmtoolbox is invalid.
  at System.IO.FileSystemWatcher..ctor(String path, String filter) 
  at McTools.XrmConnection.ConnectionManager.SetupFileSystemWatcher()

When I re-created the missing folder path, XTB opened without issue. I have 10-20 credentials in my connections list, so this is pretty annoying when I need to update XTB. Is there an auto-update feature within the application?

**Comment by antbanks2014** [comment]
I just ended up going to the following file path and deleting the XrmToolBox folder located there and was able to start up successfully

C:\Users\{username}\AppData\Roaming\MscrmTools

**Comment by rstarkov** [comment]
This happens if you extract the latest version into a different directory to where the old one was located. This scenario definitely needs to be handled better. Maybe reopen?

**Comment by MarkvdWeerd** [comment]
You can also edit the "MscrmTools.ConnectionsList" file located at C:\Users**{username}**\AppData\Roaming\MscrmTools

in Notepad++ and change the path to the connection file to the correct location.

`<?xml version="1.0" encoding="utf-8"?>
<ConnectionsList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Files>
    <ConnectionFile>
      <Name>Default</Name>
      <LastUsed>0001-01-01T00:00:00</LastUsed>
      <Path>C:\Users\**{username}**\AppData\Roaming\MscrmTools\XrmToolBox\Connections\ConnectionsList.Default.xml</Path>
    </ConnectionFile>
    <ConnectionFile>
      <Name>xrmToolboxConnections</Name>
      <LastUsed>2018-03-26T10:19:10.6631987+02:00</LastUsed>
      **<Path>C:\Install\XrmToolbox\xrmToolboxConnections.xml</Path>**
    </ConnectionFile>
  </Files>
</ConnectionsList>`
