### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by gogogadgetscott** [MscrmTools/XrmToolBox#604]
I would love to see a way for automating certain tasks. For example do a nightly Export To Excel. Is there any current solution for automation via CLI, scripting, and/or plugin? 

Worst case, I would look into using something like AutoHotkey but would prefer a solution that would run in the background.

Scott

**Comment by MscrmTools** [comment]
Hi
Nothing is planned for this kind of feature right now

**Comment by daryllabar** [comment]
I think this is where flow would be a better choice.

**Comment by skfd** [comment]
I would generalise this as "expose tools not only as GUI but as cli too".

**Comment by MscrmTools** [comment]
The problem is: each developer do what he wants in its plugin and I don't see yet a way to oblige them to provide "not GUI" features

**Comment by amrkarthik** [comment]
@gogogadgetscott  Isn't it achievable using out of the box CRM functionality?

**Comment by daryllabar** [comment]
This request as is is too vague and as currently written, doesn't make sense to be included in the XrmToolBox.
