### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by JasonMcAndrew** [MscrmTools/XrmToolBox#605]
Hello, 

I'm having a bizarre problem. I can connect to my Dynamics CRM Online Sandbox and modify SiteMap no problem.  

If I connect to my Live environment and modify the SiteMap it's actually loading the SiteMap from the Sandbox.

Same issue if I load the Ribbon Workbench it loads the Sandbox Entities not the Live Entities. 

I have tried various version of XrmToolBox but still the same issue, has anyone else encountered this?

Thanks
Jason

**Comment by MscrmTools** [comment]
When connecting to the Live environment, are you applying the new connection to the opened plugin?

To be sure, can you explain the step by step scenario when it comes to connecting and opening plugin?

**Comment by JasonMcAndrew** [comment]
1. Open XrmToolBox
2. Launch Ribbon Workbench 
3. Select a connection (Live Instance)
4. Type Password
5. The 'Load Solution' box opens, this is when it loads the solutions from the Sandbox instance. 

Thanks for your help.

**Comment by MscrmTools** [comment]
Never seen that... 
Can you:
Edit XrmToolBox.exe.config file to change the switch to "Verbose"
![image](https://cloud.githubusercontent.com/assets/10774317/24507135/ef8043c6-155f-11e7-8be5-0fcd24fd9965.png)

Replay the procedure
Open connection log file (on XrmToolBox storage folder) to check why it is connecting to sandbox and not live org

**Comment by JasonMcAndrew** [comment]
So it's discovering the 2 organizations but then connecting to ourdomaintesting instead of ourdomain1. 
Log file attached.

[XrmToolBox_Connection-2017-03-30.txt](https://github.com/MscrmTools/XrmToolBox/files/882531/XrmToolBox_Connection-2017-03-30.txt)

**Comment by MscrmTools** [comment]
Ok, so the problem is from Microsoft SDK assemblies...

May I share this log file with Microsoft to see what is going on?

**Comment by JasonMcAndrew** [comment]
Yes go ahead. Thanks for your help.

**Comment by JasonMcAndrew** [comment]
Has there been any update from Microsoft on this?

Thanks
Jason

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #29](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/29) via [**ZenHub**](https://www.zenhub.com/)
