### ISSUE TITLE
Request: Metadata Document Generator Entity Properties

### ISSUE THREAD

**Issue by pete-mc** [MscrmTools/XrmToolBox#607]
Thanks for such a great tool!

Would you be able to add the additional entity properties to the summary page for example:
Feedback, Note, Activities, Sending Email, Mail Merge... etc.

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.MetadataDocumentGenerator #3](https://github.com/MscrmTools/MsCrmTools.MetadataDocumentGenerator/issues/3) via [**ZenHub**](https://www.zenhub.com/)
