### ISSUE TITLE
Unable to connect to Dynamics CRM

### ISSUE THREAD

**Issue by udinesh5** [MscrmTools/XrmToolBox#608]
Hi All,

I get 'Unable to connect to Dynamics CRM' error when I try to connect to D365 Online(8.2) instance hosted in AUS data center.
I tried to connect using both of the following ways
1. Actual URL (i.e. access CRM on browser)
2. URL with unique organisation name
Please find the log and screenshot attached.

I am able to connect to a US data center CRM2016 Online(8.1) instance not upgraded to the D365.
[XrmToolBox Connection Error.zip](https://github.com/MscrmTools/XrmToolBox/files/901513/XrmToolBox.Connection.Error.zip)

Thanks
Dinesh

**Comment by MscrmTools** [comment]
Hi,
Can you precise your XrmToolBox version?

Also, what information are in the connection logs?

**Comment by udinesh5** [comment]
The version is 1.2017.3.14

**Comment by MscrmTools** [comment]
Is the office365 tenant is federated with a local AD?

**Comment by udinesh5** [comment]
The tenant has DirSync configured. 
The user account I use on XrmToolBox is an "In cloud" username ending with .onmicrosoft.com.
Also, there 2 CRM instances.
I am able to connect and work with the CRM instance using Microsoft Dynamics CRM Plugin Registration Tool without any issues.

**Comment by MscrmTools** [comment]
Ok, this is a scenario I'm not able to test unfortunately. Any chance you provide me a similar test account?

**Comment by Customery** [comment]
I get the same error trying to connect to a Dynamics 365 online instance in the AUS data centre that uses DirSync (@customerdomain.com). I am successful connecting to the US data centre using Office 365 credentials (@microsoftonline.com). 

Let me know if you'd like me to provide a test account to help troubleshoot.

Vive la France!

**Comment by MscrmTools** [comment]
Yes, that would be awesome! Thanks Neil

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #28](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/28) via [**ZenHub**](https://www.zenhub.com/)
