### ISSUE TITLE
If overridepath is not used then plugins directory is deleted

### ISSUE THREAD

**Issue by CREFaulk** [MscrmTools/XrmToolBox#609]
I wasn't able to get XrmToolBox to load at all with any of the 2017 versions. The error I get isn't so relevant since it's obviously a result of the plugins directory not existing. The initial plugins.zip is extracted and both it and the plugins folder are deleted instead of just plugins.zip. If I extract plugins.zip manually then it gets deleted when XrmToolBox.exe is started without the overridepath command line parameter.

I searched and it doesn't get moved anywhere, just deleted.

The actual errors when starting look like this because the files are missing:
System.Reflection.ReflectionTypeLoadException: Multiple Exception Occured Attempting to Intialize the Plugin Manager
Exception 1
System.TypeLoadException: Method 'WorkAsync' in type 'DLaB.XrmToolboxCommon.DialogBase' from assembly 'DLaB.XrmToolboxCommon, Version=1.2015.7.6, Culture=neutral, PublicKeyToken=null' does not have an implementation.

If I run it from the command line like
   XrmToolBox.exe /overridepath:. 
then it works fine.

I'm using Windows 10 Professional x64 with current updates. I previously had a version 1.2015.7.6 used in a project to generate early bound entities but need to update. That version still works except but has a bug. I use the current version elsewhere, on server 2008/server 2012 for other plugins, fetchxml builder, etc. with no issues but wanted to see if I could get a newer version of the early bound generator plugin to add to the old project. This only has the issue on my Windows 10 laptop.

**Comment by MscrmTools** [comment]
Hi,
This is the expected behavior.

Since November 2016 version, all XrmToolBox related files are moved to your users roaming profile. You can access this folder from XrmToolBox options > Paths.

As for the error you get, this is because you are using an old version of Daryl Labar plugins, AFAIK

**Comment by daryllabar** [comment]
The older version of the EBG is not compatible with the newer version of the XTB.

**Comment by CREFaulk** [comment]
I'm not using the older version of EBG. It's 1.2017.3.23. If I don't use override path then it doesn't even get that far.

I deleted the MscrmTools folder from my roaming profile and unzipped a new copy of the XRM Toolbox zip and it works now. When I first tried to run the current version of the toolbox Symantec blocked it every time even after I tried putting in an exception. It probably didn't create all of the files but didn't copy to the roaming profile because some of the files were there.

**Comment by daryllabar** [comment]
You had the DLaB.XrmToolboxCommon.dll Version=1.2015.7.6 in your plugins directory.  The newest version of the plugin doesn't have that file, and so the standard update via the plugin store didn't delete it.  But when you cleared your roaming profile folder, that dll got deleted, and everything was "peachy keen".

I'd close this for your @MscrmTools, but you've never invited me to this git hub project ;)

**Comment by CREFaulk** [comment]
I'm closing this as resolved.
