### ISSUE TITLE
Easy Translator - Unable to import multiple entity options at once

### ISSUE THREAD

**Issue by slaplant** [MscrmTools/XrmToolBox#610]
Hi,
I am using CRM 2013 and Easy Translator. Whenever I try to export any combination of Entity related options translation, if I select Attributes and Relationships in the same export file, whenever I try to import it back it fails and I get the attached error message. I get this behavior for all my custom entities but not for built-in entities.

![image](https://cloud.githubusercontent.com/assets/22839137/24879480/1132a8f8-1e05-11e7-9c0a-4358adcab9b9.png)

Also, this might or might not be related but since playing with the translations, the charts functionality is no longer working for a specific entity only when changing the user language to french. I get a rendering error. It is still working in english though.

Any help or insight would be appreciated.
Thanks,
Stéphane

**Comment by MscrmTools** [comment]
Hi Stephane,

What is the version of Easy Translator you are using?

**Comment by slaplant** [comment]
I am currently using the version #1.2017.3.4

**Comment by MscrmTools** [comment]
Error seems related to relationships as per the error message.
And chance you share your file with me?

**Comment by slaplant** [comment]
Here it is: 
[InvMatter - Relationships.xlsx](https://github.com/MscrmTools/XrmToolBox/files/911349/InvMatter.-.Relationships.xlsx)

**Comment by MscrmTools** [comment]
Thanks 
I'll check that tomorrow

**Comment by slaplant** [comment]
Great. Thank you sir!

**Comment by MscrmTools** [comment]
Can you try this one?
[MsCrmTools.Translator.zip](https://github.com/MscrmTools/XrmToolBox/files/912331/MsCrmTools.Translator.zip)

**Comment by slaplant** [comment]
Ok, I have copied this file in the XRM toolbox folder. I then opened the Easy Translator new version #1.2017.4.5. I exported all the entity related options for the same entity and got the same error when trying to import that .xlsx file (without modification) - it seems to stop during Relationship importing.

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.Translator #4](https://github.com/MscrmTools/MsCrmTools.Translator/issues/4) via [**ZenHub**](https://www.zenhub.com/)
