### ISSUE TITLE
Every time I try to auto update the app I get an error

### ISSUE THREAD

**Issue by anothersphere** [MscrmTools/XrmToolBox#611]
Please see dump of error.
I have no idea what this issue is.

![capture](https://cloud.githubusercontent.com/assets/24686183/24990377/a7d4360a-2067-11e7-82ad-9c1d0ea8a4b3.PNG)

**Comment by MscrmTools** [comment]
Never got that one before... Is that possible that an antivirus is blocking access to the zip file downloaded?
