### ISSUE TITLE
XRM sitemap tool for dynamics 365 missfunction

### ISSUE THREAD

**Issue by nima19864** [MscrmTools/XrmToolBox#612]
In dynamic crm 2016 latest updae known as dynamics 365 ,XRM sitemap tool does not load the main sitemap . it loads user created apps.

**Comment by MscrmTools** [comment]
With latest version, it should ask which sitemap to load. Can you confirm?

**Comment by nima19864** [comment]
Thank you for follow up.
It does ask , but none of the options contain main app. It shows sitemap for applications made through my apps in settings menu. I can edit them in out of the box app designer. We need editing the default app sitemap.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by nima19864** [comment]
Made another try, by resetting to dynamics 365 default sitemap , everything seems to work good. I did not save it anyway because edited site map has took a lot of work and I do have a lot of custom entities. I have edited the site map in crm 2015 by your app and upgraded to 2016 and now 365 with no problem. Now I’m trying to make some other minor improvements and I cant find my sitemap in options.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MscrmTools** [comment]
What do you mean when saying "options"?

**Comment by nima19864** [comment]
[cid:image003.png@01D2BF48.4BBA3250]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MscrmTools** [comment]
The image does not display. Please use Github website to post your image

**Comment by akshaypattar** [comment]
Hey Nima19864
There will be 2 default Option try both, u will get main SiteMap

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.SiteMapEditor #10](https://github.com/MscrmTools/MscrmTools.SiteMapEditor/issues/10) via [**ZenHub**](https://www.zenhub.com/)
