### ISSUE TITLE
Privilege display problem in "Your User Security - Magnified"

### ISSUE THREAD

**Issue by emregulcan** [MscrmTools/XrmToolBox#613]
Hi,
"Your User Security - Magnified" plugin (v 1.0.17102.2) has some bug (I think) for displays privileges.
I can't see privilege names, just see entity names and privilege deep indicator.
You can see my screenshot here
https://www.dropbox.com/s/x05azj4tvm210ig/xrmtoolbox-01.PNG?dl=0

**Comment by MscrmTools** [comment]
This is not one of my plugin. Please get in touch with the plugin developer to get assistance

**Comment by norriqkve** [comment]
Hi emran,

I'm the developer of the "Your User Securiy - Magnified" plugin.
Sorry for the late reply...
The UI of this plugin is very basic and might get improved in later versions.  Currently there is no immediate displaying or labeling of the privileges.

However, there should be a small tooltip when you hover over the indicators.  Also, it follows the general displaying of privliges on the Security Roles within CRM(from left to right), being: Create, Read,  Write, Delete, Append, Append To, Assign, Share.

**Comment by emregulcan** [comment]
Hi @norriqkve ,
Thank you for your response, I got this hover indicators. Actually I wrote this maybe it might be bug for languages out of English, because my system language is Turkish.
At the end there is no bug it's a feature :), no problem for me but maybe newbees will have some problems about displaying / understanding.

regards
