### ISSUE TITLE
Unable to connect to .crm11.dynamics.com (UK Region) Instance

### ISSUE THREAD

**Issue by dashdotat** [MscrmTools/XrmToolBox#614]
It looks like MS have rolled out crm11 region (UK) and XrmToolbox is currently unable to connect to it - I assume (without diving through source) that for O365 it determines which region to connect to via the URL (and crm11 isn't supported as yet)

v1.2017.3.14

[XRMToolbox Log.txt](https://github.com/MscrmTools/XrmToolBox/files/947293/XRMToolbox.Log.txt)

**Comment by MscrmTools** [comment]
You are absolutely right but XrmToolBox is not the repository to look for to fix this "issue". It's handled by MscrmTools.Xrm.Connection project.

I will update it as soon as possible or you can fork the repository as I see you forked XrmToolBox one.

It's a single line of code to change I guess but I don't know if Microsoft provided the region name associated to crm11 geo

**Comment by dashdotat** [comment]
Thanks I wasn't aware of that - I've added a pull request to MscrmTools.Xrm.Connection now and closing this issue
