### ISSUE TITLE
Metadata Document Generator

### ISSUE THREAD

**Issue by NicoleCRM** [MscrmTools/XrmToolBox#617]
Just installed the latest version of the toolbox (v1. 2017.3.14) and it looks like the metadata document generator is gone. Anyone know another way to install this piece?

**Comment by MscrmTools** [comment]
It's a mistake...

It will be added with the next version.

**Comment by NicoleCRM** [comment]
Thanks!


___________________________________
Nicole A. Williams, Senior Analyst, Front Office Technology
Golub Capital  |  150 S. Wacker Drive  |  Chicago, Illinois 60606  |  T: 312.254.5757  |  M: 312.841.9548 |  F: 312.201.9167
nwilliams@golubcapital.com<mailto:nwilliams@golubcapital.com>  |  www.golubcapital.com<http://www.golubcapital.com/>
