### ISSUE TITLE
XrmToolBox crashes on plugin retrival

### ISSUE THREAD

**Issue by micheleietri** [MscrmTools/XrmToolBox#618]
As said in the title, when I open the plugin store, once the list got retrieved program crashed, I've the lastest version, and this happens both on win 10 and win server 2012 r2.

I tried to remove the installation, cleaning everything, but the issue happens every time.

Any suggestion?

**Comment by MichiFr** [comment]
Any details? I'm too seeing crashes since the Win10 Creators update from time to time and I too did update XrmToolkit to the latest version right now.

Michael

**Comment by r-weisser** [comment]
Looks like there's an issue with accessing the pluginstore after startup. So far I'm not aware of any solution using configparameter etc.
The issue seems to be a global one. Someone mentioned the usage out of a Azure VM could work.

**Comment by MichiFr** [comment]
I just added a new issue where XRMtoolbox is crashing because of a missing file called Cinteros.Xrm.CRMWinForm, Version=2017.2.22.14.

Don't know though if this is related to this reported crash here.

**Comment by micheleietri** [comment]
It seems that' the issue is linked to network conditions when I'm connected to company network it crashes every time, but I use my mobile one on hotspot it works sometimes, sometimes still crashes.

**Comment by MscrmTools** [comment]
Is it still happening?

**Comment by wakaru9** [comment]
Hi.
Thanks for the email.
The problem solved by looking at other forumer posting.
It is related to the plug-ins path.

Thanks for this fantastic tools.

Regards.

Sent from my iPhone

On 9 Jun 2017, at 12:18 AM, MscrmTools <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it still happening?
