### ISSUE TITLE
Crash when trying to update plugins - XrmToolbox cannot find a file

### ISSUE THREAD

**Issue by MichiFr** [MscrmTools/XrmToolBox#619]
Hi,

while trying to update one or more plugins using the store, XRMtoolbox immeditaley crashes, telling me that it couln't find a file or assembly with the name Cinteros.Xrm.CRMWinForm, Version=2017.2.22.14.

I did a quick lookup inside all directories inside C:\Users\fritzmi\AppData\Roaming\MscrmTools\XrmToolBox and tried to find any DLL with that file name to no avail so far

Am I missing something at this point? Of course I'm missing a file, however, where can I get this one or any appropriate installer for the missing assembly file?

Btw. I'm using the latest available version of the toolbox 1.2017.3.14

Pls. see attached crash report...

Thanks,
Michael
[crash.txt](https://github.com/MscrmTools/XrmToolBox/files/957793/crash.txt)

**Comment by rappen** [comment]
Hi,
A few plugins from me and Innofactor use this missing assembly. They have earlier referenced this assembly with different versions, but if you manage to get the latest of all these the problem _should_ be solved.

**Comment by MichiFr** [comment]
rappen,

does this apply, too, when just trying to download/install new plugin versions through the store? Guess not or better said I've now disabled all plugins from author Innofactor AB and Jonas Rapp, Innofactor - guess that's you, right?

Restarted and still see crashes using the plugin store and sometimes when existing XRMTools with the very same error - missing file Cinteros.Xrm....

I alread have unlocked the original ZIP-file XrmToolbox.zip before extracting the included files to no avail either. Maybe a different plugin uses this assembly, too and I missed it or maybe the source of the crashes is somewhere else?

Btw I'm trying to update the plugin CRM Workflow Explorer from version 1.2016.0.5 to 1.2016.0.3 nothing special I guess. OTH the crash happens while trying to update other plugins, too.

Michael

**Comment by rappen** [comment]
Hi Michael - yes this is me Jonas (full profile if you click my head to the left)
As your update suggests this appears to be regarding the plugins store. Guess I will have to call for @MscrmTools to see if he can assist on this...

**Comment by MscrmTools** [comment]
The plugins store bug is knowed and already fixed. I just need to review repo issues if there are additional easy stuff to fix before releasing a new version. 
In the meantime, please untick the checkbox

**Comment by MscrmTools** [comment]
But I don't see the link with rappen's dll missing

**Comment by CRMBoy** [comment]
Hi,
who is the Author of Workflow Explorer plugin, I need some help in this regard, please suggest, thanks.

**Comment by MscrmTools** [comment]
Closing this issue, please reopen if needed
