### ISSUE TITLE
Can't Create Connection

### ISSUE THREAD

**Issue by RBellefond** [MscrmTools/XrmToolBox#62]
Hi.  I am new to using XRMToolBox.  I have CRM 2015 On Premise with IFD setup.

When I try to create a new connection in XRMToolBox

When I put in the Connection Name, Server Name, Port, use Windows Authentication I get an error retrieving Organization SOAP security negotiations message.  Any suggestions on how to fix this?

Thanks.

Rick Bellefond

**Comment by MscrmTools** [comment]
Server name should use discovery service dns alias
Username sometimes has to be on the form domain\login, sometimes just login
Can you display error message screenshot?

**Comment by RBellefond** [comment]
Hi.  First of all thanks for getting back to me so quickly.

How do I attach a screen shot here?

If I follow the instructions below by clicking on selecting them below, I get:

![xrmtoolbox_error](https://cloud.githubusercontent.com/assets/11426892/6600933/8ca6e030-c7e0-11e4-91e8-aaf9ff182ac5.png)

Thanks

**Comment by RBellefond** [comment]
Never mind my question about selecting images.

**Comment by MscrmTools** [comment]
Ok, so I can see at the end of the error message, that the target is not reachable.

It looks like the communication between XrmToolBox, CRM and ADFS can't reach https://adfs.rbdata.com

Can you put the full url mentionned in your browser and see if it succeed to load a page?

**Comment by RBellefond** [comment]
No, if I put that url in my browser I get:

![xrmtoolbox_error_2](https://cloud.githubusercontent.com/assets/11426892/6601276/c0cca4ce-c7e2-11e4-8209-bd3076c14716.png)

I am able to run my CRM both from within my network and outside my network

Thanks

**Comment by MscrmTools** [comment]
I don't know your infrastructure so it is not easy to help. 

Maybe you need to fill the Realm url but I can't tell you if this is required and what the value would be

**Comment by MscrmTools** [comment]
This is the problem when you develop tools and you don't have access to all kind of deployments...

If you are geek enough, you can take a trace with Fiddler to compare connexion process when connecting to CRM with your browser or with XrmToolBox

**Comment by RBellefond** [comment]
No, I am not geek enough to do that.  :)

I hired someone to help me set up my CRM 2015 system.

I am able to access my CRM from outside my network.

From inside my wifi network, I am also able to access my CRM either from my server or from a PC that is running a cable to my router.  I am NOT able to access my CRM wirelessly from inside my network.

They never could figure that out.

I wonder if that issue is related to the issue that I am having trying to connect to CRM from XrmToolBox.

Maybe this is a good stopping point for me.

Thanks for trying to help me get this resolved.

**Comment by MscrmTools** [comment]
Sorry not being able to help you more
