### ISSUE TITLE
Throwing unhandled exception (Entity Relation Diagram Creator).

### ISSUE THREAD

**Issue by nadeemmails** [MscrmTools/XrmToolBox#620]
When I click to generate data model from dynamics CRM using Entity Relation Diagram Creator after few seconds it throws an error saying "found a string attribute with unrecognized format"

![image](https://cloud.githubusercontent.com/assets/28075000/25476717/ba70d574-2b58-11e7-89a6-800ec6268599.png)

**Comment by rappen** [comment]
You need to contact the author at http://journeyintocrm.com/archives/1881 as this is not a plugin by @MscrmTools

**Comment by MscrmTools** [comment]
Thanks @rappen 

Closing this issue
