### ISSUE TITLE
Use Existing Connections When Changing a Connection

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#624]
Given this state:

- 2 plugins opened A and B
- A is connected to "Dev"
- B is connected to "Prod"
- XTB lists Connected to as "Prod", so any new plugins will have a "Prod" connection.

When switching the connection from Prod to Dev, the XTB appears to create an entirely new connection to Dev.

Any chance it can just use the existing connection rather than taking 3-4 second to create another connection to Dev?

**Comment by MscrmTools** [comment]
It should be possible to maintain a list of connections used during the session and to obtain it form there when "reconnecting"

**Comment by daryllabar** [comment]
That's what I was hoping for!  Let me know when it's done ;)

**Comment by MscrmTools** [comment]
I will just move this "issue" to the appropriate repository since it will be handled by connection project

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #26](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/26) via [**ZenHub**](https://www.zenhub.com/)

**Comment by daryllabar** [comment]
I do a poor job of putting it in the correct project...
