### ISSUE TITLE
Enhancement - Setting to Act on behalf of

### ISSUE THREAD

**Issue by daggen** [MscrmTools/XrmToolBox#625]
Hi, Some plugins would be great to be able to run as Act on Behalf of. FetchXML Builder, Counter, Excel Export etc. Instead of having each plugin incorporate this feature I think it would be great to be able to have a button/dropdown in top ribbon which allows you to pick any users in the system. Once you are done with that users you can always switch back to your original user and continue working with same plugins.

**Comment by MscrmTools** [comment]
A first version of this request will be available soon

Teasing screenshot 

![image](https://user-images.githubusercontent.com/10774317/81320639-cc45b700-9091-11ea-988b-380b33ef2f70.png)
