### ISSUE TITLE
Error when clicking on "Calculate Rollup Field Tool" in Plugin Store window

### ISSUE THREAD

**Issue by bedgren** [MscrmTools/XrmToolBox#628]
![2017-05-10_9-32-34](https://cloud.githubusercontent.com/assets/12127147/25904198/251fe9fe-3564-11e7-93cf-b4c4a4e772f5.jpg)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The remote name could not be resolved: 'www.google.https'
   at System.Net.WebClient.OpenRead(Uri address)
   at System.Windows.Forms.PictureBox.Load()
   at XrmToolBox.Forms.PluginsChecker.BuildPropertiesPanel(IPackage package)
   at XrmToolBox.Forms.PluginsChecker.lvPlugins_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2016.10.2
    Win32 Version: 1.2016.10.2
    CodeBase: file:///C:/Program%20Files/XrmToolBox/XrmToolBox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2016.10.2
    Win32 Version: 1.2016.10.2
    CodeBase: file:///C:/Program%20Files/XrmToolBox/XrmToolBox.Extensibility.DLL
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 6.1.7601.23675
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2016.9.1
    Win32 Version: 1.2016.9.1
    CodeBase: file:///C:/Program%20Files/XrmToolBox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2016.9.1
    Win32 Version: 1.2016.9.1
    CodeBase: file:///C:/Program%20Files/XrmToolBox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 8.0.0.0
    Win32 Version: 8.1.0.383
    CodeBase: file:///C:/Program%20Files/XrmToolBox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
BDK.XrmToolBox.RecycleBin
    Assembly Version: 1.2017.4.1
    Win32 Version: 1.2017.4.1
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/BDK.XRMTOOLBOX.RECYCLEBIN.DLL
----------------------------------------
BDK.XrmToolBox.StorageCleaner
    Assembly Version: 1.2016.11.3
    Win32 Version: 1.2016.11.3
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/BDK.XRMTOOLBOX.STORAGECLEANER.DLL
----------------------------------------
BDK.XrmToolBox.UserAuditViewer
    Assembly Version: 1.2016.11.3
    Win32 Version: 1.2016.11.3
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/BDK.XRMTOOLBOX.USERAUDITVIEWER.DLL
----------------------------------------
Cinteros.Xrm.CRMWinForm
    Assembly Version: 2017.2.22.14
    Win32 Version: 2017.2.22.14
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.CRMWINFORM.DLL
----------------------------------------
Cinteros.Xrm.FetchXmlBuilder
    Assembly Version: 1.2017.2.117
    Win32 Version: 1.2017.2.117
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.FETCHXMLBUILDER.DLL
----------------------------------------
Cinteros.Xrm.XmlEditorUtils
    Assembly Version: 1.2017.2.117
    Win32 Version: 1.2017.2.117
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.XMLEDITORUTILS.DLL
----------------------------------------
Cinteros.XTB.PluginTraceViewer
    Assembly Version: 1.2017.3.26
    Win32 Version: 1.2017.3.26
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/CINTEROS.XTB.PLUGINTRACEVIEWER.DLL
----------------------------------------
Cinteros.XTB.ViewDesigner
    Assembly Version: 1.2016.8.7
    Win32 Version: 1.2016.8.7
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/CINTEROS.XTB.VIEWDESIGNER.DLL
----------------------------------------
Colso.DashboardTransferTool
    Assembly Version: 1.2016.7.9
    Win32 Version: 1.2016.7.9
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/COLSO.DASHBOARDTRANSFERTOOL.DLL
----------------------------------------
Colso.DataTransporter
    Assembly Version: 1.2016.10.2
    Win32 Version: 1.2016.10.2
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/COLSO.DATATRANSPORTER.DLL
----------------------------------------
Colso.Xrm.AttributeEditor
    Assembly Version: 1.2016.8.1
    Win32 Version: 1.2016.8.1
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/COLSO.XRM.ATTRIBUTEEDITOR.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2016.10.3
    Win32 Version: 1.2016.10.3
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2017.1.2
    Win32 Version: 1.2017.1.2
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
Develop1.XrmTBPlugin.RibbonWorkbench2016
    Assembly Version: 3.0.25.3
    Win32 Version: 3.0.25.3
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/DEVELOP1.XRMTBPLUGIN.RIBBONWORKBENCH2016.DLL
----------------------------------------
DocumentFormat.OpenXml
    Assembly Version: 2.5.5631.0
    Win32 Version: 2.5.5631.0
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/DOCUMENTFORMAT.OPENXML.DLL
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly Version: 1.2017.1.2
    Win32 Version: 1.2017.1.2
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2017.1.6
    Win32 Version: 1.2017.1.6
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2016.5.1
    Win32 Version: 1.2016.5.1
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2016.5.1
    Win32 Version: 1.2016.5.1
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly Version: 1.2017.1.4
    Win32 Version: 1.2017.1.4
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2016.9.1
    Win32 Version: 1.2016.9.1
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly Version: 1.2016.8.2
    Win32 Version: 1.2016.8.2
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2016.11.2
    Win32 Version: 1.2016.11.2
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2016.10.4
    Win32 Version: 1.2016.10.4
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2017.1.3
    Win32 Version: 1.2017.1.3
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2017.1.3
    Win32 Version: 1.2017.1.3
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2017.4.10
    Win32 Version: 1.2017.4.10
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2016.6.3
    Win32 Version: 1.2016.6.3
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2017.3.4
    Win32 Version: 1.2017.3.4
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2017.4.4
    Win32 Version: 1.2017.4.4
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MsCrmTools.WebResourcesManager
    Assembly Version: 1.2017.3.9
    Win32 Version: 1.2017.3.9
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
RazDynamics.DuplicatesReportForBulkMerge
    Assembly Version: 1.2016.7.17
    Win32 Version: 1.2016.7.17
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/RAZDYNAMICS.DUPLICATESREPORTFORBULKMERGE.DLL
----------------------------------------
Ryr.SolutionHistory
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/RYR.SOLUTIONHISTORY.DLL
----------------------------------------
Ryr.XrmToolBox.EntityImageUpdater
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/RYR.XRMTOOLBOX.ENTITYIMAGEUPDATER.DLL
----------------------------------------
UserTeamSecurityRoleReporter
    Assembly Version: 1.2016.10.2700
    Win32 Version: 1.2016.10.2700
    CodeBase: file:///C:/PROGRAM%20FILES/XRMTOOLBOX/PLUGINS/USERTEAMSECURITYROLEREPORTER.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 8.0.0.0
    Win32 Version: 8.1.0.359
    CodeBase: file:///C:/Program%20Files/XrmToolBox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
MetadataViewProxies_aa338b82-9cbc-43fd-8b48-9d0a816e92fb
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1098.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/XrmToolBox/McTools.StopAdvertisement.DLL
----------------------------------------
NuGet.Core
    Assembly Version: 2.11.1.812
    Win32 Version: 2.11.1.812
    CodeBase: file:///C:/Program%20Files/XrmToolBox/NuGet.Core.DLL
----------------------------------------
System.Data.Services.Client
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Services.Client/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Services.Client.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1098.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by MscrmTools** [comment]
This is mainly a problem with the nuget package for this plugin.
I will handle the error in a next release but in the mean time, you can contact the developer so he can fix the package

**Comment by bedgren** [comment]
Will do!  Thanks for the quick reply

**Comment by MscrmTools** [comment]
oh, it seems you are on a very old version of XrmToolBox. Please download the latest version. The exception should be handled
