### ISSUE TITLE
Issue on launch

### ISSUE THREAD

**Issue by spcoman** [MscrmTools/XrmToolBox#629]
What is this being caused by? How do i correct it?

![xrmproblem](https://cloud.githubusercontent.com/assets/25466676/25919548/0d9d0300-359d-11e7-9fe6-01588262aaf6.JPG)

**Comment by MscrmTools** [comment]
You have old versions of some cinteros plugins. Update them or delete them from the plugins folder

**Comment by spcoman** [comment]
Where can I access the plugins folder?

**Comment by daryllabar** [comment]
You can view the path to your plugins on int Options Window.  (Click the Gear Icon in on the main Tool Bar)
