### ISSUE TITLE
How to Print Diagram from WorkFlow Explorer 

### ISSUE THREAD

**Issue by CRMBoy** [MscrmTools/XrmToolBox#630]
Hi folks,
I want to print Workflow diagrams from Workflow Explorer  XRMToolBox but there is no option available, can anybody guide me any solution for this, thanks in advance.

BR/ Faisal

**Comment by MscrmTools** [comment]
This is not one of mine plugins so I suggest you contact the author of this plugin

**Comment by CRMBoy** [comment]
Hi MscrmTools,
How would I know that who is the Author of this plugin as I am new please guide me thanks.
