### ISSUE TITLE
updated XRMtoolbox today to the latest and now get an error on load

### ISSUE THREAD

**Issue by nzhome** [MscrmTools/XrmToolBox#632]
Could not load file or assembly Newtonsoft.Json  version=9.0.0.0 or one of its dependencies.

how can I fix this?

**Comment by MscrmTools** [comment]
I updated my XrmToolBox the same way and I did not get the same error... 
I checked that Newtonsoft.Json is in the XrmToolBox zip file so you should have it. Can you check in your XrmToolBox folder?

**Comment by MscrmTools** [comment]
I close this issue. Please reopen it and add comment if you still get that error
