### ISSUE TITLE
Application Settings and TFS

### ISSUE THREAD

**Issue by LeszekSzejka** [MscrmTools/XrmToolBox#633]
At this moment default location for storing all data/settings is /...AppData/Roamin/...
This can be overwritten by creating a shortcut icon with proper params.

Imagine a situation when a TFS/GIT is used to store a common project settings/tools as solution folder at ProjectName/tools/Xrmtoolbox. There is no way to provide a relative path for all plugins, images, settings etc. It needs to be an absolute path, which in fact can be different at each client/dev site, depending where branch/local repos is stored. Because of these instead of having a fixed location each dev needs to change it to reflect theirs location.

Sure this is not a big issue but when working with any source control tool this should be a fixed location, with fixed settings to provide a common tools which will not lead to any discrepancies.

**Comment by shytikov** [comment]
Can `SymLinks` Windows feature be an answer for your request?

https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by MscrmTools** [comment]
I close this issue. Can reopen if needed
