### ISSUE TITLE
Changed password now getting 'Required xml:lang attribute value is missing."

### ISSUE THREAD

**Issue by xairrick** [MscrmTools/XrmToolBox#634]
I had existing connection that was working.  I edited the connection to update my password and everything was successful, but now when I try to connect I get an "Required xml:lang attribute value is missing" error. 
![2017-05-16 08_01_50-xrmtoolbox for microsoft dynamics crm _ 365 ce v1 2017 5 15](https://cloud.githubusercontent.com/assets/80464/26105003/50b4b58c-3a0e-11e7-819d-736267d7dd45.png)

I was able to create a new connection to the same crm org and the new connection works fine.

**Comment by MscrmTools** [comment]
Can you reproduce anytime?

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #33](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/33) via [**ZenHub**](https://www.zenhub.com/)
