### ISSUE TITLE
Data Transporter - XML filter fails

### ISSUE THREAD

**Issue by Dagga9** [MscrmTools/XrmToolBox#635]
Hello,
I'm not sure if this is the right place to ask about my issue...
I have created a XML filter from advanced find i CRM and pasted the XML into Data Transporter filter, but i only gat an error saying: An error occurred while analyzing the EntityName. Line 1 Pos 543.

Have i done anything wrong when i created the filter? Or i'm I inserting the filter wrong?

Hope for a quick respond.

D

**Comment by MscrmTools** [comment]
Here is your quick answer=> this is not the right place to ask this question since I'm not the owner of this plugin. 

Find the owner and ask him
