### ISSUE TITLE
Why MetaData Document Generator is not anymore on the plugin store?

### ISSUE THREAD

**Issue by Macias31** [MscrmTools/XrmToolBox#637]

**Comment by MscrmTools** [comment]
It never was! It is supposed to be shipped with XrmToolBox package.
You should have it when you install or update XrmToolBox 
What is your current version?

**Comment by Macias31** [comment]
1.2017.5.3

**Comment by MscrmTools** [comment]
You meant 1.2017.5.15? .3 does not exist

So with this version, you should have metadata document generator
