### ISSUE TITLE
Plugin list view height incorrectly size

### ISSUE THREAD

**Issue by amoedo** [MscrmTools/XrmToolBox#64]
As per the capture below the plugin list overlaps the items. This appears to only happen in computers where the Windows Display Settings are set to increase the size of all the items > 100%

![xrmtoolbox issue](https://cloud.githubusercontent.com/assets/8993332/6623136/037f7016-c8d9-11e4-8832-afcafedc0ab9.png)

**Comment by shytikov** [comment]
Wow, that's strange... Do you using font magnification? Or how this Windows' feature called, then fonts in the system might be from 80% to 150% of their default size?

**Comment by amoedo** [comment]
It happens on my machine at the office. It is due to the scallin on Windows. My display settings are to 125%
I've submitted a small pull request with a possible fix by changing the Autoscale to DPI and use the control actual size for the spacing instead of a fix value.

**Comment by shytikov** [comment]
I don't know will it work as expected... It might happen that whole plugin positioning mechanism should be adopted to this scaling feature. But let's wait what @MscrmTools will say.

**Comment by MscrmTools** [comment]
I searched thousand times how to fix this!! If it works, then it's really nice! I will merge the pull request and perform some test.
I didn't know the possibility to user DPI instead of Font sizing.

**Comment by amoedo** [comment]
I've done some testing with 100% and 125% settings on my machine. It seems to be working fine. It is painful to test because every time you change these display settings you have to log off and back on again :( Let me know if I can help

**Comment by shytikov** [comment]
Deleted my previous comment, since took a look on the code, and resolved all resolved all questions and concerns for myself :+1:

**Comment by MscrmTools** [comment]
I merged your pull request so I close this issue
