### ISSUE TITLE
Plugin Store error

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#640]
I am getting this weird error today when I launch plugin store.

![image](https://cloud.githubusercontent.com/assets/5035266/26607080/0a5a88c0-45d8-11e7-8091-a2f915381546.png)

I deleted the plugins that I installed/update today and found that installing "XrmToolBox Entity 360 View" caused this issue. I wonder how a can third party plugin can break the plugin store.

Can someone confirm that they get the same behaviour?

**Comment by rappen** [comment]
Confirmed.

**Comment by MscrmTools** [comment]
Let me try to reproduce

**Comment by DiggaTheWolf** [comment]
Same here, posted a comment on this: [https://github.com/MscrmTools/XrmToolBox/issues/599](url)

**Comment by joenewstrom** [comment]
+1 Confirmed here.

**Comment by sureshrapur** [comment]
+2 confirmed

**Comment by MscrmTools** [comment]
Problem found, it is due to Entity 360 View plugin. But I will add some checks to avoid crashing the whole plugins store

**Comment by acehaddock** [comment]
Confirmed here too just download to upgrade my old ver.  p
