### ISSUE TITLE
MscrmTools branding

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#641]
I installed these tools from the store today under the impression that these were developed by @MscrmTools but they are not.

![image](https://cloud.githubusercontent.com/assets/5035266/26607472/f770eaea-45d9-11e7-91a3-d863814bb2d6.png)

Can we please prevent people from doing this in the future? Please highlight the official plugins (MscrmTools brand) and differentiate the third party plugins in the store and also in the main interface (prevent people from using black text on lavender background as it stands for officially endorsed plugin). The other option is to automatically update official plugins and even XrmToolBox itself, just like how Chrome does it.

Please confirm if these are "official" plugins.

**Comment by rappen** [comment]
This will be handled once the XTB portal is in place, all plugin wannabes will go through a qualification process :)

**Comment by MscrmTools** [comment]
Absolutely! @rappen is correct!

For a preview of the future portal, please go there : https://ww2.xrmtoolbox.com

**Comment by shytikov** [comment]
I think it could be done without portal even today, but depends are we're able to get information about `PublicKeyToken` from NuGet. 

I guess @MscrmTools signs his assemblies with password protected key, so no one else can have same `PublicKeyToken`. So we can hardcode proper value (or compare with current value of the main assembly) and thus indicate `official` assemblies.

**Comment by shytikov** [comment]
BTW, I believe these `unofficial` plugins happens not due to evil intentions, but rather because plugin bootstrapping is still quite complex, and it's easier to copy code from one of available plugins, than start your own. Especially if you're consultant, not developer... But these efforts are still appreciated! I believe it's too harsh to ban such plugins just because person not C# ninja. We might issue notice and not mark it official based either on `PublicKeyToken` or publisher name.

**Comment by shytikov** [comment]
And yes, it looks like identifying on publisher name should be much simpler than on `PublicKeyToken` 😄  But you know... in world of `Bitcoin` and WannaCry` crypto detection of author of package looks more appropriate and definitely not an overkill 😄

**Comment by MscrmTools** [comment]
Currently, my assemblies are digitally signed after compilation. I could check if I'm able to read that information

**Comment by rajyraman** [comment]
Agree the intention of the dev was not to mislead and these new plugins are quite helpful, but highlighting officially endorsed plugin means I don't have to think twice before installing it.

**Comment by santoshCRM** [comment]
I had done these by mistake. I have changed all information copied by existing plugin. Now it will show correct information i.e name and logo.
![image](https://user-images.githubusercontent.com/23490088/28265453-6f12b602-6b0d-11e7-95ee-eb4c8ed69e91.png)
