### ISSUE TITLE
Plugin Update

### ISSUE THREAD

**Issue by DiggaTheWolf** [MscrmTools/XrmToolBox#642]
Hi

Just wondering why for some plugins that report an updated version, never get updated to the latest version when running the update process in XrmToolBox.

The ones for me that are failing are: 

- CRM Workflow Explorer 1.2016.0.3 > 1.2016.0.5
- Role Replicator 1.0.0.0 > 1.2017.5.11
- Soaplogger 1.0.0.0 > 1.2017.5.27
- User Audit Viewer 1.2017.5.1 > 1.2017.5.2

Not a biggie, just seems odd the tool reports the version update, but, can't grab it.

Kind regards,

Lee

**Comment by daryllabar** [comment]
Hmm... I wonder if the DLL versions aren't in sync?

**Comment by daryllabar** [comment]
If you download the nuget package directly and unzip, does the DLL version match the nuget version?

**Comment by DiggaTheWolf** [comment]
Hi Daryl

Tried this with Role Replicator, and no the assembly is version 1.0.0.0. Based on this I'm assuming the latest is installed, the author just needs to make sure the assembly and NuGet package versions match, is that correct?

**Comment by DiggaTheWolf** [comment]
Tried this with the others I listed too, same results, mismatch between assembly versions and NuGet package versions.
