### ISSUE TITLE
XrmToolbox crashes after installing all plugins

### ISSUE THREAD

**Issue by mdocter** [MscrmTools/XrmToolBox#649]
I was crazy enough to check all plugins from the store and install them. After that my XrmToolbox keeps crashing on startup. Even when I download the latest XTB version and run that, the same crash happens.
My Windows Event Log looks like pointing in the direction of the 'Entity 360 View' plugin.

How can I remove this plugin from being loaded? I can't seem to find some `*.xml` file or registry setting listing the checked plugins. And where are those plugin files located on the file system? I found the `C:\ProgramData\XrmToolBox` folder but that seems to be of no use in this case.

**Comment by MscrmTools** [comment]
The plugins are located in C:\users\your_login\appdata\mscrmtools\xrmtoolbox\plugins

Delete the file that cause problem and you should be good

**Comment by mdocter** [comment]
That's great! I will give it a try.
Thanks for the quick response!

**Comment by mdocter** [comment]
The `\Roaming\` part was missing from the path, but it worked like a charm:

`C:\Users\[username]\AppData\Roaming\MscrmTools\XrmToolBox\Plugins`

As expected, it was the `XrmToolBox Entity 360 View.dll` plugin that was crashing my toolbox. After deleting this file, it worked again.
