### ISSUE TITLE
Counter should use same font color as plugin

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#651]
If the counter has the font color defined for the plugin it will be readable :)

![image](https://user-images.githubusercontent.com/2572253/27275841-716e0162-54d9-11e7-8222-ea8801479026.png)

Just like it has when you display Small Icons :)

![image](https://user-images.githubusercontent.com/2572253/27275903-a66c08e6-54d9-11e7-88ae-3742262d6749.png)

**Comment by MscrmTools** [comment]
Ready! Waiting for sync
