### ISSUE TITLE
Feedback: Possiblity to search plugins in name and description via XRMtoolbox GUI

### ISSUE THREAD

**Issue by github3332** [MscrmTools/XrmToolBox#653]
Now that there are loads of similar sounding plugins, it's quite difficult to remember which plugin does what.. Also sometimes the name of the plugin doesn't tells what it actually does.

It would be a great addition to have the basic search facility in the main XRMtoolbox GUI for freetext search in plugin name and description.

Btw, keep the excellent work up with toolbox development. Kudos.

**Comment by rappen** [comment]
Anything wrong with this...? :)

![image](https://user-images.githubusercontent.com/2572253/27334743-8c3c309e-55ca-11e7-889e-3a25a2293064.png)

**Comment by MscrmTools** [comment]
I guess @rappen did answer the question

**Comment by myfairsyer** [comment]
In @rappen's screenshot it says 

> by plugin name or company name

If the filter actually also searches the description maybe that should be reflected int the tooltiptext aswell.

See https://github.com/MscrmTools/XrmToolBox/blob/master/XrmToolBox/MainForm.Designer.cs#L246

**Comment by myfairsyer** [comment]
With https://github.com/MscrmTools/XrmToolBox/commit/29426f19cc93ad686bf440eb6321dd0ac2ea7dcc#diff-c39a705a788c913e63c9b7f7f9efdcd4R169 the search box' tooltip now explicitly mentions that the description is also being searched when filtering
