### ISSUE TITLE
Search field could be wider

### ISSUE THREAD

**Issue by bwmodular** [MscrmTools/XrmToolBox#655]
Due to the every increasing number of plugins in the toolbox, it is getting harder to find the tool you want.
This would be helped if the search field was a little wider, so you can see more of the name of the plugin:
![image](https://user-images.githubusercontent.com/1889586/27426469-bcc80f34-5733-11e7-84f5-d273b622a019.png)

**Comment by rappen** [comment]
+1

**Comment by MscrmTools** [comment]
I agree but what buttons should be icon only to make this happen?

**Comment by bwmodular** [comment]
I may be wrong, but most are probably working on wide enough monitors to accommodate a little more on the toolbar:
![image](https://user-images.githubusercontent.com/1889586/27427329-7fa449a8-5736-11e7-82e6-f389e6f0c5a6.png)

**Comment by MscrmTools** [comment]
I'm working on wide monitor too but not everybody does... maybe I can define the textbox to use all remaining space. Need to check

**Comment by rappen** [comment]
One option is to move some stuff to a menu bar instead.
Or just collect them in drop-down buttons.

These are just some examples of grouping stuff:

![image](https://user-images.githubusercontent.com/2572253/27428118-5f17a1c0-5741-11e7-8b10-b4f4fc87a18e.png)

![image](https://user-images.githubusercontent.com/2572253/27428149-7730d768-5741-11e7-95ed-6514d73a5b91.png)

**Comment by MscrmTools** [comment]
I think I will go with that solution, thanks @rappen

**Comment by MscrmTools** [comment]
What about this?

![image](https://user-images.githubusercontent.com/10774317/27578759-4cdd74d4-5b25-11e7-87e2-02c58f2a09dd.png)

![image](https://user-images.githubusercontent.com/10774317/27578766-535fa156-5b25-11e7-9fac-2fd878acfd90.png)

**Comment by bwmodular** [comment]
Fantastic!

**Comment by rappen** [comment]
Très belle!

**Comment by MscrmTools** [comment]
Ready! waiting for sync
