### ISSUE TITLE
Display mostly recent installs on the top

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#656]
Lot of times, I install new plugin after looking them in the store, but I can't remember the name of it after 10-15 minutes. I then have to go the XrmToolBox storage folder and sort the dlls descending to find what to search for. Can we just have another option to show the most recently installed plugins on the top just like "Display most users tools first" option?

**Comment by MscrmTools** [comment]
That is not that easy since XrmToolBox is not aware of installation date

**Comment by rajyraman** [comment]
I think it is possible using Assembly creation timestamp. I'll work on this little more before committing the changes.

![image](https://user-images.githubusercontent.com/5035266/27635265-a781ea26-5c49-11e7-8223-67fab815dd9c.png)
