### ISSUE TITLE
Trouble creating a new connection to D365 online

### ISSUE THREAD

**Issue by AnnaVienna** [MscrmTools/XrmToolBox#659]
Hi,
I tried creating a new connection in the XrmToolBox to our D365 online instance.
I entered the Organization url (https://xxx.crm4.dynamics.com/) and on the next page provided the Username & PW of an admin user I normally use. Then, I get an error msg saying that my info has not been validated.
clientCredentials.UserName.UserName or
clientCredentials.Windows.ClientCredential.UserName MUST be populated!
If the unique name for your org is different from the name...
the unique org name I found on the developer page under Settings is org9f2f..... Do I need to insert it in the url?
Is there anything specific I need to do to establish a connection with an Online environment?

Thanks in advance,
Anna

**Comment by MscrmTools** [comment]
The "unique org name" message does not apply anymore.

Is your Office 365 federated with your local AD?

**Comment by AnnaVienna** [comment]
The active directory is located in our client's environment. As far as I know, their AD is federated with Office 365.

**Comment by MscrmTools** [comment]
I think there can be some problem with this kind of configuration... I don't have this kind of environment to test my code unfortunately

**Comment by AnnaVienna** [comment]
I see, thanks anyways! Does the new xrmToolBox version generally support D365 online?

**Comment by MscrmTools** [comment]
Yes, of course

**Comment by AnnaVienna** [comment]
thx!
