### ISSUE TITLE
Bulk Record Assigner plugin only assigns records occasionally.

### ISSUE THREAD

**Issue by anthonyparks** [MscrmTools/XrmToolBox#660]
I am attempting to use the "Bulk Record Assigner" plugin to assign saved views and dashboards owned by enabled and disabled users to other users such as myself but 90% of the time I get a message stating 0 successes and 0 failures. Accounts and opportunities have a somewhat higher rate of success but the saved views and dashboards are the critical point of the project. Can anyone provide assistance and / or feedback as to why the records aren't assigning even after connecting to an instance and viewing the users? I know the user's have and own the views because I am logged in to the instance now online looking at them.

**Comment by MscrmTools** [comment]
This is not my plugin. Please contact the plugin author
