### ISSUE TITLE
Metadata Document Generator - Enhancement: Excel export into single sheet

### ISSUE THREAD

**Issue by AlexMcLachlan** [MscrmTools/XrmToolBox#662]
Hi, 
I've used this really handy tools several times and end up wanting all the results combined in a single sheet and having to do this via macros.
Would it be possible to add an option for export to Excel to do this please?
A couple of additional columns at the start with entity display name and entity logical name can then be used to filter the sheet as appropriate.
All the best, Alex

**Comment by MscrmTools** [comment]
What plugin are you talking about??

**Comment by AlexMcLachlan** [comment]
Sorry - the Metadata Document Generator

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.MetadataDocumentGenerator #1](https://github.com/MscrmTools/MsCrmTools.MetadataDocumentGenerator/issues/1) via [**ZenHub**](https://www.zenhub.com/)
