### ISSUE TITLE
User Settings Utility not working

### ISSUE THREAD

**Issue by rskadk** [MscrmTools/XrmToolBox#663]
Using the latest XrmToolbox (1.2017.7.18 - just downloaded and extracted to the desktop). I get an error when loading users and settings:
"An error occurred: 'SystemForm' entity doesn't contain attribute with Name = 'uniquename'."
I can see all the records loaded. But the pane on the right is not updating. Each time I click on a User record I get an undhanded exeption.

**Comment by rajyraman** [comment]
Duplicate of https://github.com/MscrmTools/MsCrmTools.UserSettingsUtility/issues/15

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.UserSettingsUtility #23](https://github.com/MscrmTools/MsCrmTools.UserSettingsUtility/issues/23) via [**ZenHub**](https://www.zenhub.com/)
