### ISSUE TITLE
Error when running XrmToolBox: Could not load file or assembly 'Cinteros.Xrm.XmlEditorUtils'

### ISSUE THREAD

**Issue by mattman07** [MscrmTools/XrmToolBox#665]
XrmToolBox was working OK but has decided to give up the ghost since I've returned from holiday!
I'm new to the world of CRM and .Net, so I'm hoping it's a simple newbie error!

I've tried different versions of the toolbox but all give the same error:

![image](https://user-images.githubusercontent.com/31248941/29601591-37668e52-87d4-11e7-9da0-b6eef023d675.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'Cinteros.Xrm.XmlEditorUtils, Version=1.2016.4.106, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Cinteros.Xrm.XmlEditorUtils, Version=1.2016.4.106, Culture=neutral, PublicKeyToken=null'
   at XrmToolBox.PluginManagerExtended.Initialize()
   at XrmToolBox.MainForm.<MainForm_Load>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2017.7.18
    Win32 Version: 1.2017.7.18
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2103.2 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2017.7.10
    Win32 Version: 1.2017.7.10
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2104.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 10.0.15063.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly Version: 1.2017.6.6
    Win32 Version: 1.2017.6.6
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
    Assembly Version: 2.12.0.817
    Win32 Version: 2.12.0.817
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/NuGet.Core.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2017.5.14
    Win32 Version: 1.2017.5.14
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2017.4.13
    Win32 Version: 1.2017.4.13
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 8.0.0.0
    Win32 Version: 8.2.0.713
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly Version: 8.0.0.0
    Win32 Version: 8.2.0.749
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 8.0.0.0
    Win32 Version: 8.2.0.749
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.2.808
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 2.24.0.0
    Win32 Version: 2.24.30411.1323
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms
    Assembly Version: 2.24.0.0
    Win32 Version: 2.24.30411.1323
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/MattHall/CRM%20docs/Training/FastTrack%20CRM%20Dev/CrmDev_Day5Final/CrmDev/utils/XrmToolbox_latest/McTools.StopAdvertisement.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
BDK.XrmToolBox.UserAuditViewer
    Assembly Version: 1.2017.5.1
    Win32 Version: 1.2017.5.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/BDK.XRMTOOLBOX.USERAUDITVIEWER.DLL
----------------------------------------
Carfup.XTBPlugins.DeltaAssemblyCRM
    Assembly Version: 1.2017.6.4
    Win32 Version: 1.2017.6.4
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CARFUP.XTBPLUGINS.DELTAASSEMBLYCRM.DLL
----------------------------------------
Carfup.XTBPlugins.DeltaStepsBetweenEnvironments
    Assembly Version: 1.2017.6.1
    Win32 Version: 1.2017.6.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CARFUP.XTBPLUGINS.DELTASTEPSBETWEENENVIRONMENTS.DLL
----------------------------------------
Cinteros.Xrm.Plugins
    Assembly Version: 1.2017.2.46
    Win32 Version: 1.2017.2.46
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.PLUGINS.DLL
----------------------------------------
Colso.Xrm.AttributeEditor
    Assembly Version: 1.2016.8.1
    Win32 Version: 1.2016.8.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/COLSO.XRM.ATTRIBUTEEDITOR.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2016.10.3
    Win32 Version: 1.2016.10.3
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2017.1.2
    Win32 Version: 1.2017.1.2
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
DLaB.AttributeManager
    Assembly Version: 1.2017.8.8
    Win32 Version: 1.2017.8.8
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DLAB.ATTRIBUTEMANAGER.DLL
----------------------------------------
DocumentFormat.OpenXml
    Assembly Version: 2.5.5631.0
    Win32 Version: 2.5.5631.0
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DOCUMENTFORMAT.OPENXML.DLL
----------------------------------------
EPPlus
    Assembly Version: 4.0.5.0
    Win32 Version: 4.0.5.0
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/EPPLUS.DLL
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly Version: 1.2017.1.2
    Win32 Version: 1.2017.1.2
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2017.1.6
    Win32 Version: 1.2017.1.6
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
JourneyIntoCRM.XrmToolbox.ERDPlugin
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JOURNEYINTOCRM.XRMTOOLBOX.ERDPLUGIN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2016.5.1
    Win32 Version: 1.2016.5.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2016.5.1
    Win32 Version: 1.2016.5.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly Version: 1.2017.5.5
    Win32 Version: 1.2017.5.5
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2016.9.1
    Win32 Version: 1.2016.9.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly Version: 1.2016.8.2
    Win32 Version: 1.2016.8.2
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2017.5.3
    Win32 Version: 1.2017.5.3
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2017.5.5
    Win32 Version: 1.2017.5.5
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2017.1.3
    Win32 Version: 1.2017.1.3
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
    Assembly Version: 1.2017.5.1
    Win32 Version: 1.2017.5.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MscrmTools.PortalRecordsMover
    Assembly Version: 1.2017.7.3
    Win32 Version: 1.2017.7.3
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2017.1.3
    Win32 Version: 1.2017.1.3
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2017.4.10
    Win32 Version: 1.2017.4.10
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2016.6.3
    Win32 Version: 1.2016.6.3
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2017.4.5
    Win32 Version: 1.2017.4.5
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2017.4.2
    Win32 Version: 1.2017.4.2
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2017.4.4
    Win32 Version: 1.2017.4.4
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MsCrmTools.WebResourcesManager
    Assembly Version: 1.2017.3.9
    Win32 Version: 1.2017.3.9
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
MsCrmTools.WorkflowExplorer
    Assembly Version: 1.2016.0.3
    Win32 Version: 1.2016.0.3
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WORKFLOWEXPLORER.DLL
----------------------------------------
RazDynamics.DuplicatesReportForBulkMerge
    Assembly Version: 1.2016.7.17
    Win32 Version: 1.2016.7.17
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RAZDYNAMICS.DUPLICATESREPORTFORBULKMERGE.DLL
----------------------------------------
Ryr.ExcelExport
    Assembly Version: 2.4.0.0
    Win32 Version: 2.4.0
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RYR.EXCELEXPORT.DLL
----------------------------------------
Ryr.SolutionHistory
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RYR.SOLUTIONHISTORY.DLL
----------------------------------------
UserTeamSecurityRoleReporter
    Assembly Version: 1.2017.7.10
    Win32 Version: 1.2017.07.10
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/USERTEAMSECURITYROLEREPORTER.DLL
----------------------------------------
Xrm.Sdk.PluginRegistration
    Assembly Version: 3.2017.8.1
    Win32 Version: 3.2017.08.001
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRM.SDK.PLUGINREGISTRATION.DLL
----------------------------------------
XrmToolBox Advanced Entity 360 View
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/USERS/MH2/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRMTOOLBOX%20ENTITY%20360%20VIEW.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by rappen** [comment]
Hi
There is a version inconsistency of dependencies between plugins.
Delete files matching:
``C:\Users\<your username>\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\Cinteros*.*``
Then restart XTB, and reinstall plugins you might be missing from the Plugins Store.

**Comment by mattman07** [comment]
Thank you very much rappen.  It worked a treat!

**Comment by rappen** [comment]
Well, it's "my fault", so I better help solving it... ;-)
