### ISSUE TITLE
I am facing the issue in opening the XRMTool. Attached the Screenshot of the error

### ISSUE THREAD

**Issue by Raghuhari** [MscrmTools/XrmToolBox#666]
I am facing the issue in opening the XRMTool. Attached the Screenshot of the error

[XRM error.xlsx](https://github.com/MscrmTools/XrmToolBox/files/1267222/XRM.error.xlsx)

**Comment by daryllabar** [comment]
Did you unblock the zip file before extracting it?

**Comment by Raghuhari** [comment]
Yes I unblocked it..

**Comment by MscrmTools** [comment]
Do you have framework 4.5.2 and Windows Identity Foundation installed ?

**Comment by rappen** [comment]
Perhaps try to remove a possibly corrupt configuration file? @MscrmTools could probably tell you the name of it...

**Comment by MscrmTools** [comment]
oups... Thought it was a new installation...
You should look in c:\users\your_login\appData\Roaming\MscrmTools\XrmToolBox\Connections and check for 0 bytes file
If you find some, delete them and try to run again

**Comment by Raghuhari** [comment]
Hi 
1. I have Framework 4.7 and WIF installed
2. I Removed Mscrmtools folder completely and tried running again but I am getting same error.
Thanks,
Raghu

**Comment by Raghuhari** [comment]
![wif](https://user-images.githubusercontent.com/31511540/29932745-1d39a15c-8e43-11e7-8394-04eb2cf1a4b0.PNG)
![net framework](https://user-images.githubusercontent.com/31511540/29932744-1d36f484-8e43-11e7-99d4-1cae05cd3e91.PNG)

**Comment by Raghuhari** [comment]
![wif](https://user-images.githubusercontent.com/31511540/29932781-405477de-8e43-11e7-8822-45359d509f7f.PNG)

**Comment by MscrmTools** [comment]
Do you still have issues ?

**Comment by MscrmTools** [comment]
Closing for now
