### ISSUE TITLE
Unexpected error regarding Cinteros.Xrm.XmlEditorUtils, Version=1.2016.4.106, Culture=neutral, PublicKeyToken=null

### ISSUE THREAD

**Issue by Debster25** [MscrmTools/XrmToolBox#667]
I cannot connect to the XRM Toolbox, when trying to open the program, i get an error message with the following log file. Please advise what to do?
(hope the log still make sense... considering it is in Dutch)
Zie het einde van dit bericht voor meer informatie over het aanroepen 
van JIT-foutopsporing (Just In Time) in plaats van dit dialoogvenster.

************** Tekst van uitzondering **************
System.IO.FileNotFoundException: 
Kan bestand of assembly Cinteros.Xrm.XmlEditorUtils, Version=1.2016.4.106, Culture=neutral, PublicKeyToken=null of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.
Bestandsnaam: Cinteros.Xrm.XmlEditorUtils, Version=1.2016.4.106, Culture=neutral, PublicKeyToken=null
   bij XrmToolBox.PluginManagerExtended.Initialize()
   bij XrmToolBox.MainForm.<MainForm_Load>d__35.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

WRSCH: registratie van assembly-bindingen is uitgeschakeld.
Als u assembly-bindingsfouten wilt registreren, stelt u de registerwaarde [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) in op 1.
Opmerking: er is een prestatiestraf gekoppeld aan de registratie van assembly-bindingsfouten.
Als u deze functie wilt uitschakelen, verwijdert u de registerwaarde [HKLM\Software\Microsoft\Fusion!EnableLog].

************** Geladen assembly's **************
mscorlib
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly-versie: 1.2017.7.18
    Win32-versie: 1.2017.7.18
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2103.2 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly-versie: 1.2017.7.10
    Win32-versie: 1.2017.7.10
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2104.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly-versie: 3.5.0.0
    Win32-versie: 10.0.15063.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2046.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly-versie: 1.2017.6.6
    Win32-versie: 1.2017.6.6
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
    Assembly-versie: 2.12.0.817
    Win32-versie: 2.12.0.817
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/NuGet.Core.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly-versie: 1.2017.5.14
    Win32-versie: 1.2017.5.14
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly-versie: 1.2017.4.13
    Win32-versie: 1.2017.4.13
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly-versie: 8.0.0.0
    Win32-versie: 8.2.0.713
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly-versie: 8.0.0.0
    Win32-versie: 8.2.0.749
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly-versie: 8.0.0.0
    Win32-versie: 8.2.0.749
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly-versie: 2.2.0.0
    Win32-versie: 2.2.2.808
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly-versie: 2.24.0.0
    Win32-versie: 2.24.30411.1323
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms
    Assembly-versie: 2.24.0.0
    Win32-versie: 2.24.30411.1323
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.DLL
----------------------------------------
System.Configuration
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly-versie: 1.0.0.0
    Win32-versie: 1.0.0.0
    CodeBase: file:///C:/Users/Debbie%20Rhebok/Downloads/XrmToolbox/McTools.StopAdvertisement.DLL
----------------------------------------
System.Xml.Linq
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2046.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
AndyPopkin.BulkWorkflowExecution
    Assembly-versie: 1.2017.7.21
    Win32-versie: 1.2017.7.21
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/ANDYPOPKIN.BULKWORKFLOWEXECUTION.DLL
----------------------------------------
Cinteros.Xrm.Plugins
    Assembly-versie: 1.2017.2.46
    Win32-versie: 1.2017.2.46
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.PLUGINS.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly-versie: 1.2016.10.3
    Win32-versie: 1.2016.10.3
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly-versie: 1.2017.1.2
    Win32-versie: 1.2017.1.2
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
EPPlus
    Assembly-versie: 4.0.5.0
    Win32-versie: 4.0.5.0
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/EPPLUS.DLL
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly-versie: 1.2017.1.2
    Win32-versie: 1.2017.1.2
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly-versie: 1.2017.1.6
    Win32-versie: 1.2017.1.6
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly-versie: 2.1.0.0
    Win32-versie: 2.1.0.556
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MICROSOFT.XRM.TOOLING.CONNECTOR.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly-versie: 1.2016.5.1
    Win32-versie: 1.2016.5.1
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly-versie: 1.2016.5.1
    Win32-versie: 1.2016.5.1
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly-versie: 1.2016.11.1
    Win32-versie: 1.2016.11.1
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly-versie: 1.2017.5.5
    Win32-versie: 1.2017.5.5
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly-versie: 1.2016.9.1
    Win32-versie: 1.2016.9.1
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly-versie: 1.2017.3.1
    Win32-versie: 1.2017.3.1
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MscrmTools.DashboardTransferTool
    Assembly-versie: 1.2016.6.1
    Win32-versie: 1.2016.6.1
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DASHBOARDTRANSFERTOOL.DLL
----------------------------------------
MscrmTools.DataUsageInspector
    Assembly-versie: 1.2016.9.20
    Win32-versie: 1.2016.9.20
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DATAUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly-versie: 1.2016.8.2
    Win32-versie: 1.2016.8.2
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly-versie: 1.2016.8.23
    Win32-versie: 1.2016.8.23
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly-versie: 1.2016.12.1
    Win32-versie: 1.2016.12.1
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly-versie: 1.2017.5.3
    Win32-versie: 1.2017.5.3
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly-versie: 1.2017.5.5
    Win32-versie: 1.2017.5.5
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly-versie: 1.2016.11.1
    Win32-versie: 1.2016.11.1
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly-versie: 1.2017.1.3
    Win32-versie: 1.2017.1.3
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly-versie: 1.2016.8.23
    Win32-versie: 1.2016.8.23
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
    Assembly-versie: 1.2017.6.4
    Win32-versie: 1.2017.6.4
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MscrmTools.PortalRecordsMover
    Assembly-versie: 1.2017.7.3
    Win32-versie: 1.2017.7.3
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly-versie: 1.2016.8.23
    Win32-versie: 1.2016.8.23
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly-versie: 1.2017.1.3
    Win32-versie: 1.2017.1.3
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly-versie: 1.2016.11.1
    Win32-versie: 1.2016.11.1
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly-versie: 1.2017.4.10
    Win32-versie: 1.2017.4.10
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly-versie: 1.2016.6.3
    Win32-versie: 1.2016.6.3
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly-versie: 1.2016.8.23
    Win32-versie: 1.2016.8.23
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly-versie: 1.2017.3.1
    Win32-versie: 1.2017.3.1
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly-versie: 1.2016.8.23
    Win32-versie: 1.2016.8.23
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly-versie: 1.2017.4.5
    Win32-versie: 1.2017.4.5
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly-versie: 1.2017.7.5
    Win32-versie: 1.2017.7.5
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly-versie: 1.2017.4.4
    Win32-versie: 1.2017.4.4
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MsCrmTools.WebResourcesManager
    Assembly-versie: 1.2017.3.9
    Win32-versie: 1.2017.3.9
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
Ryr.ExcelExport
    Assembly-versie: 2.4.0.0
    Win32-versie: 2.4.0
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RYR.EXCELEXPORT.DLL
----------------------------------------
UoW.MsCrm.DataExporter
    Assembly-versie: 1.0.0.1458
    Win32-versie: 1.0.0.1458
    CodeBase: file:///C:/USERS/DEBBIE%20RHEBOK/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/UOW.MSCRM.DATAEXPORTER.DLL
----------------------------------------
mscorlib.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT-foutopsporing **************
Als u JIT-foutopsporing wilt inschakelen, moet in het configuratiebestand voor deze
toepassing of computer (machine.config) de waarde
jitDebugging in het gedeelte system.windows.forms zijn ingesteld.
De toepassing moet ook zijn gecompileerd terwijl foutopsporing
was ingeschakeld.

Bijvoorbeeld:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wanneer JIT-foutopsporing is ingeschakeld, worden onverwerkte uitzonderingen
naar het JIT-foutopsporingsprogramma gestuurd dat op de computer is geregistreerd
en worden niet door dit dialoogvenster verwerkt.

**Comment by rappen** [comment]
There seems to be some version mismatch.
Could you try removing all files matching:
``c:\Users\<your_user_name>\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\Cinteros.*.dll``

And then restart XrmToolBox and download the plugins you lost from the Plugins Store?

**Comment by Debster25** [comment]
Thanks Jonas, you’re a star! ☺
We’re connected again.

I do have another question. I often get error messages when connecting to a saved organization/instance, then when trying again, I usually succeed in connecting, but I was wondering if it is safe to delete the ConnectionsList.Default.xml
From the c:\Users\<your_user_name>\AppData\Roaming\MscrmTools\XrmToolBox\Connections folder?
And if this would solve the issue

Below is an example of an error message

[cid:image001.png@01D32659.85ACB730]

Thanks much,
Debbie

Van: Jonas Rapp [mailto:notifications@github.com]
Verzonden: dinsdag 5 september 2017 15:00
Aan: MscrmTools/XrmToolBox <XrmToolBox@noreply.github.com>
CC: Debbie Rhebok <Debbie.Rhebok@pixelzebra.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [MscrmTools/XrmToolBox] Unexpected error regarding Cinteros.Xrm.XmlEditorUtils, Version=1.2016.4.106, Culture=neutral, PublicKeyToken=null (#667)


There seems to be some version mismatch.
Could you try removing all files matching:
c:\Users\<your_user_name>\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\Cinteros.*.dll

And then restart XrmToolBox and download the plugins you lost from the Plugins Store?

**Comment by rappen** [comment]
Pinging @MscrmTools for the last question.
And thanks :) Glad it helped!

**Comment by MscrmTools** [comment]
Yes you can delete it if you have at least one another connection file. If you don't the Default file will be recreated
