### ISSUE TITLE
RibbonWorkBench Ver 3.1.86.1 issue

### ISSUE THREAD

**Issue by LanCru** [MscrmTools/XrmToolBox#668]
Using RWB and getting the following error.
![xrmtoolbox_rw_error](https://user-images.githubusercontent.com/32072837/30554598-ecae747a-9c59-11e7-9193-91008b5a3b65.PNG)

I tried bypassing the problem by adding ClientUI.js to my solution, but it still fails with the same error.

Lannie Crudup
lannie.crudup@healthcurrent.org

**Comment by MscrmTools** [comment]
It's not one of my plugin... you should check with Scott Durow at develop1.net
