### ISSUE TITLE
Issue registering plugin on xrmtoolbox

### ISSUE THREAD

**Issue by panayiotisp** [MscrmTools/XrmToolBox#670]
I created a new plugin and tried to registered on your website, but I am receiving an error at the nuget id (panayiotis_p)

error message: "An unknown failure has occurred. Error ID # [c6100da9-b4f6-43e5-8ec1-cdd665e08264]"

**Comment by MscrmTools** [comment]
You must provide your Nuget package id, not your nuget user id

**Comment by panayiotisp** [comment]
Thanks, just did
