### ISSUE TITLE
Experiencing issue when starting XrmToolBox

### ISSUE THREAD

**Issue by mygls** [MscrmTools/XrmToolBox#671]
Hello,
when I try to open the latest release of XrmToolBox, it crashes throwing the following error:

![error](https://user-images.githubusercontent.com/32269460/30812708-ce085d58-a20b-11e7-8f71-1f6ea54960ea.png)

I have unlocked .rar before unzipping it and I don't know what happens.
Can anyone help me??
Thanks in advance.

**Comment by MscrmTools** [comment]
This is possible that a plugin is making this error

Can you help translating the spanish error message?

**Comment by mygls** [comment]
Could not load type 'XrmToolBox.Attributes.BackgroundColorAttribute' from assembly 'XrmToolBox, Version=1.2017.7.18, Culture=neutral, PublicKeyToken=null'.

Is it enough or do you need something else?

**Comment by MscrmTools** [comment]
Latest version should show you faulting plugins
