### ISSUE TITLE
Connection Issue with Production Site

### ISSUE THREAD

**Issue by kimj01** [MscrmTools/XrmToolBox#674]
I am not able to connect XRMToolBox to our CRM production site.  I am however able to connect to our sandbox environment.   I have tried to mirror the setup for sandbox and other various alternatives at the different connection steps without luck. Thanks

**Comment by MscrmTools** [comment]
Which tenant? Which version?
________________________________
De : kimj01 <notifications@github.com>
Envoyé : lundi 2 octobre 2017 19:03
À : MscrmTools/XrmToolBox
Cc : Subscribed
Objet : [MscrmTools/XrmToolBox] Connection Issue with Production Site (#674)


I am not able to connect XRMToolBox to our CRM production site. I am however able to connect to our sandbox environment. I have tried to mirror the setup for sandbox and other various alternatives at the different connection steps without luck. Thanks

**Comment by kimj01** [comment]
Microsoft Dynamics CRM 2016 On Premise - 8.1.0.359
Trying to use the XRMToolBox v1.2017.7.18

**Comment by MscrmTools** [comment]
So I don't understand what refers to a sandbox environment...  anyway, if these two environments are made of dedicated CRM deployments, then I guess the problem is on the server side, not on XrmToolBox. to validate this theory, please use the LoginTester from SDK to check if you can connect to both organizations

**Comment by kimj01** [comment]
Sandbox is a copy of production to test changes before they are imported.  That is why it is strange that we are able to connect to the lower environment and not production.  It is an exact copy.

I am not familiar with the Login Tester, are there steps on how to do this?

**Comment by MscrmTools** [comment]
It's a tool in the SDK, just run it and try to connect to your organization

**Comment by kimj01** [comment]
I am  not familiar with running tools in SDK.  Where can I find more information on doing that?

**Comment by MscrmTools** [comment]
Download the SDK, extract it, go to "bin" folder, double click on "LoginControlTester.exe", play
