### ISSUE TITLE
Constructor of all plugins called on FormClosing

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#675]
This line causes all plugins constructor to be invoked:
https://github.com/MscrmTools/XrmToolBox/blob/master/XrmToolBox/MainForm.cs#L746-L750

**Comment by rajyraman** [comment]
I wrote those lines to save session state before closing. I have to figure out another way.

**Comment by daryllabar** [comment]
So what is causing the constructors to be invoked?  The PluginManager's Plugins Enumerator?

**Comment by rappen** [comment]
It performs ``GetControl()`` on all objects in ``pManager.Plugins``, which typically calls the plugin's constructor.

**Comment by rappen** [comment]
Related to #672 and #676

**Comment by rajyraman** [comment]
Now getting the active plugin before close from the tab.

**Comment by rappen** [comment]
Thanks @rajyraman ! Now closing XTB is instantaneous, instead of a couple of seconds :)

**Comment by rajyraman** [comment]
@rappen : Introduced the bug and the created the fix for it. 😐
