### ISSUE TITLE
Plugins in Store not installing latest version

### ISSUE THREAD

**Issue by bwmodular** [MscrmTools/XrmToolBox#678]
There are a number of plugins which appear in the store as having new versions available. Selecting them and pressing Install makes no difference.
Not a big problem, but not sure why this is happening and it makes it difficult to make work out when there are new updates available.
Screenshot - ignore the Auto Number Manager at the top as this is not installing because it's not compatible:
![pluginsnotupdating](https://user-images.githubusercontent.com/1889586/31709607-69de68e0-b3ea-11e7-83d8-cc19b2812c2d.png)

**Comment by MscrmTools** [comment]
Their Nuget package are wrong, in the way that the package contains a file with a different number form the package itself

**Comment by bwmodular** [comment]
OK, so this is only something that the plugin owners can fix. I'll close the issue. Thanks.
