### ISSUE TITLE
Add search box for filtering plugins installed

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#68]
Guys, number of already available plugins is quite large already. I believe plugin search box should be added to be able quickly filter plugin and find exactly one you currently need.

**Comment by MscrmTools** [comment]
I agree. I just have concerns about the time it takes to redraw the list of plugins

**Comment by MscrmTools** [comment]
Feature is almost done! Just a question : Should I search with "Starts with" or "Contains" operator ? Against "Title" or "Company" or both?

**Comment by rappen** [comment]
My vote goes to "most accepting", i.e. `contains` and Title `or` Company.
And filtering "as you type".

**Comment by MscrmTools** [comment]
This is what I've done so far but wanted just a confirmation

**Comment by rappen** [comment]
:+1:

**Comment by MscrmTools** [comment]
![filterplugins](https://cloud.githubusercontent.com/assets/10774317/6733823/cd5810f2-ce54-11e4-94d0-6b68bf765e11.png)

**Comment by rappen** [comment]
Awesomeness.

**Comment by MscrmTools** [comment]
Is "Filter plugin" label is good enough? I'm not sure about it...

**Comment by rappen** [comment]
Or just "Search:"

**Comment by MscrmTools** [comment]
"Search" looks just nice in XrmToolBox :+1:
