### ISSUE TITLE
Unable to Update XRM Toolbox from 1.2017.7.18 to 1.2017.10.19

### ISSUE THREAD

**Issue by dmgerber** [MscrmTools/XrmToolBox#683]
Attached are the images of the errors that I get when trying to update.

![xrm toolbox upload error](https://user-images.githubusercontent.com/32842326/31962854-bf1787e2-b8cc-11e7-970f-d15ed7300526.jpg)

**Comment by MscrmTools** [comment]
Hi, the update did occur but the Auto Updater does not find the XrmToolBox.exe. Try to run XrmToolBox again and you should be good

Version 1.2017.10.19 embeds an update of this component that should fix this error

**Comment by dmgerber** [comment]
I got the below message when I tried to install the Ribbon Workbench 2016 plug in?

[cid:image001.png@01D34CE4.A7D27B40]

**Comment by MscrmTools** [comment]
The image is not added correctly when sent by email. Can you add it again ?

**Comment by dmgerber** [comment]
Here you go.

**Comment by MscrmTools** [comment]
No, still not, please use Github website to add your image

**Comment by dmgerber** [comment]
Additional message when opening the Plug In

**Comment by dmgerber** [comment]
The Plugins Store does seem to be loading correctly now.

**Comment by MscrmTools** [comment]
ok, did not understand anything but I guess we can close this issue
