### ISSUE TITLE
App Crash when trying to open Project Link/Load attributes for Duplicate Detection

### ISSUE THREAD

**Issue by macwi** [MscrmTools/XrmToolBox#684]
Hi,

we're trying to use the Duplicate Detection for Bulk Merge plugin.

We are connected to CRM Org, were able to load the entities, but when trying to load attributes, XrmToolBox crashes and we receive:

_System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei CRMConsultants.DuplicateDetectionReport.DuplicateDetectionReportTool.<cmbEntities_SelectedIndexChanged>b__18_2(RunWorkerCompletedEventArgs evt)
   bei XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   bei System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)_

We guess that this error is thrown by the Toolbox, because when trying to open Project Website from the context menu on main page, we get the same error.

Windows 10, CRM 2011 (UR18)

Best regards
Michael

**Comment by MscrmTools** [comment]
This plugin is not one of mine, please contact the developer of this plugin to raise this issue
