### ISSUE TITLE
Ribbon Workbench 2016 - Not able to publish an Account Ribbon

### ISSUE THREAD

**Issue by dmgerber** [MscrmTools/XrmToolBox#685]
![xrm toolbox ribbon workbench error](https://user-images.githubusercontent.com/32842326/32006080-ce7a8caa-b973-11e7-853c-190677cd1827.png)
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

When I attempt to unhide the Delete and Deactivate buttons I get the attached error trying to publish the solution,

**Comment by MscrmTools** [comment]
Are you sure the error is about publishing an account plugin? the error message seems not related...

**Comment by MscrmTools** [comment]
Ok, so the screenshot you provided seems not related to your problem.

As you should have read it, this repository is not made to fix issues with other plugins. Please contact the author of RibbonWorkBench for any issue related to this plugin
