### ISSUE TITLE
Store window size

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#69]
Related to #68 it would be great if the main window size was stored in config file.
The first thing I do, everytime I open XTB, is to enlarge the window to easier find what I am looking for.

**Comment by MscrmTools** [comment]
That can be done.
Should I put an option to allow user to store or not this setting?

**Comment by rappen** [comment]
I dont' think that is necessary. Just include a check that size is not bigger than screen (common scenario after unplugging external monitor) etc.
If position is also stored, make sure the top/left is not outside the screen as well.

**Comment by MscrmTools** [comment]
Ok, I can check to see if the window is maximized too
