### ISSUE TITLE
Web Resources Manager 'Replace with new file' not working

### ISSUE THREAD

**Issue by lykebank** [MscrmTools/XrmToolBox#693]
In latest version of this tool, the 'Replace with new file' function does not actually bring in the contents of the selected file.

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.WebResourcesManager #35](https://github.com/MscrmTools/MsCrmTools.WebResourcesManager/issues/35) via [**ZenHub**](https://www.zenhub.com/)
