### ISSUE TITLE
Manually copying over an extension when dialog is open

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#694]
XrmToolBox becomes unresponsive when I manually copy a dll to the plugins folder, when a dialog is open in XrmToolBox.

### Repro

1. Open Tools -> Settings
2. Choose Paths tab and click on "Open XrmToolBox storage folder"
3. Copy over a plugin dll to the Plugins folder
4. Navigate back to XrmToolBox. XrmToolBox is unresponsive.

**Comment by rappen** [comment]
I think this could be a case of modal prompt behind main form...

**Comment by MscrmTools** [comment]
Yes, when adding a file in plugins folder, a dialogue asks for reloading plugins list

**Comment by MscrmTools** [comment]
I will refresh the plugins list automatically so that this problem does not happen anymore
