### ISSUE TITLE
Plugin Store - Plugin not compatible with latest XrmToolBox error message

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#695]
Why is this error displayed?

![image](https://user-images.githubusercontent.com/5035266/32358778-e13e50c6-c09c-11e7-9306-4174578776f4.png)

I am using the latest version
![image](https://user-images.githubusercontent.com/5035266/32358788-f9079b9a-c09c-11e7-8cfe-b65a0e51834b.png)

Could it be because the plugin has not been approved yet?

**Comment by MscrmTools** [comment]
Your nuget package must define what minimum version of XrmToolBox it is dependent from.

Currently, the dependency is set to version 1.0.0.0 which does not exist and/or is less than the current version.

**Comment by rajyraman** [comment]
Updated a new package with _XrmToolBox_ as dependency. I had _XrmToolBoxPackage_ as dependency earlier.
