### ISSUE TITLE
Make connections duplicatable and editable, and add import/export to/from file

### ISSUE THREAD

**Issue by astrohart** [MscrmTools/XrmToolBox#696]
In the Connection Manager, there really should be the following features:

- Edit an existing connection's properties and be able to run a test
- Delete an existing connection
- Duplicate an existing connection into a new connection (in case I want to make a slight tweak but otherwise leave the settings the same)
- Rename an existing connection
- Filter the connection list (by putting a text box control in the upper right corner, then whatever you type is a filter for everything in the list)

Import/Export connections to/from a file.

I see there is a drop down on the toolbar that has Create new connection file/Add existing connection file but perhaps those are not obvious places to put those commands.  Perhaps if there could be buttons or menus added to that form to provide access to those in a more intuitive way.

![image](https://user-images.githubusercontent.com/8261875/32670846-afc5b9f8-c60a-11e7-8bc8-67d56711d2b3.png)

**Comment by MscrmTools** [comment]
Only one of the feature mentioned is not yet implemented... you can edit properties, rename, duplicate, etc.

Instead of just telling what is wrong, please propose better implementation
