### ISSUE TITLE
Not really sure what "OK" and "Cancel" buttons mean on the Switch Connection window

### ISSUE THREAD

**Issue by astrohart** [MscrmTools/XrmToolBox#697]
See the image below:

![image](https://user-images.githubusercontent.com/8261875/32670892-d91bed7c-c60a-11e7-8a98-1ab11762f711.png)

The OK and Cancel buttons could be more clearly and intuitively named, as I am not sure what they mean on a form like this.

I am assuming that the OK button connects to the selected connection and the Cancel button dimisses the form without connecting.  Perhaps:

![image](https://user-images.githubusercontent.com/8261875/32670954-25bac4be-c60b-11e7-8e7a-f62e39c6aa18.png)

This is slightly better UX.

**Comment by MscrmTools** [comment]
As you assumed correctly, I'm pretty sure everyone does too... this is really minor "issue" but I could eventually change this

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #51](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/51) via [**ZenHub**](https://www.zenhub.com/)
