### ISSUE TITLE
OK button does nothing when there is no connection selected in the list

### ISSUE THREAD

**Issue by astrohart** [MscrmTools/XrmToolBox#698]
The proper UX for the Select A Connection form would really be to grey out the "OK" or "Connect" button if nothing is selected in the list box.  Right now, if I click to remove any sort of highlighting whatsoever from the Connections list box, so that none of the items is selected, or if I delete all the connections, then the OK button still is clickable and just plain does not do anything.

Typically, in applications written for the Microsoft Windows desktop, each button, if clickable, should always perform a definite action from the user's perspective.  If a button is clickable and then does not do anything, that is not good UX.  

The recommended UX is to grey out any buttons that don't apply, when certain criteria are met.

**Comment by MscrmTools** [comment]
Again, really minor issue... I will "fix" it

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #50](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/50) via [**ZenHub**](https://www.zenhub.com/)
