### ISSUE TITLE
Logon fails for connecting to Dynamics 365 Online

### ISSUE THREAD

**Issue by danmyhre** [MscrmTools/XrmToolBox#699]
Logon fails for connecting to Dynamics 365 Online. Does this tool support modern authentication?

**Comment by MscrmTools** [comment]
Please explicit "modern authentication"...

**Comment by danmyhre** [comment]
Specifically, this is the method we are using:
https://docs.microsoft.com/en-us/azure/active-directory/connect/active-directory-aadconnect-pass-through-authentication

Basically though, when logging into CRMOL, the user should be presented with the Azure AD login web page so that it support whatever AuthN process the tenant is using (AAD Pass-Through, ADFS, AAD).  As an example, get the latest AzureRM PowerShell module, then type "Login-AzureRMAccount".  This then gives you a modern authentication prompt (forms based, support MFA and conditional access enforced for AAD, etc).

**Comment by MscrmTools** [comment]
So, the answer is basically: yes it is supported but you have to use a connection string (there is a link to do so in the first page of the connection wizard).

I need to work on enabling this modern authentication mechanism so that it is more user friendly that connection strings

**Comment by danmyhre** [comment]
Can you provide an example of exactly what we should be using in the connection string in this tool so that it prompts for modern auth?  I tried the various option from the MSDN article with no success.  Thanks much!!

**Comment by MscrmTools** [comment]
I guess this one should do the trick:
`<add name="MyCRMServer" connectionString="AuthType=OAuth;Username=jsmith@contoso.onmicrosoft.com; Password=passcode;Url=https://contoso:8080/Test;AppId=<GUID>;RedirectUri=app://<GUID>;TokenCacheStorePath =c:\MyTokenCache;LoginPrompt=Auto"/>`

from [MSDN](https://msdn.microsoft.com/en-us/library/mt608573.aspx?f=255&MSPPError=-2147217396#Examples)

**Comment by danmyhre** [comment]
When I do that one, it produces an error that the organization cannot be null.  
Also, which GUIDs would you use...the Dynamics CRM online app ID from Azure ID?
Lastly, not sure username or password should be in there as the login form would need to handle that

**Comment by MscrmTools** [comment]
yes, login/password are not mandatory, 

Url should be CRM Online url
AppId should be the id of an app you created in your Azure AD tenant with access privilege to Dynamics CRM Online
RedirectUri can be whatever you mentioned in the same app. 
TokenCacheStorePath should be a file path and not a folder path based on my experience

**Comment by danmyhre** [comment]
That still produces the organization name cannot be null error.  I am also curious why it needs an app_id to authenticate if you are authenticating as an Azure AD user principal.

**Comment by MscrmTools** [comment]
I cannot speak for Microsoft here but that is the way they enabled connecting using Oauth

**Comment by MscrmTools** [comment]
Please see https://www.xrmtoolbox.com/documentation/for-users/connecting-to-an-organization/ for help on connecting to MFA enabled organization
