### ISSUE TITLE
An unexpected error occurred while Plugin Development

### ISSUE THREAD

**Issue by piyushpaliwal** [MscrmTools/XrmToolBox#701]
Hi, I was just trying to create my first plugin looking at the documentation provided in the Wiki. However, upon execution or while debugging, I'm greeted with the following error.

`An unexpected error occured: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Composition.CompositionContractMismatchException: Cannot cast the underlying exported value of type 'PP.SolutionManager.Plugin.GetControl (ContractName="XrmToolBox.Extensibility.Interfaces.IXrmToolBoxPlugin")' to type 'XrmToolBox.Extensibility.Interfaces.IXrmToolBoxPlugin'.
`

I know this has to be a very small mistake probably but unfortunately am not able to get past this as of now. Any insights would be highly appreciated.

**Comment by MscrmTools** [comment]
The easiest would be to use the XrmToolBox plugin template. The wiki doc is quite old.

There is pre release doc available here: https://www.xrmtoolbox.com/documentation

Please try from there. You shouldn't have any problem

**Comment by MscrmTools** [comment]
@piyushpaliwal any news?

**Comment by piyushpaliwal** [comment]
@MscrmTools hey sorry I forgot to mention that yes the new documentation helps a lot and am currently into the development of a new plugin.
Thanks for the help
