### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by mbaumannOMPI** [MscrmTools/XrmToolBox#702]
I have tried uninstalling and reinstalling the toolbox but still continue to get this error any time I try to do anything.  Details and screenshot attached
[unhandledexception.txt](https://github.com/MscrmTools/XrmToolBox/files/1522031/unhandledexception.txt)
![capture](https://user-images.githubusercontent.com/33267136/33489585-ee507fc6-d679-11e7-9a62-88688b5dfb80.JPG)

**Comment by MscrmTools** [comment]
Already answered with the fix included in #665
