### ISSUE TITLE
An unhandled exception occurred while opening XRMToolbox

### ISSUE THREAD

**Issue by jeetjg** [MscrmTools/XrmToolBox#704]
![xrmtoolboxerror](https://user-images.githubusercontent.com/34532901/33978183-70bda6d8-e0c4-11e7-938c-fcc0020e9eb5.png)
[XrmToolboxErrorDetails.txt](https://github.com/MscrmTools/XrmToolBox/files/1558112/XrmToolboxErrorDetails.txt)

I am experiencing an unhandled exception error while opening the XrmToolbox from the extracted XRMToolbox zip file. I have the ".Net framework 4.6.2" installed on my machine.

**Comment by MscrmTools** [comment]
What is your version of XrmToolBox?

**Comment by jeetjg** [comment]
XrmToolBox v1.2017.10.19

**Comment by MscrmTools** [comment]
It might come from an old plugin... can you try to update them all from plugins store?

**Comment by jeetjg** [comment]
Please know, I am unable to open XrmToolbox so how would I be able to update the plugins from the plugins store?

I validated the error and it seems like it is coming from the file "XrmToolBox.Extensibility.dll"
![xrmerror](https://user-images.githubusercontent.com/34532901/33996258-aeff2f2e-e106-11e7-9801-f21afffb29d5.png)

**Comment by MscrmTools** [comment]
Ok, so clear your plugins folder (at least those that are not mine)

**Comment by rvroemen** [comment]
I have the same issue, and noticed 2 things:
1. the Plugin.zip subfolder is not extracted automatically
2. when you extract this subfolder and start the XRMToolBox application, the Plugin subfolder is deleted and an error is thrown...

**Comment by MscrmTools** [comment]
No. I guess you don't understand where plugins are actually stored.

There are now located in C:\users\your_profile\AppData\Roaming\MscrmTools\XrmToolBox\Plugins. Try to clear all plugins not issued by MscrmTools, Javista or DamSim (those are mine actually). 

Then restart XrmToolBox, you shouldn't get this error anymore

**Comment by rvroemen** [comment]
Yes, that is the solution! Thank you!

**Comment by gtebo** [comment]
Hi, rvroemen,
Im having this issue and I tried to delete all plugins not issued by MscrmTools, Javista or DamSim. But when I am launching xrmtoolbox, I still have the same error. Can you describe your steps?
