### ISSUE TITLE
CRM 365 V9 Javascript Validator

### ISSUE THREAD

**Issue by Miesjh** [MscrmTools/XrmToolBox#705]
Hi, 
I've created a tool that can Validate Dynamics 365 Javascripts and mark the line that need to be changed for V9. It also gives a suggestion. Maybe it can be available as a plugin?

Kind Regards, 

Michel

**Comment by MscrmTools** [comment]
Sure. You can create a plugin for that.

Follow these pages : https://www.xrmtoolbox.com/documentation

**Comment by Miesjh** [comment]
Cool. I will refactor the code to create the plugin. You will here from me soon.

**Comment by MscrmTools** [comment]
I'm closing the thread as it is not really an issue but do not hesitate to add other comments here

**Comment by Miesjh** [comment]
OK no problem. I'm busy creating the plugin.
