### ISSUE TITLE
Could not load type MultipleConnectionsPluginControlBase

### ISSUE THREAD

**Issue by pmanmath** [MscrmTools/XrmToolBox#706]
I have downloaded latest tool and trying to run it but getting below error. Can you please help here to fix this?

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.TypeLoadException: Could not load type 'XrmToolBox.Extensibility.MultipleConnectionsPluginControlBase' from assembly 'XrmToolBox.Extensibility, Version=1.2017.7.10, Culture=neutral, PublicKeyToken=null'.
   at XrmToolBox.PluginManagerExtended.Initialize()
   at XrmToolBox.MainForm.<MainForm_Load>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2017.10.19
    Win32 Version: 1.2017.10.19
    CodeBase: file:///C:/Users/mapand/Documents/Delete/XrmToolbox_Latest/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2017.7.10
    Win32 Version: 1.2017.7.10
    CodeBase: file:///C:/Users/mapand/Documents/Delete/XrmToolbox_Latest/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 10.0.16299.15
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly Version: 1.2017.10.7
    Win32 Version: 1.2017.10.7
    CodeBase: file:///C:/Users/mapand/Documents/Delete/XrmToolbox_Latest/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
    Assembly Version: 2.12.0.817
    Win32 Version: 2.12.0.817
    CodeBase: file:///C:/Users/mapand/Documents/Delete/XrmToolbox_Latest/NuGet.Core.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2017.10.15
    Win32 Version: 1.2017.10.15
    CodeBase: file:///C:/Users/mapand/Documents/Delete/XrmToolbox_Latest/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2017.10.15
    Win32 Version: 1.2017.10.15
    CodeBase: file:///C:/Users/mapand/Documents/Delete/XrmToolbox_Latest/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.9002.0

**Comment by MscrmTools** [comment]
Can you try to update nugget packages with latest version (all except active directory ones)?

**Comment by pmanmath** [comment]
I've updated the package. Still getting same error.

**Comment by MscrmTools** [comment]
What are you doing? Running XrmToolBox ? Trying to develop a new plugin? Can’t understand the context

**Comment by MscrmTools** [comment]
No answer. Closing the issue. Please reopen if it still occurs
