### ISSUE TITLE
Provide support for keyboard shortcuts

### ISSUE THREAD

**Issue by jaimalleshk** [MscrmTools/XrmToolBox#708]
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

**Comment by rappen** [comment]
XrmToolBox exposes interface ``IShortcutReceiver`` that is up to each plugin developer to implement.
This enables keyboard shotcuts that are not "hijacked" by other plugins.
If you would like shortcuts in specific plugins, please create an issue in apropriate plugin repository.
