### ISSUE TITLE
Search by Author does not work in new Plugins Store

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#713]
Searching by author in new Plugins Store does not return expected results.

New:
![image](https://user-images.githubusercontent.com/2572253/35195215-8ccccde4-fec0-11e7-89ab-4e2ac23cccf8.png)

Legacy:
![image](https://user-images.githubusercontent.com/2572253/35195226-c9a034b8-fec0-11e7-8ebe-9a1a75bf706d.png)

**Comment by santoshCRM** [comment]
I am also facing same kind of issue. My plugin not showing even after using legacy.

**Comment by MscrmTools** [comment]
What is your plugin?

**Comment by matthewjmurphy** [comment]
Unsubscribe

Sent from my iPhone

On Mar 12, 2018, at 7:27 AM, MscrmTools <notifications@github.com<mailto:notifications@github.com>> wrote:


What is your plugin?

**Comment by santoshCRM** [comment]
I have checked again. If I enable Use legacy option and reopen Xrmtoolbox plugin store, My plugin showing. Can you share what could be the issue and how can we resolved this.
Below are my plugins.
Personal view
Role Replicator
Soap Logger.

**Comment by MscrmTools** [comment]
The new plugins store only shows plugins registered on XrmToolBox portal.
I sent emails to all developers with plugins not yet registered. It seems you did not see it

**Comment by matthewjmurphy** [comment]
PLEASE UNSUBSCRIBE ME

Sent from my iPhone

On Mar 12, 2018, at 7:58 AM, MscrmTools <notifications@github.com<mailto:notifications@github.com>> wrote:


The new plugins store only shows plugins registered on XrmToolBox portal.
I sent emails to all developers with plugins not yet registered. It seems you did not see it

**Comment by MscrmTools** [comment]
@matthewjmurphy, I cannot do that, this is your responsability to unsubscribe.
And writing in capital letters really does not help

**Comment by MscrmTools** [comment]
Solved now
