### ISSUE TITLE
Could not load type 'Xrm.ToolBox.Extensibility.Interfaces.IShortcutReceiver' from assembly 'XrmToolBox.Extensibility. Version=1.2017.2.7.Culure=neutral.PublicKey Token=null'.

### ISSUE THREAD

**Issue by Gras8** [MscrmTools/XrmToolBox#714]
I don't really know how to fix this.
This appen after i tried to add the plug-in program

**Comment by rappen** [comment]
It sounds like you have plugins requiring a newer version of XrmToolBox.
What version of XTB do you use?
Note that it is always recommended to use the latest version, which currently is 1.2018.1.20.

**Comment by Gras8** [comment]
Oh i have 1.2017.3.14, maybe this is the problem. But know i'm not more enabled to open the program, so i think that i have to delete all and download the latest version, am i right?

**Comment by rappen** [comment]
Yes, best is to download, unblock, unpack XTB into a new folder and try again.
If problem still persists, delete/rename folder:
``c:\Users\<username>\AppData\Roaming\MscrmTools\XrmToolBox``
And then restart XTB.
