### ISSUE TITLE
XrmToolBox Plugin List

### ISSUE THREAD

**Issue by DigitalFlow** [MscrmTools/XrmToolBox#715]
Hey everyone,

I was wondering, whether there is a mechanism for requesting a revalidation of a plugin on the XrmToolBox homepage.
Specifically I added my [CloneFields tool](https://www.xrmtoolbox.com/plugins/MsDyn.Contrib.CloneFieldDefinitions/) and submitted it for validation, which was rejected due to icon sizes.
I fixed the issue almost two weeks ago, but the plugin is still rejected.

What can I do for requesting a revalidation?

Kind Regards and thanks for your help,
Florian

**Comment by MscrmTools** [comment]
You just did!

Sorry, I did not see the changes.

I need to implement a mechanism to be notified in a better way

**Comment by DigitalFlow** [comment]
Thanks for approving :)
