### ISSUE TITLE
Column is no longer a valid column?

### ISSUE THREAD

**Issue by soziblewuup** [MscrmTools/XrmToolBox#717]
Hi, 

First off, thanks for the tool (View Layout Replicator), very useful! 

Secondly, I'm experiencing an issue replicating a queue item view. The fields selected from the related email(object) entity all display in the view customization area with an orange exclamation mark with the error message:

The a_[id].from column is no longer a valid column because it has been deleted as a column option. You need to remove this column and, if you want, add a different one.

All other columns selected from the Queue Item native entity are displaying as expected. 

When actually navigating to the view in the system, from a user perspective, the view displays with all the columns. It's only in the customization area where an error is found.

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.ViewLayoutReplicator #4](https://github.com/MscrmTools/MsCrmTools.ViewLayoutReplicator/issues/4) via [**ZenHub**](https://www.zenhub.com/)
