### ISSUE TITLE
"Unable to Login ..." in every crm after Plugins Updates

### ISSUE THREAD

**Issue by bryce2071** [MscrmTools/XrmToolBox#721]
Hi, 
i did a Plugin Update. After that i wasnt able to Login to any of my 5 crm-systems ... "Unable to Login to Dynamics CRM".
An solution for this?

Thx, PeB

**Comment by MscrmTools** [comment]
It seems a plugin version is corrupting the whole thing.
Please review the connection logs, it should talk about conflict between early bound types.

**Comment by bryce2071** [comment]
Hi, thx for reply.
I found it. It was the (new added) Audit History Extractor. 
I uninstalled it, then it works :-)

This was the error:
Error	: A proxy type with the name audit has been defined by another assembly. Current type: DLaB.Xrm.Entities.Audit, DLaB.Xrm.Entities, Version=8.1.0.1, Culture=neutral, PublicKeyToken=null, Existing type: AuditHistoryExtractor.AppCode.Audit, AuditHistoryExtractor, Version=1.0.1.9, Culture=neutral, PublicKeyToken=null
Parametername: audit

Thx, PeB

**Comment by MscrmTools** [comment]
ok, thank you for the information, I will send the information to the author

**Comment by bryce2071** [comment]
Ive done this, opened an issue at his github proj.site.

--
Gruss Peter
________________________________

**Comment by MscrmTools** [comment]
Just saw it. Added a comment too to explain what to do to fix it
