### ISSUE TITLE
Ability to duplicate a tab/tool

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#722]
It would be nice to quickly duplicate a tab using a shortcut key or right-click on the tab itself and select duplicate. The reason for this request is because I frequently open the same tool on two different tabs with two different connections e.g. compare web resources, running fetch etc.

Here is how I imagine the flow:

1. User has a tool already open
2. The user hits shortcut Ctrl+Shift+D and the connection window pops up
3. The chooses the connection he/she needs by pressing ⬆️ or ⬇️ and then "Enter".
4. The new tab/tool opens with the specified connection

**Comment by rappen** [comment]
I vote 👍

**Comment by MscrmTools** [comment]
Ok, give me some times, guys, I'm in the process of implementing DockPanel like @rappen did. I need to replumb everything... 

![image](https://user-images.githubusercontent.com/10774317/35722540-04d80986-07f7-11e8-8465-ae66133b4b53.png)

**Comment by rajyraman** [comment]
@MscrmTools Looks great 🤗

**Comment by MscrmTools** [comment]
Two years after, this is coming... :D

**Comment by rappen** [comment]
I just wish this would somehow call the tool's "Save your stuff now" before duplicating, it would solve this issue... 😊 https://github.com/rappen/FetchXMLBuilder/issues/234
