### ISSUE TITLE
How to use MultipleConnectionsPluginControlBase

### ISSUE THREAD

**Issue by ZooY** [MscrmTools/XrmToolBox#726]
The article https://www.xrmtoolbox.com/documentation/for-developers/multipleconnectionsplugincontrolbase-base-class/ is not correct - AdditionalConnectionDetails property has no access to IOrganizationService as show in "Access additional organization services" section.
AdditionalConnectionDetails has no Keys property.

**Comment by MscrmTools** [comment]
Fixed!
