### ISSUE TITLE
MetadataDocumentGenerator - it's not in the plugin store 

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#727]
Where's the Metadata Document Generator plugin? - it's not showing up in a list of available plugins.

**Comment by MscrmTools** [comment]
Hi Scott,
So far it is only included in XrmToolBox package. So, if you miss the plugin, you can download XrmToolBox package and extract plugins.zip content to get the expected plugin.

**Comment by mscottsewell** [comment]
Yes - I was able to extract it from the download - 
However this was a brand new installation as of 4 weeks ago, so I'm unsure why I wouldn't have them installed already. - I found that there were 5 total plugins that were in the zip, but not in the folder.
Close this for now, but it's possibly affecting other users.
