### ISSUE TITLE
CRM 4.0

### ISSUE THREAD

**Issue by afabozzi** [MscrmTools/XrmToolBox#728]
Forgive me if this is the wrong place to ask this.  I searched high and low for CRM 4.0 bulk export tool and all I can get are source code files from codeplex which I don't know what to do with them.  I am basically trying to export all my data to csv and them import it in to SuiteCRM.  Do you offer any plugins or tools that will do the job for 4.0?  2011 and up is all I saw in the read me.  any search on the tool takes me to https://archive.codeplex.com/?p=mscrmbulkdataexport or https://archive.codeplex.com/?p=mscrmbulkupdatetool.  Thanks for your time and any help on the matter.

**Comment by MscrmTools** [comment]
As mentioned, XrmToolBox only works for CRM 2011 and above.
I don’t know anything about the tool you mentioned for CRM 4.
You could try to upgrade to CRM 2011 then use the tools inside XrmToolBox

**Comment by rixpoint** [comment]
Hey @afabozzi sorry this is over 2 years long but might be helpful for anyone else who stumbles across it as I had the same problem and found a few unhelpful posts before working it out myself :)

Once you download the source files:

- go to the releases\0 folder

- rename 0e5d2184-ad68-4cbf-848f-ed59bfdd64ca to 0e5d2184-ad68-4cbf-848f-ed59bfdd64ca.zip (just add .zip to the filename)

- Unzip and then simply run the application directly from the folder :)

Enjoy (helped me migrate the data easily to a SharePoint application I've built!)

**Comment by afabozzi** [comment]
That is helpful still thanks for posting!  I will try it out as I think soon we may be migrating to something.
