### ISSUE TITLE
Manage NN Relationships - Contact:MarketingList relationship not consistently showing

### ISSUE THREAD

**Issue by kmpiotrowski** [MscrmTools/XrmToolBox#730]
When trying to remove members from a marketing list, getting inconsistent results in looking up the relationship between Contact and Marketing List (List Members)
![contacttomarketinglist](https://user-images.githubusercontent.com/32843573/37408013-9a6aecd6-2771-11e8-8c5c-90ce8e030813.png)
![contacttomarketinglist_qa](https://user-images.githubusercontent.com/32843573/37408015-9a8e1bd4-2771-11e8-8e72-8bf359f76d63.png)

Sometimes it will show me the marketing list option and sometimes it wont.

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/Javista.XrmToolBox.ManageNN #7](https://github.com/MscrmTools/Javista.XrmToolBox.ManageNN/issues/7) via [**ZenHub**](https://www.zenhub.com/)
