### ISSUE TITLE
XrmToolBox AutoUpdater 

### ISSUE THREAD

**Issue by rduz** [MscrmTools/XrmToolBox#732]
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

**Comment by rduz** [comment]
Every time I try to update, I receive the message "The request was aborted.  Could not create SSL/TLS secure channel."

**Comment by rduz** [comment]
XrmToolBox for Microsoft Dynamics CRM / 365 CE (v1.2017.10.19)

**Comment by rduz** [comment]
![image](https://user-images.githubusercontent.com/956908/37434153-a029b996-27ac-11e8-8d4c-9a9d7a864a8c.png)

**Comment by rduz** [comment]
![image](https://user-images.githubusercontent.com/956908/37434170-b052b6ba-27ac-11e8-842e-fcaa856e4a8f.png)

**Comment by MscrmTools** [comment]
It seems your network does not allow to connect to Github to download update package
