### ISSUE TITLE
Error trying to follow 'Create your own plugin' tutorial on Add Nuget package

### ISSUE THREAD

**Issue by glosrob** [MscrmTools/XrmToolBox#733]
I have a weird memory I have logged this before. I can't see it in the list, but if it does exist already just close this one.

Trying to follow the tutorial and on adding the Nuget packages I get the following:

> Could not install package 'MscrmTools.Xrm.Connection 1.2017.10.15'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.'

Same error for project targeting 4.6, 4.5.2.
Same error for previous XrmToolBoxPackage version 1.2017.11.20

[Tutorial is here](https://github.com/MscrmTools/XrmToolBox/wiki/Develop-your-own-custom-plugin-for-XrmToolBox#Develop-your-plugin-for-XrmToolBox-v1201576-and-above)

I am using an updated version VS 2017 community.

**Comment by MscrmTools** [comment]
Can you try with this documentation instead?

**Comment by glosrob** [comment]
> Can you try with this documentation instead?

Do you mean the wiki on here? If so, that is what I meant (sorry).

**Comment by MscrmTools** [comment]
Forgot to put the link : https://www.xrmtoolbox.com/documentation/for-developers/ 

sorry about that

**Comment by glosrob** [comment]
Looks like same error to me.

![image](https://user-images.githubusercontent.com/2010333/37531213-66e61732-2933-11e8-80a0-8b3d64c9ac59.png)

**Comment by MscrmTools** [comment]
Did you try to put the project with target framework 4.6.2?

**Comment by glosrob** [comment]
Ha I rebuilt my machine and have only just noticed I don't have 4.6.2 installed (and so the template targets the next nearest I guess). 

Retrying shortly..

**Comment by glosrob** [comment]
Installed 4.6.2 (updated Visual Studio) and got the same error:

![image](https://user-images.githubusercontent.com/2010333/37706623-1e445bb0-2cf8-11e8-9a62-0942dc5de864.png)

The project created was targetting 4.6.1 again (I don't know if this is purposeful). 

However, I was then able to manually get it working by:
- switching project to target 4.6.2
- manually updating all Nuget packages via `nuget restore MySolution.sln`

So I'm set now.

**Comment by MscrmTools** [comment]
Glad to know it’s good for you
