### ISSUE TITLE
Version Issue with Plugin ViewTransfer Tool

### ISSUE THREAD

**Issue by nexrm** [MscrmTools/XrmToolBox#734]
We have submitted this issue directly to the Plugin Git as well but wondered since it seemed to occur after recent update if should be submitted here as well.

When launching the tool we get 

Error occurred when trying to display this plug-in: Unable to cast object type
'DamSim.ViewTransferTool.ViewTransferTool' to type 'XrmToolBox.Extensibility.PluginControlBase'.

This issue recently occurred.
XrmToolBox Version 1.2018.3.21
ViewTranferTool Version: 1.2016.10.3

This issue appears to be on the Solution TransferTool as well.

Thank you and please advise.

**Comment by MscrmTools** [comment]
Fixed for both plugins

**Comment by nexrm** [comment]
Thanks!  Works!
