### ISSUE TITLE
Plugin Store - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by dodgster02** [MscrmTools/XrmToolBox#735]
Using the latest version of the XRM Toolbox (1.2018.3.21) and attempting to update the existing plugins I have already previously installed I encounter the attached image
![error](https://user-images.githubusercontent.com/26326026/37765043-23c97d90-2dbb-11e8-9b0a-d5acce76b6bf.jpg)

I have also wiped my local XRMToolbox folder in my roaming profile and attempted to run a clean version of the Toolbox and still encounter other errors with the plugin store like the below
![broke](https://user-images.githubusercontent.com/26326026/37765196-7f3cb0c0-2dbb-11e8-85ba-642dc9cc57b7.jpg)

Rolling back to V.1.2018.1.20 seems to also have the same problem above
Rolling back to v1.2017.10.19 throws a HTTP 500 error when I try to retrieve the plugins from the nuget feed

**Comment by MscrmTools** [comment]
Fixed!
It was due to a new registered plugin and an issue with Nuget platform it seems

**Comment by khorozhansky** [comment]
I've just met the same issues on 2 different computers.

**Comment by MscrmTools** [comment]
Nuget.org is currently down, which explains the problem

**Comment by khorozhansky** [comment]
Works now after the fix, thanks!
