### ISSUE TITLE
Xrmtoolbox template issue visual studio

### ISSUE THREAD

**Issue by foufione** [MscrmTools/XrmToolBox#736]
I have an issue after downloading the xrmtoolbox template from visual studio. I tried to open a new project using this template but i got this error 

> couldnt add all the required packages to the project. the following package failed to install  from 'C:\...' :  Mscrmtools.xrm.connection.1.2017.10.15 : could not install package :'Mscrmtools.xrm.connection.1.2017.10.15' You are trying to install this package into a project that targets '.NetFramework, version=v4.6' but the package does not contain any assembly references or content files that are compatible with that framework...'

**Comment by MscrmTools** [comment]
And you must target your projet to framework 4.6.2

**Comment by foufione** [comment]
I used the version deployed yesterday on this link [https://marketplace.visualstudio.com/items?itemName=TanguyTMVPCRM.XrmToolBoxPluginProjectTemplate-19499#review-details](url) 
for the framework i have only two options 4.6 or 4.6.1

**Comment by foufione** [comment]
I tried to install the 4.6.2 but it's not allowed since the 4.7 is already installed

**Comment by MscrmTools** [comment]
CRM sdk works on 4.6.2 (for latest version) so does XrmToolBox.
It seems to be an issue with your environment then

**Comment by foufione** [comment]
Thank you for ur help, i will try to install the v4.6.2 and let u know for the updates for this issue

**Comment by MscrmTools** [comment]
Any news?

**Comment by ryanperrymba** [comment]
Hi Tanguy & Team,  I am still getting a similar error.  Visual studio is standard 2017.  Have tried downloading template via VS, and directly from XRMToolBox site.  Targeting 4.6.2 on new project creation.  Screen Capture of error attached.
![capture-xrminstallerror](https://user-images.githubusercontent.com/38732630/46189950-9550d200-c2ae-11e8-9208-0a840efd10b3.PNG)

**Comment by foufione** [comment]
> Any news?

yes, Now I can create a project with xrmtoolbox template, but I still getting @ryanperrymba 's error

**Comment by MscrmTools** [comment]
I have a new version available. Should fix this issue
