### ISSUE TITLE
Plugin store null reference

### ISSUE THREAD

**Issue by AntoineGauthier** [MscrmTools/XrmToolBox#738]
Hello,

I'm suddenly having an issue with the plugin store.
I'm not sure what I did but I ended up loosing all my defined connections and now each time I start the plugin store I get this error message:
![image](https://user-images.githubusercontent.com/10197231/37972237-2d2ea934-31d8-11e8-9663-5e1d9b961912.png)

If I have the option of starting the plugin store on the app start I get a much more complete message which says:

![image](https://user-images.githubusercontent.com/10197231/37972183-08fa1d32-31d8-11e8-9eb7-ba839f485071.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at XrmToolBox.PluginsStore.DTO.XtbPlugin.get_Files()
   at XrmToolBox.PluginsStore.StoreFromPortal.AnalyzePackage(XtbPlugin plugin)
   at XrmToolBox.PluginsStore.StoreFromPortal.LoadNugetPackages()
   at XrmToolBox.New.NewForm.<NewForm_Load>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2018.3.21
    Win32 Version: 1.2018.3.21
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2017.7.10
    Win32 Version: 1.2017.7.10
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 10.0.16299.15
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly Version: 1.2017.10.7
    Win32 Version: 1.2017.10.7
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
    Assembly Version: 2.12.0.817
    Win32 Version: 2.12.0.817
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/NuGet.Core.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2017.10.15
    Win32 Version: 1.2017.10.15
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2017.10.15
    Win32 Version: 1.2017.10.15
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.9002.0
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.9002.0
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.0.2090
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.882
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 2.29.0.1078
    Win32 Version: 2.29.40822.1520
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms
    Assembly Version: 2.29.0.1078
    Win32 Version: 2.29.40822.1520
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Dev/CRM_SDK/XrmToolBox/McTools.StopAdvertisement.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
BDK.XrmToolBox.StorageCleaner
    Assembly Version: 1.2017.11.1
    Win32 Version: 1.2017.11.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/BDK.XRMTOOLBOX.STORAGECLEANER.DLL
----------------------------------------
Cinteros.Xrm.CRMWinForm
    Assembly Version: 2017.11.15.2
    Win32 Version: 2017.11.15.002
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.CRMWINFORM.DLL
----------------------------------------
Cinteros.Xrm.FetchXmlBuilder
    Assembly Version: 1.2018.2.2
    Win32 Version: 1.2018.02.002
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.FETCHXMLBUILDER.DLL
----------------------------------------
Cinteros.Xrm.XmlEditorUtils
    Assembly Version: 1.2018.2.1
    Win32 Version: 1.2018.02.001
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.XMLEDITORUTILS.DLL
----------------------------------------
Cinteros.XTB.ViewDesigner
    Assembly Version: 1.2016.8.7
    Win32 Version: 1.2016.8.7
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XTB.VIEWDESIGNER.DLL
----------------------------------------
Colso.Xrm.AttributeEditor
    Assembly Version: 1.2018.3.1
    Win32 Version: 1.2018.3.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/COLSO.XRM.ATTRIBUTEEDITOR.DLL
----------------------------------------
Colso.Xrm.DataTransporter
    Assembly Version: 1.2018.3.3
    Win32 Version: 1.2018.3.3
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/COLSO.XRM.DATATRANSPORTER.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2018.3.5
    Win32 Version: 1.2018.3.5
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2018.3.3
    Win32 Version: 1.2018.3.3
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
Develop1.XrmTBPlugin.RibbonWorkbench2016
    Assembly Version: 3.1.177.1
    Win32 Version: 3.1.177.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DEVELOP1.XRMTBPLUGIN.RIBBONWORKBENCH2016.DLL
----------------------------------------
DLaB.AttributeManager
    Assembly Version: 1.2018.1.25
    Win32 Version: 1.2018.1.25
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DLAB.ATTRIBUTEMANAGER.DLL
----------------------------------------
DLaB.Common
    Assembly Version: 1.0.1.13
    Win32 Version: 1.0.1.13
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DLAB.COMMON.DLL
----------------------------------------
DLaB.EarlyBoundGenerator
    Assembly Version: 1.2018.3.6
    Win32 Version: 1.2018.3.6
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DLAB.EARLYBOUNDGENERATOR.DLL
----------------------------------------
DLaB.Xrm.2016
    Assembly Version: 1.1.8.7
    Win32 Version: 1.1.8.7
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DLAB.XRM.2016.DLL
----------------------------------------
DLaB.Xrm.Entities
    Assembly Version: 8.1.0.1
    Win32 Version: 8.1.0.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DLAB.XRM.ENTITIES.DLL
----------------------------------------
DLaB.XrmToolboxCommon
    Assembly Version: 1.2016.9.10
    Win32 Version: 1.2016.9.10
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DLAB.XRMTOOLBOXCOMMON.DLL
----------------------------------------
DocumentFormat.OpenXml
    Assembly Version: 2.5.5631.0
    Win32 Version: 2.5.5631.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DocumentFormat.OpenXml/v4.0_2.5.5631.0__31bf3856ad364e35/DocumentFormat.OpenXml.dll
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly Version: 1.2017.1.2
    Win32 Version: 1.2017.1.2
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2017.11.7
    Win32 Version: 1.2017.11.7
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2016.5.1
    Win32 Version: 1.2016.5.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2016.5.1
    Win32 Version: 1.2016.5.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly Version: 1.2017.11.6
    Win32 Version: 1.2017.11.6
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2016.9.1
    Win32 Version: 1.2016.9.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly Version: 1.2016.8.2
    Win32 Version: 1.2016.8.2
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2017.12.3
    Win32 Version: 1.2017.12.3
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2018.1.8
    Win32 Version: 1.2018.1.8
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2018.3.5
    Win32 Version: 1.2018.3.5
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
    Assembly Version: 1.2018.3.6
    Win32 Version: 1.2018.3.6
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MscrmTools.PortalRecordsMover
    Assembly Version: 1.2017.7.3
    Win32 Version: 1.2017.7.3
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2017.12.6
    Win32 Version: 1.2017.12.6
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2018.1.2
    Win32 Version: 1.2018.1.2
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2017.4.10
    Win32 Version: 1.2017.4.10
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2016.6.3
    Win32 Version: 1.2016.6.3
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2017.4.5
    Win32 Version: 1.2017.4.5
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2017.8.6
    Win32 Version: 1.2017.8.6
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2017.4.4
    Win32 Version: 1.2017.4.4
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MsCrmTools.WebResourcesManager
    Assembly Version: 1.2018.3.17
    Win32 Version: 1.2018.3.17
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
Ryr.SolutionHistory
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RYR.SOLUTIONHISTORY.DLL
----------------------------------------
SeAn.XrmToolbox.Plugins.CrmReportSync
    Assembly Version: 2016.8.3.6
    Win32 Version: 2016.8.3.6
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/SEAN.XRMTOOLBOX.PLUGINS.CRMREPORTSYNC.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.3.0
    Win32 Version: 3.0.3.0
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/WEIFENLUO.WINFORMSUI.DOCKING.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.3.0
    Win32 Version: 3.0.3.0
    CodeBase: file:///C:/USERS/ANTOI/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/WEIFENLUO.WINFORMSUI.DOCKING.THEMEVS2015.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
MetadataViewProxies_132034ed-f2b9-47e9-b1b5-8e6fa0c9e936
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Any help would be greatly appreciated.

I'm on the latest version of the XrmToolBox by the way.

**Comment by MscrmTools** [comment]
Not your fault.
It’s due to badly registered plugins in XTB portal.
It’s fixed now

**Comment by AntoineGauthier** [comment]
Indeed, all back to normal except all my connections that somehow disappeared but that's not an issue as I've already re typed them all :)

Thanks for the feedback,
Guess the issue can be closed 👍
