### ISSUE TITLE
Switching between tabs not working as expected

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/XrmToolBox#739]
Hi

can you make transferring between tabs have the same behavior even if re ordering happen 
fore example i have 'Main window - portal editor - From Library Manager', in the beginning the switching will work as expected (each move will take you to the next tab) but in case you re order them you will start jumping

**Comment by MscrmTools** [comment]
What is "transferrng between tabs" by the way. Not sure to understand what it means

**Comment by aboodh95** [comment]
Clicking ctrl-tab

**Comment by MscrmTools** [comment]
It was even not supposed to work at all with the latest version. Anyway, fix is on its way
