### ISSUE TITLE
Unable to Remove Un-necessary Columns in Relationships of the Entites

### ISSUE THREAD

**Issue by manas3487** [MscrmTools/XrmToolBox#742]
Hi I am unable to Hide Un-necessary Columns in RelationshipTabs of corresponding  Entities in  XRM Toolbox.
For Reference Please find the below screen shot
<img width="654" alt="capture" src="https://user-images.githubusercontent.com/35729553/38087269-1ba15dee-3375-11e8-93bd-400669de9873.PNG">

Please try to Resolve the Issue because I don't need all the columns in the relationship I want to filter out many of them. but the button you placed for this purpose seems not working properly.

Thanks and Regards,
Manas

**Comment by MscrmTools** [comment]
What the point of creating this issue a second time, in the wrong repository whereas the issue on the right repository has just be marked as resolved?
