### ISSUE TITLE
Titles in Metadata are loading Multipletimes if i click Load entities multiple times

### ISSUE THREAD

**Issue by manas3487** [MscrmTools/XrmToolBox#743]
Hi While I click load entities button multiple times I have found the following bug in the Metadata Browser.
Please find below screen shot for your reference.They are loading multiple times based on my Clicking on Load entites button.
![image](https://user-images.githubusercontent.com/35729553/38098337-7006d984-3395-11e8-846f-4f1054234144.png)

Thanks and Regards,
Manas

**Comment by MscrmTools** [comment]
Please open issues in the appropriate repository

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.MetadataBrowser #7](https://github.com/MscrmTools/MsCrmTools.MetadataBrowser/issues/7) via [**ZenHub**](https://www.zenhub.com/)
