### ISSUE TITLE
Error loading recent plugin from Start page

### ISSUE THREAD

**Issue by r-weisser** [MscrmTools/XrmToolBox#745]
When loading a recently used plugin from the new Start page, an error message appears
'Value cannot be null. Parameter name: s'

This happens when there is currently no connection to the organization of the recently used plugin AND the organization credentials are not stored.

**Comment by MscrmTools** [comment]
Yeah... just found it too... will try to fix it for next release

**Comment by MscrmTools** [comment]
Fixed in next release
