### ISSUE TITLE
Issue adding new plugin in xrmtoolbox protal

### ISSUE THREAD

**Issue by santoshCRM** [MscrmTools/XrmToolBox#746]
Hi, 
I am trying to add my new plugin in your xrmtoolbox Portal. but each time it showing error.
Error:- An unknown failure has occurred. Error ID # [f9a21857-b484-469e-978b-bc69f13f3605]
I have added my plugin in Nuget.org . Still I am not able to add my plugin
My plugin link as below
https://www.nuget.org/packages/EntitySecurityRole 

Hope you will respond soon

**Comment by MscrmTools** [comment]
Can't tell what was wrong... I added it myself. I will review it soon
