### ISSUE TITLE
[feature request] Connect to multiple organization

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/XrmToolBox#747]
@HasanAliKaraca commented on [Thu Apr 12 2018](https://github.com/MscrmTools/MsCrmTools.MetadataBrowser/issues/8)

Hi. I use metadata browser for multiple organizations. I use it like this:

1) Connect an organization.
2) Open the metadata plugin.
3) Connect another organization.
4) Open the metadata plugin in another tab(don't refresh other tabs)

So i had to connect between multiple organizations and i got 3 plugin tabs always open. İ change organization connection frequently. Connection times are wasting too much time.How can this plugin easily switched between organizations or extended to get the life easier for this scenario? I can work in this feature too.

---

@MscrmTools commented on [Thu Apr 12 2018](https://github.com/MscrmTools/MsCrmTools.MetadataBrowser/issues/8#issuecomment-380791126)

Ok, So I guess your feature request is more a request for XrmToolBox than for this plugin. It seems complicated to implement without lot of code rework. I will investigate to understand how this could be implemented.
I will close this issue and move it to XrmToolBox repository

**Comment by HasanAliKaraca** [comment]
If its possible this can be solved as multiple connection stayed connected(not disconnect on swap connection) and active connection can be changed from somewhere on ui.

**Comment by MscrmTools** [comment]
Lucky you! This feature arrives in next version

**Comment by HasanAliKaraca** [comment]
Cool stuff! Lets see when it arrives, thanks :)
