### ISSUE TITLE
Cannot run XrmToolBox downloaded from XrmToolBox.com website (version 1.2018.3.21)

### ISSUE THREAD

**Issue by nickbrandl** [MscrmTools/XrmToolBox#749]
Since last version, I'd been experiencing random errors when runing plug-ins, so I decided to delete XrmToolBox installation and try the latest version.
I have downloaded the xrmtoolbox.zip from the link provided in the webiste and after unlocking the .zip file and trying to run XrmToolBox.exe, I receive this error:

![image](https://user-images.githubusercontent.com/16178171/38941624-412a0878-432d-11e8-99fa-a94c20d885f7.png)

So, I've created a Connections directory inside current directory, and now I receive this error:
![image](https://user-images.githubusercontent.com/16178171/38942563-6ad84f20-432f-11e8-9de0-74737b173fce.png)

So it seems that there are missing files in the distributable zip file.

Here you have a screenshot of my install folder:
![image](https://user-images.githubusercontent.com/16178171/38942723-d69aacee-432f-11e8-9161-390ea3924b54.png)

Regards

**Comment by MscrmTools** [comment]
I don't know where you downloaded this package because if I do the same from www.xrmtoolbox.com, then I can see these files in the archive:
![image](https://user-images.githubusercontent.com/10774317/38943536-f29a9254-4331-11e8-8e0e-4351f560ffb8.png)

**Comment by nickbrandl** [comment]
I've cloned the repository and after building the solution and running from debug, the toolbox work as expected...Perhaps there is an old registry key that references an assembly no longer installed on my machine..yet the issue still arises in the executable from the downloaded zip.

**Comment by MscrmTools** [comment]
Ok, I see, the link is wrong on that page... Please try again from homepage. I'll fix the link on the release page
