### ISSUE TITLE
Calling other plugin does not focus other plugin

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#750]
When using the integration feature between plugins, the called plugin is not focused if it was already opened when calling it.
The message is passed along, but you can't "see it" as it is done in the background.

Simple example:
Use Bulk Data Updater to get the query from FXB, and when returning the query from FXB the BDU uses it and retrieves records, but it is not visible to the user.

**Comment by MscrmTools** [comment]
I will work on this.

Shouldn't be too complicated
