### ISSUE TITLE
Debug Plugin wiki page out of date

### ISSUE THREAD

**Issue by dodgster02** [MscrmTools/XrmToolBox#751]
I may be wrong, but does the information about debugging xrm toolbox plugins still apply for the most recent version of XRM Toolbox?

I've managed to follow most of the information on this page but unclear how certain areas currently work:

1. Debug Configurations -> how can I set an "overridepath" to point to the debug folder, and use a specific connection when the connections file currently sits in my own local %AppData% folder? I'm guessing this isn't possible without copying the connections file to the overridepath folder

2. The XrmToolBox.exe.config file doesn't exist in the XrmToolbox nuget package. Does this section still apply for debugging plugins?

**Comment by rappen** [comment]
Hi

1. You can easily add existing connection files from the connection manager, so you can reuse those you already have. Pro tip is to store your connection files in another location, I use my OneDrive folder to access them from wherever I happen to be.
2. I don't think this is necessary anymore.

btw, are you looking at teh wiki page here on GitHub or in the XrmToolBox website?
https://www.xrmtoolbox.com/documentation/for-developers/debug/

More info on connection files and storage: https://youtu.be/_nS5tnYM8lk

**Comment by MscrmTools** [comment]
I updated wiki to redirect to XrmToolBox website documentation
