### ISSUE TITLE
Creating New Connection to SB

### ISSUE THREAD

**Issue by CPow123** [MscrmTools/XrmToolBox#752]
I am still able to use my existing connections but am having an issue connecting to a new SB instance. Creating the connection seems to work fine and says test is successful, but I am getting the below error when trying to connect to the new connection.

![image](https://user-images.githubusercontent.com/38534781/39002105-cb532e4c-43c5-11e8-86b6-24aacc81f10c.png)

I was able to create another (DUP) connection my prod instance, and was able to successfully connect to that. Not sure if it's something in the new SB instance that is causing the error. 

Any help is greatly appreciated.

**Comment by MscrmTools** [comment]
It seems you did not save the password, did you?
Anyway, this shouldn't happen, unless you are using the Most Recently Used items in the start page. There is a known bug here

**Comment by CPow123** [comment]
I did check the box to "Save password as encrypted string in connections file". Also, I am using the connection manager on the bottom left, not a shortcut from Recently Used.

**Comment by MscrmTools** [comment]
What if you connect from the "Connect to CRM" button on the upper left ?

**Comment by CPow123** [comment]
Same error.

**Comment by MscrmTools** [comment]
Yes it is. I never faced this issue unless not having password saved...
Can you just check if your connection has a Guid in its XML definition ?

**Comment by CPow123** [comment]
Got in after deleting and re-entering connection, for 3rd or 4th time. Thanks for the assistance, much appreciated.
