### ISSUE TITLE
An error occured when trying to update some plugins.\n\nPlease start XrmToolBox again to fix this problem.

### ISSUE THREAD

**Issue by mtnmuncher** [MscrmTools/XrmToolBox#753]
"An error occured when trying to update some plugins.\n\nPlease start XrmToolBox again to fix this problem."

1. I was using XTB 3.21.2018.
2. I opened store to update FetchXmlBuilder
3. Received above error.
4. uninstalled ALL plug-ins.
4. Downloaded latest XTB 4.22.2018.
5. unzipped to new folder.
6. execute XrmToolBox.exe from new folder.
7. I still receive above error.

**Comment by MscrmTools** [comment]
This problem is generally due to a corrupt update.xml file in your XrmToolBox root folder. Can you search for it and delete it?
