### ISSUE TITLE
Connection issue - Socket operation encountered a dead network

### ISSUE THREAD

**Issue by andy-sam7** [MscrmTools/XrmToolBox#76]
I've just downloaded 1.2015.3.10 - When I try to set-up a new connection for an on-premise CRM, enter server name & port then click Get Orgs I get the following error:
An error occured while retrieving organizations: Metadata contains a reference that cannot be resolved: 'http://server:port/XmrServices/2011/Discovery.svc?wsdl'.
Inner Exception: Unable to connect to the remote server
Inner Exception: A socket operation encountered a dead network <ip>:port

The IP mentioned is the correct IP for the server referenced.  
I still have the previous version on my PC 1.2013.12.17 and that works fine.
I've unblocked all the files as far as I can tell - checked them 3 times!

I'm stumped - what am I missing? - please help!

Many thanks, Andy.

**Comment by MscrmTools** [comment]
I would need to check what are the differences between these two versions but as far as I know, there shouldn't be such problem with the new version.

One point is that setting a connection to a server reachable only by IP address shouldn't work since discovery service returns a host name to connect to the organization service

**Comment by MscrmTools** [comment]
Did you update your current Xrmtoolbox folder? If so, maybe you would like to give a try to create a new folder with only the updated version

**Comment by MscrmTools** [comment]
Moreover, can you confirm that server:port are correct for your deployment?

**Comment by andy-sam7** [comment]
It was in a new folder with the previous version untouched.  The server:port were correct - I was trying the same in both versions.  However, the strange thing is, after shutting down my PC and coming in to work this morning it has now decided to work fine.  Obviously, I should have tried the classic "switch of and back on again" solution first!  Apologies for the time waste.

**Comment by MscrmTools** [comment]
No problem, I'm happy this is working now!
