### ISSUE TITLE
[Feature request] Show number of ratings in plugin store

### ISSUE THREAD

**Issue by r-weisser** [MscrmTools/XrmToolBox#761]
Hi,
first of all great thing to have a plugin rating opportunity!

To get a better idea of how to interpret the ratings stars + number of ratings will tell more about a plugin
E.g. *** (20) vs ***** (1)

**Comment by rappen** [comment]
👍

**Comment by MscrmTools** [comment]
Does it look ok like this?

![image](https://user-images.githubusercontent.com/10774317/40373754-e63669e0-5de7-11e8-8ec2-8e433a89410a.png)
