### ISSUE TITLE
Favorites on Start Page

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#762]
I'd like to be able to pin my favorites to the start page.
![image](https://user-images.githubusercontent.com/2572253/39690264-c8995c54-51d9-11e8-96ef-ab7e1920e0bb.png)

Then I can access them easily here, since the Start Page is really where I always start. MRU list is good, but combined with Favorites it would be super good!

![image](https://user-images.githubusercontent.com/2572253/39690320-efee6a24-51d9-11e8-915d-151752e4e9af.png)

**Comment by MscrmTools** [comment]
Great idea!

**Comment by MscrmTools** [comment]
@rappen, where would you display Favorites when the screen is smaller and "Welcome" message goes up and Recent and Quick Actions use half of the available width?

**Comment by rappen** [comment]
That's probably the best option. I'm also thinking that the welcome text mayby should be so centered and focused. I have to admit I've never read it...

**Comment by rappen** [comment]
Très bien!
