### ISSUE TITLE
Can't connect to Dynamics by using proxy server

### ISSUE THREAD

**Issue by kabix** [MscrmTools/XrmToolBox#763]
We have discovered two problems with proxy.
 · If Username does not contain domain, IndexOutOfRangeException occurs.
 · Even though we fix the first problem, the registered proxy settings are not used. 

So, we propose the following modifications. 
XrmToolBox / AppCode / WebProxyHelper.cs 24 line.
 · If userNamePart.Length is 1, do not set the value to Domain. 

McTools.Xrm.Connection / ConnectionManager.cs 361 line
· If DefaultWebProxy is already set, do not set WebRequest.GetSystemWebProxy (). 

Because I could not build McTools due to private key, could you please verify?

**Comment by MscrmTools** [comment]
Can you tell me if the changes you asked are working as expected? I don't have the corresponding environment to test it
[Hotfix.zip](https://github.com/MscrmTools/XrmToolBox/files/2027354/Hotfix.zip)

**Comment by kabix** [comment]
@MscrmTools
This fix appears to behave as expected.
Thanks!!
