### ISSUE TITLE
connection truncates first 7 letter from domanin

### ISSUE THREAD

**Issue by AlexBanu4985** [MscrmTools/XrmToolBox#764]
XrmToolbox version v1.2018.4.22 (lattest) 

I've create a new connection using org url and I had an error. 
In the error log a saw that some how the first 7 letter from url truncated. 
I've trided again adding 7 more letter an the start of url and it worked.

**Comment by MscrmTools** [comment]
Can you provide the log file?

**Comment by AlexBanu4985** [comment]
It's ok. I'am dumbass. The fist seven letter that were truncated, guess what were the missing "http://". I've wrote connection url without them as in Plugin Registration Tool. My bad. Sorry.
