### ISSUE TITLE
Package does not contain a manifest message when opening XrmToolBox

### ISSUE THREAD

**Issue by abriden02** [MscrmTools/XrmToolBox#765]
Just upgraded from Dynamics CRM 2016 8.1.1 to Dynamics 365 8.2.2 On-premises.
Now when I open XrmToolBox, I get a message "Package does not contain a manifest".
Using XrmToolBox for Microsoft Dynamics CRM / 365 CE (v1.2017.7.18)
I cannot upgrade to a newer version of XrmToolBox due to need for a newer .NET framework not supported on my Windows 10 OS.
How can I get XrmToolBox working again?

**Comment by MscrmTools** [comment]
Is the error message from XrmToolBox itself or from the plugins store?

**Comment by abriden02** [comment]
Thanks, the message is from the Plugins Store.

**Comment by MscrmTools** [comment]
Ok so you can define options to not run plugins store during XrmToolBox start.
But of course, that will not help in the end since you won’t be able to download new and updated plugins.
It seems not so complicated to have framework 4.6.2 installed on your computer but it depends of course of your IT department

**Comment by abriden02** [comment]
When I tried to install .NET framework 4.6.2 I got a message that it was not supported on my OS.

**Comment by mparssey** [comment]
I have similar error with 2018.1.4.22.
I tried installing .NET 4.6.2, but got message that it was already installed, though Programs and Features shows 4.5.1 SDK (running Windows 10 Enterprise). Checked the registry and the Release value confirms that.

**Comment by MscrmTools** [comment]
I’m on windows 10 too and don’t have any issues (works too for all my colleagues)
Can’t tell how to fix it unfortunately

**Comment by LTaylorNZ** [comment]
Same error here as well, with version 1.2018.4.22 on Windows 10.

**Comment by MscrmTools** [comment]
Did you all try to install latest version of .net framework instead? 
https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-10#net-framework-462

**Comment by LTaylorNZ** [comment]
If I run the installer I get the message ".NET Framework 4.6.2 or a later update is already installed on this computer."

I can try the 4.7.2 installer.

**Comment by MscrmTools** [comment]
Please do and let me know the result

**Comment by mparssey** [comment]
When trying again I connect to an organisation (Onpremises 8.2.1.176) successfully,
Then open Plugins Store page, I can see the ticker for Retrieving plugins from Nuget feed..., and still get the "package does not contain a manifest"

When I first open XrmToolbox and it opens the Plugins Store automatically I get error "Unable to connect to the remote server", which is what I get each time until I've connected to an organisation.

I then changed Display options to deselect Use Legacy Plugins Stores. It then worked.

It is repeatable. I have to connect to an organisation to get passed "Unable to connect to the remote server", then with Use Legacy Plugins Stores deselected the store will load successfully.

**Comment by MscrmTools** [comment]
Ok, so it seems the problem is related to the Legacy Plugins Store.

The solution will then be to open XrmToolBox.Settings.xml file from XrmToolBox storage folder to put setting "PluginsStoreUseLegacy" to false.

You may have to do the same on file XrmToolBox.PluginsStore.xml (setting "UseLegacy")

**Comment by RCarlson32** [comment]
This worked for me!  Many thanks.

**Comment by abriden02** [comment]
Thanks.
I can't find PluginsStoreUseLegacy, though.
Lines found with "Plugins" below:

<PluginsStoreShowIncompatible xsi:nil="true" />
  <PluginsStoreShowUpdates xsi:nil="true" />
  <PluginsStoreShowNew xsi:nil="true" />
  <PluginsStoreShowInstalled xsi:nil="true" 
  <CloseEachPluginSilently>false</CloseEachPluginSilently>
  <CloseOpenedPluginsSilently>false</CloseOpenedPluginsSilently>
  <DisplayPluginsStoreOnStartup>true</DisplayPluginsStoreOnStartup>
  <DisplayPluginsStoreOnlyIfUpdates>false</DisplayPluginsStoreOnlyIfUpdates>

**Comment by RCarlson32** [comment]
![capture 2png](https://user-images.githubusercontent.com/39741534/40735170-8089d830-6408-11e8-8674-fc677a9af509.PNG)
![capture1](https://user-images.githubusercontent.com/39741534/40735171-809c7288-6408-11e8-866b-67a1070c32b4.PNG)

You can make the changes to false on the areas selected and it should work like it did for me.

**Comment by LTaylorNZ** [comment]
That worked for me too. Thanks for your help.

**Comment by MscrmTools** [comment]
I think it is time to remove Legacy Plugins Store...

**Comment by abriden02** [comment]
Thanks for sharing the screenshots!
That helped clarify for me.
- I have a XrmToolBox.Settings.xml file, however, the <PluginStoreUseLegacy> line does not exist in my file.
- I do not have a file named "XrmToolBox.PluginsStore.xml".

**Comment by MscrmTools** [comment]
So maybe you have an old version... what is yours?

**Comment by abriden02** [comment]
I have 1.2017.7.18.
When I go to Check for update, I get a message "No update available!"

**Comment by MscrmTools** [comment]
I must admit there was a bug in that version so that it does not find any update. But there is! 
Please download latest version from https://www.xrmtoolbox.com and you should be good
