### ISSUE TITLE
Cannot create connection

### ISSUE THREAD

**Issue by StephaneSeguin** [MscrmTools/XrmToolBox#766]
Since the last update i cannot connct to any organization. 
Getting error. 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2018-05-30 16:17:01  Source	: mscorlib
Method	: HandleReturnMessage
Date	: 2018-05-30
Time	: 16:17:01
Error	: Une faute non sécurisée ou incorrectement sécurisée a été reçue de l'autre partie. Voir le FaultException interne pour le code et les détails de la faute.
Stack Trace	: Server stack trace: 
   à System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.ProcessReply(Message reply, SecurityProtocolCorrelationState correlationState, TimeSpan timeout)
   à System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   à System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   à System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   à System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   à System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   à System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   à System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   à Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   à Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   à Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   à Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer)
   à Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   à Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: Not Provided
Method	: Not Provided
Date	: 2018-05-30
Time	: 16:17:01
Error	: An error occurred when verifying security for the message.
Stack Trace	: Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2018-05-30 16:17:01  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2018-05-30 16:17:01  ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2018-05-30 16:17:01  Source	: mscorlib
Method	: HandleReturnMessage
Date	: 2018-05-30
I even deleted the complete solution including in the Roaming files and redownload the latest version and still the same issue.

Thank you

**Comment by MscrmTools** [comment]
Did you try from another computer?

**Comment by StephaneSeguin** [comment]
No. This is my main and only Computer to work of CRM environnements.

**Comment by MscrmTools** [comment]
Ok, so I cannot really help you if this is related to your computer only, since no one else reported this error.

**Comment by StephaneSeguin** [comment]
Installed it on my kid PC and it works. What cold cause this security issue on my Comapany PC?

**Comment by MscrmTools** [comment]
No idea... there could be a bunch of reason...
