### ISSUE TITLE
XrmToolbox Close Logic

### ISSUE THREAD

**Issue by altmank** [MscrmTools/XrmToolBox#768]
I sometimes accidentally press the X to close the XRMToolbox, I then get prompts if I am sure I want to close tabs. Since I did not mean to close the program, I say No, I do not want to close the tabs. After saying no, the XrmToolbox closes anyway. It seems like perhaps rejecting the request to close the tabs should abort the program closing too.

**Comment by rappen** [comment]
I have seen similar, when prompting is disabled in XTB but FXB asks if you want to save changes. Hitting Cancel still shuts down XTB.
