### ISSUE TITLE
Power BI accelerator plugin 

### ISSUE THREAD

**Issue by Taust1** [MscrmTools/XrmToolBox#769]
I am using the Power BI accelerator to create queries using XML to decode alphanumeric IDs used in MS D365 for sales.  The issue I am facing is the XML code is setting values as "null" rather than decimal numbers.  When I query this same table without using the PBI accelerator the decimal values are displayed, but all the other columns are obviously alphanumeric.  

Has anyone had this issue before?  I am happy to share my code with anyone who might have a suggestion.

**Comment by MscrmTools** [comment]
Are we talking about Sonoma partners plugin?

**Comment by Taust1** [comment]
yes, however they have been acquired by  E&Y so i do not have a contact to reach out to.

**Comment by MscrmTools** [comment]
Ok, so I'm not sure you will find help here.
I will try to find someone from ex-Sonoma Partners to know if we can get the source code for this plugin

**Comment by Taust1** [comment]
Thank you, any information would be much appreciated

**Comment by Taust1** [comment]
Any luck with the source code?
