### ISSUE TITLE
Mark environment with colour

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#770]
It would be nice to have a colour associated with a connection/environment. For e.g. I would like to choose red, when I am working with production org, as a visual cue. This colour should run across the connection status bar on the bottom. I would set this up when I setup the connection.

**Comment by r-weisser** [comment]
In addition coloring the plugin-tab-selector with the active connection would also be nice.
Having an additional colored indicator (beside name of connection) helps to differentiate between plugins of different connections. Specially for long plugin names like 'User, Team and Security Role Reports'

**Comment by MscrmTools** [comment]
@rajyraman  @r-weisser  What about this kind of display?

Color and text could be defined during creating a connection

![image](https://user-images.githubusercontent.com/10774317/41956869-6ab955ec-79e5-11e8-9919-60dc4d275b0a.png)

**Comment by rajyraman** [comment]
This is great Tanguy 👍

**Comment by MscrmTools** [comment]
Lucky you! This feature arrives in next version
