### ISSUE TITLE
Contiue to have error issues when clicking new upgrade button

### ISSUE THREAD

**Issue by WhiteyC** [MscrmTools/XrmToolBox#772]
![image](https://user-images.githubusercontent.com/23065270/41519182-e16f0480-7309-11e8-8926-5f90fdc8dc60.png)

There seems to be a permission consideration here. Standard Windows 10 installation.

**Comment by medevil84** [comment]
@WhiteyC you can fix the issue by temporary rename the "XrmToolBox" to "XrmToolBox2" (or something else). I've fixed the bug so this should not happen on future releases.

**Comment by WhiteyC** [comment]
Thanks. I also found signing into the application as administrator worked also but that still is only a workaround. Glad to help :)
