### ISSUE TITLE
Registering new tool fails

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#773]
This error is shown when trying to register a new tool.
Retries gives the same message, but with different guids.
NuGet package exists and is validated and listed.

![image](https://user-images.githubusercontent.com/2572253/41520838-e9a0bb88-72cf-11e8-9298-bca6c706bc05.png)

**Comment by MscrmTools** [comment]
It worked from CRM org. Can't tell what went wrong
