### ISSUE TITLE
How to manage lots of connections

### ISSUE THREAD

**Issue by r-weisser** [MscrmTools/XrmToolBox#775]
I'm currently dealing with multiple different systems and connections(> 20)
What would be the best way to handle all of them?

1. Group them by Name, similar systems starting with same name
2. Introduce some kind of connection folder to group multiple connections together by insert or select existing <groupname>  while connection creation?

Any suggestions here?

**Comment by MscrmTools** [comment]
The solution is already available with "Connections Files". See [documentation](https://www.xrmtoolbox.com/documentation/for-users/manage-connections/)

**Comment by r-weisser** [comment]
Thank you for the link.
This behaviour is exactly how it should be.

After struggling a bit with the menubar of the connection window which unnecessarily hides items on selection I want to suggest some improvements:

- Hide/Deactivate 'Move selected...' Menü when no row is selected
- Shrink connection-file dropdown length and hide MRU description to gain space to show all 4 connection file related controls

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.Xrm.Connection #53](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/53) via [**ZenHub**](https://www.zenhub.com/)
