### ISSUE TITLE
XrmToolbox issue in creating ER diagram

### ISSUE THREAD

**Issue by jmadele** [MscrmTools/XrmToolBox#777]
Hi All
I was using XrmToolbox to generate ER diagrams from Dynamics 365 on-premises 2016 and came across this problem:
![0317 error png-640x480](https://user-images.githubusercontent.com/32598656/42410587-d7176a9a-81b9-11e8-9a5f-e6f472f3175f.png)

 I still can generate metadata document using XrmToolbox. Anyone can help me out?  Thanks.

**Comment by MscrmTools** [comment]
You need to create an issue in the appropriate repository, if exists...
I’m not the developer of this plugin so can’t help
