### ISSUE TITLE
Separating Open File dialog

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/XrmToolBox#779]
Hi

it's just a suggestion, is there a way that you can separate the ope file dialog from each plugin, for example normal loaded path for the open file dialog for Web Resource is the JavaScript solution, and in the plugin registration will be the DLL location.

**Comment by MscrmTools** [comment]
No, I cannot do that. It’s the responsibility of each plugin to set or not the folder that will be showed first when using open file dialog.
If no path is specified, then the last folder used anywhere in the OS is used

**Comment by aboodh95** [comment]
OK, Thank you
