### ISSUE TITLE
Latest plugin version not showing in Plugin Store

### ISSUE THREAD

**Issue by jamesnovak** [MscrmTools/XrmToolBox#780]
I published an update to my plugin 4 days ago and unlisted the older version.  New version is 1.2018.7.1 The new version is not being shown in the Plugin Store, even with the latest install of the XrmToolbox.

Nuget package: https://www.nuget.org/packages/Xrm.Tools.CrmSvcUtilTS

Am I missing something in my tags?  

I cleared the Plugin Store cache and refreshed. I also manually deleted plugin and nuget package cache with no luck.  I downloaded the latest and ran from a separate folder with the override path, so it was a clean install.  I still see the old version listed: 
![image](https://user-images.githubusercontent.com/69029/42763678-ca3532ce-88e1-11e8-9e37-e17b8532fcc6.png)

**Comment by MscrmTools** [comment]
A workflow on my side failed so the update was not retrieved.

You can refresh manually your plugin in my CRM organization by going in your XrmToolBox portal profile. There is a list of your plugins and you can force refresh of its content from there
________________________________
De : James Novak <notifications@github.com>
Envoyé : lundi 16 juillet 2018 16:21
À : MscrmTools/XrmToolBox
Cc : Subscribed
Objet : [MscrmTools/XrmToolBox] Latest plugin version not showing in Plugin Store (#780)


I published an update to my plugin 4 days ago and unlisted the older version. New version is 1.2018.7.1 The new version is not being shown in the Plugin Store, even with the latest install of the XrmToolbox.

Nuget package: https://www.nuget.org/packages/Xrm.Tools.CrmSvcUtilTS

Am I missing something in my tags?

I cleared the Plugin Store cache and refreshed. I also manually deleted plugin and nuget package cache with no luck. I downloaded the latest and ran from a separate folder with the override path, so it was a clean install. I still see the old version listed:
[image]<https://user-images.githubusercontent.com/69029/42763678-ca3532ce-88e1-11e8-9e37-e17b8532fcc6.png>

**Comment by jamesnovak** [comment]
Sounds good.  I noticed that a few hundred downloads were registered, so I think it's all good now!
