### ISSUE TITLE
Webresources Manager

### ISSUE THREAD

**Issue by aaroncarpenter** [MscrmTools/XrmToolBox#781]
I am getting an error that says there is an error in the XML document when trying to open this plugin.

![image](https://user-images.githubusercontent.com/3410156/42770980-8e670d8c-88da-11e8-843a-6ea1d0a86c07.png)

**Comment by MscrmTools** [comment]
Please check closed issue where this problem has been answered multiple times...

You just need to delete previous WRM settings file

**Comment by aaroncarpenter** [comment]
Got it. My apologies for not checking there first.
