### ISSUE TITLE
Unable to debug plugins - could not load file or assembly McTools.Xrm.Connection

### ISSUE THREAD

**Issue by bwmodular** [MscrmTools/XrmToolBox#782]
Hi,
I'm trying to debug a plugin (MsCrmTools.UserSettingsUtility) so that I can resolve an issue. I had it working before but now (months later) I come back to it and I just cannot get it to debug.

I've downloaded the latest version of the UserSetttingsUtility from Github.
I've updated my local copy of the toolbox to the latest version (1.2018.7.26)
I've copied the entire contents of my toolbox folder to the Bin/debug folder of my project.
I've added the build event to copy the plugin to /Plugins
I've amended the start action and start options on the Debug properties page.

When I try and debug, I get this big error:
![image](https://user-images.githubusercontent.com/1889586/42938511-7162f120-8b4a-11e8-95f9-2a4f0e1ed7bd.png)

To me this looks like a mismatch between the toolbox release version of the McTools.Xrm.Connection and the one used by the UserSettingsUtility project,, so I tried to update this from Nuget (from 1.2017.2.12 to 1.2018.7.18) but this fails with this error: _"Could not install package 'MscrmTools.Xrm.Connection 1.2018.7.18'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."_

I feel like I'm missing something obvious, but can't figure it out - any ideas?

Thanks,
Ben

**Comment by MscrmTools** [comment]
There is a more easy way to debug plugins. Please read the [documentation](https://www.xrmtoolbox.com/documentation/for-developers/debug/)

Moreover, it seems you have an old version of UserSettingsUtility code as it should already be set to use .Net Framework 4.6.2

**Comment by bwmodular** [comment]
Gah - sorry you are right - I thought I had the latest version, but I'm clearly still working with my older clone. Start again - sorry for the confusion.....
