### ISSUE TITLE
Add "New" tag for new plugin

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/XrmToolBox#784]
Hi,

Can you add "New" tag or icon for the just installed plugins, also if they can have there own segregation in the Start Page

**Comment by MscrmTools** [comment]
Not sure there is enough space in Start Page... Adding a new icon should be easy. I will work on this

**Comment by MscrmTools** [comment]
And... ready!

![image](https://user-images.githubusercontent.com/10774317/81201283-668bf900-8fc5-11ea-812e-84b2e3aa5775.png)

**Comment by rappen** [comment]
That looks super nice! 😎
