### ISSUE TITLE
cannot start custom plugins from XRM Toolbox

### ISSUE THREAD

**Issue by PrashantPatil7875** [MscrmTools/XrmToolBox#786]
I have designed custom plugin but when I tried to start plugin from XRM Toolbox I got following error
![image](https://user-images.githubusercontent.com/41750156/43301555-938182be-9183-11e8-84c9-89846f3a20be.png)
I have tried a new version of XRM toolbox but  I am getting the same error. Please look into this issue.

**Comment by MscrmTools** [comment]
There might be a bug in the template, please remove all custom code from the constructor of your plugin control

**Comment by PrashantPatil7875** [comment]
Thank you for a reply. I had tried this option. I had created a new project in Visual  Studio and selected XRMtoolbox template without changing any code I tried to run it but still I got the same error. I also removed my all custom code from the constructor and tried to run plugin but the issue not resolved.

**Comment by PrashantPatil7875** [comment]
I think I have found an issue and temporary workaround in XRMToolbox so I will try to explain it in detail.
First  I have created a new project in visual studio and selected xrmtoolbox template without changing the code I had compiled and used this custom plugin in xrmtoolbox. when clicked  on myfirstlugins and try to connect crm org I got following error.
![image](https://user-images.githubusercontent.com/41750156/43379155-9cfe709c-93e8-11e8-9aa1-6161121f273c.png)
After double checking everything,  I had tried to run custom plugins in a different way. First I disconnected from CRM org then I start my sample custom plugin but this time I didn't choose to connect with CRM org and started plugins.
![image](https://user-images.githubusercontent.com/41750156/43379309-61090fba-93e9-11e8-844a-11874dffb568.png)
as usually plugins started without connecting to CRM org.
![image](https://user-images.githubusercontent.com/41750156/43379357-a6c957da-93e9-11e8-9503-d05cfb358c83.png)
After this step, I connected XRMtoolbox with CRM org and run this same plugin and it worked.
![image](https://user-images.githubusercontent.com/41750156/43379416-f0aa1f1a-93e9-11e8-870e-8df9f9175124.png)
I am still looking to  fix this issue but if anyone having the same problem maybe they can use  this temporary solution.

**Comment by PrashantPatil7875** [comment]
Now I am able to run my custom plugin.Just comment following lines in  UpdateConnection method             //mySettings.LastUsedOrganizationWebappUrl = detail.WebApplicationUrl;
//LogInfo("Connection has changed to: {0}", detail.WebApplicationUrl);
