### ISSUE TITLE
File new updated version of `XTB` that includes `Connection` fixes

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#787]
Is it possible to create new `bugfix` release off the schedule. There are some nasty `ConnectionString` related bugs which would be nice to be fixed. Otherwise it's almost impossible to even develop new plugins and fixes for existing ones — it's often just impossible to connect to the CRM...

Would be really appreciated.

**Comment by MscrmTools** [comment]
I will release a fix version really soon with all your fixes. Thanks for that, btw

**Comment by MscrmTools** [comment]
I will push everything this evening. If new fixes are to come, that should be today :)

As for bugfix release, there is already automatic prerelease in this repository when anything is commited on XrmToolBox project

**Comment by shytikov** [comment]
Thank you for your quick response! And for all the work you do!
