### ISSUE TITLE
The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by NaveenaChhabra** [MscrmTools/XrmToolBox#789]
I Am using XRMT
[XrmToolBox_Connection-2018-08-01.log](https://github.com/MscrmTools/XrmToolBox/files/2247941/XrmToolBox_Connection-2018-08-01.log)
ool Box 2015 while creating connection with organisation i am getting below error.

The remote server returned an error: (403) Forbidden

**Comment by MscrmTools** [comment]
What is XrmToolBox 2015?

**Comment by NaveenaChhabra** [comment]
Yes, XRMToolBox2015

**Comment by MscrmTools** [comment]
It does not exist... or if you are using an XrmToolBox version from 2015, then please download the latest version

**Comment by NaveenaChhabra** [comment]
HI Have downloaded latest version of XRMToolbox  1.2018.7.28  still facing same error.
The remote server returned an error: (403) Forbidden.

**Comment by MscrmTools** [comment]
Here is the time where you send me screenshots about how you configure your connection :)

**Comment by MscrmTools** [comment]
is your username an office 365 email address?

**Comment by NaveenaChhabra** [comment]
Yes, But i tried with other user name which is not office 365 user

**Comment by MscrmTools** [comment]
any integration between your local AD and Azure AD?

**Comment by NaveenaChhabra** [comment]
No, There is no integration between local AD & Azure AD. 
Earlier it was working fine. But from last 15 days it is not working. Even i tried on other machine also. i tried so many thing but no fruitful result found.

**Comment by MscrmTools** [comment]
If it was working earlier then it doesn't work anymore, except if the problem occurs since an XrmToolBox update, I will contact my network team to understand where the http request go
