### ISSUE TITLE
Unable to see custom entities or solutions with custom entities for any plugins in Prod environment only

### ISSUE THREAD

**Issue by toddow21** [MscrmTools/XrmToolBox#790]
I am unable to see any custom entities for ANY plugin when connected to my production environment (D365 online v9.0) running XRM Toolbox v1.2018.7.28. However, when connecting to my Sandbox org, they show up fine. It is not a user issue, I've logged in with my credentials on a colleagues computer and the custom entities all show up. And vice-versa, my colleague has made a connection on my laptop using his credentials, and no custom entities or solutions with custom entities show up. I've used older versions, removed all files in the local and storage folders, I cannot figure this issue out. And it was working previously up until about 2 weeks ago. Not sure what could have changed to introduce this issue. Has anyone else seen this issue or have any ideas what might be causing it?

**Comment by MscrmTools** [comment]
Can you tell us if there is any version difference between prod and sandbox orgs?

**Comment by toddow21** [comment]
No - both are version 1612 (9.0.2.761)

**Comment by MscrmTools** [comment]
Did you try to recreate connections for both org? Is that the same behavior?

**Comment by toddow21** [comment]
Yes, deleted connections multiple times, even re-created with different user and still same behavior even with a  different username.

**Comment by toddow21** [comment]
Some examples. I could go on, it impacts every plugin. No custom entities or solutions with custom entities show up anywhere. 
<img width="372" alt="fetch_xml_builder_prod" src="https://user-images.githubusercontent.com/14299160/43597916-4e27faea-9638-11e8-9854-c0ae6bc6e898.png">
<img width="376" alt="fetch_xml_builder_sandbox" src="https://user-images.githubusercontent.com/14299160/43597917-4e448dcc-9638-11e8-9ed7-e1cae79c97bb.png">
<img width="679" alt="metadata_browser_prod" src="https://user-images.githubusercontent.com/14299160/43597918-4e5f6a5c-9638-11e8-8676-7ac4d4188acd.png">
<img width="682" alt="metadata_browser_sandbox" src="https://user-images.githubusercontent.com/14299160/43597920-4e7ff13c-9638-11e8-993d-365e700b2a44.png">

**Comment by rappen** [comment]
I know it affects all plugins, but since this is a really strange problem, I'll still ask stupid question:
In FXB there are options for which entity types to display, and these settings are stored per connection.

![image](https://user-images.githubusercontent.com/2572253/43601411-5eabae48-968d-11e8-88ee-b9dcf14088a9.png)

Can you verify these settings?

**Comment by MscrmTools** [comment]
Can you try to connect with plugin registration tool and see if you can register a plugin against a custom entity or not?

**Comment by toddow21** [comment]
Yes - I looked at that option, tried playing around with it to just show custom entities and then the dropdown shows up blank. 

This is now being reported by two more of my colleagues. Same exact issue. However, we have done some further testing and accessing other D365 client production orgs works fine. It seems to be something specific to our production org only.

**Comment by toddow21** [comment]
I am also unable to see any custom plugins or register them

**Comment by MscrmTools** [comment]
Ok, so this is definitively not an issue with XrmToolBox.
May we close this issue?

**Comment by toddow21** [comment]
Sorry - to clarify, using the SDK plugin registration tool, I see my custom plugins. I meant using the XRM Toolbox plugin registration tool - that one I cannot see custom plugins. 

<img width="589" alt="plugin registration tool" src="https://user-images.githubusercontent.com/14299160/43610962-95e9bda4-965c-11e8-88de-d9b01cefb5ac.png">

**Comment by gregowens** [comment]
Do you have the same security role in each environment? Maybe you are not Sysadmin in Production?

**Comment by toddow21** [comment]
Any ideas on this? It is still an issue - only with our own instances. I am definitely an admin and the other admin is also experiencing the same issue. Getting very frustrated.

**Comment by kbolton** [comment]
I have the same problem with 
XrmToolBox v1.2018.10.29
Dynamics 365 v9.1.0.2057

**Comment by kbolton** [comment]
I have some information but unfortunately I don't have great before and after pictures.  So I'm going to throw a herring in the air and y'all can decide if it's red.

My company had several environments setup (production, trial, etc) and it seemed that XTB was connecting to our trial environment.  The trial environment did not have any of the custom entities.
![image](https://user-images.githubusercontent.com/6640917/53055231-f901b480-3474-11e9-97f0-c10ceee8d2af.png)

I deleted the additional environments and I can now see the custom entities in XTB.  Hope it helps.
