### ISSUE TITLE
AccessTeamIntegration Tool Depreciated ?

### ISSUE THREAD

**Issue by lokyeung** [MscrmTools/XrmToolBox#792]
Through the Documentation, I still able to see it, but it the list of available plugins it went away. 
Any solution to get this tool back as we are looking to leverage this tool to import the access team members. 

Thanks!

**Comment by leojouffe** [comment]
In the new XRM TOOL version, AccessTeamIntegration plugin seems not to be maintened anymore.
https://www.xrmtoolbox.com/plugins/
Is there any chance to recover it ? 
Thank you in advance for your answer !

**Comment by MscrmTools** [comment]
The developer did not register it on the new XrmToolBox portal developer so the only way is to [download](https://www.nuget.org/packages/AccessTeamImportPkg/) the plugin package and install it manually. Just hope it is still compatible with current version of XrmToolBox
