### ISSUE TITLE
Issue while importing translated custom entity via Easy Translator

### ISSUE THREAD

**Issue by jalakraval123** [MscrmTools/XrmToolBox#797]
We're using the plug-in called "Easy Translation" to Import/Export Import translated entity and field text.

We're facing the below error's while importing the translated custom entity. 

[MsCrmTools.Translator.log](https://github.com/MscrmTools/XrmToolBox/files/2293721/MsCrmTools.Translator.log)

Could you please help us to troubleshoot this issue? How we can identify where we need to focus to resolve this error?

Thank you

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.Translator #13](https://github.com/MscrmTools/MsCrmTools.Translator/issues/13) via [**ZenHub**](https://www.zenhub.com/)
