### ISSUE TITLE
Issue connecting to CRM 365 V9 instance

### ISSUE THREAD

**Issue by neospfa** [MscrmTools/XrmToolBox#802]
I have 5 CRM instances accessible on my tenant, and when trying to connect to one of them, XRMToolbox always connect to another one, always the same. No issue with the 4 others.
I wonder if there is not something wrong with the way Organization and OrganizationUrlName are interpreted at the login phase, I explain why :
- The CRM instance to which I try to connect has an URL like "https://orgname.crm4.dynamics.com" and its uniquename is "orgname02"
- The CRM instance to which XRMToolbox connects effectively has an URL like "https://iq-orgname.crm4.dynamics.com" and its uniquename is "orgname" (for historical reason)

I tried to manually modify the connection file and edit the values in these XML field (Organization and OrganizationUrlName) but they always get resetted after connection, so it does not work.

I never had that issue with previous versions of XRMToolbox.
Any idea ?

**Comment by MscrmTools** [comment]
This is not related to the new version of XrmToolBox AFAIK. the CrmServiceClient constructor has difficulty to identify which organization is the appropriate one to load when two orgs have the same value for uniquename and url name.

**Comment by MscrmTools** [comment]
Latest version of Tooling assemblies should fix this issue. I will close the issue now. Please reopen it after next release if the problem still occurs
