### ISSUE TITLE
Unable to Connect to xrmtoolbox to Online D365

### ISSUE THREAD

**Issue by dnaveen2012** [MscrmTools/XrmToolBox#806]
Hi Team,
I have online D365 instance and the instance redirects to ADFS URL. Because of this i am not able to connect to the organization using xrm tool box with any of the authentication type.

Please help me to solve this.

Thanks
Naveen Dasari

**Comment by MscrmTools** [comment]
I guess you should use the connection string way. But I cannot tell what would be the value expected for your configuration
