### ISSUE TITLE
Unable to publish web resource

### ISSUE THREAD

**Issue by saranasd** [MscrmTools/XrmToolBox#807]
I have just download the CRM Toolbox for 365 v1.2018.7.28 
after updating the web resource (js File) while publishing its throwing me the error.
"System.Overflow.Exception:Values was either too large...."

but same file i can able to edit inside the crm and publish from there and also i can publish the same file lower version of the XRM toolbox.

Please check and advise.

Thanks 
Saravanan

**Comment by MscrmTools** [comment]
I guess you are talking about WebResources Manager?

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.WebResourcesManager #73](https://github.com/MscrmTools/MsCrmTools.WebResourcesManager/issues/73) via [**ZenHub**](https://www.zenhub.com/)
