### ISSUE TITLE
Can‘t show the start page and plugins tabs

### ISSUE THREAD

**Issue by lw7898** [MscrmTools/XrmToolBox#809]
You need to adjust the pnlConnectLoading panel' layout because it overlaps both startpage and plugins tab

**Comment by MscrmTools** [comment]
Can you share a picture?
This should happen only if you have a shortcut that includes a connection

**Comment by flashking** [comment]
I'm having the same issue. I get a blank screen when i log in. I tried about 3 different version and still same issue.

**Comment by MscrmTools** [comment]
Same question: may I have a screenshot?

**Comment by flashking** [comment]
In fact, I just tried to reinstall it and now getting an error 

![image](https://user-images.githubusercontent.com/649814/45643723-98f38600-ba70-11e8-88a7-df11c0e8a8f8.png)

**Comment by MscrmTools** [comment]
Your version is outdated... There should have been at least 6 new versions then.

Please download and install latest version

**Comment by MscrmTools** [comment]
Can you show the details of the error?

Also, i guess you may have to delete the XrmToolBox settings file

**Comment by flashking** [comment]
Ok, I just deleted the XrmToolBox settings file and it is now working. I think the issue started with the last update. Thanks

**Comment by lw7898** [comment]
Sorry for late reply. I also get a blank screen whether i connected or not, and the issue still unsolved even i delete the XrmToolBox.Settings.xml file. then i run the version i mofified it is working...

**Comment by SixColor** [comment]
> Sorry for late reply. I also get a blank screen whether i connected or not, and the issue still unsolved even i delete the XrmToolBox.Settings.xml file. then i run the version i mofified it is working...

how to modify blank screen please

**Comment by MscrmTools** [comment]
The blank screen can be due to invalid tool assembly. Please remove all tools from Plugins folder except those who starts with "MscrmTools" and try to run again XrmToolBox
