### ISSUE TITLE
Users, Team and Security Roles Report

### ISSUE THREAD

**Issue by glenwol** [MscrmTools/XrmToolBox#814]
I just installed the latest version and I am getting a strange behavior from this plugin.  I start it and it runs fine on my Test and Development systems, but when I run it on Production it does nothing.

I click on LOAD DATA and it spins for half a second and then comes back with nothing.  Getting the same behavior on multiple installs but only against my Production box.

Any ideas?

Thanks,
Glen

**Comment by MscrmTools** [comment]
Please check with plugin developer.

**Comment by MscrmTools** [comment]
I just have his twitter handle : @nishantranaCRM
