### ISSUE TITLE
Please create a Chocolatey Package

### ISSUE THREAD

**Issue by fberasategui** [MscrmTools/XrmToolBox#815]
As the title suggests, it would be nice if this tool was available as a Choco package to enable CLI-based installation.

**Comment by MscrmTools** [comment]
Please point me to the appropriate documentation to understand where to start

**Comment by fberasategui** [comment]
@MscrmTools Chocolatey is a package manager for Windows (akin to apt-get on Linux), based on Nuget. So basically you can pack your application as a Nuget / Chocolatey package and have people install it via the command line.

https://chocolatey.org/docs/create-packages

**Comment by joshcampbell191** [comment]
I know this post is getting a little old, however I'm in the process of submitting a Chocolatey package to do just that. 

I'll update this post once the link is live.

In the meantime, you can check out the code here: [chocolatey-packages/xrmtoolbox](https://github.com/joshcampbell191/chocolatey-packages/tree/master/xrmtoolbox). It was built using [Chocolatey Automatic Package Updater Module](https://github.com/majkinetor/au-packages-template) to facilitate updates.

**Comment by joshcampbell191** [comment]
The package is now live: [https://chocolatey.org/packages/xrmtoolbox](https://chocolatey.org/packages/xrmtoolbox).

The latest version will be pushed shortly.

**Comment by joshcampbell191** [comment]
The latest version has been approved.

**Comment by MscrmTools** [comment]
Thank you very much @joshcampbell191 

I really did not have time to do it...
