### ISSUE TITLE
Issue with Entity Security Role Plugin

### ISSUE THREAD

**Issue by AshokJinkala** [MscrmTools/XrmToolBox#817]
Hi, 

It was a nice plugin, Thanks.  I found one issue when I am using this plugin, after checking with different scenarios I noticed the issue happens only if entity display name includes special characters, please check. 

Thanks....!

**Comment by MscrmTools** [comment]
Here is the [appropriate repository](https://github.com/santoshCRM/EntitySecurityRole) to create an issue for this plugin
