### ISSUE TITLE
"Are you sure you want to close this tab" doesn't focus to the correct tab

### ISSUE THREAD

**Issue by gregowens** [MscrmTools/XrmToolBox#818]
It's a minor issue really, however: 

If I have multiple tabs open in XrmToolBox and I opt to close the entire application by clicking "X" in the top right corner of the application, each tab will raise a prompt asking "Are you sure you sure you want to close this tab?". This allows me to confirm that I am not losing anything (e.g. a FetchXml statement that I haven't saved). Selecting "No" to this prompt ultimately allows me to abort closing the application. I have noted however that **"...this tab" does not always refer to the tab that is presently selected/visible to the user.** This means that I could potentially agree to closing the tab I can see, while another in the background (that I may want to keep after all) gets closed instead.

## Steps to reproduce: ##

1.  Open XrmToolBox and connect to an organisation
2.  Open up the first three plugins in your list (for example)
3.  Note the name of the currently-visible plug-in (I.e. the last one that you opened) 
4.  Click the application's close button in the top right corner
5.  XTB will prompt "Are you sure you want to close this tab?"
6.  Answer "Yes" to the prompt
7.  Note that the tab you identified in step 3 is still open, however another tab was closed (2 remain open)

**Comment by MscrmTools** [comment]
Would it be ok if the question popup includes the plugin name?

**Comment by gregowens** [comment]
It wouldn't be the most efficient user experience or what one might _expect_ to happen (imagine similar experience in Word or Excel for example) but I say this in ignorance of what you'd need to do to set focus to each tab in turn. Certainly it would be an improvement.

**Comment by MscrmTools** [comment]
Yes i know, I was considering a quick fix before implementing the full request

**Comment by MscrmTools** [comment]
@gregowens, is it still an issue in latest version?

**Comment by gregowens** [comment]
Sorry this is late. Yes definitely resolved.
