### ISSUE TITLE
Issue connecting D365 online via MFA

### ISSUE THREAD

**Issue by genesario** [MscrmTools/XrmToolBox#820]
Hello,
We go to MFA in our tenant and i found an issue connecting.
We registered App
![image](https://user-images.githubusercontent.com/32870200/47345081-95c46900-d6b2-11e8-9dcc-d7277d79013d.png)
Added accesess
Specified Redirect URI: <http://localhost> and <https://ourcrm.crm4.dynamics.com>
![image](https://user-images.githubusercontent.com/32870200/47345156-bdb3cc80-d6b2-11e8-96f2-d0c662c4878d.png)
And created connection string
AuthType=OAuth;Url=https://ourcrm.crm4.dynamics.com; AppId=<our app id>; RedirectUri=<http://localhost> or <https://ourcrm.crm4.dynamics.com> ; TokenCacheStorePath=c:\\Temp\\Oauth\\cache.txt; LoginPrompt=Always;RequireNewInstance=True;
As i found no user-pwd should  be in string.
XRMtoolbox checks and saves such connection.
cache.txt is filled by some token text.
But literaly on each mouse click i am asked to enter password and SMS code
So it is definitely impossible to work.
Any clues?

**Comment by MscrmTools** [comment]
Do not put Always as LoginPrompt, but put Auto, and your should be good

**Comment by genesario** [comment]
It didnt work on my work PC
But worked on home PC
I believe because on work PC i login to windows in one domain and CRM is already in another.
And XRMToolbox with Auto tries to use login information from windows logon.

**Comment by MscrmTools** [comment]
that might be a reason...
