### ISSUE TITLE
Updater Tool missing Quotes when opening ToolBox post update

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#822]
My XTB path is "C:\CRM Tools\XrmToolBox"
After updating I get this error when I click on the Open XrmToolBox button:

![image](https://user-images.githubusercontent.com/9728423/47728163-2f03fa00-dc34-11e8-98d7-668899fe2dc4.png)

**Comment by MscrmTools** [comment]
What was your previous version? I guess I already fixed it

**Comment by plepaisant** [comment]
I have just created a pull request for this issue https://github.com/MscrmTools/XrmToolBox/pull/823. 
The problem is that when the path of XrmToolBox contains spaces, the path is  splitted in many args. The path has to be rebuilt before adding quotes

**Comment by MscrmTools** [comment]
I merged the PR. Closing the issue
