### ISSUE TITLE
Synchronous Event Order Editor missing

### ISSUE THREAD

**Issue by AntoineGauthier** [MscrmTools/XrmToolBox#825]
Hello,

It seems that the plugin Synchronous Event Order Editor is missing from the newer releases.

I don't know from which version it first started to be missing as it became an interest of mine only recently.

I wanted to use the plugin with a 2015 on premise organization.

If the plugin is not supported anymore would you be able to provide an alternative allowing me to set the ranks of real time workflow on a 2015 on premise organization?

Thanks a lot!

**Comment by osculator106** [comment]
Yes. @AntoineGauthier  you are right I am also not able to find it.

**Comment by AntoineGauthier** [comment]
Any feedback on this ?

**Comment by AntoineGauthier** [comment]
Strange thing, I am now once again able to find it.
It is a strong possibility that I (and my coworkers) simply missed it, in any case this issue can be dismissed. 

Thanks a lot.
