### ISSUE TITLE
Unable to register new tool in XrmToolBox

### ISSUE THREAD

**Issue by VineetCRM** [MscrmTools/XrmToolBox#827]
Hi, I am not able to register my new plugin to XrmToolBox site. 
I am getting error message as "Errors have been found in your Nuget package: 
 XrmToolBox version dependency is missing in Nuget package."
This is my Nuget package url"https://www.nuget.org/packages/GetOffice365License/". Could you please suggest with a resolution? Thanks in advance!

![xrmtoolbox_error](https://user-images.githubusercontent.com/45289376/48944001-4c6f6f80-ef25-11e8-80c2-6fb159c47b24.JPG)

**Comment by VineetCRM** [comment]
Just to let you know, I have already added XrmToolBox dependency in Nuget package.

![xrmtoolboxdependency](https://user-images.githubusercontent.com/45289376/48944607-a96c2500-ef27-11e8-9a7e-723fb711e4f4.JPG)

**Comment by MscrmTools** [comment]
I have a bug because I'm analyzing all versions of the plugin. 
Could you unlist version 1.0.0 so that it does not appear in results. It should fix the issue
