### ISSUE TITLE
Taking too much for valiation 

### ISSUE THREAD

**Issue by lokesh7588** [MscrmTools/XrmToolBox#832]
Hi,

I have published new plugin (Bulk Security Patcher) on Saturday dated 4 Jan 2018 but its not validated yet 
I wanted to know normally how much any plugin will take to validate 

Thanks and Regards
Lokesh

**Comment by MscrmTools** [comment]
Hi,
I’m just back from holidays. Should be validated in a couple of days

**Comment by lokesh7588** [comment]
Thank you

**Comment by lokesh7588** [comment]
requesting for revalidation since 5 to 6 days 
but it is still under validation

**Comment by lokesh7588** [comment]
Okay thank you 
i will do the necessary changes and update my Nuget

Thanks
