### ISSUE TITLE
Unable to find www.xrmtoolbox.com

### ISSUE THREAD

**Issue by mikeread2018** [MscrmTools/XrmToolBox#834]
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

**Comment by MscrmTools** [comment]
I can access it.
Certainly a network issue on your side

**Comment by mikeread2018** [comment]
Yep - sorry, should have completed the message. 
On a new download of the xrmtoolbox, on an environment that has a proxy server. The first time the toolbox is started and subsequent time a message is displayed "unable to find www.xrmtoolbox.com" - along with a stack trace. I've added a proxy to the settings (toolbox) and is now fine. An "instruction" message box might be helpful if this message is displayed OR default the proxy to use IE settings...

**Comment by MscrmTools** [comment]
XrmToolBox is released with a config file that should default to IE settings
