### ISSUE TITLE
Not able to update

### ISSUE THREAD

**Issue by Hightower1** [MscrmTools/XrmToolBox#835]
When i click on update i get an error message. 

![image](https://user-images.githubusercontent.com/37645475/51272648-48ddef00-1990-11e9-8ed5-900bb9aad9d5.png)

**Comment by MscrmTools** [comment]
What is your XrmToolBox version?

**Comment by Hightower1** [comment]
Current version is 1.2018.7.28

**Comment by MscrmTools** [comment]
There was a bug in one of older versions. Can you tell me if XrmToolBox closes itself when updating it? If not can you try to manually close it before the end of the download?

**Comment by Hightower1** [comment]
When i click on update that is when that error pops up. Nothing starts to download. I clicked on continue and the download screen appeared but nothing started.

**Comment by MscrmTools** [comment]
Do you have the file mentioned on your XrmToolBox folder?

**Comment by Hightower1** [comment]
As you can see below that file referenced is in the folder. 
![image](https://user-images.githubusercontent.com/37645475/51346467-59ab6500-1a63-11e9-8515-297b36dbe023.png)

**Comment by MscrmTools** [comment]
Never seen this issue. I guess your best option is to download latest version and overwrite your XrmToolBox with it
