### ISSUE TITLE
Approval process for plugins

### ISSUE THREAD

**Issue by deepakkumar1984** [MscrmTools/XrmToolBox#838]
One of my plugins was rejected last year and I just updated it to the latest version of XrmToolBox dependencies. I have updated the Nuget few days ago, but still the status of plugin in Pending. Does it need manual approval?

Plugin Name: "Recycle Bin"
https://www.xrmtoolbox.com/plugins/plugininfo/?id=2bf4b17e-aa07-e811-90cd-00155d6707f2

**Comment by MscrmTools** [comment]
Did you really updated it? The problem are still the same than last year + a version mismatch between your assembly and your Nuget package...

So here are the (same) problems:
- Version mismatch between your plugin assembly and your nuget package
- Please provide an Icon Url in your Nuget package
- Please provide an Image for the small plugins list in your plugin class metadata
- Please ensure that a service is available before peforming action. Currently, opening your plugin without a connection and clicking on buttons make the tool crash (See https://www.xrmtoolbox.com/documentation/for-developers/plugincontrolbase-base-class/) 

You "just" have to follow the procedure on XrmToolBox documentation.

Please do not update your Nuget package until all these points are fixed.

**Comment by deepakkumar1984** [comment]
I have updated the plugin a day ago and still in Pending state. Just wondering if anything happens automatically or someone has to validate it manually. How can I know what else is the issue?

**Comment by MscrmTools** [comment]
I’m at the MVP Summit and have no time yet to validate.
The process is partially manual.
Please be patient
