### ISSUE TITLE
Connections are not getting saved

### ISSUE THREAD

**Issue by karan-mittal** [MscrmTools/XrmToolBox#840]
Hello,

I have some 20-25 CRM Orgs in Dev, and same in UAT and PROD.
I am trying to clone the connections, created all 25 in Dev, UAT and Prod, but they are getting removed on their own while working on XrmToolBox.

Any idea.

**Comment by karan-mittal** [comment]
Hello,

I have some 20-25 CRM Orgs in Dev, and same in UAT and PROD.
I am trying to clone the connections, created all 25 in Dev, UAT and Prod, but they are getting removed on their own while working on XrmToolBox.

Any idea.

**Comment by rappen** [comment]
Are you using dedicated connection files or just default behavior?
This short tutorial might be of help regarding connection management in XrmToolBox: https://jonasrapp.net/xtb-school/conn

**Comment by MscrmTools** [comment]
@karan-mittal is that still an issue? 
As it's a year ago, I'm closing the issue. Reopen it if needed
