### ISSUE TITLE
License file is not recognized

### ISSUE THREAD

**Issue by sjarrell** [MscrmTools/XrmToolBox#841]
I have donated and received my license xml file, however when I place it in the C:\Program Files (x86)\XrmToolbox directory I am still receiving the Donate message. Any suggestions?

Thanks,

Steve

**Comment by MscrmTools** [comment]
I think I see what the problem is.
A file might be missing in XrmToolBox zip file. Can you try to add this file too in your XrmToolBox folder?
[McTools.StopAdvertisement.zip](https://github.com/MscrmTools/XrmToolBox/files/2916520/McTools.StopAdvertisement.zip)

**Comment by sjarrell** [comment]
Thanks. We'll give it a try!

**Comment by MscrmTools** [comment]
@sjarrell Any news?

**Comment by sjarrell** [comment]
@MscrmTools Unfortunately I'm still seeing it (see attachment). I do have McTools.StopAdv.xml and McTools.StopAdvertisement.dll placed in the main program folder.
![XMLToolbox](https://user-images.githubusercontent.com/47953101/55500522-84469c00-5616-11e9-8081-c64ff8032252.jpg)

**Comment by MscrmTools** [comment]
Ok, let me check this!

**Comment by MscrmTools** [comment]
I tested it and it worked as expected... Don't know what is happening here

**Comment by MscrmTools** [comment]
Should be fixed in next release
