### ISSUE TITLE
SDK Tooling Connection causing errors loading plugins

### ISSUE THREAD

**Issue by jamesnovak** [MscrmTools/XrmToolBox#843]
Connections created using the Connection Wizard seem to be fine.

repro:
Create a a new Connection using the SDK Login control.
Connect to the CRM instance
Attempt to load a plugin

you will receive the following error message: 
![image](https://user-images.githubusercontent.com/69029/53586340-f4648c80-3b55-11e9-8a25-94894e4818b4.png)

The following error can be found in the XrmToolBox_Connection-xxx.log

Microsoft.Xrm.Tooling.Connector.CrmServiceClient    Error    2    2/28/2019 12:11:33 PM  OrganizationWebProxyClient is null
Microsoft.Xrm.Tooling.Connector.CrmServiceClient    Error    2    2/28/2019 12:11:33 PM  OrganizationWebProxyClient is null
Source    : Not Provided
Method    : Not Provided
Date    : 2/28/2019
Time    : 12:11:33 PM
Error    : OrganizationWebProxyClient is null
Stack Trace    : Not Provided

**Comment by MscrmTools** [comment]
Fixed with latest version
