### ISSUE TITLE
Connection Change on single tab not working

### ISSUE THREAD

**Issue by apstevenson** [MscrmTools/XrmToolBox#845]
Hi,

It seems the connection is not changing when selecting another one from the connection list at the bottom. It looks like it's only happening when there is a single tab open. I noticed this as I am developing a plugin where the UpdateConnection override is not triggering.

Steps:
I installed the latest version to a new VM. 
Added two connections.
Ran a fetch xml tester query with a connection, note results.
Switched connection in list at bottom.
Validated that the Connection name in the Tab did not change.
Confirmed that running the query again has same results but should be different.
Creating a second tab allows tab selection when switching connections works as expected.

Thanks,
Al

**Comment by bafadam** [comment]
Can also verify this.

**Comment by apstevenson** [comment]
Hey there just wanted to ping back. I'm not sure if I opened this as a bug or not. But this could be a Data Integrity issue for some people. They might have thought that they changed the connection since it appears to change at the bottom. However did not change as noted in the tab header. Then they start making changes in an environment that was not intended. Thanks.
