### ISSUE TITLE
Connection .net exception when running tool in environment with no internet

### ISSUE THREAD

**Issue by DerekHAu** [MscrmTools/XrmToolBox#847]
I seem to get an exception when running XRMToolbox from a completely disconnected server (in an on-premise environment). It takes a lot longer to load (as it waits for it to time out) I am able to hit continue and everything works. It seems to be trying to connect back to an IP address, either for tracking or looking for plugin updates).
It isn't a huge issue, just annoying. Thanks.

**Comment by murthysrvn** [comment]
@DerekHAu, 

Can you confirm if you have the latest code. A similar issue was fixed as part of #828.

**Comment by DerekHAu** [comment]
I am not sure now. Next time I have to use the tool with on that client's site, I'll make sure I am on the latest build and log again if it is still present. 
Thanks

**Comment by MscrmTools** [comment]
Any news?
