### ISSUE TITLE
Start / switch to one plugin from another

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#85]
As we are developing more plugins, where some of them are somewhat related to each other, or could benefit from each other (e.g. _This action needs a fetch to retrieve data, do you want to start FXB to compose the query?_)

So it would be great if there was a XTB method to call another plugin, if the plugin is available.

It would also be great if it was possible to pass some contextual information to the other plugin.
Might even be possible to pass a "handle" to an event listener in the calling plugin, to be able to pass some sort of _result_ back to the caller.

As you can hear from my vague request, this needs to be specified in more detail. If it is feasible to implement.

**Comment by daryllabar** [comment]
In an effort to KISS (hoping that translates to non-native English readers), I would vote that this is not something that the XTB handles.  If you want to call another plugin, you can call it directly from your own plugin.  I've even created common DLLs for my plugins that both of my plugins call.  That's another possible solution as well.

**Comment by rappen** [comment]
Sounds like a good KISS approach :)
Would love to see some example of that, but perhaps not in this forum.

**Comment by MscrmTools** [comment]
Ok so can we close this issue, then?

**Comment by rappen** [comment]
Kill it!

**Comment by rappen** [comment]
@MscrmTools it turns out existing methods don't really do what I was aiming at.
Would you be interested in including such functionality in XTB, or shall I pursue other possible solutions for this?

**Comment by shytikov** [comment]
Voting for reopening this one! :100:

**Comment by rappen** [comment]
Hi

Just wanted to let you know that I have implemented this functionality to make my Bulk Data Updater (BDU) able to communicate with FXB. BDU uses fetchxml to retrieve data from CRM, and it is a lot of help to be able to use FXB to compose the fetch.

Code in BDU:
```
...
var mbargs = new MessageBusEventArgs("FetchXML Builder");
mbargs.TargetArgument = fetchXml;
OnOutgoingMessage(this, mbargs);
...

public void OnIncomingMessage(MessageBusEventArgs message)
{
    if (message.SourcePlugin == "FetchXML Builder" &&
        message.TargetArgument != null && message.TargetArgument is string)
    {
        fetchXml = (string)message.TargetArgument;
    }
}
```

Code in FXB:
```
public void OnIncomingMessage(MessageBusEventArgs message)
{
    calledArgs = message;
    if (message.TargetArgument != null && message.TargetArgument is string)
    {
        ParseXML((string)message.TargetArgument, false);
    }
    tsbReturnToCaller.ToolTipText = "Return FetchXML to " + calledArgs.SourcePlugin;
    EnableControls(true);
}

private void ReturnToCaller()
{
    if (calledArgs == null)
    {
        return;
    }
    var message = new MessageBusEventArgs(calledArgs.SourcePlugin)
    {
        TargetArgument = GetFetchString(true)
    };
    OnOutgoingMessage(this, message);
}
```

All this works beautifully!

So there is now (when committed etc) a nice and clean integration interface to FetchXML Builder, for anyone to use!

**Comment by shytikov** [comment]
:+1:
