### ISSUE TITLE
Possible virus in Autoupdater

### ISSUE THREAD

**Issue by apstevenson** [MscrmTools/XrmToolBox#850]
When I downloaded the zip file the scanner didn't pick it up but when I unzipped it then it found it. Happened on two different computers. Please verify to see if it's just my systems.

**Comment by MscrmTools** [comment]
This is a known issue. 
I’m trying to update my antivirus but my computer is stuck when updating definitions.
I will post news as soon as I get some

**Comment by MscrmTools** [comment]
May I ask what antivirus you are using?

**Comment by apstevenson** [comment]
Yeah sure, it's Windows Defender:

Threat definition version: 1.289.911.0,
Version created on: 11:10:11 AM: Monday, March 11, 2019
Last Update: 9:14 Tuesday, March 12, 2019

**Comment by MscrmTools** [comment]
Ok, so this is the only antivirus that detects it... BUT I have the same version and it does not find anything... :/

**Comment by apstevenson** [comment]
Yeah and it just started happening yesterday, I guess after the latest Defender version was created. My other machine that detected it has the same version of defender.

**Comment by apstevenson** [comment]
The other strange thing is that Defender doesn't find when it scans the Zip file. Only when I try to unzip it will it complain. 

Were you trying the virus total site that was mentioned in #458 ?

**Comment by MscrmTools** [comment]
Just got the confirmation from Microsoft this is a false positive. There should be new definition soon to remove this detection

**Comment by apstevenson** [comment]
Excellent! Thank you for your help!
