### ISSUE TITLE
Privacy - data collection should be opt-in

### ISSUE THREAD

**Issue by amervitz** [MscrmTools/XrmToolBox#851]
I got a notice of new data collection being performed. Here is a description of it:

![image](https://user-images.githubusercontent.com/10599498/54225866-3d0b3680-44c2-11e9-90b1-867f59fc02b7.png)

Please respect users privacy and make such data collection an opt-in setting that requires explicit approval before collecting such data about users.

**Comment by MscrmTools** [comment]
I'm not collecting any data "about users". I don't understand what users privacy you are talking about as I collect absolutely no data about the user. 
The more precise data about the user is the state where he lives. That can be anyone amongst millions of people

**Comment by daryllabar** [comment]
Is there some concern you have with the level of information that is logged?

**Comment by amervitz** [comment]
I do not want my usage of this application to be tracked in this manner. Lots of software applications give the option of choosing whether to allow such telemetry tracking to be performed.

An opt-out option, while less desirable, would also be appreciated.

**Comment by daryllabar** [comment]
Could you explain why?  I'll repeat, can you define something specific that you are concerned about?  This telemetry is extremely valuable when it comes to trouble shoooting and diagnosing potential issues.  Until there is a reason as to why this information is in any way something that would have any potential concern for an individual, I see no reason to implement such a request.

**Comment by amervitz** [comment]
It is quite simple, I value my [privacy ](https://www.merriam-webster.com/dictionary/privacy) and do not want to participate in sharing this usage information which you are interested in collecting.

**Comment by georged** [comment]
@amervitz you are using free software and derive enormous value on a daily basis. Being anal retentive about anonymous data collection is not helpful. Your privacy is not violated in any shape or form because there is no association between **you** and any of the data collected, full stop. Afaik, there's no way to even state that the two subsequent log entries come from the same installation (assuming that the versions and the _state/country_ match).

To put it into perspective. What if the tool makes it a condition of the use? Would you stop using the tool?

**Comment by daryllabar** [comment]
@amervitz You still haven't make an argument about how this is affecting your privacy.  I'm closing this request.

If you would like to continue to use the tool and not have that information tracked you can always update your hosts file to block https://dc.services.visualstudio.com/v2/track.  Cheers!

**Comment by MscrmTools** [comment]
@amervitz, Next release will allow to optout the data collect.
