### ISSUE TITLE
In plugin store some plugin is grayed out although it is not installed. When trying to install the program says the installation is done, but the plugin is not appearing in the list of plugins.

### ISSUE THREAD

**Issue by rzinguer** [MscrmTools/XrmToolBox#853]
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

**Comment by MscrmTools** [comment]
Screenshot? List of impacted plugins?

**Comment by rzinguer** [comment]
Here is the screenshot attached. The plugin is Manage Workflows.

![image](https://user-images.githubusercontent.com/47708441/54402926-71d6e380-46a4-11e9-884a-77c5fe319ede.png)

**Comment by MscrmTools** [comment]
Does it still happen with latest version of this plugin? I don't reproduce it
