### ISSUE TITLE
Unable to register plugin - Sql Error

### ISSUE THREAD

**Issue by MannyGrewal** [MscrmTools/XrmToolBox#854]
Hi,
I have built my plugin and got the nuget package done. Gone through your checklist and it seems my plugin ticks all the boxes but when I try to go to https://www.xrmtoolbox.com/plugins/new/
and put its nuget id "Veritec.WorkflowBuddy", and click Submit. I get the following error

Sql error: 'String or binary data would be truncated. The statement has been terminated.'

**Comment by MscrmTools** [comment]
I guess it’s due to the title of your plugin that is a description... so it’s too long for the name attribute

**Comment by MannyGrewal** [comment]
That was it, I will change title and re-submit.
