### ISSUE TITLE
Unable to connect to Dynamics 365 online (version 9.1)

### ISSUE THREAD

**Issue by RRB-CRM** [MscrmTools/XrmToolBox#857]
I'm getting below error while trying to connect to CRM online.

**Error	: Value cannot be null.
Parameter name: identityProvider**

I tried with the latest verstion of xrmtoolbox and also with the previous versions. I also tried with different connection options (with Url and connection string) but no luck.
Log file attached.

[XrmToolBox_Connection-2019-03-27.log](https://github.com/MscrmTools/XrmToolBox/files/3012238/XrmToolBox_Connection-2019-03-27.log)

**Comment by JamesStuder** [comment]
Are you using 2 factor authentication?  If so, you will need to generate an app password in order to connect.
