### ISSUE TITLE
Entity Attibute Mapping

### ISSUE THREAD

**Issue by Kitemundo** [MscrmTools/XrmToolBox#862]
Have been using this great tool for some time now without any hitch. However, I've upgraded to the latest update and now it doesn't list my entities. Its flies thru "retrieving source entities' pop up screen but doesn't list anything (scn2).

Is there anything I can do to fix this?
 
![scn1](https://user-images.githubusercontent.com/47138295/57427524-d6529100-7256-11e9-86f2-aa860a50f3da.png)
![scn2](https://user-images.githubusercontent.com/47138295/57427527-dbafdb80-7256-11e9-8bb4-173318417444.png)

Best regards,

Lawrence

**Comment by rappen** [comment]
This tool is created by NORRIQ, I suggest you contact them instead.
See https://www.xrmtoolbox.com/plugins/Norriq.XrmToolBox.YourEntityAttributeMappingsCustomized/
