### ISSUE TITLE
Attribute Audit Explorer Export File not saving

### ISSUE THREAD

**Issue by stapix** [MscrmTools/XrmToolBox#863]
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

**Comment by stapix** [comment]
Every single time I try to export the file from the plugin, there is no file saved.

**Comment by MscrmTools** [comment]
I'm not the owner of Audit Explorer plugin. Please contact the developer [Here](https://github.com/MarioEME/MESquare.XrmToolBox.AuditExplorer/issues)
