### ISSUE TITLE
Connecting to Online Instance as Partner

### ISSUE THREAD

**Issue by hshill1ng** [MscrmTools/XrmToolBox#864]
Has anyone figured out how to use XRMToolbox connecting as a partner accounts thru delegation with two factor authentication enabled?

**Comment by TclasenITVT** [comment]
You could try creating an AppRegistration inside the azure ad that is connected to the crm instance you want to access. Upload a Certificate to the AppRegistration and give permissions for accessing dynamics. Then use a non-interactive user with the certificate auth. At least that worked for us.
