### ISSUE TITLE
Plugin Update

### ISSUE THREAD

**Issue by DigitalFlow** [MscrmTools/XrmToolBox#865]
Hey there,

I updated my XrmToolBox plugin to a new version, but the new version is currently not showing up in the plugin list: https://www.nuget.org/packages/MsDyn.Contrib.CloneFieldDefinitions
Could you please update the version for my plugin inside your list?

Kind Regards,
Florian

**Comment by MscrmTools** [comment]
There is a recurring job that updates definition each 6 hours.
If you want/need it to be faster, log in your profile, then in your plugins list, you can force the refresh of your plugin definitions

**Comment by piyushpaliwal** [comment]
@MscrmTools the plugin has been published to the nuget since 11 days now, why is the 6 hours job not picking it up?

**Comment by DigitalFlow** [comment]
It seems I registered with Twitter Auth on the XrmToolBox portal.
As I got rid of Twitter, I can't login anymore. I'm not able to force refresh currently.

**Comment by MscrmTools** [comment]
There was an issue in your plugin update workflow.
It's fixed now

**Comment by DigitalFlow** [comment]
Hi @MscrmTools,

Seems we're having this issue again with version 1.2.0 which we released this night.
Could you check please?

FYI @piyushpaliwal 

Kind Regards,
Florian
