### ISSUE TITLE
Add a connection button on the main page

### ISSUE THREAD

**Issue by Juli3n75** [MscrmTools/XrmToolBox#866]
When the XRMToolBox starts, it would be nice to have the connection menu in the middle of the "Start Page" and not in the top left.
![image](https://user-images.githubusercontent.com/51375209/58891021-c09b8480-86b9-11e9-9b23-3e2223dcc21b.png)

**Comment by MscrmTools** [comment]
After review, it does not seem easily doable as connection controls are not part of XrmToolBox but another project. That would mean rebuilding connections UI here.
Won't implement, sorry ;)

**Comment by rappen** [comment]
@Juli3n75 you show him - I'm looking forward to a PR from you that fixes this! 😁
