### ISSUE TITLE
Many plugins error on opening in XRMToolbox since recent update

### ISSUE THREAD

**Issue by simes1** [MscrmTools/XrmToolBox#868]
I am finding quite a few user-centric plug-ins fail to open since I updated XRMToolbox to the latest version:

![image](https://user-images.githubusercontent.com/11423243/59204149-efbd6480-8b97-11e9-80e9-7e093ec959f9.png)

Examples include:

- Personal Views
- Personal user views migration
- Personal Views/Charts/Dashboards Transfer Tool
- Sockeye.ViewTransfer

**Comment by MscrmTools** [comment]
This is a know not-issue. Developers have been warned weeks ago about this change. You just have to wait that developers update their plugins. Or asked them directly to update their plugins

**Comment by simes1** [comment]
Thanks for the prompt response

I have created issue for two of them but then found the issue more widespread.

In the meantime which version of XRMToolbox do I need to revert back to in order to avoid this problem?

--
Simon

**Comment by MscrmTools** [comment]
The previous one. So 1.2019.2.32 if I’m correct
