### ISSUE TITLE
Copying View layouts and Filters

### ISSUE THREAD

**Issue by wayneataylor** [MscrmTools/XrmToolBox#87]
Hi
I have used the Copy layouts between Views in an Entity, and that works great, but I have a situation where it would be good to also copy the quite complex Filter applied to a View to other Views on the same entity,
Anyone got any easy ways of doing this?
cheers
Wayne

**Comment by MscrmTools** [comment]
What is the point to copy the same filter in other views of the same entity? a view IS a filter on data. So it seems to me that having different views with same filter is a non sense

**Comment by wayneataylor** [comment]
In this situation we have different views that show the same Entries, but show different columns depending on which View is selected
Also, we need to copy this same Filtering to a Lookup view etc
Thanks
Wayne

**Comment by rappen** [comment]
One of the functions in FetchXML Builder is to update the query / filter of system views, so that can be used.
You find it at http://fxb.xrmtoolbox.com

**Comment by MscrmTools** [comment]
Yep, and since View Layout Replicator replicates... Layout (indeed), then I guess I won't include this feature. 
As @rappen said, you can use FetchXmlBuilder to update the query
