### ISSUE TITLE
Unable to login with latest update xxx6.33

### ISSUE THREAD

**Issue by ArvindBhat83** [MscrmTools/XrmToolBox#873]
I am unable to login to CRM after the latest update which is xxxx6.33

**Comment by MscrmTools** [comment]
Can you give us more information? What kind of deployment? With watch kind of authentication?

**Comment by ArvindBhat83** [comment]
Hi,

Thank you for your prompt response.

I have an existing connection set up for my PROD environment where in I am providing email id with the domain and password.  This is with the connection wizard option from Xrmtookbox.  Both are failing, either connecting to the environment by providing credentials or connecting through a plugin like bulk workflow execution.  It was working till yesterday but not anymore, not for me nor colleagues around me.

Regards,
Arvind.

**Comment by MscrmTools** [comment]
I still don’t understand if you are connecting to online, onprem, ifd ?
What is the version of your organization?

**Comment by ArvindBhat83** [comment]
Apologies! Its online.  D365 version 9.1.0.5229.

As I type this, suddenly I am able to login.  Its almost as if there was an Xrmtoolbox outage.

**Comment by MscrmTools** [comment]
There cannot be a XrmToolBox outage since it’s not an online service. 
But an issue with Office 365 authentication was more likely the issue

**Comment by Mattw112** [comment]
I too am having this issue.  D365 online.  Tried different types of auth.  Has always worked in the past, now just says unable to logon.

**Comment by MscrmTools** [comment]
I worked all day with XrmToolBox and dynamics online without any issue

**Comment by Mattw112** [comment]
That's great!  Wish I could ... still not working today. Anything to try?  I didn't change anything as far as I know.
[XrmToolBox_Connection-2019-06-27.log](https://github.com/MscrmTools/XrmToolBox/files/3335927/XrmToolBox_Connection-2019-06-27.log)

**Comment by rhamblin** [comment]
Same here. It was working up to last night now it's not working for me as well as my team member suddenly. I tried re-installing, using older versions etc. Nothing works

**Comment by MscrmTools** [comment]
So it must be something that changed on the authentication side... or do you know if April release was activated on orgs maybe?

**Comment by MscrmTools** [comment]
@Mattw112 this is an issue with your adfs

**Comment by rhamblin** [comment]
Any update on timeline of a fix? This is impacting completion of a time-critical fix

**Comment by MscrmTools** [comment]
There is no fix needed on XrmToolBox side, the problem is on your IT side

**Comment by ArvindBhat83** [comment]
Not sure what the IT can do as its D365 online.  I am still facing this issue. Neither able to connect through the plugin nor directly to the instance

**Comment by MscrmTools** [comment]
Azure Active Directory can be federated with your local AD and that can impact authentication process

**Comment by ArvindBhat83** [comment]
Thank you for the prompt response.  But direct login is working fine.  Even plugin registration tool works.  Issue is only with Xrmtookbox login.

**Comment by MscrmTools** [comment]
What if you use the SDK login control in XrmToolBox? Does it work?

**Comment by ArvindBhat83** [comment]
No, even that doesn’t work.  Gives me the below error.  By the way now even the plugin registration tool login is failing.  I am able to directly login to CRM though.  I’ll raise an internal ticket and see if it gets resolved.

You don't have permission to access any of the organizations in the Microsoft Dynamics CRM Online region that you specified. If you're not sure which region your organization resides in, choose "Don't know" for the CRM region and try again. Otherwise check with your CRM administrator.

**Comment by MscrmTools** [comment]
So, the connection using SDK Login control is totally handled by Microsoft SDK assemblies, nothing related to XrmToolBox. So if this does not work, then there is something wrong on your deployment.
You just need to understand that login to the web ui does not mean everything is correct. SDK calls multiple web services to authenticate and login.

**Comment by Prajgulhane** [comment]
Same problems with our organization also (D365 Online).
It is working with trial tenants/accounts of D365 online.

Thanks in advance.
