### ISSUE TITLE
Issue while importing in portal record mover

### ISSUE THREAD

**Issue by thiashton** [MscrmTools/XrmToolBox#874]
Below issue while importing records in portal record mover.
Please find the attached file for more info.

[XRM Issue.txt](https://github.com/MscrmTools/XrmToolBox/files/3335710/XRM.Issue.txt)

**Comment by MscrmTools** [comment]
Can you open an issue in the appropriate repository please?

**Comment by thiashton** [comment]
Sure, thanks
