### ISSUE TITLE
Plugin Store: Every time i click plugin, plugin list is refreshing

### ISSUE THREAD

**Issue by fuattatar** [MscrmTools/XrmToolBox#875]
Every time i click plugin, plugin list is refreshing
Version: 1.2019.6.33

![xrmtoolbox refresh issue](https://user-images.githubusercontent.com/2419809/60504580-84643f80-9cca-11e9-8637-0ae89379a615.gif)

**Comment by rappen** [comment]
Getting annoyed by this too... 👍

**Comment by MscrmTools** [comment]
Technically, it is not refreshed but repainted :)

But Ok, I will fix this
