### ISSUE TITLE
Can't connect to online CDS instance

### ISSUE THREAD

**Issue by Triangle333** [MscrmTools/XrmToolBox#876]
I can't connect to online CDS instance (v9.1.0.5825) with both Connection String & Connection Wizard approaches. Please see log file for both.

I'm getting "An error occurred when processing the security tokens in the message:Authorization failed" & "ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER"

I've checked my login\pass thru browser - works great. SDK Login Control also works for me but it is really cumbersome to use.

If there is an issue at my org side is there anything I can do to fix it?

[XrmToolBox_Connection-2019-07-03.log](https://github.com/MscrmTools/XrmToolBox/files/3353381/XrmToolBox_Connection-2019-07-03.log)

**Comment by MscrmTools** [comment]
What is your XrmToolBox version? I can connect to my CDS instances just fine

Is that a Dynamics 365 CE instance or a CDS only instance?

**Comment by Triangle333** [comment]
CDS only. Latest toolbox17:33, 3 July 2019, MscrmTools <notifications@github.com>:What is your XrmToolBox version? I can connect to my CDS instances just fine
Is that a Dynamics 365 CE instance or a CDS only instance?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
-- Sent from Yandex.Mail for mobile

**Comment by MscrmTools** [comment]
I just created a brand new CDS instance and I can connect find to it using connection wizard

**Comment by Triangle333** [comment]
Can this depend on region or user permissions? 21:17, 3 July 2019, MscrmTools <notifications@github.com>:I just created a brand new CDS instance and I can connect find to it using connection wizard

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
-- Sent from Yandex.Mail for mobile

**Comment by MscrmTools** [comment]
region : could not tell. I'm in EMEA
user permissions: of course, if you don't have access to the instance, XrmToolBox does not too. But if you can access the instance from web, you should be able to access it with XrmToolBox

**Comment by Triangle333** [comment]
I guess this is related to the company auth schema (smartcards & some domain security)
