### ISSUE TITLE
Plugin not getting updated automatically

### ISSUE THREAD

**Issue by piyushpaliwal** [MscrmTools/XrmToolBox#877]
Hi,
We are making modifications to our Plugin frequently and it never gets picked up by the job which updates the plugins. This issue was previously reported as well (#865) for the same plugin.

Nuget Link: [https://www.nuget.org/packages/MsDyn.Contrib.CloneFieldDefinitions](https://www.nuget.org/packages/MsDyn.Contrib.CloneFieldDefinitions
)
Can you please let us know what is the permanent fix for this issue.

**Comment by MscrmTools** [comment]
It seems there is too much versions which makes my workflow to reach the 2 minutes timeout.

**Comment by MscrmTools** [comment]
I updated it manually but you could maybe unlist some first versions
