### ISSUE TITLE
2015 - Spring - Copying Views to 'non-public' views throws error.

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#88]
In CRMSpring2015, if you attempt to copy a view to something other than a public view (such as attempting to copy the 'Active' view to the Quick Find or Advanced Find Default view) - CRM Reports that only public views can be activated/deactivated. - Not sure if this is a bug in CRM or if it's just a new requirement to account for in the XrmToolBox.

If you copy from Active to Inactive views, it works fine. It also works fine to copy to non-public views in the Winter 2015 and earlier versions.

**Comment by MscrmTools** [comment]
Thank you @mscottsewell, I will test it myself and try to find an alternative way to do it. If I can't, it seems it will be the end of this plugin...

**Comment by MscrmTools** [comment]
Found it!!
In CRM 2015 SP1, SetStateRequest, AssignRequest are replaced by a simple Update. As I was retrieving all attributes for the view and was changing just fetchxml and layoutxml, when update action occurs with statecode attributes included, it tries to perform a SetState, which is not possible for specific system views.
So, I will just fix the update to updates only fetchxml and layoutxml attributes

**Comment by daryllabar** [comment]
Wait, you can update the state and the owner with just a normal update?  Did they update the early binding to make those fields editable?

**Comment by MscrmTools** [comment]
Yes, they did!
Read the SDK preview on MSDN, you will be blasted by new features in the SDK (additional keys, upsert, transactionnal multiple requests and I forgot a lot of new stuff)

**Comment by MscrmTools** [comment]
Well, I didn't test the Early binding but I'm quite sure they did

The "yes" answer is surely for the normal update that can update owner and state
