### ISSUE TITLE
Plugins Store url finder too sensitive

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#883]
Sometimes it finds links that are not links.
Example:
![image](https://user-images.githubusercontent.com/2572253/62196773-e8882b00-b37e-11e9-985f-3bb58620ae44.png)

**Comment by MscrmTools** [comment]
weird, I use the following code to detect if the release notes is an url or not
```
if (Uri.TryCreate(releaseNotes, UriKind.Absolute, out _))
```
So it means that .Net Framework consider the content of this plugin as a valid url...

I guess I will add a check so it starts with "http"
