### ISSUE TITLE
Debugging plugin: System.Net.WebException

### ISSUE THREAD

**Issue by norriqkve** [MscrmTools/XrmToolBox#885]
I'm trying to debug my plugin but I keep bumping into the following error when the plugin starts.

![Capture](https://user-images.githubusercontent.com/26870014/62363948-a0a10980-b520-11e9-8a69-1a2e69cfbddb.PNG)

I've already found the cause of it... but I don't know how to fix it.

The form XrmToolBox.Forms.NewPluginVersion tries to load a picture from the XtbPlugin.LogoUrl.
Which, I assume, is taken from the XrmToolBox Plugin Store.
But this picture no longer exists due to an update of our company website.

https://www.xrmtoolbox.com/plugins/plugininfo/?id=604e6388-5007-e811-90cd-00155d6707f2

As you can see, the logo show a "broken" image.

I don't see any possibility to change this URL in the XrmToolBox. Would it be possible for you to modify this directly in the XrmToolBox Plugin Store?  It can be just wiped clear for now... so I can continue debugging :)

Additionally, as a permanent fix, I would suggest the 404 Not Found error is caught and handled on the form(use the default unkown.png image).

**Comment by MscrmTools** [comment]
Thank you for the feedback. I will implement the workaround in the Plugins Store... when I come back from holidays :)

**Comment by norriqkve** [comment]
Great, thanks.

I've managed to work around the issue but setting my Assembly version higher than what's in the Plugin Store. This prevents the NewPluginVersion form from popping up.
Additionally, after some more investigation, the logo is specified in the Nuspec file, which, I assume feeds the logo in the Plugin Store.  So once I publish a new package on Nuget with an existing logo, this issue will be resolved. 

But still would be nice to know that the 404 is caught on the form :)

**Comment by MscrmTools** [comment]
Issue seems to be fixed in current release
