### ISSUE TITLE
Unable to connect to organization

### ISSUE THREAD

**Issue by Prajgulhane** [MscrmTools/XrmToolBox#886]
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

![ToolBox_LoginIssue](https://user-images.githubusercontent.com/13052380/62921541-ab805780-bdc6-11e9-9012-242562d6ce1e.png)

**Comment by MscrmTools** [comment]
You did read the guidelines before posting this issue, didn’t you?

As for the issue, the message is quite clear : Authentication Failure
Something is wrong with your credentials or you don’t provide the appropriate values for your deployment

**Comment by Prajgulhane** [comment]
I did verified it, I am able to login on web through same credentials.

I now tried by checking 
![image](https://user-images.githubusercontent.com/13052380/62928092-7af3ea00-bdd5-11e9-88fd-b8715b91c552.png)

But still I am getting this.
![image](https://user-images.githubusercontent.com/13052380/62927978-3cf6c600-bdd5-11e9-88dc-dfba3a80af78.png)


Also I am trying by choosing existing connection which was working fine before 10-15 days

![image](https://user-images.githubusercontent.com/13052380/62928223-c1494900-bdd5-11e9-8a19-7f1bfda96034.png)

**Comment by Prajgulhane** [comment]
Hello XRMToolBox Team, 
Any solution on this?

Thanks in advance.

**Comment by Prajgulhane** [comment]
Able to login now by choosing Office 365.
