### ISSUE TITLE
Plugins Store disapproves of my date format

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#888]
Not sure I'm doing this right, but it seems XTB hates my scientifically decent date format:
![image](https://user-images.githubusercontent.com/2572253/63776757-4a867280-c8e2-11e9-91f0-83006cd91c57.png)

**Comment by MscrmTools** [comment]
Mine is correct. Date displayed in French format

**Comment by rappen** [comment]
Could it be that it is locked to the French format?
Or are you seeing something other than what I see? (I don't know how French looks...)

**Comment by MscrmTools** [comment]
The format you see is not the French one (which is jj/MM/AAAA).

So, not locked

**Comment by rappen** [comment]
Thanks. I'll investigate a bit more, closing if I find the solution/explanation.

**Comment by MscrmTools** [comment]
Did you find an explanation? maybe your local date settings?

**Comment by MscrmTools** [comment]
@rappen, anything new in this one ?

**Comment by rappen** [comment]
Nope. I give up!
