### ISSUE TITLE
Multiple IOrganizationService instances

### ISSUE THREAD

**Issue by CoreySutton** [MscrmTools/XrmToolBox#889]
Hi team,

### Multiple `IOrganizationService`'s to same organization
We are building a plugin that would highly benefit from multiple instances of `IOrganizationService` for multi-threading retrieval of records.

Are client credentials, connection string, or some other method of building multiple `IOrganizationService` exposed?

### Example
We are querying for user's personal views. This requires us to impersonate the personal view owner. With ~600 users, this means we send 600 impersonated `RetrieveMultiple` requests synchronously, changing who we are impersonating each request. We want these ~600 `RetrieveMultiple`'s to execute asynchronously, and need multiple instances of IOrganizationService to do this.

**Comment by daryllabar** [comment]
I pull the settings for the connection from the config in the Early bound Generator.  It's totally not supported, but it works fairly well.

**Comment by rappen** [comment]
Isn't this where your tool should inherit `MultipleConnectionsPluginControlBase` instead of `PluginControlBase`?

**Comment by daryllabar** [comment]
Isn't MultipleConnectionsPluginControlBase used to connect to different Orgs?  This is just to connect to the same org, a whole bunch of times.

**Comment by CoreySutton** [comment]
@daryllabar I copied your technique of pulling the connection settings from the config and it worked well. However I dropped the requirement for multiple IOrganizationService instances. Thanks for your help 😊

It would be great if XTB support creation of multiple IOrganizationService instances OOTB, but IMO it's a pretty low-priority request.

**Comment by MscrmTools** [comment]
Sorry I did not answer to this thread.
In your plugin, you have access to `ConnectionDetail`object that has a `GetCrmServiceClient(bool forceNewService = false)`method. If you put `true` for `forceNewService`, you should get another instance of `CrmServiceClient`

**Comment by CoreySutton** [comment]
Legend, thanks for the response. Will give that a try.
