### ISSUE TITLE
Web Resource Manager is not working in XRM Tool box. Error: Root element is missing.

### ISSUE THREAD

**Issue by SusritaMallick** [MscrmTools/XrmToolBox#890]
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

**Comment by daryllabar** [comment]
Please add details.  When does this happen?

**Comment by SusritaMallick** [comment]
While trying to open web resource manager from XRM toolbox, this error message is appearing. Please find the attached screenshot.
![web resource manager issue](https://user-images.githubusercontent.com/55030721/64518369-aa800e80-d30f-11e9-85f2-a4e51da4c519.PNG)

**Comment by MscrmTools** [comment]
You need to delete settings file for this plugin

**Comment by SusritaMallick** [comment]
Can you please let me know the path(How to delete the settings and from where)?
Thank you.

**Comment by rappen** [comment]
This shows how to find the working folder: https://youtu.be/EWP2X4eaJEY?t=270

**Comment by daryllabar** [comment]
@MscrmTools... Wondering if we should give an option to delete the file from the XTB?

**Comment by MscrmTools** [comment]
It’s a specific issue for a specific version of webresources manager. Shouldn’t happen anymore

**Comment by SusritaMallick** [comment]
Mentioned issue is resolved...Thank you all !!! :)
