### ISSUE TITLE
Guest users and XrmToolBox connection error

### ISSUE THREAD

**Issue by mwong128** [MscrmTools/XrmToolBox#895]
Hello All -

I have an issue with guest users not able to connect XrmToolBox to CRM.  Our internal users are able to connect with SDK login.  We've tried creating connection strings and SDK login for them, but they still get the following:

"Invalid Login Information: An unsecured or incorrectly secured fault was received from the other party.  See the inner FaultException for the fault code and detail. An unsecured or incorrectly secured fault was received from the other party .  See the inner FaultException for the fault code and detail. => Authentication FailureUnable to Login to Dynamics CRM Unable to Login to Dynamics CRM."

We are using MFA for accounts.

I'm hoping some one can provide guidance.

Thanks.

**Comment by JJGriffin** [comment]
I'm having the same issue currently, but I think this could be an SDK limitation as opposed to an XrmToolbox issue. According to [this forum post](https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/302859/crm-connection-string-for-azure-ad-b2b-accounts/889840), Azure AD B2C is not supported for connections made via the SDK. If someone is able to confirm this either way, that would be really appreciated! Thanks.

**Comment by MattB-msft** [comment]
this error: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail. An unsecured or incorrectly secured fault was received from the other party
infers your not using oAuth for authentication ( which is required for MFA).  if your using MFA, you cannot just use the user/password flow..  you also need to choose the login option that allows you to provide a client ID and a redirect URL to login.   

if your using the current version of the toolbox, I believe the XrmToolbox team did include the option to use our (microsoft) login control which *I think* is using our common ID's

**Comment by JJGriffin** [comment]
Hi @MattB-msft, thanks for the suggestion! The XrmToolbox does indeed have the login control you mentioned. In terms of the Client ID/Redirect URL, are these values obtained by setting up an application registration on Azure AD tenant? i.e.

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/walkthrough-register-app-azure-active-directory

**Comment by MattB-msft** [comment]
Yes.. that doc is a bit dated now, Azure is moving their application registration experience forward quickly.  
In text form.. 
1) goto the azure portal
2) goto Azure Active Directory
3) goto AppRegistration
4) click New Registration
5) Give it a name
6) Choose Native App
7) give it a redirect Uri ( this does not really matter for this type of login but a good thing to do is to app://<guid>) 
8) Register. 

Then copy out the "Application (client) ID" Guid, and note the redirect URI
once you have that you can plugin the AppID and Redirect in the login flow for XrmToolbox and it should let you in.    You will still need to use your user ID / PW with that.  

if you want to login via the application id, there are an additional set of steps that are required.

**Comment by mwong128** [comment]
Hi Matt- sorry for the delay in response.  Yes, your solution worked.  Thank you!
