### ISSUE TITLE
Error while registering a new plugin 

### ISSUE THREAD

**Issue by rajsekhar311** [MscrmTools/XrmToolBox#897]
Hi Team,
I developed a new plugin and tried to register the same, but I am getting the below error while registering. I couldn't understand the actual issue with my nuget package. Please let me know what would be actual issue. 

![2019-10-02_1607](https://user-images.githubusercontent.com/36291984/66051250-df5a3c80-e52e-11e9-80f5-7a6b89f0ee1f.png)

**Comment by rappen** [comment]
Only enter the Id of the package, which seems to be `XrmTools.BusinessUnitHierarchy`.

**Comment by rajsekhar311** [comment]
Yes, that works like charm. Thanks :)

**Comment by rappen** [comment]
👍
