### ISSUE TITLE
My plugin not listed in Plugin Store

### ISSUE THREAD

**Issue by norriqkve** [MscrmTools/XrmToolBox#898]
Hello,

Our plugin "Your User Security - Magnified" is not shown in the Plugin Store list.
On the portal(xrmtoolbox.com) it's properly show in My Plugins and even updated to the latest Nuget package.

What could be the reason for this?

Regards,
kve.

**Comment by MscrmTools** [comment]
The issue was in the size of the dataset returned when querying plugins and a limitation in XrmToolBox code.
Code has been updated and waiting for a new release, I raised the size of the dataset
