### ISSUE TITLE
Several plugin projects does not compile

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#9]
Following plugin projects 
```
MsCrmTools.MetadataDocumentGenerator
MsCrmTools.Translator
MsCrmTools.WebResourcesManager
```
has missing dependencies to:
```
Yahoo.Yui.Compressor
EcmaScript.NET.modified
GemBox.LicenseKey
```
that could not be resolved on most developers' workspaces being environment dependent, thus does not compile.

Pull request #8 partially is related to this issue, and tries to substitute missing libraries their copies from `NuGet`.

The same should be done for dependencies listed above.

**Comment by MscrmTools** [comment]
I can add Yahoo.Yui.Compressor and EcmaScript.NET.modified in an Assembly folder. But GemBox.LicenseKey is an assembly of my own that contains a private license key I can't share. So this one will never be added.

**Comment by shytikov** [comment]
Thank you!

I was suspicions about this `LicenseKey` assembly :)

BTW, I've added `XrmToolBox` as git submodule to the my plugin, so right now it would be build against most recent codebase without too much efforts.

**Comment by daryllabar** [comment]
I had the same problem shytikov, so I created a different build that skipped the projects with dependencies on the non standard dlls.  I believe it is in the solution file, so you can use that for doing your builds locally.

**Comment by shytikov** [comment]
I've just wire up projects to existing binaries in `packages` folder, so in case of version update `NuGet` will do all routine procedures.

**Comment by skfd** [comment]
GemBox dependency can be replaced with EPPlus. I did it for MsCrmTools.Translator once. Since XrmToolBox is on Github, I'll buckle up and do a pull request!

**Comment by shytikov** [comment]
GitHub made collaboration a lot easier indeed.

**Comment by MscrmTools** [comment]
Thank you @skfd ! Can't wait to see the updated tools

**Comment by MscrmTools** [comment]
Ok, let's close this issue as the configuration workaround works
