### ISSUE TITLE
Send messages to application statusbar from within plugin

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#90]
I think it would be really nice addition to `XTB` functionality if we will make informational statusbar, that could be controlled from the plugin. Possible application:

* Show small tips on usage;
* Showing warning messages, that does not block application work;
* Show completion percentage of execution (by showing progress bar, for example);

And many other possibilities, that every developer could discover by himself.

**Comment by MscrmTools** [comment]
I can work on that...

One decision to make is to choose what behavior to expose. You are talking about text and progress bar that are two different controls for a status bar.
So, should I expose a method that takes a statusbar control (can't remember exact name) already filed with data and overwrite existing control in statusbar or just text or expose multiple methods (one for text, one for progressbar)?

**Comment by shytikov** [comment]
I don't have clear vision for now, I rather have a need.

Moving progress bar if far more usable than dry numbers like `64 of 2386 operations completed` on yellow background... So basically I would appreciate some kind of framework to show progress to user. 

I think sometimes text also could be usable. For showing status of none blocking calls to `CRM`. Like when @rappen retrieves information about current entity attributes when we're using FetchXMLBuilder during design.

**Comment by MscrmTools** [comment]
Just for information, I have investigated on this topic... the problem is allowing plugins to access statusbar can be made through two possibilities:
- Making the statusbar a public singleton so it can be access anywhere. It seems not ideal to me
- Adding an event on IXrmToolBoxPluginControl interface to implement the possibility to pass a message back to main application, that will pass the message to the statusbar. But it will break each and every plugin that does not use PluginControlBase
Any thought?

**Comment by daryllabar** [comment]
Couldn't you create a new interface, that plugins could optionally implement, but the PluginControlBase would?

**Comment by MscrmTools** [comment]
Forgot about this one... Yes I can! :)

**Comment by MscrmTools** [comment]
As I'm not so fluent with all English terms, can you help me to find a name for this interface?

**Comment by daryllabar** [comment]
Guess I'm not so sure what the thing does...  This is just a plugin that defines a message that the main application is listening for, to call for updating the status bar message?

**Comment by MscrmTools** [comment]
yes it is

**Comment by daryllabar** [comment]
It's kind of weird since it actually isn't doing anything, but declaring what it wants.  Maybe IStatusBarNotifier?

**Comment by daryllabar** [comment]
What's the method name you're thinking it's going to implement?

**Comment by MscrmTools** [comment]
Something like SetStatusBarMessage(string message)

**Comment by daryllabar** [comment]
IStatuaBarMessager?

**Comment by MscrmTools** [comment]
Thank you, code is ready to be shipped with next release

**Comment by daryllabar** [comment]
That was supposed to read IStatusBarMessager... Hopefully you caught my type-o

**Comment by MscrmTools** [comment]
One final question : how does the statusbar should behave when moving from one tab to another? 1) Should the progress message and bar be displayed only when it is related to the selected tab or 2) should it be always visible ?
if 1), I need to pass the control information with the message so the statusbar knows what message to display depending on the selected tab
if 2) that means statusbar display progress info from another tab, and if selected tab update the message, it can become confusing

any thought?

**Comment by rappen** [comment]
Ideally, the main app should keep a dictionary of plugin/status to be able to switch between current statuses when switching plugin focus.
Or saving "last defined status" on the plugin instance itself.

**Comment by MscrmTools** [comment]
Thank you @rappen, it is my preferred approach too
