### ISSUE TITLE
Connection string with "AuthType=ClientSecret"

### ISSUE THREAD

**Issue by ltouro** [MscrmTools/XrmToolBox#900]
Have been trying to connect to a Dynamics365 instance using the following connection string, without success. 

```
AuthType=ClientSecret;url=https://orgName.crm.dynamics.com;ClientId=GUID;ClientSecret=RandomStringGeneratedAtAzurePortalOnAppRegistration
```

Would you please confirm if that kind of connection string is supported by XrmToolbox? Otherwise, I'm available to help implementing this feature on XrmToolbox.

**Comment by MscrmTools** [comment]
It is not yet supported as I need to review impact of using latest version of Xrm Tooling before adding it in XrmToolBox

**Comment by ltouro** [comment]
Thanks for the quick reply. Let me know if I can help with anything.
