### ISSUE TITLE
Connection string based on application user not working

### ISSUE THREAD

**Issue by kip-dk** [MscrmTools/XrmToolBox#902]
The following connection string is valid and can be used from code using the SDK to connect to CRM-Online.

For some reason xrmtools does not support this type of connectionstring, even though it has the option to simply enter a connectionstring when connecting to an organization:

AuthType=ClientSecret; url=https://mytenentname.crm4.dynamics.com; ClientId=my-application-id; ClientSecret=my-secret.

It is very easy to impl. if the tool is using the standard connector. Simply parse in the url to the CrmServiceClient.

**Comment by MscrmTools** [comment]
The point here is that XrmToolBox does not use latest sdk version yet and only latest one can handle clientId and client secret.

Support is coming

**Comment by kip-dk** [comment]
thanks for the quick feedback and headsup. i look forward.

**Comment by MscrmTools** [comment]
Should be good with latest version
