### ISSUE TITLE
Cannot open Opportunity Line in some plugins

### ISSUE THREAD

**Issue by chinhpv95** [MscrmTools/XrmToolBox#903]
Hi team,

I noticed that I cannot open Opportunity Line in plugin View Designer, View Layout Replicator. It throws error "Object reference not set to an instance of an object". Is this limitation of XRM ToolBox?

Thanks,
Chinh.

**Comment by rappen** [comment]
Possibly related issue: https://github.com/MscrmTools/MsCrmTools.Translator/issues/22

**Comment by MscrmTools** [comment]
Not related to XrmToolBox itself, certainly to each plugin or a platform change

**Comment by chinhpv95** [comment]
> Not related to XrmToolBox itself, certainly to each plugin or a platform change

Can you please fix it?

**Comment by MscrmTools** [comment]
Should be able to, but you need to create an issue for the plugin where you encountered the error
