### ISSUE TITLE
Cannot install any plugin

### ISSUE THREAD

**Issue by Louzy82** [MscrmTools/XrmToolBox#904]
When I try to install a new plugin from the plugins store get the same error every time:

'No connection could be made because the target machine actively refused it 152.199.23.209:443'

I really need this to work urgently to fix a problem we're having...

Thanks in advance for any help!!!

**Comment by rappen** [comment]
Got a nasty firewall at your company perhaps?
If you know what tool you need to install, you could actually find the package on NuGet and download it manually, unpack it, and add it to XTB.

A bit of a procedure, but it works, worst case.

@MscrmTools perhaps we should a a section to the docs with step-by-step instructions?

**Comment by ameed** [comment]
If that is really a firewall issue, as Jonas suspected, then probably spinup a minimal vm in azure to create a small playground environment of your own. This could help if you are using D365 online or onprem ifd.

This work around came in quite handy at a client where Citrix access was quite limited.

**Comment by MscrmTools** [comment]
@rappen, yes we can do that!

**Comment by Louzy82** [comment]
thanks, I found the plugin and could manually add it to the folder and it works.
