### ISSUE TITLE
Scroll Bar Issue

### ISSUE THREAD

**Issue by santoshCRM** [MscrmTools/XrmToolBox#909]
With version v1.2019.7.34 
Observe some scaling issue with plugins and tool also. No scroll bar showing for plugins who not fit in single screen.
![image](https://user-images.githubusercontent.com/23490088/69540154-fdcb3a00-0fab-11ea-8770-a745b590b103.png)

**Comment by rappen** [comment]
This is mos tlikely a design flaw in the tool you are running.
I would suggest creating an issue in the repository for that tool: https://github.com/mkalinov/DynamicsCrm_AttachmentsReversibleCopy/issues/new

**Comment by MscrmTools** [comment]
I second @rappen. The problem is on the tool itself that should follow winforms design best practices
