### ISSUE TITLE
Ribbon Workbench Error when trying to connect a Solution

### ISSUE THREAD

**Issue by IsabelSchauss** [MscrmTools/XrmToolBox#911]
Hi, 
somehow I cannot connect a Solution to Ribbon Workbench anymore. I Always receive a Script Error. 
![image](https://user-images.githubusercontent.com/58512325/70138063-aefa6000-168f-11ea-8bec-7e825a9c3e6e.png)
I tried to create a new solution and connect it but I get exactly the same error. 
Any ideas why this problem occurs?
Thanks!
Best Regards,
Isabel

**Comment by rappen** [comment]
When you have opened Ribbon Workbench, use this menu item to submit feedback on teh Ribbon Workbench:

![image](https://user-images.githubusercontent.com/2572253/70138329-55466580-1690-11ea-971f-f7991049fadb.png)

**Comment by IsabelSchauss** [comment]
Thanks, will do.
