### ISSUE TITLE
OAuth auth mechamism not working / XrmToolbox using outdated MscrmTools.XrmTools.Connection

### ISSUE THREAD

**Issue by peta** [MscrmTools/XrmToolBox#916]
In its latest XrmToolbox version it is not possible to logon using S2S/AppUser/OAuth mechanism. 

Error message: `ERROR REQUESTING Token FROM THE Authentication contextUnable to connect to CRM: Path cannot be the empty string or all whitespace".

After some live debugging of XrmToolbox I found out that the error is caused by an invalid token cache string value passed from `McTools.Xrm.Connection.ConnectionDetail.ConnectOAuth(...)` down to `Microsoft.Xrm.Tooling.Connector.CrmServiceClientTokenCache()`. 

It was introduced in [this commit](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/commit/0892c2003fe74eeda5830e41b8d36fcddf2205f2#diff-2bc6f1b5fc9e268360486425b6453535)  and has already been fixed by a contributor end of november last year [in here](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/commit/8204ce505cafced2e6d605abea695933e0db7683). But unfortunately even the current XrmToolbox prerelease references an [outdated version](https://github.com/MscrmTools/XrmToolBox/blob/6a3454a32625d35b3bc794780f8e6a1928f1aa64/XrmToolBox/packages.config#L13) of the `MscrmTools.Xrm.Connection` package, which  does not yet contain the fix from the commit mentioned above.

@MscrmTools  Any intents to update the deps and bring a new (pre-)release for this? I would consider it quite critical since S2S/App User scenarios raise in popularity.

**Comment by MscrmTools** [comment]
Hello, yes a new version is planned. I’m waiting for some feedback of my mvp peers about this new version before releasing it

**Comment by MscrmTools** [comment]
Should be good with latest release
