### ISSUE TITLE
Not able to connect to CRM 1.2020.2.36

### ISSUE THREAD

**Issue by Serjanya** [MscrmTools/XrmToolBox#919]
After update XTB to Version: 1.2020.2.36 I get some troubles to connect to my organization (on-premise, build 8.2.1.176) via AD.

```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	05.02.2020 21:20:57  Initialize CRM connection Started - AuthType: AD
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	05.02.2020 21:20:57  Discovery URI is = https://______/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	05.02.2020 21:20:57  DiscoverOrganizations - Initializing Discovery Server Object with https://______/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	05.02.2020 21:20:57  DiscoverOrganizations - attempting to connect to CRM server @ https://______/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	05.02.2020 21:21:18  Unable to login to Dynamics CRM, Error was : Metadata contains a reference that cannot be resolved: 'https://______/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9'.
Source	: System.ServiceModel
Method	: Retrieve
Date	: 05.02.2020
Time	: 21:21:18
Error	: Metadata contains a reference that cannot be resolved: 'https://______/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9'.
Stack Trace	: at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, NetworkCredential networkCredential, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: System
Method	: GetResponse
Date	: 05.02.2020
Time	: 21:21:18
Error	: Unable to connect to the remote server
Stack Trace	: at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
======================================================================================================================
Inner Exception Level 2	: 
Source	: System
Method	: DoConnect
Date	: 05.02.2020
Time	: 21:21:18
Error	: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond XXX.XXX.XXX.XXX:443
Stack Trace	: at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	05.02.2020 21:21:18  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	05.02.2020 21:21:18  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 05.02.2020
Time	: 21:21:18
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================
```

**Comment by Serjanya** [comment]
Got it. Reason is XTB remove port from connection.

URL from log:
`https://myorg.com/XRMServices/2011/Discovery.svc` - not available 
Correct URL:
`https://myorg.com:8080/XRMServices/2011/Discovery.svc` - it's Ok

**Comment by MscrmTools** [comment]
Thanks for finding the issue.
I will check the code to find out where the issue is

**Comment by irah2008** [comment]
Something wrong with the new release, when i give 443 in port the url becomes http & when i give 80 url becomes https (This is for on-premises). Online right after connection is established Toolbox closes itself (Online environment with 2020 wave1 applied)

**Comment by halfr** [comment]
There seems to be a fundamental problem with Connections in the new release.

After updating to the new release and re-creating my connection (and settings) against my online instance, the connection is validated but the XTB terminates right after opening the connection.

**Comment by MscrmTools** [comment]
I will Check this afternoon but I already used the new version without any issue

**Comment by MscrmTools** [comment]
@irah2008, I do not reproduce the port issue

@halfr can you precise if there is MFA activated on your user account?

**Comment by MscrmTools** [comment]
@irah2008 I can also connect to online without XrmToolBox crash

Can you test with a fresh installation?

**Comment by Serjanya** [comment]
Find solution.
You should fix and save tag value `<ServerName>`
Add domain and port in **ConnectionsList.Default.xml**:
from  `<ServerName>yourserv</ServerName>`
to `<ServerName>yourserv.yourdomain.com:8080</ServerName>`

**Comment by halfr** [comment]
@MscrmTools Tested with Fresh update and both a user account having MFA and a user account w/o MFA from inside federated AD.

**EventLog Application Error:** (app path obfuscated ---)

>Name der fehlerhaften Anwendung: XrmToolBox.exe, Version: 1.2020.2.36, Zeitstempel: 0x5e384b39
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.18362.535, Zeitstempel: 0x50cc8d5a
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000003a839
ID des fehlerhaften Prozesses: 0xe178
Startzeit der fehlerhaften Anwendung: 0x01d5dcfeec835348
Pfad der fehlerhaften Anwendung: C:\Users\---\XrmToolBox.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 02ff3961-c505-4727-9981-4c56f79ca17e
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

**EventLog .Net Runtime Exception:**

>Anwendung: XrmToolBox.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Exception
   bei McTools.Xrm.Connection.ConnectionManager.LoadConnectionsList()
   bei McTools.Xrm.Connection.ConnectionManager.fsw_Changed(System.Object, System.IO.FileSystemEventArgs)
   bei System.IO.FileSystemWatcher.OnChanged(System.IO.FileSystemEventArgs)
   bei System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32, UInt32, System.Threading.NativeOverlapped*)
   bei System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

However Connections for both users work fine on another developer machine.

Maybe a .Net Framework Version issue on my Client machine?

**Comment by irah2008** [comment]
> @irah2008 I can also connect to online without XrmToolBox crash
> 
> Can you test with a fresh installation?

Fresh installation simulates similar behaviour. On premise connection now just closes the window without much error.

Possible workaround to revert to previous release which works fine

**Comment by MscrmTools** [comment]
I will have access to an onpremise deployment (CRM 8.2) today. Will do some additional tests.

Btw, asked some MVPs to perform tests with latest version and no one reported connection issues

**Comment by MscrmTools** [comment]
Ok, I found one issue that leads to NullReferenceException error when trying to connect to OnPremise. Is that the issue you are seeing?

**Comment by Serjanya** [comment]
@MscrmTools did you manage to find something about erasing port number from connection?

[Fix connection settings](https://github.com/MscrmTools/XrmToolBox/issues/919#issuecomment-582943614) every time tires

**Comment by MscrmTools** [comment]
@Serjanya Yes! found it! Fix is on its way... Still waiting to find info on XrmToolBox crash when connecting before releasing a new version

**Comment by MscrmTools** [comment]
This is the fixed connection assemblies. It should fix onPremise issues 
[McTools.Xrm.Connection.WinForms.zip](https://github.com/MscrmTools/XrmToolBox/files/4171714/McTools.Xrm.Connection.WinForms.zip)

**Comment by Serjanya** [comment]
> This is the fixed connection assemblies. It should fix onPremise issues
> [McTools.Xrm.Connection.WinForms.zip](https://github.com/MscrmTools/XrmToolBox/files/4171714/McTools.Xrm.Connection.WinForms.zip)

Thank you, everything works well!

**Comment by MscrmTools** [comment]
> > This is the fixed connection assemblies. It should fix onPremise issues
> > [McTools.Xrm.Connection.WinForms.zip](https://github.com/MscrmTools/XrmToolBox/files/4171714/McTools.Xrm.Connection.WinForms.zip)
> 
> Thank you, everything works well!

Glad it's fixed.

Now I need more info from other users having trouble
