### ISSUE TITLE
Connections to Dynamics 365 broken

### ISSUE THREAD

**Issue by outreachcanada** [MscrmTools/XrmToolBox#920]
Since upgrading to this version of the XrmToolBox ALL of my previous connecitons to Dynamics no longer work AND I cannot create a new connection.
Is there a fix? 

--

- XTB Version: 1.2020.2.36

**Comment by MscrmTools** [comment]
What is the behavior? Is there any error message?

**Comment by MscrmTools** [comment]
Quick workaround is to download again the previous version

**Comment by MscrmTools** [comment]
@outreachcanada, can you explain your scenario?
OnPremise or Online?

**Comment by sundvl** [comment]
I am also experiencing issues signing into online version after upgrading to version 1.2020.2.36.  No error is captured in the log file, however, I was able to capture this stack trace when attempting to recreate the connection

![XrmToolboxError](https://user-images.githubusercontent.com/60792275/74053526-3ec2d000-4999-11ea-86d0-6bcff7d2e8fb.jpg)

**Comment by MscrmTools** [comment]
This error seems to indicate that Dynamics Sdk versions are incorrect.
Can you try a fresh installation of the latest version and tell me if the issue still occurs?

**Comment by sundvl** [comment]
That screen shot was taken after trying a fresh installation.

**Comment by LiftEmotion** [comment]
I have also problems loggin in to my crm after the update - even old version and on other pc's (clean install of old version)  no connection possible. See message below.

![afbeelding](https://user-images.githubusercontent.com/50330173/74321490-a35ba180-4d82-11ea-83a7-7e404edc18b9.png)
When I look in the log I see the following 
![afbeelding](https://user-images.githubusercontent.com/50330173/74321588-d00fb900-4d82-11ea-93b1-8a872cfab0c8.png)

Is there a fix - it worked like a charme until today.
Please help

**Comment by MscrmTools** [comment]
If the problem occurs also with the old version, then the problem is unlikely in XrmToolBox but in your org.
Can you create a new connection with the old version?

**Comment by LiftEmotion** [comment]
Addition on my message earlier...
On my own pc the error looks a bit different - there is states something about the sdk version see below

![afbeelding](https://user-images.githubusercontent.com/50330173/74323180-6b099280-4d85-11ea-97f4-6081374fa0aa.png)
We have an on-premise - version 1612 (8.2.2.112)

**Comment by LiftEmotion** [comment]
I have some result on the other PC - clean install of version 6.25 and used the old list of connections - succesfully logged in...

**Comment by MscrmTools** [comment]
The error message seems to tell it cannot find the hostname

**Comment by MscrmTools** [comment]
@sundvl can you confirm if you have Early Bound Generator installed in XrmToolBox? If so, can you remove it (the plugin itself and its folder) and try again to connect?

**Comment by sundvl** [comment]
I do have Early Bound Generator installed.  I removed the plugin (and folder).  No luck.  Same error.

**Comment by MscrmTools** [comment]
Did you remove the EBG folder too?

**Comment by sundvl** [comment]
Yes, I did.  I tried a clean install of the new release (1.2020.2.37) and still have the same issue.  I have now rolled back to 1.2019.11.35 where the connection works without errors.

**Comment by MscrmTools** [comment]
Ok, so the issue is because Microsoft.Xrm.Sdk assembly is in your GAC. Remove it from the GAC and you will be good
