### ISSUE TITLE
Connection highlight is not displayed, empty gray bar is shown in its place.

### ISSUE THREAD

**Issue by aovar** [MscrmTools/XrmToolBox#921]
Version 1.2020.2.36 (latest)

Where there was the connection highlight, now it displays a gray, empty horizontal bar.

This happens with all plugins.

I can configure and save the connection (including the highlight settings) with no issues.

Here is a screenshot of the Plugin Registration tool, above the toolbar the gray area is where the highlight was before (I blanked out the name of the active connection and the assembly names):
![image](https://user-images.githubusercontent.com/35955914/74136141-dcaed880-4bed-11ea-917d-e2941a3ecdbe.png)

**Comment by MscrmTools** [comment]
Thank you for reporting this. 
Fix is on its way

**Comment by aovar** [comment]
It looks like the current (latest, just updated now) version is not picking up on former highlight settings, I tried with one and I had to reconfigure it for the highlight to show.
