### ISSUE TITLE
Close Tool Silently doesn't stick

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#922]
It immediately forgets the setting.

![XTB settings error](https://user-images.githubusercontent.com/2572253/74193241-57f8a480-4c57-11ea-8be8-bf0677e27541.gif)

---
- Deployment: Online
- DB Version: 9.1.0.12935
- XTB Version: 1.2020.2.36

**Comment by MscrmTools** [comment]
Fix on its way
