### ISSUE TITLE
XTB backup under ProgramData

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#923]
Just out of pure curiosity, how come the backup folder created during update is placed under ProgramData, when all other files are under AppData?

---
- XTB Version: 1.2020.2.37

**Comment by MscrmTools** [comment]
Ah ah! Just noticed it too when updating

**Comment by rappen** [comment]
I've noticed it every time I've done my presentation on the plumbing of XTB.... 😉

**Comment by MscrmTools** [comment]
Ah, I guess this is because the roaming profile (or where XTB stores its file) is the folder to backup. So I don't want to backup the backup
