### ISSUE TITLE
new xrm dynamics portal - cant submit a rating for a tool.

### ISSUE THREAD

**Issue by MaxineHarwood** [MscrmTools/XrmToolBox#926]
tried to rate a great plugin but i get an error - attribute title cannot be NULL. there is no title displayed on the rating page. screenshot attached
![Picture1](https://user-images.githubusercontent.com/36911507/74578523-ff236600-4fe0-11ea-9aae-9b4d88f733e0.png)

---
- Deployment: Online
- DB Version: 9.1.0.13225
- XTB Version: 1.2020.2.36

**Comment by MscrmTools** [comment]
I guess the problem is on one of the version of your Nuget package.
A title node has to be null.
If you have older and intermediate version, please un list them to keep only the version you want to submit

**Comment by MscrmTools** [comment]
I did not reproduce.
Can you try again
