### ISSUE TITLE
Connection removed FQDN

### ISSUE THREAD

**Issue by AlGu1** [MscrmTools/XrmToolBox#930]
On every connection to OnPremise CRM 365 v9, the "ConnectionsList.Default.xml" lost the FQDN in XML Node "OrganizationDataServiceUrl" and "WebApplicationUrl". After the Connection ist Close, we must chnage the File bevor reconnect :-(

**Comment by MscrmTools** [comment]
Can you confirm you are using latest version?
I will check this

**Comment by AlGu1** [comment]
![image](https://user-images.githubusercontent.com/18306111/75633782-4a0bc300-5c08-11ea-8f2c-68a5e3d6f626.png)

**Comment by MscrmTools** [comment]
The problem is with your OnPremise configuration in Deployment Manager. These url are taken from there. 
Update your Deployment manager properties to includes FQDN here
