### ISSUE TITLE
Opened tools are not displayed

### ISSUE THREAD

**Issue by xiaohtian** [MscrmTools/XrmToolBox#931]
[Write your comment/feedback/issue here]

---
- XTB Version: 1.2020.2.37

![image](https://user-images.githubusercontent.com/9548514/75965009-26e05c80-5f03-11ea-9d7a-c50e0e0059a2.png)

When I open the tool, it doesn't show up in the main window.

But when I drag this tab, it shows.

![image](https://user-images.githubusercontent.com/9548514/75965318-97877900-5f03-11ea-8589-74d8d38fa88f.png)

My OS  is Win 10.

**Comment by MscrmTools** [comment]
It seems to be an issue with, what I see in your screenshot, a high DPI monitor.
What is then size and resolution of your screen?

**Comment by xiaohtian** [comment]
My resolution is 1920 × 1080

**Comment by xiaohtian** [comment]
Thank for your response. I try change resolution to 1366×768. This problem still exists.
![image](https://user-images.githubusercontent.com/9548514/76076534-06370600-5fda-11ea-8c3c-ff04c3a08212.png)

**Comment by MscrmTools** [comment]
AFAIK, this is more an issue with the text density than the resolution.
I have had this issue in the past during XrmToolBox development but not when using it

**Comment by MscrmTools** [comment]
@xiaohtian did you try to change the text density?

**Comment by xiaohtian** [comment]
Sorry, the reply is late. I use the default settings.

**Comment by xiaohtian** [comment]
Hi,I found that this problem only appears in the Chinese operating system. I use the English system to run without this problem.

**Comment by MscrmTools** [comment]
ok, as this is really specific and I won't be able to fix anything by myself, I'm closing this issue.
