### ISSUE TITLE
No Tool Display after Installation

### ISSUE THREAD

**Issue by kongwilson99** [MscrmTools/XrmToolBox#932]
List of tool installed, but there is nothing shown on the tool tab.
Is there anything wrong with my installation?
![image](https://user-images.githubusercontent.com/58587628/77147895-524d7480-6ac9-11ea-93d2-3aad3ad2fcaf.png)

**Comment by MscrmTools** [comment]
Can you double click on tools tab to pop it out? Are tools visible?

**Comment by kongwilson99** [comment]
yes, double click works....forgive my dummy question. Thanks.

**Comment by MscrmTools** [comment]
It’s not a dummy question. There is some issue with some screen resolutions

**Comment by kongwilson99** [comment]
Oh, I see it.
I just think this may be something I don’t know how to use XRMTool.

Best Regards,
Wilson Kong

________________________________
