### ISSUE TITLE
Connection to 365CE Online Failed for all environments - v1.2020.2.37

### ISSUE THREAD

**Issue by Skepertie** [MscrmTools/XrmToolBox#934]
I had the XRMToolbox running for a while successfully and recently upgraded succesfully. But since last Friday I can't connect anymore to any environment using existing or new connections. The same credentials are used when logging in via the browser and with success.
CE - Online
When setting up new Connections I am using the Connection Wizard

![XRM Connection Failed](https://user-images.githubusercontent.com/62556291/77334024-8f617300-6d24-11ea-8f6c-ec480e7526fd.JPG)

When checking the log folder it is saying the following
![XRM StackTrace](https://user-images.githubusercontent.com/62556291/77334566-465dee80-6d25-11ea-9df3-f4914b8cecf8.JPG)

**Comment by MscrmTools** [comment]
Maybe something change regarding the federation of your local active directory with azure AD?
Anyway, since it had worked, something must have changed on your side. 
I have no issue connecting to my online environments

**Comment by Skepertie** [comment]
That was my first thought as well, but I do have a colleague that is connected to our network the same way, who runs a 2018 version of XRMToolbox which still can connect to our environments.
Is there a place where you can download a previous version ?

**Comment by MscrmTools** [comment]
Yes on GitHub release. Do not take a pre release

**Comment by Skepertie** [comment]
An older version version is also not working unfortunately for me, any thoughts what else to check or perhaps verify with our Infra Department ?
I really need this to work and I am bit stuck what to check with the Infra Department

**Comment by MscrmTools** [comment]
Unfortunately, it’s very difficult for me to give you hints on what to check...
Maybe MFA has been enabled on your account? Or federation with azure AD has been changed?

**Comment by MscrmTools** [comment]
@skepertie are you still experiencing this issue?

**Comment by Skepertie** [comment]
I have managed to found the root cause of this.
Currently I was using the basic authentication for logging in.
This has always worked, but now our Infra departments has changed a policy where they explicitly block connections of this type to MS cloud services for Element AD accounts:
