### ISSUE TITLE
XRMToolbox keeps closing with errors in the event viewer

### ISSUE THREAD

**Issue by naveedmcp** [MscrmTools/XrmToolBox#935]
[Write your comment/feedback/issue here]

---
- XTB Version: 1.2020.2.37
--

Faulting application name: XrmToolBox.exe, version: 1.2020.2.37, time stamp: 0x5e42e1f9
Faulting module name: KERNELBASE.dll, version: 10.0.17134.1365, time stamp: 0x32d59a64
Exception code: 0xe0434352
Fault offset: 0x000000000003a388
Faulting process id: 0x5ef8
Faulting application start time: 0x01d6020497ad1c42
Faulting application path: C:\Project Work\D365\XrmToolbox\XrmToolBox.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: c40d79ab-cc22-42b8-835e-dcd50f75ada1
Faulting package full name: 
Faulting package-relative application ID: 

----

Application: XrmToolBox.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at McTools.Xrm.Connection.ConnectionManager.LoadConnectionsList()
   at McTools.Xrm.Connection.ConnectionManager.fsw_Changed(System.Object, System.IO.FileSystemEventArgs)
   at System.IO.FileSystemWatcher.OnChanged(System.IO.FileSystemEventArgs)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by naveedmcp** [comment]
@jamesnovak @skfd @shytikov @macacq

**Comment by jamesnovak** [comment]
is this a recent upgrade from an older version?  i think it was v1.2020.2.36 (https://www.xrmtoolbox.com/releases/xrmtoolbox-v1.2020.2.36/) versions ago that significant changes were made to the connections, including a change in how the file is structured.  The release notes indicate that you should recreate your connections. 
I suggest that you remove the connections folder and try loading the connections

**Comment by MscrmTools** [comment]
@naveedmcp, does it still occur?

**Comment by MscrmTools** [comment]
No answer... closing this issue.
Can be reopened if needed
