### ISSUE TITLE
MRU in Taskbar

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#936]
How awesome would it be to get the MRU list available with right click in the taskbar like so many other apps have?
Really awesome!

![image](https://user-images.githubusercontent.com/2572253/77912507-fd60e980-7292-11ea-9e9e-61fa06d18445.png)

---
- XTB Version: 1.2020.2.37

**Comment by MscrmTools** [comment]
Is that even possible? 😅

**Comment by rappen** [comment]
Should be.... 🤔
https://docs.microsoft.com/en-us/windows/win32/shell/taskbar-extensions#jump-lists

**Comment by MscrmTools** [comment]
From what I read, it’s not available directly in winforms

**Comment by rappen** [comment]
😢

**Comment by MscrmTools** [comment]
This exists for WPF only.
If we wanted this on winforms, we should use an old package from 2009. 
Not sure I want to do this
