### ISSUE TITLE
D365 - XrmToolBox 2020 returns an error when establishing a new connection

### ISSUE THREAD

**Issue by khawla-d** [MscrmTools/XrmToolBox#938]
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

**Comment by khawla-d** [comment]
Hi,

I am using CRM 365 Online (with 2FA) and after an upgrade of my Xrmtoolbox 2018 to 2020 I am getting below error when trying to connect to my organisation. I don't have this problem in the old version 2018. I really need to use the 2020 version.
<img width="432" alt="connectionErrorXrmToolBox" src="https://user-images.githubusercontent.com/64418525/80377919-31ccc300-889c-11ea-9aa9-59e9d375f50f.PNG">

Thank you,

**Comment by MscrmTools** [comment]
This is a known issue that is caused by the fact you have old CRM sdk assemblies in your computer global assembly cache.
Remove them and you will be good

**Comment by khawla-d** [comment]
Problem solved ! Thank you :)
