### ISSUE TITLE
Cannot run latest version

### ISSUE THREAD

**Issue by zenecamickeyd** [MscrmTools/XrmToolBox#939]
Today I installed v1.2020.4.38 and now the application crashes with the error:  
> Object reference not set to an instance of an object.

I delete that installation and installed the earlier version v1.2020.2.37 but that did not solve the issue.

[XRM Toolbox Error.docx](https://github.com/MscrmTools/XrmToolBox/files/4540374/XRM.Toolbox.Error.docx)

**Comment by MscrmTools** [comment]
There was an issue with a new tool. But this should be fixed now

**Comment by zenecamickeyd** [comment]
Was the fix introduced between this morning and now?  So do I just download 1.2020.4.38 again?

**Comment by MscrmTools** [comment]
There is no fix. The issue was with a new tool definition in XrmToolBox portal. I fixed the tool definition and the error disappear.
And yes, it was this morning (French time)

**Comment by zenecamickeyd** [comment]
Thanks for your help.  I downloaded the latest version again and it's all working again.

**Comment by zenecamickeyd** [comment]
Thanks for your help. I downloaded the latest version again and it's all working again.
