### ISSUE TITLE
Error while updating site map...

### ISSUE THREAD

**Issue by KarstenWirl** [MscrmTools/XrmToolBox#94]
![error_updatesitemap](https://cloud.githubusercontent.com/assets/11767749/6959858/5473b5fa-d91d-11e4-99e0-35ab4f0ac184.PNG)

**Comment by MscrmTools** [comment]
It seems you put a space in the Id value.
Try without space in the id

**Comment by KarstenWirl** [comment]
Thanks for the quick reply and you're right. Spaces are not a good idea for an id.

Have a nice day!
