### ISSUE TITLE
XRMToolbox will not start

### ISSUE THREAD

**Issue by HETY-GER** [MscrmTools/XrmToolBox#940]
Hi to all,
in Advance I would like to apologize for any mistakes or misunderstandable Terms I use as I am absolutely new to all this.
My Company Notebook I am using has WIN10 installed, also Microsoft.NET Framework 4.8.
I have downloaded the XRMToolbox Installation zip-file, unblocked it (as explained on the xrmtoolbox Website) and relocated the zip-file to a Folder on my personal Desktop. I unziped the file and tried to start the xrmtoolbox.
But as soon as I doubleclick on the Icon, I receive an error message and I am not able to continue.
Even our IT People with Administration Rights are not able to start the Toolbox.
I did have an older Version (from 2018) which worked fine but many of the tools will not work anymore.
Coudl anyone of you give me a hint?

Thanx in advance

**Comment by MscrmTools** [comment]
Is there any error in event viewer ?

**Comment by HETY-GER** [comment]
Unfortunately in German only:

![image](https://user-images.githubusercontent.com/64462944/80469180-80339d80-8940-11ea-82bb-bdcf004d9346.png)

**Comment by HETY-GER** [comment]
As a translation it would be approx.:
"The mentioned device, path or file can  not be reached. You do not have the neccessary rights to choose that element." (Bad translation , sorry)

**Comment by HETY-GER** [comment]
By the way, I have tried several versions of the toolbox now and v!.2019.2.32 does work. All newer versions create the same error message.

**Comment by MscrmTools** [comment]
Maybe something related to SDK assemblies
But I could not tell with just that error message
