### ISSUE TITLE
Early Bound Generator issue V1.2020.5.11

### ISSUE THREAD

**Issue by clintolin** [MscrmTools/XrmToolBox#946]
I just updated EBG to 1.2020.5.11 and unfortunately just get the error: System.InvalidOperationException: There is an error in XML document (1, 40). ---> System.InvalidOperationException: <Config xmlns=''> was not expected.

Not sure how to get this message straight through to Daryl, but I would hope we can get an update soon as we highly depend on this tool.

thanks!
clint

**Comment by MscrmTools** [comment]
Hi.
This is not the appropriate repository.

Can you post the issue in early bound generator repository (https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools)?

Thanks

**Comment by clintolin** [comment]
Sure will. It would be awesome if we had some sort of link to the correct location within XRMToolbox. Jus saying...

**Comment by daryllabar** [comment]
There is.  It's under the help menu for the tool vs for the XTB as a whole

**Comment by clintolin** [comment]
ahhh.... but the tool won't open in this case :-) It's fine. I found you via the link they gave me. I bookmarked it this time.
