### ISSUE TITLE
Allow passing context from source tool to duplicated tool

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/XrmToolBox#949]
Following @rappen request on Twitter, XrmToolBox should be able to pass context/state of a source tool instance to a duplicated tool instance.

**Comment by MscrmTools** [comment]
@rappen, does the following new interface seems sufficient to you?
`IDuplicableTool` with methods `object GetState()` and `void ApplyState(object state)`

**Comment by rappen** [comment]
So.... I would implement the `GetState` method to return `MyToolCustomStateObject` and this is called before duplicating, and implement `ApplyState` that if called with `MyToolCustomStateObject` I could restore whatever state it got, right?
I kinda like it :)

**Comment by MscrmTools** [comment]
You did understand.

**Comment by MscrmTools** [comment]
as for `IMessageBusHost` it won't know what tool instance to target if many of them are opened

**Comment by rappen** [comment]
👍
In that case my only objection is that the interface should be called `IDuplicatableTool` instead 😊

**Comment by MscrmTools** [comment]
My poor english...

**Comment by MscrmTools** [comment]
Implemented!

**Comment by daryllabar** [comment]
> My poor english...

I'm picturing a little mythical creature called English that is just crying in a corner somewhere...

**Comment by MscrmTools** [comment]
I knew I was doing a mistake here
