### ISSUE TITLE
4 plugins not updating no matter how many times you try

### ISSUE THREAD

**Issue by DerekHAu** [MscrmTools/XrmToolBox#951]
There are 4 tool updates that have consistently come up as requiring update, but never actually complete their update. How do we fix this (or can we allow certain tools to be completely ignored)?

![image](https://user-images.githubusercontent.com/37601628/82291326-20cf2780-99ec-11ea-8cda-1e61189ad60c.png)

---
- Deployment: Online
- DB Version: 9.1.0.16532
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.5.39

**Comment by rappen** [comment]
This means the author has composed packages of "Latest Version" containing tool dlls of "Installed Version".
Please submit issues for these tools specifically.

**Comment by MscrmTools** [comment]
It seems to be the same author. I will also contact him directly so that he can update packages

**Comment by DerekHAu** [comment]
Yeah we noticed it was all one author after we posted... thanks for following up... I told my colleague you always seemed very involved/responsive :)

**Comment by MscrmTools** [comment]
Developer contacted. Closing the issue for now

**Comment by MscrmTools** [comment]
Ok, developer answered but he does not have time to update his tools for now. 
I will reject them so that this is not an issue anymore
