### ISSUE TITLE
Using xrmtoolbox connect to D365 of China Region

### ISSUE THREAD

**Issue by GHSunnyGH** [MscrmTools/XrmToolBox#955]
Does xrmtoolbox support connect to D365 of China Region?
I use the XrmToolbox version of 1.2020.5.39,  and choost 'SDK Login control', then choose the region of 'China', but it seems still find the organizations from CDS Global, not CDS China.

**Comment by MscrmTools** [comment]
Sdk login control method is from official CRM SDK. 
If this control does not work, then there is nothing I can do...
Please try another connection method

**Comment by MscrmTools** [comment]
any news?

**Comment by GHSunnyGH** [comment]
Not worked yet.
![0](https://user-images.githubusercontent.com/58726489/97256777-ec8b4d00-184e-11eb-9692-f17b1bb40bf2.JPG)

**Comment by MscrmTools** [comment]
Can you try latest version of XrmToolBox?

**Comment by GHSunnyGH** [comment]
I used the latest version 1.2020.10.41, and also tried the connection method of 'OAuth/MFA',
error says ' This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. '.

**Comment by MscrmTools** [comment]
Ok, I may have missed something when shipping latest version of XrmToolBox.
I just released a new version of connection controls.
Normally, when running again XrmToolBox, you should be prompted to update connection assemblies. 
![image](https://user-images.githubusercontent.com/10774317/97279742-aa0c4500-183b-11eb-92e2-4150de2d6436.png)

Can you try? and tell me if you were prompted to update them?

**Comment by GHSunnyGH** [comment]
I clicked the 'Update Now', and then the tool was restarted. I tried to connect to  D365 of China Region again, same error as before.

**Comment by MscrmTools** [comment]
What if you don't precise the region?

**Comment by GHSunnyGH** [comment]
Even if I don't precise the region, the same error happened.
![0](https://user-images.githubusercontent.com/58726489/97418643-03f83200-1944-11eb-97fc-793052212992.JPG)

**Comment by MscrmTools** [comment]
Are you sure your user account has license and/or app shared?

**Comment by GHSunnyGH** [comment]
yes, my account can access D365 Of China region via IE, C# code in visual studio, and PluginRegistration tool .

**Comment by GHSunnyGH** [comment]
About PluginRegistration tool,  I followed the following step to skip calling the default discovery service, then I can connect to D365 Of China region, Is there a similar method for XrmToolBox?

https://community.dynamics.com/365/f/dynamics-365-general-forum/369550/dynamics-365-plugin-registration-tool-gives-permission-error/977534
====================
Even-though you have system admin access you might get this error. This is because sometimes CRM Discovery service is not able to resolve the region correctly and throws this error message. To resolve this issue follow the below steps:

Open PluginRegistration.exe.config file
Look for appSettings, if you don' find one then add the below tag after system.diagnostics
<appSettings>
    <add key="SkipDiscovery" value="True" />
</appSettings>
This will skip calling the default discovery service and will prompt you to enter your instance URL.
=============================================

**Comment by MscrmTools** [comment]
Yes you can test this by creating an XrmToolBox.exe.config file (if not exists, should look like below) and add the same XML
 
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
  </startup>
  <runtime>
    <loadFromRemoteSources enabled="true" />
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Tooling.Connector" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.8.0" newVersion="5.2.8.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.29.0.1078" newVersion="2.29.0.1078" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="McTools.Xrm.Connection" publicKeyToken="96037217801d9658" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2017.4.13" newVersion="1.2017.4.13" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Sdk" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Crm.Sdk.Proxy" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Web.XmlTransform" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.0.34420" newVersion="3.0.0.34420" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Tooling.CrmConnectControl" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true">
      <proxy autoDetect="True" bypassonlocal="False" />
    </defaultProxy>
  </system.net>
  <system.diagnostics>
    <trace autoflush="true" />
    <sources>
      <source name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" switchName="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="console" type="System.Diagnostics.DefaultTraceListener" />
          <remove name="Default" />
          <add name="CustomListener" />
        </listeners>
      </source>
    </sources>
    <switches>
      <!--
            Possible values for switches: Off, Error, Warning, Info, Verbose
                Verbose:    includes Error, Warning, Info, Trace levels
                Info:       includes Error, Warning, Info levels
                Warning:    includes Error, Warning levels
                Error:      includes Error level
        -->
      <add name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value="Verbose" />
    </switches>
    <sharedListeners>
      <add name="fileListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="XrmToolBoxConnection.log" />
      <add name="CustomListener" type="Microsoft.Xrm.Tooling.Connector.DynamicsFileLogTraceListener, Microsoft.Xrm.Tooling.Connector" BaseFileName="XrmToolBox_Connection" Location="LocalUserApplicationDirectory" MaxFileSize="52428800" />
    </sharedListeners>
  </system.diagnostics>
<appSettings>
    <add key="SkipDiscovery" value="True" />
</appSettings>
</configuration>
```

**Comment by GHSunnyGH** [comment]
not worked.
![Uploading 0.JPG…]()

**Comment by GHSunnyGH** [comment]
not worked.
![0](https://user-images.githubusercontent.com/58726489/97421850-f2188e00-1947-11eb-8c23-deb92e0234dd.JPG)

**Comment by MscrmTools** [comment]
As I don't have any possibilty to access a China env myself, I'm afraid I cannot help more here...

**Comment by GHSunnyGH** [comment]
got it, very thankful！

**Comment by MattB-msft** [comment]
@GHSunnyGH where you able to resolve this?

**Comment by GHSunnyGH** [comment]
I use the connection method "Connection String" , and set "AuthType=OAuth", it works.

**Comment by jzh24516** [comment]
> I use the connection method "Connection String" , and set "AuthType=OAuth", it works.
@GHSunnyGH can you help to share the sample connection string to connect with D365 CRM cloud service in China Region aka. 21Vianet?   It reports clientId missing.    Many Thanks.   Michael

**Comment by GHSunnyGH** [comment]
@jzh24516 

AuthType=OAuth;Username=XXXXXX@XXXXXX.partner.onmschina.cn; Password=XXXXXX;Url=https://XXXXXX.crm.dynamics.cn;AppId=XXXXXXXXXXXXXXXXX;RedirectUri =app://XXXXXXXXXXXXXXXXX;TokenCacheStorePath =d:\XXXXXX;LoginPrompt=Auto

**Comment by jzh24516** [comment]
> @jzh24516
> 
> AuthType=OAuth;Username=[XXXXXX@XXXXXX.partner.onmschina.cn](mailto:XXXXXX@XXXXXX.partner.onmschina.cn); Password=XXXXXX;Url=https://XXXXXX.crm.dynamics.cn;AppId=XXXXXXXXXXXXXXXXX;RedirectUri =app://XXXXXXXXXXXXXXXXX;TokenCacheStorePath =d:\XXXXXX;LoginPrompt=Auto

Thanks a million, will try it.

**Comment by jzh24516** [comment]
> @jzh24516
> 
> AuthType=OAuth;Username=[XXXXXX@XXXXXX.partner.onmschina.cn](mailto:XXXXXX@XXXXXX.partner.onmschina.cn); Password=XXXXXX;Url=https://XXXXXX.crm.dynamics.cn;AppId=XXXXXXXXXXXXXXXXX;RedirectUri =app://XXXXXXXXXXXXXXXXX;TokenCacheStorePath =d:\XXXXXX;LoginPrompt=Auto

I made it, thank you for your great help
