### ISSUE TITLE
Error after creating first connection, Xml Document

### ISSUE THREAD

**Issue by muhammad-naderi** [MscrmTools/XrmToolBox#956]
After downloading a clean copy and removing %AppData%\Roaming\MscrmTools\XrmToolBox
the app opens fine, how ever as soon as the wizard (any of them) for creating a connection finishes I get an error regarding creating xml of connections file

in the next run(s) I get following error on splash screen:
![xrmtoolbox](https://user-images.githubusercontent.com/8791318/84106557-ba5c8880-aa30-11ea-8535-9a15a1af720d.png)

and ofcourse the connection file seem corrupted

`<?xml version="1.0" encoding="utf-8"?>
<CrmConnections xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ByPassProxyOnLocal>false</ByPassProxyOnLocal>
  <Connections>
    <ConnectionDetail>
      <AuthType>ActiveDirectory</AuthType>
      <AzureAdAppId>00000000-0000-0000-0000-000000000000</AzureAdAppId>
      <ConnectionId>4aa209b0-93ad-4cea-a4e9-821b7e88ab4e</ConnectionId>
      <ConnectionName>Dev</ConnectionName>
      <ConnectionString>***(Removed by me)</ConnectionString>
      <IsCustomAuth>false</IsCustomAuth>
      <IsFromSdkLoginCtrl>false</IsFromSdkLoginCtrl>`

I've worked with this tool for a couple of years this error has just started, disabling the Kaspersky Antivirus did not help either.

I have this problem with latest version v1.2020.6.40

of course removing the connection file fix the issue until I create another connection

**Comment by muhammad-naderi** [comment]
this is the very first error after entering a name for newly created connection:

![xrmtoolbox2](https://user-images.githubusercontent.com/8791318/84107163-34414180-aa32-11ea-92ec-8774d27dbea8.png)

full error details:
[errordetails.txt](https://github.com/MscrmTools/XrmToolBox/files/4750026/errordetails.txt)

**Comment by MscrmTools** [comment]
Is there any special character you are aware of in the information you provided to establish the new connection?

**Comment by muhammad-naderi** [comment]
No there is not, 
Connecting to the same server since 2016

just found out v1.2019.11.35 is working file 
btw, copy and pasting connection file from v1.2019.11.35 to latest version does NOT resolve the issue

**Comment by muhammad-naderi** [comment]
The problem is from the system date settings
on Win 10 I am using Persian Calendar and this causes the issue (while filling `CrmConnections.Connections.ConnectionDetail.LastUsedOn`)
 changing windows calendar to default gregorian fixed the issue.
