### ISSUE TITLE
Connection with Home Realm Url fails although Fiddler trace shows successful authentication

### ISSUE THREAD

**Issue by mvkmuc** [MscrmTools/XrmToolBox#958]
When connecting with the external URL of an IFD we get a "Failed Login" message from the XRM Toolbox although a Fiddler trace shows that the authentication with the STS has been successfull.

"Failed login" message:
![Failed Login Message](https://user-images.githubusercontent.com/33146950/85420290-49aa8580-b573-11ea-823f-8ca92a3bff49.png)

Xrm Tollbox log file:
[XrmToolBox_Connection-2020-06-23.log](https://github.com/MscrmTools/XrmToolBox/files/4820269/XrmToolBox_Connection-2020-06-23.log)

Screenshot of the Fiddler trace showing successful authentication with returned security token:
![Response from STS with SecurityToken](https://user-images.githubusercontent.com/33146950/85420400-7068bc00-b573-11ea-8630-664430479cac.png)

**Comment by MscrmTools** [comment]
Did you try to connect using the SDK Login Control? This is to validate if the standard control from SDK can login or not.
XrmToolBox does not decide if the connection fails or not. If the connection succeeds (as it seems in the screenshot), XrmToolBox should not return an error. So something else must occurs first.

I don't have the same kind of environment for testing purpose so I can't really help more.

**Comment by MscrmTools** [comment]
any news?

**Comment by MscrmTools** [comment]
No news since two years. Closing this but can be reopen if needed
