### ISSUE TITLE
New tool still pending...

### ISSUE THREAD

**Issue by norriqkve** [MscrmTools/XrmToolBox#961]
Hey,

I submitted a new tool two weeks ago, it was rejected once for a minor issue.
It was immediately fixed and a new version was published to NuGet... but it's still Pending at the moment...
I already have done a "Force plugin update" and it is the latest version now...

When can I expect another validation run?

Kind regards.
kve

**Comment by daryllabar** [comment]
Do you know what it was rejected for?

**Comment by norriqkve** [comment]
Because we forgot to add Author info in the AssemblyInfo file

**Comment by MscrmTools** [comment]
Validation is a manual process and I’m very busy these days...
Please be patient.
Is it also your tool that receive 5 stars rating whereas it’s not even published?

**Comment by norriqkve** [comment]
That's from a friend of mine who got a sneak preview and he rated it via the xrmtoolbox.com/plugins site where the new Tool is listed as Pending.

**Comment by MscrmTools** [comment]
The tool has been approved.

As for the rating, it does not give a good feedback as it seems "you" are trying to push your plugin. Your friend should have wait that the tool is validated

**Comment by norriqkve** [comment]
If it's an issue, you can remove the rating... it doesn't matter to me.
