### ISSUE TITLE
Unhandled Exception on startup

### ISSUE THREAD

**Issue by nameless071** [MscrmTools/XrmToolBox#963]
Hi, I get an unhandled exception on startup of XRMToolbox:
************** Ausnahmetext **************
System.Net.WebException: Der Remotename konnte nicht aufgelöst werden: 'http'
   bei System.Net.HttpWebRequest.GetResponse()
   bei NuGet.RequestHelper.GetResponse()
   bei NuGet.RedirectedHttpClient.GetResponseUri(HttpClient client)
   bei NuGet.RedirectedHttpClient.EnsureClient()
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei NuGet.MemoryCache.GetOrAdd[T](Object cacheKey, Func`1 factory, TimeSpan expiration, Boolean absoluteExpiration)
   bei NuGet.RedirectedHttpClient.get_CachedClient()
   bei NuGet.RedirectedHttpClient.get_Uri()
   bei NuGet.DataServicePackageRepository.get_Context()
   bei NuGet.DataServicePackageRepository.FindPackagesById(String packageId)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
XrmToolBox
    Assembly-Version: 1.2020.6.40.
    Win32-Version: 1.2020.6.40.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/XrmToolBox.exe.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4001.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
XrmToolBox.Extensibility
    Assembly-Version: 1.2020.6.40.
    Win32-Version: 1.2020.6.40.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/XrmToolBox.Extensibility.DLL.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4150.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
Microsoft.IdentityModel
    Assembly-Version: 3.5.0.0.
    Win32-Version: 6.1.7601.24479.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/Microsoft.IdentityModel.DLL.
----------------------------------------
System.IO.Compression.FileSystem
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll.
----------------------------------------
XrmToolBox.PluginsStore
    Assembly-Version: 1.2020.6.40.
    Win32-Version: 1.2020.6.40.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/XrmToolBox.PluginsStore.DLL.
----------------------------------------
NuGet.Core
    Assembly-Version: 2.14.0.832.
    Win32-Version: 2.14.0.832.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/NuGet.Core.DLL.
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 12.0.0.0.
    Win32-Version: 12.0.3.23909.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/Newtonsoft.Json.DLL.
----------------------------------------
McTools.Xrm.Connection
    Assembly-Version: 1.2020.5.33.
    Win32-Version: 1.2020.5.33.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/McTools.Xrm.Connection.DLL.
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly-Version: 1.2020.5.33.
    Win32-Version: 1.2020.5.33.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/McTools.Xrm.Connection.WinForms.DLL.
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly-Version: 9.0.0.0.
    Win32-Version: 9.0.45.329.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/Microsoft.Xrm.Sdk.DLL.
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly-Version: 9.0.0.0.
    Win32-Version: 9.0.45.329.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/Microsoft.Xrm.Sdk.Workflow.DLL.
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly-Version: 9.0.0.0.
    Win32-Version: 9.0.45.329.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/Microsoft.Crm.Sdk.Proxy.DLL.
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.0.51.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/Microsoft.Xrm.Tooling.Connector.DLL.
----------------------------------------
Microsoft.Xrm.Tooling.Ui.Styles
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.0.51.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/Microsoft.Xrm.Tooling.Ui.Styles.DLL.
----------------------------------------
Microsoft.Xrm.Tooling.CrmConnectControl
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.0.51.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/Microsoft.Xrm.Tooling.CrmConnectControl.DLL.
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly-Version: 5.2.7.0.
    Win32-Version: 5.2.7.0.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL.
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly-Version: 3.0.6.0.
    Win32-Version: 3.0.6.0.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/WeifenLuo.WinFormsUI.Docking.DLL.
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly-Version: 3.0.6.0.
    Win32-Version: 3.0.6.0.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL.
----------------------------------------
ScintillaNET
    Assembly-Version: 3.6.3.0.
    Win32-Version: 3.6.3.0.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/ScintillaNET.DLL.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Net.Http
    Assembly-Version: 4.1.1.3.
    Win32-Version: 4.6.26907.01.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/System.Net.Http.DLL.
----------------------------------------
System.Runtime.Serialization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
----------------------------------------
SMDiagnostics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll.
----------------------------------------
System.ServiceModel.Internals
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
McTools.StopAdvertisement
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/*****/Desktop/XRMToolbox/McTools.StopAdvertisement.DLL.
----------------------------------------
System.Xml.Linq
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.ComponentModel.Composition
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll.
----------------------------------------
DamSim.SolutionTransferTool
    Assembly-Version: 1.2020.4.10.
    Win32-Version: 1.2020.4.10.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL.
----------------------------------------
DamSim.ViewTransferTool
    Assembly-Version: 1.2019.11.4.
    Win32-Version: 1.2019.11.4.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL.
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly-Version: 1.2018.6.3.
    Win32-Version: 1.2018.6.3.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL.
----------------------------------------
Javista.AttributesFactory
    Assembly-Version: 1.2019.11.2.
    Win32-Version: 1.2019.11.2.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.ATTRIBUTESFACTORY.DLL.
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly-Version: 1.2019.10.9.
    Win32-Version: 1.2019.10.9.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL.
----------------------------------------
MsCrmTools.AccessChecker
    Assembly-Version: 1.2018.7.2.
    Win32-Version: 1.2018.7.2.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL.
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly-Version: 1.2019.11.3.
    Win32-Version: 1.2019.11.3.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL.
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly-Version: 1.2019.5.3.
    Win32-Version: 1.2019.5.3.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL.
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly-Version: 1.2018.9.11.
    Win32-Version: 1.2018.9.11.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL.
----------------------------------------
MsCrmTools.AuditCenter
    Assembly-Version: 1.2019.11.2.
    Win32-Version: 1.2019.11.2.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL.
----------------------------------------
MsCrmTools.ChartManager
    Assembly-Version: 1.2017.3.1.
    Win32-Version: 1.2017.3.1.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL.
----------------------------------------
MscrmTools.CrmTraceReader
    Assembly-Version: 1.2018.4.1.
    Win32-Version: 1.2018.4.1.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CRMTRACEREADER.DLL.
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly-Version: 1.2020.2.4.
    Win32-Version: 1.2020.2.4.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL.
----------------------------------------
MscrmTools.EmailAnonymizer
    Assembly-Version: 1.2019.12.1.
    Win32-Version: 1.2019.12.1.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.EMAILANONYMIZER.DLL.
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly-Version: 1.2016.12.1.
    Win32-Version: 1.2016.12.1.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL.
----------------------------------------
MsCrmTools.FormRelated
    Assembly-Version: 1.2017.12.3.
    Win32-Version: 1.2017.12.3.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL.
----------------------------------------
MsCrmTools.Iconator
    Assembly-Version: 1.2018.7.9.
    Win32-Version: 1.2018.7.9.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL.
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly-Version: 1.2016.11.1.
    Win32-Version: 1.2016.11.1.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL.
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly-Version: 1.2020.4.13.
    Win32-Version: 1.2020.4.13.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL.
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly-Version: 1.2019.5.1.
    Win32-Version: 1.2019.5.1.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL.
----------------------------------------
MscrmTools.PortalCodeEditor
    Assembly-Version: 1.2020.5.14.
    Win32-Version: 1.2020.5.14.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL.
----------------------------------------
MscrmTools.PortalRecordsMover
    Assembly-Version: 1.2020.6.20.
    Win32-Version: 1.2020.6.20.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL.
----------------------------------------
MsCrmTools.SampleTool
    Assembly-Version: 1.2018.6.23.
    Win32-Version: 1.2018.6.23.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL.
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly-Version: 1.2020.2.12.
    Win32-Version: 1.2020.2.12.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL.
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly-Version: 1.2018.9.3.
    Win32-Version: 1.2018.9.3.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL.
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly-Version: 1.2019.5.12.
    Win32-Version: 1.2019.5.12.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL.
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly-Version: 1.2020.5.5.
    Win32-Version: 1.2020.5.5.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL.
----------------------------------------
MsCrmTools.SolutionImport
    Assembly-Version: 1.2016.8.23.
    Win32-Version: 1.2016.8.23.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL.
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly-Version: 1.2020.4.2.
    Win32-Version: 1.2020.4.2.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL.
----------------------------------------
MsCrmTools.Translator
    Assembly-Version: 1.2020.5.12.
    Win32-Version: 1.2020.5.12.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL.
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly-Version: 1.2020.4.13.
    Win32-Version: 1.2020.4.13.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL.
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly-Version: 1.2017.4.4.
    Win32-Version: 1.2017.4.4.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL.
----------------------------------------
MscrmTools.WebresourcesManager
    Assembly-Version: 2.2020.5.12.
    Win32-Version: 2.2020.5.12.
    CodeBase: file:///C:/USERS/*****/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
WindowsBase
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll.
----------------------------------------
System.Web
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4075.0 built by: NET48REL1LAST.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll.
----------------------------------------
System.Design
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll.
----------------------------------------
MetadataViewProxies_fe3445de-6d48-4efc-be4e-d52420872c33
    Assembly-Version: 0.0.0.0.
    Win32-Version: 4.8.3752.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
System.Xaml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll.
----------------------------------------
System.Data.Services.Client
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Services.Client/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Services.Client.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------

In the first sentence, it says remote name could not be resolved.

I already did the steps resetting XRMToolbox from your web page, as well as addiontionally deleting the folder created in ProgramData.
What seems strange is, that the installed plugins that I am constantly deleting in the folder are back on startup of the application, so it seems that nothing I will do will have an impact.

I tried starting up on different networks (with/Without proxy) and starting the application on a remote desktop that I opened from my PC.  I don't know if I forgot to do anything.

If someone has got an idea on what I could try next, that would be great.

Thanks!
Florian

**Comment by MscrmTools** [comment]
What seems strange to me is that the error occurs when XrmToolBox is searching for tools update (I guess, because the stack trace does not show where the error comes from). 
But there is no way the url is simply "http"

**Comment by nameless071** [comment]
Yes, that is indeed strange. Is there any way to completely clear anything (plugins, etc.)? 
They are being loaded at startup, even though I cleared the Plugins folder in Appdata/Roaming.

**Comment by MscrmTools** [comment]
Maybe AppData/Roaming is not where the plugins are stored. You can confirm this by opening Settings, then go to Path tab and click on storage folder to open the appropriate folder where Plugins, Settings and everything should be

**Comment by nameless071** [comment]
Yes, it should be there. It is very strange, as if there were some kind of chache or something sililar.

**Comment by CREFaulk** [comment]
I have the same issue. I can't ignore the error and run anything either or I get another error. IE Enhanced security configuration is not active. I can access the XrmToolBox web page from the Windows client with no problems.
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
`

If I try to run any plugin I get an error "An error occurred when trying to display this tool: Unable to cast object of type 'Microsoft.Xrm.Tooling.Connector.CrmServiceClient' to type 'Micrsofot.Xrm.Sdk.Client.OrganizationServiceProxy'.

I don't see any installation instructions beyond removing the protection option from the zip file. Any suggestions on how to install a working Xrm ToolBox? I just downloaded v1.2020.6.40 and tried to run it on Windows Server 2012 R2 where CRM 2015 is installed.

**Comment by nameless071** [comment]
Hi @CREFaulk , 
I just did another test. Deleting everything as described in the instructions and running CCleaner after it. Restart PC and run CCleaner again. After that, it seems to work for now. I restarted the PC just to check and it still works.
Hope this helps you.

**Comment by MscrmTools** [comment]
@CREFaulk Which tool leads to this error? It is generally due to tool not respecting XrmToolBox best practices

**Comment by CREFaulk** [comment]
> Hi @CREFaulk ,
> I just did another test. Deleting everything as described in the instructions and running CCleaner after it. Restart PC and run CCleaner again. After that, it seems to work for now. I restarted the PC just to check and it still works.
> Hope this helps you.

I will try a more of a clean install by looking for related files and registry entries. Maybe one of them is wrong.

**Comment by CREFaulk** [comment]
> @CREFaulk Which tool leads to this error? It is generally due to tool not respecting XrmToolBox best practices

All I tried but the first was the Ribbon Manager. After that I just tried any of them. I installed the toolbox on another client and had no issues but for something like the Ribbon Manager which publishes to CRM I really want a local connection. I'll try a clean install. I know older versions of the toolbox worked at one point on the CRM server itself.

**Comment by MscrmTools** [comment]
There is no such tool Ribbon Manager, not validated at least. If you are talking about Ribbon Workbench, then I suggest to update it to latest version using the Tool Library

**Comment by CREFaulk** [comment]
Yes, it is the "Ribbon Workbench"

**Comment by MscrmTools** [comment]
So I am quite sure its author did everything to make it compatible. Juste use latest version of XrmToolBox and RibbonWorkbench and you should be good

**Comment by MscrmTools** [comment]
Closing the issue since no answer from @CREFaulk 
Please reopen if the problem still happens
