### ISSUE TITLE
Website documentation MFA connection update

### ISSUE THREAD

**Issue by Barabazs** [MscrmTools/XrmToolBox#964]
I'm not sure where I should file an issue about the documentation on https://www.xrmtoolbox.com.

On [Connecting to an environment](https://www.xrmtoolbox.com/documentation/for-users/connecting-to-an-organization/) there is a paragraph concerning MFA which tells the user to create an Azure Application ID etc. Although this might be true, it is much easier to create an app password with this procedure: [Manage app passwords for two-step verification](https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords)

**Comment by MscrmTools** [comment]
I never used them with XrmToolBox...

Would you be able to right a simple procedure using it with XrmToolBox so that I can add it in XrmToolBox website?

**Comment by Barabas-dev** [comment]
No problem. I'll look into it.

Is there a link between the docs in the wiki and the website?

**Comment by MscrmTools** [comment]
No, I need to remove the doc on the wiki which is completly outdated
