### ISSUE TITLE
XrmToolBox crash after creating the Organization Proxy.

### ISSUE THREAD

**Issue by amadeus128** [MscrmTools/XrmToolBox#965]
I use the current version of XrmToolBox (v1.2020.6.40) which worked fine until yesterday. Since today I have a strange problem: 
I can start the program without problems, but when I connect to a CRM organization it works at first, but after 3~5 seconds the program closes itself. In the status bar I could still read that the Organization service proxy was created successfully, then the program closes without any further message.

I have completely deleted the MscrmTools folder in Roaming and downloaded the application fresh.

The organization I am connecting to is an OnPremise organization with IFD.

So far it has always worked great.

In the event log of my computer I could find the following two entries:

![Error1](https://user-images.githubusercontent.com/68429397/87788485-bb59b480-c83d-11ea-82bd-1aa6f154be9c.png)

![Error2](https://user-images.githubusercontent.com/68429397/87788500-c44a8600-c83d-11ea-8da7-ab7069e1eefe.png)

Is this a problem with my computer or .NET installation or a problem with XrmToolBox?

Greeting,
amadeus

**Comment by MscrmTools** [comment]
If everything has always worked correctly with this version of XrmToolBox and it does not work anymore since few days, I think the problem is not really with XrmToolBox but with something that changed on your computer.
It will be very difficult for me to help you
