### ISSUE TITLE
Cannot update my Plugin

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/XrmToolBox#966]
Hi,

I have a plugin "Solution Layer Removal", I did an up[date for it and push it to NuGet, but I'm getting the error "this tool has not been developed specifically to support the latest breaking changes version of XrmToolBox...", I make sure that I have updated all packages, then republish it, still getting the error
![image](https://user-images.githubusercontent.com/12459798/90316991-4e6a3500-df37-11ea-8352-a295d3622d81.png)
![image](https://user-images.githubusercontent.com/12459798/90317007-6346c880-df37-11ea-8656-2d7e50c105df.png)

**Comment by daryllabar** [comment]
I think you need to list the XrmToolBox nuget package as a dependency for you nuget package.  You only list the Xrm.connection package

**Comment by aboodh95** [comment]
Hi @daryllabar l,

Thanks, that resolved the problem
