### ISSUE TITLE
Nothing can be show in page of XrmToolBox

### ISSUE THREAD

**Issue by zclam** [MscrmTools/XrmToolBox#967]
I can see anything in page until today.So how to use this tool?Thanks in advance
![image](https://user-images.githubusercontent.com/46147793/91957824-23565280-ed39-11ea-8e86-7f9b20a4ea9d.png)

i've reinstalled before and restart WINDOWS,but it can't work!
The steps as follows:
Remove the folder of XrmToolBox,Delete content of folder C:\users\appData\your_login\Roaming\MscrmTools\XrmToolBox,and Unzip the XrmToolBox.zip
---
- Deployment: Online
- DB Version: 9.1.0.21936
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40

**Comment by rappen** [comment]
Perhaps an issue for @markmpn who is the creator of that tool?
https://github.com/MarkMpn/Sql4Cds/issues

**Comment by MarkMpn** [comment]
@zclam Does this only affect SQL 4 CDS, or other tools as well?

**Comment by zclam** [comment]
> @zclam Does this only affect SQL 4 CDS, or other tools as well?

All including Start page.

**Comment by MscrmTools** [comment]
This is an issue with the screen density as far as I can tell
