### ISSUE TITLE
Issue with localization of Form names

### ISSUE THREAD

**Issue by EugenePavlikov** [MscrmTools/XrmToolBox#97]
Example:
Base language - English (1033)
Additional language - Russian (1049)
Default user language - English

1. Create form with name "Form Name" for any entity
2. Export form name translation with Easy Translator
3. For 1049 change form name to "Form Name from Easy Translator" (for example)
4. Import translation with Easy Translator
5. Publish customizations

As a results:
1. All users, with any default language, will see "Form Name from Easy Translator" as a form name
2. If you try to export translation again, for 1049 translation will be empty, for 1033 will be "Form Name from Easy Translator"

System export/import translation works fine for me.

**Comment by MscrmTools** [comment]
Hi,
You are right. Retrieval of labels were updated lately and update had not been implemented.

The fix will be available in next release or if you are a developer, you can get it through Github today
