### ISSUE TITLE
error "Object reference not set to an instance of an object." when using Entity Security Role and selecting Retrieve Entities

### ISSUE THREAD

**Issue by dgayle218** [MscrmTools/XrmToolBox#970]
Getting error "Object reference not set to an instance of an object." when using Entity Security Role and selecting Retrieve Entities
[error using Entity Security Role.pdf](https://github.com/MscrmTools/XrmToolBox/files/5221156/error.using.Entity.Security.Role.pdf)

---
- Deployment: Online
- DB Version: 9.1.0.21949
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40

**Comment by MscrmTools** [comment]
This is not one of my tool. Please contact the author directly.
I just have his blog... http://dotnetdeveloper2012.blogspot.com/2018/04/dynamics-crm-entity-security.html?m=1
