### ISSUE TITLE
[BUG] Easy translation doesn't import attributes and global option sets

### ISSUE THREAD

**Issue by Stepsn** [MscrmTools/XrmToolBox#971]
Hello, thanks for the great job!!

**Describe the bug**
Easy translation doesn't import attributes and global option sets

**To Reproduce**
Import the excel file 

**Expected behavior**
Everything should be imported at the end of the process

**Screenshots**
![image](https://user-images.githubusercontent.com/71352627/93265357-d480d200-f7a8-11ea-8837-097cf43c774a.png)

**Desktop (please complete the following information):**
 - XrmToolbox 1.2020.6.40
 - Tool version 1.2020.7.13

**Additional context**
Connected to a sandbox environnement Dynamics wave 2  9.1.0000.22837

**Comment by MscrmTools** [comment]
Fixed in latest version
