### ISSUE TITLE
System connecting to environment not specified by the "Organization url"

### ISSUE THREAD

**Issue by mmixxerr** [MscrmTools/XrmToolBox#972]
Hello,

When setting up a connection I specify envAlpha.crm.dynamics.com in the Organization url and seemingly connect and authenticate successfully, but down at the bottom of the XrmToolBox window it shows envBravo.crm.dynamics.com. Looking at the actual logs and saved connection info in ConnectionsList.Default.xml, it indeed connected to envBravo.api.crm.dynamics.com. See below for snippets from XrmToolBox Connection .log and ConnectionList xml. This appears to be caused by some issue with disco.crm.dynamics.com sending back the wrong information.

I'm wondering if XrmToolBox should catch things like this as it seems pretty dangerous (if it even is possible to catch as I am not familiar enough with how the whole process works).

**Pic of UI:** https://imgur.com/a/F3FUtCp 

**ConnectionList.Default.xml snippet:**
`<Organization>ZuluCorp</Organization>
<OrganizationDataServiceUrl>https://envBravo.api.crm.dynamics.com//XRMServices/2011/OrganizationData.svc</OrganizationDataServiceUrl>
<OrganizationFriendlyName>ZuluCorp Sandbox</OrganizationFriendlyName>
<OrganizationServiceUrl>https://envBravo.api.crm.dynamics.com/XRMServices/2011/Organization.svc</OrganizationServiceUrl>
<OrganizationUrlName>ZuluCorp</OrganizationUrlName>
<OrganizationVersion>9.1.0.22251</OrganizationVersion>
<OriginalUrl>https://envAlpha.crm.dynamics.com</OriginalUrl>`

**XrmToolBox_Connection-2020-09-26.log**
`Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Verbose   16   9/26/2020 1:12:48 PM  Initialize CRM connection Started - AuthType: Office365
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Information    8   9/26/2020 1:12:48 PM  Using User Specified Server 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Information    8   9/26/2020 1:12:48 PM  DiscoverOrganizations - Initializing Discovery Server Object with https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Verbose   16   9/26/2020 1:12:48 PM  DiscoverOrganizations - attempting to connect to CRM server @ https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Verbose   16   9/26/2020 1:12:49 PM  DiscoverOrganizations - created CRM server proxy configuration for https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc - duration: 00:00:00.8907152
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Verbose   16   9/26/2020 1:12:49 PM  DiscoverOrganizations - proxy requiring authentication type : OnlineFederation 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Verbose   16   9/26/2020 1:12:50 PM  DiscoverOrganizations - Authenticated via OnlineFederation. Auth Elapsed:00:00:01.1811215
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Verbose   16   9/26/2020 1:12:50 PM  DiscoverOrganizations - service proxy created - total create duration: 00:00:02.0740129
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Information    8   9/26/2020 1:12:50 PM  DiscoverOrganizations - Discovery Server Get Orgs Call Complete - Elapsed:00:00:00.2816496
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Information    8   9/26/2020 1:12:50 PM  Found 2 Org(s)
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Information    8   9/26/2020 1:12:50 PM  Looking for Organization = envAlpha in the results from CRM's Discovery server list.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Information    8   9/26/2020 1:12:50 PM  found User Org = envAlpha in results
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Verbose   16   9/26/2020 1:12:50 PM  DiscoveryServer indicated organization service location = https://envBravo.api.crm.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Information    8   9/26/2020 1:12:50 PM  Organization Service URI is = https://envBravo.api.crm.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Verbose   16   9/26/2020 1:12:50 PM  ConnectAndInitCrmOrgService - Initializing Organization Service Object
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Information    8   9/26/2020 1:12:50 PM  ConnectAndInitCrmOrgService - Requesting connection to Organization with CRM Version: 9.1.0.22251
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Information    8   9/26/2020 1:12:50 PM  ConnectAndInitCrmOrgService - Using ISerivceManagement
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Verbose   16   9/26/2020 1:12:50 PM  ConnectAndInitCrmOrgService - attempting to connect to CRM server @ https://envBravo.api.crm.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Verbose   16   9/26/2020 1:12:51 PM  ConnectAndInitCrmOrgService - created CRM server proxy configuration for https://envBravo.api.crm.dynamics.com/XRMServices/2011/Organization.svc - duration: 00:00:00.4546756
Microsoft.Xrm.Tooling.Connector.CrmServiceClient   Verbose   16   9/26/2020 1:12:51 PM  ConnectAndInitCrmOrgService - proxy requiring authentication type : OnlineFederation`

---
- Deployment: Online
- DB Version: 9.1.0.22251
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40

**Comment by MscrmTools** [comment]
I guess we already saw this kind of behavior for organization that had been renamed with a name previously used by another organization.
Might it be your case?

**Comment by mmixxerr** [comment]
Correct and it appeared to be caused by envBravo's "Unique Name" (under Instance Referenc Information) being literally "envAlpha". After we deleted envBravo, XrmToolBox started connecting just fine to envAlpha. Obviously, I'm using psuedonyms for the environments. The names were more like envAlpha="CompanyName" and envBravo="CompanyNameSandbox".

This was all part of a tenant migration which went like this:
1. envAlpha was created in the new tenant.
2. envCharlie from the old tenant was migrated to the new tenant, overwriting envAlpha (I'm not sure if the Microsoft team deleted envAlpha and then moved envCharlie into place or overwrote). envBravo already existed in the new tenant for testing purposes which was a sandbox copy of envCharlie while it was in the original tenant.
3. "envCharlie", now in the new tenant, was renamed to "envAlpha".

So maybe what you are really connecting to when you type in a domain like _envAlpha_.crm.dynamics.com is actually "Unique Name".crm.dynamics.com according to disco and the "envAlpha" and "Unique Name" do not have to be the same. Then the question is can XrmToolbox even catch this discrepancy and should it? Maybe this is really rare, but dangerous IMO.

**Comment by MscrmTools** [comment]
I guess the issue is more on MS side since I'm just using what the user tells me (the org url) and MS assemblies do all the connection process.
So I guess nothing I can handle in XrmToolBox
