### ISSUE TITLE
Solution Components Mover: add "Installed On" sortable column or make solution names searchable [Improvement]

### ISSUE THREAD

**Issue by partridgetim** [MscrmTools/XrmToolBox#975]
When I use Solution Components Mover, I'm often moving components from a recently created solution to a newly created solution but our environments often have many solutions and patches to wade through.
I'd love for a "Installed On" column to be added that is sortable, or for the solution name to be searchable so I could easily find or filter to my recently created solutions. Thanks for considering.

**Comment by MscrmTools** [comment]
That would be a nice addition. I will work on it

Thanks for the suggestion

**Comment by ChrisMilton** [comment]
@MscrmTools, I would love to contribute to this project and give this enhancement a try. Do you mind if I create a PR for this?

**Comment by MscrmTools** [comment]
Sure! Any help is welcomed as I'm quite busy these days

**Comment by ChrisMilton** [comment]
Thanks! I have created a new [Pull Request](https://github.com/MscrmTools/MsCrmTools.SolutionComponentsMover/pull/9) containing the changes

**Comment by MscrmTools** [comment]
Thanks! I will review it tomorrow
