### ISSUE TITLE
Login to Dynamics CRM 365 on premise secured with Azure MFA

### ISSUE THREAD

**Issue by tkammerlander** [MscrmTools/XrmToolBox#979]
Dear xrmtoolbox team,

i have a question, is it also possible to connect to an on premise dynamics crm 365 via ifd url which is secured with a local adfs server which performs azure aad mfa?

if so is there a tutorial somewhere?

regards, Thomas

**Comment by MscrmTools** [comment]
Wow! That's a specific scenario... I have no idea if it's possible or not.
Try using SDK login control to check if this is possible with MS control

**Comment by tkammerlander** [comment]
Thanks for the info ill let you know the outcome :-)

**Comment by tkammerlander** [comment]
We did test everything and we were able to login with a custom on prem c# application. we had to register an adfs client on our local adfs server. xrmtoolbox did not work just yet.

**Comment by MscrmTools** [comment]
When I was talking about SDK login client, I was referring to one of the connection method available:
![image](https://user-images.githubusercontent.com/10774317/96116458-c5488d80-0ee8-11eb-9a4e-4f04a9aa88f9.png)

Does it work with this connection method?

**Comment by tkammerlander** [comment]
No the SDK Login Client does not work. What i guess would be necessary would be that you include a dummy client app id for this specific logon scenario and a field for a callback url that adfs redirects to after authentication. the admin then has to register that client app id on his local adfs server and grant permissions to access the relying party identifier of his crm installation.

**Comment by MscrmTools** [comment]
ok, so SDK login control is the official Microsoft control to connect. So I guess that means that even MS does not handle correctly this scenario.
Without an access to this kind of env and your custom c# application, that will be difficult to implement in XrmToolBox

**Comment by MattB-msft** [comment]
Actually, We do handle this. 
MFA is an JWT/OAuth flow.  If you register on your ADFS Server **and authorize** the default tools AppID ( [here ](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/deploy/post-installation-configuration-guidelines-dynamics-365#configure-the-oauth-provider)) you should be able to connect using the On-Premise | OAuth flow.

**Comment by MscrmTools** [comment]
Thank you @MattB-msft for jumping in, I must admit I don't have any knowledge on this kind of auth configuration

**Comment by MattB-msft** [comment]
@tkammerlander did this get sorted for you?  if not can you let us know whats going on?

**Comment by tkammerlander** [comment]
Hy @MattB-msft  sorry iam really busy these days but ill try to reply as soon as possible. at the end everything works for our custom app but i was not able to test it yet for the xrmtoolbox.

**Comment by MscrmTools** [comment]
@tkammerlander any news?

**Comment by MattB-msft** [comment]
@tkammerlander   Poking here... Can you close this if your Good to go?

**Comment by tkammerlander** [comment]
fixed with registering custom app id ill come back when i have more time for a more detailed description. THxxxx to everyone helping
