### ISSUE TITLE
Metadata Document Generator plug-in install error: 403 Forbidden

### ISSUE THREAD

**Issue by Customery** [MscrmTools/XrmToolBox#982]
I have installed the latest version of XrmToolBox and I'm trying to install the Metadata Document Generator tool 1.2019.5.1.

After the tool is downloaded, I get an error from the installer: "An error occurred: The remote server returned an error: (403) Forbidden.

**To Reproduce**
Open XrmToolBox 1.2020.10.41
Install Metadata Document Generator 1.2019.5.1

**Expected behavior**
Other tools have installed successfully, and I was expecting Metadata Document Generator to install.

**Screenshots**
![image](https://user-images.githubusercontent.com/20672898/96667975-78a7fb00-139d-11eb-9928-02939948fa0e.png)

**Desktop (please complete the following information):**
XrmToolBox 1.2020.10.41
Metadata Document Generator 1.2019.5.1
Windows Server 2016 remote desktop via Citrix with no local admin privileges

**Additional context**

**Comment by MscrmTools** [comment]
@Customery Looking at the screenshot, it seems that latest version is already installed. Am I wrong?

**Comment by Customery** [comment]
Yes, it was downloaded and installed today. As fresh as can be!


Neil Benson
Managing Director
Brisbane, QLD, Australia
Tel: +61 484 322 232
Email: neil.benson@customery.com
Web: customery.com
Brisbane (AEST) is UTC+10
Become a Customery Insider

**Comment by MscrmTools** [comment]
So, there is no issue anymore right?
