### ISSUE TITLE
issue connecting to Teams Environment (Oakdale)

### ISSUE THREAD

**Issue by PZSchotenGVDW** [MscrmTools/XrmToolBox#985]
[Write your comment/feedback/issue here]
 Hi, 

I'm trying to make a connection through the SDK Login Control to connect to an environment behind a Teams site (Oakdale)

When I click 'SDK login control' and fill in all the data ,MFA starts and  I get a correct overview of all the environments but when I try to connect I get an error saying I can not connect. 

Is there an issue with Team environments  ?

Kind regards,

Gunter
---
- Connection Controls Version: 1.2020.10.35
- XrmToolBox Version: 1.2020.10.41

**Comment by MscrmTools** [comment]
I must admit I never tried to connect with project Oakdale before and I don't know the capability there

I will try to understand if there is something specific

**Comment by MscrmTools** [comment]
Got the answer.
There is no API access to Project Oakdale (see [this blog article](https://powerapps.microsoft.com/en-us/blog/a-closer-look-at-data-platform-capabilities-in-project-oakdale/)) so this is the expected behavior
