### ISSUE TITLE
Cannot Impersonate with SDK Login Control

### ISSUE THREAD

**Issue by cmbswim89** [MscrmTools/XrmToolBox#986]
After successfully connecting to one of our orgs XrmToolBox will not let me Impersonate any user. I validated I have the correct permissions for impersonating and validated that the connection is valid and can query records from our org. The Impersonate button is greyed out and won't let me click on it at all.

**Comment by MscrmTools** [comment]
Button is activated based on information retrieved from the connection when connecting. 
Code is checking if user has a role assigned that has the privilege prvActOnBehalfOfAnotherUser

**Comment by MscrmTools** [comment]
Can you try again with this updated assembly?

[McTools.Xrm.Connection.zip](https://github.com/MscrmTools/XrmToolBox/files/5511043/McTools.Xrm.Connection.zip)

**Comment by ccellar** [comment]
Works for me with the updated assembly

**Comment by MscrmTools** [comment]
Ok, I will push a new version of connection controls globally with this fix

**Comment by cmbswim89** [comment]
Thank you the file above fixed the issue.
