### ISSUE TITLE
[Improvement] Offer Auto Paging to developers: _pluginContext.service.RetrieveMultiple 

### ISSUE THREAD

**Issue by seanmcne** [MscrmTools/XrmToolBox#988]
**Describe the solution you'd like**
Tools are being limited to 5000 users, instead of having every single developer know how to page or request paging. 

**Describe alternatives you've considered**
Many tool authors aren't expecting more than a certain # of users or max 5000 users. 

**Additional context**
Many tool authors aren't thinking any customer would have more than 5000 users, this is a repeated issue. 

With a similar extension built into the plugin you can help your developers (or even assume they automatically want all rows): 
https://github.com/seanmcne/XrmCoreLibrary/blob/8c30ccc80daf785305d48847148555ddde507a6f/v9/Extensions/ServiceExtensions.cs#L218

**Comment by rappen** [comment]
Interesting idea.
Curious though - why/how is this specific to `users`?
An extension like that would of course work for any entity, what is your specific "problem" since you are explicitly referencing users?

**Comment by seanmcne** [comment]
Yep it would apply to any entity but I have run into several toolbox addins that need to load systemusers and choke after the first 5000. This seems to be a common area where developers miss foreseeing an issue that negates the usefulness of their addin (arguably a narrow use case) but we have found a Boolean and "Max" int optional set of parameters let developers just shoot for a max number (or all) results without having to do any tricky paging (which may not always be obvious). 

Feel free to re-use the linked extension methods if they're helpful 😀

**Comment by MscrmTools** [comment]
We can definitively provide an extension to allow this autopaging but tool developers will still need to implement it

**Comment by MattB-msft** [comment]
@seanmcne we could always just add it to the Cds/crmServiceClients @seanmcne

**Comment by seanmcne** [comment]
@MattB-msft, I like that even better - let's definitely discuss, are you accepting PR's?  :)

**Comment by MattB-msft** [comment]
On the internal feeds, not on git at this time
/r me and I can set you up :)

________________________________

**Comment by MscrmTools** [comment]
closing the thread
