### ISSUE TITLE
Connection issue with latest .NET SDK installed

### ISSUE THREAD

**Issue by ahmadpirani** [MscrmTools/XrmToolBox#989]
So I was working with CRM online for a while yesterday morning. Later I had a need to install latest .NET SDK. However, that broke XRM Toolbox ability to connect to any CRM org.

Uninstalling all .NET frameworks greater than 4.7.1 resolved the issue.

The error was "you do not have access to any CRM online orgs".

---
- Deployment: Online
- DB Version: 9.1.0.24647
- Connection Controls Version: 1.2020.10.35
- XrmToolBox Version: 1.2020.10.41

**Comment by MattB-msft** [comment]
the underlying SDK Clients ( provided by Microsoft ) required either .net framework 4.6.2+
that said, there are known issues with .4.7.1, which is nolonger supported by Microsoft as it was superseded by .net 4.7.2 which corrects the issue. 

My recommendation for full framework would be to stick with .net 4.6.2, 4.7.2, or .4.8

**Comment by MscrmTools** [comment]
Thank you @MattB-msft
