### ISSUE TITLE
Unable to Login to Dynamics CRM

### ISSUE THREAD

**Issue by befaes** [MscrmTools/XrmToolBox#990]
Since 18/11/2020 afternoon all previously working Connections to Dynamics 365 CRM appear no longer working. An Error is received "Invalid Login Information... Unable to Login to Dynamics CRM" (as in the image below). Colleagues experience the same issue. Found on the web a similar post of another user, same timing. Not sure what could be done to overcome this issue. Suggestions are welcome :)
![image](https://user-images.githubusercontent.com/54271681/99671957-119c6580-2a73-11eb-933a-ee975abb1c0c.png)

---
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.10.41

**Comment by MattB-msft** [comment]
@befaes ,  Are you using the SDK Login control or one of the other methods?

**Comment by befaes** [comment]
Hi, I'm using the Connection Wizard

**Comment by befaes** [comment]
Great, it is working via an SDK Login Control connection and next Office 365 with default settings (instead of the earlier Connection Wizard connections which stopped working). Thanks @MattB-msft !

**Comment by MscrmTools** [comment]
@befaes Connection Wizard use Office 365 authentication that relies on WS-TRUST which is deprecated and eventually removed by Microsoft (or your IT service, don't know the details). That should explain why connection wizard does not work anymore. You can also use Oauth authentication method
