### ISSUE TITLE
Use local folder when running in Debug config/folder

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#991]
When testing/debugging tools during development we always have to add `/overridepath:.` or similar.
Wouldn't it be great if XTB detected debug configuration (which might be difficult since it's only the tool that's in debug configuration) or that it is running from a `/bin/Debug` folder and then default to current folder for storage?

---
- Deployment: Online
- DB Version: 9.1.0.25245
- Connection Controls Version: 1.2020.10.35
- XrmToolBox Version: 1.2020.11.42

**Comment by MscrmTools** [comment]
Not sure it's a good idea. 
If someone wants to test overridepath switch when exe is in a debug folder, it will not be able to if we force this

**Comment by rappen** [comment]
You've got a point.
