### ISSUE TITLE
XRMToolbox fails after connecting to instance

### ISSUE THREAD

**Issue by BSuycott** [MscrmTools/XrmToolBox#992]
After upgrading on Nov 30th to latest release, when I attempt to connect the system appears to connect but then the XRMToolbox abends and closes.  When setting up connections they test out under both connection string and under OAuth/MFA (have been using this tool for years) but now I cannot run any of the tools as post connection the XRMToolbox itself fails.  What steps can be taken to help determine the cause of this as we really need this tool running.

---
- Connection Controls Version: 1.2020.10.35
- XrmToolBox Version: 1.2020.11.42

**Comment by MscrmTools** [comment]
Hi @BSuycott, is there any error message or XrmToolBox is just crashing?

**Comment by BSuycott** [comment]
No message, just closes.  The connection tests all look good when setting up.  Then when actually connecting it gets connected then shuts down.  Any recommendations on logs or other areas to look at that I can provide you to inspect?

**Comment by MscrmTools** [comment]
Never faced this behavior and there is no additional log I'm thinking of...

Any change on your computer except the upgrade? 
Do you run XrmToolBox the standard way or are you using a specific location for file storage (using switch /overridepath)?

**Comment by BSuycott** [comment]
Everything worked fine before doing the upgrade on Monday afternoon.  No changes to my laptop.
Our laptops are locked down by our company policy, so before I can try to load a previous version I will need to schedule with our tech team to unlock my computer.  I am thinking perhaps that I need to completely clear out the old implementation and try installing again – just want to make sure I know what to remove (all directories, etc.).  Can you tell me what directories I need to clear out to make sure it is all cleaned?

**Comment by Jani-P** [comment]
I did download that latest version 1.2020.11.42.  Connection did test success and was saved too. After that trying any tool, xrmtoolbox did close without any warning. 

I added shortcut with overridepath to different location. As a result. Opening  Xrmtoolbox did gave a notice that there is a update available. I think it said  .37. ? now I did update from there. After that open connection and tool did stay open. Tthere were no plugins installed. I did select one and it worked. Also toolbox without override path did open with those default plugins.  
Hope that helps others too

**Comment by MattB-msft** [comment]
Given you said that your laptop is 'locked down' 
You may want to look in your application or system event log and see if the XrmToolbox was blocked from loading due to a signing or policy reason.

**Comment by BSuycott** [comment]
Older  version of XRMToolbox work fine, only the new version causes the issue of loading and then once connection is established does it terminate with no error message.

**Comment by rappen** [comment]
I recall @MscrmTools mentioning that a recent release accidentally wasn't signed - have you tried with the current latest (1.2021.1.44) which should be properly signed?

**Comment by MscrmTools** [comment]
@BSuycott is it still an issue with latest release?

**Comment by BSuycott** [comment]
It is not failing in the last several releases.
________________________________
