### ISSUE TITLE
Cannot connect, exception System.String not found

### ISSUE THREAD

**Issue by rafastryk** [MscrmTools/XrmToolBox#993]
I'm not able to connect to my D365 environment. Connection Wizard throws an Exception "System.MissingMethodException System.String not found"
![Image 7](https://user-images.githubusercontent.com/5776080/100787936-ac525800-3414-11eb-90a3-4f98a6935f7e.png)

---
- Connection Controls Version: 1.2020.10.35
- XrmToolBox Version: 1.2020.11.42

**Comment by MscrmTools** [comment]
This error means old version of Microsoft assemblies are used instead of the ones shipped with XrmToolBox.
The most likely cause of this is old version of Microsoft assemblies in your global assembly cache. Remove them and you should be good
