### ISSUE TITLE
Possibility to group connections ?

### ISSUE THREAD

**Issue by ameed** [MscrmTools/XrmToolBox#994]
As consultants, we are usually working with a number of clients in different times, this means the connection list grows to a number of different tentants / environments. It would bring more ease of use, if connections could be grouped in the drop-up in left footer, so one could make some sort of grouping of connections ?

---
- Connection Controls Version: 1.2020.10.35
- XrmToolBox Version: 1.2020.11.42

**Comment by rappen** [comment]
Are you working with connection files?
That will reflect even in the dropup.

![image](https://user-images.githubusercontent.com/2572253/100887518-58e41680-34b5-11eb-9f3b-4dcba3741d1a.png)

Tutoral on connection files: http://jonasr.app/xtb-school/conn

**Comment by MscrmTools** [comment]
As @rappen said, it already exists

**Comment by ameed** [comment]
Hi, thanks for guidance, i have just restructured all my connections based on clients, and that really helps. 
Though i wonder if it could be possible to make groups with subgroups within ?  ... for example, making root group for Client, then for User Based connections, and within there each environment etc. For an idea, could this be solved by adding windows subfolders ?
