### ISSUE TITLE
ISettingsPlugin interface

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#995]
Many many MANY tools have their own settings.
How nice would it be to have a common entry point to access those settings?
Very nice!

![image](https://user-images.githubusercontent.com/2572253/100894806-29390c80-34bd-11eb-805d-0a84680ed075.png)

Suggestion is to implement a `ISettingsPlugin` interface that works just like the `IAboutPlugin` interface.

**Comment by MscrmTools** [comment]
Why not!
What method would be available in that interface?

**Comment by rappen** [comment]
If a tool implements the `ISettingsPlugin` interface, a menu option just like the About menu option should appear in XTB.

![image](https://user-images.githubusercontent.com/2572253/100896151-9c8f4e00-34be-11eb-8929-1dbcc44a9687.png)

And the interface would look something like this:
```
namespace XrmToolBox.Extensibility.Interfaces
{
    public interface ISettingsPlugin
    {
        void ShowSettings();
    }
}
```

Clicking the menu option would call `ShowSettings`.
