### ISSUE TITLE
Calling other tools with NewInstance=true doesn't work

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#996]
It works in the sense that a new instance of the tool is opened, but then the first opened instance is getting the target argument and the focus.
Self-assigning, I will fix 🙂

---
- Deployment: Online
- DB Version: 9.1.0.25551
- Connection Controls Version: 1.2020.10.35
- XrmToolBox Version: 1.2020.11.42

**Comment by MscrmTools** [comment]
Thank you Jonas!
